### ISSUE TITLE
[Feature Request]: Add PostgreSQL

### ISSUE THREAD

**Issue by avr** [beyondcode/herd-community#1]
### Feature Description

It would be great if you could add the PostgreSQL PDO driver for PHP.

### Is this feature valuable for other users as well and why?

Yes. I believe other Laravel users who use PostgreSQL in production would value a local development environment with Postgres.

**Comment by sebastiaanluca** [comment]
Ran into this too. The site mentions PostgreSQL and DBngin, so assumed it was included.

Btw, the "support" link refers to https://github.com/beyondcode/herd-website which gives a 404.

**Comment by sawirricardo** [comment]
@avr can you please specify the title to be [Feature Request]: Add PostgreSQL extension so that it can be clearer?

**Comment by sineld** [comment]
+1 

I have reinstalled Valet as the PostgreSQL driver is currently not supported.

**Comment by adilimudassir** [comment]
+1

**Comment by sineld** [comment]
Please see:

https://github.com/beyondcode/herd-community/issues/9

**Comment by sawirricardo** [comment]
Something like this? Herd's `php.ini`
```
extension="/opt/homebrew/lib/php/pecl/20220829/php_pgsql.so"
```

**Comment by sineld** [comment]
Download this two files.

https://ufile.io/umszq70p
https://ufile.io/blihbd5g

Put anyhere on your device and link to it in php.ini file:

# sineld
extension="/Users/sineld/somewhere/Herd/php/8.2/extensions/pgsql.so"
extension="/Users/sineld/somewhere/Herd/php/8.2/extensions/pdo_pgsql.so"

**Comment by sawirricardo** [comment]
unable to load dynamic extensions

**Comment by sineld** [comment]
> unable to load dynamic extensions

Make sure you've given correct urls. Working for me.

**Comment by sawirricardo** [comment]
did you do this?
```
sudo killall nginx-arm64 dnsmasq-arm64 \
php74-fpm \
php80-fpm \
php81-fpm \
php82-fpm \
php83-fpm
```

**Comment by sineld** [comment]
Valet is already installed, I've just stopped it.

`valet stop`

After altering phpi.ini file you should stop/start Herd.

**Comment by sawirricardo** [comment]
oh, are you using intel or `Apple Sillicone` architecture? Mine is using Silicone

**Comment by sineld** [comment]
Intel i9

**Comment by sawirricardo** [comment]
That makes sense, it doesnt workout for me. How do you get that extension by the way?

**Comment by sineld** [comment]
An old version of MAMP PRO was installed on my Mac. I took extensions from there.

**Comment by servetsarica** [comment]
> Download this two files.
> 
> https://ufile.io/umszq70p https://ufile.io/blihbd5g
> 
> Put anyhere on your device and link to it in php.ini file:
> 
> # sineld
> extension="/Users/sineld/somewhere/Herd/php/8.2/extensions/pgsql.so" extension="/Users/sineld/somewhere/Herd/php/8.2/extensions/pdo_pgsql.so"

Worked for me thanks.

**Comment by avr** [comment]
The files from @sineld didn't work for me. After trying a bunch of various options to build the extensions on my own, I was finally able to get the extensions relevant to my computer by using MacPorts. There is a port for PHP 8.2 here: https://ports.macports.org/port/php82-postgresql/details/ (and ports for 7.3, 7.4, 8.0, etc, etc)

Here are the steps:

- Install MacPorts
- Run `sudo port install php82-postgresql`
- Run `port contents php82-postgresql` -> this will give you the file paths of `pdo_pgsql.so` and `pgsql.so`
- Copy + Paste these file paths into Herd's `php.ini`

Optional (this is working for me)

- Move the `*.so` files to a directory of your choice
- Follow [this guide](https://guide.macports.org/#installing.macports.uninstalling) to remove MacPorts

@mpociot - Since loading these extensions through Herd's `php.ini` seems to work, I think this can be marked resolved.

**Comment by dwightwatson** [comment]
Ideally Herd would just support Postgres - having to grab those extensions yourself using Homebrew or Macports sort of defeats the purpose. I think it is still worth considering out of the box much like MySQL support is.

**Comment by sawirricardo** [comment]
It's coming https://twitter.com/marcelpociot/status/1682674800341180416?s=46&t=DV4aGvxfuWAaxq3QwH_kSg

**Comment by avr** [comment]
If you haven't seen this update: https://twitter.com/marcelpociot/status/1683462872007954435

Worked perfectly. Thanks again, @mpociot

**Comment by sineld** [comment]
Quick update did the work. Thanks.
