### ISSUE TITLE
[Bug]: It doesn't start PHP

### ISSUE THREAD

**Issue by smartbos** [beyondcode/herd-community#10]
### Operating system version

macOS Monterey 12.6.1 (M1)

### Herd Version

1.0.8

### PHP Version

PHP 8.2

### Bug description

After fresh install, PHP was not initiated and the log message can be seen in the attached image..

![Screen Shot 2023-07-21 at 4 59 34 PM](https://github.com/beyondcode/herd-community/assets/6157033/39780432-b3db-46f7-b335-efd9732df16e)

### Steps to reproduce

Just install.

**Comment by mpociot** [comment]
Is the username in your screenshot the same one as the one you used to install Herd? Looks like there's a permission issue somehow

**Comment by smartbos** [comment]
Yes it's same. 
I also suspect this may be a permission issue due to using a laptop that reflects the company's security policy. So this seems to be a personal issue, so I'm going to close the issue.

**Comment by carnevalle** [comment]
I have the same issue. Ventura 13.4 (Intel) @mpociot @smartbos

**Comment by carnevalle** [comment]
Ok, I resolved this issue. 

I changed the group from `staff `to `admin` In the file `~/Library/Application Support/Herd/config/fpm8.2-fpm.conf`

My user wasn't in the staff group. I don't know why Herd installed with this group?

@mpociot

**Comment by jjsanderson** [comment]
This worked for me too, and resolved the issue I had in #44. For others' reference, the fix was to amend lines in the `[herd]` block:

```
group = admin
...
listen.group = admin
```

Restart servers, and I'm back up with my previously-Valet-served sites running through Herd.

**Comment by carlituxman** [comment]
> This worked for me too, and resolved the issue I had in #44. For others' reference, the fix was to amend lines in the `[herd]` block:
> 
> ```
> group = admin
> ...
> listen.group = admin
> ```
> 
> Restart servers, and I'm back up with my previously-Valet-served sites running through Herd.

This work, but when I change to other active php version (Use PHP X.X option) then the ./config/fpm/X.X-fpm.conf changes the group and listen.group to "staff" again
