### ISSUE TITLE
[Bug]: unknown host

### ISSUE THREAD

**Issue by holicow** [beyondcode/herd-community#100]
### Operating system version

macOs Ventura 13.4.1 (c)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.1.2 (Build 13(

### PHP Version

PHP 8.2.8 (cli) (built: Jul 28 2023 13:55:05) (NTS)

### Bug description

Every day I suddenly get the following error.  I have to restart my mac.  It is the only way to get Herd working again.

Unknown Host

Description: Unable to locate the server requested --- the server does not have a DNS entry. Perhaps there is a misspelling in the server name, or the server no longer exists. Double-check the name and try again.

![CleanShot 2023-08-04 at 11 00 28](https://github.com/beyondcode/herd-community/assets/4534192/eb6b79b1-4092-4b7b-ac7b-e8d6efcdda09)

### Steps to reproduce

Nothing, I am developing and suddenly this happens.  It happens almost daily.

**Comment by mpociot** [comment]
Which application type is this? I guess that's not a Laravel app

**Comment by holicow** [comment]
Yes, a laravel app.

**Comment by mpociot** [comment]
Do you know where this error is coming from? It's not from Herd itself.
Could you share the response headers when you get the error?

**Comment by holicow** [comment]
No, I do not know where the error is coming from.  I cannot get to the server so I am unclear how to get the response headers. 

However, if I run PHP artisan serve then I can reach the site.

Basically, I just get failed to load resource: the server responded with a status of 500 [Cannot find the server.]

**Comment by holicow** [comment]
I just ran laravel new test-app.  Created a new site, no changes.  I cannot reach it if I do HTTP://test-app.test with Herd running.
But with PHP artisan serve, I can reach it at HTTP://127.0.0.1:8000

**Comment by mpociot** [comment]
Would be interesting to see which HTTP headers you get when it fails. It seems like this issue isn't even coming from nginx that ships with Herd, but from a different Webserver entirely

**Comment by holicow** [comment]
Yes possible.  I quit herd, removed it from my login items.  Then restarted my mac and I have the same problem with just using Valet.  So unlikely to be a HERD issue.  We can close this issue if you prefer.

**Comment by mpociot** [comment]
Yeah, I don't think this issue is Herd related I'm afraid.

**Comment by binbyz** [comment]
same problem here.
every process is good.
`ping http://asdf.test` cannot resolve host. (Unknown host)

**Comment by mpociot** [comment]
Do you have the test file in /etc/resolvers?
There could be an issue when you uninstall Valet after installing Herd, as Valet deletes a file that Herd requires.

**Comment by binbyz** [comment]
@mpociot 

- `/etc/resolvers` doesn't exists.
- `/private/etc/resolvers`/ directory exists.

**Comment by mpociot** [comment]
Ah sorry, I meant `/etc/resolver` without the "s".

Does it contain any files?

**Comment by binbyz** [comment]
yes like this!

![Screenshot by Dropbox Capture](https://github.com/beyondcode/herd-community/assets/17328737/8ef8bcd2-26bd-44d4-9831-936d2aed45f3)

**Comment by luca-dellorto** [comment]
Same problem for me.
Everything is ok but:
ping to `asdf.test` resolve to `198.18.2.1`
If i go to `127.0.0.1` i get Herd homepage correctly.

**Comment by diegoldev** [comment]
Hi Team! Is there any fix for this issue? I'm having same issue as @luca-dellorto
