### ISSUE TITLE
[Bug]: Warning: Undefined global variable $__herd_closure

### ISSUE THREAD

**Issue by andyunleashed** [beyondcode/herd-community#1003]
### Platform

macOS

### Operating system version

macOS 15.0 (24A335)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.11.0 (Build: 33)

### PHP Version

PHP 8.3.11

### Bug description

When disabling all of the dump options or disabling interceptions via the toolbar button the app crashes out with the below:

> Warning: Undefined global variable $__herd_closure in MyAppPath/bootstrap/app.php on line 22
> 
> Fatal error: Uncaught Error: Value of type null is not callable in MyAppPath/bootstrap/app.php:22 Stack trace: #0 /public/index.php(16): require_once() 
#1 /Applications/Herd.app/Contents/Resources/valet/server.php(167): require('MyAppPath...') 
#2 {main} thrown in ~/bootstrap/app.php on line 22

With the interceptions enabled, there are no errors or exceptions being logged at all.

This issue does not occur on PHP 8.2

### Steps to reproduce

Basic herd install, no changes to the PHP configuration, just selecting PHP 8.3 as the version.

Then disabled interceptions or uncheck all options for logging.

### Relevant log output

```shell
> Warning: Undefined global variable $__herd_closure in MyAppPath/bootstrap/app.php on line 22
> 
> Fatal error: Uncaught Error: Value of type null is not callable in MyAppPath/bootstrap/app.php:22 Stack trace: #0 /public/index.php(16): require_once() 
#1 /Applications/Herd.app/Contents/Resources/valet/server.php(167): require('MyAppPath...') 
#2 {main} thrown in ~/bootstrap/app.php on line 22

With the interceptions enabled, there are no errors or exceptions being logged at all.
```

**Comment by mpociot** [comment]
Could you check if the FPM 8.3 instance was successfully restarted?
When toggling the dump interception or unchecking the logging options, we need to restart FPM in order to apply the changes.

I would assume that this (for some reason) didn't work for you.

Could you retry this after (Force) stopping all Herd services?
You can do that by holding down the option key when you click on the menubar icon.

**Comment by mpociot** [comment]
Hm yeah maybe. Can you trigger the error again when toggling the dump interception?

I'll make sure that the FPM services always get (forcefully) stopped in this scenario so that you can't run into this issue 👍

**Comment by andyunleashed** [comment]
Toggling interception now doesn't seem to trigger the issue - the only thing I can think that may have caused it, is that I left all log options enabled when running hundreds of tests through the system previously, maybe it caused it to choke from stress? I'm running them at the moment over and over to see if I can get it to repeat the problem.

**Comment by mpociot** [comment]
Yeah, for some reason Herd was unable to properly restart FPM which causes the error to show up.

Some background explanation:
Under the hood, the new dump interception feature makes use of a custom PHP extension. When the interception is disabled, we basically need to reload FPM to clear the opcache.

I'll fix this in the next update so that any FPM processes always get killed. Thanks for reporting this 👍

**Comment by andyunleashed** [comment]
Great stuff thanks for replying so quick with a fix and the planned update :)

**Comment by kevinpickett** [comment]
I am having the same issue today. (Mac, Herd 1.11.0 Build 33)

**A few more details to add:**

The force stop and start of services only resolves the issue if the network checkbox is unchecked. I am able to trigger the same issue again reliably 100% of the time, even after the force stop and start whenever checking/un-checking the network checkbox. I am making a GET request to a 3rd party service outside of my control.

![Screenshot 2024-09-19 at 9 24 20 AM](https://github.com/user-attachments/assets/b303dd7f-928f-4d92-a70f-6a4e7450a2f9)

**Comment by mpociot** [comment]
@kevinpickett when the network checkbox is checked, we add an event listener that listens for Http facade events - we don't actually modify anything on the outgoing request. 

So you have an error as soon as you enable watching for outgoing http requests?

**Comment by mpociot** [comment]
Ohhhh now I get it! This will be fixed in the next release - sorry if this caused any confusion.

**Comment by kevinpickett** [comment]
@mpociot No stress on my end, thanks Marcel! I just appreciate the heck out of what you all are building here 🙏🏻

**Comment by mpociot** [comment]
This is now fixed in Herd 1.11.1

**Comment by datashaman** [comment]
Seeing this on Herd 1.13.0 Build 37.

**Comment by mmoollllee** [comment]
And me on 1.14.1 PHP 8.2.27
Closing and reopening Herd fixes this temporarily

**Comment by mpociot** [comment]
When does this error occur for you?
Toggling the dump watcher on / off could previously cause this error.

**Comment by JoeriE** [comment]
Having the same issue on PHP8.3 and Herd 1.21.2
Is there any solution? Force restart won't work.
