### ISSUE TITLE
[Bug]: Empty dump window content

### ISSUE THREAD

**Issue by maxcelos** [beyondcode/herd-community#1004]
### Platform

macOS

### Operating system version

Sonoma 14.6.1

### System architecture

Intel (x86)

### Herd Version

1.11.0

### PHP Version

8.2

### Bug description

Dumps window has counters updated but display no content.

![CleanShot 2024-09-18 at 11 02 10](https://github.com/user-attachments/assets/276069cb-2dca-4713-97b1-816c226d2cb4)

### Steps to reproduce

Just add some dump() or dd() anywhere and run the application

**Comment by mpociot** [comment]
Does this only occur when dumping/logging some specific output?

Or do you also get this when you simply have a new route that just does `dd("test");`?

**Comment by maxcelos** [comment]
Looks like the content doesn't matter. Just tired with simple string in a fresh Laravel 11 project.

Works in:
- Simple web route (function), 
- Inside controller
- In a class method instantiated in controller

Doesn't work:
- Commands (works if I call the command in a web route, but not via terminal)
- Listeners
- Jobs

Note: Used php artisan queue:listen in job tests

**Comment by mpociot** [comment]
@maxcelos I'm unable to reproduce this - could you maybe push a demo repository somewhere?

Are you sure that you are using Herd's `php` binary in the CLI? 
You can check this by running `which php` 

You can also verify this by running `php -r "var_dump(extension_loaded('herd'));"`

**Comment by maxcelos** [comment]
Yeah, my setup is entirely based on Herd.

Today that same test project started showing the dumps again.

From last week to now, I don't remember doing any change. But we can close this issue since its was probably just something in my end. 

Thanks for the attention.
