### ISSUE TITLE
[Bug]: Can't access my .test websites

### ISSUE THREAD

**Issue by clausbertels** [beyondcode/herd-community#1008]
### Platform

macOS

### Operating system version

macOS Sequoia 15.0

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.11

### Bug description

This is my first experience with Laravel/herd. 

Everything appears fine - Nginx, DNSMasq and FPM are green, but the *.test URL's don't return my sites. I just get "Safari can't find the server".

Things do work when I manually edit the hosts file and point 127.0.0.1 to any specific .test URL. But I don't want to do that for every new site. Or is that a requirement?

In parallel to [this issue](https://github.com/beyondcode/herd-community/issues/674) I assumed it was a permissions problem. I gave full disk access to Herd in system settings and I gave write permission to everyone on the hosts file. I'm the admin user. I have another non-admin account on this laptop that I also use for work.

**Comment by mpociot** [comment]
Can you try and ping any local sites, such as `ping foo.test`?

You should have a file called `/etc/resolver/test` with this content:

```
nameserver 127.0.0.1
```

And the dnsmasq service should be running: `sudo ps aux | grep dnsmasq`

**Comment by clausbertels** [comment]
> Can you try and ping any local sites

`ping: cannot resolve starterkit-main.test: Unknown host`

> You should have a file called `/etc/resolver/test` with this content:

Exists and has that content.

> And the dnsmasq service should be running

```
nobody             321   0,0  0,0 34435552   4216   ??  Ss    2:36pm   0:00.07 /usr/local/opt/dnsmasq/sbin/dnsmasq --keep-in-foreground -C /usr/local/etc/dnsmasq.conf -7 /usr/local/etc/dnsmasq.d,*.conf
Claus            13733   0,0  0,0 410723856   1536 s000  S+    4:04pm   0:00.00 grep dnsmasq
```

**Comment by mpociot** [comment]
Ahh @clausbertels that's the issue!
You have another dnsmasq process running, which is not the one managed by Herd!

I assume this is still managed by homebrew and does not use the configuration that Herd needs.
Try stopping it manually via:

```
sudo brew services stop dnsmasq
```

**Comment by clausbertels** [comment]
I did have dnsmasq running in brew. I stopped it, but it didn't resolve the issue. I tried logging out, restarting and even reinstalling Herd as a hail mary.

`brew services list`
```
Name    Status User File
dnsmasq none        
php     none        
unbound none        
```

**Comment by clausbertels** [comment]
I've been troubleshooting with ChatGPT for hours - I know, I'm sorry - and the only thing that came up was that `/Users/Claus/Library/Application Support/Herd/config/valet/Nginx/ ` is empty on my system. Chich it says it's not supposed to be.

**Comment by clausbertels** [comment]
Issue solved! I don't fully understand the reason, but I do think it's interesting to know @mpociot.

I had Adguard's custom DNS profile installed https://adguard-dns.io/en/public-dns.html (method 2). Removing it resolved my issue. Is there a way to use it in conjunction with Herd?

**Comment by fschroiff** [comment]
@clausbertels thanks for mentioning this!! I had a DNS configuration profile from NextDNS installed, once I removed it Herd worked fine.
