### ISSUE TITLE
[Bug]: All .test websites return 500 status

### ISSUE THREAD

**Issue by greenspace10** [beyondcode/herd-community#1009]
### Platform

Windows

### Operating system version

Windows 11 (10.0.22631 Build 22631)

### System architecture

Windows

### Herd Version

1.11.0

### PHP Version

8.*

### Bug description

Just updated to Herd 1.11.0 and now none of my sites are accessible.

I can ping them, and there are no logs I can find.

### Steps to reproduce

On windows update herd to 1.11.0

**Comment by mpociot** [comment]
Can you share a screenshot from the error page?

**Comment by greenspace10** [comment]
not sure what happened but after reinstalling and multiple reboots, it seems to be working again.
