### ISSUE TITLE
[Bug]: Vapor file uploads - $_ENV not populated from .env

### ISSUE THREAD

**Issue by timredbullet** [beyondcode/herd-community#1010]
### Platform

macOS

### Operating system version

macOS Sonoma Version 14.3.1

### System architecture

Intel (x86)

### Herd Version

1.11.0 (Build: 33)

### PHP Version

PHP 8.2.16 (cli) (built: Feb 16 2024 00:30:02) (NTS)

### Bug description

We have an application hosted on Laravel Vapor. From the Laravel Vapor documentation we're using the `Vapor.store` method to stream files to s3.

When attempting to upload a file locally, the application responds with the following error:
Unable to issue signed URL. Missing environment variables: AWS_BUCKET, AWS_DEFAULT_REGION, AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY

This is triggered from the following method on vapors `SignedStorageUrlController`:
```
    protected function ensureEnvironmentVariablesAreAvailable(Request $request)
    {
        $missing = array_diff_key(array_flip(array_filter([
            $request->input('bucket') ? null : 'AWS_BUCKET',
            'AWS_DEFAULT_REGION',
            'AWS_ACCESS_KEY_ID',
            'AWS_SECRET_ACCESS_KEY',
        ])), $_ENV);

        if (empty($missing)) {
            return;
        }

        throw new InvalidArgumentException(
            'Unable to issue signed URL. Missing environment variables: '.implode(', ', array_keys($missing))
        );
    }
```

When checking the output of `$_ENV` on the command line using tinker no environment settings are injected despite Laravel's documentation claim leading to the error above:

> All of the variables listed in the .env file will be loaded into the $_ENV PHP super-global when your application receives a request. However, you may use the env function to retrieve values from these variables in your configuration files.

### Steps to reproduce

1. Install the Vapor NPM Package:
```
npm install --save-dev laravel-vapor
```

2. Within your applications app.js file initialize the global Vapor javascript object:
```
// Vite
import Vapor from 'laravel-vapor'
window.Vapor = Vapor

// Mix
window.Vapor = require('laravel-vapor');
```

3. Ensure UserPolicy exists
```
php artisan make:policy UserPolicy --model=User
```

4. Add the following method to your UserPolicy:
```
public function uploadFiles(User $user)
{
    return true;
}
```

5. Set your AWS environment credentials in the `.env` file.

6. Attempt to upload a file, we're using Vue:
```
<input type="file" id="file" ref="file">

Vapor.store(this.$refs.file.files[0], {
    progress: progress => {
        this.uploadProgress = Math.round(progress * 100);
    }
}).then(response => {
    axios.post('/api/profile-photo', {
        uuid: response.uuid,
        key: response.key,
        bucket: response.bucket,
        name: this.$refs.file.files[0].name,
        content_type: this.$refs.file.files[0].type,
    })
});
```

**Comment by mpociot** [comment]
@timredbullet this would also mean that a `dd($_ENV);` does not show you the content of your `.env` variables, which does not really make sense to me.
Maybe this was a cache related issue?
I can see al .env variables being populated in $_ENV just fine.

**Comment by timredbullet** [comment]
@mpociot I've just checked and this specific project/repository I'm working with does not have the application env data available in the `$_ENV` output.

Tinker also confirms:

```
Psy Shell v0.12.4 (PHP 8.2.16 — cli) by Justin Hileman
> $_ENV['APP_URL']

   WARNING  Undefined array key "APP_URL".

= null

>
```

I've cleared my application cache, not sure what else to do? I checked another project of mine which doesn't use laravel vapor and this shows the environment variables inside the `$_ENV` output in tinker.

**Comment by mpociot** [comment]
Is there anything else that's modified in your application?
I just tried to reproduce this by running:

```
laravel new vapor-test
cd vapor-test
composer require laravel/vapor-core --update-with-dependencies
```

And then running dd($_ENV); in tinker, which shows all of the variables.

Can you verify that this is also the case for you when you create a new application? 
Then I assume that this is somehow related to your specific codebase 🤔

**Comment by timredbullet** [comment]
@mpociot yes that looks good. Apologies, it looks like I was using an older version of phpdotenv

```
composer require vlucas/phpdotenv
```

Fixed the issue for me now, I can see the application variables within the `$_ENV` output now.

Apologies and thanks for the support/help, appreciate it.
