### ISSUE TITLE
[Bug]: Updating Herd resets "Launch at login"

### ISSUE THREAD

**Issue by hebbet** [beyondcode/herd-community#1013]
### Platform

Windows

### Operating system version

11 23H2

### System architecture

Intel (x86)

### Herd Version

1.11.0

### PHP Version

8.3

### Bug description

After updating one of my PCs to 1.10.0 i noticed that after restarting the PC herd didn't launch automatically. 

the same happend with 1.11.0

Before Update on 1.11.0
![image](https://github.com/user-attachments/assets/6ad4b927-3a57-48a8-86bb-3d265c264aa8)

after Update on 1.11.0
![image](https://github.com/user-attachments/assets/ce0e1850-7944-4156-82d3-7d17a9842932)

### Steps to reproduce

install older herd version

upgrade to the latest.

**Comment by hebbet** [comment]
with update to 1.11.1 i had the same issue.

so it was not fixed with next-release.

**Comment by mpociot** [comment]
Yeah, but it won't happen in future updates because of the fix in 1.11.1 🙂

**Comment by hebbet** [comment]
i have the issue again on my two PCs, after updating to 1.12.0 and to 1.13.0 on windows the checkboxed where still checked, but only after i removed the check and re added it, it startup works again

**Comment by hebbet** [comment]
that is still happing, after upgrading to 1.14.0
