### ISSUE TITLE
[Bug]: Deploying won't work (wordpress site)

### ISSUE THREAD

**Issue by torriv83** [beyondcode/herd-community#1018]
### Platform

Windows

### Operating system version

Windows 11

### System architecture

Intel (x86)

### Herd Version

1.11.0

### PHP Version

8.2

### Bug description

I'm just testing the deploy feature in herd. I'm trying to deploy a wordpress site, but it only stays on loading (red dots moving). not able to click on cancel. need to close the windows for it to dissapear. 

Not sure if this is a bug, or if it's not even possible to deploy a non laravel project. 

the site is on digital ocean.

**Comment by mechelon** [comment]
Can you check in Forge if there was a deployment attempt? 🤔

**Comment by torriv83** [comment]
I can't find any logs indicating there was a deployment attempt. In forge, on my laravel apps, i have a "Deployment" menu item, but this is not in my wordpress app.

**Comment by sschlein** [comment]
If that's the case, it's not possible to deploy a WordPress site and we need to verify what the Forge API returns in these scenarios.

**Comment by torriv83** [comment]
ok. To be able to deploy wordpress sites would be akiller feature and make my life much easier in those projects. 

Anyways, thanks for the answers.
