### ISSUE TITLE
[Bug]: Herd CRASHING.

### ISSUE THREAD

**Issue by Mace12409** [beyondcode/herd-community#1022]
### Platform

Windows

### Operating system version

Windows 11

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

Newest

### PHP Version

maybe 8.2

### Bug description

When ever I try to open herd it does not open I killed it in task manager and try to open it and it still not opening can someone help me?

**Comment by mechelon** [comment]
Depending on your settings, Herd might only live in your menu bar - can you check there?
If that doesn't solve it, can you share your Herd logs found in `%USERPROFILE%\AppData\Roaming\Herd\logs\main.log`?
