### ISSUE TITLE
[Bug]: I can't use PostgreSQL with Herd on Windows 11, Herd 1.11.0

### ISSUE THREAD

**Issue by ahajicek07** [beyondcode/herd-community#1023]
### Platform

Windows

### Operating system version

Windows 11 Pro 10.0.22631 Build 22631

### System architecture

Intel (x86)

### Herd Version

1.11.0

### PHP Version

PHP 8.3

### Bug description

I can't use PostgreSQL with Herd, it was working, but when I updated to the latest version I can't run it anymore. When I try to turn on PostgreSQL services it turns back to red with error log.

### Steps to reproduce

I've tried to delete and reinstall the service, and it doesn't work.

### Relevant log output

```shell
Starting PostgreSQL (PostgreSQL) on port 5432 with datapath 7ab49abb-5c94-4232-ab07-466157cf5d56Execution of PostgreSQL by a user with administrative permissions is not
permitted.
The server must be started under an unprivileged user ID to prevent
possible system security compromises.  See the documentation for
more information on how to properly start the server.
```

**Comment by mechelon** [comment]
Can you try to force-quit all PostgreSQL services and then restart, as shown in the screenshot?

![CleanShot 2024-09-23 at 08 30 52](https://github.com/user-attachments/assets/6b7a833d-4dde-4f30-96a7-d3bcc37a642f)

**Comment by ahajicek07** [comment]
So I got it to work on 1 of 2 computers. My home computer worked by start herd and not using, "run as administrator" but it doesn't work on my work computer as a way to get this to work.

So I did the force quit, and deleted the service and tried to reinstall the PostgreSQL and it gives me this error 

"Herd was unable to setup the service. Please check your log files and try again."

![PostgreSQL-Install-Error](https://github.com/user-attachments/assets/f836cdc7-f007-4564-a22c-7671a184306c)

Then I get the same error when I try to start it in the error log:

"Starting PostgreSQL (PostgreSQL) on port 5432 with datapath 52d6303c-63e9-4786-b0fe-292c45b38928Execution of PostgreSQL by a user with administrative permissions is not
permitted.
The server must be started under an unprivileged user ID to prevent
possible system security compromises.  See the documentation for
more information on how to properly start the server."

**Comment by mpociot** [comment]
@ahajicek07 but you are not running Herd as an Administrator, right?

**Comment by ahajicek07** [comment]
@mpociot I was able to get it to work on my work machine. This was the difference, where-as on my home machine fit fixed things to just run herd without explicitly clicking 'run as administrator' by right clicking herd and clicking 'run as administrator,' at work, because its on a 'work domain' and my user is an 'administrator' I had to right click herd and click 'Run as a different user' and login to a new user that isn't my default at work 'administrator,' Doing that I can't access the user folder I currently have my projects, but I'll just move them. Hopefully this fixes things for now since I can now run PostgreSQL.

P.S. Thank you for helping me with this, and beyond excited for what you're doing with dumping all the variables on the laravel error page you've been demo'ing on Laravel. Would be a huge productivity boost when working through new code.

**Comment by InfinityXTech** [comment]
Same issue here, without cahnging the user, only thing that helped was to install pg outside of herd.

**Comment by tamr** [comment]
> Same issue here, without cahnging the user, only thing that helped was to install pg outside of herd.

Or you can run it with limited privileges:

```
runas /trustlevel:0x20000 "C:\Program Files\Herd\Herd.exe"
```

**Comment by darwin-buelo** [comment]
> > Same issue here, without cahnging the user, only thing that helped was to install pg outside of herd.
> 
> Or you can run it with limited privileges:
> 
> ```
> runas /trustlevel:0x20000 "C:\Program Files\Herd\Herd.exe"
> ```

 This works on my machine

**Comment by raalejandre89** [comment]
> > Same issue here, without cahnging the user, only thing that helped was to install pg outside of herd.
> 
> Or you can run it with limited privileges:
> 
> ```
> runas /trustlevel:0x20000 "C:\Program Files\Herd\Herd.exe"
> ```

This also worked for me
