### ISSUE TITLE
[Bug]: Windows Integrations UI Dark Mode Issue

### ISSUE THREAD

**Issue by OscarKolsrud** [beyondcode/herd-community#1035]
### Platform

Windows

### Operating system version

Windows 10 pro 22H2 19045.4894

### System architecture

Windows

### Herd Version

1.11.0

### Bug description

See attached image. There are UI Colour issues on the list page of the integrations.

![image](https://github.com/user-attachments/assets/52cdf29b-a79e-4f75-abc6-41422b19a606)

### Steps to reproduce

Integrations page on Windows with dark mode in system settings enabled

**Comment by mpociot** [comment]
This is now fixed in Herd 1.11.1
