### ISSUE TITLE
[Bug]: Cannot Uninstall Herd / Fresh Install

### ISSUE THREAD

**Issue by studiotwo68** [beyondcode/herd-community#1039]
### Platform

macOS

### Operating system version

macOS Sonoma 14.7

### System architecture

Intel (x86)

### Herd Version

1.11.0

### PHP Version

PHP 8.3

### Bug description

Morning. Herd had been previously installed on my MacBook (under my user). I have been through all steps within the official uninstall procedure several times. But, after re-installing, the OnBoarding wizard does not run. Herd does load, but it doesn't create any sites. So, my question is, how do I get the OnBoarding wizard to run? Or, is there something missing within the uninstall instructions? 

### Steps to reproduce

https://herd.laravel.com/docs/1/troubleshooting/uninstalling

**Comment by mpociot** [comment]
Maybe the privileged helper tool is still installed.
You can remove it by running:

```
sudo /Library/PrivilegedHelperTools/de.beyondco.herd.helper uninstall
```

**Comment by studiotwo68** [comment]
@mpociot thank you so much Marcel. That worked perfectly!!

**Comment by danwall** [comment]
Looks like this note never made it to the documentation, but it is required to fully uninstall Herd and trigger the onboarding upon reinstallation.
