### ISSUE TITLE
[Feature Request]: Make Settings Window resizeable

### ISSUE THREAD

**Issue by jansgescheit** [beyondcode/herd-community#104]
### Feature Description

The settings window has a static size and should be manually resizable.

### Is this feature valuable for other users as well and why?

The users have something from it to not have to scroll at the stove paths if there are more than four entries.

For the sites it would be helpful if you could drag the window more in the width to see the URL and the paths.

**Comment by mpociot** [comment]
Making the window resizable is actually quite complicated - but we will improve the default width/the way we display paths 👍
