### ISSUE TITLE
[Bug]: `post_max_size` should be automatically updated based on `upload_max_filesize`

### ISSUE THREAD

**Issue by adevade** [beyondcode/herd-community#1041]
### Platform

Windows

### Operating system version

Windows 11

### System architecture

Windows

### Herd Version

1.11.0 PRO

### Bug description

When defining the **Max File Upload Size** in PHP Settings, I think `post_max_size` should be updated as well. Either to the same value, or something a bit bigger. Now it seems to be hard coded to 8M.

![image](https://github.com/user-attachments/assets/f9c115a9-ffb2-442d-b2a2-9293b8eb26bf)

**Comment by mpociot** [comment]
This is now fixed in Herd 1.11.1
