### ISSUE TITLE
[Bug]: can't start Reverb

### ISSUE THREAD

**Issue by rozvinen** [beyondcode/herd-community#1043]
### Platform

macOS

### Operating system version

12.4

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.11.0 

### Bug description

Reverb can't start
log:
Warning: require(/Users/Shared/Herd/services/reverb/1.x/vendor/autoload.php): Failed to open stream: No such file or directory in /Users/Shared/Herd/services/reverb/1.x/artisan on line 18

Fatal error: Uncaught Error: Failed opening required '/Users/Shared/Herd/services/reverb/1.x/vendor/autoload.php' (include_path='.:') in /Users/Shared/Herd/services/reverb/1.x/artisan:18
Stack trace:
#0 {main}
  thrown in /Users/Shared/Herd/services/reverb/1.x/artisan on line 18

ls reverb dir:
README.md	bootstrap	database	resources	tests
__MACOSX	composer.json	package.json	routes		vite.config.js
app		composer.lock	phpunit.xml	storage
artisan		config		public		test

### Steps to reproduce

add new service - broadcasting - Reverb - save default form

**Comment by mpociot** [comment]
When the Reverb service gets initialized, it should automatically run `composer install` for you. Maybe that didn't work for whatever reason.

Please manually run `composer install` in your Reverb service directory (/Users/Shared/Herd/services/reverb/1.x/).
Afterwards you can start Reverb from the app UI.

**Comment by camelinuk** [comment]
I also face the same problem. after I changed directory (cd /User/Shared/Herd/services/reverb/1.x/),  and tried to  composer install, system shows the error here:

`
>>  composer install
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - nette/schema is locked to version v1.3.0 and an update of this package was not requested.
    - nette/schema v1.3.0 requires php 8.1 - 8.3 -> your php version (8.4.3) does not satisfy that requirement.
  Problem 2
    - brianium/paratest is locked to version v7.4.3 and an update of this package was not requested.
    - brianium/paratest v7.4.3 requires php ~8.2.0 || ~8.3.0 -> your php version (8.4.3) does not satisfy that requirement.
  Problem 3
    - league/config is locked to version v1.2.0 and an update of this package was not requested.
    - league/config v1.2.0 requires nette/schema ^1.2 -> satisfiable by nette/schema[v1.3.0].
    - nette/schema v1.3.0 requires php 8.1 - 8.3 -> your php version (8.4.3) does not satisfy that requirement.

`

So, I tried to use ''' composer update '''

it just works fine for me.

`
   INFO  Discovering packages.  

  laravel/reverb .............................................................................................................................. DONE
  laravel/sail ................................................................................................................................ DONE
  laravel/sanctum ............................................................................................................................. DONE
  laravel/tinker .............................................................................................................................. DONE
  nesbot/carbon ............................................................................................................................... DONE
  nunomaduro/collision ........................................................................................................................ DONE
  nunomaduro/termwind ......................................................................................................................... DONE
  pestphp/pest-plugin-laravel ................................................................................................................. DONE
  spatie/laravel-ignition ..................................................................................................................... DONE

97 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
`

**Comment by sloan58** [comment]
For me this was because I haven't installed any php/composer dependencies on my OS.  I'm trying to keep everything in Herd or docker/sail.  If you're in this situation you can use docker to install the composer dependencies.

```bash
cd /Users/Shared/Herd/services/reverb/1.x
docker run --rm -it -v .:/app -w /app serversideup/php:8.3-cli composer install
```
