### ISSUE TITLE
[Bug]: Everytime herd download's php 8.3 on start

### ISSUE THREAD

**Issue by parth391** [beyondcode/herd-community#1049]
### Platform

macOS

### Operating system version

macOS Sequoia 15.0

### System architecture

Intel (x86)

### Herd Version

1.11.0 (Build: 33)

### PHP Version

PHP 8.3.12

### Bug description

PHP 8.3.12 (latest version) is already installed. Herd is still downloading and installing the same PHP version. It takes almost 5 minutes to complete the process, every time mac reboots.

<img width="957" alt="Screenshot 2024-09-30 at 1 18 54 PM" src="https://github.com/user-attachments/assets/64daaa23-0ace-45a9-9cd2-52cf01c7c94c">
<br/><br/>
The second issue is "system password", which also is being asked every time on mac reboots.

<img width="819" alt="Screenshot 2024-09-30 at 3 29 02 PM" src="https://github.com/user-attachments/assets/c52f22f4-b446-4981-a6a5-3f092859339c">
<br/><br/>
I tried to remove completely and reinstall herd, this didn't help me. But now a new issue comes up, i can't install NVM.

https://github.com/user-attachments/assets/84169107-525f-46de-bb45-2dac76a8a6da

**Comment by mpociot** [comment]
https://herd.laravel.com/docs/1/troubleshooting/common-issues#herd-shows-the-welcome-screen-on-every-start

Please make sure that you allow the helper service to run in the background.

**Comment by parth391** [comment]
Ok, now i have enabled herd to run in background. But still, i am unable to install nvm.
