### ISSUE TITLE
[Bug]: "Add site" dialog freezes keeping opening and closing the modal

### ISSUE THREAD

**Issue by mattiadelfranco** [beyondcode/herd-community#1052]
### Platform

macOS

### Operating system version

macOS Sonoma 14.1 23B2073

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.11.1 (Build: 34)

### Bug description

When i click on "Add Site" button, the software enters in a loop where the "Choose a template for your new site" keeps opening and closing, at this point I can't interact anymore with the software and i need to force close the Herd.

This is making me unable to add a new site and using Herd.

Actually I don't have any site added to Herd, so it's possible that this bug affects only fresh installation without any site added.

I'm using Herd Pro.

### Steps to reproduce

1) Start Herd
2) Open the "Sites" window
3) Click on "Add site" button

**Comment by mpociot** [comment]
Do you have any parked sites configured?

![CleanShot 2024-10-01 at 13 51 13@2x](https://github.com/user-attachments/assets/45760b5d-9a4d-4142-9689-60d214576d64)

**Comment by stefandroog** [comment]
Same issue. Just started with Herd...

**Comment by phaybein** [comment]
I have a fresh install and experiencing the same matter

Apple M2 Max | 14.0 (23A344)

<img width="1022" alt="Screenshot 2024-10-12 at 7 10 39 AM" src="https://github.com/user-attachments/assets/089c4831-44f9-495d-a55a-521c398c49a0">

**Comment by slossetti** [comment]
Same issue here.

**Comment by sschlein** [comment]
Please be aware that you can also create sites via the terminal: https://herd.laravel.com/docs/1/getting-started/sites#creating-your-first-site

We are trying to debug this right now and provide a GUI for this again but we haven't been able to reproduce this yet

**Comment by mpociot** [comment]
I was just able to reproduce this on macOS 14.0 as well.
The issue does not occur on macOS 14.5+ (I haven't checked every version in-between)
What's interesting is that this bug also does not occur on older macOS versions (like macOS 12).

So this is unfortunately a macOS bug and you should update your OS. I will add a check into Herd to prevent this from happening, but we won't be able to fix the root issue as it's OS related.
