### ISSUE TITLE
[Bug]: Herd doesnt load/start

### ISSUE THREAD

**Issue by LarryBarker** [beyondcode/herd-community#1055]
### Platform

macOS

### Operating system version

macOS sonoma 14.6.1

### System architecture

Intel (x86)

### Herd Version

Can't tell, but should be the latest

### Bug description

Not sure what happened but since my last system restart, Herd will not load. I've tried opening it through finder, nothing happens. Also trying `herd start` in my terminal and it just hangs
<img width="1624" alt="image" src="https://github.com/user-attachments/assets/fa528b8e-37bd-4079-9dc9-385b506368a8">

Let me know how I can provide more context, I know this is brief but not sure what to do at this point. Thank you!

**Comment by mpociot** [comment]
Is Herd in your activity monitor/running?

**Comment by LarryBarker** [comment]
It wasn't showing in the force quit window, I didn't check the activity monitor though. However, I ran a system update and when I restarted, Herd is working again. Not sure what was going on, feel free to close this out. I can follow up if it happens again, and make sure to check the activity monitor. Thank you!
