### ISSUE TITLE
[Bug]: 502 on some php83 sites

### ISSUE THREAD

**Issue by haugen86** [beyondcode/herd-community#1056]
### Platform

macOS

### Operating system version

macOS sequoia

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.11.1 (Build: 34)

### PHP Version

PHP 8.3.12 (cli) (built: Sep 27 2024 00:18:43) (NTS)

### Bug description

So after buying Herd Pro, and upgrading Herd, I started experiencing 502 on two sites. One of the sites I'm currently working on upgrading from 7.4 to 8.3. The 7.4 branch works fine, but the 8.3 branch is giving a 502. Makes me think PHP-fpm is not running, but I have other sites on 8.3 that is in fact working just fine. Both sites are isolated as well.

I have tried force-stopping all services, and starting them again - but same thing is happening.

### Relevant log output

```shell
502 site:

# ISOLATED_PHP_VERSION=8.3
server {
    listen 127.0.0.1:80;
    server_name chuckberries.test www.chuckberries.test *.chuckberries.test;
    #listen VALET_LOOPBACK:80; # valet loopback
    root /;
    charset utf-8;
    client_max_body_size 1024M;

    location /41c270e4-5535-4daa-b23e-c269744c2f45/ {
        internal;
        alias /;
        try_files $uri $uri/;
    }

    location / {
        rewrite ^ "/Applications/Herd.app/Contents/Resources/valet/server.php" last;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    access_log off;
    error_log "/Users/mariushaugen/Library/Application Support/Herd/Log/nginx-error.log";

    error_page 404 "/Applications/Herd.app/Contents/Resources/valet/server.php";

    location ~ [^/]\.php(/|$) {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass $herd_sock_83;
        fastcgi_index "/Applications/Herd.app/Contents/Resources/valet/server.php";
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME "/Applications/Herd.app/Contents/Resources/valet/server.php";
        fastcgi_param HERD_HOME "/Users/mariushaugen/Library/Application Support/Herd";
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    location ~ /\.ht {
        deny all;
    }
}





Working site:

# ISOLATED_PHP_VERSION=8.3
server {
    listen 127.0.0.1:80;
    server_name nexus.test www.nexus.test *.nexus.test;
    #listen VALET_LOOPBACK:80; # valet loopback
    root /;
    charset utf-8;
    client_max_body_size 1024M;

    location /41c270e4-5535-4daa-b23e-c269744c2f45/ {
        internal;
        alias /;
        try_files $uri $uri/;
    }

    location / {
        rewrite ^ "/Applications/Herd.app/Contents/Resources/valet/server.php" last;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    access_log off;
    error_log "/Users/mariushaugen/Library/Application Support/Herd/Log/nginx-error.log";

    error_page 404 "/Applications/Herd.app/Contents/Resources/valet/server.php";

    location ~ [^/]\.php(/|$) {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass $herd_sock_83;
        fastcgi_index "/Applications/Herd.app/Contents/Resources/valet/server.php";
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME "/Applications/Herd.app/Contents/Resources/valet/server.php";
        fastcgi_param HERD_HOME "/Users/mariushaugen/Library/Application Support/Herd";
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    location ~ /\.ht {
        deny all;
    }
}
```

**Comment by mpociot** [comment]
Do you get any output in the nginx error log?
It should be located at `~/Library/Application Support/Herd/Logs`

Given that both sites use the same fastcgi_pass socket, this is weird 🤔 

Herd might switch to the debug FPM process, if you either have xdebug enabled manually, or if the breakpoint detection is enabled.

You should see the status of your debug FPM processes when holding down the option key, while clicking on the Herd menubar icon.
But a force-stop should restart these as well, so that's odd.

**Comment by haugen86** [comment]
Hey Marcel, thanks for answering promptly.

This is the output from the nginx log:

```shell
2024/10/02 09:44:08 [error] 26562#196032: *6 upstream prematurely closed connection while reading response header from upstream, client: 127.0.0.1, server: chuckberries.test, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/Users/mariushaugen/Library/Application Support/Herd/herd-debug83.sock:", host: "chuckberries.test"
``` 

I cannot see any status for debug FPM processes from the Herd dropdown, while holding down option. Also tried disabling the breakpoint detection.

🤯

**Comment by haugen86** [comment]
Aah, yes it actually `herd-debug83.sock` in the log. So the Xdebug browser extension is not enabled, and I tried in a different browser - but with the same outcome.

Haha, yes I have tried turning it off and on again. I even upgraded the OS while experiencing this 😆 

I will try to go further down the rabbit hole, but help is veeery much appreciated!

**Comment by mpociot** [comment]
@haugen86 please try scrolling in the services list - if macOS is configured to automatically hide scrollbars, it might not be obvious that you can scroll inside of the services while holding down the option key.

**Comment by mpociot** [comment]
@haugen86 if you have a minute for a quick screensharing session, feel free to jump on this call. Might be easier than going back and forth on this issue:

https://meet.google.com/pco-bwno-xfd

**Comment by haugen86** [comment]
Yeah give me a minute and I'll be there

**Comment by filzasaleem** [comment]
How do I disable PHP Deprecated warnings in Herd.
I have tried  in settings opened the php.ini file and added error_reporting = E_ALL & ~E_WARNING & ~E_NOTICE & ~E_DEPRECATED but i still get the warnings, 
(i stopped and started all services after the changes)

**Comment by haugen86** [comment]
So my colleague got it working, while I'm still having issues. Even did a fresh installe of macOS and still same issue...

Is there somewere I could see links to older versions of herd, might try to roll back even further to see if it has impact. It was working fine like a month or two ago 😭

**Comment by mpociot** [comment]
@haugen86 I'm afraid we don't allow rolling back to previous versions of PHP.
But if it works with the same PHP version for your colleagues, that shouldn't be the cause of this issue either 🤔

**Comment by haugen86** [comment]
I gave up on figuring this out.
