### ISSUE TITLE
[Bug]: Laravel herd MacOS [Sequoia 15.0] does not open after updating.

### ISSUE THREAD

**Issue by dlogvin** [beyondcode/herd-community#1057]
### Platform

macOS

### Operating system version

macOS sequoia 15.0

### System architecture

Intel (x86)

### Herd Version

1.11.1

### Bug description

App does not open after installing the new version.

![Screenshot 2024-10-02 at 17 59 14](https://github.com/user-attachments/assets/00851cd7-8685-4fed-9ca2-c9e65996bd9a)

**Comment by dlogvin** [comment]
I re-installed manually and it fixed the issue. But it's quite odd why this happened.

**Comment by mpociot** [comment]
Weird. Maybe the file got corrupted during download. Glad it's working now
