### ISSUE TITLE
[Bug]:  [Step Debug] Could not connect to debugging client. Tried: localhost:9003 (through xdebug.client_host/xdebug.client_port).

### ISSUE THREAD

**Issue by abdulwahhabkhan** [beyondcode/herd-community#1059]
### Platform

macOS

### Operating system version

macOS Sequoia 15.0

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.11

### PHP Version

PHP 8.2.24 (cli) 

### Bug description

All `Laravel` commands show message if lister disabled.

 [Step Debug] Could not connect to debugging client. Tried: localhost:9003 (through xdebug.client_host/xdebug.client_port).
<img width="1703" alt="image" src="https://github.com/user-attachments/assets/4181f069-4ffb-454f-9e92-fa11e3a07918">

### Steps to reproduce

`php artisan` or any other Laravel command

`php -v` works fine.

**Comment by mpociot** [comment]
This is unrelated to Herd. It means that you have Xdebug enabled, but no debugging client is actually listening for debug connections

**Comment by abdulwahhabkhan** [comment]
Thanks a lot sir,

If `Xdebug` is enabled, Its not necessary that during every command I will have lister setup to.  I will activate listener only when its required.

as before using `Herd` I did not face this issue.

Done some search and following setting remove the message.
```
zend_extension=/Applications/Herd.app/Contents/Resources/xdebug/xdebug-83-arm64.so
xdebug.mode=debug,develop
xdebug.start_with_request=yes
xdebug.start_upon_error=yes
xdebug.log_level=0
```

This was not mentioned in doc.

Once again thanks a lot.

**Comment by JohnnyWalkerDigital** [comment]
None of the above settings worked for me and PHPUnit, but the following did:

> zend_extension=/Applications/Herd.app/Contents/Resources/xdebug/xdebug-84-arm64.so
> xdebug.mode=debug,develop,coverage
> xdebug.start_with_request=yes
> xdebug.start_upon_error=yes
> xdebug.log_level=0

For me it was as simple as adding "coverage" to xdebug.mode
