### ISSUE TITLE
[Bug]: Herd Share redirecting to local valet domain

### ISSUE THREAD

**Issue by mbuk** [beyondcode/herd-community#106]
### Operating system version

macOS Venture 13.5

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.1.2 (Build 13)

### Bug description

I can access ```<project>.test``` in my browser and ```https://<project>.test```
When I run herd share with a custom domain and attempt to access ```<project>.dev.<redacted>.co.uk``` I get redirected to ```https://<project>.test```

The same thing happens if I attempt to access ```<project>.dev.<redacted>.co.uk``` on a different workstation.

### Steps to reproduce

I have freshly installed herd
I have installed PHP 7.4.33 and 8.2.8 via the herd php menu.
My system PHP version is 8.2.8

In a fresh terminal window I have gone to the laravel project folder.
I ran ```herd link --secure```
Then I opened the herd app and changed the project version to php 7.4
I restarted all the herd "services"
I added my expose token to the the config

I opened terminal and changed directory the project
Then I ran ```herd share```

I can access the project via ```http://<project>.test``` and ```https://<project>.test``` redirection to the ssl site is working.

The problem comes when I attempt to access via my custom expose domain.
```http://<project>.dev.<redacted>.co.uk```
or
```https://<project>.dev.<redacted>.co.uk```
on this workstation or on another workstation they are redirected via a 301 to the local domain ```https://<project>.test```

I have tired removing and reinstalling herd - including delete the ~/Library/Application Support/Herd folder between removing and reinstalling

I have tried supplying subdomain/domain/name in various combinations to herd share but can't get this to work.

I have looked that the ```~/Library/Application Support/Herd/config/valet/Nginx/<project>.test``` file and tired adding in ```<project>.dev.<redacted>.co.uk``` as a site name.

**Comment by mbuk** [comment]
a bit more info on this.

If I remove this section 

```
server {
    listen 127.0.0.1:80;
    #listen 127.0.0.1:80; # valet loopback
    server_name <redacted>.test www.<redacted>.test *.<redacted>.test;
    return 301 https://$host$request_uri;
}
```

The site will load on the correct domain - but the php version isn't the isolated version 7.4 it's what ever the system version is.

**Comment by mbuk** [comment]
@mpociot Do you think this could actually be an issue with Valet?

**Comment by marlocorridor** [comment]
This might be related:
https://github.com/beyondcode/expose/issues/13#issuecomment-645336957

**Comment by marlocorridor** [comment]
> `expose` share https://<project>.test` https://github.com/beyondcode/herd-community/issues/106#issuecomment-1677269839
running this and trying to a different browser works for me

**Comment by importjeremy** [comment]
> @mpociot I think this is a problem with herd rather than expose. Because if I run the version of expose bundled with herd manually with: `expose share https://<project>.test` both the local SSL site and the url shared by expose work. vs running herd share or `herd share https://<project>.test` which redirects to `https://<project>.test`
> 
> See here: [beyondcode/expose#13](https://github.com/beyondcode/expose/issues/13)

Running `expose share https://<project>.test` works for me also, but only when I add the generated url to `APP_URL` in the .env file. If I don't add it there, it redirects to the local site.

**Comment by importjeremy** [comment]
Running `expose share https://<project>.test` works for me also, but only when I add the generated url to `APP_URL` in the `.env` file. If I don't add it there, it redirects to the local site.

[https://github.com/beyondcode/herd-community/issues/106#issuecomment-1677269839](url)

**Comment by nathangross** [comment]
I just created a discussion that I think might be similar to this issue? I would love to figure out how to use herd share with vite (`npm run dev`)
https://github.com/beyondcode/herd-community/discussions/211

**Comment by SaaberDev** [comment]
This might help if anyone is using (herd + ngrok with homebrew).

Run `ngrok http --host-header=rewrite https://domain.test` this way for now until `herd share` is not getting fixed.

Note that, I also tried `herd share-tool ngrok` to make sure herd is using ngrok.

**Comment by devserge** [comment]
Has there been any fix for this? I tried the solution of @SaaberDev, but at my end it redirects to localhost too.

**Comment by mbuk** [comment]
@devserge no movement on this yet.

**Comment by WendellAdriel** [comment]
Do we have any updates on this?
For now, I had to use the solution provided by @SaaberDev for it to work properly

**Comment by mpociot** [comment]
Does it make a difference when you explicitly try to share your project URL?
Like this: `herd share https://your-secure-site.test`

**Comment by philipkozeny** [comment]
> Does it make a difference when you explicitly try to share your project URL? Like this: `herd share https://your-secure-site.test`

I have the same setup (custom pro domain) as someone stated above.

- with `expose share https://your-secure-site.test` it works now
- with `herd share https://your-secure-site.test` it doesn't work and I get redirect from my custom domain to the local `https://your-secure-site.test` site

**Comment by nkb-bd** [comment]
> ngrok http --host-header=rewrite https://domain.test

This worked me also, it should be fixed

**Comment by SaaberDev** [comment]
> > I recently ran into the same issue. For me uninstalling both Herd an Valet and reinstalling Herd again fixed the issue.
> 
> I don't have valet in installed directly - just herd.

@devserge , @mbuk , @mpociot 

If this does not work for you then you are probably running "http" and also redirecting from your route file. For example when you visit "/" you are redirecting to "/dashboard". This redirect is the culprit when sharing site from localhost.

Quick fix:

Add this code to your `AppServiceProvider`.

```php
if ($this->app->environment() != 'production') {
   !request()->header('x-forwarded-host') ?: request()->headers->set('host', request()->header('x-forwarded-host'));
}
```

Now share your site according to my previous comment of course using herd + ngrok in homebrew and CHILL ... 😇

**Comment by ryanmortier** [comment]
Same issue with `herd share`

**Comment by ryanmortier** [comment]
Looks like the latest build of Herd has fixed this issue for me. Anyone else?

**Comment by nkb-bd** [comment]
Still not working !

**Comment by joadam** [comment]
@mpociot Still not working with herd version 1.22.1 (build: 53) on Mac
