### ISSUE TITLE
[Bug]: Tabs in dump window are not selectable

### ISSUE THREAD

**Issue by nezaboravi** [beyondcode/herd-community#1064]
### Platform

macOS

### Operating system version

Sequoia 15.0 (24A335)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.10.0 build 33

### PHP Version

PHP 8.3

### Bug description

I cant get tabs on Dump window to work, and cant click on any. 
<img width="603" alt="image" src="https://github.com/user-attachments/assets/6b3241d8-643d-44e9-afd5-d8e3c1c27941">

**Comment by mpociot** [comment]
Please update to the latest version where this was fixed

**Comment by nezaboravi** [comment]
Did this morning, it works, thanks marcel :)
