### ISSUE TITLE
[Bug]: TablePlus is not opening from Sites page

### ISSUE THREAD

**Issue by pyerro** [beyondcode/herd-community#1065]
### Platform

Windows

### Operating system version

Windows 11 (23H2)

### System architecture

Intel (x86)

### Herd Version

1.11.1

### Bug description

Changelog for 1.11.1 states that "TablePlus can now be opened from the Sites page". If I click on Open button on Sites page it opens Explorer > This Computer. I have TablePlus installed.

### Steps to reproduce

On Laravel Herd Dashboard > Open Sites > click on a TablePlus Open button.

**Comment by mechelon** [comment]
Where is TablePlus installed on your machine?

**Comment by pyerro** [comment]
Default install location: C:\Program Files\TablePlus\

**Comment by isimmons** [comment]
Same here. Default location but Herd opens the explorer to "This PC" 
If I follow through and click on `C:\Program Files\TablePlus\TablePlus.exe` it opens.

**Comment by isimmons** [comment]
@mpociot It's still not working.
Herd 1.11.2 on a new PC

When I click open for tableplus, Windows wants me to "Select an app to open this .sqlite file"
I browse to and choose "C:\Program Files\TablePlus\TablePlus.exe"
TablePlus opens and gives me an error "Driver Error Can't connect to database"

But if I open TablePlus, create a sqlite connection and browser to the database.sqlite file it works.

Even after creating the connection, it still won't open without the driver error when opening from Herd

**Comment by AhmedSalheia** [comment]
same issue as @isimmons still
Herd version: 1.13.0.
TablePlus version: 6.2.2.
OS: windows 11 (x64).
PHP version: 8.3.

clicking the (open) button on a site from herd sites windows ask me to select an app as mentioned, choose TablePlus, an error (Can't connect to database) pops up.

creating a connection in TablePlus works, but opening from herd still gives the same error after that.
Any Suggestions?
