### ISSUE TITLE
[Bug]: Herd Window Issue

### ISSUE THREAD

**Issue by devajmeireles** [beyondcode/herd-community#1066]
### Platform

macOS

### Operating system version

macOS 14.4.1 (23E224)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.11.1

### Bug description

Ok! Herd is great, but this annoys me. I reported this in the past, via Twitter to @mpociot, but now I want to open an official issue about it. I don't know about other people, but for me Herd's windows simply don't "call" when I request them. 

An example of this is this short video, where I open the Services window, but after clicking on the item I want to open, I still have to go to the dock and click on the application icon to display the services window. 

![CleanShot 2024-10-03 at 21 38 26](https://github.com/user-attachments/assets/28edc28c-e619-4114-8558-bd87e7538b8b)

I hope this will be fixed! And yes, I take full responsibility for not reporting this earlier, @mpociot , since I told you on Twitter, but I didn't respond to your messages informing you what the window problems were.

### Steps to reproduce

Using the same macOS I mentioned, try opening the Service window and check if the window will be called in the foreground or if you will need to show the dock and click on the Herd icon to display the window.

**Comment by mpociot** [comment]
This is now fixed with Herd 1.11.2
