### ISSUE TITLE
[Bug]: Herd showing 504 error after fresh install

### ISSUE THREAD

**Issue by mikemuller** [beyondcode/herd-community#1070]
### Platform

macOS

### Operating system version

Sonoma 14.7

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.11.1

### Bug description

Herd not working after reinstall of the application. I get a 504 error for every site I create.

### Steps to reproduce

I was trying to find a conflict in my local machine so I had removed some brew serveices and un-installed Herd. I want to use it again but when I re-install herd, it does not go through any of the installation steps. It just opens and then I get a 504 error on all my sites. I can't change PHP version at all. Nothing seems to save.  It also don't have all the services listed. I don't see nginx or DNS. I'm guessing that removing some brew services broke things but I'm not sure how to fix.

**Comment by mpociot** [comment]
Maybe the privileged helper tool is still installed.
You can remove it by running:

sudo /Library/PrivilegedHelperTools/de.beyondco.herd.helper uninstall

This will make sure that the onboarding process starts again.

**Comment by mauriciodulce** [comment]
Same issue #1077
