### ISSUE TITLE
[Bug]: Unable to install Herd profiler

### ISSUE THREAD

**Issue by labomatik** [beyondcode/herd-community#1072]
### Platform

macOS

### Operating system version

Sonoma 14.5 (23F79)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.11.1 build 34

### PHP Version

Php 8.1.30

### Bug description

At the installation of the profiler i got this:
 INFO  Latest release: 0.4.16

  INFO  Installing the SPX Profiler extension...

  INFO  Laravel Herd is installed. Installing for all available PHP versions...

  INFO  Restarting Laravel Herd...

  ERROR  There was an error installing the extension.

  ERROR  Please check the output above for any errors.

After the installation i've this error:

`
Warning: PHP Startup: Unable to load dynamic library '/Users/christophe/Library/Application Support/Herd/config/php/81/spx/spx.so' (tried: /Users/christophe/Library/Application Support/Herd/config/php/81/spx/spx.so (dlopen(/Users/christophe/Library/Application Support/Herd/config/php/81/spx/spx.so, 0x0009): tried: '/Users/christophe/Library/Application Support/Herd/config/php/81/spx/spx.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/christophe/Library/Application Support/Herd/config/php/81/spx/spx.so' (no such file), '/Users/christophe/Library/Application Support/Herd/config/php/81/spx/spx.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64'))), /lib/php/extensions/no-debug-non-zts-20210902//Users/christophe/Library/Application Support/Herd/config/php/81/spx/spx.so.so (dlopen(/lib/php/extensions/no-debug-non-zts-20210902//Users/christophe/Library/Application Support/Herd/config/php/81/spx/spx.so.so, 0x0009): tried: '/lib/php/extensions/no-debug-non-zts-20210902//Users/christophe/Library/Application Support/Herd/config/php/81/spx/spx.so.so' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/lib/php/extensions/no-debug-non-zts-20210902//Users/christophe/Library/Application Support/Herd/config/php/81/spx/spx.so.so' (no such file), '/lib/php/extensions/no-debug-non-zts-20210902//Users/christophe/Library/Application Support/Herd/config/php/81/spx/spx.so.so' (no such file))) in Unknown on line 0
`

**Comment by mpociot** [comment]
The bash script should automatically download the extension for the correct architecture (arm64 in your case)

Could you verify the extension architecture by running:

file ~/path/to/your/so/file

Does this error only show up on PHP 8.1?

**Comment by labomatik** [comment]
this is what i have
 
With iterm2:
uname -a
Darwin MBP-Christophe.localdomain 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:16:51 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T8103 x86_64

via phpstorm
uname -a
Darwin MBP-Christophe.localdomain 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:16:51 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T8103 arm64


`
 ~ ⮀ file /Users/christophe/Library/Application\ Support/Herd/config/php/81/spx/spx.so
/Users/christophe/Library/Application Support/Herd/config/php/81/spx/spx.so: Mach-O 64-bit bundle x86_64
 ~ ⮀ cd development/
 ~/development/ ⮀ ⭠ master ● ⮀ a cache:clear && a config:cache

Warning: PHP Startup: Unable to load dynamic library '/Users/christophe/Library/Application Support/Herd/config/php/81/spx/spx.so' (tried: /Users/christophe/Library/Application Support/Herd/config/php/81/spx/spx.so (dlopen(/Users/christophe/Library/Application Support/Herd/config/php/81/spx/spx.so, 0x0009): tried: '/Users/christophe/Library/Application Support/Herd/config/php/81/spx/spx.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/christophe/Library/Application Support/Herd/config/php/81/spx/spx.so' (no such file), '/Users/christophe/Library/Application Support/Herd/config/php/81/spx/spx.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64'))), /lib/php/extensions/no-debug-non-zts-20210902//Users/christophe/Library/Application Support/Herd/config/php/81/spx/spx.so.so (dlopen(/lib/php/extensions/no-debug-non-zts-20210902//Users/christophe/Library/Application Support/Herd/config/php/81/spx/spx.so.so, 0x0009): tried: '/lib/php/extensions/no-debug-non-zts-20210902//Users/christophe/Library/Application Support/Herd/config/php/81/spx/spx.so.so' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/lib/php/extensions/no-debug-non-zts-20210902//Users/christophe/Library/Application Support/Herd/config/php/81/spx/spx.so.so' (no such file), '/lib/php/extensions/no-debug-non-zts-20210902//Users/christophe/Library/Application Support/Herd/config/php/81/spx/spx.so.so' (no such file))) in Unknown on line 0
`

**Comment by o1y** [comment]
> The bash script should automatically download the extension for the correct architecture (arm64 in your case)

It seems like the profiler was installed when iTerm2 was running with Rosetta enabled, which likely led to the installation of x86_64 binaries instead of the correct arm64 binary. I had the same issue when installing the profiler. Totally forgot to turn off Rosetta after running some legacy stuff there .. 

As a work around uncheck "Open with Rosetta" for iTerm2 and try reinstalling the lib using the script. If I remember correctly, I first had to remove all SPX references to the extension inside all php.ini files.

**Comment by labomatik** [comment]
Indeed, i just deleted the content of the SPX (folder, lines in the ini)
I run again the installation script in phpstorm and all is correct now.

**Comment by mpociot** [comment]
Perfect - I'll close this issue then :)
