### ISSUE TITLE
[Bug]: After update to 1.11.1 it fails to launch.

### ISSUE THREAD

**Issue by jjcsinke** [beyondcode/herd-community#1073]
### Platform

macOS

### Operating system version

macOS 15.0

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.11.1

### Bug description

I updated to 1.11.1 but it then failed to launch. Just a small blip of the app icon and it closes immediately.

~`herd info` gives Error finding executable PHP output:~ - not a symptom anymore.

 

### Steps to reproduce

Did an uninstall as described on the support page (remove App Support etc.)

Clean install of 1.11.1 did not help

Another uninstall

Re-install 1.11.0 does work so that should be a clean install for it.
Re-enter my Pro licence

Update to 1.11.1 
Fails again.

No uninstall actions
Install 1.11.0 (copy to App folder)

Herd does work

**Comment by jjcsinke** [comment]
not actually got any sites running yet, but at least the app launches. bedtime now.

**Comment by mpociot** [comment]
Did you get a crash log when opening Herd? I can't seem to find it in Sentry. 
Would be great to know so I can help figure out what's going wrong.

**Comment by jjcsinke** [comment]
No, nothing from macOS, and the debugger option also doesn’t seem to receive anything yet.

**Comment by mpociot** [comment]
@jjcsinke do you have a minute to look at this via screensharing?
Feel free to join, if you do: https://meet.google.com/eij-zbhp-dgi

**Comment by mpociot** [comment]
@jjcsinke Going deeper down the rabbit hole, this error seems to be related to Swift / macOS itself.

Could you tell me which exact macOS version you are running and if there is a macOS update available for you?

**Comment by jjcsinke** [comment]
I'm on 15.0, will update to 15.0.1 now

**Comment by jjcsinke** [comment]
@mpociot that solved it for me. 
Thanks for the support!
