### ISSUE TITLE
[Bug]: YARN version overwrites

### ISSUE THREAD

**Issue by vitali-exposure** [beyondcode/herd-community#1079]
### Platform

macOS

### Operating system version

mac

### System architecture

Intel (x86)

### Herd Version

latest

### Bug description

I don't know why but my yarn version turns to 1.2 (I have installed 4.2.2)
Seems herd nodejs overwrites system nodejs I don't know the reason of that bug.

![Screenshot 2024-10-09 alle 15 55 50](https://github.com/user-attachments/assets/9fdcb16b-c1b2-45ea-b836-77689dfbef72)

<img width="688" alt="Screenshot 2024-10-09 alle 15 58 40" src="https://github.com/user-attachments/assets/c65969de-809f-4eda-9905-623f07188018">

**Comment by mpociot** [comment]
I'm not sure where this error message from the pre-commit is coming from, but it seems like it's not using the node version from Herd (which has yarn 4.2.2 installed).

This sounds to me like it's an issue with GitHub Desktop not loading the correct environment - not with Herd itself, as it works fine in the CLI.
