### ISSUE TITLE
[Bug]: Herd bash script using wrong binaries directory

### ISSUE THREAD

**Issue by mayocca** [beyondcode/herd-community#108]
### Operating system version

macOS Ventura 13.4.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.1.2 (Build: 13)

### Bug description

The Herd bash script is assuming that the user's home directory is the same name as the user itself.

```bash
# In ~/Library/Application Support/Herd/bin/Herd:5
DIR="/Users/$USER/Library/Application Support/Herd/bin/"
```

The script should look for the `$HOME` environment variable to get the actual home directory in case it is different to the user running the script.

```bash
# Should replace ~/Library/Application Support/Herd/bin/Herd:5
DIR="$HOME/Library/Application Support/Herd/bin"

# Note that the trailing `/` has also been removed because
# it is already added every time the variable is used. 
```

### Steps to reproduce

- Install latest Herd version.
- Change the current user's username.
- Run any `herd` command.

### Relevant log output

```shell
Could not open input file: /Users/{user}/Library/Application Support/Herd/bin//find-usable-php.php
Error finding executable PHP. Quitting for safety.
Provided output from find-usable-php.php:
```

**Comment by mpociot** [comment]
Thanks for reporting this. This will be fixed in the next release 👍
