### ISSUE TITLE
[Bug]: Deprecated notification when using php 8.4 RC1

### ISSUE THREAD

**Issue by JurgenThijs** [beyondcode/herd-community#1082]
### Platform

macOS

### Operating system version

macOS Sequoia 15.0

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.11.1 (Build: 34)

### PHP Version

PHP 8.4.0 (RC1)

### Bug description

When creating a fresh new Laravel project (11.27.2) and opening it in the browser, you immedialtely get a depricated error for BeyondCode\HerdConfiguration

Deprecated: BeyondCode\HerdConfiguration\HerdConfiguration::loadConfigFile(): Implicitly marking parameter $path as nullable is deprecated, the explicit nullable type must be used instead in /Applications/Herd.app/Contents/Resources/valet/HerdConfiguration.php on line 173

### Steps to reproduce

laravel new my-new-site
cd my-new-site
Open herd sites and change your project to 8.4
herd open

**Comment by mpociot** [comment]
This is now fixed with Herd 1.11.2

**Comment by dinhquochan** [comment]
Should be a temporary fix by adding the line below into `php.ini`

```ini
error_reporting=E_ALL & ~E_DEPRECATED
```
