### ISSUE TITLE
[Bug]: `herd init` Doesn't Work After Edit `herd.yml` Manually

### ISSUE THREAD

**Issue by devajmeireles** [beyondcode/herd-community#1085]
### Platform

macOS

### Operating system version

15.0.1 (24A348)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.11.1 (Build 34)

### PHP Version

PHP 8.3.12 (cli) (built: Sep 27 2024 00:18:43) (NTS)

### Bug description

Since `herd init:fresh` erases the contents of the `herd.yml` file, I manually edited it to add the meilisearch service. After that, when I try to run `herd init` no service starts, as shown below:

![CleanShot 2024-10-11 at 01 59 59](https://github.com/user-attachments/assets/32ab7456-1984-4ac9-add4-37df064f77bf)

### Steps to reproduce

1. Try to edit your `herd.yml` manually by adding any supported herd services
2. After that, run `herd init`

**Comment by sschlein** [comment]
It looks like Meilisearch 1.90 is already available on port 7700, so why would it install it again?

`herd init` does not start the services but installs them if they are not available on your system,, so "is running" might be a bit misleading.

**Comment by devajmeireles** [comment]
> It looks like Meilisearch 1.90 is already available on port 7700, so why would it install it again?
> 
> `herd init` does not start the services but installs them if they are not available on your system,, so "is running" might be a bit misleading.

So `herd init` doesn't start the service, instead it is used to install the service? It doesn't make much sense that the `herd init` command doesn't work to 1) install and start the services or 2) start the service if it is installed. Maybe we need a `herd start`? Easier, maybe tweaking `herd init` to work as I mentioned would be welcome.

**Comment by mpociot** [comment]
This is now fixed with Herd 1.11.2
