### ISSUE TITLE
[Bug]: Can't load any sites on 1.11.1 unless I manually add the site to `/etc/hosts`

### ISSUE THREAD

**Issue by tommcfarlin** [beyondcode/herd-community#1088]
### Platform

macOS

### Operating system version

macOS Sequoia 15.0.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.11.1

### Bug description

I attempted to load any of the sites I have linked and secured with Herd and none of them load. 

### Notes

* I've started and stopped my services using brew.
* I've started and stopped services via Herd.
* I've reinstalled Herd.
* All icons are green.
* No sites load unless I explicitly point one domain to 127.0.0.1

I have to manually add the site to my `/etc/hosts` file for it to load. The relevant portion of `/etc/hosts` file looks like this:

```
127.0.0.1 ambox.test
```

I have `/etc/resolver/test` and it has the following:

```
nameserver 127.0.0.1
```

### Output

Chrome (both with and without the DNS setting changed in `chrome://settings`) returns the following error:

```
This site can’t be reached

The webpage at https://mydomain.test/ might be temporarily down or it may have moved permanently to a new web address.

ERR_TUNNEL_CONNECTION_FAILED
```

### Steps to reproduce

I started work today and none of my sites loaded. This appears to have started after upgrading to 1.11.1.

Can provide more context as needed.

**Comment by sschlein** [comment]
The error message sounds like a VPN. Does your Mac try to use a VPN to connect to local sites? If yes, that likely doesn't work.

**Comment by tommcfarlin** [comment]
It doesn't; I don't have a VPN active and there is nothing running that would cause this, _as best as I can tell_. 

I've not added, removed, or modified any VPN configurations since the latest update.

**Comment by tommcfarlin** [comment]
Wasn't able to resolve the problem with my projects in their directory but I moved them to `/Herd/sites` and things resolve fine.

Thanks for the help!

**Comment by sschlein** [comment]
That's odd but great that you were able to solve it :)
