### ISSUE TITLE
[Bug]: Dock icon not hidden after opening a herd service

### ISSUE THREAD

**Issue by wesleylether** [beyondcode/herd-community#1090]
### Platform

macOS

### Operating system version

macOs Sequoia 15.0.1 (24A348)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.11.1 (Build: 34)

### Bug description

When Herd starts initial, the dock item of Herd is hidden. But after opening any service like "sites", "dumps", "mail", etc, the Herd dock item is visible in the dock.

### Steps to reproduce

1. Start Herd
2. Herd icon in dock is hidden
3. Open Herd service in example "sites"
4. See Herd icon in dock
5. Close Herd service "sites"
6. Herd icon still visible in dock

**Comment by sschlein** [comment]
What happens if you click on the Herd icon? Is there a window that get's visible? You can also check your main menu bar if there is any reference.

**Comment by wesleylether** [comment]
When I click on the herd icon. No window will be shown. Herd does activate because the main menu bar shows the reference of Herd. But after clicking on Herd in the main menu bar, no options are available .

**Comment by mpociot** [comment]
@wesleylether do you have any external screens connected or use any kind of virtual desktop software?

**Comment by wesleylether** [comment]
@mpociot I indeed use multiple external screens, but do not use a virtual desktop software.

But I do have fixed it with the following mac option:
> Systemsettings > Desktop / Dock > Mission Control > Displays have separate spaces. 

When I enable this one, then the issue is resolved. But when you disable this option, then the issue occurs.

**Comment by mpociot** [comment]
@wesleylether ohh - great find! This will be fixed in the next release 🎉

**Comment by wesleylether** [comment]
@mpociot Ah great to hear. Then I will close this bug and await the next release!
