### ISSUE TITLE
[Bug]: Services and Herd crashes very often

### ISSUE THREAD

**Issue by mchev** [beyondcode/herd-community#1094]
### Platform

macOS

### Operating system version

macOS Somona 14.6.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.11.1 (Build: 34)

### PHP Version

PHP 8.3

### Bug description

I have a Laravel Reverb service activated and it keep stopping with no reason (port 8080, not secured). There is only this service.

I don't know if it's related but Herd crashes a lot too. Sometimes with an alert and sometimes i just see it because i got a Bad Gateway. (similar to #1083 so it maybe related to M1 M2 architecture)

Herd never crashed before. What changed ? Latest update and also subscription to pro.

### Relevant log output

![Capture d’écran 2024-10-16 à 12 55 18](https://github.com/user-attachments/assets/1ee9df5b-3946-4c93-ae79-25aaf6c4da55)

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000cc529cf54490 -> 0x00004c529cf54490 (possible pointer authentication failure)
Exception Codes:       0x0000000000000001, 0x0000cc529cf54490

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [25900]

**Comment by sschlein** [comment]
Can you please check if the profiler is constantly enabled and writing lots and lots of data?

![CleanShot 2024-10-16 at 12 55 40](https://github.com/user-attachments/assets/9be8893b-902f-4aa8-83b6-75204a611aac)

**Comment by mchev** [comment]
> Can you please check if the profiler is constantly enabled and writing lots and lots of data?

Detect breakpoints automatically is checked.
I have 0 entries in Profiler Data

**Comment by sschlein** [comment]
Can you update your macOS to the latest version? There was a bug on macOS 15.0.0 that had the same problems and it was fixed on 15.0.1, so it may also got fixed from 14.6.1 to 14.7 if you're not going to Sequoia yet.

**Comment by mchev** [comment]
> Can you update your macOS to the latest version?

Thanks, I'll give this a try and test it throughout the day to see if the issue is resolved. I'll come back here to close the ticket or provide an update.

**Comment by mchev** [comment]
@sschlein after update to 15.0.1 (24A348) the service keep stopping.
I'm wondering if this is when i try my apps with multiple browsers open (to test websockets)

**Comment by mchev** [comment]
Herd seems to be ok now. But just one hour testing.
Memory limit is 128

**Comment by sschlein** [comment]
Yeah, definitely increase that by a lot for Reverb, maybe start with 1024 and do a Reverb restart after the change.

**Comment by mchev** [comment]
> Yeah, definitely increase that by a lot for Reverb, maybe start with 1024 and do a Reverb restart after the change.

Sorry but it still crashes after increasing to 1024. Il check later if there is another issue, memory leak or something else.

**Comment by mpociot** [comment]
I'll close this issue as this seems to be related to Reverb crashing and not Herd itself.
If possible and open an issue on the reverb repository - maybe the Herd service logs give any insight into why Reverb is crashing.

**Comment by mchev** [comment]
I'm using it without Herd locally and in production with Forge, and I haven't encountered any issues. 
This seems to be specifically related to Herd.

**Comment by juliangums** [comment]
I'm also encountering this issue. This was really the reason I got the Pro licence. Seems to happen if there are a few too many events in too little time especially with ShouldBroadcastNow. Hope that helps/

**Comment by sschlein** [comment]
This could be related to PHP not having anough memory, can you check the PHP configuration for the version that runs Reverb? Should be within the PHP settings, either overall or specific per version.

**Comment by jhull** [comment]
Dang, was hoping the new M4 and Sequoia 15.5 would let me finally start using Reverb through Herd - but alas - constant crashing (1024MB set for PHP). As above, Reverb never crashes if i just start manually from CLI - something about Herd...
