### ISSUE TITLE
[Bug]: fresh Herd Installation fails to correclty install (/Library/Application Support/Herd/bin//herd: line 13: php: command not found Error finding executable PHP. Quitting for safety. Provided output from find-usable-php.php:)

### ISSUE THREAD

**Issue by marfrede** [beyondcode/herd-community#1096]
### Platform

macOS

### Operating system version

Sequoia 15.0.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.1.11 (and I also tried 1.9.1)

### Bug description

After installation of Laravel Herd, I get the following error, when running `herd --version`:
```cmd
➜  ~ herd --version
/Users/morv/Library/Application Support/Herd/bin//herd: line 13: php: command not found
Error finding executable PHP. Quitting for safety.
Provided output from find-usable-php.php:
```

Also when trying to run php:

```cmd
➜  ~ php --version
zsh: command not found: php
```

### Steps to reproduce

I had a problemn with Laravel Herd after I changed my username on my Mac.
So what I did was

- follow the [`Uninstall`](https://herd.laravel.com/docs/1/troubleshooting/uninstalling) guide
- completely reinstall Laravel Herd ([`Installation`](https://herd.laravel.com/docs/1/getting-started/installation))
- open a new terminal and type: `herd --version`

**Comment by marfrede** [comment]
FYI
- I found no solution but to install herd-lite (via `/bin/bash -c "$(curl -fsSL https://php.new/install/mac)"`)
- Also I installed nvm via brew and installing node via nvm
- Now I was finally able to get my Laravel/React running again.

Still no solution to install Herd, but no solution needed anymore for me.

**Comment by pmochine** [comment]
I just installed herd for the first time, coming back to laravel after 2 years. And I have the same problem. I installed herd via the mac.app from the website and I wanted to try out the "herd composer" command, but it says:
```
herd --version
zsh: command not found: herd
```

**Comment by mpociot** [comment]
I assume that PHP was still in your PATH for the old username?

You could remove the existing Herd helper service manually and then re-install Herd which triggers the onboarding again: `sudo /Library/PrivilegedHelperTools/de.beyondco.herd.helper uninstall`

Changing your username sounds like an edge case to me 😬
