### ISSUE TITLE
[Bug]: After updating to latest version herd stopped working. 

### ISSUE THREAD

**Issue by waqasriaz** [beyondcode/herd-community#1097]
### Platform

macOS

### Operating system version

macOS Version 15.0 Beta (24A5279h)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.11.1

### PHP Version

8.3.12

### Bug description

Check this video https://monosnap.com/file/ZNe35nm2OzVnQycckvVv7cnC9EXOH3 

Herd not start 

### Steps to reproduce

check this video https://monosnap.com/file/ZNe35nm2OzVnQycckvVv7cnC9EXOH3 

### Relevant log output

```shell
no log
```

**Comment by mpociot** [comment]
There's a known bug in macOS 15.0 beta - please update to the latest stable release.

**Comment by brysonreece** [comment]
Worth noting macOS 15.1 Beta resolves this issue.
