### ISSUE TITLE
[Bug]: PHP Session with Redis Handler

### ISSUE THREAD

**Issue by deleugpn** [beyondcode/herd-community#110]
### Operating system version

macOS Ventura 13.4.1 (c) (22F770820d)

### System architecture

Intel (x86)

### Herd Version

1.1.2

### PHP Version

PHP 8.2.8 (cli) (built: Jul 28 2023 13:55:05) (NTS)

### Bug description

Unable to use PHP native session `session_start()` after changing the session configuration with `'save_handler' => 'redis'`. Since Redis extension is enabled, I'm not sure what would be the reason to not have the session handler.

```
session_start(): Session save handler "redis" cannot be found
```

### Steps to reproduce

```
session_start([
                'gc_maxlifetime' => '28800',
                'save_handler' => 'redis',
                'save_path' => 'tcp://redis-service:6379',
                'cookie_domain' => 'my.project.test',
                'cookie_secure' => true,
                'cookie_httponly' => '1',
                'cookie_samesite' => 'Lax',
            ]);
```

**Comment by mpociot** [comment]
Thanks for reporting this. It will be fixed in an upcoming internal PHP update

**Comment by deleugpn** [comment]
Hey @mpociot I've been watching the Changelog from Herd to see if this has been tagged, but now I noticed your comment is about an internal PHP update. What's the best way for me to know when this has been fixed?
