### ISSUE TITLE
[Bug]: Herd does not work when VPN (Express VPN) is running. 

### ISSUE THREAD

**Issue by pelachile** [beyondcode/herd-community#1102]
### Platform

macOS

### Operating system version

macOS Sonoma 14.6.1

### System architecture

Intel (x86)

### Herd Version

1.11.1

### PHP Version

PHP 8.2.4

### Bug description

local .test sites will not load

### Steps to reproduce

Turn on a VPN. Try to connect to any local .test site

**Comment by sschlein** [comment]
Your VPN seems to intercept the local traffic, so the only solution is to either configure it differently or turn it off. That's not something that Herd can change.

**Comment by EliasZ** [comment]
In case anyone comes across this via Google (like I did): there is no way to configure ExpressVPN to exclude certain TLDs or give priority to dnsmasq in the app.

Only viable solution is manually adding the project(s) to your hosts file:
`127.0.0.1 example.test`

Then resolution at least works with the ExpressVPN app on.
