### ISSUE TITLE
[Bug]: Laravel site loading too long but if https / secure is enable work perfectly

### ISSUE THREAD

**Issue by morizbebenk** [beyondcode/herd-community#1103]
### Platform

Windows

### Operating system version

Windows 11 (24H2 26100.2152)

### System architecture

Windows

### Herd Version

1.11.1

### PHP Version

8.3.12

### Bug description

I've reinstalled Laravel Herd several times but it's still the same.

When accessed in a browser, the Laravel application takes a very long time to load, but when I enable HTTPS / Secure, the application runs perfectly.

**Comment by sschlein** [comment]
This sounds like a system configuration issue to me, there's likely something intercepting the request like an anti virus program that forces https connections.

**Comment by morizbebenk** [comment]
I have disabled Windows Defender but still get the same results.
I have also added the Herd App to Windows Firewall in the Inbound Rules and Outbound Rules sections.

Is there an error log that I can check for the problem I mentioned ?

**Comment by mpociot** [comment]
Can you reproduce this issue with a fresh Laravel installation?
On Windows, the first request usually tends to take a bit longer - but subsequent requests are much faster. Maybe that's the case for you as well and it's not directly related to the SSL certificate?

**Comment by morizbebenk** [comment]
I have installed App with Laravel Herd, Composer and Laravel commands, but it's still the same.

![Screenshot 2024-10-29 123420](https://github.com/user-attachments/assets/1517b0d0-5f35-4d02-bc5a-31cd6926659f)

If https is enabled the preview is showing

![Screenshot 2024-10-29 123507](https://github.com/user-attachments/assets/de501c3c-c4d2-45c7-a22a-ce22fe135d1a)

**Comment by sschlein** [comment]
Is this for any chance, related to an Intertia and Vue with SSR app? If yes, you need to run the SSR server to make it fast.
