### ISSUE TITLE
[Bug]: Laravel Herd Defaults to PHP 8.4 During installation, Causing Compatibility Issues

### ISSUE THREAD

**Issue by DriesD1** [beyondcode/herd-community#1105]
### Platform

macOS

### Operating system version

macOS 15.0 (24A335)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.11.1

### PHP Version

8.3

### Bug description

I encountered a problem while trying to install Laravel Herd and Statamic. During the installation process, Laravel Herd automatically defaults to PHP version 8.3. This behavior causes compatibility issues with Statamic, which may not support this PHP version fully at this time.

**Comment by mpociot** [comment]
Which version do you mean? The title says 8.4, but your message 8.3. 

You can change the global version using the menubar icon or by typing "herd use 8.2” in your terminal

**Comment by corrosive4354** [comment]
When using Herd version 1.11.1 on macOS 15.0 (ARM64), it was found that PHP 8.3 was automatically selected during the installation process, which is not fully compatible with Statamic's support.

You can replace Herd with [Servbay](https://servbay.com), which is the most professional environment management tool on MAC. You can switch the PHP version you need, even the latest PHP8.4.

**Comment by corrosive4354** [comment]
When installing Laravel Herd, it uses PHP 8.4 by default, and Statamic may not fully support this version yet, causing compatibility issues.
You can use [Servbay](https://servbay.com) to switch PHP to 8.3 with one click. Of course, Servbay also supports PHP 8.4, you can take a look.
