### ISSUE TITLE
[Bug]: database.herd.test not loading sqlite file

### ISSUE THREAD

**Issue by 45ooo** [beyondcode/herd-community#1108]
### Platform

Windows

### Operating system version

windows 11 pro (23H2 22631.4317 1000.22700.1041.0)

### System architecture

Windows

### Herd Version

1.11.1

### Bug description

unable to load adminer correctly on a freshly build laravel breeze with default sqlite configuration

### Steps to reproduce

site > add > new Laravel project > next > laravel breeze:

![image](https://github.com/user-attachments/assets/f10d7d04-7996-4c91-81ea-357a51e9272c)

once project done generated, tested d login and register to make sure it works fine.
the sqlite is working as expected for login and register

when click site > <the side that is newly generated> click "open" button which is at right side of Adminer

![image](https://github.com/user-attachments/assets/1d2e655a-b53a-40a3-9b60-c8abfe1e428c)

![image](https://github.com/user-attachments/assets/ab168a36-8a63-4d74-bf83-cfa29c9c5ae8)

unable to access the project sqlite file

**Comment by mechelon** [comment]
Can you share the database-related part of your local `.env` file to support@beyondco.de?

**Comment by 45ooo** [comment]
here is the .env

**Comment by mechelon** [comment]
Thanks, this will be fixed in the next release :)
