### ISSUE TITLE
[Bug]: Certificates not trusted after setting up (secure) Reverb

### ISSUE THREAD

**Issue by joshstobbs** [beyondcode/herd-community#1112]
### Platform

macOS

### Operating system version

macOS Sonoma 14.5

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.11.1 (Build 34)

### Bug description

I tried setting up a new Reverb service and since starting it my previously provisioned certificates are no longer trusted, tried in both Chrome and Safari.

This is the first Reverb service I have setup since the SSL Reverb fix went out.

I'd love to understand what is happening and hopefully how to fix it!  I've found #452 which seems to talk about the same or similar issue.

Thanks so much!

### Steps to reproduce

- Secure a site
- Start a new Reverb service and ensure it is using the secure mode
- Check your browser to see if your previously secured site has a trusted certificate

**Comment by mpociot** [comment]
Hm this is really weird. Reverb (as mentioned in #452) does not affect any existing certificates.
Does re-securing your already secured sites fix this?

**Comment by joshstobbs** [comment]
So, I (un)fortunately have almost the exact same experience as the previous reporter.  I tried re-securing the sites, restarting the computer, and completely reinstalling Herd.  Nothing worked, though I went through the process of reinstalling a Reverb service on the new instance of Herd and walked away for the night.  When I came back today all was well.

I'm going to close this now as technically for me this is fixed, it was still strange though.  Let me know if there's any logs I can provide or if you need any more info!
