### ISSUE TITLE
[Bug]: DNSMasq reported green but won't works

### ISSUE THREAD

**Issue by roncsak** [beyondcode/herd-community#1115]
### Platform

macOS

### Operating system version

macOS Sonoma 14.1.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.11.1 (Build:34)

### Bug description

The DNSmasq service reported good (green) in the contextual menu but it is not working.

### Steps to reproduce

Hi there,
when I start Herd click on the icon H on the toolbar, the context menu opens and shows me that following services are up and running (with green dot in front of them):
- Nginx
- DNSmasq
- FPM-8.3

When I click on the icon which opens the logs of the relevant service I got the following for DNSmasq:   
`dnsmasq: failed to create listening socket for 127.0.0.1: Address already in use`

After some googling, I found out that some service already using the port needed for dnsmasq but I cannot / won't remove that service.

My expectation would be, that the green dot should be yellow or red, because the service couldn't start as intended.

Also, in that case I cannot open any site with *.test url. In such case, I still would like to know how to open these sites if it's possible.

### Relevant log output

```shell
dnsmasq: failed to create listening socket for 127.0.0.1: Address already in use
```

**Comment by mpociot** [comment]
This means that you already have an instance of DNSmasq running.
Maybe you have it running via brew already?

Try:

```
sudo brew services stop dnsmasq
```

**Comment by mpociot** [comment]
Feel free to re-open this if you still need help

**Comment by roncsak** [comment]
> Feel free to re-open this if you still need help

Hi @mpociot , is it possible to reopen this somehow? 🤔
