### ISSUE TITLE
[Bug]: Failed to Open .test Files on macOS: DNS Address Not Found Despite Dnsmasq Connection

### ISSUE THREAD

**Issue by dikeshraj** [beyondcode/herd-community#1118]
### Platform

macOS

### Operating system version

macOS 15 Sequoia 15.0.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.11.1 build 34

### Bug description

In macOS, we tried three different versions as suggested in the GitHub issue solutions, but the .test file does not open. In the menu bar, Dnsmasq shows as green, but when attempting to open, we receive the following message:

This site can’t be reached.
project.test’s DNS address could not be found. Diagnosing the problem.
DNS_PROBE_POSSIBLE."

**Comment by mpociot** [comment]
Can you ping any .test site in the terminal? Like `ping foo.test`?
Do you see any logs next to DNSMasq?

**Comment by dikeshraj** [comment]
When I run ping foo.test in the terminal, I get:

ping: cannot resolve foo.test: Unknown host

Also, I don’t see any logs in DNSMasq.

**Comment by mpociot** [comment]
Alright, does the following file exist?
`/etc/resolver/herd`

You can get the content via:

```
less /etc/resolver/herd
```

**Comment by dikeshraj** [comment]
No, got No such file or directory.

**Comment by mpociot** [comment]
Oh sorry, told you the wrong filename. Should be `/etc/resolver/test`

Also check if any dnsmasq services are potentially running already: `sudo ps aux | grep dnsmasq`

**Comment by dikeshraj** [comment]
When I ran less /etc/resolver/test, I saw the output:

nameserver 127.0.0.1
nameserver 127.0.0.1

Next, I checked if any dnsmasq services were potentially running by using the command:

sudo ps aux | grep dnsmasq

nobody           7211   0.0  0.0 410761984    768   ??  S     3:53PM   0:00.03 /Applications/Herd.app/Contents/Resources/dnsmasq-arm64 --keep-in-foreground --conf-file=/Users/dikesh/Library/Application Support/Herd/config/dnsmasq/dnsmasq.conf
dikesh           9183   0.0  0.0 410734816   1552 s002  S+    4:33PM   0:00.00 grep dnsmasq

**Comment by dikeshraj** [comment]
Do I need to take any further action on my side, or should I wait for another version release to resolve the issue?

**Comment by mpociot** [comment]
This looks all good to me 🤔 
Does the config file exist as well? `/Users/dikesh/Library/Application Support/Herd/config/dnsmasq/dnsmasq.conf`?

Do you have any special network settings? Like using a VPN?

You could try editing the `/etc/resolver/test` file and remove one "nameserver ..." line, as it should only be in there once, but I don't think that's the problem.
If you edit the file, try stopping/restarting all Herd services to see if that fixed the issue.

**Comment by dikeshraj** [comment]
When run nano /Users/dikesh/Library/Application Support/Herd/config/dnsmasq/dnsmasq.conf

 I saw the output:

address=/.test/127.0.0.1
listen-address=127.0.0.1

I don't use any network settings, and I have tried three versions of Herd and read all the bug solutions on GitHub, but I still cannot resolve the issue. What should I do next?

**Comment by mpociot** [comment]
Did you try removing the duplicate nameserver settings?

**Comment by dikeshraj** [comment]
Yes, sir, but it still doesn't resolve. I always get the error:

This site can’t be reached
project.test refused to connect.

**Comment by Karkianup** [comment]
Sometimes, Herd’s internal settings can get misconfigured. Go to: 
/Users/yourusername/Library/Application Support/Herd

Inspect Herd’s configuration files, specifically those related to ports and .test domain resolution

**Comment by dikeshraj** [comment]
@mpociot sir,I updated to the new version of Herd, but these issues were not resolved.

This site can’t be reached
project.test refused to connect.
Try:

Checking the connection
[Checking the proxy and the firewall](chrome-error://chromewebdata/#buttons)
ERR_CONNECTION_REFUSED

**Comment by hh-0** [comment]
I'm facing the same issue. Herd status shows Nginx, Dnsmasq, and FPM-8.3 as green. But "brew services list" shows none of them are running

**Comment by sschlein** [comment]
@hh-0 That's because Herd does not use Homebrew 🙂

**Comment by hh-0** [comment]
I found my issue. I was dumb.  I'm using Edge and it's using a different DNS service provider in the Settings. Switching it to "Use current service provider" fixed the issue.

**Comment by MalinStalAtWork** [comment]
> dnsmasq/dnsmasq.conf

hello! I have the same problem. i dident have this dnsmasq/dnsmasq.conf my cofig file says 82 and 83?? how to fix this?

**Comment by sschlein** [comment]
@MalinStalAtWork @dikeshraj Do you still wait for solutions or have you either given up or found the solution? It's very very likely simething in your own DNS settings, a VPN, company proxy, etc and not directly related to Herd.

**Comment by dikeshraj** [comment]
This issue is fixed in my case. Please uninstall Herd, then go to the Library folder, and navigate to the Cache folder. Inside the Cache folder, you will find a Herd folder. Delete this folder, then reinstall Herd. The issue should be resolved. If it is not fixed, let me know, and I will help you further.
