### ISSUE TITLE
[Bug]: Links with spaces are not properly escaped

### ISSUE THREAD

**Issue by nmrdxt** [beyondcode/herd-community#112]
### Operating system version

macOS Ventura 13.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.1.2 (Build: 13)

### Bug description

I've noticed it with Zsh's shell script – Herd injects its relevant domain names, it does not properly escape the path.

For example, it injects:

Library/Application Support/Herd/config/php/82/

Instead of:

Library/Application\ Support/Herd/config/php/82/

This causes all sort of issues.

I might be missing something silly here, tho, it's been a long day hehe

### Steps to reproduce

You can see the injected paths in the relevant shell scripts such as .zshrc, etc

**Comment by mpociot** [comment]
Which issues do you see exactly? 
The paths are wrapped in quotes, so this shouldn't be an issue.

**Comment by nmrdxt** [comment]
Thank you for the prompt response. 

Unfortunately, it is an issue, although the issue might not be within Herd. But just as an example – If I try to use Expose, the returned error is related to the unescaped path. Once I update the shell script with the added backslash, expose works normally. It also happens with other valet related commands, such as valet secure or start.

Thanks!

**Comment by nmrdxt** [comment]
The issue I believe is when injecting paths into variables, wrapping the paths with quotes does not inject the path with the quotes. To inject the path with the quotes and avoid issues, you might need to add escaped quotes, or use single quotas.

Instead of:

export PATH="/Library/Application\ Support/Herd/bin/":$PATH

This might work better:

export PATH="'/Library/Application\ Support/Herd/bin/'":$PATH

**Comment by mpociot** [comment]
Valet had an issue when an environment contained a space, which should be fixed now.
