### ISSUE TITLE
[Bug]: PHP 8.4.0RC3 missing redis extension

### ISSUE THREAD

**Issue by ejunker** [beyondcode/herd-community#1120]
### Platform

macOS

### Operating system version

macOS Sonoma 14.7

### System architecture

M3

### Herd Version

1.11.1

### PHP Version

PHP 8.4.0RC3 (cli) (built: Oct 25 2024 10:50:08) (NTS)

### Bug description

I was using PHP 8.3.13 and then installed PHP 8.4.0RC3. The first thing I noticed is that the redis extension was not installed.

### Steps to reproduce

1. install PHP 8.4.0RC3
2. open a new shell
3. verify PHP version `php -v` PHP 8.4.0RC3 (cli) (built: Oct 25 2024 10:50:08) (NTS)
4. Run `php -m | grep redis` and notice that it does not show redis

I also ran `php -i` and looked at the `Configure Command` and do not see `--enable-redis`

Configure Command =>  './configure'  '--prefix=' '--with-valgrind=no' '--enable-shared=no' '--enable-static=yes' '--disable-all' '--disable-cgi' '--disable-phpdbg' '--enable-cli' '--enable-fpm' '--disable-embed' '--disable-micro' '--enable-intl' '--enable-pdo' '--with-sqlite3=/Users/runner/work/static-php-builder/static-php-builder/buildroot' '--with-pdo-sqlite' '--with-curl' '--with-zlib' '--with-zlib-dir=/Users/runner/work/static-php-builder/static-php-builder/buildroot' '--with-openssl=/Users/runner/work/static-php-builder/static-php-builder/buildroot' '--with-openssl-dir=/Users/runner/work/static-php-builder/static-php-builder/buildroot' '--enable-tokenizer' '--enable-bcmath' '--with-bz2=/Users/runner/work/static-php-builder/static-php-builder/buildroot' '--enable-calendar' '--enable-dba' '--enable-ftp' '--with-iconv=/Users/runner/work/static-php-builder/static-php-builder/buildroot' '--enable-mysqlnd' '--with-mysqli' '--enable-mbstring' '--enable-mbregex' '--enable-xml' '--enable-simplexml' '--enable-ctype' '--enable-dom' '--enable-filter' '--enable-session' '--enable-fileinfo' '--with-pdo-mysql' '--enable-posix' '--enable-sockets' '--enable-shmop' '--with-sodium' '--enable-sysvmsg' '--enable-sysvsem' '--enable-sysvshm' '--enable-gd' '--with-zip=/Users/runner/work/static-php-builder/static-php-builder/buildroot' '--with-gmp=/Users/runner/work/static-php-builder/static-php-builder/buildroot' '--enable-xmlwriter' '--enable-phar' '--enable-exif' '--enable-xmlreader' '--with-readline=/Users/runner/work/static-php-builder/static-php-builder/buildroot' '--enable-pcntl' '--enable-soap' '--with-libxml=/Users/runner/work/static-php-builder/static-php-builder/buildroot' '--with-ffi' '--enable-zend-signals' '--with-pgsql=/Users/runner/work/static-php-builder/static-php-builder/buildroot' '--with-pdo-pgsql=/Users/runner/work/static-php-builder/static-php-builder/buildroot' '--with-ldap=/Users/runner/work/static-php-builder/static-php-builder/buildroot' '--with-xsl=/Users/runner/work/static-php-builder/static-php-builder/buildroot' '--enable-igbinary' '--enable-zstd' '--with-libzstd=/Users/runner/work/static-php-builder/static-php-builder/buildroot' '--with-gettext=/Users/runner/work/static-php-builder/static-php-builder/buildroot' 'PKG_CONFIG=/Users/runner/work/static-php-builder/static-php-builder/buildroot/bin/pkg-config' 'PKG_CONFIG_PATH=/Users/runner/work/static-php-builder/static-php-builder/buildroot/lib/pkgconfig'

**Comment by mpociot** [comment]
I just published a new 8.4.0 RC3 build with Redis included!
