### ISSUE TITLE
[Bug]: site seach is not preserved but applied, when reopen after closing.

### ISSUE THREAD

**Issue by gps-dev-team** [beyondcode/herd-community#1127]
### Platform

macOS

### Operating system version

macOS Sequoia 15.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.11.2

### Bug description

Site search removed from search box but applied to site list.

### Steps to reproduce

Search for site

<img width="1028" alt="image" src="https://github.com/user-attachments/assets/9e5b095a-c449-442f-814a-435187334d3c">

After closing the screen show the following result.
<img width="1028" alt="image" src="https://github.com/user-attachments/assets/873144e1-dd9b-48b1-8270-88a8f8fee5d3">

To get all site back need to do search and remove

**Comment by mpociot** [comment]
This is now fixed in version 1.12.0
