### ISSUE TITLE
[Bug]: Launch at Login setting reverted after each update

### ISSUE THREAD

**Issue by PeteBishwhip** [beyondcode/herd-community#1129]
### Platform

macOS

### Operating system version

macOS Sequoia 15.0.1 (24A348)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.11.2 (Build 35)

### Bug description

I have a prefence **not** to launch Herd at Startup as it interferes with Docker ports I require for some projects.

Each and every time I update Herd, this setting is reverted back to Launch at Startup and has to be turned off again.

### Steps to reproduce

1. Install a version of Herd that is not latest (Go back one version)
2. Disable "Launch at Startup"
3. Install the update
4. ASSERT: Launch at Startup is checked and on reboot, Herd launches.
5. EXPECT: Launch at Startup to remain unchecked and on reboot, Herd does not launch.

**Comment by sschlein** [comment]
We'll look into that, I thought that was resolved a while ago🤔

Sorry for the inconvenience.

**Comment by PeteBishwhip** [comment]
If there's any specific log I might be able to provide to you, just let me know. Happy to help. It's not the worst bug in the world. It's just annoying :D

**Comment by mpociot** [comment]
@PeteBishwhip I am unable to reproduce this issue, and it seems like you're also the only one who has reported this.
Please see if something else is preventing the userdefaults to be written or something like that.

I tried this on multiple different macs as well as on virtual machines varying from macOS 14 to 15.1 without success.

**Comment by hebbet** [comment]
i guess you mean #1013
