### ISSUE TITLE
[Bug]: The process has been signaled with signal "6"

### ISSUE THREAD

**Issue by plompd** [beyondcode/herd-community#113]
### Operating system version

Ventura 13.5

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.1.2 (build 13)

### PHP Version

PHP 8.2.8

### Bug description

I'm trying to run Statamic CMS with the Laravel Herd. It seems that whenever I use an Image Processing tool, it fails to run and I get this error:

`The process has been signaled with signal "6"`

Statamic uses Glide, which you can configure to use either `Imagick` or `GD`. Both are not working.
I see that `Imagick` is installed with Herd, so I'm not sure if I'm missing something here?

### Steps to reproduce

Use the `{{ glide }}` tag in an Antlers view inside a Statamic project.

### Relevant log output

```shell
https://flareapp.io/share/LPdkOVNm
```

**Comment by mpociot** [comment]
Probably related to #150
