### ISSUE TITLE
[Bug]: Xdebug is not working anymore after update 1.11.2 on Macbook pro M2

### ISSUE THREAD

**Issue by mdierks83** [beyondcode/herd-community#1130]
### Platform

macOS

### Operating system version

Mac OS Sequoia 15.0.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.11.2

### PHP Version

PHP 8.3

### Bug description

I have a series of projects running on different PHP versions, but Xdebug is no longer functioning in any of them. Despite my attempts to adjust the settings and restart the environment, nothing seems to work. What else can I do to troubleshoot this issue?

### Steps to reproduce

Update to 1.11.2 version with Macbook pro m2

**Comment by sschlein** [comment]
Why does "isn't working anymore" mean?

**Comment by mdierks83** [comment]
When I set a breakpoint in PhpStorm and refresh the page, the debugger no longer pauses at the breakpoint, nor does it return to PhpStorm. This used to work perfectly, but as of today, it suddenly stopped working across all projects. The only related change I made today was running an update of Herd

**Comment by sschlein** [comment]
Can you try to force-stop and restart all services? It sounds like there's an old process from the previous version running or so – you can hold the option key while opening the system try menu to trigger the force stop.

**Comment by sschlein** [comment]
I think I found an – unfortunate – cleanup commit so it might be broken right now. If I can confirm and reproduce that with the team, we are likely publishing a fix or at least upload a beta build until the release next Tuesday.

You can enable Xdebug by manually copying the content from the debug.ini file to your normal php.ini and while I know that this is not a good long term solution, we might need to provide a fix for that, sorry.

**Comment by mdierks83** [comment]
Yes... it works! Copying the contents into the regular php.ini did indeed solve the issue for now. Thanks for your help, and I’ll keep an eye out for the update next Tuesday.

**Comment by sschlein** [comment]
I'll keep that open until it's fixed so that others can find the issue

**Comment by speedball73** [comment]
I added the lines from debug.ini but for it to work I have to delete the server (PHP->Servers) in PhpStom (every time after a reboot).

**Comment by tnorthcutt** [comment]
Same issue here, thanks for opening this @mdierks83

**Comment by wesleylether** [comment]
+1

**Comment by tjerkruyter** [comment]
+1

**Comment by x-dragos** [comment]
+1

**Comment by mpociot** [comment]
This is now fixed in version 1.12.0
