### ISSUE TITLE
PHP Deprecated realpath()

### ISSUE THREAD

**Issue by nassiry** [beyondcode/herd-community#1131]
### Platform

Windows

### Operating system version

Windows 10 home 22h2 64 bit

### System architecture

Windows

### Herd Version

1.11.1

### PHP Version

8.3.12

### Bug description

In windows PowerShell run herd tinker or herd site-information it will return ```PHP Deprecated realpth(): Passing null to parameter #1 ($path) of type string is Deprecated in phar://C:/Users/username/.config/herd/bin/herd.phar/cli/Valet/Herd.php on line 50```

### Steps to reproduce

Use existing laravel project the project folder I have in desktop, link the project open powershell and type herd tinker.

**Comment by sschlein** [comment]
We've identified the issue in Herd and we'll fix that in the next version for next week (12th Nov)

**Comment by nassiry** [comment]
@mechelon , as i debug the issue more deeply. Here is how to reproduce. 

- link existing laravel project. Play around with `tinker`
- unlink the project by running `herd unlink project-name` and link back the project from UI try `tinker` it won't work this time.
- completely close herd and reopening the `tinker` will work again.
- same process for site-information ... but with a bit different,  in first linking site-information worked with Deprecated message on top. The second option, it will also stop working

**Comment by mpociot** [comment]
This is now fixed in version 1.12.0
