### ISSUE TITLE
[Bug]: Herd Pro - MySQL service data files are included in Time Machine backups

### ISSUE THREAD

**Issue by hjanos-bc** [beyondcode/herd-community#1132]
### Platform

macOS

### Operating system version

macOS Sequoia 15.1 (24B83)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.11.1 (Build: 34)

### PHP Version

PHP 8.3.13 (cli) (built: Oct 25 2024 00:21:18) (NTS)

### Bug description

I have discovered that MySQL service's data files are included in the Time Machine backups.

Since Herd is for local development, I would imagine users very rarely need backups of development database files, but because it is changing frequently, it inflates the backups.

Herd could add metadata for these files so they are excluded from Time Machine backups.

I would imagine this can be true for more services, especially database ones.

I think that depending on the point of view, this can be considered both a feature request or a bug report.

### Steps to reproduce

Add MySQL service in Herd Pro
Seed the database
Make sure Time Machine has a backup configured and make a snapshot
Open data directory for the service
Open Time Machine
Snapshots of the database files are there

**Comment by mpociot** [comment]
We will add a note about the service location and the fact that they might get backed up by default. If you wish to manually exclude those files, you can do this - but I think it's better to not automatically exclude files from our end.
