### ISSUE TITLE
[Bug]: HERD slow on project with inertia

### ISSUE THREAD

**Issue by RomkaLTU** [beyondcode/herd-community#1134]
### Platform

Windows

### Operating system version

Windows 11 Pro 24H2

### System architecture

Windows

### Herd Version

1.11.1

### PHP Version

PHP 8.3.12

### Bug description

TTFB is 2s on every refresh when rendering innetia page (vuejs). If I switch to blade render everything is fine. Same project working good on macos.

### Steps to reproduce

Render any inertia component something like this:

```
Route::get('/', function () {
    return Inertia::render('Welcome', [
        'canLogin' => Route::has('login'),
        'canRegister' => Route::has('register'),
        'laravelVersion' => Application::VERSION,
        'phpVersion' => PHP_VERSION,
    ]);
});
```

**Comment by RomkaLTU** [comment]
> I have had issues with Herd being slow when minimised. Once I opened the GUI, the speed difference was quite significant.

Doesn't help in my case.

**Comment by sschlein** [comment]
Can you both reproduce this with a fresh Laravel install with Breeze at Intertia and Vue? I've set this up and switching between the homepage, login, registration works pretty quickly and without the delay. I can create an account, log in and go to my profile and only the first request to the site in the browser is slowish – all requests to other pages of the app after that run without issues and fast.

**Comment by rd-aemetriks** [comment]
Yes, if you're navigating with Link it's OK, but a full page reload is slow - not just the first but every full page refresh. When developing, I just like to hit CMD/CTRL + R. So as I understand, this is not fixable at the moment.

**Comment by RomkaLTU** [comment]
Yes, if you're navigating with Link it's OK, but a full page reload is slow - not just the first but every full page refresh. When developing, I just like to hit CMD/CTRL + R. So as I understand, this is not fixable at the moment.

**Comment by sschlein** [comment]
Oh, I can actually reproduce this behavior and we'll look into that.

**Comment by mpociot** [comment]
Alright so the problem comes from initializing a Inertia SSR project, but not starting the actual SSR server.

You can do this via:

```
php artisan inertia:start-ssr
```

Then the requests will be fast again

**Comment by jellebreuer** [comment]
This fixed the issue for me, from 2s back to 20ms,
put this in your .env file while developing
INERTIA_SSR_ENABLED=false

Im guessing the check for the ssr server is faster on osx/linux and it needs a full 2s timeout on windows
