### ISSUE TITLE
[Bug]: 502 on fresh install

### ISSUE THREAD

**Issue by kylemilloy** [beyondcode/herd-community#1138]
### Platform

macOS

### Operating system version

macOS 15.0.1

### System architecture

Intel (x86)

### Herd Version

1.11.2 Build 35

### Bug description

All sites are 502 and there are no logs in nginx.

I did a fresh install of herd and bought a license and clicked the link on the webpage that deep linked me into the activation and skipped the onboarding steps. Tried uninstalling and reinstalling completely as well as a reboot after uninstall and I can't get the onboarding to pop back up to confirm this. Tried changing PHP versions, tried removing the helper to trigger the onboarding...notta.

**Comment by kylemilloy** [comment]
<img width="1224" alt="Screenshot 2024-11-08 at 17 42 38" src="https://github.com/user-attachments/assets/1c8a1779-6437-49ec-9855-db44cb2aa5a6">

**Comment by mpociot** [comment]
Did you go through the onboarding partially though? 

Because it looks like PHP is missing/not installed. Did the Herd helper get installed for you?

You can always install PHP via the settings

**Comment by kylemilloy** [comment]
Yeah I removed the helper and booted herd and finished going through the onboarding/installer and it worked as per your recommendation [here](https://github.com/beyondcode/herd-community/issues/1096) but nginx still looks to be missing. If you look I do have PHP installed (php83) and that is accessible in the cli but it's giving me 502s still so I think it's an nginx thing. I don't use valet and was strictly doing sail beforehand

**Comment by kylemilloy** [comment]
[This](https://github.com/beyondcode/herd-community/issues/10#issuecomment-1646678682) ended up being the fix
