### ISSUE TITLE
[Bug]: Herd dump intercept display anonymous error.

### ISSUE THREAD

**Issue by KhairulAzmi21** [beyondcode/herd-community#1149]
### Platform

macOS

### Operating system version

macOS Sonoma 14

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.1.12

### PHP Version

PHP 8.3

### Bug description

![image](https://github.com/user-attachments/assets/b721986a-05d0-4657-8adf-c5943fd952dd)

This Error happen randomly when I open herd dump . 

When I refresh on the same page, the error got . 

### Steps to reproduce

I go to any link of my site .
error appear .

**Comment by sschlein** [comment]
Do you have binary data in your database? If yes, can you disable query logging in the dumps and see if the error goes away? We might need a fix for that if my guess is correct.

**Comment by KhairulAzmi21** [comment]
> Do you have binary data in your database? If yes, can you disable query logging in the dumps and see if the error goes away? We might need a fix for that if my guess is correct.

yes error came from query , 

but not neccesary binary data . sometimes without it also we are getting this error .

**Comment by mpociot** [comment]
This issue was fixed in Herd 1.12.0

Please update your version of Herd
