### ISSUE TITLE
[Bug]: Not able to uninstall old php version

### ISSUE THREAD

**Issue by Nothing-Works** [beyondcode/herd-community#1152]
### Platform

Windows

### Operating system version

Win 10

### System architecture

Windows

### Herd Version

1.12.0

### PHP Version

8.4.1

### Bug description

Not able to uninstall pervious php versions

### Steps to reproduce

![image](https://github.com/user-attachments/assets/f6ebe984-f20a-4161-9c95-15ea9143322f)
after I installed two php versions, I am not able to uninstall one of the PHP version.

**Comment by sschlein** [comment]
Did you right click them and click "uninstall"?

**Comment by Nothing-Works** [comment]
ok, good to know, no, I didn't, I thought I can just uncheck the checkbox. loll
