### ISSUE TITLE
[Bug]: Did you guys stop supporting custom TLDs and not put it in the changelog?

### ISSUE THREAD

**Issue by tomfinitely** [beyondcode/herd-community#1155]
### Platform

macOS

### Operating system version

macOS Sonoma 14.7.1 (23H222)

### System architecture

ARM

### Herd Version

1.12

### Bug description

Title says what it does:

Custom TLDs no longer work for new sites, but they do for existing sites — the extra great part is how I lost multiple billable hours trying to figure out WTF happened because it wasn't documented anywhere.

### Steps to reproduce

Use a custom domain for months, update Herd one night, create a new site the next day, spend hours pulling your hair out.

### Relevant log output

```shell
N/A
```

**Comment by mpociot** [comment]
We didn't remove support for custom TLDs, no. Custom TLDs still work via `herd tld` even though it still requires a bit of manual work (which was always the case). Nothing changed regarding that implementation as far as I know.

Which version of Herd were you using before?

**Comment by tomfinitely** [comment]
I set up .local as my TLD using the `herd tld` command (`herd tld local` to be specific).

I do have dnsmasq set up through homebrew, however, it's not running since my understanding is that Herd has it built in. I guess it's possible there could be something in my PATH that has led to a conflict.

My output for `herd tld` was `local` — now it's `test` because I've acquiesced in favor of having consistently stable dev sites vs using custom TLDs  ¯\_(ツ)_/¯ 

`/Users/me/Library/Application Support/Herd/bin/
/Users/me/.nvm/versions/node/v20.10.0/bin
/opt/homebrew/bin
/opt/homebrew/sbin
/usr/local/bin
/System/Cryptexes/App/usr/bin
/usr/bin
/bin
/usr/sbin
/sbin
/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin
/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin
/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin
/Library/Apple/usr/bin
/Users/tomfinley/.composer/vendor/bin
/Users/tomfinley/.orbstack/bin
/opt/homebrew/bin
/Users/me/.composer/vendor/bin`
