### ISSUE TITLE
[Bug]: Nginx cannot start due to invalid variable name error in nginx.conf

### ISSUE THREAD

**Issue by aneeskhan47** [beyondcode/herd-community#1157]
### Platform

Windows

### Operating system version

Windows 11 Version 23H2 (OS Build: 22631.4460)

### System architecture

Windows

### Herd Version

1.12.0

### Bug description

Hi,

I did a complete fresh install of Herd on my windows 11 system (no prior of any other lamp or wamp or similar installation)

I ran the installed as administrator and ran herd as administrator too but when i run Herd the php service is up and running but nginx seems not to starting due to some invalid variable in the nginx.conf file located in my `C:\Users\Anee$\.config\herd\config\nginx/nginx.conf`

upon my investigation there seem to be problem in line `include herd.conf` inside the nginx.conf file:

![image](https://github.com/user-attachments/assets/438b6bdf-65a3-44b1-8d6a-628fade5f16b)

If I comment out this line, then nginx starts but I can't access my site because the main herd.conf is commented out. so seems like some invalid variable in `herd.conf` file which i couldn't find.

### Relevant log output

```shell
2024/11/23 08:16:21 [emerg] 14348#6896: invalid variable name in C:\Users\Anee$\.config\herd\config\nginx/nginx.conf:143
```

**Comment by mpociot** [comment]
Could you try and include the configuration file with an absolute path? I have a feeling that this is related to the dollar sign in your username.

**Comment by aneeskhan47** [comment]
> Could you try and include the configuration file with an absolute path? I have a feeling that this is related to the dollar sign in your username.

Yes, you are right, I just installed Herd on my other Windows 10 system which has the user of "Anees" and now it works 😄 

Can we do something to avoid this if someone has a dollar sign in their Windows user name? like escaping the character or something so that future users don't face this issue

**Comment by mpociot** [comment]
I'll see what's the best way for us to fix this.

On your device, just replace `include herd.conf` with:

```
include "C:\Users\Anee$\.config\herd\config\nginx\herd.conf"
```

And it'll work :)
