### ISSUE TITLE
[Bug]: Tailwind and CSS styles not working using Expose

### ISSUE THREAD

**Issue by vbaguet** [beyondcode/herd-community#1159]
### Platform

Windows

### Operating system version

Windows 11 Pro 10.0.26100

### System architecture

Windows

### Herd Version

1.12.0

### PHP Version

PHP 8.3.0

### Bug description

When exposing my application in local using Expose within Herd Pro, the styles are not working. Is there somethin I can do to prevent this? I would like to show my project to a client.

Thank you.

**Comment by cotiga** [comment]
Assets being served over HTTP while the public URL is HTTPS
The issue with Vite and Expose yet no fix has been provided.
This makes it very frustrating to share a project without hacking around the code or configuration.
