### ISSUE TITLE
[Feature Request]: Change File Upload Size Limit

### ISSUE THREAD

**Issue by gjsman** [beyondcode/herd-community#116]
### Feature Description

Hello,

I wish it was easier to configure the upload size limit in both NGINX and PHP from Herd; because the default 2MB limit (and the steps required to change it) is a bit painful.

Gabriel

### Is this feature valuable for other users as well and why?

Well, hopefully, I'm not the only one who needs files bigger than 2MB.

**Comment by nam-co** [comment]
I believe this is already in the App, @gjsman don't forget to close the issue

**Comment by gjsman** [comment]
> I believe this is already in the App, @gjsman don't forget to close the issue

Thank you for the reminder. I’m closing the issue as this feature has been added since it was filed.
