### ISSUE TITLE
[Bug]: Site-specific PHP version ignored; defaults to global version

### ISSUE THREAD

**Issue by RanaMoizHaider** [beyondcode/herd-community#1162]
### Platform

macOS

### Operating system version

macOS Sequoia 15.1.1 (24B91)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.11.2 (Build: 35)

### Bug description

I have to change php version globally to access each site. Site specific PHP version is not picked up by default.

Here you can see errors in preview when I selected PHP 8.4 globally while having PHP 8.3 for the site db.test specifically
<img width="1264" alt="image" src="https://github.com/user-attachments/assets/437fd4f2-3524-4d6d-a579-f2549f43833f">

And here you can see no errors when I selected PHP 8.3 globally while still having PHP 8.3 specifically for the site
<img width="1266" alt="image" src="https://github.com/user-attachments/assets/f44740e0-4acc-4071-bdd0-139d573a4267">

Sites should not have any effect when I change global PHP version and should stick to the version specified for them (I think that's how it should work, Please correct me if it should not). I have sites that use PHP 7.4 and I have to change global version every time I want to work with them.

**Comment by sschlein** [comment]
Can you please update to Herd 1.12.0? Herd 1.12 improves PHP 8.4 support, so setting up 8.4 globally definitely makes a difference. 

How did you set the isolated versions? It should work exactly how you describe as long as you have all required PHP versions installed.

**Comment by RanaMoizHaider** [comment]
Issue is not specific to PHP 8.4. And I also faced this bug in earlier versions of Herd when PHP 8.4 was not even in the available versions. if I have a project with version 8.1 I have to change it to 8.1 globally. site specific version is ignored.

Also I updated Herd to 1.12.0 and still facing this issue.
<img width="1250" alt="image" src="https://github.com/user-attachments/assets/92740aa4-e4bc-4af8-9f9f-f3916af8edee">

**Comment by RanaMoizHaider** [comment]
I have all php versions installed that are needed by different projects I have. And I do select php version required by the project in site general settings in Herd. Is there anything else that needs to be done?
<img width="894" alt="image" src="https://github.com/user-attachments/assets/c2c890a8-cca3-448e-906c-d40469ef5be6">

**Comment by sschlein** [comment]
Are you 100% sure that nginx from herd works on your machine and that there is no old nginx process from Homebrew or so that is serving these sites?

You can try with `brew services list` and checking the nginx of Herd.
