### ISSUE TITLE
Dumps not working

### ISSUE THREAD

**Issue by stephanesoares** [beyondcode/herd-community#1163]
### Platform

Windows

### Operating system version

Windows 11 (24H2 26100.2454)

### System architecture

Intel (x86)

### Herd Version

1.13.0

### PHP Version

8.3.14

### Bug description

Dumps don't fire. Nothing has changed on the PC, the only thing has been updates to the herd.

Its a bug of last version?

**Comment by mpociot** [comment]
I'm still able to see and call dumps with version 1.13.0 on Windows 🤔 
Are you trying to dump something via the CLI or via the browser? Did you try and restart the services?

**Comment by stephanesoares** [comment]
Via browser, yes i restart services, and reinstall herd

**Comment by stephanesoares** [comment]
Yes its enabled at UI, 

via cli not works too

I will uninstall and delete the configuration files, and install again.

**Comment by stephanesoares** [comment]
uninstalling, deleting settings, and installing again, the problem continues

**Comment by stephanesoares** [comment]
I create a new laravel instalation,

with only this in web.php

Route::get('/', function () {
    dump('testing');
    return view('welcome');
});


Yes is all enabled

**Comment by mpociot** [comment]
Does it make a difference when you uncheck everything?

**Comment by stephanesoares** [comment]
Nope. continue no see nothing on page, and nothing at dumps window

**Comment by mpociot** [comment]
Well, I'm starting to run out of ideas.
If the interception works, this means that the communication between Laravel and Herd is not working.

Could this be some firewall issue that a local connection to port 9001 is not possible?
Have you tried changing the port?
Can you access `http://localhost:9001/version` in your browser?

**Comment by stephanesoares** [comment]
![{F74239BA-368B-41C1-813B-06E9010D5A81}](https://github.com/user-attachments/assets/e310c81c-dfae-4cf4-b3c9-5cc302a88e55)

**Comment by mpociot** [comment]
Can you share the content of your Herd log file?

```
%USERPROFILE%\AppData\Roaming\Herd\logs
```

You can always try and downgrade to a previous version, but version 1.13.0 changed nothing regarding dumps at all, so I don't think that going back to 1.12.0 will fix things.

**Comment by stephanesoares** [comment]
[main.log](https://github.com/user-attachments/files/17947920/main.log)

**Comment by stephanesoares** [comment]
![{AEFAE1B1-FE89-4947-B563-9B70C67F00FF}](https://github.com/user-attachments/assets/799f7eb2-f1e1-43a7-ac62-bf7c779fcbb4)


Continues..... Can be windows updates or something ?

**Comment by stephanesoares** [comment]
Another computer with this

![image](https://github.com/user-attachments/assets/85b6452b-764f-4a31-a28c-c9d1c2a27ca2)


works, 


i will run pending update of windows, and verify if stop works at another pc

**Comment by stephanesoares** [comment]
After updated to Windows 11 (24H2 26100.2454) another computer continue works, so its another thing. have you any idea?

**Comment by stephanesoares** [comment]
@mpociot i solved, problem was ports, i remove everything, fresh install with no configs, no appdata etc

i try change ports internal and helper and solves...
