### ISSUE TITLE
[Bug]: Composer not found

### ISSUE THREAD

**Issue by AlexVanSteenhoven** [beyondcode/herd-community#1164]
### Platform

Windows

### Operating system version

Windows 11 (OS Build 22631.4460)

### System architecture

Windows

### Herd Version

1.13.0

### Bug description

When I create a new project using herd I get the message that composer is not recognized as a command.

![image](https://github.com/user-attachments/assets/44f2cf3f-d608-4542-ab04-c180530debc0)

### Relevant log output

```shell
'composer' is not recognized as an internal or external command, operable program or batch file.
```

**Comment by mpociot** [comment]
Please try restarting Herd. Probably `composer` was not properly added to the PATH when Herd was first started.
You should be able to use `composer` via the CLI without any issues as well.
