### ISSUE TITLE
[Bug]: Create a new service hangs on "Extracting service - this may take a while"

### ISSUE THREAD

**Issue by LeShadow** [beyondcode/herd-community#1167]
### Platform

macOS

### Operating system version

macOS 15.1 (24B82)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.13.0

### Bug description

When I try to add a new service, it hangs for a long time (I folded laundry, I started cooking) on:

`Extracting service - this may take a while`

This happened with both:
- PostgreSQL
- Meilisearch

Is there something I am missing/something I did wrong? 
I bought the pro license, went to services, wanted to install PostgreSQL and Meilisearch.

### Steps to reproduce

1. Open Herd
2. Install pro license
3. Go to services
4. Add service
5. Select Meilisearch (1.9.0 I think the version was, it is still loading)
6. Select autostart
7. Click on "Save"
And now it hangs :/

**Comment by LeShadow** [comment]
I am so sorry for posting this bug report! 

Apparently just restarting Herd helped. It almost looks like something didn't want to complete when I wanted to install a service straight after I installed my pro license? 

So the steps to solve this for me:
1. install pro license
2. restart Herd
3. Now it works!

**Comment by mpociot** [comment]
Can you check the contents of /Users/Shared/Herd/services?

Maybe there's a broken zip file or something similar?

**Comment by chrisdeeming** [comment]
Hey @mpociot I also just activated my Pro license and seem to be experiencing the same as @LeShadow.

```
chrisdeeming [/Users/Shared/Herd/services/mysql] % ls -lah
total 355160
drwxr-xr-x  3 chrisdeeming  wheel    96B  2 Dec 14:15 .
drwxr-xr-x  3 chrisdeeming  wheel    96B  2 Dec 14:15 ..
-rwxr-xr-x  1 chrisdeeming  wheel   173M  2 Dec 14:15 8.0.36.zip
```

Seems as though the download finished nearly 15 minutes ago but I'm still on the create new service screen:

<img width="1022" alt="image" src="https://github.com/user-attachments/assets/e319426d-977e-46cb-b886-e4103a2ec01a">

I'm able to `unzip` the file without issue so doesn't appear to be a broken zip. Restarting Herd allowed me to create the service without issue.

It was very quick! I'd go as far as to say the "this may take a while" text might be a tad pessimistic. I sat here for way too long until I thought maybe something was wrong 😄
