### ISSUE TITLE
[Bug]: `~/Herd` folder gets recreated on launch even if the default was changed

### ISSUE THREAD

**Issue by lukasbestle** [beyondcode/herd-community#117]
### Operating system version

Ventura 13.5

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.1.2 (Build: 13)

### Bug description

I use `~/Sites` to host my sites, so I don't need `~/Herd`. However it is recreated every time Herd is launched.

**Expected behavior:** Herd should only create the folder on launch if it is configured as a "Herd path".

### Steps to reproduce

1. Navigate to the "General" settings
2. Delete `~/Herd` from the "Herd paths"
3. Delete the `~/Herd` folder in Finder
4. Restart Herd
5. `~/Herd` folder gets recreated

**Comment by mpociot** [comment]
Hi @lukasbestle 
Thanks for reporting - good catch, I'll make sure that the folder only gets created during onboarding 👍

**Comment by cotiga** [comment]
Solved with 1.2.0 version
Thanks Marcel

**Comment by lukasbestle** [comment]
Thanks, I can verify that this is solved.
