### ISSUE TITLE
[Bug]: Injected shell script causing noticeable lag between terminal sessions

### ISSUE THREAD

**Issue by jackwh** [beyondcode/herd-community#1172]
### Platform

macOS

### Operating system version

macOS Sequoia 15.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.13.0

### Bug description

Since installing Herd Pro a few weeks ago I've found new terminal sessions taking much longer to launch. Normally I'd expect a new `zsh` console to be interactive straight away, but whatever Herd's doing is adding a 1.5–3s delay.

I tracked it down to this part of my `.zshrc` file. If I comment it out everything goes super fast again:

```
# Herd injected NVM configuration
export NVM_DIR="/Users/jack/Library/Application Support/Herd/config/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
```

Can this be fixed or optimised?

**Comment by mpociot** [comment]
I don't think there's a lot we can do about this, I'm afraid. 

You can however simply comment out the shell script, and leave the NVM_DIR export in place. 
NVM will continue to work as is - you will only lose the automatic node version switching when you change folders. 

To apply an isolated Node version manually, you can run "nvm use" in a folder that got isolated.

**Comment by acurrieclark** [comment]
For anyone else stumbling on this issue, there are a few ways you can defer loading of NVM to aid with terminal session load time.

My current weapon of choice is to load nvm and the herd nvm config inside a wrapper function in my `.zshrc`:

```zsh
nvm () {
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
  [[ -f "/Applications/Herd.app/Contents/Resources/config/shell/zshrc.zsh" ]] && builtin source "/Applications/Herd.app/Contents/Resources/config/shell/zshrc.zsh"
  nvm "$@"
}
```

Once the function has been called for the first time, it loads the herd specific `nvm` function and config, which replaces this function. Subsequent calls are made to the newly loaded `nvm`.

**Comment by jackwh** [comment]
That's a great solution, thanks! @mpociot maybe something like this could be used to improve the slowness in a future release.

**Comment by acurrieclark** [comment]
I have discovered a few issues with this, in that node is also now lazy loaded too, and won't be available until `nvm` has been run with my setup above. I'll post back if I come up with a better setup
