### ISSUE TITLE
[Bug]: SQLSTATE[HY000] [1049] Unknown database 'laravel'

### ISSUE THREAD

**Issue by lcallif** [beyondcode/herd-community#1176]
### Platform

macOS

### Operating system version

macOS Monterey 12.6.8

### System architecture

Intel (x86)

### Herd Version

1.13.0

### PHP Version

PHP 8.2.26

### Bug description

I stop the MySQL Service in manager-osx, start the MySQL service in Herd, refresh the local site and receive the error stated above.  I cannot imagine that it is an issue with Herd, I am pretty darn sure I missed some setting needed in Herd, I just can't find it.  Just please don't embarrass me toooo bad.  :-)

BTW, VERY impressive app!

### Steps to reproduce

Stop the MySQL Service in manager-osx, start the MySQL service in Herd, refresh the localhost site......
![Screen Shot 2024-12-01 at 10 23 54 PM](https://github.com/user-attachments/assets/162d1394-2935-4da6-9efd-5c5c52dfd9bc)
![Screen Shot 2024-12-01 at 10 23 19 PM](https://github.com/user-attachments/assets/f7124ccf-3a29-47e9-bda3-2b7854ef210b)
![Screen Shot 2024-12-01 at 10 23 07 PM](https://github.com/user-attachments/assets/d80aa683-b745-4dc4-b596-85131d11ed7b)

**Comment by mpociot** [comment]
You will need to create the database manually in order to connect to it. 
When running "php artisan migrate" Laravel will detect that the database does not exist yet and ask if it should get created. 

Otherwise you can create it manually via something like TablePlus.

**Comment by lcallif** [comment]
The database exists and is available via manager-osx.  I should not need to create the db from scratch.  Rather it should be able to be added to Herd as an existing database, similar to PhpStorm.
Sorry, this is still an open issue.

**Comment by mpociot** [comment]
Well Herd creates a new MySQL service, which is now running and has no databases
. 
When you stop your existing MySQL service, your existing databases will no longer be used - as a new server is now running. 

If you want to migrate your existing database over to Herd, you can simply dump them when they are running and then re-import them into the MySQL instance that is running via Herd.

**Comment by lcallif** [comment]
Serious ? So, there is no way to get Herd to connect to an existing db ?

**Comment by mpociot** [comment]
If you want to use an existing database, you should keep using your existing database server 🤔

Well - or import it into the server managed by Herd, if you want to use that instead. 

I don't know how it works via the MySQL service you use, but maybe you can use a similar approach to easily import all of your databases:

https://laravel-news.com/migrate-mysql-from-dbngin-herd

**Comment by lcallif** [comment]
Why doesn't Herd use an existing MySQL db ?  Products such as PhpStorm will attach to an existing db.  TablePlus will attach to an existing db. Darn near any SQL tool can attach to an existing db.

I am lost as to why this would be an issue and I can't believe that I am the first or only one to have encountered this limitation.  

I was looking forward to getting rid of manager-osx, but it appears that unless I create a new db, create all the tables / views, and migrate all of the data to it, I will have no other option.

Dang....  

I will create a new "Feature" request for this later today.  For what it is worth, I am disappointed with this solution.  I just don't get this.  Nope, I don't.

Dang, Dang, Dang, and one more Dang.

Hmmmmmm, if you don't mind, could you please explain why Herd is not able to startup the MySQL Service and attach to an existing MySQL db ?  Curiosity, which may stop me in my tracks from adding this as a "Feature" request.  I know y'all have WAYYYYYY more knowledge about this stuff and would LOVE to hear the reasoning behind this...  Thank you for your time.
