### ISSUE TITLE
[Bug]: Command not found Error finding executable PHP. Quitting for safety.

### ISSUE THREAD

**Issue by creativeq-dev** [beyondcode/herd-community#118]
### Operating system version

Mac OS Ventura

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.1.2

### PHP Version

PHP 8.2.8

### Bug description

/Users/Mac-Mini/Library/Application Support/Herd/bin//herd: line 12: php: command not found
Error finding executable PHP. Quitting for safety.
Provided output from find-usable-php.php:

### Steps to reproduce

The program was uninstalled and reinstalled according to the documentation, but the error persists. Herd works correctly, but the CLI is generating errors and the Sites list is not appearing in the app ui.

### Relevant log output

```shell
/Users/Mac-Mini/Library/Application Support/Herd/bin//herd: line 12: php: command not found
Error finding executable PHP. Quitting for safety.
Provided output from find-usable-php.php:
```

**Comment by mpociot** [comment]
This is related to https://github.com/beyondcode/herd-community/issues/79#issuecomment-1659748292
Please modify the file manually at the moment, the fix will be available later this week!
