### ISSUE TITLE
[Bug]: Restarting Mac Causes Herd to Lose Activation Key

### ISSUE THREAD

**Issue by devinnived** [beyondcode/herd-community#1185]
### Platform

macOS

### Operating system version

macOS Sequoia 15.1.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.13.0

### Bug description

Restarting laptop causes Herd to lose activation key, forcing user to go login to website and copy activation key into app.

### Steps to reproduce

* Quit Herd
* Restart laptop
* Open Herd where it ask to install PHP and ask for email and activation key

**Comment by sschlein** [comment]
Can you make sure that you have the background service enabled?

https://herd.laravel.com/docs/1/troubleshooting/common-issues#the-helper-service-isnt-running

**Comment by devinnived** [comment]
Apologies for the late reply. Yes enabling the background service fixed this issue.
