### ISSUE TITLE
[Bug]: HerdHelper not starting

### ISSUE THREAD

**Issue by n-els** [beyondcode/herd-community#1189]
### Platform

Windows

### Operating system version

Windows 11 22631

### System architecture

64-bit

### Herd Version

1.13.0

### Bug description

Like many others here, I have the problem that HerdHelper does not start and therefore my projects are not accessible in the browser.

However, I can start HerdHelper manually by double-clicking (on the .exe), but that can't be the solution?
So far I have solved it by either editing the hosts file myself or starting the HerdHelper myself.

### Relevant log output

```shell
[2024-12-08 17:05:01.174] [error] HTTP Request Failed: {
  message: 'connect ECONNREFUSED 127.0.0.1:5999',
  name: 'Error',
  stack: 'Error: connect ECONNREFUSED 127.0.0.1:5999\n' +
    '    at Function.from (C:\\Program Files\\Herd\\resources\\app.asar\\node_modules\\axios\\dist\\node\\axios.cjs:837:14)\n' +
    '    at RedirectableRequest.handleRequestError (C:\\Program Files\\Herd\\resources\\app.asar\\node_modules\\axios\\dist\\node\\axios.cjs:3083:25)\n' +
    '    at RedirectableRequest.emit (node:events:517:28)\n' +
    '    at ClientRequest.<anonymous> (C:\\Program Files\\Herd\\resources\\app.asar\\node_modules\\follow-redirects\\index.js:38:24)\n' +
    '    at ClientRequest.emit (node:events:517:28)\n' +
    '    at Socket.socketErrorListener (node:_http_client:501:9)\n' +
    '    at Socket.emit (node:events:517:28)\n' +
    '    at emitErrorNT (node:internal/streams/destroy:151:8)\n' +
    '    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },..
```

**Comment by sschlein** [comment]
How does the debug file look like? Any ideas or better errors after going through https://herd.laravel.com/docs/windows/1/troubleshooting/common-issues#the-herdhelper-windows-service-isnt-working ?

**Comment by n-els** [comment]
I have reinstalled Herd because I realized that the service for the HerdHelper did not exist, now it is there and is also started at startup. I think this can be closed. Thank you!

**Comment by n-els** [comment]
Strange, but the HerdHelper service can no longer be found in the Windows Service Manager, I restarted my PC and it just disappeared.

**Comment by sschlein** [comment]
Which anti virus program dislikes Herd?

The helper changes the hosts file, so there is a chance that the program doesn't like that and thinks that it's malware. You can likely flag it as trusted somewhere in the settings of your anti virus.

**Comment by sschlein** [comment]
The only way why the helper can disappear is that either a anti-virus program removes it or there is a corporate policy installed on your machine that does it remotely.
