### ISSUE TITLE
Adding 'git' binary

### ISSUE THREAD

**Issue by comes** [beyondcode/herd-community#119]
### Feature Description

Any chance to add the git binaries as well? With the `git` binaries, it is a download herd and start doing stuff out of the box. without the need to install xcode or brew or whatever.

### Is this feature valuable for other users as well and why?

I guess so. Download herd and start doing great stuff.

**Comment by lukasbestle** [comment]
To be honest I think this is out of scope for Herd. Git is included with the macOS command line tools. Installing Xcode is not necessary.

**Comment by mpociot** [comment]
I agree that this is kind of outside the scope of Herd
