### ISSUE TITLE
[Bug]: When Herd updates to a new version, I have to re-activate15.0.1

### ISSUE THREAD

**Issue by rikh42** [beyondcode/herd-community#1192]
### Platform

macOS

### Operating system version

15.0.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.13.0

### Bug description

When Herd auto-updates, the next time I restart my computer I am taken through the full 'welcome' sequence you see the first time you ever use Herd. This warns me I will need to enter my account password (I don't need to) and then asks me to enter my license details again. It then installs PHP from scratch, even though it was already installed and up to date.

I would expect a minor version update to realise I was already using Herd and was already activated. Perhaps show me some information about what's changed, rather than treating it as a new install for a new customer.

### Steps to reproduce

Let Herd update
Restart computer

**Comment by sschlein** [comment]
Can you please check if the HerdHelper is properly installed? My guess would be that this happens on every restart but you don't restart very often and assume it's setup related:

https://herd.laravel.com/docs/1/troubleshooting/common-issues#herd-shows-the-welcome-screen-on-every-start
