### ISSUE TITLE
[Bug]: Latest Chrome version breaks Herd HTTP access

### ISSUE THREAD

**Issue by JordanDalton** [beyondcode/herd-community#1193]
### Platform

macOS

### Operating system version

macOs Sonoma Version 14.4.1

### System architecture

Intel (x86)

### Herd Version

1.13.0 (Build: 37)

### PHP Version

PHP 8.3.10 (cli) (built: Jul 30 2024 13:44:37) (NTS)

### Bug description

This morning when I opened chrome it had updated to 131.0.6778.109 (Official Build) (x86_64). As a result I keep experiencing 502 errors within Herd when attempting to access my application over non-secure (http) address.

I did attempt to set my site up with HTTPS which was unsuccessful at resolving the issue. It appears chrome is not honoring Herd's SSL certificate.

I've reset caches, settings, reinstalled Herd but to no avail.

### Steps to reproduce

1. Update to latest chrome version
2. Attempt to access app (http)
3. First page will load, but any subsequent http calls to endpoints will 502 as chrome attempts to force HTTPS.
4. Enable HTTP for site
5. 502 is still experienced.

### Relevant log output

```shell
Example.

2024/12/10 09:30:05 [error] 18488#187584: *2 upstream timed out (60: Operation timed out) while reading response header from upstream, client: 127.0.0.1, server: , request: "GET /ajax/users?per_page=200 HTTP/1.1", upstream: "fastcgi://unix:/Users/jordandalton/Library/Application Support/Herd/herd-debug.sock", host: "<redacted>.test", referrer: "http://<redacted>.test/listings"
```

**Comment by mpociot** [comment]
I don't think this issue is related to Chrome, as I don't think a browser update results in a bad gateway on nginx/FPM. 

Have you tried to restart/force stop all Herd services?
The error message indicates that you are trying to access the debug FPM service because you either have xdebug enabled manually or because Herd detected a breakpoint in your project. 

Try accessing your site without any breakpoints/by disabling xdebug.

**Comment by JordanDalton** [comment]
I was surprised as the app would work in FF but not chrome.

Disabling xdebug and breakdpoints seems to have done the trick.

**Comment by JordanDalton** [comment]
However, google still forces my app to https://myapptest/ (though I dont' have the app set to use SSL)

**Comment by mpociot** [comment]
@JordanDalton Chrome has a crazy cache when it comes to SSL enabled sites 😅
