### ISSUE TITLE
[Bug]: enabling access_log

### ISSUE THREAD

**Issue by robjchan** [beyondcode/herd-community#1199]
### Platform

macOS

### Operating system version

macOS 15.2 (24C101)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

Herd 1.13.0

### Bug description

I'm trying to enable Nginx access log.

I have added this to herd.conf and restarted Herd

access_log "/Users/****/Library/Application Support/Herd/Log/nginx-access.log";

After visiting the site the file is created however it's empty.  Am I missing something?

### Steps to reproduce

added 
access_log "/Users/****/Library/Application Support/Herd/Log/nginx-access.log";

to  
/Users/****/Library/Application Support/Herd/config/nginx/herd.conf

**Comment by sschlein** [comment]
Does the site have a dedicated nginx conf?

You can check that in the valet(sites folder of your Herd config folder 🙂

**Comment by robjchan** [comment]
Ahh I see what you mean.

I undid my change to  /Users/****/Library/Application Support/Herd/config/nginx/herd.conf

and made the change to /Users/****/Library/Application Support/Herd/config/valet/Nginx/mysite.test

restarted herd via "herd restart" and just like magic nginx-access.log is beng populated.

Thanks for the prompt and hope it helps someone else
