### ISSUE TITLE
[Feature Request] Equivalent of Valet Link

### ISSUE THREAD

**Issue by deleugpn** [beyondcode/herd-community#12]
### Feature Description

I don’t want to add an entire folder and have all its subfolders linked automatically as that doesn’t work on my workflow. Valet let me link a specific folder, which would be great to replicate here.

### Is this feature valuable for other users as well and why?

It seems to be basic functionality on Valet which would be lost here

**Comment by mpociot** [comment]
You can use the "herd" CLI command, just like you would use valet. 
So running "herd link" would link a single folder.
