### ISSUE TITLE
[Bug]: Nginx Errors - Address Already in Use?

### ISSUE THREAD

**Issue by jacobgraf** [beyondcode/herd-community#120]
### Operating system version

macOS Sonoma 14.0 Public Beta

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.1.2 (Build 13"

### PHP Version

PHP 7.4

### Bug description

Nginx shows stopped. When I try to "Start All", I get the following errors in the Nginx logs.

![CleanShot 2023-08-14 at 09 37 35@2x](https://github.com/beyondcode/herd-community/assets/146333/3b1f841b-ed74-4462-9cd5-7eee5065e9d9)

### Steps to reproduce

Stop All Services > Start All Services

**Comment by mpociot** [comment]
Hi @jacobgraf 
This indicates that another service on your computer is using these ports.
Please make sure that you do not have any other webservers running. For example, try stopping nginx manually:

```
sudo brew services stop nginx
```

**Comment by jacobgraf** [comment]
@mpociot Yes, sorry, I should have mentioned, I did that and nothing else was running except `nginx-arm64` which is coming from Herd. It's almost like during the activation step of the services in Herd, it was fumbling over itself as it fired up and leaving some of those services running while it was trying to spin up other ones.

In any event, I "Stopped All" in Herd, then went into Activity Monitor and filtered by 'nginx' and stopped any phantom `nginx-arm64` processes. I was then able to start the services in Herd successfully.

It still might be worth looking into on your end. When starting the services, maybe it would be good to have a "kill all" step in order to make sure none of those phantom processes are stuck running?

**Comment by mpociot** [comment]
Ah thanks for letting me know. That's weird..I already store/create a PID file that remembers the last process ID of Nginx so I can kill it on application start, if it somehow was not successfully stopped.

But since killing the process manually, Herd is now running fine for you?

We mention how you can manually (re)start processes in the documentation as well: https://herd.laravel.com/docs/1/troubleshooting/restarting-services

**Comment by jacobgraf** [comment]
It is working now! Ahh, I didn't see that in the docs. It felt like maybe some PIDs were orphaned. I'm sure that command would have fixed it, but maybe it's worth adding a button in the GUI which does this too? Or if you didn't want it to be readily available in the GUI, maybe adding an 'alt' option on the 'Stop All' which changes it to "Force Stop All" might be handy. ¯\_(ツ)_/¯

I'm hoping it's not a frequent thing, but adding in the option might come in handy for troubleshooting. 

Thanks again for your help and for building Herd. I love it!

**Comment by jacobgraf** [comment]
@mpociot Just another update here. I switched in the menubar menu from PHP 8.0 to PHP 7.4 and FPM failed to load. I checked the logs and it said it was already running. I did a Stop All and Start All and it still wouldn't start. I looked in activity monitor and searched for fpm. There were 3 processes running. I did Stop All in Herd and then manually killed those fpm processes in Activity Monitor, then did Start All, and they all worked.

I still feel like there is a need for a more robust "Stop All" that can catch these orphaned processes.

**Comment by jacobgraf** [comment]
@mpociot Still having this issue when changing PHP versions. Orphaned processes must manually be killed via Activity Monitor. Is there a way to add a fix for this in Herd so we don't have to manually kill the orphaned processes?

**Comment by ryanmortier** [comment]
@mpociot I notice this happens to me when "securing" a site which I believe restarts the nginx service. I believe @jacobgraf is onto something with requiring a more robust service stop option.

**Comment by jacobgraf** [comment]
Why did this get closed? It's still a problem for me (and others) and I continually have to open Activity Monitor to kill the orphaned FPM processes. This happens mainly when switching between PHP versions.

**Comment by jacobgraf** [comment]
I believe I did have trouble on-boarding Herd when I first installed it now that you say that. I think it conflicted with some Valet stuff. I did do a full uninstall/reinstall when that happened and then I didn't have any issues.

There seem to be other users experiencing this too. I guess what we're asking for is an easier way to force kill any/all processes related to Herd. Like I said above, maybe add a hidden command to the menubar icon that only shows up when you hold alt or something?

Just something to make it easier so we don't have to continually open Activity Monitor, Search for herd processes and manually force stop them.

**Comment by mpociot** [comment]
Yeah, that's a good idea!

I'll add it to the menu as well as a CLI command :) 

Btw, you don't need to search through activity monitor and use this in the meantime: https://herd.laravel.com/docs/1/troubleshooting/restarting-services#force-a-shutdown-of-all-herd-services

**Comment by ryanmortier** [comment]
My issues are 100% with nginx, not the PHP services and stem from when I secure sites, etc.

That troublshooting command doesn't seem to kill the nginx processes at all. Do you know why?

```
➜  ~ which hstop
hstop: aliased to sudo killall nginx-arm64 dnsmasq-arm64 php74-fpm php80-fpm php81-fpm php82-fpm php83-fpm
```
```
➜  ~ hstop
No matching processes were found
```
```
➜  ~ sudo lsof -i :80
COMMAND     PID USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
nginx-arm 29597 root    5u  IPv4 0x76973c7f51d82371      0t0  TCP localhost:http (LISTEN)
nginx-arm 29598 ryan    5u  IPv4 0x76973c7f51d82371      0t0  TCP localhost:http (LISTEN)
nginx-arm 29599 ryan    5u  IPv4 0x76973c7f51d82371      0t0  TCP localhost:http (LISTEN)
nginx-arm 29600 ryan    5u  IPv4 0x76973c7f51d82371      0t0  TCP localhost:http (LISTEN)
nginx-arm 29601 ryan    5u  IPv4 0x76973c7f51d82371      0t0  TCP localhost:http (LISTEN)
nginx-arm 29602 ryan    5u  IPv4 0x76973c7f51d82371      0t0  TCP localhost:http (LISTEN)
nginx-arm 29603 ryan    5u  IPv4 0x76973c7f51d82371      0t0  TCP localhost:http (LISTEN)
nginx-arm 29604 ryan    5u  IPv4 0x76973c7f51d82371      0t0  TCP localhost:http (LISTEN)
nginx-arm 29605 ryan    5u  IPv4 0x76973c7f51d82371      0t0  TCP localhost:http (LISTEN)
```

![CleanShot 2023-12-13 at 12 27 54](https://github.com/beyondcode/herd-community/assets/2053960/ddd418d0-6ab7-41c5-a10a-23bb7ed744a1)


I didn't have any onboarding issues with Herd, like I said earlier in this thread I started from a fresh install of Sonoma and installed Herd without any previous Valet installs or nginx/dnsmasq.

**Comment by mpociot** [comment]
It's weird that those processes don't get killed for you, as `sudo killall nginx-arm64` should get rid of them.

I just added this to Herd though, which will land in the next update, which hopefully resolves the issue for you as well. The force stop option will appear when you press the option key.


https://github.com/beyondcode/herd-community/assets/804684/9600ac69-5d25-4ced-9e11-f1f1b0676cb9

**Comment by jacobgraf** [comment]
@mpociot Saw the new Force Stop feature was added! Thanks!

I know it's minor, and I tried to find a way I could do my own PR, but for consistency, I would Title Case all of those options.

Currently, they are showing "Stop all", "Start all", and "Force Stop All". I would just update the first 2 to have a capital A on all. "Stop All" and "Start All".

Thanks again!

**Comment by jacobgraf** [comment]
@mpociot Used this new Force Stop All feature today after updating PHP. The FPM wouldn't start, which is the issue I usually had. Used the Force Stop All feature and boom, worked great! Thanks!
