### ISSUE TITLE
Can not connect to sites without VPN

### ISSUE THREAD

**Issue by nitras** [beyondcode/herd-community#1209]
### Platform

macOS

### Operating system version

Macos

### System architecture

Intel (x86)

### Herd Version

1.13.0

### PHP Version

php 8.28

### Bug description

Hello there.
For some reason none of my herd sites are working anymore. Unless i connect to the web via a vpn.
I tried to uninstall the VPN app, reboot, to no avail.
I tried to install the herd app again, reboot, to no avail.

Baffled how to fix this.

Thank you.

### Steps to reproduce

Open herd website in browser
> can not connect to mysite.test
Active vpn 
> can connect mysite.test

**Comment by nitras** [comment]
> That sounds very weird, indeed!
> 
> My assumption is that the VPN app is maybe controlling it's own DNS server/dnsmasq instance?
> 
> Could you see if (when Herd is not running) anything is running on the default dnsmasq port?
> 
> ```
> sudo lsof -i :53
> ```
> 
> When Herd is running, it should look something like this:
> 
> ```
> COMMAND     PID   USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
> dnsmasq-a 32205 nobody    4u  IPv4 0x4f41f596906c7392      0t0  UDP localhost:domain
> dnsmasq-a 32205 nobody    5u  IPv4 0xfefef0f46a1d7a87      0t0  TCP localhost:domain (LISTEN)
> ```

Thanks for helping (i am not very at home at these things — i am more of a designer who love to toy around with building websites)

This is what i got 

COMMAND     PID   USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
dnsmasq-x 15119 nobody    4u  IPv4 0xe06011473d84e518      0t0  UDP localhost:domain
dnsmasq-x 15119 nobody    5u  IPv4 0x11e06b5e452d27a5      0t0  TCP localhost:domain (LISTEN)

**Comment by mpociot** [comment]
Okay that sounds right to me. 

Can you simply try and run 

ping foo.test

In your terminal once Herd is running? Does that resolve to 127.0.0.1?

**Comment by nitras** [comment]
> Okay that sounds right to me.
> 
> Can you simply try and run
> 
> ping foo.test
> 
> In your terminal once Herd is running? Does that resolve to 127.0.0.1?

Once Herd is running it states:

`ping: cannot resolve foo.test: Unknown host`

**Comment by nitras** [comment]
I believe I have it working again. I had installed docker.
I stopped docker, to no avail.

The only difference with yesterday was: No docker installed.
So I deleted docker, booted again.

I perfectly can connect to my .test domains now.

Odd! I have a friend over in a few days, he's quite into docker and networking. I will post his findings here.

**Comment by Aa123123-aa** [comment]
最佳 快连VPN 服務

    绝对匿名的加密連接
    超快的速度且無數位足跡
    在美國和全球有数千台安全服务器
官方下载：
https://expvpn.net
https://vpndapps.com
https://letsvpnt.com
https://letskuailian.com
