### ISSUE TITLE
PHP build CI is broken?

### ISSUE THREAD

**Issue by lukasbestle** [beyondcode/herd-community#121]
### Operating system version

Ventura 13.5

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.1.2 (Build: 13)

### Bug description

Herd currently offers me the following PHP versions:

- 8.3 Beta 1
- 8.2.8
- 8.1.22
- 8.0.30
- 7.4.33

8.3 Beta 2 was released 12 days ago. Is something broken in the automatic build CI or do unstable versions like 8.3 require special/manual treatment?

Don't worry if that's the case. I don't want to hurry you, just want to ask if it's intended.

**Comment by mpociot** [comment]
Yeah, still 8.3 requires some manual work as it's not included in the "release channel" that we regularly check.  I just triggered the new 8.3 Beta 2 builds - they take ~30 minutes for both Intel and ARM versions to appear in the UI.

Thanks for reporting this!

**Comment by lukasbestle** [comment]
Thanks for your super quick reply. 👍
