### ISSUE TITLE
[Feature Request]: Uninstall PHP Versions via the UI

### ISSUE THREAD

**Issue by StanBarrows** [beyondcode/herd-community#124]
### Feature Description

Add the possibility to uninstall PHP Versions via the UI.

<img width="976" alt="CleanShot 2023-08-17 at 00 48 12@2x" src="https://github.com/beyondcode/herd-community/assets/10268813/868cd4f7-8627-4fb5-86eb-fd0ed7b482d7">

**Comment by cotiga** [comment]
I asked myself the same question.
Waiting :
https://github.com/beyondcode/herd-community/issues/69#issuecomment-1658039417
