### ISSUE TITLE
[Feature Request]: Add sites in the UI 

### ISSUE THREAD

**Issue by coendr** [beyondcode/herd-community#127]
### Feature Description

Add the input field or add new site window for adding sites in the UI instead through the terminal.
This will also work well for adding subdomains.

<img width="900" alt="image" src="https://github.com/beyondcode/herd-community/assets/50136539/c1e3c1d0-0f68-4431-b9d1-302046758832">

**Comment by robindirksen1** [comment]
For example: `herd link subdomain.myproject`

**Comment by mpociot** [comment]
We now added a separate Installer GUI in the UI. We'll add more features (like linking sites) soon
