### ISSUE TITLE
[Bug]: List of sites is empty

### ISSUE THREAD

**Issue by CalumChamberlain** [beyondcode/herd-community#128]
### Operating system version

macOS Ventura 13.4.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.1.2 (Build: 13)

### Bug description

![image](https://github.com/beyondcode/herd-community/assets/34173688/be2a9c3d-6586-404b-b073-21276843d445)

The list of sites is blank in the Herd GUI but when running `herd parked` I get several sites.

https://github.com/beyondcode/herd-community/issues/37 I checked this issue regarding numbers but none of my sites match this.

**Comment by crimann** [comment]
I had the same problem with a fresh Herd installation, which by default only installed PHP 7.4. Installing PHP 8.2 from the settings brought the sites list back.

**Comment by mpociot** [comment]
@CalumChamberlain Could this be the same issue for you?

**Comment by CalumChamberlain** [comment]
> I had the same problem with a fresh Herd installation, which by default only installed PHP 7.4. Installing PHP 8.2 from the settings brought the sites list back.

Thanks, that fixed my issue. Previously I had 8.3, 8.1 and 7.4 installed. As soon as I installed 8.2 the list reappeared

**Comment by tonypartridger** [comment]
I have this issue too, I have all php versions installed :/

**Comment by mpociot** [comment]
@tonypartridger whats your output when you run "herd parked --json" via CLI?

**Comment by tonypartridger** [comment]
> herd parked --json

a nice structure JSON output with an array of sites which have: site, secures, url, path and phpVersion.

It contains some sites we work on I don't really want to disclose but it's a completely sane list without any json errors

**Comment by tonypartridger** [comment]
Ok, I managed to resolve it with some checks, I removed all paths in Herd Paths and just added the one www directory I use.... So suspect it could be some of the valet paths that were part of the first migration existed and contained duplicates or some paths were not valid now?
