### ISSUE TITLE
[Bug]: Not loading php.ini file

### ISSUE THREAD

**Issue by morrislaptop** [beyondcode/herd-community#129]
### Operating system version

macOS Ventura 3.4.1 (c)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.1.2

### Bug description

Occuring across all PHP versions

### Steps to reproduce

1. Open the php.ini file for the php version
2. Set a setting like memory_limit
3. Run php -i | grep memory_limit
4. Observe the setting has not taken affect

### Relevant log output

```shell
php -i | grep ini
Configuration File (php.ini) Path => /lib
```

**Comment by ammarsdc** [comment]
Same issue here. Mine Herd version might same 1.1.2 (Build 13). I'm trying to amend `upload_max_filesize=5M`. Once changed and saved, checking thru `phpinfo()`, the value is still the same as default (`2M`). I also noticed the Loaded Configuration File has value `none`.

**Comment by mechelon** [comment]
Can you check in your terminal configuration file (e.g. `~/.zshrc`) if the path to the Herd `php.ini` files is injected correctly?

For example, for PHP 8.1 it should look something like that:
``
`
# Herd injected PHP 8.1 configuration.
export HERD_PHP_81_INI_SCAN_DIR="/Users/YOUR-USER/Library/Application Support/Herd/config/php/81/"
```

Also, points `which php` to the correct Herd binary?

**Comment by morrislaptop** [comment]
php is ponting to herd. I'm using fish. Tried setting that env variable but no luck :/

**Comment by barchard** [comment]
I think I am seeing the same issue with `.user.ini` files. I have a `.user.ini` file in the Herd site's document root with a `auto_append_file` directive specified. The path is the full/absolute path to a `.php` file. If you look at the `phpinfo();`, you'll see that the additional `.ini` file is *not* parsed.

Directory structure:

```
/path/to/herd/site/
/path/to/herd/site/index.php
/path/to/herd/site/.user.ini
/path/to/herd/site/subfolder/auto_append_file.php
```

Contents of `.user.ini`:

```
[Herd]
auto_append_file = "/path/to/herd/site/subfolder/auto_append_file.php"
zlib.output_compression = "On"
```

The contents of `index.php`:

```
<?php phpinfo(); ?>
```

You'd expect that the `.user.ini` file is parsed and load the `auto_append_file.php` but the output of `phpinfo` shows:

```
Scan this dir for additional .ini files | (none)
-- | --
Additional .ini files parsed | (none)
```

**Comment by mpociot** [comment]
PHP tries to load it's ini file in two different locations:
1. Version specific ini file `~/Library/Application Support/Herd/config/php/[VERSION]/php.ini`
2. Generic php.ini file `~/Library/Application Support/Herd/config/php/php.ini`

I noticed that some PHP binary URLs were cached in our CDN endpoint, so it could be that your specific version is still looking for the generic php.ini file instead of the global one.

If that's the case, you can simply delete the PHP binaries from `~/Library/Application Support/Herd/bin` and re-download the latest versions via the PHP settings UI.

**Comment by barchard** [comment]
@mpociot any thoughts on the .user.ini issue I noticed? Should I open it as a separate issue?

**Comment by ammarsdc** [comment]
> Same issue here. Mine Herd version might same 1.1.2 (Build 13). I'm trying to amend `upload_max_filesize=5M`. Once changed and saved, checking thru `phpinfo()`, the value is still the same as default (`2M`). I also noticed the Loaded Configuration File has value `none`.

Hi. Just a quick update on my report. I just noticed the `Loaded Configuration File has value: none` only when I run `php artisan serve`.  Running `which php` return me `/Users/{username}/Library/Application Support/Herd/bin//php`. However, when I place the folder inside Herd directory, the directive has value: `/Users/{username}/Library/Application Support/Herd/config/php/81/php.ini`. May I know why this happened?

One more thing, the directives values as I put inside my `.user.ini` was not reflected in `phpinfo()`. So might be the same issue as reported by @barchard.

**Comment by pxlrbt** [comment]
> Can you check in your terminal configuration file (e.g. `~/.zshrc`) if the path to the Herd `php.ini` files is injected correctly?
> 
> For example, for PHP 8.1 it should look something like that:
> 
> ```
> # Herd injected PHP 8.1 configuration.
> export HERD_PHP_81_INI_SCAN_DIR="/Users/YOUR-USER/Library/Application Support/Herd/config/php/81/"
> ```
> 
> Also, does `which php` point to the correct Herd binary?

Is this intended to work out of the box or why isn't there any mention of setting the env var?

For the fish users:
I had to set this in the fish config to make Herd load the correct config files

```sh
set -x HERD_PHP_82_INI_SCAN_DIR "/Users/[USER]/Library/Application Support/Herd/config/php/82/"
```

**Comment by jreviews** [comment]
In case it helps someone, I had a similar issue where the ini settings were not working. After opening the Activity Monitor in Mac and killing all the php##-fpm processes, then stopping services and starting them again in Herd, the updated php.ini started working. It wasn't enough to quit Herd or stop/start the services. I also had to kill the proceses.

**Comment by husniramdani** [comment]
this works for me : 
If you are using the [Fish](https://fishshell.com/) shell, you will need to run the following command to add the Herd binaries to your path:
`fish_add_path -U $HOME/Library/Application\ Support/Herd/bin/`

**Comment by BFAscend** [comment]
If it helps anyone else, I spent a few hours tearing my hair out over this. I couldn't get the .ini to load when PHP artisan serving, but if you access your project through Herd's "sites" feature, it loads the .ini

**Comment by handhikadj** [comment]
> > Same issue here. Mine Herd version might same 1.1.2 (Build 13). I'm trying to amend `upload_max_filesize=5M`. Once changed and saved, checking thru `phpinfo()`, the value is still the same as default (`2M`). I also noticed the Loaded Configuration File has value `none`.
> 
> Hi. Just a quick update on my report. I just noticed the `Loaded Configuration File has value: none` only when I run `php artisan serve`. Running `which php` return me `/Users/{username}/Library/Application Support/Herd/bin//php`. However, when I place the folder inside Herd directory, the directive has value: `/Users/{username}/Library/Application Support/Herd/config/php/81/php.ini`. May I know why this happened?
> 
> One more thing, even though I serve the app within the Herd directory, the directives values as I put inside my `.user.ini` was not reflected in `phpinfo()`. So might be the same issue as reported by @barchard.

I'm having  the same issue on the latest Herd . it's `/Users/me/Library/Application Support/Herd/bin//php` when running `which php`
@ammarsdc if it's fixed, can you tell me how you fixed it?

CC @mpociot
