### ISSUE TITLE
[Feature Request]: Remove an installed PHP version

### ISSUE THREAD

**Issue by neurotools** [beyondcode/herd-community#13]
### Feature Description

I notice you can't remove a PHP version after install it.

Also, @mpociot mentioned in his Blog Post https://beyondco.de/blog/announcing-laravel-herd/

> On the herd.laravel.com website, we have a scheduled command that checks daily if a new PHP version was released. If that's the case, it uses the [GitHub Actions API](https://docs.github.com/en/rest/actions/workflow-runs?apiVersion=2022-11-28) to manually trigger a workflow run. This needs to happen twice - once for ARM64 binaries and once for x86 versions of PHP.

But I installed PHP 8.2 and the installed version is 8.2.7 on the versions menu of Herd, and 8.2.6 on CLI:

`PHP 8.2.6 (cli) (built: Jun  2 2023 23:59:34) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.6, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.6, Copyright (c), by Zend Technologies`

But at PHP.net website says the 8.2.8 version is the lastest and it's the one shown on the screenshot published on his Blog post:

![imagen](https://github.com/beyondcode/herd-community/assets/6556055/aa7d07af-8170-4198-b67d-6c7febb26d00)

https://beyondco.de/img-blog/herd/php.png

### Is this feature valuable for other users as well and why?

It's important to have the option to remove a PHP version you don't need any more and be capable of install the latest fix version of a PHP minor version.

**Comment by sineld** [comment]
+1

**Comment by mpociot** [comment]
Right now, you can manually remove PHP versions by simply deleting the FPM and CLI binary in your `~/Library/Application Support/Herd/bin` folder.
Make sure to unisolate any site that makes use of the version though.
