### ISSUE TITLE
[Bug]: Injected lines added to .zshrc despite values already being exported

### ISSUE THREAD

**Issue by brysonreece** [beyondcode/herd-community#131]
### Operating system version

macOS Ventura 13.5

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.2.0 (Build 14)

### Bug description

Hey there! In short, the variable exports that Herd adds to your `~/.zshrc` file (for `PATH` and `PHP_INI_SCAN_DIR` values) should first be checked to determine if they're already resolvable (or maybe a configuration option added to the settings in order to disable this functionality).

This would be particularly helpful for those of us using shell integrations like [Fig](https://fig.io/) which handle loading your shell configuration for you. A practical example is show here (the contents of my personal `.zshrc` file):
```
# Fig pre block. Keep at the top of this file.
[[ -f "$HOME/.fig/shell/zshrc.pre.zsh" ]] && builtin source "$HOME/.fig/shell/zshrc.pre.zsh"

# Fig post block. Keep at the bottom of this file.
[[ -f "$HOME/.fig/shell/zshrc.post.zsh" ]] && builtin source "$HOME/.fig/shell/zshrc.post.zsh"
```

After Herd injects it's info into the `~/.zshrc` file, it ends up looking like this:
```
# Fig pre block. Keep at the top of this file.
[[ -f "$HOME/.fig/shell/zshrc.pre.zsh" ]] && builtin source "$HOME/.fig/shell/zshrc.pre.zsh"

# Fig post block. Keep at the bottom of this file.
[[ -f "$HOME/.fig/shell/zshrc.post.zsh" ]] && builtin source "$HOME/.fig/shell/zshrc.post.zsh"


# Herd injected PHP binary.
export PATH="/Users/bryson/Library/Application Support/Herd/bin/":$PATH

# Herd injected PHP configuration.
export PHP_INI_SCAN_DIR="/Users/bryson/Library/Application Support/Herd/config/php/:$PHP_INI_SCAN_DIR"

# Herd injected PHP 8.2 configuration.
export HERD_PHP_82_INI_SCAN_DIR="/Users/bryson/Library/Application Support/Herd/config/php/82/"

# Herd injected PHP 8.3 configuration.
export HERD_PHP_83_INI_SCAN_DIR="/Users/bryson/Library/Application Support/Herd/config/php/83/"
```

-- Despite `PATH` and the various `PHP_INI_SCAN_DIR` exports already being configured and exported correctly through the previous `source` calls.

To recap, a potential fix could be implemented one of the following ways:
* By first sourcing the `.zshrc` file and checking if the expected variables are correctly configured.
* Adding a Settings option to disable this functionality altogether
* Only performing those injections on app update / PHP version change/installation.

---

(Although not a concern of this application, it's worth noting that an additional effect of this is that it breaks Fig's expectation that it's "post" `source` will be the last thing in the `.zshrc` file, and that any modifications to the `~/.zshrc` file are inserted between the "pre" and "post" `source` calls. This means that every time Herd starts, it breaks my entire shell until I manually open `.zshrc` and remove the offending lines.)

### Steps to reproduce

Start Herd, then check that the problematic lines are being injected into your `~/.zshrc` file.

**Comment by brysonreece** [comment]
I feel like it's worth pointing out that even though Fig is used heavily in the above example, as it's ingrained into my personal setup, this problem persists despite foregoing that tool.

For example, if I would extract my `PATH` and `PHP_INI_SCAN_DIR` declarations to a separate file (ex. `.zsh_exports`, kind of like `.zsh_aliases`) and then tried to source that file at the top of my `.zshrc`, the unnecessary injections into `.zshrc` would still occur.

**Comment by mpociot** [comment]
Thank you for reporting this.
I don't think there's really a good way for us to work around this issue at the moment, as we need to ensure that these environment variables are set/available.
I'll try to check their existence and skip modifying the zshrc file in this case.

**Comment by helmerdavila** [comment]
Same, this is causing some conflicts with my current chezmoi sync between remote and local

**Comment by WMOH-DEV** [comment]
same here, new installation
