### ISSUE TITLE
[Bug]: Installation fails on MacOS 13.5 with Intel M2

### ISSUE THREAD

**Issue by SDJeff** [beyondcode/herd-community#132]
### Operating system version

macOS ventura 13.5

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

About not accessible

### PHP Version

PHP 8.2.9 NTS Aug 16 2023

### Bug description

During the installation of the version, downloaded 21st Aug'23 no password request came like announcent.
Valet was stopped and download of php8.2 was shown even if it was already installed by brew of this fresh MacBook.
Path was adjusted in .zshrc an the services are running after the installation seems to be completed.

But the icon in the menu bar was not shown and you can't open the Herd App manually. No window or interface was reachable. I can't stop or kill the app over the menu. Last chance was to uninstall all and remove all like described in the docs after ein killall processes.

Sorry but there was no error message or something else what i could provide at the moment to help you further. Finally i switched back to Valet which runs fine with phpmon.

### Steps to reproduce

Second try of the installation, without any changes at the os failed in the same way.

**Comment by mpociot** [comment]
This usually happens when there is not enough space in the Menu bar to show the icon - as reported by some other users. Please ensure that there's enough space to see the icon.

**Comment by SDJeff** [comment]
Was thinking the same because i am using the Bartender App. Even if i stop Bartender i can't open the Herd interface and there are nevertheless an icon. It is a pretty new machine and there are 3 or 5 icons only at the moment. So i think it could not really depending on the space. On top i can't open a project which i created new in the ~/Herd directory, so i was thinking the installation isn't really complete. Can i check any logs for you to narrow down the error?
