### ISSUE TITLE
[Bug]: Unable to start Nginx

### ISSUE THREAD

**Issue by Welfordian** [beyondcode/herd-community#135]
### Operating system version

macOS Ventura 13.5

### System architecture

Intel (x86)

### Herd Version

1.2.0 (Build: 14)

### Bug description

Installed Laravel Herd & went through the setup process.
Nginx logs show SSL_CTX_new() failed (SSL: routines::library has no ciphers).

On another note, it seems you can't highlight the text in the logs panel to copy.

**Comment by mpociot** [comment]
This issue must be related to some user-specific OpenSSL configuration.
Do you have a custom `OPENSSL_CONF` environment variable/use a custom OpenSSL Homebrew version that might affect Nginx?

**Comment by mikahoy045** [comment]
where to get the error log of this nginx not running?

**Comment by emmanuelcoker** [comment]
The issue is related to the port used by herd already used by another service.
I was able to fix this by changing the ports in herd.conf, adminer.conf, and my project file to port 8080

in the file change  listen 127.0.0.1:80 to  listen 127.0.0.1:8080
