### ISSUE TITLE
[Bug]: Something wrong with buffer

### ISSUE THREAD

**Issue by edalzell** [beyondcode/herd-community#137]
### Operating system version

13.5

### System architecture

Intel (x86)

### Herd Version

1.2

### PHP Version

8.2.8

### Bug description

Note this does NOT occur when using Valet.

I get this error: https://flareapp.io/share/LPl8DEbP

The code is here:

```php
  public function __invoke()
    {
        echo $this;

        ob_flush();

        flush();
    }
```

If I make that code:

```php
  public function __invoke()
    {
        echo $this;
        if (ob_get_contents()) {
            ob_flush();
        }
        flush();
    }
```

Then I don't get the error, but the package author thinks this is a PHP/Herd issue: https://github.com/qruto/laravel-wave/issues/35

**Comment by edalzell** [comment]
The default php.ini needs `output_buffering = 4096` to make things work nice.

**Comment by edalzell** [comment]
Thanks Marcel!

**Comment by soeurngsar** [comment]
I went through all these solution, but it still not working. If run command artisan serve it working fine.
I'm using Herd version 1.3.2 on Mac M1 pro CPU.
