### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by keithpowers** [beyondcode/herd-community#138]
### Operating system version

mac os ventura

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.0.

### PHP Version

php 8.2

### Bug description

unble to use Docker and Herd on same machine
I need docker for some of my sites to talk to each other backend frontend and micro services but want herd to allow me to do quick sites for experiments new featurs using the mariadb container from docker to run data in herd sites

### Steps to reproduce

install docker then herd unable to see any docker sites or use herd.

**Comment by mpociot** [comment]
This is a bit out of the scope from Herd. I guess the issue is that Docker and Herd try to use the same ports.
