### ISSUE TITLE
[Feature Request]: Ngrok

### ISSUE THREAD

**Issue by CodeTechNL** [beyondcode/herd-community#139]
### Feature Description

Hi,

If im correct, Expose is a product that you guys created. Im using a paid account at Ngrok. Is Herd going to support Ngrok in the feature?

**Comment by sschlein** [comment]
Hey, you can switch to ngrok by using `herd share-tool ngrok`. This still keeps the Expose settings in the settings but `herd share` uses ngrok then.

**Comment by abdulbasit-dev** [comment]
@sschlein when using herd share-tool ngrok, it say Command "share-tool" is not defined
