### ISSUE TITLE
[Feature Request]: Herd folder work with symlinks

### ISSUE THREAD

**Issue by allanmcarvalho** [beyondcode/herd-community#14]
### Feature Description

Sometimes symlinks can speedup the development. In my case, I have a Laravel applications that use two or more domains, eg. one for main application and other for api, like I use in production. Today Herd don't allow you to create manualy a domain to a folder, so symlinks will be very helpfull.

I fixed temporaly this with a not usually way. I created another folder inside Herd folder, and put a public folder with index.php and others files inside it (like Laravel sctructure), them I fixed the requires to the main project, so in this way I have two domains running on same application, but isn't an elegant solution.

Maybe an other solution instead use symlinks, is add to Herd settings a possibility of create alias for a domain, this is a "like a charm" solution in my opinion.

### Is this feature valuable for other users as well and why?

Yes, I believe that many users uses a application that has more than one domain. I believe too, that this will be usefull in other things.

**Comment by mpociot** [comment]
I think the feature you're looking for is `herd link` via the CLI.
Just like Valet, you can make use of all `valet ...` CLI commands. 
See https://laravel.com/docs/10.x/valet#the-link-command

**Comment by allanmcarvalho** [comment]
Thanks @mpociot
