### ISSUE TITLE
[Feature Request]: Xdebug

### ISSUE THREAD

**Issue by n1xn** [beyondcode/herd-community#141]
### Feature Description

Would like to know how you guys debug with heard as you market it on the website
as "development environment"...

### Is this feature valuable for other users as well and why?

guess so

**Comment by mpociot** [comment]
We're working on adding xdebug support 👍 
I'll close this as it's on our roadmap and xdebug support has been requested in #16

**Comment by carlituxman** [comment]
But only works for php 8.2
