### ISSUE TITLE
[Bug]: PHP FPM Doesn't start

### ISSUE THREAD

**Issue by 366-lefteris** [beyondcode/herd-community#142]
### Operating system version

macOS Ventura 13.5.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.2.0

### Bug description

PHP-FPM Process cannot start all versions 7.4 - 8.3 dont start at all.
i get the below log output.

Relevant information about the system.

The mac is managed in Active directory (LDAP) The current user is a local admin.

### Relevant log output

```shell
FPM-7.4 logs
[21-Aug-2023 18:52:59] NOTICE: [pool herd] 'user' directive is ignored when FPM is not running as root
[21-Aug-2023 18:52:59] NOTICE: [pool herd] 'group' directive is ignored when FPM is not running as root
[21-Aug-2023 18:52:59] ERROR: [pool herd] failed to chown() the socket ' /Users/<user>/Library/Application Support/Herd/herd74.sock': Operation not permitted (1)
[21-Aug-2023 18:52:59] ERROR: FPM initialization failed
```

**Comment by mpociot** [comment]
This could be an issue when your user is not in the admin group.

Maybe this helps?

https://github.com/beyondcode/herd-community/issues/10#issuecomment-1648579131

**Comment by 366-lefteris** [comment]
@mpociot thank you very much this has Fixed the issue.

**Comment by pryley** [comment]
In my case, I had to delete the `~/Library/Application Support/Herd` folder, restart Herd, and reinstall the PHP versions.

I think the issue had something to do with the way Herd migrated over from Valet which was used previously.

**Comment by xodivorce** [comment]
> In my case, I had to delete the `~/Library/Application Support/Herd` folder, restart Herd, and reinstall the PHP versions. That fixed it.
> 
> I think the issue had something to do with the way Herd migrated over from Valet which was used previously. I forgot what the exact error was, but it was something like herd81.sock could not be initialized because an instance was already in use.

It works, thanks

**Comment by ahmadrio** [comment]
> In my case, I had to delete the `~/Library/Application Support/Herd` folder, restart Herd, and reinstall the PHP versions. That fixed it.
> 
> I think the issue had something to do with the way Herd migrated over from Valet which was used previously. I forgot what the exact error was, but it was something like herd81.sock could not be initialized because an instance was already in use.

thanks
