### ISSUE TITLE
[Bug]: Herd Stopped working after update to 1.2

### ISSUE THREAD

**Issue by misodrobny** [beyondcode/herd-community#143]
### Operating system version

macOS 13.5 (22G74)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.2.0 Build: 14

### PHP Version

PHP 8.2.9

### Bug description

After upgrading to Herd 1.2.0 any site giving network error in all browsers

![Screenshot 2023-08-24 at 22 47 30](https://github.com/beyondcode/herd-community/assets/54170028/e9d1788f-97a6-4930-93b9-2da3368067bf)

### Steps to reproduce

do not know.

**Comment by mpociot** [comment]
It seems like nginx is not running for you. What do the services in the Herd menubar look like?

**Comment by misodrobny** [comment]
All green. 
![Screenshot 2023-08-24 at 22 51 43](https://github.com/beyondcode/herd-community/assets/54170028/1114b90d-a699-4548-8bc6-e23605c83320)

**Comment by misodrobny** [comment]
Log are empty :(

**Comment by mpociot** [comment]
Can you check the additional log files at '~/Library/Application Support/Herd/Log/`?
You can try and stop Herd and kill all services manually in case there were any stray processes: https://herd.laravel.com/docs/1/troubleshooting/restarting-services

**Comment by misodrobny** [comment]
I tried it and also check additional logs. Logs are empry and killall did not work. I fully unisntalled Herd and affter uninstall and clean install is the situation the same.

I will try to investigate, probably is problem sth on my machine, but currently with no idea :)

**Comment by misodrobny** [comment]
Thanks for help it was somekind of machine related issue. I had to do full reinstall because of other problems and herd is working fine now.

**Comment by MPSimon** [comment]
@misodrobny What was the issue? i've ran into the same problem.
