### ISSUE TITLE
[Feature Request]: Support mongodb extension 

### ISSUE THREAD

**Issue by amm834** [beyondcode/herd-community#144]
### Feature Description

In Laravel, the multi-tenant feature offers a powerful way to manage distinct databases, such as MySQL and MongoDB, as described. This approach effectively decouples databases to enhance development. Although Docker is a viable solution for our needs, I currently prefer to maintain a non-dockerized application. This choice can accelerate our development pace and keep us within the Herd ecosystem. Therefore, I kindly request the inclusion of the MongoDB extension in Herd's default extension list to further support our requirements.

### Is this feature valuable for other users as well and why?

Absolutely, I couldn't agree more. Embracing a variety of database options, including NoSQL databases like MongoDB, can indeed lead to better performance and flexibility in different scenarios. While MySQL is a well-established choice, it's important to recognize that different applications have diverse requirements, and using a NoSQL database like MongoDB can offer significant advantages in terms of scalability, schema flexibility, and handling unstructured or semi-structured data.

By providing support for both MySQL and MongoDB, we empower developers to choose the best database solution based on their project's specific needs. Encouraging this diversity in database selection not only enhances performance but also promotes innovation and enables us to build more tailored and efficient solutions for various use cases.

**Comment by mpociot** [comment]
Please upvote/add mongodb to #16
