### ISSUE TITLE
[Bug]: How can I enabled the default xsl extension.

### ISSUE THREAD

**Issue by tecnoe** [beyondcode/herd-community#145]
### Operating system version

macOs Ventura 13.5

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.2.0

### PHP Version

PHP 8.2

### Bug description

How can I enable the PHP-XSL extension.  PHP includes the XSL extension by default, but I do not how to enable it.

**Comment by sschlein** [comment]
Herd only includes the extensions that are listed at the FAQs at https://herd.laravel.com/ at the moment but you can install others with the process described in the docs: https://herd.laravel.com/docs/1/advanced-usage/additional-extensions

**Comment by ElRochito** [comment]
@sschlein xsl can't be install via pecl 

`pecl install xsl` prompt 
```
No releases available for package "pecl.php.net/xsl"
install failed
```

**Comment by ElRochito** [comment]
@sschlein any ideas to install it other than pecl ?

**Comment by zupolgec** [comment]
There are various extensions that can't be installed with PECL. Any other solution? Thanks!

**Comment by SagarNaliyapara** [comment]
@ElRochito @zupolgec Found any solutions? I'm also finding how to install xsl extension

**Comment by zupolgec** [comment]
> @ElRochito @zupolgec Found any solutions? I'm also finding how to install xsl extension

Nope. Only solution at the moment is to go back to Homebrew PHP

**Comment by SagarNaliyapara** [comment]
@zupolgec I downloaded extension manually from here - https://packages.macports.org/php81-xsl/ and then found .so file in it, added into php.ini and it fixed the issue for me

**Comment by robbanl** [comment]
I found this thread some time earlier. New computer, same problem :-)

I downloaded the corresponding xsl.so file and saved it in:

/Users/**myusername**/Library/Application Support/Herd/config/php/81

Then added the following line to the PHP file in the same directory:

extension=/Users/**myusername**/Library/Application Support/Herd/config/php/81/xsl.so

After running php -v, I had to authorize the xsl.so file in OSX system settings, like any other unverified application.

Hopefully I won't need to find this thread again, but the above might help someone else.

**Comment by marlonbasten** [comment]
Well, I tried to do the same but I'm getting this error after loading the xsl.so:

Warning: PHP Startup: Unable to load dynamic library '/Users/**/.extensions/php/83/xsl.so' (tried: /Users/**/.extensions/php/83/xsl.so (dlopen(/Users/**/.extensions/php/83/xsl.so, 0x0009): Library not loaded: /opt/local/lib/libexslt.0.dylib

Any ideas what that could be? Already installed `libxml2` and `libxslt` via homebrew to no avail.

**Comment by marlonbasten** [comment]
Ok, I fixed it (for me at least).

This solved it for me:
```bash
sudo mkdir -p /opt/local/lib
sudo ln -s /opt/homebrew/opt/libxslt/lib/libexslt.0.dylib /opt/local/lib/
sudo ln -s /opt/homebrew/opt/libxslt/lib/libxslt.1.dylib /opt/local/lib/
sudo ln -s /opt/homebrew/opt/libxml2/lib/libxml2.2.dylib /opt/local/lib/
```

**Comment by robbanl** [comment]
@marlonbasten Nice, this looks like a much nicer solution than mine :-) I'll give it a try!

**Comment by ElRochito** [comment]
Hi guys,

I follow steps above but I've got this error

Warning: PHP Startup: Unable to load dynamic library '/usr/local/lib/php/pecl/20210902/xsl.so' (tried: /usr/local/lib/php/pecl/20210902/xsl.so (dlopen(/usr/local/lib/php/pecl/20210902/xsl.so, 0x0009): Library not loaded: /opt/local/lib/libexslt.0.dylib
  Referenced from: <0845E028-95C5-3392-BBE8-E399D8651057> /usr/local/lib/php/pecl/20210902/xsl.so
  Reason: tried: '/opt/local/lib/libexslt.0.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/local/lib/libexslt.0.dylib' (no such file), '/opt/local/lib/libexslt.0.dylib' (no such file)), /lib/php/extensions/no-debug-non-zts-20210902//usr/local/lib/php/pecl/20210902/xsl.so.so (dlopen(/lib/php/extensions/no-debug-non-zts-20210902//usr/local/lib/php/pecl/20210902/xsl.so.so, 0x0009): tried: '/lib/php/extensions/no-debug-non-zts-20210902//usr/local/lib/php/pecl/20210902/xsl.so.so' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/lib/php/extensions/no-debug-non-zts-20210902//usr/local/lib/php/pecl/20210902/xsl.so.so' (no such file), '/lib/php/extensions/no-debug-non-zts-20210902//usr/local/lib/php/pecl/20210902/xsl.so.so' (no such file))) in Unknown on line 0
PHP 8.1.24 (cli) (built: Sep 29 2023 01:25:08) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.24, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.24, Copyright (c), by Zend Technologies


<img width="973" alt="image" src="https://github.com/beyondcode/herd-community/assets/1737307/e1086585-4bd1-4070-bcb1-c919371963f6">
