### ISSUE TITLE
unable to run core php project[Bug]: 

### ISSUE THREAD

**Issue by ManojPadhiyar1993** [beyondcode/herd-community#147]
### Operating system version

macOS ventura 13.5.1

### System architecture

Intel (x86)

### Herd Version

1.2

### PHP Version

7.4

### Bug description

Hi
hear community i just install the herd it works fine for laravel project but when i run core php project it not works
your reply it really helpful for me
thank u

**Comment by sschlein** [comment]
What's a core php project? A project with just an index.php?

**Comment by ManojPadhiyar1993** [comment]
hi @sschlein  thank you for reply 
not not just index.php it mcv structure

**Comment by ManojPadhiyar1993** [comment]
As of now i just set up mamp :)
it's better if you help me for herd shows 404

**Comment by sschlein** [comment]
If you're happy with MAMP, that's fine 😀 

We're mainly focused on Laravel at the moment and don't support every custom project structure right now

**Comment by ManojPadhiyar1993** [comment]
Alright 
for a moment it's okay with MAMP
but i want to update with herd 
thank you for reply :)
