### ISSUE TITLE
[Bug]: Spatie Media Library + Herd Crashes when Queuing Conversions

### ISSUE THREAD

**Issue by blhylton** [beyondcode/herd-community#150]
### Operating system version

macOS Ventura 13.5

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.2.0 (Build: 14)

### PHP Version

PHP 8.2.9, 8.1.22

### Bug description

I am utilizing [Spatie's Laravel Media Library](https://github.com/spatie/laravel-medialibrary) within a few projects. When conversions are set up to queue, and the queue is not `sync`, the queue worker dies without any discernable error a few seconds into creating the conversions. I can't determine any rhyme or reason for when it crashes because it successfully converts some media sometimes.

Theoretically, this could also be an issue with their library, but this only happens in Herd, so I'm leaning in that direction. The same image sets successfully convert when running in a more traditional environment.

System architecture doesn't seem to matter either, as one of my coworkers has the same issue on a different project with an Intel Mac.

### Steps to reproduce

1. Create New Laravel Project with Spatie's Media Library package
2. Set queue to `redis` (or `database`; presumably anything except `sync` but those are the two I have tried)
3. Follow their directions for [preparing a model](https://spatie.be/docs/laravel-medialibrary/v10/basic-usage/preparing-your-model) and [defining conversions](https://spatie.be/docs/laravel-medialibrary/v10/converting-images/defining-conversions)
4. [Associate a media file with your model](https://spatie.be/docs/laravel-medialibrary/v10/basic-usage/associating-files), triggering the conversion(s).
5. Allow queue worker to run until it crashes

This doesn't happen with every conversion, but it almost always seems to happen when attempting to [regenerate the media](https://spatie.be/docs/laravel-medialibrary/v10/converting-images/regenerating-images).

### Relevant log output

```shell
No logs written to laravel.log, herd.log, php-fpm.log, or nginx-error.log.
```

**Comment by mpociot** [comment]
Hi @blhylton 
We just tried to reproduce your issue but unfortunately were unable to do so.
Could you give us some more information on which files/file types you are trying to convert using the medialibrary?

What I tried:

```php
$user = \App\Models\User::first();
$user->addMediaFromUrl('https://beyondco.de/apps/icons/expose.png')->toMediaCollection();
```

```php
public function registerMediaConversions(Media $media = null): void
{
    $this
        ->addMediaConversion('preview')
        ->fit(Manipulations::FIT_CROP, 100, 100);
}
```

These conversions work fine for me with Herd and I can't force the queue worker to crash. I suppose this has something to do with the conversion type and possibly the file types you're using.

**Comment by blhylton** [comment]
@mpociot 

I should've known it wouldn't be that easy. I'll see if I can isolate the issue into its own repo.

The project it is happening to me the most on has multiple conversions (six, if memory serves, but I'm on mobile right now) per image, in case that helps.

**Comment by stockhausen** [comment]
@mpociot I have the same problem only with files whose height or width is greater than 3000 pixels.

**Comment by mpociot** [comment]
@stockhausen can you consistently reproduce this with images > 3000 pixels?

**Comment by stockhausen** [comment]
yes, some of my projects (10 under GD) for each image > 3000 pixels high or wide don't work with herd but work with valet, no problem for conversion with imagick. 

use this image : https://unsplash.com/photos/EBFMLYND2fU/download?ixid=M3wxMjA3fDF8MXxhbGx8MXx8fHx8fDJ8fDE2OTUwMzEyNjR8&force=true

add to user avatar by example and make this conversion with queuing all job generate goes to fail

```php
        $this
            ->addMediaConversion('preview')
            ->fit(Manipulations::FIT_CROP, 300, 300)
            ;
        $this
            ->addMediaConversion('thumb')
            ->fit(Manipulations::FIT_CROP, 800, 800)
            ;   

        $this
            ->addMediaConversion('resize')
            ->width(1400)
            ->height(1400)
            ;   
```

my configuration : 
valet is installed on my computer and stopped
herd php 8.1
my computer APPLE M1 16Go

our customers are sometimes given images by communications departments that don't pay attention to image size. We are often confronted with this type of test on our developments and locally herd doesn't work with GD and files over 3000 pixels to resize.

**Comment by mpociot** [comment]
This has now been resolved in the latest PHP builds. PHP 8.3.0 for ARM64 is already available, the others are queued and are compiling as well.
