### ISSUE TITLE
[Bug]: herd share returns Could not connect to the server

### ISSUE THREAD

**Issue by theoreaves** [beyondcode/herd-community#152]
### Operating system version

macOS Ventura version 13.4

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.2.0 (Build 14)

### PHP Version

php 8.2.7

### Bug description

herd share
Could not connect to the server.
Connection to tls://us-1.sharedwithexpose.com:443 failed during TLS handshake: SSL operation failed with code 5. OpenSSL Error messages: error:80000002:system library::No such file or directory error:80000002:system library::No such file or directory error:80000002:system library::No such file or directory error:80000002:system library::No such file or directory error:0A000086:SSL routines::certificate verify failed

### Steps to reproduce

run 'herd share' in a project directory

### Relevant log output

```shell
Could not connect to the server.
Connection to tls://us-1.sharedwithexpose.com:443 failed during TLS handshake: SSL operation failed with code 5. OpenSSL Error messages: error:80000002:system library::No such file or directory error:80000002:system library::No such file or directory error:80000002:system library::No such file or directory error:80000002:system library::No such file or directory error:0A000086:SSL routines::certificate verify failed
```

**Comment by mpociot** [comment]
Please update your PHP version to fix this issue.

**Comment by theoreaves** [comment]
I updated to 8.2.9, but still get this error:

herd share
Could not connect to the server.
Connection to tls://us-1.sharedwithexpose.com:443 failed during TLS handshake: SSL operation failed with code 1. OpenSSL Error messages: error:0A0003E8:SSL routines::reason(1000)

**Comment by mpociot** [comment]
Could you tell me the output of `php --ini` and if this file exists?

**Comment by theoreaves** [comment]
php --ini
Configuration File (php.ini) Path: /lib
Loaded Configuration File:         (none)
Scan for additional .ini files in: /Users/treaves/Library/Application Support/Herd/config/php/82/
Additional .ini files parsed:      /Users/treaves/Library/Application Support/Herd/config/php/82/php.ini


Here is the contents of the /Users/treaves/Library/Application Support/Herd/config/php/82/php.ini file:

curl.cainfo=/Users/treaves/Library/Application Support/Herd/config/php/cacert.pem
openssl.cafile=/Users/treaves/Library/Application Support/Herd/config/php/cacert.pem
pcre.jit=0


I also found these:
/usr/local/etc/php/8.2/php.ini
/usr/local/Cellar/php/8.2.8/.bottle/etc/php/8.2/php.ini

**Comment by theoreaves** [comment]
I just updated to the latest version of php (8.2.10) and that did the trick.
Thanks!

**Comment by nam-co** [comment]
Hi, I'm on the latest version of 8.2, but also getting an SSL error, Sending emails has never work since I change to Herd ,  I did a fresh install with Sonoma and same thing (didn't install Valet)

```
file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages: error:0A000086:SSL routines::certificate verify failed
```

just in case, here is my php.ini (the paths seem correct)
```
curl.cainfo=/Users/macbookpro/Library/Application Support/Herd/config/php/cacert.pem
openssl.cafile=/Users/macbookpro/Library/Application Support/Herd/config/php/cacert.pem
pcre.jit=0

memory_limit=128M
upload_max_filesize=5M
```
<img width="349" alt="Screenshot 2023-11-01 at 12 14 13 PM" src="https://github.com/beyondcode/herd-community/assets/3951529/0b985ccd-bb53-437f-a3eb-0c7c77620c1a">

Appreciate any help

**Comment by mpociot** [comment]
@larskoole which URL are you trying to access? Is it a local one?

**Comment by larskoole** [comment]
`https://localurl.test/assets/demo/products/mbp14-2021.png`

**Comment by mpociot** [comment]
Was `localurl.test` secured by Herd?

**Comment by mpociot** [comment]
If you open the `cacert.pem` file in your ~/Library/Application Support/Herd/config/php folder, could you scroll to the bottom.
There should be individual entries from Herd as those certificates get appended to that file.

Like this:

![image.png](https://volta.s3.fr-par.scw.cloud/image_c462c2ccb5.png)

If those entries are not in there, could you try and re-run herd unsecure/secure for the local URL you are trying to access?

**Comment by larskoole** [comment]
If I unsecure, then both entries are still there. I'm guessing that's expected behavior.

**Comment by mpociot** [comment]
You should also be able to just quit and restart Herd. We automatically append all secured certificates to that file on application start

**Comment by larskoole** [comment]
I've unsecured the domain, then restarted Herd.
Both entries were gone (yay).
I've secured the domain (1 entry added to the cert).
But, still getting the same error, even after restarting all processes, the terminal, and Herd.

**Comment by mpociot** [comment]
Okay - this at least means that the cacert.pem file is correct. This means that your PHP version is for some reason not using the php.ini value.

How do you perform the file_get_contents call? Is it via FPM / in the browser, or via a Terminal command like artisan?

**Comment by larskoole** [comment]
Currently via terminal, but I can try via the browser too.

**Comment by mpociot** [comment]
If you do it via terminal, which PHP version do you use?

`which php` should point to the Herd PHP binary.

And `php --info | grep openssl.cafile` should give you the correct value from your php.ini file

**Comment by larskoole** [comment]
`/Users/lars/Library/Application Support/Herd/bin//php`

```
openssl.cafile => /Users/lars/Library/Application Support/Herd/config/php/cacert.pem => /Users/lars/Library/Application Support/Herd/config/php/cacert.pem
```

**Comment by larskoole** [comment]
Oh and I use php 8.2.11 in the terminal.

**Comment by mpociot** [comment]
Okay...so I'm able to reproduce this locally using file_get_contents.

It works when you're using the Laravel `Http` facade, as this one uses curl under the hood - and PHP tells curl to use the custom cacert.pem file.

But stream based functions like `file_get_contents` do not unfortunately use the custom certificate file.

You could manually set the default stream context and pass in the path to your cacert.pem file, even though I doubt that this is a good fix:

```php
stream_context_set_default([
    'ssl' => [
        'verify_peer' => true,
        'verify_peer_name' => true,
        'cafile' => '/path/to/your/cacert.pem'
    ]
]);
```

The other option would be to use a curl based solution like Guzzle or the Laravel Http facade to work around this issue.
Unfortunately, there's no other way to fix this as Herd's PHP binary does not know about the locally secured certificates otherwise.

**Comment by larskoole** [comment]
Oh that makes total sense, would you happen to know what the `file_get_contents` equivalent would be with the `Http` facade?

**Comment by mpociot** [comment]
Yeah that would be: `Http::get('https://my-local-site.test`)->body()`

In addition, you get a bunch of nice convenience methods to easily access headers or JSON data: https://laravel.com/docs/10.x/http-client

**Comment by larskoole** [comment]
Replaced all my `file_get_content` methods and works like a charm.

Thanks for all the help!
