### ISSUE TITLE
[Bug]: Site can’t be reached

### ISSUE THREAD

**Issue by rahmat-dev** [beyondcode/herd-community#153]
### Operating system version

macOS Ventura 13.5

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.2.0 (Build: 14)

### PHP Version

PHP 8.2.9 (cli) (built: Aug 22 2023 13:42:30) (NTS)

### Bug description

I cannot access my laravel project using Herd. It returns "This site can't be reached"
![image](https://github.com/beyondcode/herd-community/assets/40190205/25839fc6-615e-4bde-93d8-846748163db3)

I've started all services and no error.
![image](https://github.com/beyondcode/herd-community/assets/40190205/9a1bf782-3e61-4ad1-a01d-65fda79db3f4)

**Comment by Xmk** [comment]
I have a similar problem.
@rahmat-dev tell me how you decided?

**Comment by rahmat-dev** [comment]
> I have a similar problem. @rahmat-dev tell me how you decided?

I changed the use secure DNS setting in my brave browser which was previously Cloudflare to the current service provider

![image](https://github.com/beyondcode/herd-community/assets/40190205/b53560cd-7366-4de3-a078-bc423d2e566d)
