### ISSUE TITLE
[Feature Request]: Add documentation for creating local and global custom drivers

### ISSUE THREAD

**Issue by aaronbushnell** [beyondcode/herd-community#155]
### Feature Description

There seems to be some general confusion about the proper way to create local (#122, #33) and global (#81) custom drivers using Herd. While [Valet has some documentation](https://laravel.com/docs/10.x/valet#custom-valet-drivers) on this, it doesn't exactly match up to how Herd behaves (at least when it comes to custom drivers and the folder path to use).

I think an additional section under the documentation "Advanced Usage" for setting up drivers would really be helpful (and hopefully spare the Beyond Code team repetitive GitHub issues).

### Is this feature valuable for other users as well and why?

Yes, developers who are building WordPress, Craft, Drupal, and other non-Laravel apps often need to reconfigure things such as the public root of their project when using Herd (or Valet).

**Comment by sschlein** [comment]
We've added docs for this at https://herd.laravel.com/docs/1/extending-herd/custom-drivers
