### ISSUE TITLE
[Bug]: new PharData('my_file.tar.gz') fails silently on the command line

### ISSUE THREAD

**Issue by tomwelch** [beyondcode/herd-community#156]
### Operating system version

macOS Ventura 13.5.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.2.0 (Build: 14)

### Bug description

I'm using https://github.com/tronovav/geoip2-update to download Geoip2 database updates with the following code in a Laravel Command.

```php
$client = new Client([
    'license_key' => 'LICENSE_KEY_HERE',
    'dir' => database_path('maxmind'),
    'editions' => ['GeoLite2-City'],
]);

$client->run();
```

When running the command with artisan from the command line, the package downloads the required .tar.gz file and then attempts to extract it, but it fails silently when instantiating PharData.

Running the same code via a Controller methods works as expected.

Using the same version of PHP (8.2.9) on the command line installed via Brew also works as expected.

### Steps to reproduce

1. Create a new Laravel project and install https://github.com/tronovav/geoip2-update
2. Register an account an API key at Maxmind https://www.maxmind.com/en/geolite2/signup
3. Create the folder database/maxmind
4. Create a command with the code above in the handle method
5. Run the new command

You will see an archive file located at database/maxmind that doesn't get extracted.

**Comment by mpociot** [comment]
<img width="629" alt="image" src="https://github.com/beyondcode/herd-community/assets/804684/122ed186-9591-430d-8f0e-4f5b439cc666">

I just found the time to try your code. It all worked for me using the latest version of PHP (I tried it with 8.2 and 8.3)

**Comment by gofish543** [comment]
@mpociot  I can assure you this is not a closed issue. Same issues on MacOS

**Comment by tomwelch** [comment]
Hi @gofish543, thanks for pointing me in the right direction. I've done a bit of testing this morning and can confirm it is a memory constraint. Increasing PHP's memory to 256MB did the trick for me 👍

**Comment by ahegyen** [comment]
Inserting this row at first helped me too:
ini_set('memory_limit', '512M');

You can experience the same problem at this application too, the update doesn'tdownload the full db just few kBytes:
https://github.com/Torann/laravel-geoip
