### ISSUE TITLE
[Bug]: Unknown on line 0

### ISSUE THREAD

**Issue by cliffordjames** [beyondcode/herd-community#157]
### Operating system version

macOs Ventura 13.4.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.2.0 (Build: 14)

### PHP Version

PHP 8.2.9 (cli) (built: Aug 22 2023 13:42:30) (NTS)

### Bug description

I followed the instructions on the Installing additional PHP extensions page with the following:

```bash
brew install php
```

```bash
pecl install grpc
```

But now every time I use pecl it says: Warning: Module "grpc" is already loaded in Unknown on line 0

How do I get rid of this message?

### Steps to reproduce

```bash
brew install php
```

```bash
pecl install grpc
```

### Relevant log output

```shell
php --ini output:


Configuration File (php.ini) Path: /lib
Loaded Configuration File:         (none)
Scan for additional .ini files in: /Users/cliffordjamesvandenbos/Library/Application Support/Herd/config/php/82/
Additional .ini files parsed:      /Users/cliffordjamesvandenbos/Library/Application Support/Herd/config/php/82/php.ini
```
contents of ~/Library/Application Support/Herd/config/php/82/php.ini:

```
extension=/opt/homebrew/Cellar/php/8.2.9/pecl/20220829/grpc.so

curl.cainfo=/Users/cliffordjamesvandenbos/Library/Application Support/Herd/config/php/cacert.pem
openssl.cafile=/Users/cliffordjamesvandenbos/Library/Application Support/Herd/config/php/cacert.pem
pcre.jit=0
```
```

**Comment by mpociot** [comment]
Please check your homebrew php.ini file - it seems like pecl or grpc gets registered twice in the php.ini
