### ISSUE TITLE
[Bug]: Error with Expose configuration

### ISSUE THREAD

**Issue by KiritoXD01** [beyondcode/herd-community#158]
### Operating system version

macOS Ventura 13.5.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.2.0

### PHP Version

PHP 8.2

### Bug description

When I try to set up the expose token I get this message in the textbox:

Warning: preg_match(): Allocation of JIT memory failed, PCRE JIT will be disabled. This is likely caused by security restrictions. Either grant PHP permission to allocate executable memory, or set pcre.jit=0 in phar:///Users/kirito/Library/Application Support/Herd/bin/expose/.box/vendor/composer/semver/src/VersionParser.php on line 48

Box Requirements Checker
========================

> Using PHP 7.4.33
> PHP is using the following php.ini file:
  WARNING: No configuration file (php.ini) used by PHP!

> Checking Box requirements:
  E..

                                                                                
 [ERROR] Your system is not ready to run the application.                       
                                                                                

Fix the following mandatory requirements:
=========================================

 * The application requires the version "^8.1" or greater.

### Steps to reproduce

Open Expose configuration and I get this message in the Input to add the token:

![image](https://github.com/beyondcode/herd-community/assets/46627083/9539ffb0-e0de-44d0-9632-29dd9cdc7c57)

**Comment by mpociot** [comment]
I believe this happens when you temporarily switch the Herd version to something lower than PHP 8.1
I'll fix this in the next release.

In the meantime, please update your PHP version in Herd to 8.1+ to access this setting screen
