### ISSUE TITLE
[Documentation]: Duplicate hash links

### ISSUE THREAD

**Issue by carstenjaksch** [beyondcode/herd-community#159]
### Operating system version

macOS Ventura 13.0.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.2.0 (Build 14)

### Bug description

I used the docset generator of Dash to download the Herd docs.
Along the way I recognized that some headlines use duplicate IDs.

Here for example: https://herd.laravel.com/docs/1/advanced-usage/php-versions

- Via the GUI
- Via the CLI

Would be great if someone could check for more duplicates and edit them. I would do it, but couldn't find a public repo of the docs.

**Comment by sschlein** [comment]
The docs are generated from Markdown files on the fly and so we don't have control over this at the moment. I am considering this a minor issue that we might fix but not in the near future.
