### ISSUE TITLE
[Bug]: Herd logotype look-a-like

### ISSUE THREAD

**Issue by Kekos** [beyondcode/herd-community#160]
### Operating system version

N/A

### System architecture

Intel (x86)

### Herd Version

N/A

### Bug description

I noticed today that your logotype looks very similar to the one for the [Swedish Tenants’ Association](https://www.hyresgastforeningen.se/).

**Comment by sschlein** [comment]
I can at least asure you that we're not related and haven't seen this before, there have been multiple logo versions and that was the final one. Unfortunate, that they also use the Laravel brand color and it looks nearly identical.
