### ISSUE TITLE
[Bug]: SQLSTATE[HY000] [2002]  (trying to connect via (null)) 

### ISSUE THREAD

**Issue by tripletens** [beyondcode/herd-community#163]
### Operating system version

Ventura 13.0 

### System architecture

Intel (x86)

### Herd Version

1.0.6

### PHP Version

PHP 8.2.8

### Bug description

I tried connecting my database to my laravel application cloned from my github and  i keep getting this error. 

 SQLSTATE[HY000] [2002]  (trying to connect via (null)) (SQL: select * from information_schema.tables where table_schema = school_mgt and table_name = migrations and table_type = 'BASE TABLE')

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:760
    756▕         // If an exception occurs when attempting to run a query, we'll format the error
    757▕         // message to include the bindings with SQL, which will make this exception a
    758▕         // lot more helpful to the developer instead of just the database's errors.
    759▕         catch (Exception $e) {
  ➜ 760▕             throw new QueryException(
    761▕                 $query, $this->prepareBindings($bindings), $e
    762▕             );
    763▕         }
    764▕     }

      +36 vendor frames 
  37  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

I have checked my port and other database credentials and yet its not connecting properly. 

Thanks,

Chinonso

### Steps to reproduce

Clone this github repo: https://github.com/tripletens/school_app

1. Run git clone https://github.com/tripletens/school_app.git
2. Run composer install
3. Run cp .env.example .env
4. Run php artisan key:generate
5. Run php artisan migrate -->>> At this point i keep getting the error
6. Run php artisan serve
7. Go to link localhost:8000

**Comment by sschlein** [comment]
It looks like you haven't set up a database and point your `.env` file to it.
