### ISSUE TITLE
[Bug]: (Minor) App setting UI, round icons appear squished

### ISSUE THREAD

**Issue by sergeifilippov** [beyondcode/herd-community#167]
### Operating system version

MacOS Ventura 13.5.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.2.0 Build 14

### Bug description

Super minor display issue.

In the settings panel for the app. Look at the icons. The following icons have a round shape, but when you compare them to an actual circle, they appear squished.

1. General
2. PHP

![image](https://github.com/beyondcode/herd-community/assets/123676/1b9db002-c7ef-4f29-9feb-69fe77cdcd30)

### Steps to reproduce

Open the settings panel.

**Comment by mpociot** [comment]
![image](https://github.com/beyondcode/herd-community/assets/804684/1e4fd449-5031-425e-98eb-7960c22f079f)

They are pretty round to me 😅
