### ISSUE TITLE
[Feature Request]: Curl HTTP2 support

### ISSUE THREAD

**Issue by scrummitch** [beyondcode/herd-community#169]
### Feature Description

When creating a http2 request using curl client on a herd PHP instance, it always fails.

Try this locally:

    if (!defined('CURL_HTTP_VERSION_2_0')) {
        define('CURL_HTTP_VERSION_2_0', 3);
    }

    $version = curl_version();

    if ($version['features'] & constant('CURL_VERSION_HTTP2') !== 0) {

        $url = 'https://google.com/';

        $ch = curl_init();
        curl_setopt($ch,CURLOPT_URL,$url);
        curl_setopt($ch,CURLOPT_RETURNTRANSFER,true);
        curl_setopt($ch,CURLOPT_HEADER,1);
        curl_setopt($ch,CURLOPT_HTTP_VERSION,CURL_HTTP_VERSION_2_0);
        curl_setopt($ch,CURLOPT_SSL_VERIFYPEER,false);

        $response = curl_exec($ch);

        if ($response !== false && strpos($response, 'HTTP/2') === 0) {
            echo 'HTTP/2 support!';
        } elseif ($response !== false) {
            echo 'No HTTP/2 support on server.';
        } else {
            echo curl_error($ch);
        }
        curl_close($ch);
    } else {
        echo 'No HTTP/2 support on client.';
    }

    echo '\n';

### Is this feature valuable for other users as well and why?

It would be nice to be able to make http2 requests, especially as i am building a local APNS notification service. As far as I can tell, this worked fine on Valet.

**Comment by scrummitch** [comment]
Obligatory phpinfo() 
<img width="974" alt="image" src="https://github.com/beyondcode/herd-community/assets/990013/71624675-133a-4f55-9404-c1f4efb8f99c">

**Comment by mpociot** [comment]
Thanks for reporting this. I'm able to reproduce this. I'll publish a new PHP update with curl HTTP2 enabled

**Comment by scrummitch** [comment]
Thanks @mpociot, I love herd ❤️

**Comment by mpociot** [comment]
New PHP builds are currently distributed that will have HTTP2 enabled 🎉
