### ISSUE TITLE
[Bug]: Valet custom local drivers don't work

### ISSUE THREAD

**Issue by slovenianGooner** [beyondcode/herd-community#17]
### Operating system version

macOS Ventura 13.3

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.0.6 (Build 8)

### Bug description

My local valet driver is not working the same as on the Valet installation. 

As per @mpociot this is a known issue that will be resolved soon as Herd is currently using a fork of Valet. 

Just wanted to keep this bug on the record so it doesn't get left out :)

**Comment by mpociot** [comment]
I just tested this locally.
It seems like Herd does not migrate existing custom drivers.
In order to load custom Valet drivers, please copy your existing drivers into the correct Herd folder:

```
~/Library/Application Support/Herd/config/valet/Drivers
```

Then your custom drivers will keep working as usual!

We'll also modify the onboarding for new users so that existing drivers will be migrated automatically.

**Comment by slovenianGooner** [comment]
My stupid brain wrote the issue wrong. This is actually to do with Local Valet drivers and not custom ones. So the issue is this lines of code are different in the Valet for you have in Herd and the one in official Valet. Hence our LocalValetDriver class is not loaded properly.

This one requires a namespace (which I can fix in our projects)
![F1ecNGMXoAItPOJ](https://github.com/beyondcode/herd-community/assets/1257629/2a071509-5794-4d30-a3eb-037059a6f62c)

This one assumes there is no namespace:
![F1ecNGTWYAAxDQM](https://github.com/beyondcode/herd-community/assets/1257629/b80d7609-a5e6-4094-937a-7ffa87d721ce)

Problem arises not everyone in our team will use Herd so should be compatible between Valet and Herd ;)

**Comment by mpociot** [comment]
Oh right - this will then be fixed as soon as we migrate to the latest version of Valet!
