### ISSUE TITLE
.user.ini file not working

### ISSUE THREAD

**Issue by barchard** [beyondcode/herd-community#171]
I think I am seeing the same issue with `.user.ini` files. I have a `.user.ini` file in the Herd site's document root with a `auto_append_file` directive specified. The path is the full/absolute path to a `.php` file. If you look at the `phpinfo();`, you'll see that the additional `.ini` file is *not* parsed.

Directory structure:

```
/path/to/herd/site/
/path/to/herd/site/index.php
/path/to/herd/site/.user.ini
/path/to/herd/site/subfolder/auto_append_file.php
```

Contents of `.user.ini`:

```
[Herd]
auto_append_file = "/path/to/herd/site/subfolder/auto_append_file.php"
zlib.output_compression = "On"
```

The contents of `index.php`:

```
<?php phpinfo(); ?>
```

You'd expect that the `.user.ini` file is parsed and load the `auto_append_file.php` but the output of `phpinfo` shows:

```
Scan this dir for additional .ini files | (none)
-- | --
Additional .ini files parsed | (none)
```

_Originally posted by @barchard in https://github.com/beyondcode/herd-community/issues/129#issuecomment-1688597003_

**Comment by mpociot** [comment]
The `.user.ini` file is currently not supported by Herd.
Do you know if this is supported by Laravel Valet?

**Comment by neurotools** [comment]
Is there any other way to set specific php.ini values for one Herd site?

**Comment by jorenvh** [comment]
@mpociot any update on the possibilities for this?
