### ISSUE TITLE
[Bug]: Preview of index.php 404 Not Found 

### ISSUE THREAD

**Issue by AlaaEddinAlbarghoth** [beyondcode/herd-community#172]
### Operating system version

404 Not Found

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.0.6 (Build: 8)

### PHP Version

PHP 8.2.8

### Bug description

I always got this error "404 Not Found" when trying to preview the code I did.
I already configured the settings of PHP like this 

<img width="622" alt="Screenshot 2023-09-09 at 14 06 25" src="https://github.com/beyondcode/herd-community/assets/16362865/47175327-03d1-49be-a390-f09777b9c58f">

**Comment by mpociot** [comment]
Hey,

I personally never used the preview feature, so I'm not sure what the actual output should be.
If you're getting a 404 response (from Herd) then there must be some path mapping missing in PHPStorm?

I'm also unable to reproduce this locally, as the preview doesn't even work at all on my machine. It just tries to open a PHP file in the browser (without actually hitting a server).
