### ISSUE TITLE
[Feature Request]: Option to hide the icon in the statusbar

### ISSUE THREAD

**Issue by CamilleScholtz** [beyondcode/herd-community#174]
### Feature Description

There is no real reason for the (quite big) icon to always be visible. All other 'deamon' apps I use have this ability. If the user wants to access the settings he should just be able to (re)launch the Herd app which in turn should display the settings menu.

Related issue: #105

### Is this feature valuable for other users as well and why?

Yes, most other apps have this option, which shows you people make use of it.

**Comment by mpociot** [comment]
Herd has quite a lot of essential actions in the menubar application (like setting the default PHP version, restarting services, etc) and those actions are not available when you open just the settings window.
I don't think we'll add this in the near future - **but** we'll make the icon smaller :D

**Comment by ju5t** [comment]
@mpociot in the changelog it says the height of the icon has changed. Does this relate to your comment about making it smaller or is this something else?

Because after the update, the icon is as big as before.
