### ISSUE TITLE
[Bug]: Site can't be reached (ERR_NAME_NOT_RESOLVED)

### ISSUE THREAD

**Issue by rubenmoya** [beyondcode/herd-community#175]
### Operating system version

macOS Ventura 13.5.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.2.0 (Build: 14)

### PHP Version

PHP 8.2.10 (cli) (built: Sep  1 2023 00:12:21) (NTS)

### Bug description

I'm new to all this PHP/Laravel/Herd world, so I don't really know how all this tools (valet/herd) work under the hood, please bear with me.

I installed Valet a while back, and used it for a little bit. Then when I read about Herd I uninstalled Valet and installed Herd, but somehow it still told me that "You have valet installed, let's migrate, etc".

Some services didn't start, but I restarted the computer and it worked.

Today I'm tried to use it again, but I keep getting the "Site can't be reached" error. I tried to upgrade to the latest Herd version, uninstall it, install it again, restart the computer, etc. And I still get the error, I'm not sure what I'm doing wrong.

I have checked the nginx, DNSMask and FPM-8.2 logs, and the only one with contents is the last one, this is the log:

![image](https://github.com/beyondcode/herd-community/assets/905225/d99386a8-2751-42db-a4c9-89d42438e356)

The app itself looks like everything is "working":

![image](https://github.com/beyondcode/herd-community/assets/905225/ce5ba355-7841-4d85-a766-e0260d5cd1ae)

I'm not sure where to look at, or what to try, so any help is appreciated.

Let me know if there is any more information that I can provide!

**Comment by Gandhi11** [comment]
I have the same problem on a Intel Mac

**Comment by jhgeluk** [comment]
Experiencing the same

**Comment by mpociot** [comment]
Could you please check if the following file exists: `/etc/resolver/test`?
If it does not, please create it with the following content:

```
nameserver 127.0.0.1
```

**Comment by rubenmoya** [comment]
Sorry to reopen this, I've just checked and it does exist:

![image](https://github.com/beyondcode/herd-community/assets/905225/4ab90974-14bc-4172-8b3d-7ce931a9d5cc)

Is there any information I can provide to debug it?

**Comment by sadhakbj** [comment]
I am also facing the same issue, valet was working perfectly fine, installing herd seems to be a problem for me.

**Comment by henryonsoftware** [comment]
I got the same problem, and yes on Intel Mac

**Comment by muba00** [comment]
I got the same problem "This site can’t be reached", and but on M1 Mac

**Comment by drlogout** [comment]
Same here.

**Comment by samueloshio** [comment]
Am facing same problem on windows 10. Is there any way to fix this please. I'm completely new to PHP Laravel and herd world. As matter of fact, this is my first bite using Laravel bootcamp chirper project 😉

As for my case, herd is serving from c:\users\user\Herd
Site in this directory like http://chirper.test says can't be reach

Any support to fix this will be appreciated 👍

**Comment by laurensgroeneveld** [comment]
In my case (on Mac) this was caused by having a NextDNS profile installed. When I disabled it I could access the site again (had to do a `composer install` first but not sure if that was related).

**Comment by joeyboli** [comment]
Solution : open your browser and change dns to default os dns

**Comment by phutd** [comment]
In my case ( on Mac intel ), open GG Chrome settings and change DNS.
Example: GG public DNS - DNS Os

It works well for me.

**Comment by THUANDOVAN93** [comment]
> Solution : open your browser and change dns to default os dns

In my case (on Mac Intel), open GG Chrome settings and change DNS (change to OS default)
It works well for me.

**Comment by andipyk** [comment]
<img width="803" alt="Screenshot 2024-05-05 at 13 23 31" src="https://github.com/beyondcode/herd-community/assets/11852352/42d8f6cd-9c72-4950-af2b-fc8dd1de6e04">

**Comment by andipyk** [comment]
![chrome-capture](https://github.com/beyondcode/herd-community/assets/11852352/690a25db-0a98-4c1f-8580-69ecbc19b097)

**Comment by superbolang** [comment]
Hello I encountered the same problem and above method didn't work

**Comment by clipsmm** [comment]
Still experiencing the issue. It has been working the suddenly stopped working for all .test domains

ERR_TUNNEL_CONNECTION_FAILED

![Screenshot 2024-07-02 at 13 38 04](https://github.com/beyondcode/herd-community/assets/5929813/74ecf090-8ed4-419c-b46f-dda729b0c4e8)

MacBook Pro M3

**Comment by hexlay** [comment]
None of the above helped on latest macos and latest herd (1.9.1) i still have ERR_NAME_NOT_RESOLVED and can't seem to fix it, also no logs are being written for that as well

**Comment by lancedouglas1** [comment]
Same issue, above solutions didn't help. Latest Herd and MacOs on M3

**Comment by jeffegiovani** [comment]
For me, in Windows, above solutions didn't help. Reinstalling Herd solved my problem.

**Comment by rvanbaalen** [comment]
Note to future self or others; for me, Little Snitch (network firewall) was routing all requests to a secure DNS server. Added a custom exception for the project.test domain and it worked.

**Comment by andipyk** [comment]
So Easy 

Edit file hosts:
edit host
```
sudo nano /etc/hosts
```

then 

```
127.0.0.1    yourlaravel.test

```

**Comment by andipyk** [comment]
> > So Easy
> > Edit file hosts: edit host
> > ```
> > sudo nano /etc/hosts
> > ```
> > 
> > 
> >     
> >   
> > then
> > ```
> > 127.0.0.1    yourlaravel.test
> > ```
> 
> Ite and if your app is multi tenant with sub domain tenancy so you need to have wildcard *.yourlaravel.test?

Hosts do not support wildcards, so you have to explicitly write:
```
127.0.0.1  tenant1.yourlaravel.test  
127.0.0.1  tenant2.yourlaravel.test  
#and so on.
```

I know this is not ideal, but switching to a different browser for development could also be a solution.”

**Comment by HQuserTR** [comment]
F*ck herd, thats it.

**Comment by krisnaw** [comment]
Can you provide an update on this issue? I encountered an error when attempting to access the site using Google Chrome, but it functions correctly on Safari.

**Comment by tolnaiz** [comment]
Probably not the most robust solution, but in NextDNS settings you can add rewrites like:
*.test → 127.0.0.1
