### ISSUE TITLE
[Feature Request]: View/Update Nginx Conf

### ISSUE THREAD

**Issue by bentradesupport** [beyondcode/herd-community#177]
### Feature Description

It would be nice to be able to have access to the nginx conf files for each site through the UI. It would also be nice to have access to the main nginx conf so I could extend the timeout on my local machine for special processes. One of my wordpress plugins is timing out and I cannot run it from CLI. 

### Is this feature valuable for other users as well and why?

This feature should be useful for many folks that need to make special changes or proxies to other ports or IP addresses for non-php (eg, node) processes.

**Comment by s7thamon** [comment]
Also having this issue with nginx timeout, were you able to figure out how to increase it?

**Comment by mpociot** [comment]
You can already update and view the nginx configuration file.
It is located in: `~/Library/Application Support/Herd/config/nginx`

**Comment by bentradesupport** [comment]
@mpociot I have tried updating all of the CONF files I can find in the HERD, however, NGINX always times out at around 6:30 seconds. I've updated the individual conf for the Herd site as well, restarted both herd and my machine, yet 6:30 timeout for nginx. I've set all timeouts to 5 days in all PHP INI files and all NGINX CONF files, yet always a timeout. 

Am I missing something? Also, I had to hunt down manually that location after I made this post initially. There is no mention of that anywhere in any docs that I can find. So an update to docs, or a menu option similar to the "php.ini" option that opens the nginx conf folder on the local machine would be helpful.

**Comment by rabiibrahimi** [comment]
I have same issue, can't find the location of ~/Library/Application Support/Herd/config on my machine. It would be nice if this could be opened from UI.
Thanks

**Comment by peter-tell** [comment]
Bumping this as well. Is there anyway we can increase the NGINX timeout?

**Comment by robertuniqid** [comment]
> I have same issue, can't find the location of ~/Library/Application Support/Herd/config on my machine. It would be nice if this could be opened from UI. Thanks

Use the UI to show the php.ini file, then you can see the directory location, I've spent a lot of time trying to find an answer, and used `EasyFind`, and noticed the PHP folder was right beside it.

**Comment by arunava-t-exponent** [comment]
I want to set reverse proxy in nginx for running my node application. I edit .conf file also for nginx. But it not worked. It would be good if user can modified nginx configuration.

**Comment by JackEllis** [comment]
@mpociot +1 on this please, I am dying over here 😭

**Comment by abewartech** [comment]
on windows where is path of nginx?

**Comment by AmirJavaidSwe** [comment]
Has anyone found an answer? what is the easiest way to add different configurations for nginx for each site on Mac?

**Comment by ekowamoonu** [comment]
On Windows, you can find the config files here  C:\Users\<Username>\.config\herd\config
