### ISSUE TITLE
[Bug]: Herd showing too many folders under the sites 

### ISSUE THREAD

**Issue by rehanazher** [beyondcode/herd-community#178]
### Operating system version

macOs Ventura 13.3

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.2.0 (Build 14)

### PHP Version

PHP 8.2

### Bug description

When I add my laravel project under General Tab , under sites tab it shows a lot many folders as sites but none of those works. 

![image](https://github.com/beyondcode/herd-community/assets/64159/1988b64c-4cf4-4851-bf45-53dc95f0373d)

![image](https://github.com/beyondcode/herd-community/assets/64159/4b666b05-54f0-47c0-93ec-c4b3dba3853e)

i have two projects one of those is working fine as expected but other is not. 

### Steps to reproduce

Not sure how to reproduce

**Comment by TheAbhishekIN** [comment]
remove starter kit from list in **General** tab using ➖ button

**Comment by mpociot** [comment]
As @TheAbhishekIN suggests, the "Herd paths" are meant to be the root paths under which all of your PHP projects live.
You are not supposed to add individual sites directly to this list, but rather the parent folder.

**Comment by rehanazher** [comment]
Hi,   will moving my starterkit project under /Development/laravel work. Will give it a try later today. Thanks
