### ISSUE TITLE
[Bug]: Securing sites via Herd returns a CERT_AUTHORITY_INVALID error

### ISSUE THREAD

**Issue by genericmilk** [beyondcode/herd-community#18]
### Operating system version

macOS Ventura 13.4.1 (c)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.0.8 (Build: 10)

### PHP Version

PHP 8.2.6 (cli) (built: Jun  2 2023 23:59:34) (NTS)

### Bug description

Securing Laravel applications in Herd results in the site returning a NET::ERR_CERT_AUTHORITY_INVALID response in Chrome. Unsecuring the site also no longer returns the site to http:// (Non SSL).

This has been the case on 2 machines (Both M1 Max) that have both been ported from Laravel Valet### 

### Steps to reproduce

1. Create a new laravel site in a parked folder using `laravel new test` 
2. Visit `http://test.test` in the browser and note it is non SSL.
3. Using Herd's sites manager click the padlock icon for `test.test`
4. Reload the page
5. Chrome displays a NET::ERR_CERT_AUTHORITY_INVALID message
6. Clicking the padlock again does not revert the site to non SSL

**Comment by genericmilk** [comment]
(It's worth noting that this works when using `herd secure` in the root folder of the project)

**Comment by mpociot** [comment]
So running `herd secure` via CLI works for you, but not via the UI? 🤔

**Comment by genericmilk** [comment]
Yeah bit of a weird one. Herd UI reports it as secured and following up with a `herd secure` fixes the SSL cert:
<img width="809" alt="Screenshot 2023-07-22 at 21 31 28" src="https://github.com/beyondcode/herd-community/assets/1846127/3bd33151-78db-47a0-8cb6-6af6aa9fe683">

**Comment by genericmilk** [comment]
Here's a chain of screenshots to better illustrate with me making a new laravel app `example`:
<img width="1912" alt="Screenshot 2023-07-22 at 22 25 27" src="https://github.com/beyondcode/herd-community/assets/1846127/f2d40711-cdfa-4e8b-a464-f22c1736f757">
(Note this is running http / non ssl)
<img width="1022" alt="Screenshot 2023-07-22 at 22 25 44" src="https://github.com/beyondcode/herd-community/assets/1846127/a7e847f6-6483-4df7-ae8e-8adbeeec3ddc">
The padlock is clicked to secure the site

<img width="1912" alt="Screenshot 2023-07-22 at 22 25 47" src="https://github.com/beyondcode/herd-community/assets/1846127/bf4f4d3f-2abd-42a3-8b8a-6585e2e4d232">
The certificate error occurs

<img width="922" alt="Screenshot 2023-07-22 at 22 26 04" src="https://github.com/beyondcode/herd-community/assets/1846127/bae2df11-ffcb-40ea-9a26-70e1153148f7">
`herd secure` is run manually in project root

<img width="1912" alt="Screenshot 2023-07-22 at 22 26 06" src="https://github.com/beyondcode/herd-community/assets/1846127/074d7905-d9d1-4bb2-9bb6-fdcc9c57c74e">
The cert attaches properly

**Comment by genericmilk** [comment]
I don't know if it's any help also but I am asked for sudo (root) when using `herd secure` in the terminal but not in the Herd app. It's possibly a case that a command is failing which needs super user access perhaps? (Just guessing here as I have no idea lol!)

**Comment by mpociot** [comment]
We just fixed this issue locally and will release a new version shortly 👍
