### ISSUE TITLE
[Bug]: throwing cURL error 60 even though ssl is enabled.

### ISSUE THREAD

**Issue by bkintanar** [beyondcode/herd-community#180]
### Operating system version

macOS Ventura 13.5.2 (22G91)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.2.0 (Build:14)

### Bug description

I'm having a cURL error 60 when my laravel application tries to ping. Both local projects are hosted by herd and both projects ssl enabled in herd as well.

```
local.ERROR: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://{herd-domain}.test/random-endpoint
```

![CleanShot 2023-09-18 at 16 05 27](https://github.com/beyondcode/herd-community/assets/685928/8dfb79c5-9dc8-4e99-95f7-f89d62ea4644)

![CleanShot 2023-09-18 at 16 07 50](https://github.com/beyondcode/herd-community/assets/685928/75672eea-e9e0-49d4-acd1-e11340b44a35)

![CleanShot 2023-09-18 at 16 09 28](https://github.com/beyondcode/herd-community/assets/685928/2c219392-cd9c-4baa-9820-37eb3c4e6b8b)

**Comment by mpociot** [comment]
Right, this is an issue that occurs when you restart Herd.
We'll publish a patch release to address this issue 👍
