### ISSUE TITLE
[Bug]: Project.test cannot access the site after activating the local global DOH DNS service

### ISSUE THREAD

**Issue by echome123** [beyondcode/herd-community#188]
### Operating system version

macOS 13.5

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.2.0

### Bug description

My local computer has enabled the global DOH NDS service through the configuration profile. At this time, running Herd to access project.test cannot be accessed, but when I close the DOH service, everything returns to normal.

### Steps to reproduce

DOHconfiguration profile from: https://github.com/paulmillr/encrypted-dns/

**Comment by mpociot** [comment]
I don't know about DOH DNS, but Herd uses DNSMasq as a separate DNS server. This is to resolve all `*.test` domains to localhost.
DNSMasq uses a resolver file located in `/etc/resolvers/test`, which points all test domains to the local nameserver.

So I suppose you would need to configure DOH DNS to work nicely with DNSMasq
