### ISSUE TITLE
[Bug]: Can't detect executable (FFMpeg)

### ISSUE THREAD

**Issue by PhiloNL** [beyondcode/herd-community#19]
### Operating system version

13.3.1 (a) 

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.0.8

### PHP Version

PHP 8.2.6 (cli) (built: Jun  2 2023 23:59:34) (NTS)

### Bug description

I'm using the [PHP FFMpeg](https://github.com/PHP-FFMpeg/PHP-FFMpeg) library and the following code works in the CLI but not via the browser.

```php
$ffprobe = \FFMpeg\FFProbe::create();
$duration = $ffprobe->format('file.mp3')->get('duration');

// CLI:
"9.994625"

// Web:
FFMpeg\ Exception \ ExecutableNotFoundException: Unable to load FFProbe
```

### Steps to reproduce

You can use the library above or simply try to `exec` something.

```php
exec('ffprobe -v quiet -print_format json -show_format -i file.mp3', $output); dd($output);
```

When using `php artisan tinker`, it will return results.
When using the browser it will return an empty array.

**Comment by mpociot** [comment]
Interesting, seems like FPM ignores the PATH environment variable 🤔 
I assume the same code worked on Valet?

**Comment by PhiloNL** [comment]
Yes, but the result seems to be the same for other things, for example:

Terminal:
```shell
php artisan tinker
Psy Shell v0.11.19 (PHP 8.2.6 — cli) by Justin Hileman
> exec('php -v', $output, $resultCode); dd($output, $resultCode);
array:4 [ // vendor/psy/psysh/src/ExecutionLoopClosure.php(53) : eval()'d code:2
  0 => "PHP 8.2.6 (cli) (built: Jun  2 2023 23:59:34) (NTS)"
  1 => "Copyright (c) The PHP Group"
  2 => "Zend Engine v4.2.6, Copyright (c) Zend Technologies"
  3 => "    with Zend OPcache v8.2.6, Copyright (c), by Zend Technologies"
]
0

> exec('which php', $output, $resultCode); dd($output, $resultCode);
= "/Users/philo/Library/Application Support/Herd/bin//php"
``` 

Browser:

```
[] 
127 // According to StackOverflow value 127 is returned by /bin/sh when the given command is not found within your PATH system variable, and it is not a built-in shell command.

[]
1 // The command execution failed with a completion code that signals an error.
```

**Comment by mpociot** [comment]
Interesting. I'll see if there's something missing from the FPM config, even though that's the same as Valet.

**Comment by PhiloNL** [comment]
I did a fresh valet install with Valet on a virtual machine, and it no longer works there 😅 really weird; it must be some strange local thing, so it might not be related to Herd 😄. I ended up fixing this by setting the executables manually:

```
$ffprobe = \FFMpeg\FFProbe::create([
            'ffmpeg.binaries'  => env('FFMPEG_BINARIES'),
            'ffprobe.binaries' => env('FFPROBE_BINARIES'),
        ]);
```
