### ISSUE TITLE
[Feature Request]: Multiple URL option

### ISSUE THREAD

**Issue by Jafo232** [beyondcode/herd-community#191]
### Feature Description

It would be helpful if we could point multiple URLs to a single path.  I have not been able to figure out a way to do this.

### Is this feature valuable for other users as well and why?

Lots of applications use things like cnames for example in their logic.  i.e. a user comes in at admin.DOMAIN.TEST takes them to the apps admin portal.

**Comment by jsmit99** [comment]
+1 would be great addition

**Comment by jmarcher** [comment]
I use symlinks for this.

**Comment by mpociot** [comment]
You can already do this by using `herd link` via the CLI.

To use it:

```
cd my-site
herd link my-alias
```

This links the site "my-site" as `my-alias.test`, so it's available with both URLs.
