### ISSUE TITLE
[Bug]: 500 Internal Server Error

### ISSUE THREAD

**Issue by milanchheda** [beyondcode/herd-community#196]
### Operating system version

Ventura 13.4.1 (c)

### System architecture

Intel (x86)

### Herd Version

1.2.1 (Build: 15)

### PHP Version

8.2

### Bug description

I have setup an existing simple laravel application (Laravel Framework 10.9.0) which I added inside herd and expected it would just work but I keep getting `500 internal server error`. But if I do `php artisan serve`, application works fine. There are no errors in `laravel.log` too. While I understand, its not Herd issue, can someone tell/help me what can be the issue here? Also, I have kept `APP_DEBUG=true` but it doesn't show error on the screen. Why?

<img width="891" alt="image" src="https://github.com/beyondcode/herd-community/assets/1329515/ac549231-20be-45de-a62c-902daf356c06">

### Relevant log output

```shell
There are no errors or warnings in laravel.log.
```

**Comment by arnaudlidz** [comment]
Same, I've installed new version of macOs and herd no works anymore

**Comment by mpociot** [comment]
Do you see any errors in your FPM log files?
You can access them here: `~/Library/Application Support/Herd/Log/`
Some content might also be written in the windows when you click on the log icon in the menu bar next to FPM/nginx

**Comment by milanchheda** [comment]
@mpociot: I checked but all logs are empty. Nothing is Nginx nor in FPM.

**Comment by milanchheda** [comment]
Shut down laptop.
Took a break.
Started laptop.
Turned out there was a problem with `.env`. 
Apologies for raising this issue.
Thanks for the support.

**Comment by mpociot** [comment]
Ahh, well good that you figured it out :)

**Comment by kumbirai265** [comment]
What was the problem with it?

**Comment by clementmas** [comment]
My `.env` file had a line commented-out with a semi-column instead of a hash resulting in a 500 error. I didn't see any error message or log until I ran:

```bash
php artisan 
The environment file is invalid!
Failed to parse dotenv file. Encountered an invalid name at [; QUEUE_CONNECTION].
```

**Comment by arvidkahl** [comment]
Just ran into the same issue with `.env` — a stray quote mark had snuck into the file, and because `.env` isn't tracked by git, I didn't see that it had changed.
