### ISSUE TITLE
[Bug]: Documentation does not tell you to remove the PATH changes when uninstalling

### ISSUE THREAD

**Issue by markjaquith** [beyondcode/herd-community#2]
### Operating system version

macOS Ventura 13.4.1

### Herd Version

1.0.6

### Bug description

When uninstalling Herd, the documentation does not tell you that `.zshrc` was edited and to revert those changes. Mine contained:

```zsh
# Herd injected PHP binary.
export PATH="/Users/mark/Library/Application Support/Herd/bin/":$PATH
export PHP_INI_SCAN_DIR="/Users/mark/Library/Application Support/Herd/config/php/":$PHP_INI_SCAN_DIR
```

### Steps to reproduce

1. Install Herd
2. Follow the Herd uninstall steps
3. `echo $PATH` and see that Herd is still present.

**Comment by mpociot** [comment]
I just added this to the uninstallation documentation 👍
