### ISSUE TITLE
[Bug]: Menu shows 2 PHP versions running

### ISSUE THREAD

**Issue by trig79** [beyondcode/herd-community#20]
### Operating system version

macOS ventura 13.4

### System architecture

Intel (x86)

### Herd Version

1.0.8 build 10

### Bug description

Hey 
In the toolbar dropdown, when you have changed versions of PHP, they remain in the services list and are shown as active.
They also remain on the list when restarting the application. 
You can see here that FPM-8.1 and 7.4 are showing as running:  
<img width="206" alt="image" src="https://github.com/beyondcode/herd-community/assets/65402006/52b8a2fb-3ea6-4752-8689-a7a6853ed582">. 

note: This doesn't affect the behavior of the application and when checking in the terminal the correct version of PHP is always present.

Proposal:
The services section should only show nginx, DNSMasq, and the PHP version you have selected.

### Steps to reproduce

load applications, choose different PHP versions, and check if they persist in the services section.

### Relevant log output

```shell
n/a
```

**Comment by mpociot** [comment]
This is because your have a PHP site that is isolated as PHP 7.4. 
Toggling the PHP Version changes the default version, but if isolated sites require other PHP versions they will always show up in the list.
