### ISSUE TITLE
[Feature Request]: Support for PHP7.3 , PHP7.2

### ISSUE THREAD

**Issue by inuryyev** [beyondcode/herd-community#200]
### Feature Description

I currently have projects that are running on PHP 7.3 and 7.2. If PHP 7.3 and 7.2 are supported, I won't need to set up a separate environment for these projects

### Is this feature valuable for other users as well and why?

Yes, this feature can be valuable for other users who work with different old versions of PHP .

**Comment by mpociot** [comment]
Hey,

unfortunately we can't provide older versions of PHP as static binaries, which is why we're starting with PHP 7.4 in Herd.
If you need older versions, you can install and use them manually via Homebrew.

**Comment by esemlabel** [comment]
I hope you can post instructions how to switch to php version from homebrew. I have installed php 7.1. unfortunatelly, herd does not have something like valet use
