### ISSUE TITLE
[Bug]: Update Error!

### ISSUE THREAD

**Issue by LHongy** [beyondcode/herd-community#205]
### Operating system version

macOS 13.5.2 (22G91)

### System architecture

Intel (x86)

### Herd Version

1.2.2

### Bug description

Failed to Updating to 1.3.0.
![image](https://github.com/beyondcode/herd-community/assets/21149156/5af36bb8-09e4-48dc-9631-0d0bb3bd7f7b)

**Comment by mpociot** [comment]
Hey,

I'm unable to reproduce this as I successfully updated from 1.2.2 on both my M1 Macbook as well as my Intel Macbook.
I guess this is a CDN/URL issue on your end that should be resolved automatically.

Maybe try downloading the update again in a couple of minutes.
