### ISSUE TITLE
[Bug]: -1 Memory Limit not Maintained

### ISSUE THREAD

**Issue by nedwors** [beyondcode/herd-community#206]
### Operating system version

macOS Sonoma 14.0

### System architecture

Intel (x86)

### Herd Version

1.3.0 (Build 17)

#### Expected
1. Set memory limit in UI to `-1`
2. See that `-1` is preserved in UI
3. See that `-1` as a memory limit is applied to `php.ini` file

#### Actual
1. Set memory limit in UI to `-1`
2. `-1` updates to `1` in UI after changing tabs and navigating back
3. `1M` is set as memory limit in `php.ini` file

### Steps to reproduce

1. Set memory limit in UI to `-1`
2. Select "Sites" tab, then select "PHP" tab
3. See that memory limit is now `1` in UI
4. See that `1M` is set as memory limit in `php.ini` file

> Interestingly, before updating Herd I already had `-1` in my `php.ini`. Upon opening Herd after updating to `1.3.0`, the memory limit was already filled with `1` - not `-1` in the UI.

**Comment by mpociot** [comment]
Ahh right - seems like it's an issue with the pre-selection of the value.
If you enter `-1` in the UI, the correct value of `memory_limit=-1` will be written to your php.ini file.

But if you then re-open the settings, it will prefill the input field with `1` and therefore override your existing settings.

Thanks for reporting this, I'll publish a 1.3.1 bugfix later today 👍

**Comment by nedwors** [comment]
No problemo - thanks a bundle 😎

**Comment by mpociot** [comment]
Fixed in 1.3.1
