### ISSUE TITLE
[Bug]: Unable to save UI php.ini settings

### ISSUE THREAD

**Issue by kupoback** [beyondcode/herd-community#207]
### Operating system version

macOS Monterey 12.7

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.3.1 (Build 18)

### PHP Version

PHP 8.1.24

### Bug description

When changing Upload Size, or Memory Limit, the values update in the appropriate php.ini, however when you click off the tab in the UI, and go back to PHP, it resets to the default values.

### Steps to reproduce

Open up Herd Settings UI
Navigate to the PHP tab
Change the values of Upload Size and/or Memory Limit
Navigate to another tab
Navigate back to the PHP Tab
Observe the values changing

![Herd PHPini Bug](https://i.ibb.co/KypFbHN/Herd-PHPini-Bug.gif)

**Comment by mpociot** [comment]
Could you see if the PHP 8.0 php.ini file gets modified?
All installed versions should be updated

**Comment by karimApps142** [comment]
@kupoback facing same issue did you solve it?

**Comment by kupoback** [comment]
> @kupoback facing same issue did you solve it?

Only way is to edit the files instead of using the GUI. Then avoid that tab in the GUI.

**Comment by mpociot** [comment]
Unfortunately we aren't able to reproduce this issue.
