### ISSUE TITLE
[Bug]: Xdebug not enabled since update to 1.3.1

### ISSUE THREAD

**Issue by euperia** [beyondcode/herd-community#209]
### Operating system version

macOS Ventura 13.5.2

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.3.1 (Build 18)

### PHP Version

PHP 8.1

### Bug description

I have enabled xdebug in the php.ini config as described in the documentation and restarted Herd.

The cli shows that it is enabled, but output from `phpinfo()` doesn't show the XDebug section.

### Steps to reproduce

```shell
> brew install php@8.1
> pecl install xdebug
```

```ini
# /Users/<username>/Library/Application Support/Herd/config/php/81/php.ini
curl.cainfo=/Users/<username>/Library/Application Support/Herd/config/php/cacert.pem
openssl.cafile=/Users/<username>/Library/Application Support/Herd/config/php/cacert.pem
pcre.jit=0


zend_extension=/opt/homebrew/lib/php/pecl/20210902/xdebug.so
xdebug.mode=debug

memory_limit=512M
upload_max_filesize=16M

```

```shell
> which php
/Users/<username>/Library/Application Support/Herd/bin//php
```

```shell
> php -v
PHP 8.1.24 (cli) (built: Sep 29 2023 00:22:23) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.24, Copyright (c) Zend Technologies
    with Xdebug v3.2.2, Copyright (c) 2002-2023, by Derick Rethans
    with Zend OPcache v8.1.24, Copyright (c), by Zend Technologies
```
```shell
>php --ini
Configuration File (php.ini) Path: /lib
Loaded Configuration File:         (none)
Scan for additional .ini files in: /Users/<username>/Library/Application Support/Herd/config/php/81/
Additional .ini files parsed:      /Users/<username>/Library/Application Support/Herd/config/php/81/php.ini
```

Quit Herd and restart, visit page with `phpinfo()`

![CleanShot 2023-10-12 at 10 11 27](https://github.com/beyondcode/herd-community/assets/2648745/6454c5e6-539b-4001-a0ec-e2af1b0460f6)

Xdebug not listed and not available.

**Comment by mpociot** [comment]
Are you sure that Herd / the site you are visiting is using the correct PHP version?
Unfortunately I can't see that information from your screenshot.

**Comment by euperia** [comment]
Sorry - its definitely the correct version.  

![CleanShot 2023-10-12 at 10 25 40](https://github.com/beyondcode/herd-community/assets/2648745/8cac87f4-0a76-4a61-a978-5a4b702c111b)

**Comment by mpociot** [comment]
When you open the Herd settings, are all FPM services running/green?
Maybe a stale FPM process was still running and therefore the php.ini changes were not loaded.

If that's the case, you can manually force to stop FPM by running:

```
sudo killall php81-fpm
```

Afterwards, open Herd and select Stop all / Start all to restart all services.

**Comment by euperia** [comment]
Thanks for the pointer.  It turned out I had a runaway php-fpm process from 8.2 that wouldn't die.

```shell
> ps auxwww | grep fpm
root             35612   0.0  0.0 408644304   1472 s008  S+   10:34am   0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn --exclude-dir=.idea --exclude-dir=.tox fpm
username        35601   0.0  0.0 408994320    688   ??  S    10:34am   0:00.00 php-fpm: pool www
username        35600   0.0  0.0 408985104    784   ??  S    10:34am   0:00.00 php-fpm: pool www
username        35594   0.0  0.2 408985424  13056   ??  S    10:34am   0:00.07 php-fpm: master process (/opt/homebrew/etc/php/8.2/php-fpm.conf)
```

Quitting Herd, and then force killing that process (via Activity Monitor), and then starting Herd again solved it.

Thanks for your quick help with this @mpociot .
