### ISSUE TITLE
[Bug]: Dusk doesn't work

### ISSUE THREAD

**Issue by PhiloNL** [beyondcode/herd-community#21]
### Operating system version

13.3.1 (a) 

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.0.8

### PHP Version

PHP 8.2.6 (cli) (built: Jun 2 2023 23:59:34) (NTS)

### Bug description

Facebook\WebDriver\Exception\UnknownErrorException: unknown error: net::ERR_CONNECTION_REFUSED

### Steps to reproduce

```
gh repo clone livewire/livewire && cd livewire
composer require "laravel/framework:10.*" --no-interaction --no-update --dev
composer update --prefer-stable --no-interaction
vendor/bin/dusk-updater detect --no-interaction
vendor/bin/phpunit --testsuite Browser
```

**Comment by mpociot** [comment]
Thanks for reporting this, Philo.
Looks like it was a bug in the Testbench package. I submitted a PR, which will fix this 👍

**Comment by crynobone** [comment]
Released `orchestra/testbench-dusk` versions:

* `v6.31.1` (Laravel 8)
* `v7.26.1` (Laravel 9)
* `v8.6.7` (Laravel 10)
