### ISSUE TITLE
[Bug]: Herd 1.3.1, PHP CLI doesn't load the php.ini

### ISSUE THREAD

**Issue by bibiseb** [beyondcode/herd-community#210]
### Operating system version

macOS Sonoma 14.0

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.3.1

### PHP Version

PHP 8.1.24

### Bug description

phpinfo(); (in fpm) says mongodb is well loaded but the CLI says it is not. 
```
log_errors=On
error_log=/path/to/error.log
```
Is ignored by the CLI

=> The CLI should load the same configuration file as FPM.

**Comment by mpociot** [comment]
Are you sure that your CLI PHP version is the same as the one in the browser?
What do you get when you run `php81 -i | grep mongodb`

**Comment by bibiseb** [comment]
I get nothing

**Comment by mpociot** [comment]
Herd uses the `HERD_PHP_81_INI_SCAN_DIR` environment variable to locate and load the php.ini file.

In your `~/.zshrc` file, you should have this entry:

```
export HERD_PHP_81_INI_SCAN_DIR="/Users/micha/Library/Application Support/Herd/config/php/81/"
```

And the folder should contain a php.ini file. Could you verify this?

**Comment by bibiseb** [comment]
It is fixed we are using fish and we had to run this command:

`set -Ux HERD_PHP_81_INI_SCAN_DIR "/Users/USERNAME/Library/Application Support/Herd/config/php/81/"`
