### ISSUE TITLE
[Bug]: ini files for PHP 8.1 not loaded, only for 8.2

### ISSUE THREAD

**Issue by michapietsch-streamline** [beyondcode/herd-community#216]
### Operating system version

macOS Ventura 13.6

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.3.1 (Build 18)

### Bug description

For PHP 8.1 Herd doesn't seem to load the ini file, only for PHP 8.2

### Steps to reproduce

I used Valet and PHP via Homebrew until now. Got PHP 8.1 working fine, using it with Xdebug. I wanted to try Herd, selected PHP 8.1, wanted to test Xdebug integration right away to have my setup complete, but it didn't work. I tried PHP 8.2, and interestingly it worked. Then I checked the attached output, and noticed a problem with the loading of the ini files.

The ini files exist. But it seems they don't get scanned.

### Relevant log output

```shell
❯ php -v
PHP 8.2.11 (cli) (built: Sep 29 2023 00:10:16) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.11, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.11, Copyright (c), by Zend Technologies

❯ php --ini
Configuration File (php.ini) Path: /lib
Loaded Configuration File:         (none)
Scan for additional .ini files in: /Users/micha/Library/Application Support/Herd/config/php/82/
Additional .ini files parsed:      /Users/micha/Library/Application Support/Herd/config/php/82/php.ini

// Switching to PHP 8.2 in der Herd menu

❯ php -v
PHP 8.1.24 (cli) (built: Sep 29 2023 00:22:23) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.24, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.24, Copyright (c), by Zend Technologies

❯ php --ini
Configuration File (php.ini) Path: /lib
Loaded Configuration File:         (none)
Scan for additional .ini files in: (none)
Additional .ini files parsed:      (none)
```
```

**Comment by mpociot** [comment]
Herd uses the `HERD_PHP_81_INI_SCAN_DIR` environment variable to locate and load the php.ini file.

In your `~/.zshrc` file, you should have this entry:

```
export HERD_PHP_81_INI_SCAN_DIR="/Users/micha/Library/Application Support/Herd/config/php/81/"
```

And the folder should contain a php.ini file. Could you verify this?

**Comment by michapietsch-streamline** [comment]
> Herd uses the `HERD_PHP_81_INI_SCAN_DIR` environment variable to locate and load the php.ini file.
> 
> In your `~/.zshrc` file, you should have this entry:
> 
> ```
> export HERD_PHP_81_INI_SCAN_DIR="/Users/micha/Library/Application Support/Herd/config/php/81/"
> ```

Thanks, that's it!

It injected only the 8.2 variable. I manually copied it for 8.1. It works now.
