### ISSUE TITLE
[Bug]: Related to installing in preexisting valet, and installing after valet removal

### ISSUE THREAD

**Issue by znsstudio** [beyondcode/herd-community#219]
### Operating system version

macOs Ventura 13.5.2 (22G91)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.3,1

### Bug description

I have installed and reinstalled Herd multiple times, but can not see list of sites and can not find why it is happening

and it is not bug but question is it possible to secure alias host names?

Also trying to add site in sites tab, gives error but can not see installer output

### Steps to reproduce

I had valet in my computer and i removed everything related to valet and tried to install herd from scratch.

### Relevant log output

```shell
N/A
```

**Comment by mpociot** [comment]
Which shell do you use? Zsh/bash or something else?

**Comment by znsstudio** [comment]
> uter and i removed everything related to valet and tried to inst

thank you quick response @mpociot, eventually it got resolved after multiple tries :) I still do not know what was issue. 

only thing left can I secure aliases?

Because I did `ln -sfn template newsite` and want to secure **newsite** also but it does not show up in Sites tab, anything can be done?

**Comment by mpociot** [comment]
@znsstudio you can manually secure the alias by running `herd secure your-alias.test` in the terminal 👍
