### ISSUE TITLE
[Bug]: Cannot share Herd sites using Expose: asks for Expose Pro license

### ISSUE THREAD

**Issue by connecteev** [beyondcode/herd-community#22]
### Operating system version

MacOS Monterey 12.5.1 (21G83)

### System architecture

Intel (x86)

### Herd Version

1.0.8

### PHP Version

8.3

### Bug description

The Herd docs indicate that you can share sites using Expose for free. Is  that accurate or is sharing sites intended to be a paid Expose Pro feature only? 
https://herd.laravel.com/docs/1/advanced-usage/sharing-sites

This is what I see when I use an Expose free license:
![image](https://github.com/beyondcode/herd-community/assets/64816/e5b9c005-c8a7-4b17-86c7-946b2d292aaf)

> herd share
Authentication failed. This server region requires an Expose Pro license as part of our global network. Learn more at: https://expose.dev/get-pro
Connection to server closed.

**Comment by mpociot** [comment]
Seems like you once configured Expose to use a default-server that is not part of the free server region.
You can change it back to the free server by calling `expose default-server main` from the CLI.

**Comment by connecteev** [comment]
That fixed it, thanks.
