### ISSUE TITLE
[Feature Request]: Yii2 Compatibility

### ISSUE THREAD

**Issue by daihop** [beyondcode/herd-community#224]
### Feature Description

I'm a bit out of depth here, so apologies in advance if this is wrong place to put this.

I have a legacy Yii2 project that I need to maintain. I'd like to serve it via Herd. At present I get a 404 when trying to access it. I'm not sure, but I think the nginx config file may need to be updated to get it to work.

I appreciate this is a Laravel product but I think it would be great to run other frameworks via Herd if possible. Especially the Yii2 project I have to maintain! 

### Is this feature valuable for other users as well and why?

Other users in similar situations would benefit from compatibility with other frameworks.

**Comment by mpociot** [comment]
I just googled for a Yii2 Laravel Valet driver and found this: https://github.com/Yangbx/Laravel-Valet-Yii2-Driver

You can copy this file to `~/Library/Application Support/Herd/config/valet/Drivers` 👍
