### ISSUE TITLE
[Bug]: Ngnix won't launch, throws error about invalid package-lock.json

### ISSUE THREAD

**Issue by benjibee** [beyondcode/herd-community#225]
### Operating system version

macOS Sonoma 14.0

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.3.1 (Build: 18)

### Bug description

I noticed ngnix was no longer running from looking at the Herd menu and having a look at the logs I see:

`[emerg] 1117#12286: unexpected "{" in /Users/username/Library/Application Support/Herd/config/valet/Ngnix/package-lock.json:1`

This is the full contents of that file

```
{
  "name": "Nginx",
  "lockfileVersion": 3,
  "requires": true,
  "packages": {}
}
```

Something worth noting is that it's not possible to copy / paste from the log window, so I typed this out. Also this error is not visible in `/Users/username/Library/Application Support/Herd/Log/nginx-error.log` – I only see the last errors I had from a week ago.

### Steps to reproduce

There's nothing I can directly connect to this problem occurring. I updated Herd on the 16th of October but have been using it since then without issue. Last action I performed was unlocking my user and attempting to visit a local site for testing.

**Comment by mpociot** [comment]
I don't really know how/why this package-lock.json exists for you. Maybe it was copied over when migrating from Valet to Herd?
We don't create this file in any way.
You can just delete it and that should fix the error

**Comment by benjibee** [comment]
I've deleted it and the issue is now solved. I can't say how it ended up there, either.

If anyone else finds this issue and it fixes the problem please add a 👍 in case it's happening to others.
