### ISSUE TITLE
No Symlink to php after install [Bug]: 

### ISSUE THREAD

**Issue by stevepop** [beyondcode/herd-community#227]
### Operating system version

macOs Ventura 13.6

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.3.1

### Bug description

After installation, there was no php symlink and Herd CLI could not execute.  I made a clean uninstall and reinstall no lessd than 6 times and the result was the same.

![CleanShot 2023-10-26 at 12 40 15@2x](https://github.com/beyondcode/herd-community/assets/526063/42565ee5-f16f-4085-b3f2-ebdfdd8737dc)

I confirmed this by running `ls -lrt /Users/steve/Library/Application\ Support/Herd/bin` 
![CleanShot 2023-10-26 at 12 44 47@2x](https://github.com/beyondcode/herd-community/assets/526063/e18277df-eda6-4d32-8bdf-bdbd617738a9)

I was only able to make it work by manually creating a symlink to one of the PHP versions I installed. 

### Steps to reproduce

- Install Herd
- Go to console and run `herd --version` or `php -v`
 - Check the bin directory of Herd for the php symlink.

**Comment by mpociot** [comment]
Does it make a difference when you manually run `herd use 8.1` in your terminal? This should force to re-create the symlink.
Otherwise, please create the symlink manually. I'm not sure why/what caused the symlink creation to fail for you.

**Comment by leewillis77** [comment]
`herd` wouldn't work here since it depends on the presence of `/Users/steve/Library/Application\ Support/Herd/bin/php`

**Comment by geekysaurabh001** [comment]
This still is an issue in 2025. Mac. On php upgrade, symlink is lost.
