### ISSUE TITLE
[Bug]: 404 Site not found: herd.sock not found

### ISSUE THREAD

**Issue by ogamacheDev** [beyondcode/herd-community#228]
### Operating system version

macOS Ventura 13.6

### System architecture

Intel (x86)

### Herd Version

1.3.1

### Bug description

After a fresh install of Herd, I am unable to access the newly installed projects, I get a 404 site not found. After some investigation, I found in the nginx log file this:
```shell
2023/10/27 08:32:23 [crit] 16363#134482: *1 connect() to unix:/Users/ogamache/Library/Application Support/Herd/herd.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/Users/ogamache/Library/Application Support/Herd/herd.sock:", host: "radical-test.test"
```

### Steps to reproduce

1. Install Herd
2. Park a folder
3. Install a new project
4. Check if it works
5. Check the logs

### Relevant log output

```shell
2023/10/27 08:32:23 [crit] 16363#134482: *1 connect() to unix:/Users/ogamache/Library/Application Support/Herd/herd.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/Users/ogamache/Library/Application Support/Herd/herd.sock:", host: "radical-test.test"
```

**Comment by mpociot** [comment]
What's the status of your Herd services?

**Comment by ogamacheDev** [comment]
Everything seems to be up and running: 
<img width="254" alt="image" src="https://github.com/beyondcode/herd-community/assets/65354990/ac700bc6-8f81-48d5-8d4a-7f4de393fe88">

**Comment by mpociot** [comment]
Could you please try and install another PHP version (like 8.1) and switch between those versions. Does that fix the problem for you?

Could you also show me the contents of your ~/Library/Application Support/Herd directory?

**Comment by mpociot** [comment]
Looks like it's there 😅 
It's a symlink that points to the correct socket site based on your PHP version.

Which error do you get exactly? The 404 from Herd?
If so, could you share your sites listing/UI or the list of parked paths?

**Comment by ogamacheDev** [comment]
The symlink is there but It can't find it (sorry for the french screenshot)
![image](https://github.com/beyondcode/herd-community/assets/65354990/78996ec3-4752-4c8f-bda2-d9323a45247b)

I get a 404 site not found error, I parked my folder correctly and the site is found in the site list:
![image](https://github.com/beyondcode/herd-community/assets/65354990/8ece9dd3-e47e-4259-9e85-5f4a3b171780)

![Capture d’écran, le 2023-10-27 à 09 07 17](https://github.com/beyondcode/herd-community/assets/65354990/dcdd6348-432d-4e17-90e0-15c14735b4e1)

**Comment by mpociot** [comment]
If you don't mind, do you have a minute to debug this with me via screensharing (like Tuple/Google Meet)?

**Comment by ogamacheDev** [comment]
Of course.

**Comment by mpociot** [comment]
https://meet.google.com/uwf-odwj-poj

Here you go :)

**Comment by ogamacheDev** [comment]
### For some people that might get this issue:
The issue was that Herd didn't recognize my project structure, do no driver was loaded. In that case, you can create you own driver inside the project in a file called `LocalValetDriver.php`:

```
<?php

use Valet\Drivers\BasicValetDriver;

class LocalValetDriver extends BasicValetDriver
{
    /**
     * Determine if the driver serves the request.
     */
    public function serves(string $sitePath, string $siteName, string $uri): bool
    {
        return true;
    }

    /**
     * !!!! ENTER THE WEB ROOT IN THE $staticFilePath VARIABLE
     * Determine if the incoming request is for a static file.
     */
    public function isStaticFile(string $sitePath, string $siteName, string $uri)
    {
        $staticFilePath = $sitePath.'/public'.$uri;

        if ($this->isActualFile($staticFilePath)) {
            return $staticFilePath;
        }

        return false;
    }

    /**
     * !!!! ENTER THE WEB ROOT IN THE $sitePath VARIABLE
     * Get the fully resolved path to the application's front controller.
     */
    public function frontControllerPath(string $sitePath, string $siteName, string $uri): ?string
    {
        return parent::frontControllerPath(
            $sitePath.'/public',
            $siteName,
            $this->forceTrailingSlash($uri)
        );
    }

    /**
     * Redirect to uri with trailing slash.
     */
    private function forceTrailingSlash($uri)
    {
        if (substr($uri, -1 * strlen('/wp/wp-admin')) == '/wp/wp-admin') {
            header('Location: '.$uri.'/');
            exit;
        }

        return $uri;
    }
}
```

Hope it helps. Cheers!
