### ISSUE TITLE
[Feature Request]: Allow one-click to open / launch sites from "Sites" tab

### ISSUE THREAD

**Issue by connecteev** [beyondcode/herd-community#23]
### Feature Description

Herd is great. What would make it even better (and me, lazier) is allowing one-click to open / launch sites from the "Sites" tab, instead of having to type URLs manually. This can become a time-saver for someone like me that has a number of laravel projects at a time.

![image](https://github.com/beyondcode/herd-community/assets/64816/6e038b4a-595e-480b-8f3b-023c7b037a8c)

### Is this feature valuable for other users as well and why?

Yes

**Comment by mpociot** [comment]
This feature is now available in Herd 1.1.0 🎉

**Comment by connecteev** [comment]
Thank you @mpociot! This works great and I'm loving Herd so far.
