### ISSUE TITLE
[Bug]: Sites / Create new application can't locate php (wrong version)

### ISSUE THREAD

**Issue by django23** [beyondcode/herd-community#233]
### Operating system version

macOS 13.5.1 (22G90)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.3.1 (Build 18)

### Bug description

When creating a site through the wizard the following error occurs:
![CleanShot 2023-10-31 at 13 27 52](https://github.com/beyondcode/herd-community/assets/827397/58b9183d-aaab-4589-af2d-03b97ad4dfc4)

I have the following PHP version installed through the Herd:
![CleanShot 2023-10-31 at 13 29 18](https://github.com/beyondcode/herd-community/assets/827397/900a2339-3618-4f1b-881d-fd8437c2e9d7)

And php is also installed through brew: 
![image](https://github.com/beyondcode/herd-community/assets/827397/b00c320e-8efc-4eee-91c6-122d6e128026)

**Comment by django23** [comment]
A way to fix the issue is by installing PHP8.2:
![CleanShot 2023-10-31 at 13 34 44](https://github.com/beyondcode/herd-community/assets/827397/5e85a7ba-6a1f-4697-9123-4e417064af20)

**Comment by mpociot** [comment]
We'll fix this in an upcoming version, in the meantime you need PHP 8.2 in order to use the site creation wizard.
