### ISSUE TITLE
[Feature Request]: Apache Support

### ISSUE THREAD

**Issue by xcrap** [beyondcode/herd-community#238]
### Feature Description

Will there ever be a version with Apache Support?

### Is this feature valuable for other users as well and why?

Not every server have migrated or fully support NGINX, Apache is still very much on demand. Some works with both using Apache for the main server and NGINX for static delivery.

**Comment by esemlabel** [comment]
Highly demand on this feature, I think.

**Comment by balconsoftakhmedov** [comment]
apache support for Herd will be very good feature. do you have any news about ?

**Comment by mirko77** [comment]
I have the same question

**Comment by xcrap** [comment]
I was hoping for a bit more engagement regarding my request for Apache support in Herb. A brief explanation outlining why this feature might not be interesting or viable would have been appreciated. Instead, the issue was simply given a thumbs down and closed. This lack of communication feels somewhat dismissive.

**Comment by jase-languasco** [comment]
As someone that just paid for Herd Pro and looking to see how I could use apache for one of the sites I manage, it isn't great to see no response from the maintainers here... @mpociot

**Comment by blackchineykh** [comment]
Interested in this as well

**Comment by Metronoid** [comment]
I'm continuing the interest in this feature

**Comment by mikescott** [comment]
I would pay for it right now if it had Apache
