### ISSUE TITLE
[Bug]: Failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by joshuablum** [beyondcode/herd-community#239]
### Operating system version

macOS Sonoma 14.1 (23B74)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.3.1

### PHP Version

PHP 8.2

### Bug description

Exactly what's described in https://github.com/spatie/global-ray/issues/44
From my testing I think it's related to Herd and included PHP binaries (8.2 specifically) since switching to a different PHP version with Herd or using Homebrew PHP/Valet works all fine.

### Steps to reproduce

Use Herd's PHP 8.2 binary, use something like the `spatie/global-ray` package.

### Relevant log output

```shell
Warning: file_get_contents(/Users/mike/.config/valet/config.json): Failed to open stream: No such file or directory in /Users/mike/.composer/vendor/spatie/global-ray/src/scripts/global-ray-loader.php on line 45

Warning: Attempt to read property "paths" on null in /Users/mike/.composer/vendor/spatie/global-ray/src/scripts/global-ray-loader.php on line 47

Warning: foreach() argument must be of type array|object, null given in /Users/mike/.composer/vendor/spatie/global-ray/src/scripts/global-ray-loader.php on line 47

Warning: file_get_contents(/Users/mike/.config/valet/config.json): Failed to open stream: No such file or directory in /Users/mike/.composer/vendor/spatie/global-ray/src/scripts/global-ray-loader.php on line 45

Warning: Attempt to read property "paths" on null in /Users/mike/.composer/vendor/spatie/global-ray/src/scripts/global-ray-loader.php on line 47

Warning: foreach() argument must be of type array|object, null given in /Users/mike/.composer/vendor/spatie/global-ray/src/scripts/global-ray-loader.php on line 47
```

**Comment by babul** [comment]
I'm seeing this too. All specs the same except I'm on an Intel Mac.

**Comment by mpociot** [comment]
The error is unrelated to Herd.
The `global-ray-loader.php` file checks for the existence of a config.json file that doesn't exist 🤷 

Global Ray needs to be modified in order to detect if the user is running Valet or Herd.
