### ISSUE TITLE
Cant find the server / site cannot be reached

### ISSUE THREAD

**Issue by flatcapco** [beyondcode/herd-community#24]
### Operating system version

13.4.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.0.6

### Bug description

Herd is showing as installed correctly and I have checked all the equivalent valet commands  with herd list, herd secured etc.. however none of my sites in the parked directory will load with a ssl or without. Even trying a very basic index.html test.

I'm not sure where to look for useful troubleshooting info as it all looks correct except it wont load a site.

**Comment by AbdullahGhanem** [comment]
i am still facing the same issue

**Comment by flatcapco** [comment]
@AbdullahGhanem I fixed it by uninstalling herd via their docs and reinstalling

**Comment by itrsudlgs** [comment]
still waiting for how to fix it
