### ISSUE TITLE
[Bug]: Error When Adding New Site with Space in Project Name

### ISSUE THREAD

**Issue by imakeinternet** [beyondcode/herd-community#240]
### Operating system version

MacOS 12.5.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.3.1 (Build 18)

### PHP Version

PHP 8.2.8

### Bug description

An error occurs when following the standard process to add a new site with a project name that includes a space (e.g., "My Project").

```
There was an error creating your application...

Too many arguments to "new" command, expected arguments "name".
```

<img width="594" alt="image" src="https://github.com/beyondcode/herd-community/assets/4062140/e2cd8ddd-6a60-4fa3-900d-8926735d2867">

**Expected Result:**
The new site should be added successfully without errors, even if the project name contains spaces.

**Actual Result:**
The system produces an error upon completing the steps, preventing the site from being added.

**Hypothesis:**
The error may be due to the project name with a space not being properly escaped when passed as a parameter to the "new" command. This is based on the observed behavior and the nature of the error message received.

### Steps to reproduce

1. Navigate to Herd > Settings > Sites.
2. Initiate the process to add a new site.
3. Enter a project name that contains a space, such as "My Project".
4. Complete the necessary steps to finalize adding the site.

### Relevant log output

```shell
There was an error creating your application...

Too many arguments to "new" command, expected arguments "name".
```

**Comment by mpociot** [comment]
We fixed this locally and it'll be available in the next update. When creating a project named `My Project`, this will result in a folder called `my-project`.
