### ISSUE TITLE
[Feature Request]: Herd website - smaller text for small viewports

### ISSUE THREAD

**Issue by devnll** [beyondcode/herd-community#25]
### Feature Description

Hopefully it's ok to submit this here..

When accessing https://herd.laravel.com/ on my phone (Samsung S22), some of the text is cut off:

![Screenshot_20230723_152145_Chrome Beta](https://github.com/beyondcode/herd-community/assets/47151094/fa448ed9-bc25-481a-bc94-412f3fdddfc6)

Things seem fine for viewports over ~420px wide.

**Comment by mpociot** [comment]
Fixed 👍

**Comment by devnll** [comment]
Awesome, thanks @mpociot!

... and of course thanks for all your work on Herd, hope it helps spread PHP/Laravel to even more people 🌝
