### ISSUE TITLE
[Feature Request]: Switch all sites to a singular version of PHP

### ISSUE THREAD

**Issue by genericmilk** [beyondcode/herd-community#252]
### Feature Description

I just updated to PHP 8.3 and noted that because each site's controls are version specific, it took a long time to manually switch each entry from 8.2 to 8.3 - In future a "master" dropdown that changes this for every site would be fab (Maybe in PHP settings tab?)

### Is this feature valuable for other users as well and why?

This would be a huge timesaver. I myself have over 30 sites and it was slow switching each by hand :-)

**Comment by bashgeek** [comment]
Just use `herd use 8.3` in your terminal to set the default version. But I agree that this should be a setting in the GUI, too.

**Comment by mpociot** [comment]
If you haven't isolated your sites, you can just switch the generic PHP version in the menubar, which will automatically switch all non-isolated sites :)

![image](https://github.com/beyondcode/herd-community/assets/804684/05c8258a-a37d-44bc-913a-c8972ce1a6e6)
