### ISSUE TITLE
[Bug]: upstream prematurely closed connection error after updating PHP versions

### ISSUE THREAD

**Issue by WendellAdriel** [beyondcode/herd-community#254]
### Operating system version

macOS Sonoma 14.1.1

### System architecture

Intel (x86)

### Herd Version

1.3.1 (Build 18)

### PHP Version

PHP 8.2.13 and PHP 8.3.0

### Bug description

After updating my PHP versions to PHP 8.2.13 and PHP 8.3.0 I started to get this error:

```
upstream prematurely closed connection while reading response header from upstream
```

The weird thing is that this is happening only with endpoints that access a PgSQL DB. The application uses two DBs, a MySQL one and a PgSQL one. All endpoints that are accessing the MySQL one only are working, but all endpoints that access the PgSQL DB are resulting in this:

![image](https://github.com/beyondcode/herd-community/assets/11641518/94f9e5bb-dde4-4803-815c-c7ab2e0418fd)

And when I check the logs the error above and on the Relevant log output are being added to the log file.

I already did some research and tried some solutions that I saw happening with Valet. Tried to uninstall and install Herd and the issue wasn't fixed.

This started to happen today after I updated my PHP versions on Herd.

### Steps to reproduce

I can't share the repository since it's private, but a simple Laravel app that accesses a PgSQL DB with a simple query should be enough to check this behaviour.

### Relevant log output

```shell
2023/11/24 16:21:56 [error] 8783#11646759: *1 upstream prematurely closed connection while reading response header from upstream, client: 127.0.0.1, server: , request: "GET /v1/brands/4572/competitor-suite/explore/whitespace-opportunities?timeframe=2d HTTP/1.1", upstream: "fastcgi://unix:/Users/wendell_adriel/Library/Application Support/Herd/herd.sock:", host: "trackstreet.test"
```

**Comment by mpociot** [comment]
Hm is this related to https://github.com/laravel/valet/issues/1433 ?

**Comment by WendellAdriel** [comment]
I tried some solutions on this, but it didn't work.

I tried adding some fastcgi params like: https://github.com/laravel/valet/issues/1433#issuecomment-1652189244

I also tried adding this: https://github.com/laravel/valet/issues/1433#issuecomment-1763383493 to the `~/Library/Application\ Support/Herd/config/fpm/8.2-fpm.conf` but it didn't work as well.

Then I removed Herd completely from my computer and installed it again, the issue was still happening. Tried the solutions above again and the issue is still happening. IDK what to try anymore.

**Comment by crazywhalecc** [comment]
It seems that this problem cannot be reproduced in the existing running environment. I used the following steps:

1. Install Herd and download PHP 8.3.0
2. Connect to the database and install it using Homebrew: `brew install postgresql`
3. Create an account and connect
4. Use Herd to quickly create a Laravel project and insert `var_dump(\Illuminate\Support\Facades\DB::select('SELECT 1,2,3,4,5'));` into the homepage
5. Successfully display query results

I first tried the above steps on Ventura and then on a clean Sonoma virtual machine, but the problem did not occur. Did I miss something?

**Comment by redpark2** [comment]
Exact same problem here. 

When a Postgres connection is made, the Nginx upstream error triggers. 
Also happens with PHP 8.3

All was working perfectly before upgrading to PHP 8.2.13. 
Have uninstalled and reinstalled Herd twice... 

Herd 1.3.1, PHP 8.2.13 or 8.3
macOS Sonoma 14.1.1
M1 architecture

**Comment by Ewoutvans** [comment]
I was also having the same issue with connection to PostgreSQL databases

Herd: Version 1.3.1 (Build 18)
PHP 8.2.13
macOS Sonoma 14.1.1

I've done some testing and found if postgres has SSL mode on, the 502 Bad Gateway happens.
When disabling the SSL mode everything works as expected.
As @crazywhalecc pointed out with `brew install postgresql` it seems to work for me, and that's because ssl = off by default in homebrew. I'm however using a postgres server installed by forge where ssl is on.

**Comment by mpociot** [comment]
Thanks for the SSL hint!
I just built new 8.2.13 versions that no longer have this issue. 
It seems to be related to a specific OpenSSL version that gets used as a dependency. 
The 8.3.0 version will be built as well.

**Comment by askdkc** [comment]
@mpociot 

Can you share how you build PHP for Herd by any chance? Configure options?

**Comment by thomas-shirley** [comment]
Hi there — it looks like this bug is no isolated to Herd. I'm running Homebrew php 8.3 and Postgres 14 standalone — with the same error.

**Comment by mpociot** [comment]
@thomas-shirley Yeah, it's related to the specific openssl version that was used in combination with postgresql

**Comment by thomas-shirley** [comment]
Looks like this bug is being tracked in Homebrew core: https://github.com/Homebrew/homebrew-core/issues/155651

**Comment by crazywhalecc** [comment]
I tried debugging, and the result should be a pointer error caused by pdo_pgsql and newer openssl. But I'm not good at debugging with lldb, there's only so much I can do.

<details>

<summary>Console Log</summary>

```
$ lldb buildroot/bin/php test.php
(lldb) target create "php"
Current executable set to 'php' (arm64).
(lldb) settings set -- target.run-args  "test.php"
(lldb) run
Process 23230 launched: 'php' (arm64)
TEST
php(23230,0x1e27de080) malloc: *** error for object 0xa2: pointer being freed was not allocated
php(23230,0x1e27de080) malloc: *** set a breakpoint in malloc_error_break to debug
Process 23230 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x0000000187724764 libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`:
->  0x187724764 <+8>:  b.lo   0x187724784               ; <+40>
    0x187724768 <+12>: pacibsp 
    0x18772476c <+16>: stp    x29, x30, [sp, #-0x10]!
    0x187724770 <+20>: mov    x29, sp
Target 0: (php) stopped.
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
  * frame #0: 0x0000000187724764 libsystem_kernel.dylib`__pthread_kill + 8
    frame #1: 0x000000018775bc28 libsystem_pthread.dylib`pthread_kill + 288
    frame #2: 0x0000000187669ae8 libsystem_c.dylib`abort + 180
    frame #3: 0x000000018758ae28 libsystem_malloc.dylib`malloc_vreport + 908
    frame #4: 0x000000018758e6e8 libsystem_malloc.dylib`malloc_report + 64
    frame #5: 0x000000018759af20 libsystem_malloc.dylib`find_zone_and_free + 308
    frame #6: 0x00000001003d9824 php`freePGconn + 300
    frame #7: 0x000000010010fa60 php`pgsql_handle_closer(dbh=0x0000000102083000) at pgsql_driver.c:233:4 [opt]
    frame #8: 0x000000010010f914 php`pdo_pgsql_handle_factory(dbh=<unavailable>, driver_options=<unavailable>) at pgsql_driver.c:1330:3 [opt]
    frame #9: 0x0000000100103440 php`zim_PDO___construct(execute_data=<unavailable>, return_value=<unavailable>) at pdo_dbh.c:389:6 [opt]
    frame #10: 0x000000010029b034 php`ZEND_DO_FCALL_SPEC_RETVAL_UNUSED_HANDLER(execute_data=0x0000000102017020) at zend_vm_execute.h:0 [opt]
    frame #11: 0x0000000100278eb8 php`execute_ex(ex=<unavailable>) at zend_vm_execute.h:56998:7 [opt]
    frame #12: 0x00000001002790e4 php`zend_execute(op_array=0x000000010207c200, return_value=0x0000000000000000) at zend_vm_execute.h:61595:2 [opt]
    frame #13: 0x0000000100257b90 php`zend_execute_scripts(type=8, retval=0x0000000000000000, file_count=<unavailable>) at zend.c:1881:4 [opt]
    frame #14: 0x00000001001f7db4 php`php_execute_script(primary_file=0x000000016fdfe8e0) at main.c:2516:13 [opt]
    frame #15: 0x0000000100341658 php`do_cli(argc=<unavailable>, argv=<unavailable>) at php_cli.c:966:5 [opt]
    frame #16: 0x000000010033fe84 php`main(argc=<unavailable>, argv=0x0000600000203260) at php_cli.c:1340:18 [opt]
    frame #17: 0x0000000187403f28 dyld`start + 2236
(lldb) 
```

</details>

<details>

<summary>test.php</summary>

```
<?php

$str = 'pgsql:host=localhost;port=5432;dbname=postgres;user=user;password=password';

echo "TEST\n";

$a = new PDO($str);
echo "TEST\n";

var_dump($a->query('SELECT 1,2,3,3,5'));
```

</details>

Here's an not-stripped php-cli on macOS arm64: 
[php.zip](https://github.com/beyondcode/herd-community/files/13691255/php.zip)
