### ISSUE TITLE
[Feature Request]: Match post_max_size to upload_max_filesize

### ISSUE THREAD

**Issue by Ratko-Solaja** [beyondcode/herd-community#257]
### Feature Description

I have used Max File Upload Size feature to set my desired upload size, however, WordPress in Site Health, tells me that the `post_max_size` is less than `upload_max_filesize`.

Maybe, setting Max File Upload Size (`upload_max_filesize`) can also overide the `post_max_size` to match the value.

**Comment by jannisborgers** [comment]
I’d love that. My CMS complains about the maximum upload size being 8M. The culprit is `post_max_size` though, not `upload_max_filesize`, which I set to 256 MB already.

**Comment by tyroga** [comment]
Yes, agree, this needs to be done as it seems changing it in the php.ini doesn't seem to fix it for me. 😓

**Comment by jannisborgers** [comment]
Changing `post_max_size` in all .ini files for Herd's PHP (clicking Show .ini file in menu bar), then closing and opening Herd did the trick for me.
