### ISSUE TITLE
[Bug]: Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.0". You are running 7.2.34

### ISSUE THREAD

**Issue by brandymedia** [beyondcode/herd-community#262]
### Operating system version

macOS Ventura 13

### System architecture

Intel (x86)

### Herd Version

1.3.1

### PHP Version

8.2.11

### Bug description

After creating a new site using the Herd setup wizard, the wrong PHP is being used.

In the 'sites' list the new site states it is set to use PHP 8.2 but when visiting in the browser the following error is thrown:

`Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.0". You are running 7.2.34`

I have tried selecting a different version from the dropdown and back again but the only way to get past this is to use a Laravel Valet command directly on the directory `valet isolate php@8.2`.

### Steps to reproduce

1. Create a new site using the setup wizard
2. Visit site in browser

### Relevant log output

```shell
Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.0". You are running 7.2.34. in .../vendor/composer/platform_check.php on line 24
```

**Comment by mpociot** [comment]
I'm a bit confused as Herd does not ship PHP 7.2, so this version must come from an existing brew installation.
As you also mention Valet, this probably messes up the Herd configuration, as those services can not run at the same time.

So I assume that you are running PHP via Valet, but created and isolated the site with Herd (or vice versa) which doesn't work 😅

**Comment by brandymedia** [comment]
Apologies, it sounds like maybe I have something conflicting from my original Valet setup. I was running Valet and then installed Herd and must have missed the step to remove my old setup.
