### ISSUE TITLE
[Bug]: autocompletion seems not to work with ZSH

### ISSUE THREAD

**Issue by encodiaweb** [beyondcode/herd-community#264]
### Operating system version

macOS Ventura 13.6.1

### System architecture

Intel (x86)

### Herd Version

1.3.1 (Build 18)     (herd --version  # output: 1.0.0)

### PHP Version

PHP 8.2.13 (cli) (built: Nov 26 2023 00:00:08) (NTS)

### Bug description

Autocompletion seems not to work, at least with ZSH.
I tried both static and dynamic installation, as described here: `herd completion --help`

After configuring Herd autocompletion and restarting the shell, I expect this behavior (for example):
   `herd r<TAB>` should be expanded to `herd restart`.

Instead, I got this:
   `herd README.md`  (assuming in the current directory there's a README.md file).

Another issue concerns unescaped paths reported in the `herd completion --help` command.
It prints 

   `eval "$(/Users/myusername/Library/Application Support/Herd/bin/herd.phar completion zsh)`

but I think it should print

   `eval "$(/Users/myusername/Library/Application\ Support/Herd/bin/herd.phar completion zsh)`.

Anyway, I tried autocompletion using the correct path.

Thanks!

### Steps to reproduce

Follow these instructions: `herd completion --help`

**Comment by mpociot** [comment]
The problem seems to be that Symfony console automatically generates these completion scripts and uses the PHP internal filename for this script (which is `herd.phar` instead of just `herd`).

You can manually fix this, by running `herd completion zsh` and then copy/paste the script into your `.zshrc` file, removing all occurrences of `herd.phar`

**Comment by encodiaweb** [comment]
> removing all occurrences of herd.phar

I'm not sure about what you meant.
I dumped the script, did copy/paste in my `.zshrc`, removed `herd.phar` (I also tried to remove only `.phar`), reloaded the shell, but nothing changed.

Thanks for your time @mpociot

**Comment by vicmattos** [comment]
For anyone looking this up.

Solved by adding `compdef` with correct second argument to `herd` right bellow `eval` command:
```
eval "$($HOME/Library/Application Support/Herd/bin/herd.phar completion zsh)"
compdef _sf_herd.phar herd
```

**Comment by davideprevosto** [comment]
@vicmattos thank you!
