### ISSUE TITLE
[Bug]: php.ini not loaded by php binary available via cli

### ISSUE THREAD

**Issue by ammar-madni** [beyondcode/herd-community#267]
### Operating system version

macOS Sonoma 14.1.2

### System architecture

Intel (x86)

### Herd Version

1.3.1 (Build: 18)

### Bug description

I have followed the instructions in the docs and configured the php.ini file for the version of php I need (7.4) to include the additional extension I require (mongodb) like so:

My php.ini file located at: `/Users/ammar/Library/Application Support/Herd/config/php/74/php.ini` has the following contents:
```
curl.cainfo=/Users/ammar/Library/Application Support/Herd/config/php/cacert.pem
openssl.cafile=/Users/ammar/Library/Application Support/Herd/config/php/cacert.pem
pcre.jit=0

extension=/usr/local/lib/php/pecl/20190902/mongodb.so

memory_limit=128M
upload_max_filesize=2M
```

Running my site I can see the correct php.ini file has been loaded along with the mongodb extension.
<img width="676" alt="Screenshot 2023-12-02 at 23 28 11" src="https://github.com/beyondcode/herd-community/assets/61558359/8db6debf-dfb7-4eee-b57d-428b4d47324a">
<img width="885" alt="Screenshot 2023-12-02 at 23 29 26" src="https://github.com/beyondcode/herd-community/assets/61558359/8fd2a56a-7ec5-47ce-abc7-26990fa9621e">

However, when I run php via the cli my php.ini file is not loaded.
```
> which php
/Users/ammar/Library/Application Support/Herd/bin//php
> php -ini | grep "Loaded Configuration File"
Loaded Configuration File => (none)
```

**Comment by rastitkac** [comment]
I've come across this problem too. Specifically, no matter what memory_limit value is set in the settings / php.ini files, the cli php has 128M.

![CleanShot 2023-12-05 at 14 01 33](https://github.com/beyondcode/herd-community/assets/23151096/0da1cb1e-01bc-4431-b767-2337087c99a4)

**Comment by peterson-umoke** [comment]
same issue here

**Comment by mpociot** [comment]
When PHP via the CLI is not using the correct ini file, please make sure that you have the necessary environment variables setup. 
Usually, Herd injects them in your `~/.zshrc` file during onboarding.

This is what it looks like, please adjust the username and PHP version

```
# Herd injected PHP 8.2 configuration.
export HERD_PHP_81_INI_SCAN_DIR="/Users/YOUR-USERNAME-HERE/Library/Application Support/Herd/config/php/82/"

# Herd injected PHP 8.3 configuration.
export HERD_PHP_83_INI_SCAN_DIR="/Users/YOUR-USERNAME-HERE/Library/Application Support/Herd/config/php/83/"
```

**Comment by ElRochito** [comment]
Hi @mpociot ,

Thanks for your answer, I setup environment variables on my .zshrc like this : 

```
# Herd injected PHP configuration.
export HERD_PHP_81_INI_SCAN_DIR="/Users/xxxx/Library/Application Support/Herd/config/php/81/"
export HERD_PHP_82_INI_SCAN_DIR="/Users/xxxx/Library/Application Support/Herd/config/php/82"
export HERD_PHP_83_INI_SCAN_DIR="/Users/xxxx/Library/Application Support/Herd/config/php/83/"

# Herd injected PHP binary.
export PATH="/Users/xxxx/Library/Application Support/Herd/bin":$PATH
```

but I already have the same problem, values are not take into account

**Comment by mpociot** [comment]
@ElRochito What do you get when you run this in your terminal:

```
echo $HERD_PHP_82_INI_SCAN_DIR

php --ini
```

**Comment by ElRochito** [comment]
`echo $HERD_PHP_82_INI_SCAN_DIR`prompts `/Users/xxx/Library/Application Support/Herd/config/php/82/`

`php.ini` prompts 
```
Configuration File (php.ini) Path: /lib
Loaded Configuration File:         (none)
Scan for additional .ini files in: /Users/xxx/Library/Application Support/Herd/config/php/82/
Additional .ini files parsed:      /Users/xxx/Library/Application Support/Herd/config/php/82/php.ini,
/Users/xxx/Library/Application Support/Herd/config/php/82/xdebug.ini
```

It seems `max_execution_time` can't be overwritten, if I update memory_limit for example, it's take into account

**Comment by ammar-madni** [comment]
@mpociot Herd has injected the env vars into my zshrc:

```
# Herd injected PHP binary.
export PATH="/Users/ammar/Library/Application Support/Herd/bin/":$PATH

# Herd injected PHP 8.2 configuration.
export HERD_PHP_82_INI_SCAN_DIR="/Users/ammar/Library/Application Support/Herd/config/php/82/"


# Herd injected PHP 7.4 configuration.
export HERD_PHP_74_INI_SCAN_DIR="/Users/ammar/Library/Application Support/Herd/config/php/74/"


# Herd injected PHP 8.0 configuration.
export HERD_PHP_80_INI_SCAN_DIR="/Users/ammar/Library/Application Support/Herd/config/php/80/"


# Herd injected PHP 8.1 configuration.
export HERD_PHP_81_INI_SCAN_DIR="/Users/ammar/Library/Application Support/Herd/config/php/81/"


# Herd injected PHP 8.3 configuration.
export HERD_PHP_83_INI_SCAN_DIR="/Users/ammar/Library/Application Support/Herd/config/php/83/"
```

When I run `echo $HERD_PHP_74_INI_SCAN_DIR` I get `/Users/ammar/Library/Application Support/Herd/config/php/74/` as expected.

But when I run `php --ini` I get:
```
Configuration File (php.ini) Path: /lib
Loaded Configuration File:         (none)
Scan for additional .ini files in: (none)
Additional .ini files parsed:      (none)
```

**Comment by peterson-umoke** [comment]
So this issue is very clear with the last feedback... every time you switched to a new default version, herd injects the values of the new "php.ini" but leaves the old values present... A cleanup of the previous values seems like the only solution cause immediately cleared the unused ini files, everything works

**Comment by mpociot** [comment]
@peterson-umoke your comment finally made me realize what's going on!
This issue was only related to PHP 7.4 and 8.0, as those specific versions were not yet properly built to make use of the HERD_PHP_ environment variables.

I triggered new builds for those versions on the CI pipeline, so they should be available soon, which fixes this issue! :)

**Comment by ammar-madni** [comment]
> @peterson-umoke your comment finally made me realize what's going on! This issue was only related to PHP 7.4 and 8.0, as those specific versions were not yet properly built to make use of the HERD_PHP_ environment variables.
> 
> I triggered new builds for those versions on the CI pipeline, so they should be available soon, which fixes this issue! :)

@mpociot Thank you!

**Comment by peterson-umoke** [comment]
@mpociot, happy to be help. guess this issue is now truly closed.

**Comment by tembra** [comment]
> When PHP via the CLI is not using the correct ini file, please make sure that you have the necessary environment variables setup. Usually, Herd injects them in your `~/.zshrc` file during onboarding.
> 
> This is what it looks like, please adjust the username and PHP version
> 
> ```
> # Herd injected PHP 8.2 configuration.
> export HERD_PHP_81_INI_SCAN_DIR="/Users/YOUR-USERNAME-HERE/Library/Application Support/Herd/config/php/82/"
> 
> # Herd injected PHP 8.3 configuration.
> export HERD_PHP_83_INI_SCAN_DIR="/Users/YOUR-USERNAME-HERE/Library/Application Support/Herd/config/php/83/"
> ```

I need to add it manually on my fish config file (`~/.config/fish/config.fish`).

```
set -Ux HERD_PHP_82_INI_SCAN_DIR "$HOME/Library/Application Support/Herd/config/php/82/"
```

Herd does not include it during onboarding.

**Comment by Ken-vdE** [comment]
My issue was (I think) that the
```
# Herd injected PHP binary.
export PATH="/Users/ammar/Library/Application Support/Herd/bin/":$PATH
```
was added BEFORE 
```
# Herd injected PHP binary.
export PATH="/Users/ammar/Library/Application Support/Herd/bin/":$PATH
```

switching those two fixed the issue.
`php --ini` now correctly reads the ini file.

**Comment by torbentschechne** [comment]
I run into a similar issue, but it's not cli related. I've set the memory limit to `1024` in the herd settings. The php.ini looks like this:

```
curl.cainfo=/Users/torben/Library/Application Support/Herd/config/php/cacert.pem
openssl.cafile=/Users/torben/Library/Application Support/Herd/config/php/cacert.pem
pcre.jit=0

upload_max_filesize=2M
memory_limit=1024M
```

My phpinfo states:
<img width="684" alt="CleanShot 2024-02-09 at 12 46 58@2x" src="https://github.com/beyondcode/herd-community/assets/4470136/260a4a89-27e5-4bcd-9047-94a66991fde1">

But the `memory_limit` is 128M, so it misses the information from php.ini
<img width="719" alt="CleanShot 2024-02-09 at 12 47 12@2x" src="https://github.com/beyondcode/herd-community/assets/4470136/f273b095-40b0-4f0b-9999-7ba62d312a35">

Does anybody know why php does not take the value into account despite it reads the correct php.ini file?

**Comment by torbentschechne** [comment]
> Can you check your FPM configuration file? Up to Herd 1.4.0 it could overwrite the ini settings. If that's the case, just remove the ini setting override and restart the Herd services.

I believe I don't have one, when I am not mistaken. I have no other PHP in `etc/php` or `/usr/local`. I also use 1.4.0 currently.
