### ISSUE TITLE
[Bug]: env: php: No such file or directory

### ISSUE THREAD

**Issue by saeedvaziry** [beyondcode/herd-community#268]
### Operating system version

macOS 14.1.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.3.1 (Build 18)

### PHP Version

PHP 8.2.13

### Bug description

Running the following code via Herd's HTTP Webserver

```php
exec("/Users/saeed.vaziry/Fun/laravel/artisan hello 2>&1", $output, $return_var);
info('Output: ' . implode("\n", $output));
info('Return Var: ' . $return_var);
```

And getting this Result

```
Output: env: php: No such file or directory
```

Looks like it doesn't recognize the path of the php binary

**Comment by mpociot** [comment]
Hey,

this is related to https://github.com/beyondcode/herd-community/issues/94 

Please modify your FPM configuration file and add the `PATH` environment variable to your config.

```
env[PATH] = {herd bin path}
```
