### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by brySuarez0711** [beyondcode/herd-community#27]
### Operating system version

macOS Ventura 13

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.0.6

### Bug description

Hi, I am getting an error when install a project with Akaunting, I get always a 404 not found in my site.

### Steps to reproduce

Install akaunting project

### Relevant log output

```shell
404 not found
```

**Comment by mpociot** [comment]
This must be an issue with the way you have linked your site/project.
Closing this as it is not an issue with Herd itself.
