### ISSUE TITLE
[Bug]: Herd serves another locate site SSL certificate

### ISSUE THREAD

**Issue by nicolasbinet** [beyondcode/herd-community#271]
### Operating system version

macOs Sonoma 14.1.2 (23B2091)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.3.1 (Build: 18)

### Bug description

Local website serves another local website SSL certificate

### Steps to reproduce

I've secured a new website through Laravel Herd interface.
When browsing this website, both Google Chrome (+dev) & Firefox (+developer edition) state the website as non secured.
When reading the SSL certificate I get the certificate for another local website.
Any idea what could be the reason? and how I could fix it?

![CleanShot 2023-12-06 at 09 00 51@2x](https://github.com/beyondcode/herd-community/assets/867710/3182bbc9-316c-4049-a81b-f9c262fa62b5)

**Comment by nicolasbinet** [comment]
Now it's working correctly.
I've only restarted the computed since my first message.
Also, at that time, all services where not green lighted in the Herd menu bar dropdown.
Hope this helps.

**Comment by ItsRD** [comment]
I've got the same issue. I've created a new local website and try to give it a SSL certificate, however when I check the details, it shows me another website from the folder.

The other local domain its referring to was a valet website.
