### ISSUE TITLE
[Bug]: Unable to override max_execution_time value

### ISSUE THREAD

**Issue by ElRochito** [beyondcode/herd-community#272]
### Operating system version

macOS Sonoma 14.1.2

### System architecture

Intel (x86)

### Herd Version

1.3.1 (Build 18)

### PHP Version

PHP 8.2.13 (cli) (built: Nov 26 2023 00:00:08) (NTS)

### Bug description

Updates `max_execution_time` in `php.ini` is not taken into account

### Steps to reproduce

- Update `<path_to_herd>/config/php/8x/php.ini`
- Set `max_execution_time=-1`
- `herd restart`
- `php -i | grep max_execution_time`

It will prompt `max_execution_time => 0 => 0`

**Comment by nblackburn** [comment]
Related: #267 

It doesn't appear as though the `php.ini` file is not being used, so this is likely related.

**Comment by mpociot** [comment]
Please see https://github.com/beyondcode/herd-community/issues/267#issuecomment-1850042661

**Comment by Fludem** [comment]
> I am facing this issue, running php8.2. Followed [#267 (comment)](https://github.com/beyondcode/herd-community/issues/267#issuecomment-1850042661), didn't working still.

I'm also facing this issue and the comment also didn't work.

I can change the memory limit in the .ini file and run Herd Restart in terminal and the changes are reflected, however max execution time is printing:

> dylanmarriott@Dylans-Air ~ % php -i | grep execution
> max_execution_time => 0 => 0

**Comment by Fludem** [comment]
### Update

We're all idiots, you can't test max execution time via CLI because it defaults to unlimited that's why we see
>max_execution_time => 0 => 0

I created a route to dump PHPInfo:

```php
Route::get('/dump', function () {
    return response()->make(phpinfo(), 200, ['Content-Type' => 'text/plain']);
});
```

This shows the modified value. The CLI having different values is detailed here:
[PHP Max Execution Time](https://www.php.net/manual/en/info.configuration.php#ini.max-execution-time)

Which says the following:

> max_execution_time [int](https://www.php.net/manual/en/language.types.integer.php)
> This sets the maximum time in seconds a script is allowed to run before it is terminated by the parser. This helps prevent poorly written scripts from tying up the server. The default setting is 30. When running PHP from the [command line](https://www.php.net/manual/en/features.commandline.php) the default setting is 0.
