### ISSUE TITLE
[Bug]: Can't share local site with Ngrok

### ISSUE THREAD

**Issue by ammar-madni** [beyondcode/herd-community#278]
### Operating system version

macOS Sonoma 14.2

### System architecture

Intel (x86)

### Herd Version

1.3.1 (Build 18)

### PHP Version

PHP 7.4

### Bug description

I use Valet normally and sharing my local sites using Ngrok/Cloudflare Tunnels works just fine. But with Herd I get a 404 when visiting the public domain provided by Ngrok/Cloudflare.

### Steps to reproduce

Run `ngrok http https://your-site.test`. Visit the link provided by ngrok.

**Comment by mpociot** [comment]
You need to add `--host-header=rewrite` to your command in order to tell ngrok that it should send the appropriate headers.

```
ngrok http https://your-site.test --host-header=rewrite
```

Not sure if Valet handles this differently, but this is the default (per ngrok docs) way to do it.

**Comment by ammar-madni** [comment]
Thanks @mpociot, that's the solution I ended up going with.

Valet handles it differently as I've never had to use the flag before.

Any chance you're familiar with the equivalent flag required when using Cloudflare tunnels?

**Comment by tanhatariq** [comment]
> Thanks [@mpociot](https://github.com/mpociot), that's the solution I ended up going with.
> 
> Valet handles it differently as I've never had to use the flag before.
> 
> Any chance you're familiar with the equivalent flag required when using Cloudflare tunnels?

I've tried the same header tag with Cloudflare directed to a herd URL working on host machine, but the header tag --host-header=rewrite doesn't seems to work, @ammar-madni Did u had any luck to find a solution, make a herd site work through CF tunnel? If so, do share, how you achieved it.
