### ISSUE TITLE
[Bug]:  Changes in views not taking effect

### ISSUE THREAD

**Issue by ize-302** [beyondcode/herd-community#28]
### Operating system version

macOS Ventura 13.4.1

### System architecture

Intel (x86)

### Herd Version

1.0.8 (Build: 10)

### Bug description

Changes made on the views aren't taking effect in the browser. 

Only occurs when project is installed with Breeze template (React or Vue)

### Steps to reproduce

- Setup a project `laravel new PROJECT_NAME --breeze`
- Select either Vue or React for templating option
- After installation, (make sure Herd is running), open project in browser
- In the project, make changes to the views
- Refresh the page

**Comment by mpociot** [comment]
Not sure which view you're editing, but it's working fine.
When choosing breeze make sure to update your vue/react components, not the blade file.
Changes will also need you to run `npm run dev`.
