### ISSUE TITLE
[Bug]: Include xml files for Imagick to prevent issues

### ISSUE THREAD

**Issue by robdekort** [beyondcode/herd-community#280]
### Operating system version

macOS Sonoma 14.2

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.3.1

### PHP Version

All available PHP versions

### Bug description

The Imagick extension is included in Herd, but it seems to missing ` --with-xml` for the `imagemagick` library. This causes issues with using Imagick [like these](https://github.com/beyondcode/herd-community/issues/86) when trying to use `readImageBlob`.

See this comment for a possible solution: https://github.com/beyondcode/herd-community/discussions/90#discussioncomment-7894968

Much appreciated 🙏.

### Steps to reproduce

$image = new Imagick();
$svg = file_get_contents("image.svg");
$image->readImageBlob($svg);

### Relevant log output

```shell
UnableToOpenConfigureFile `delegates.xml' @ warning/configure.c/GetConfigureOptions/722
```

**Comment by mpociot** [comment]
I'm waiting for https://github.com/crazywhalecc/static-php-cli/pull/64 to be merged, and then I'll update our builder to fix this 👍

**Comment by robdekort** [comment]
Wonderful. Thank you for the update Marcel. I'll keep an eye out.

**Comment by mpociot** [comment]
Just to give you a quick update: I've been working on upgrading our PHP builds the whole day and tested things, but unfortunately the Apple notarization service is currently down, so the PHP updates might take some time to be published (most likely tomorrow).

**Comment by robdekort** [comment]
No worries and I really appreciate all the work that goes into this. Happy to test whenever you and Apple are ready.

**Comment by msucevan** [comment]
I have the same issue, right. Waiting to be merge soon. Thanks for your work

**Comment by mpociot** [comment]
The builds are now being distributed, starting with ARM64 versions - Intel builds will follow afterward.

PHP 8.3.0 is already available and fixes this bug, the other versions are compiling  🎉

**Comment by robdekort** [comment]
Amazing. Thank you and best wishes for the Holidays Marcel.

**Comment by robdekort** [comment]
I can confirm it's fixed in 8.3 🥳

**Comment by msucevan** [comment]
Sorry for my misunderstanding in this matter. But, I have the newest version of Herd (Intel version) and the newest PHP versions, but I still get the error. I need something to manually update/install?

**Comment by msucevan** [comment]
Sorry @mpociot @robdekort for my misunderstanding in this matter. But, I have the newest version of Herd (Intel version) and the newest PHP versions, but I still get the error. I need something to manually update/install?

**Comment by mpociot** [comment]
@msucevan could you tell me which architecture (Intel/M1 etc) you are using and which PHP version?

**Comment by robdekort** [comment]
FWIW all still seems good on M1/8.3.

**Comment by msucevan** [comment]
@mpociot I'm using Intel with 8.1

**Comment by bitbirddev** [comment]
i would love to have avif/heic/heif support for imagemagick. since it is compiled in the php binary i can't update it via pecl. my local imagemagick has avif-Delegates but php's imagemagick extension always uses that one shipped with herd...

**Comment by bitbirddev** [comment]
@davideprevosto i'm sorry but i haven't found any solution yet. if you do, please tell me :P

**Comment by davideprevosto** [comment]
> @davideprevosto i'm sorry but i haven't found any solution yet. if you do, please let me know :P

@bitbirddev I will try to use Valet
