### ISSUE TITLE
[Bug]: Updated PHP and now can't load extensions

### ISSUE THREAD

**Issue by ryanmortier** [beyondcode/herd-community#281]
### Operating system version

macOS Sonoma 14.1.2

### System architecture

ARM64 M2

### Herd Version

1.3.1 (Build: 18)

### PHP Version

PHP 8.2.13 (cli) (built: Dec 20 2023 15:02:15) (NTS)

### Bug description

I got a notification from Herd to update PHP which I then clicked to update. Now php-fpm won't start and I can't run php from cli anymore.

I'm loading in extensions `pdo_sqlsrv.so` and `sqlsrv.so` which worked previously without issue.

If I comment out these two extensions from the php.ini file, I can start php-fpm and php works in the cli.

Here is my `php.ini`:
```
extension=/opt/homebrew/lib/php/pecl/20220829/pdo_sqlsrv.so
extension=/opt/homebrew/lib/php/pecl/20220829/sqlsrv.so

curl.cainfo=/Users/ryan/Library/Application Support/Herd/config/php/cacert.pem
openssl.cafile=/Users/ryan/Library/Application Support/Herd/config/php/cacert.pem
pcre.jit=0


memory_limit=128M
upload_max_filesize=50M
```

Here is the error I get when trying to run in cli:

> Error finding executable PHP. Quitting for safety.
Provided output from find-usable-php.php:
Warning: PHP Startup: Unable to load dynamic library '/opt/homebrew/lib/php/pecl/20220829/pdo_sqlsrv.so' (tried: /opt/homebrew/lib/php/pecl/20220829/pdo_sqlsrv.so (dlopen(/opt/homebrew/lib/php/pecl/20220829/pdo_sqlsrv.so, 0x0009): symbol not found in flat namespace '_OnUpdateLong'), /lib/php/extensions/no-debug-non-zts-20220829//opt/homebrew/lib/php/pecl/20220829/pdo_sqlsrv.so.so (dlopen(/lib/php/extensions/no-debug-non-zts-20220829//opt/homebrew/lib/php/pecl/20220829/pdo_sqlsrv.so.so, 0x0009): tried: '/lib/php/extensions/no-debug-non-zts-20220829//opt/homebrew/lib/php/pecl/20220829/pdo_sqlsrv.so.so' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/lib/php/extensions/no-debug-non-zts-20220829//opt/homebrew/lib/php/pecl/20220829/pdo_sqlsrv.so.so' (no such file), '/lib/php/extensions/no-debug-non-zts-20220829//opt/homebrew/lib/php/pecl/20220829/pdo_sqlsrv.so.so' (no such file))) in Unknown on line 0 Warning: PHP Startup: Unable to load dynamic library '/opt/homebrew/lib/php/pecl/20220829/sqlsrv.so' (tried: /opt/homebrew/lib/php/pecl/20220829/sqlsrv.so (dlopen(/opt/homebrew/lib/php/pecl/20220829/sqlsrv.so, 0x0009): symbol not found in flat namespace '_OnUpdateBool'), /lib/php/extensions/no-debug-non-zts-20220829//opt/homebrew/lib/php/pecl/20220829/sqlsrv.so.so (dlopen(/lib/php/extensions/no-debug-non-zts-20220829//opt/homebrew/lib/php/pecl/20220829/sqlsrv.so.so, 0x0009): tried: '/lib/php/extensions/no-debug-non-zts-20220829//opt/homebrew/lib/php/pecl/20220829/sqlsrv.so.so' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/lib/php/extensions/no-debug-non-zts-20220829//opt/homebrew/lib/php/pecl/20220829/sqlsrv.so.so' (no such file), '/lib/php/extensions/no-debug-non-zts-20220829//opt/homebrew/lib/php/pecl/20220829/sqlsrv.so.so' (no such file))) in Unknown on line 0 /Users/ryan/Library/Application Support/Herd/bin/php82

I'm assuming it has something to do with the bundled PHP because if I use the system PHP installed via homebrew, it loads the extensions just fine as seen below:

> ➜  20220829 git:(stable) bphp -v
PHP 8.2.13 (cli) (built: Nov 21 2023 09:55:59) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.13, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.13, Copyright (c), by Zend Technologies

> ➜  20220829 git:(stable) bphp -m | grep sqlsrv
pdo_sqlsrv
sqlsrv

> ➜  20220829 git:(stable) which bphp
bphp: aliased to /opt/homebrew/bin/php

> ➜  20220829 git:(stable) l
total 1.5M
-rw-r--r-- 1 root admin 342K Nov 30 20:44 pdo_sqlsrv.so
-rw-r--r-- 1 root admin 755K Nov 30 20:51 redis.so
-rw-r--r-- 1 root admin 338K Nov 30 20:43 sqlsrv.so

> ➜  20220829 git:(stable) pwd
/opt/homebrew/lib/php/pecl/20220829

> ➜  20220829 git:(stable) pecl list
Installed packages, channel pecl.php.net:
=========================================
Package    Version State
pdo_sqlsrv 5.11.1  stable
redis      6.0.2   stable
sqlsrv     5.11.1  stable

### Steps to reproduce

Upgrade Herd's php with custom extensions.

### Relevant log output

See above

**Comment by jason-beach** [comment]
Having the same issues! Any thoughts?

**Comment by mpociot** [comment]
I'll look into this. 

@jason-beach do you have this problem with the same extension?

**Comment by peterbrinck** [comment]
Also an issue for me.

In my case it's `pcov`, which I build from the source
https://github.com/krakjoe/pcov/blob/develop/INSTALL.md

**Comment by jason-beach** [comment]
@mpociot yes same as what was reported exactly.

**Comment by mpociot** [comment]
It looks like /lib/php/extensions/no-debug-non-zts-20220829/ is hardcoded in front of the actual lookup path. 

Any idea what's causing this @crazywhalecc ?

**Comment by ryanmortier** [comment]
@mpociot does this have anything to do with the `extension_dir` config in the "real" `php.ini` file wherever that exists?

The `extension` directive is a relative path to the `extension_dir` path.

**Comment by upwebdesign** [comment]
One thing I noticed is that if I were to put a non-existent extension in the php.ini file, I wouldn't receive any errors at all.

> extention=/opt/homebrew/lib/php/pecl/20220829/pdo_sqlsrvasdasdasdasd.so

But if I add `post_max_size = 1G`, it is correctly reflected on the info page even if the fake extension is still in the `php.ini` file. I cannot explain this behavior. It may be something I am doing on my end.

**Comment by mpociot** [comment]
A new PHP build is currently being compiled - I started with 8.2 on ARM64.
While upgrading the PHP build scripts to the latest version, I didn't notice that I now have to pass the `--no-strip` option to keep debug symbols and the ability to load external extensions.

I successfully tested this locally with the grpc extension. 
Can you verify this? The update is for 8.2 is now available.

**Comment by crazywhalecc** [comment]
I should have made no changes to the extension lookup directory. And I tested xdebug on latest 8.2.13 in Herd.

But after I tried to upgrade PHP just now, I found that it did not read the php.ini file, so when I add it for the first time, it was not loading extension until I uncommented the zshrc configuration file or used the `-d` to specify the conf.

**Comment by upwebdesign** [comment]
@mpociot @crazywhalecc, I can now load the `pdo_sqlsrv` and `sqlsrv` extensions. Thank you for the quick turnaround!

To be completely truthful, at one point in my debugging, I started using `extention=` instead of `extension=`; however, the original issue reared its head before I began debugging. I'm just happy I caught myself before commenting in error.

**Comment by mpociot** [comment]
Awesome! I'll publish the other versions now so this issue will be foxed in all updated PHP versions!

**Comment by mpociot** [comment]
Closing this issue as the new builds are being distributed

**Comment by ryanmortier** [comment]
Fixed for me too, thanks.

**Comment by patrick-levesque** [comment]
I also had issues yesterday after updating to the latest PHP. Everything's working fine now. Thanks for quickly fixing it!

**Comment by ryanmortier** [comment]
I don't think you can use API version `20220829` for PHP 7.4? You probably have the wrong version of the extension installed.

From PHP 7.4 CLI, try this command and post results `php -i | grep "PHP API"`

**Comment by subdesign** [comment]
> I don't think you can use API version `20220829` for PHP 7.4? You probably have the wrong version of the extension installed.

Wow, version 20190902 worked for me, I missed testing this version, my bad!
Thanks
