### ISSUE TITLE
[Bug]: Bad CPU type in executable

### ISSUE THREAD

**Issue by jaeggiag** [beyondcode/herd-community#282]
### Operating system version

Sonoma 14.1.1

### System architecture

Intel (x86)

### Herd Version

1.3.1 (Build 18)

### Bug description

with 8.2, php --version -> Bad CPU type in executable
with 8.0, php --version -> PHP 8.0.30 (cli) (built: Aug  5 2023 00:26:50) ( NTS )

**Comment by jEstevezRod** [comment]
Same error here, for me only happens with 8.2.14.

When I change to 8.3 (8.3.0) it works well

Also happens that Sites tabs now don't show any project it used to show. It occurred just when I updated the php version of php fpm 8.2

**Comment by mpociot** [comment]
Sorry, this was related to our build pipeline upgrade that introduced the new extensions (imap, ldap and xsl).
A new build is currently compiling and will be available in ~20 minutes

**Comment by crazywhalecc** [comment]
Are there more error messages for new versions (including imap, xsl, ldap)?

**Comment by mpociot** [comment]
@crazywhalecc nah it's unrelated to the extensions, I just had a misconfigured workflow action after upgrading to your main branch, which caused the automatic job to use the wrong (arm64) worker instead of the intel one.

**Comment by CristianSitov** [comment]
Any chance to unblock the `herd` app after switching to php8.1?

```
➜  Herd herd
/Users/crs/Library/Application Support/Herd/bin//herd: line 166: /Users/crs/Library/Application Support/Herd/bin/php82: Bad CPU type in executable
```
