### ISSUE TITLE
[Bug]: Composer why-not php 8 doesn't work with Herd php binary

### ISSUE THREAD

**Issue by kasus** [beyondcode/herd-community#283]
### Operating system version

macOS Sonoma 14.2.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.3.1 (Build 18)

### PHP Version

PHP 8.1.26 (cli) (built: Dec 21 2023 08:51:01) (NTS)

### Bug description

Composer why-not command running with Herd's php binary returns an error, while it works well with php binary from homebrew.
I checked with Herd 8.1 and 8.2 binaries.

### Steps to reproduce

Under Laravel 9 installation
```bash
composer why-not php 8.2
```

### Relevant log output

```shell
Package "php" could not be found with constraint "8.2", results below will most likely be incomplete.
There is no installed package depending on "php" in versions not matching 8.2
Not finding what you were looking for? Try calling `composer update "php:8.2" --dry-run` to get another view on the problem.
```

**Comment by sschlein** [comment]
I just tried it and it works:

```
Package "php" could not be found with constraint "8.2", results below will most likely be incomplete.
nette/schema     v1.2.2  requires php (>=7.1 <8.2)
nette/utils      v3.2.7  requires php (>=7.2 <8.2)
phpspec/prophecy v1.15.0 requires php (^7.2 || ~8.0, <8.2)
Not finding what you were looking for? Try calling `composer update "php:8.2" --dry-run` to get another view on the problem.
```

Feeld free to reopen the issue if the issue persists. In general, that doesn't seem to be php version of Herd related.
