### ISSUE TITLE
[Feature Request]: Add support for xdebug by default

### ISSUE THREAD

**Issue by MouhcineMAHFOUD** [beyondcode/herd-community#284]
### Feature Description

XDebug is a very important tool that allows many teams debug on various big PHP projects regardless of the technology/framework.
It will be a big addition to the awesome features that Herd brings out of the box especially for teams working on big projects.

### Is this feature valuable for other users as well and why?

Xdebug is not only valuable, but sometimes it's necessary to hunt bugs.

**Comment by sschlein** [comment]
Xdebug is included by default now: https://herd.laravel.com/docs/1/advanced-usage/xdebug

No more brew!
