### ISSUE TITLE
[Feature Request]: Just a windows version

### ISSUE THREAD

**Issue by MohamadElhadidy** [beyondcode/herd-community#29]
### Feature Description

Just a windows version 
i don't know why most laravel ecosystem  is macos only 

### Is this feature valuable for other users as well and why?
there are more people using windows than any os

**Comment by mpociot** [comment]
A windows version is currently not planned

**Comment by soixt** [comment]
It's said when Taylor said he doesnt want to limit people of simply trying/using laravel and presents herd which limits people to MAC only....
