### ISSUE TITLE
[Bug]: Error 502 "Bad Gateway" when using a email:dns validation after POST

### ISSUE THREAD

**Issue by neurotools** [beyondcode/herd-community#291]
### Operating system version

macOS Ventura 13.5

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.3.1 (Build 18)

### PHP Version

PHP 8.3.0 (cli) (built: Dec 20 2023 22:44:53) (NTS)

### Bug description

Herd fails with a 502 Bad Gateway error when sending a POST request to a route when there's a validation rule with "email:dns".

This is related to issue #76

### Steps to reproduce

The following repo has a minimal case to reproduce the error: [https://github.com/neurotools/herd-error-502-test](https://github.com/neurotools/herd-error-502-test)

### Relevant log output

```shell
2024/01/04 16:48:01 [error] 7776#1769305: *1320 upstream prematurely closed connection while reading response header from upstream, client: 127.0.0.1, server: , request: "POST / HTTP/1.1", upstream: "fastcgi://unix:/Users/neurotools/Library/Application Support/Herd/herd.sock:", host: "herd-error-502-test.test", referrer: "http://herd-error-502-test.test/"
```

**Comment by neurotools** [comment]
I tried to trace down where the error is triggered and found that a call to PHP's function [dns_get_record](https://www.php.net/manual/en/function.dns-get-record.php) is what causes the error 502.

I added other route to the repo to test that.

```php
Route::get('test', function () {
    return dns_get_record('laravel.com', DNS_A);
});
```
This route trigger the error.

**Comment by yoeriboven** [comment]
Same error here. All works well when I remove `dns` from the validation rules.

**Comment by mpociot** [comment]
Could you tell me which PHP version and operating system (architecture) you have?
This works fine for me.

**Comment by neurotools** [comment]
Indeed, when using 1.1.1.1 as DNS server, if works like a charm. As soon as I changed back to my ISP's DNS servers, it fails.

Using 2800:150:e:3:14 it fails

**Comment by mpociot** [comment]
Huh okay - this should at least help us figure out what's going wrong. Thank you for confirming this.

**Comment by bojmaliev** [comment]
I can confirm i have the same error

**Comment by mpociot** [comment]
I'm closing this for now as I'm unable to properly reproduce this. Both @crazywhalecc (who maintains the static-php build) and I tried to debug and reproduce this issue without success.
