### ISSUE TITLE
[Bug]: Various breaking bugs seemingly surrounding PHP 8.3

### ISSUE THREAD

**Issue by legecha** [beyondcode/herd-community#292]
### Operating system version

macOS Sonoma 14.2.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.3.1 (18)

### Bug description

No sites showed up, no PHP, Laravel or Composer binaries would run, couldn't add other sites.

### Steps to reproduce

After a fresh installation, I noticed that no sites showed up. Tried adding/removing directories (~/Development, ~/Herd, ~/Code, etc) to no avail.

Notice that in .zshrc it had added `HERD_PHP_82_INI_SCAN_DIR` pointing to an `82` directory, however only 8.3 was installed.

Also noticed that `~/Library/Application Support/Herd/bin/php` had a broken symlink - pointing to a non-existent 8.2 binary instead of the installed 8.3.

Once I fixed these paths, `php --version` and `composer --version` started working again.

However, sites still won't show anything up, including after clicking refresh. Also, if I use the + button to add a new site, that fails after going through the options with the following error:

```
There was an error creating your application...

Installer Output
/bin/sh: line 1: /Users/whoever/Library/Application Support/Herd/bin/php82: No such file or directory
```

This made me wonder if it was 8.2 that was used internally to perform various tasks. So I installed 8.2 again and that seemed to fix the issues - everything seems to work again.

### Relevant log output

```shell
Both logs in Log were empty.
```

**Comment by mpociot** [comment]
Hey,

yeah this is a known issue that we are currently working on. Right now, you still need PHP 8.2 in order to see sites and create new ones. This will be fixed in an update this week.

**Comment by drbe4t** [comment]
@mpociot how do i fix this now? I did upgrade from herd. I've tried uninstalling PHP versions and reinstalling them.
