### ISSUE TITLE
[Bug]: Herd Version Number does not display the current installed GUI Version in command line

### ISSUE THREAD

**Issue by Houbsi** [beyondcode/herd-community#293]
### Operating system version

macOS Sonoma 14.2.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.3.1 (Build18)

### PHP Version

PHP 8.3

### Bug description

<img width="1164" alt="image" src="https://github.com/beyondcode/herd-community/assets/70960/9dbc2c7b-1aac-4666-b28b-9d19ae61d1a6">

When running the herd command from the command line, there is a different version number as shown in the GUI

**Comment by mpociot** [comment]
This will be fixed in the next update, thanks!
