### ISSUE TITLE
I get : Warning: Module "redis" is already loaded in Unknown on line 0 message

### ISSUE THREAD

**Issue by subdesign** [beyondcode/herd-community#295]
### Operating system version

macOS Monterey 12.7.2

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.3.2 (build 19)

### Bug description

First of all it's not a bug just don't know why happens. After installed and setup Herd, I started adding extensions one by one to my php 8.2 ini. 
After that added extensions to to 8.1 ini also. 
But changing to an 8.1 project, and running eg. artisan command I get the message: 
`Warning: Module "redis" is already loaded in Unknown on line 0` or `Warning: Module "imagick" is already loaded in Unknown on line 0`

how should I handle extensions?

my 8.2 php.ini:
```php
curl.cainfo=/Users/user/Library/Application Support/Herd/config/php/cacert.pem
openssl.cafile=/Users/user/Library/Application Support/Herd/config/php/cacert.pem
pcre.jit=0
output_buffering=4096
extension=/opt/homebrew/lib/php/pecl/20220829/memcached.so
extension=/opt/homebrew/lib/php/pecl/20220829/imagick.so
extension=/opt/homebrew/lib/php/pecl/20220829/redis.so

memory_limit=512M
upload_max_filesize=64M
```

my 8.1 php.ini:
```php
curl.cainfo=/Users/user/Library/Application Support/Herd/config/php/cacert.pem
openssl.cafile=/Users/user/Library/Application Support/Herd/config/php/cacert.pem
pcre.jit=0
output_buffering=4096
extension=/opt/homebrew/lib/php/pecl/20220829/memcached.so
extension=/opt/homebrew/lib/php/pecl/20220829/redis.so

memory_limit=512M
upload_max_filesize=64M
```
<img width="553" alt="Screenshot 2024-01-12 at 16 40 08" src="https://github.com/beyondcode/herd-community/assets/691695/49e70355-3897-405a-9b9d-5afee67828ac">

**Comment by mpociot** [comment]
Those extensions are already included with Herd, so you do not need to manually load them
