### ISSUE TITLE
[Bug]: PHP pecl extension installed in 20230831 directory instead of 20220829 

### ISSUE THREAD

**Issue by christianschoenmakers** [beyondcode/herd-community#297]
### Operating system version

14.1.1 (23B81)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.3.2

### PHP Version

PHP 8.3.0 (cli) (built: Dec 20 2023 22:44:53) (NTS)

### Bug description

I want to install sqlsrv and pdo_sqlsrv extensions. I've installed them with pecl. 

According to the documentation https://herd.laravel.com/docs/1/advanced-usage/additional-extensions the extensions should be added to the php.ini file in this way: 

```
extension=/opt/homebrew/lib/php/pecl/20220829/[extension].so
```

However, the pecl extensions are installed in the `20230831` directory on my machine.

If I include them with the new directory, I'm getting an error when restarting PHP.

```
extension=/opt/homebrew/lib/php/pecl/20230831/sqlsrv.so
extension=/opt/homebrew/lib/php/pecl/20230831/pdo_sqlsrv.so
```

(I've also tested to include the `extension_dir` instead of the full paths)

Warning when restarting Herd / PHP:

```
Warning: PHP Startup: sqlsrv: Unable to initialize module
Module compiled with module API=20230831
PHP    compiled with module API=20220829
These options need to match
 in Unknown on line 0

Warning: PHP Startup: pdo_sqlsrv: Unable to initialize module
Module compiled with module API=20230831
PHP    compiled with module API=20220829
These options need to match
 in Unknown on line 0
```

### Steps to reproduce

Install sqlsrv and pdo_sqlsrv according to the documentation 

Add extensions to php.ini file

Reload Herd / PHP

**Comment by tembra** [comment]
Possible same problem as #296 

The folder chosen by PECL to save the extension must not be changed by you. I guess this folder contains the date of extension's release.

Probably when you installed PHP through brew you got a different version that Herd is using.

**Comment by SDJeff** [comment]
> Probably when you installed PHP through brew you got a different version that Herd is using.

If you have a fresh mac with Sonoma it will install by default php8.3 if you use brew.
So after the installation i switch in Herd to php8.3. 

But if you install than like described the xdebug extension. I had no error message with the path, but also no xdebug extension enabled.

**Comment by SDJeff** [comment]
> ### Operating system version
> 14.1.1 (23B81)
> 
> ### System architecture
> ARM64 (M1, M2, etc)
> 
> ### Herd Version
> 1.3.2
> 
> ### PHP Version
> PHP 8.3.0 (cli) (built: Dec 20 2023 22:44:53) (NTS)
> 
> ### Bug description
> I want to install sqlsrv and pdo_sqlsrv extensions. I've installed them with pecl.
> 
> According to the documentation https://herd.laravel.com/docs/1/advanced-usage/additional-extensions the extensions should be added to the php.ini file in this way:
> 
> ```
> extension=/opt/homebrew/lib/php/pecl/20220829/[extension].so
> ```
> 
> However, the pecl extensions are installed in the `20230831` directory on my machine.
> 
> If I include them with the new directory, I'm getting an error when restarting PHP.
> 
> ```
> extension=/opt/homebrew/lib/php/pecl/20230831/sqlsrv.so
> extension=/opt/homebrew/lib/php/pecl/20230831/pdo_sqlsrv.so
> ```
> 
> (I've also tested to include the `extension_dir` instead of the full paths)
> 
> Warning when restarting Herd / PHP:
> 
> ```
> Warning: PHP Startup: sqlsrv: Unable to initialize module
> Module compiled with module API=20230831
> PHP    compiled with module API=20220829
> These options need to match
>  in Unknown on line 0
> 
> Warning: PHP Startup: pdo_sqlsrv: Unable to initialize module
> Module compiled with module API=20230831
> PHP    compiled with module API=20220829
> These options need to match
>  in Unknown on line 0
> ```
> 
> ### Steps to reproduce
> Install sqlsrv and pdo_sqlsrv according to the documentation
> 
> Add extensions to php.ini file
> 
> Reload Herd / PHP
> 
> ### Relevant log output
> _No response_

I think you need for > M1 platform like described at the MS Docs here: [Linux and macOS Installation](https://learn.microsoft.com/de-de/sql/connect/php/installation-tutorial-linux-mac?view=sql-server-ver16#installing-on-macos)
sudo CXXFLAGS="-I/opt/homebrew/opt/unixodbc/include/" LDFLAGS="-L/opt/homebrew/lib/" pecl install sqlsrv
sudo CXXFLAGS="-I/opt/homebrew/opt/unixodbc/include/" LDFLAGS="-L/opt/homebrew/lib/" pecl install pdo_sqlsr

**Comment by mpociot** [comment]
This issue is related to the way that pecl via brew utilizes the installed PHP version(s) and not an issue with Herd itself.
