### ISSUE TITLE
Additional .ini files not loaded by php-fpm, but in terminal they are

### ISSUE THREAD

**Issue by exophunk** [beyondcode/herd-community#298]
### Operating system version

macOs Ventura 13.5

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

Herd 1.3.2

### PHP Version

PHP 8.2.14

### Bug description

I can place an additional `xdebug.ini` file in the folder:
`/Users/robertkrieg/Library/Application Support/Herd/config/php/82/`

The output of `php --ini` (or `herd php --ini`) is:

```
Configuration File (php.ini) Path: /lib
Loaded Configuration File:         (none)
Scan for additional .ini files in: /Users/robertkrieg/Library/Application Support/Herd/config/php/82/
Additional .ini files parsed:      /Users/robertkrieg/Library/Application Support/Herd/config/php/82/php.ini,
/Users/robertkrieg/Library/Application Support/Herd/config/php/82/xdebug.ini
```

When running `php` from the terminal, the additional ini file is parsed correctly (and XDebug is running)

When running PHP via browser (running the website), only the `php.ini` file is loaded and additional *.ini files are ignored. How would I configure herd php to also load additional ini files in the directory?

In the `phpinfo()` output in the browser, it says:
```
Scan this dir for additional .ini files 	(none)
Additional .ini files parsed 	(none) 
```

### Steps to reproduce

Add additional `file.ini` file next to your `php.ini` file

- In terminal `php` it is loaded
- In the browser, additional files are not loaded, only `php.ini`

**Comment by mpociot** [comment]
Hey!
I just noticed this two days ago and fixed it locally already. 

This will be fixed in the next app update. In the meantime, please combine the ini values in a single file.
