### ISSUE TITLE
[Bug]: Site won't use chosen PHP version

### ISSUE THREAD

**Issue by asdf072** [beyondcode/herd-community#300]
### Operating system version

macOS 14.2.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.3.2

### PHP Version

PHP 8.2/7.4

### Bug description

I have several sites running on 8.2, but one needs to run 7.4. I installed and then chose 7.4 in the Settings->Sites gui. I can see php7.4 running via `ps ax`, but that site is still using php 8.2, which crashes.

I tried using Valet at one point, so it looks like I have nginx entries for a few of those sites, but not the one that needs 7.4. Would it be helpful to remove the Valet portions?

### Steps to reproduce

Install Herd as directed. Change one site to php7.4 via the GUI. Restart Herd. Site marked as 7.4 still runs via fpm on 8.2.

**Comment by mpociot** [comment]
Which output do you get when you run `herd isolated`?

**Comment by asdf072** [comment]
I'm sorry. This was an unrelated issue.
