### ISSUE TITLE
[Bug]: PHP 8.3 still on old version

### ISSUE THREAD

**Issue by ultimateBusiness** [beyondcode/herd-community#302]
### Operating system version

macOS Sonoma 14.2.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.3.2 (Build: 19)

### Bug description

We are officially on PHP 8.3.2, but in Herd is still 8.3.0 installed.

**Comment by mpociot** [comment]
The new builds are now available and get built automatically
