### ISSUE TITLE
[Bug]: WebSockets with SSL does not seem to be working (Pusher/Soketi/Echo)

### ISSUE THREAD

**Issue by caendesilva** [beyondcode/herd-community#304]
### Operating system version

macOS Sonoma 14.2

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.2.2, Build 16

### Bug description

I am unable to get WebSockets to work when securing the local Herd domain. Turning off SSL, the WebSockets work as expected. But when secured, it times out.

As I'm getting the same issue with both the laravel-websockets package and Soketi through Docker I suspect something with Herd could be the culprit. 

### Steps to reproduce

I'm on Laravel 10, with the documented examples to set up Echo with Soketi.

### Relevant log output

```shell
app-zM25f0wj.js:11 WebSocket connection to 'wss://localhost:6001/app/app-key?protocol=7&client=js&version=7.6.0&flash=false' failed: WebSocket is closed before the connection is established.
```

**Comment by mpociot** [comment]
The SSL certificate file for Herd gets stored in `~/Library/Application Support/Herd/config/php/cacert.pem` so I assume that Socketi and Laravel WebSockets need to read/parse this file to obtain information about the certificate. 
I'm not sure how to do this with Soketi, for Laravel WebSockets, please configure the ssl options accordingly:

https://github.com/beyondcode/laravel-websockets/blob/master/config/websockets.php#L267-L281

**Comment by caendesilva** [comment]
> The SSL certificate file for Herd gets stored in `~/Library/Application Support/Herd/config/php/cacert.pem` so I assume that Socketi and Laravel WebSockets need to read/parse this file to obtain information about the certificate. I'm not sure how to do this with Soketi, for Laravel WebSockets, please configure the ssl options accordingly:
> 
> https://github.com/beyondcode/laravel-websockets/blob/master/config/websockets.php#L267-L281

Okay thanks, knowing where the certificates are should help.
