### ISSUE TITLE
[Bug]: Schema dump is not working

### ISSUE THREAD

**Issue by msucevan** [beyondcode/herd-community#305]
### Operating system version

macOS Sonoma 14.2.1 (23C71)

### System architecture

Intel (x86)

### Herd Version

1.3.2 build 19

### PHP Version

PHP 8.2.15 (cli) (built: Jan 19 2024 00:32:27) (NTS)

### Bug description

Running the command:

```bash 
php artisan schema:dump
```

I get the following error:
```   
Symfony\Component\Process\Exception\ProcessFailedException 

  The command "mysqldump  --user="${:LARAVEL_LOAD_USER}" --password="${:LARAVEL_LOAD_PASSWORD}" --host="${:LARAVEL_LOAD_HOST}" --port="${:LARAVEL_LOAD_PORT}" --no-tablespaces --skip-add-locks --skip-comments --skip-set-charset --tz-utc "${:LARAVEL_LOAD_DATABASE}" --routines --result-file="${:LARAVEL_LOAD_PATH}" --no-data" failed.

Exit Code: 127(Command not found)```

### Steps to reproduce

_No response_

### Relevant log output

_No response_

**Comment by mpociot** [comment]
Make sure that `mysqldump` is available somewhere in your PATH environment variable.
We do not ship mysqldump along with Herd.

**Comment by altayevrim** [comment]
Hi everyone, I didn't want to open a new issue. 
Since the recent Services feature, any plans on shipping `mysqldump` with Herd Pro?
