### ISSUE TITLE
[Bug]: Nginx http not forwarding data to https

### ISSUE THREAD

**Issue by diogogomeswww** [beyondcode/herd-community#308]
### Operating system version

Sonoma 14.2.1

### System architecture

Intel (x86)

### Herd Version

1.3.2 (build 19)

### Bug description

Sending a post request to http has an empty $_REQUEST/$_POST.
The same request for the https works, but if we change it to http, it will fail because the payload is empty.

### Steps to reproduce

Send an http post request to the same endpoint using http and https.

**Comment by mpociot** [comment]
We send a 301 redirect, which does not persist POST and GET requests. If you want to achieve this, you will need to manually adjust your isolated sites nginx configuration file.
