### ISSUE TITLE
Duplicate application directory (domain name) problem

### ISSUE THREAD

**Issue by arqamsaeed786** [beyondcode/herd-community#310]
### Operating system version

Macos 14.3

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.3.2 (Build 19)

### PHP Version

php 8.1

### Bug description

I have a folder inside /valet folder which is called shahisouq_ecom and it was working fine. So i created another folder inside /valet/test/shahisouq_ecom and in the new folder i tried herd link and terminal shows (symbolic link has been created in **), so it shows correct message but my shahisouq_ecom domain became un accessible in chrome and also its not coming inside Herd sites so i tried hard and at last i created same folder inside /valet folder and i tried herd unlink there and then i use herd link inside new directory /valet/test/shahisouq_ecom, then everything works fine. so i think its overwrite or same domain in new place error.

### Steps to reproduce

create 2 folders with same name inside /valet/shahisouq and also in /valet/test/shahisouq and use herd link in both the places and this domain will be hidden from herd application sites window. i hope you understand it.

**Comment by sschlein** [comment]
So if you create multiple folders in multiple directories that are watched by herd and both have the same name or if you link then with the same domain, it won't work and there's no way to make it work :)
