### ISSUE TITLE
[Bug]: Wrong Shared URL when using herd share with Expose

### ISSUE THREAD

**Issue by heychazza** [beyondcode/herd-community#311]
### Operating system version

macoS Sonoma 14.3

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.3.2 (Build: 19)

### PHP Version

PHP 8.2.15 (cli) (built: Jan 19 2024 00:15:08) (NTS)

### Bug description

When running `herd share` with Expose, the wrong URL is returned. My app is configured to use `tebexanalytics.test` (with HTTPS) and works fine in the browser.

However with the `herd share` command, it returns "analytics.tebex.io.test:443" (analytics.tebex.io being the folder name) which results in a 404, site not found error.

### Steps to reproduce

Run `herd share`

**Comment by sschlein** [comment]
Hi @heychazza – while we debug this, you can run the command `herd share http://tebexanalytics.test` to share the correct url.

**Comment by sschlein** [comment]
We've discussed this internally and decided to keep it like it is now. Herd (and Expose) assume that you are using Herd or Valet and share foldername.test. If you use a different configuration and link the site with a different domain, you can share it via the command provided above.

Expose doesn't know anything about configured Herd domains nor could it decide which one you'd like, so adding the domain and protocol in the share command is the way to go.

**Comment by yahya31415** [comment]
I have the same problem. Passing the shared url as argument doesn't seem to do anything

**Comment by DanjBethel** [comment]
Was this ever fixed? Still broken.

**Comment by sschlein** [comment]
As described above, that's a feature not a bug. 

Please share your site via the full command if you are not using the convention:

`expose share https://your-local-domain.test`

**Comment by heychazza** [comment]
> As described above, that's a feature not a bug.
> 
> Please share your site via the full command if you are not using the convention:
> 
> `expose share https://your-local-domain.test`

Hi, as we've all mentioned unfortunately this does not work, running `herd share https://analyse.test` for example returns this:
```
Status                  Expose Pro 💎
Shared URL:             <folder>.test:80
Dashboard:              http://127.0.0.1:4040
Public HTTP:            http://x.sharedwithexpose.com
Public HTTPS:           https://x.sharedwithexpose.com
```

Which of course ends up in a 404.

**Comment by Sanabria** [comment]
I'm also running into the same issue even when using the full command. 

`herd share https://pucv.test`

The wrong local url gets shared: `pucv.test` gets turned into `macbook.test` which is my user folder which leads to a 404

```
You are not allowed to specify custom subdomains. Please upgrade to Expose Pro. Assigning a random subdomain instead.

Status:			Expose Free - Get custom subdomains and access to our performant global server network with Expose Pro! ➡️  https://expose.dev/get-pro
Shared URL:		macbook.test:80
Dashboard:		http://127.0.0.1:4040
Public HTTP:		http://6xob0mfsgk.sharedwithexpose.com
Public HTTPS:		https://6xob0mfsgk.sharedwithexpose.com
```

**Comment by jonjieviduya** [comment]
I am also getting the same issue. Any update with this issue?

**Comment by phpanos** [comment]
Still broken for me too. It wrongly sets the shared url based on folder name instead of the argument given.

**Comment by heychazza** [comment]
Hey @sschlein / @mpociot - are we going to get some form of fix for this? It's been an issue since February and nothings changed. You've mentioned that this is a "feature not a bug", and told us to use the full url, yet this doesn't work either hence why so many above have also chimed in.

Please fix this..

**Comment by sschlein** [comment]
Hey, you all seem to use `herd share` instead of `expose share`

**Comment by sheldonkotyk** [comment]
> Hey, you all seem to use `herd share` instead of `expose share`

It's in the documentation to do so with Herd.
https://herd.laravel.com/docs/macos/sites/sharing-sites

**Comment by ramonbakker1992** [comment]
im using herd, and both herd share and expose share give a 404

**Comment by sschlein** [comment]
A 404 from Herd or Expose?
