### ISSUE TITLE
[Bug]: Nginx won't start after update

### ISSUE THREAD

**Issue by Sindoweb** [beyondcode/herd-community#313]
### Operating system version

macOS Sonoma 14.2.1 (23C71)

### System architecture

Intel (x86)

### Herd Version

1.4.0

### Bug description

I updated Herd to 1.4.0 which resulted in Nginx not starting.
The following error is logged:

<img width="803" alt="image" src="https://github.com/beyondcode/herd-community/assets/1379550/98915707-4002-4361-8fc0-8ec26c76b28a">

### Steps to reproduce

Upgrade from Herd 1.3 to 1.4

**Comment by mpociot** [comment]
Does that file exist for you?

**Comment by mpociot** [comment]
Can you share a screenshot with the contents of the folder?

**Comment by mpociot** [comment]
The detect.js file should generate that for you. Did you restart Herd/force kill the services?

**Comment by mpociot** [comment]
Awesome! 🙂

**Comment by nam-co** [comment]
Same thing, I also had herd in a subfolder, re installed and it asked to move the app to the applications folder, all 👍
