### ISSUE TITLE
[Bug]: Herd says dnsmasq is running but Activity Monitor does not

### ISSUE THREAD

**Issue by ulfie22** [beyondcode/herd-community#314]
### Operating system version

macOS Sonoma 14.3

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.40

### Bug description

This is a new install of Herd (with Pro). I had a long working version of Valet which Herd claimed to upgrade. The only variation from standard in my Valet installation was that I had a custom TLD - which I changed back to .test using Valet commands. I turned off nginx and dnsmasq from my Homebrew installation by removing their Launch Agents and rebooting - `brew services list` shows they are not running. Under the Herd menu, it shows nginx and dnsmasq running - Activity Monitor shows nginx but not dnsmasq. Clicking on the log files reveals nothing - the windows open but they are empty. PHP is running under Activity Monitor. Going to any of my sites with `.test` in Chrome or Safari produces a ERR_CONNECTION_REFUSED or a BAD GATEWAY. Ideas on how to fix this?

### Steps to reproduce

Install Herd on my computer.

### Relevant log output

```shell
There is NO log output.
```

**Comment by mpociot** [comment]
Do you see it in your process list by running "ps aux | grep dnsmasq"?

As dnsmasq is running as root, it might not be visible immediately in your activity monitor.
You can also try running "sudo brew services list" to see the sudo status of your services. 

There's a good chance that dnsmasq is in that list.

**Comment by ulfie22** [comment]
Hi Marcel - thanks for the response. 

Yes - I do see `dnsmasq` in the process list from the command line:

```
➜  zmr git:(1664-add-data-for-row-ddi) ✗ ps aux | grep dnsmasq
nobody           10481   0.0  0.0 408646896    640   ??  S     4:54PM   0:00.05 /Applications/Herd.app/Contents/Resources/dnsmasq-arm64 --keep-in-foreground --conf-file=/Users/andy/Library/Application Support/Herd/config/dnsmasq/dnsmasq.conf
root             10479   0.0  0.0 408669648   2928   ??  S     4:54PM   0:00.01 sudo /Applications/Herd.app/Contents/Resources/dnsmasq-arm64 --keep-in-foreground --conf-file=/Users/andy/Library/Application Support/Herd/config/dnsmasq/dnsmasq.conf
andy             90157   0.0  0.0 408636112   1536 s000  S+   11:01AM   0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn --exclude-dir=.idea --exclude-dir=.tox dnsmasq
```
I am still getting the same results - all sites show No Connection or Bad Gateway. 

This what my `brew services list` looks like:

```
➜  zmr git:(1664-add-data-for-row-ddi) ✗ brew services list
Name        Status  User File
dnsmasq     none
emacs       none
meilisearch none
mysql       none
nginx       none
php         none
php@8.0     none
redis       started andy ~/Library/LaunchAgents/homebrew.mxcl.redis.plist
unbound     none
```

I've tried stopping everything and restarting (multiple times). I've cleaned out my Launch agents folder of anything that looks remotely conflicting. Valet was working perfectly - radical suggestions welcome.

**Comment by mpociot** [comment]
@ulfie22 What does `sudo brew services list` give you? It's different from running it without sudo

**Comment by ulfie22** [comment]
@mpociot Thanks again for your help. This is quite frustrating!

With Herd and Valet stopped:
```
➜  zmr git:(dev) sudo brew services list
Name        Status User File
dnsmasq     none
emacs       none
meilisearch none
mysql       none
nginx       none
php         none
php@8.0     none
redis       none   root
unbound     none
```

If I start Herd, I get all green lights in the menu bar accessory. The nginx and dnsmasq log files show empty. dnsmasq is running:

```
➜  zmr git:(dev) ps aux | grep dnsmasq
andy             86421   0.0  0.0 408636112   1536 s000  S+   10:28AM   0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn --exclude-dir=.idea --exclude-dir=.tox dnsmasq
nobody           86174   0.0  0.0 408690928   1360   ??  S    10:27AM   0:00.01 /Applications/Herd.app/Contents/Resources/dnsmasq-arm64 --keep-in-foreground --conf-file=/Users/andy/Library/Application Support/Herd/config/dnsmasq/dnsmasq.conf
root             86170   0.0  0.0 408686032   8032   ??  S    10:27AM   0:00.01 sudo /Applications/Herd.app/Contents/Resources/dnsmasq-arm64 --keep-in-foreground --conf-file=/Users/andy/Library/Application Support/Herd/config/dnsmasq/dnsmasq.conf

```

nginx is running:
```
➜  zmr git:(dev) ps aux | grep nginx
andy             86559   0.0  0.0 408626896   1392 s000  S+   10:30AM   0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn --exclude-dir=.idea --exclude-dir=.tox nginx
andy             86187   0.0  0.0 409621184    512   ??  S    10:27AM   0:00.00 nginx: worker process
andy             86186   0.0  0.0 409621184    512   ??  S    10:27AM   0:00.00 nginx: worker process
andy             86185   0.0  0.0 409621184    512   ??  S    10:27AM   0:00.00 nginx: worker process
andy             86184   0.0  0.0 409621184    512   ??  S    10:27AM   0:00.00 nginx: worker process
andy             86183   0.0  0.0 409621184    512   ??  S    10:27AM   0:00.00 nginx: worker process
andy             86182   0.0  0.0 409621184    512   ??  S    10:27AM   0:00.00 nginx: worker process
andy             86181   0.0  0.0 409621184    512   ??  S    10:27AM   0:00.00 nginx: worker process
andy             86180   0.0  0.0 409621184    512   ??  S    10:27AM   0:00.00 nginx: worker process
andy             86179   0.0  0.0 409621184    512   ??  S    10:27AM   0:00.00 nginx: worker process
andy             86178   0.0  0.0 409621184    512   ??  S    10:27AM   0:00.00 nginx: worker process
root             86175   0.0  0.0 409621184   2784   ??  S    10:27AM   0:00.01 nginx: master process /Applications/Herd.app/Contents/Resources/nginx-arm64 -g daemon off; -c /Users/andy/Library/Application Support/Herd/config/nginx/nginx.conf
root             86169   0.0  0.0 408825296   7152   ??  S    10:27AM   0:00.01 sudo /Applications/Herd.app/Contents/Resources/nginx-arm64 -g daemon off; -c /Users/andy/Library/Application Support/Herd/config/nginx/nginx.conf
```

php is running, though it seems like both the homebrew and Herd versions are being referenced:
```
➜  zmr git:(dev) ps aux | grep php
andy             99229  12.0  2.2 418887552 722176   ??  S    12:44PM 155:33.96 /Users/andy/Library/Application Support/JetBrains/Toolbox/apps/PhpStorm/ch-0/233.14015.96/PhpStorm 2023.3 EAP.app/Contents/MacOS/phpstorm
andy             82959   0.7  0.1 409075392  23072 s001  S+   10:16AM   0:03.22 /opt/homebrew/Cellar/php/8.3.2/bin/php artisan horizon:supervisor andys-mbpattlocalnet-Tpk7:supervisor-1 redis --workers-name=default --balance=auto --max-processes=10 --min-processes=1 --nice=0 --balance-cooldown=3 --balance-max-shift=1 --parent-id=82950 --auto-scaling-strategy=time --backoff=0 --max-time=0 --max-jobs=0 --memory=512 --queue=default,workout,follows,bookmarks,lowvolume --sleep=3 --timeout=3600 --tries=1 --rest=0
andy               563   0.2  0.2 409721072  56432   ??  S    12:45PM  12:16.64 php /Applications/Tinkerwell.app/Contents/Resources/phpactor/bin/phpactor language-server
andy             86601   0.2  0.0 408626896   1392 s000  S+   10:30AM   0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn --exclude-dir=.idea --exclude-dir=.tox php
andy              5114   0.0  0.0 409192128   7312 s001  S+   Mon04PM   0:52.94 php artisan horizon:watch
andy             86190   0.0  0.0 409423760    624   ??  S    10:27AM   0:00.00 php-fpm: pool herd
andy             86189   0.0  0.0 409432624    624   ??  S    10:27AM   0:00.00 php-fpm: pool herd
andy             86188   0.0  0.0 409432624    624   ??  S    10:27AM   0:00.00 php-fpm: pool herd
andy             86173   0.0  0.0 409423520  13600   ??  S    10:27AM   0:00.04 php-fpm: master process (/Users/andy/Library/Application Support/Herd/config/fpm/8.3-fpm-debug.conf)
andy             86172   0.0  0.0 409432384  13168   ??  S    10:27AM   0:00.03 php-fpm: master process (/Users/andy/Library/Application Support/Herd/config/fpm/8.3-fpm.conf)
andy             82983   0.0  0.1 409328320  23520 s001  S+   10:16AM   0:00.94 /opt/homebrew/Cellar/php/8.3.2/bin/php artisan horizon:work redis --name=default --supervisor=andys-mbpattlocalnet-Tpk7:supervisor-1 --backoff=0 --max-time=0 --max-jobs=0 --memory=512 --queue=bookmarks --sleep=3 --timeout=3600 --tries=1 --rest=0
andy             82984   0.0  0.1 409336512  23520 s001  S+   10:16AM   0:00.91 /opt/homebrew/Cellar/php/8.3.2/bin/php artisan horizon:work redis --name=default --supervisor=andys-mbpattlocalnet-Tpk7:supervisor-1 --backoff=0 --max-time=0 --max-jobs=0 --memory=512 --queue=lowvolume --sleep=3 --timeout=3600 --tries=1 --rest=0
andy             82981   0.0  0.1 409320128  23584 s001  S+   10:16AM   0:00.98 /opt/homebrew/Cellar/php/8.3.2/bin/php artisan horizon:work redis --name=default --supervisor=andys-mbpattlocalnet-Tpk7:supervisor-1 --backoff=0 --max-time=0 --max-jobs=0 --memory=512 --queue=workout --sleep=3 --timeout=3600 --tries=1 --rest=0
andy             82982   0.0  0.1 409205440  23536 s001  S+   10:16AM   0:00.91 /opt/homebrew/Cellar/php/8.3.2/bin/php artisan horizon:work redis --name=default --supervisor=andys-mbpattlocalnet-Tpk7:supervisor-1 --backoff=0 --max-time=0 --max-jobs=0 --memory=512 --queue=follows --sleep=3 --timeout=3600 --tries=1 --rest=0
andy             82980   0.0  0.1 409197248  23552 s001  S+   10:16AM   0:00.94 /opt/homebrew/Cellar/php/8.3.2/bin/php artisan horizon:work redis --name=default --supervisor=andys-mbpattlocalnet-Tpk7:supervisor-1 --backoff=0 --max-time=0 --max-jobs=0 --memory=512 --queue=default --sleep=3 --timeout=3600 --tries=1 --rest=0
andy             82950   0.0  0.1 409198272  22736 s001  S+   10:16AM   0:02.65 php artisan horizon
```

I guess that is a conflict that will need to be resolved, but I don't think that should impact nginx responding to requests at all.

![CleanShot 2024-02-07 at 10 36 36@2x](https://github.com/beyondcode/herd-community/assets/161110/98888fe8-3663-41cb-92c2-c10edd85c20d)

Just to be completely clear, the `sudo brew services list` looks the same with Herd running or not. Thank you again for your help.

**Comment by mpociot** [comment]
If you run `ping something.test` what does it resolve to?
If it successfully resolves to localhost, then DNSmasq is running as expected.

You should have a file `/etc/resolver/test` with this content: 

```
nameserver 127.0.0.1
```

Not sure if changing the TLD did mix some things up

**Comment by ulfie22** [comment]
@mpociot Thanks, Marcel. If I try to ping the site from the command line, it successfully pings:

```
➜  zmr git:(1668-profile-and-performance-blue-line-g) ping drex.test
PING drex.test (127.0.0.1): 56 data bytes
64 bytes from 127.0.0.1: icmp_seq=0 ttl=64 time=0.077 ms
64 bytes from 127.0.0.1: icmp_seq=1 ttl=64 time=0.135 ms
64 bytes from 127.0.0.1: icmp_seq=2 ttl=64 time=0.082 ms
```

The contents of `/etc/resolver/test` is as you say it should be. nginx continues to refuse to connect. is there possibly some other config file interfering? Thanks for your continued help - we'll sort it out!

**Comment by mpociot** [comment]
Thank you for your patience on this.

Alright - the ping at least means that DNSmasq is running properly.
Is there anything in your nginx-error.log in `~/Library/Application Support/Herd/Log`?
And just to make sure that it's not a browser caching issue (ran into this a bunch of times myself), could you try and curl any URL? Doesn't matter if it exists, as you should get a 404 otherwise.

Something like `curl http://foo.test`

**Comment by ulfie22** [comment]
@mpociot Thank you again, Marcel - much appreciated!

There are some entries in the nginx log file:

```2024/02/07 15:57:10 [error] 86180#2424707: *5 js: 
2024/02/07 15:57:10 [error] 86180#2424707: *5 js: default
2024/02/07 15:57:10 [crit] 86180#2424707: *5 connect() to unix:/Users/andy/Library/Application Support/Herd/herd.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/Users/andy/Library/Application Support/Herd/herd.sock:", host: "zmr.test"
```

Trying to curl a non-existent URL got this:
```
➜  zmr git:(1668-profile-and-performance-blue-line-g) ✗ curl http://foo.test
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.22.0</center>
</body>
</html>
```

which is the same error as my "real" local site (http://zmr.test) gets.

**Comment by mpociot** [comment]
Could you please run "herd use 8.3" via the CLI? Or whatever PHP version you're using. 
You can also click in the menu bar on the PHP version. This should recreate the socket for you.

**Comment by ulfie22** [comment]
@mpociot Thank you again.

OK - selecting a PHP version from the Herd menu (both 8.3 and 8.2 had been greyed out) did indeed select one. I didn't realize that I could `herd` from the command line so here are a few more data points. In the `settings` from the app, the `sites` tab does indeed show what I would expect given the directory I added in the `general` tab, but if I go to the terminal and `herd links`, no sites are displayed. So I manually linked it (as I would have with Valet) ... and it works in Safari!! but not in chrome, which could be a caching issue.

So ... the problem seems to be that Herd is not actually linking the sites in the directory I've selected. (Big relief here, though, that something is working!!!!)

**Comment by sschlein** [comment]
I am closing this issue because it's resolved on your end. In general, there seems to be a rare issue where a symlink isn't created but it's fixable by switching PHP versions once.

We're following up on the symlink issue at https://github.com/beyondcode/herd-community/issues/343
