### ISSUE TITLE
[Feature Request]:  Add Nova as an IDE choice

### ISSUE THREAD

**Issue by yabdab** [beyondcode/herd-community#319]
### Feature Description

Can Nova ( from Panic ) be added as a IDE choice in  General Settings?

### Is this feature valuable for other users as well and why?

Yes, many Mac users use Nova as their primary IDE

**Comment by sschlein** [comment]
Do you have any data on its market share? I'd assume that this is <1% and we currently try to make everything perfect for the 90% majority before we start adding options for rare setups.

So don't take this as a "no" forever but it's not on the near term roadmap and this is why I am closing this issue for now.

**Comment by yabdab** [comment]
Hmm, Nova from Panic ( formerly named Coda ) has been around and used by Mac developers for decades. One of the first native Mac IDE apps. Not sure of their marketshare, but very surprised you are unaware of them.

Anyway, thanks for considering.

**Comment by yabdab** [comment]
https://nova.app

**Comment by fschroiff** [comment]
At least make it possible to add custom IDEs.

**Comment by sschlein** [comment]
That's more complex that you think because every IDE has it's own URL scheme and some don't even have one to open specific files. It also is different depending on the feature of the app, so creating a custom way to add own IDEs is not on the roadmap at the moment.

**Comment by nam-co** [comment]
I think Marcel added nova once to another app, maybe is not too hard, Nova is such a nice app (different from all the vscode clones)

**Comment by yabdab** [comment]
Nova would be super easy to add. The URL scheme is `nova://full/path/to/file.php`
