### ISSUE TITLE
[Feature Request]: Add support for Fish terminals

### ISSUE THREAD

**Issue by morrislaptop** [beyondcode/herd-community#32]
### Feature Description

Current installation only modifies the $PATH for bash / zsh. Fish is also used by many developers and having it "just work" would be great. 

Alternatively, updating the docs would be a quick solution! 

`fish_add_path -U $HOME/Library/Application\ Support/Herd/bin/`

### Is this feature valuable for other users as well and why?

Yes, provides a better first impression when using Herd for Fish users.

**Comment by mpociot** [comment]
We'll add this to the documentation 👍
