### ISSUE TITLE
[Bug]: Acknowledgements link broken

### ISSUE THREAD

**Issue by jreviews** [beyondcode/herd-community#321]
### Operating system version

N/A

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.4.0

### Bug description

Acknowledgements page is broken https://herd.laravel.com/acknowledgements

### Steps to reproduce

Click the Acknowledgements button in the Herd app. It takes you here https://herd.laravel.com/acknowledgements which throws a 500 server error.

**Comment by sschlein** [comment]
Fixed!
