### ISSUE TITLE
[Bug]: Mailserver, Websocket Error

### ISSUE THREAD

**Issue by devajmeireles** [beyondcode/herd-community#322]
### Operating system version

macOS Sonoma, 14.2.1 (23C71)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.4.0

### PHP Version

PHP 8.2.15

### Bug description

![CleanShot 2024-02-06 at 10 29 54](https://github.com/beyondcode/herd-community/assets/60591772/f9b42e61-0650-4938-8df8-647d5e5b0899)

**Comment by sschlein** [comment]
Hey @devajmeireles, can you please change your dump server port in the settings? That should do the trick – Mails and Dumps actually share this API port and if it's in use, that fails.

**Comment by mpociot** [comment]
We just released Herd 1.4.1 which fixes this and provides a more descriptive error message
