### ISSUE TITLE
[Bug]: GUI won't load but process is running.

### ISSUE THREAD

**Issue by nathandaly** [beyondcode/herd-community#323]
### Operating system version

macOS Sonoma 14.2.1 (23C71)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.4.0

### PHP Version

PHP 8.3.1 (cli) (built: Dec 20 2023 12:44:38) (NTS)

### Bug description

> Error finding executable PHP. Quitting for safety.

My output:

<img width="760" alt="Screenshot 2024-02-06 at 14 39 23" src="https://github.com/beyondcode/herd-community/assets/33258212/d1cddc51-cf58-4a0d-acee-6d8a5f95dd07">

#### No php{version} folder in the bin directory specified by the `find-usable-php.php`.

<img width="784" alt="Screenshot 2024-02-06 at 14 55 35" src="https://github.com/beyondcode/herd-community/assets/33258212/040b9aa2-8bb6-4c2f-bd38-8e7be1c80725">

### Steps to reproduce

Fresh install.

### Relevant log output

> Error finding executable PHP. Quitting for safety.
> Provided output from find-usable-php.php:

**Comment by sschlein** [comment]
Which PHP versions did you install? You should be able to check that from the settings. If there was a problem by downloading at least one of them, that could be the issue.

**Comment by nathandaly** [comment]
> Which PHP versions did you install? You should be able to check that from the settings. If there was a problem by downloading at least one of them, that could be the issue.

Install from where sorry? If you mean from the HERD UI. It never open. I never get an icon in the bar but it claims it's running in activity monitor. 

I tried running it from the terminal and get that error so maybe my errors has a different cause.

<img width="1516" alt="Screenshot 2024-02-06 at 15 59 29" src="https://github.com/beyondcode/herd-community/assets/33258212/38f00ae8-f7b8-4f5a-a4cd-35c28ddc32d3">

**Comment by pauljohnston** [comment]
Same issue here (and same OS & architecture).

Herd stop/start works ok via terminal.

**Comment by pauljohnston** [comment]
> Did you have the previous version installed and it stopped working after the update or did you do a fresh install?

Fresh install.

**Comment by luanrodrigues** [comment]
same problem here, fresh install did not solve the problem

**Comment by mpociot** [comment]
Just to figure out if this is the same issue as #325 - does the application become "unresponsive" in the activity monitor after some time? Or does it simply not show up?

Did you see the onboarding screen at all, or did it simply not open in the first place?

Can you run the following command in your CLI and paste the results:

`defaults read de.beyondco.herd`

**Comment by pauljohnston** [comment]
Nothing appears abnormal about the application in activity monitor.
<img width="979" alt="Screenshot 2024-02-07 at 09 14 40" src="https://github.com/beyondcode/herd-community/assets/1242028/6fb27f62-f760-4d47-9d57-20925e56984f">
Didn't get any onboarding screens. Once the installation was complete, it simply just would not open the GUI. There did appear to be some installation issue as php and composer were not found, however they did respond after restarting Herd.

Result of `defaults read de.beyondco.herd`
> "NSWindow Frame Herd" = "256 132 1000 780 0 0 1512 944 ";
SUHasLaunchedBefore = 1;
SULastCheckTime = "2024-02-07 05:39:50 +0000";
SUUpdateGroupIdentifier = 1294334063;
activeVersion = "8.3";
"check_php_updates" = 1;
"device_id" = "1B260652-D496-4483-B114-94A4071E4E12";
"installed_8.2" = "8.2.15";
"installed_8.3" = "8.3.2";
"installed_internal_8.2" = 13;
"installed_internal_8.3" = 9;
"migrated_php_ini" = 1;

**Comment by mpociot** [comment]
So I debugged this with @nathandaly and (of course) everything worked perfectly when I joined his Tuple call.
Is anyone else still running into this issue? Would be great if someone could help me debug this, as I am unable to reproduce this

**Comment by pauljohnston** [comment]
Sure, do you want me to try anything first?

Incase it is relevant, I previously used valet (via global composer), however I did uninstall first.

**Comment by luanrodrigues** [comment]
In my case i realized that the icon was hidden. I just rearranged icons and thats it.

**Comment by pauljohnston** [comment]
🤦🏻‍♂️ Same here, can't believe I didn't realise that!

I was expecting it to open by default when it was first launched, so didn't even think it just wasn't showing.

**Comment by luanrodrigues** [comment]
Case solved! 😂😂😂
