### ISSUE TITLE
[Feature Request]: Ability to hide the Dock App icon

### ISSUE THREAD

**Issue by adrum** [beyondcode/herd-community#328]
### Feature Description

It would be nice to have the option to run Herd as a menu bar app only. Similar to DBngin's "Open in menubar" feature.

**Comment by sschlein** [comment]
Herd is a menubar only app – except the settings, dumps, mail or logs window is open. In this case, macOS UX patterns ask for a Dock icon to locate the window easily. 

So it's not a hard no, but we don't put this configuration on the near term roadmap for now :)

**Comment by drewjoh** [comment]
I'd like to put my vote here as well to make this optional, and potentially default to off (hide).

I don't remember Herd showing in the dock prior to v1.4... but now I see I can't remove it.  It clutters up my dock with something that I hardly ever need to access.

Some other apps that show this pattern of defaulting/being optional: DBngin, Flux, Rectangle app, etc.

I have a lot of other apps that run in my menu bar only -- if they were to all have a dock item, it would be overflowing.  :(

**Comment by sschlein** [comment]
Hi @drewjoh 

If there's no Herd window open, it doesn't have a dock icon 🤔

**Comment by adrum** [comment]
@drewjoh Good find! I could've sworn my Dock app icon was stuck like your video. I recently restarted my machine/Herd, and it appears to be removing the dock icon as intended. It automatically remove the dock Dock icon when opening and closing Mail, Dumps and Logs. My most recent attempt of opening and closing the settings window did remove the Dock icon. So it appears this is an intermittent bug.

Honestly, I think I encountered the bug you found, and just assumed that was the expected behavior so opened this issue without realizing it was a bug. 

When the bug is not happening, I think showing and hiding the dock icon as windows open and close is the perfect behavior.

**Comment by sowrensen** [comment]
Restarting did not fix it. The dock icon is stuck even after I closed the settings window.

**Comment by dicarsio** [comment]
@sschlein  Yeah, I'm also seeing the icon as well with all windows closed. There's definitely some bug there.

**Comment by timrspratt** [comment]
@sschlein same issue for me. On latest 1.8.0 version using Herd Pro. No windows are open but the dock icon remains
