### ISSUE TITLE
[Feature Request]: Option to use /public as root

### ISSUE THREAD

**Issue by cord** [beyondcode/herd-community#33]
### Feature Description

current behavior:

if exists the `public` directory will be automatically used as root - which is great for laravel projects.

wanted behavior:

For each site make configurable if `public` will be used as root - this will allow to use herd with non-laravel projects, which use a `public` directory for other purposes.

### Is this feature valuable for other users as well and why?

Yes - this will make Herd more versatile and a true replacement for the frustrating alternative like MAMP

**Comment by mpociot** [comment]
This is automatically handled by Valet and all of its individual drivers.

**Comment by cord** [comment]
thanks - can you point to the location of the valet driver directory used by herd?

`~/.config/valet/Drivers` seems not be loaded and a local driver (https://laravel.com/docs/10.x/valet#local-drivers) throws


Fatal error: Uncaught Error: Class "Valet\Drivers\LocalValetDriver" not found in /Applications/Herd.app/Contents/Resources/valet/cli/Valet/Drivers/ValetDriver.php:52 Stack trace: #0 /Applications/Herd.app/Contents/Resources/valet/server.php(54): Valet\Drivers\ValetDriver::assign('/Users/Shared/H...', 'test2', '/p2.php') #1 {main} thrown in /Applications/Herd.app/Contents/Resources/valet/cli/Valet/Drivers/ValetDriver.php on line 52

**Comment by dedfft** [comment]
Awesome that you guys pointed out about default public folder by Valet. Was very confused by that
