### ISSUE TITLE
Expected parameter 1 to be an array, null given in

### ISSUE THREAD

**Issue by anthubbard** [beyondcode/herd-community#330]
### Operating system version

macOS 14.2

### System architecture

Intel (x86)

### Herd Version

1.4.0

### PHP Version

PHP 7.4

### Bug description

Herd updated a day ago or so to 1.4.0 and now my Statamic v2 control panel is giving Javascript errors and I cannot login. I've lost a whole day trying to fix it and we're exceptionally behind and I really don't have time to have my local dev environment broken, would love some help it's driving me crazy.

There's 4 JS files in Statamic v2 CP and Herd is injecting code into them since the update - one file for example is http://mysite.test/index.php/_resources/cp/js/app.js?v=2.11.20 - it displays all the JS then at the bottom this happens:

```...("setFlashError",e,t)}}]),e}();Object.defineProperties(n.a.prototype,{$notify:{get:function(){return new a(this)}}})}},[797]);
//# sourceMappingURL=app.js.map<br />
<b>Warning</b>:  array_merge(): Expected parameter 1 to be an array, null given in <b>/Applications/Herd.app/Contents/Resources/valet/server.php</b> on line <b>118</b><br />```

I tried to go back a version by uninstalling Herd following the instructions on the Herd website but when I install the older version 1.3.1 and open Herd nginx won't run and gives an error stating `2024/02/07 16:01:05 [emerg] 4312#46039: unknown "herd_sock" variable` - so I can't use the older version

PLEASE HELP!!

### Steps to reproduce

_No response_

### Relevant log output

_No response_

**Comment by mpociot** [comment]
Does this file exist for you:
~/Library/Application Support/Herd/config/herd.json

If it does, what's the content of it?
If it does not - can you try and create the file containing an empty JSON object {}

**Comment by OctaneInteractive** [comment]
I'm seeing the same error.

cd ~/Library/Application\ Support/Herd/config
cat herd.json
null

**Comment by mpociot** [comment]
Are you also on 7.4?

Creating this file with an empty JSON object will fix the error for now

**Comment by OctaneInteractive** [comment]
Hi @mpociot, I'm using 7.4

**Comment by mpociot** [comment]
@OctaneInteractive Did creating an empty json file fix the issue for you?

**Comment by anthubbard** [comment]
Hi thanks for this help - I didn't even have a Herd folder in Lib App Support - adding that file and creating that directory has fixed it, thank you

**Comment by mpociot** [comment]
Thank you! I'll fix this in the next release so that this issue no longer occurs. In the meantime, creating the file yourself fixes it.

**Comment by jkudish** [comment]
For what it's worth, running Herd 1.4.0, I had the same error, and fixed it the same way.

In my case, the site I'm running where I noticed the error is php 8.3 but I do have another site running php 7.4 before.
