### ISSUE TITLE
[Bug]: Herd only works on the macOS account, that installed it

### ISSUE THREAD

**Issue by maxhoffmann** [beyondcode/herd-community#333]
### Operating system version

macOS Sonoma 14.3

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.4.0

### PHP Version

8.2

### Bug description

I’ve installed Herd using the work account on my Macbook, which works as expected. When I switch to my personal account and start Herd, it opens the app normally, but its functionality doesn’t work. The sites in Herd’s path for this account don’t get listed inside Herd’s UI and don’t work, when I try opening their URLs in the browser. Also when opening the Herd folder of this account with the terminal, php and composer cannot be found.

### Steps to reproduce

1. install Herd on one account on macOS
2. logout and login with a different account on that machine
3. start Herd and try creating/using a site inside that account’s Herd folder

**Comment by sschlein** [comment]
Herd needs admin rights and I assume that the personal account isn't allowed to use the app (or can't start the services) when they are installed by a different user.

Unfortunately, that's not something that we can fix easily but would need architetual changes (if it's possible at all) and this is why we won't support that in the near future and I am closing this issue for now. We internally consider this a feature request and see if we can implement it in the future.
