### ISSUE TITLE
[Bug]: "Node update available" alert on when everything is up to date

### ISSUE THREAD

**Issue by fylzero** [beyondcode/herd-community#335]
### Operating system version

macOS Sonoma 14.2.1 (23C71)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.4.0

### Bug description

The Herd menubar shows a red flag w/ exclamation icon and menu says "Node.js update available" but when I view the node tab, everything is installed/up-to-date.

**Comment by fylzero** [comment]
@mpociot Certainly!

<img width="529" alt="menu" src="https://github.com/beyondcode/herd-community/assets/3542501/9a134ffc-7941-4524-8b9d-2eea93693799">

<img width="916" alt="nvm-screenshot" src="https://github.com/beyondcode/herd-community/assets/3542501/563aaaca-437f-499d-9e83-96a526396869">

**Comment by fylzero** [comment]
@mpociot I swear I restarted this and everything, checked it several times... but the second I go to screenshot - the top option had an update button next to it now. Seems to be resolved. Oye.

**Comment by mpociot** [comment]
@fylzero Cool
We have to check every node version manually for updates, so it might take a couple of seconds before the update button appears.
