### ISSUE TITLE
[Bug]: Node version update notif not removed from mac toolbar

### ISSUE THREAD

**Issue by iruzevic** [beyondcode/herd-community#338]
### Operating system version

macOs Sonoma 14.2.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.4.0 Build 20

### PHP Version

any

### Bug description

After updating Node, you need to exit and restart the Herd app to remove the update notification in the Mac Toolbar.

![Screenshot 2024-02-08 at 09 17 31](https://github.com/beyondcode/herd-community/assets/23283324/12e1ee25-02d6-4de5-bd66-56c784e11711)

### Steps to reproduce

1. Get the node version update notification
2. update the node version
3. notification is not removed
4. exit the app and restart
5. notification is removed

https://github.com/beyondcode/herd-community/assets/23283324/ecf1748f-9df4-4dd3-a38d-f8c3315e2d3e

**Comment by msucevan** [comment]
I have the same issue on my machine @sschlein, I'm running on Intel.

I, also, have a problem with node (I think is more about my env) I get sh: node command not found in the sites tab and is of course not recognize npm.

**Comment by sschlein** [comment]
That seems to be something different and this should be fixed with the upcoming release :)

**Comment by msucevan** [comment]
I have the same issue mentioned in this topic, basically it shows that I have node updates, but I'm up to date. 

Also I have another issue, but I think is more about my environment and not related with Herd
