### ISSUE TITLE
[Bug]: Tinkerwell doesn't work with Herd PHP binaries

### ISSUE THREAD

**Issue by radermacher** [beyondcode/herd-community#34]
### Operating system version

macOS Ventura 13.4.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.0.8 (Build: 10)

### PHP Version

PHP 8.2.8 (cli) (built: Jul 24 2023 11:48:23) (NTS)

### Bug description

After _upgrading_ from Valet to Herd and set Herd PHP binary in Tinkwell, Tinkerwell isn't working anymore because of `Detected version: No valid PHP binary selected`.

![Screenshot 2023-07-24 15 30 22](https://github.com/beyondcode/herd-community/assets/1656843/c298a81e-d8f0-450d-8808-fdfea6bd7152)

### Steps to reproduce

Set`/Users/<USERNAME>/Library/Application Support/Herd/bin/php82` as PHP Binary in Tinkwell.

Installed PHP versions via Herd:
![Screenshot 2023-07-24 15 26 27](https://github.com/beyondcode/herd-community/assets/1656843/380ac1bc-0d24-4a00-93cc-83029e50948a)

PHP binaries in folder `/Users/<USERNAME>/Library/Application Support/Herd/bin`:
![Screenshot 2023-07-24 15 28 16](https://github.com/beyondcode/herd-community/assets/1656843/bbcc7578-06d6-40f6-bf18-3781a44a0731)

**Comment by mattwmatt1987** [comment]
Need a backslash before the space in Application Support

`/Users/[user]/Library/Application\ Support/Herd/bin/php`

**Comment by mpociot** [comment]
Which Tinkerwell version do you use? I don't see an issue locally. 
Alternatively you may just type "php82" in the file picker and it should work as well 👍

**Comment by radermacher** [comment]
> Need a backslash before the space in Application Support
> 
> `/Users/[user]/Library/Application\ Support/Herd/bin/php`

This does the trick! Thanks!

Unfortunately, Tinkerwell doesn't set the filepath _excaped_ when I use the select button to browse to the binaries. This was the reason for my issue.

**Comment by radermacher** [comment]
> Which Tinkerwell version do you use? I don't see an issue locally. Alternatively you may just type "php82" in the file picker and it should work as well 👍

Thanks @mpociot, when I manually type in php82 it works as well 🎉

I use the latest version of Tinkerwell: 3.28.0

Unfortunately, Tinkerwell doesn't set the filepath excaped when I use the select button to browse to the binaries. This was the reason for my issue.

**Comment by radermacher** [comment]
Thanks @mpociot and @mattwmatt1987 for your help to get Tinkwell working with Herd Php binaries 🙏

**Comment by ragulka** [comment]
I'm having a similar, but different issue.

I've set the php path in Tinkerwell to Herd (wrapped in double quotes), and Tinkerwell indicates that it _does_ recognize it:

<img width="814" alt="CleanShot 2023-07-27 at 11 45 48@2x" src="https://github.com/beyondcode/herd-community/assets/593267/9d2cad2f-25a3-4ed5-90f2-cb465a59417d">

However, when I try to execute any PHP code in Tinkerwell, I get the following error:

`/bin/sh: /Users/ragulka/Library/Application\ Support/Herd/bin/php: No such file or directory`

* There is no difference if I escape the space or wrap the path in double quotes.
* I can run php from my CLI just fine, and `which php` results in `/Users/ragulka/Library/Application Support/Herd/bin//php` (interestingly, there's double slash before the `php` at the end?)
* Tried `Stop all` and `Start all` from Herd, everything shows green.

Any ideas?

**Comment by mpociot** [comment]
Yup, in the meantime please just type `php` in the PHP binary settings in Tinkerwell. 
We'll publish a Tinkerwell bugfix release soon 👍
