### ISSUE TITLE
[Bug]: Not auto detecting xdebug breakpoints

### ISSUE THREAD

**Issue by iruzevic** [beyondcode/herd-community#341]
### Operating system version

macOs Sonoma 14.2.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.4.0 Build 20

### PHP Version

any

### Bug description

In the app, it states that the debugger can automatically detect PHPStorm breakpoints, but this is not working in the VsCode. In order for this to work, you need to change the herd.json config manually.

It is not a problem to change this manually but it would be really nice to have a toggle button in the app to turn this on/off rather than changing the herd.json manually

### Steps to reproduce

https://github.com/beyondcode/herd-community/assets/23283324/bd6698d0-e490-45f8-b674-e145d8bf3f86

**Comment by iruzevic** [comment]
It is ok with me to have this debug key set to true and don't change it, but it took me a while to figure out why it is not working as herd.json by default sets this value to false, and there is no documentation explaining that this needs to be turned on manually in order for xdebug to work.

**Comment by sschlein** [comment]
Hey @iruzevic 

It's actually in the docs at https://herd.laravel.com/docs/1/herd-pro/xdebug#setup-with-browser-extensions

Still no need to open the herd.json at all 🙂
