### ISSUE TITLE
[Bug]: Empty Sites, Sites not opening and other issues

### ISSUE THREAD

**Issue by mkwsra** [beyondcode/herd-community#342]
### Operating system version

macOS Sonoma 14.3 (23D56)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.4.0 (Build: 20)

### PHP Version

PHP 8.2.4 (cli) (built: Mar 16 2023 16:13:06) (NTS)

### Bug description

Sites are empty, and parking and unparking is the same. 

Now I know there are other issues for this however, I'm opening this issue because I have other very odd behaviours also like:
DNSMasq is simply not working also, and I ended up having some of my local sites working and others not? it was working just fine before version Herd 1.4.0.

And I have issue with Laravel projects after I deleted vendor and composer.lock, I'm not sure if it's related tough so I'm not stressing it out, but it's about resolving all Facades, Cache, DB, and others. All of them are not working.

**Comment by mpociot** [comment]
Could you try and force stop/force start all services?
What does "some sites are working others not" mean?

What is the error message that you get in the browser?
Whats the content of your nginx-error.log file? (~/Library/Application Support/Herd/Logs)

**Comment by mkwsra** [comment]
Thanks for the tips, so for forcing the services this kind of solved one of my issues, but let me explain a bit more.

So for some websites I'm getting "502 Bad Gateway" however they were working just fine. And to help you a bit more explain the issue please take a look at this screenshot of Herd menu (DNSMasq light isn't green but some websites are working just fine others are not even presented).

![CleanShot 2024-02-08 at 17 27 00@2x](https://github.com/beyondcode/herd-community/assets/1743919/c8cc4f34-2b4e-4f6e-ba15-1daa032bbe0b)

![CleanShot 2024-02-08 at 17 28 28@2x](https://github.com/beyondcode/herd-community/assets/1743919/af69eed7-7807-40a4-913c-02961866647f)


And here is a portion of `nginx-error.log` 
```bash
2024/02/08 17:08:34 [error] 1761#20653: *331 js: 
2024/02/08 17:08:34 [error] 1761#20653: *331 js: default
2024/02/08 17:08:34 [error] 1770#20665: *325 js: 
2024/02/08 17:08:34 [error] 1770#20665: *325 js: default
2024/02/08 17:08:34 [error] 1761#20653: *331 js: 
2024/02/08 17:08:34 [error] 1761#20653: *331 js: default
2024/02/08 17:26:55 [error] 1770#20665: *346 js: 
2024/02/08 17:26:55 [error] 1770#20665: *346 js: default
2024/02/08 17:26:55 [error] 1770#20665: *346 connect() to unix:/Users/mkwsra/Library/Application Support/Herd/herd.sock failed (61: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/Users/mkwsra/Library/Application Support/Herd/herd.sock:", host: "filament-demo.test"
2024/02/08 17:26:55 [error] 1770#20665: *346 js: 
2024/02/08 17:26:55 [error] 1770#20665: *346 js: default
2024/02/08 17:26:55 [error] 1770#20665: *346 connect() to unix:/Users/mkwsra/Library/Application Support/Herd/herd.sock failed (61: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://unix:/Users/mkwsra/Library/Application Support/Herd/herd.sock:", host: "filament-demo.test", referrer: "http://filament-demo.test/"
2024/02/08 17:26:56 [error] 1770#20665: *346 js: 
2024/02/08 17:26:56 [error] 1770#20665: *346 js: default
2024/02/08 17:26:56 [error] 1770#20665: *346 connect() to unix:/Users/mkwsra/Library/Application Support/Herd/herd.sock failed (61: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/Users/mkwsra/Library/Application Support/Herd/herd.sock:", host: "filament-demo.test"
2024/02/08 17:26:56 [error] 1770#20665: *346 js: 
2024/02/08 17:26:56 [error] 1770#20665: *346 js: default
2024/02/08 17:26:56 [error] 1770#20665: *346 connect() to unix:/Users/mkwsra/Library/Application Support/Herd/herd.sock failed (61: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://unix:/Users/mkwsra/Library/Application Support/Herd/herd.sock:", host: "filament-demo.test", referrer: "http://filament-demo.test/"

```

**Comment by mkwsra** [comment]
And I know you guys are working on solving this and it's already reported, but just so you know I parked my sites folder again but unfortunately it's not working, and I have all versions installed unlike the other fellows I can't see any of my sites for now.
![Uploading CleanShot 2024-02-08 at 17.32.55@2x.png…]()

**Comment by mpociot** [comment]
Could you please click on a PHP version to mark it as "used"? This should fix the bad gateway issue 👍 

Regarding DNSMasq: It's probably still running from Valet, which is why you don't see it as "green" in the list of services.
Let's take care of getting rid of the 502 first :)

**Comment by mkwsra** [comment]
Wow, indeed, this solved my issue, I didn't even notice it! thanks a lot for this, it was driving me crazing because some websites were just fine 😅!!

![CleanShot 2024-02-08 at 17 40 12@2x](https://github.com/beyondcode/herd-community/assets/1743919/93f57b03-8cfa-4620-8bf0-3043b3ad7d87)

**Comment by mpociot** [comment]
Great!
To get rid of the DNSmasq issue, you should be able to manually stop it via:

`sudo brew services stop dnsmasq`

And then just manually toggle via the Herd menubar.

Regarding the sites list, this is related to the fish shell, which we're looking into in a separate issue 👍

**Comment by mkwsra** [comment]
Thanks, thanks & thanks!  ❤️

![CleanShot 2024-02-08 at 17 50 49@2x](https://github.com/beyondcode/herd-community/assets/1743919/ce0ed501-67c0-49b0-8f8a-d9915dd5d28c)
