### ISSUE TITLE
[Bug]: herd-debug.sock broken symlink resulting in gateway error

### ISSUE THREAD

**Issue by mattbartel** [beyondcode/herd-community#343]
### Operating system version

macOS 14.3

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.4

### PHP Version

8.2.15

### Bug description

After updating to Herd 1.4, attempting to load a previously functional site resulted in a 502 bad gateway. When checking the nginx error logs, I got the following error:

`[crit] 13635#62188: *1 connect() to unix:/Users/[user]/Library/Application Support/Herd/herd-debug.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: [local domain].test, request: "GET / HTTP/2.0", upstream: "fastcgi://unix:/Users/[user]/Library/Application Support/Herd/herd-debug.sock:", host: "[local domain].test"`

The Herd settings correctly specified that the site was using php 8.2. 

### Steps to reproduce

Other than installing Herd 1.4, I can't say what exactly will reproduce. 

The herd-debug.sock does exist as a symlink but it was pointing to herd-debugnone.sock instead of herd-debug82.sock. I was able to fix the issue by following the same symlink pattern as the herd.sock -> herd82.sock symlink:

`ln -s herd-debug82.sock herd-debug.sock`

After updating the symlink, all sites running php8.2 loaded fine.

**Comment by mpociot** [comment]
The symlink should be automatically created after activating Herd Pro and/or by switching to a PHP version.
This can either be done by clicking on the PHP version in the menubar, or by running `herd use 8.2` via CLI.

**Comment by mattbartel** [comment]
> The symlink should be automatically created after activating Herd Pro and/or by switching to a PHP version.
> 
> This can either be done by clicking on the PHP version in the menubar, or by running `herd use 8.2` via CLI.

FYI, I had activated 8.2 via the GUI but it did not recreate the symlink. Even after activating 8.2 (the only version I have installed at the moment), the symlink was still directing to the missing "none" file.

**Comment by mpociot** [comment]
Were you able to solve this issue then? Or should I re-open it?
I'm not really sure where the `none` is coming from. You could also delete the symlink manually - running `herd use 8.2` should re-set it.

**Comment by craigvc** [comment]
I have exactly same issue - i just bought pro 
ln -s herd-debug82.sock herd-debug.sock this fixes it in the shorttterm

**Comment by jwohlfert23** [comment]
@mpociot I was just trying to provide a little more info to help you identify the issue. Thank you for fixing! Herd is a game-changer.

**Comment by garyross** [comment]
I got the same error on a new Herd install
`2024/03/07 11:14:47 [crit] 31196#173494: *1 connect() to unix:/Users/xx/Library/Application Support/Herd/herd.sock failed`

When I ran 
`herd use 8.2 `
the issue went away but I don't think this is the issue because the `use 8.2` is a global setting right?

After the fix I removed the aliases and then flipped the site to 8.3, and then back again and it worked. I think what's happening is that when perhaps you have only one version of PHP then it creates a herd82.sock but then tries to connect via a `herd.sock`

 After all if a site is dependent on a symbolic link to connect to the sock what happens if one of your sites is using 8.2 and one is 8.3. They can't both be using the alias.

**Comment by Enaah** [comment]
> I got the same error on a new Herd install `2024/03/07 11:14:47 [crit] 31196#173494: *1 connect() to unix:/Users/xx/Library/Application Support/Herd/herd.sock failed`
> 
> When I ran `herd use 8.2 ` the issue went away but I don't think this is the issue because the `use 8.2` is a global setting right?
> 
> After the fix I removed the aliases and then flipped the site to 8.3, and then back again and it worked. I think what's happening is that when perhaps you have only one version of PHP then it creates a herd82.sock but then tries to connect via a `herd.sock`
> 
> After all if a site is dependent on a symbolic link to connect to the sock what happens if one of your sites is using 8.2 and one is 8.3. They can't both be using the alias.

Thanks, switching the PHP Version (and back) helped my broken installation aswell.
