### ISSUE TITLE
[Bug]: Nginx does not start - Cannot find module 

### ISSUE THREAD

**Issue by piperone** [beyondcode/herd-community#344]
### Operating system version

macOS Sonoma 14.1.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.4.0 (Build: 20)

### PHP Version

PHP 8.2.15

### Bug description

Nginx does not start. Reboot tried and did not help.

### Relevant log output

```shell
*timestamp* [emerg] 4784#30754 SyntaxError: Cannot find module "/Applications/Herd.app/Contents/Resources/config/pro/njs/detect.js" in /Users/***/Library/Application Support/Herd/config/nginx/:1
```

**Comment by mpociot** [comment]
Did you move your Herd app in a subfolder in your /Applications directory?
Right now it needs to in the `/Applications` folder directly.

**Comment by piperone** [comment]
I just realized this. I keep all my development-related apps in its own folder in Applications, so that's why it's failing. Moving the app to /Applications fixed this.

I would urge you to consider a solution where the path isn't hardcoded so that users can decide on their own install location in the future.

Thanks!

**Comment by mpociot** [comment]
Yup, I'll modify this to auto detect the location. I haven't considered the usage of sub-folders 😅
