### ISSUE TITLE
[Bug]: openssl extension not available to all php functions

### ISSUE THREAD

**Issue by daronspence** [beyondcode/herd-community#35]
### Operating system version

13.4.1 (22F82)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.0.8

### PHP Version

8.2.7

### Bug description

Trying to work with [this package](https://github.com/laravel-notification-channels/webpush) and one of the steps to install is to generate a public/private key. The package includes an aritsan command to generate they key pair, but it fails when using the Herd php binary.

When digging into the source files, the failing call is trying to use the `openssl_pkey_new()` function but it is returning `false`. You can read more about the expected output here: https://www.php.net/manual/en/function.openssl-pkey-new.php

### Steps to reproduce

- [ ] Add the https://github.com/laravel-notification-channels/webpush package to a new project
- [ ] Run the `path/to/herd/php artisan webpush:vapid` command
- [ ] Assert you get an exception similar to https://github.com/laravel-notification-channels/webpush/issues/192

### Relevant log output

```sh
 Unable to create the key

  at vendor/web-token/jwt-core/Util/ECKey.php:99
     95▕             'private_key_type' => OPENSSL_KEYTYPE_EC,
     96▕         ]);
     97▕         // var_dump([$key, self::getOpensslCurveName($curve), OPENSSL_KEYTYPE_EC]);
     98▕         if ($key === false) {
  ➜  99▕             throw new RuntimeException('Unable to create the key');
    100▕         }
    101▕         $result = openssl_pkey_export($key, $out);
    102▕         if ($result === false) {
    103▕             throw new RuntimeException('Unable to create the key');

      +17 vendor frames
  18  artisan:35
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```

**Comment by crazywhalecc** [comment]
If you want to use full openssl functions, add `export OPENSSL_CONF=/System/Library/OpenSSL/openssl.cnf` to your `~/.zshrc`.

**Comment by mpociot** [comment]
@crazywhalecc thanks! I'll also fix this in the upcoming Herd version!

**Comment by mpociot** [comment]
The new PHP builds are rolling out 🚂
