### ISSUE TITLE
[Feature Request]: PHP7.0 - PHP7.3 Support

### ISSUE THREAD

**Issue by chris-ware** [beyondcode/herd-community#36]
### Feature Description

From what I've seen, Herd only supports PHP 7.4+. This makes complete sense in terms of keeping with the supported versions of PHP, but for some, this will be a reason not to migrate from Valet, as Valet 4 still supports PHP 7.0+, allowing for older legacy sites to be slowly migrated to newer versions.

### Is this feature valuable for other users as well and why?

Yes, it would be very valuable for anyone who works in an agency where customers are very slow to approve software updates, if they haven't been well informed of the benefits of them.

**Comment by mpociot** [comment]
Unfortunately, this is not possible right now, due to the way we compile PHP into a static binary.
