### ISSUE TITLE
[Bug]: List of websites is empty in the ui

### ISSUE THREAD

**Issue by Skullbock** [beyondcode/herd-community#37]
### Operating system version

Macos Ventura 13.3

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.0.8

### PHP Version

php 8.2.8

### Bug description

In the ui, the list of sites is empty, even with 2+ paths registered.
Moreover, the list of sites dumped from the `herd parked` command shows 20 sites.

**Comment by mattwmatt1987** [comment]
Make sure you have not folders that only contain numbers. I had the same issue. Already reported it and confirmed via email.

May be other scenarios too. 
If that is not the case, i'd recommend adding in a few sites at a time to a new directory to find the culprit.

**Comment by jason-beach** [comment]
I had all my sites show up initially but they all disappeared when I tried to secure one of them by click on the secure button for a site. Now the entire list of sites is gone and won't come back.

**Comment by Skullbock** [comment]
Confirmed! Removing the sites with only numbers fixed it
