### ISSUE TITLE
[Bug]: dnsmasq: failed to create listening socket for 127.0.0.1: Address already in use

### ISSUE THREAD

**Issue by jason-beach** [beyondcode/herd-community#38]
### Operating system version

macOS Ventura 13.4.1

### System architecture

Intel (x86)

### Herd Version

1.0.8 Build 10

### Bug description

Hello,

Fresh install of Herd and everything is looking good except the DNSMasq is not green. The error report shows: dnsmasq: failed to create listening socket for 127.0.0.1: Address already in use

I've stopped all brew services, I've done valet stop even through I've not used it in a couple years. I've stopped all containers in docker for mac and quit docker. I've used lando for my local env setup and was excited to use Herd going forward but just can't seem to get DNSMasq working as it should for Herd. Any suggesstions?

### Relevant log output

```shell
dnsmasq: failed to create listening socket for 127.0.0.1: Address already in use
```
I've done sudo ps -ef | grep dnsmasq which outputs:
```shell
-2 24304     1   0 12:06PM ??         0:00.01 /usr/local/opt/dnsmasq/sbin/dnsmasq --keep-in-foreground -C /usr/local/etc/dnsmasq.conf -7 /usr/local/etc/dnsmasq.d,*.conf
  501 27472   730   0 12:09PM ttys000    0:00.00 grep dnsmasq
  ```

 I killed those but they start back up with different PID's

**Comment by mpociot** [comment]
Seems like that's still a brew Service restarting dnsmasq. 
What does: brew services stop dnsmasq 
Give you?

**Comment by jason-beach** [comment]
That command doesn't give me any output but when listing services this is what I see:

```shell
brew services list
Name          Status  User Plist
dnsmasq       stopped
mysql@5.7     stopped
nginx         stopped
php           stopped
php@7.4       stopped
postgresql    stopped
postgresql@11 stopped
redis         stopped
```

**Comment by jason-beach** [comment]
I actually got this figured out. Brew was always confusing to me with the status and using sudo.. but when I used sudo brew services stop dnsmasq it actually stopped dnsmasq this time and heard is all green. Using sudo was the key when stopping that brew service specifically.

**Comment by mpociot** [comment]
Ahh right - that bit me a couple of times as well. Glad you figured it out!
