### ISSUE TITLE
[Bug]: Herd.app is generating PHP error on all PHP 7.4 sites

### ISSUE THREAD

**Issue by GasparSukk** [beyondcode/herd-community#383]
### Operating system version

macOS Sonoma 14.2.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.4.0 (20)

### PHP Version

PHP 7.4.33

### Bug description

Herd.app is generating PHP error then using PHP 7.4

`Warning: array_merge(): Expected parameter 1 to be an array, null given in /Applications/Herd.app/Contents/Resources/valet/server.php on line 118!`

**Comment by sschlein** [comment]
Hey @GasparSukk 

This will be fixed in the next version but in the meantime, please create a herd.json file in your Herd config directory at `/Users/YOUR-USERNAME/Library/Application Support/Herd/config` and with empty json object `{}` and restart Herd

**Comment by GasparSukk** [comment]
Well. This fix get's overwritted by Herd itself. How to fx this fix?
