### ISSUE TITLE
[Bug]: after upgrading from 1.3.x* to 1.4.0, Nginx does not launch

### ISSUE THREAD

**Issue by welt** [beyondcode/herd-community#384]
### Operating system version

macOS Ventura 13.6.4 (22G513)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.4.0

### PHP Version

PHP 8.2.15 (cli) (built: Jan 19 2024 00:15:08) (NTS)

### Bug description

Herd does not launch Nginx after upgrade to Herd 1.4.0 when app is in local Applications directory. This directory location for Herd was previously working under 1.3.x.

Tried restarting, rebooting, `herd restart`. Confirmed with uninstall as per support page, re-install and repeated previous steps.

### Steps to reproduce

+ On upgrade from Herd 1.3.x to Herd 1.4.0 in 
`/Users/<username>/Applications/`
or on clean install to that same local Applications directory

+ Skip activation of Herd Pro, install PHP 8.2, set activate on start

+ Observe no error messages 

+ Observe 'Nginx' menu item is not highlighted and Nginx is not running

+ click 'Stop all' then 'Start all' from Herd menu.

+ Observe no output

+ Observe 'Nginx' menu item is not highlighted and Nginx is not running

+ in a terminal session, run `herd restart`

+ Observe nginx, dnsmasq and PHP all report to have re-started OK

+ Observe 'Nginx' menu item is not highlighted and Nginx is not running

+ click on Nginx log viewer icon in Herd menu

+ Observe 'can not find module' error message

Possible cause:

Herd.app/Contents/Resources/config/pro/nginx/debug.conf contains a hard-coded path to "/Applications"

on line 2:
js_import "/Applications/Herd.app/Contents/Resources/config/pro/njs/detect.js";

### Relevant log output

```shell
`...SyntaxError: cannot find module "/Applications/Herd.app/Contents/Resources/config/pro/njs/detect.js" in /Users/<username>/Library/Application Support/Herd/config/nginx/:1`
```

**Comment by mpociot** [comment]
Hey!

This happens when you have your Herd.app in a subfolder within the `/Applications` directory.
Right now this is not supported.
If you move the application, the file can be found :)

**Comment by welt** [comment]
oh OK - thanks for quick reply 👍 it was working under 1.3 - is that right?

**Comment by mpociot** [comment]
Yeah that's right. This will also be fixed in the next version 👍
