### ISSUE TITLE
[Bug]: Disable Node feature

### ISSUE THREAD

**Issue by KevinBatdorf** [beyondcode/herd-community#388]
### Operating system version

macOS Sonoma 14.2

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.4.0 B20

### Bug description

Herd force adds some nvm config to the path which overrides my current node version manager ([fnm](https://github.com/Schniz/fnm)). 

Since it's auto injected, I have to close Herd or just use whatever Herd chose (I guess it uses Node 16)

I don't have nvm set up or anything in Herd

![CleanShot 2024-02-09 at 20 00 45@2x](https://github.com/beyondcode/herd-community/assets/1478421/862449b0-800c-4094-aa01-2cd3b4413950)

I'm sure you know already, but here is what's added

```sh
# Herd injected NVM configuration
export NVM_DIR="/Users/kevin/Library/Application Support/Herd/config/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

[[ -f "/Applications/Herd.app/Contents/Resources/config/shell/zshrc.zsh" ]] && builtin source "/Applications/Herd.app/Contents/Resources/config/shell/zshrc.zsh"
```

**Comment by davideprevosto** [comment]
I am using Volta and I run into the same issue. I pinned node@20 with Volta, but nvm is serving the @18 version. I would like to turn off the Node section.

**Comment by eleftrik** [comment]
I totally agree with @KevinBatdorf. Herd should NOT interfere with `.zshrc` and overwrite configuration.

**Comment by eleftrik** [comment]
Thank you @mpociot for your quick feedback! I appreciate 👍

**Comment by djmtype** [comment]
I was working along on a Node-based project; nothing to do with Herd; then all of a sudden my CLI tells me my node version is too old to compile my project. Only to find out using `node -v` and `which node` that Herd has decided to foil with my zshrc settings. WTF?! Not cool.

**Comment by hamstu** [comment]
Yeah, also agree this messed up my workflow in another project, and it took a while to realize Herd had changed my Node binary. I think this is a nifty feature, but it should have been opt-in.

**Comment by murat-aksoy** [comment]
Configuring Nodejs should be optional.

**Comment by razaanstha** [comment]
Yeah, please make the node version management thing optional.

**Comment by jplhomer** [comment]
On a similar note, would love to not have the update red bubble for the Node update management in the icon when I've explicitly disabled "Notify me about Node.js updates." Thought about opening a separate issue but I figured this would probably be tackled similarly 😅 

<img width="265" alt="Screenshot 2024-02-21 at 8 43 01 AM" src="https://github.com/beyondcode/herd-community/assets/848147/946afe6c-76cd-4797-9a90-7501aa260cb2">

**Comment by carusog** [comment]
Please, make Node version management optional. I see your point, but for those that already manage Node versions, it's really really annoying.
I am personally using Volta, and I've got no alert, or notification that Herd was going to override my settings for Node, when it's supposed to be a PHP vm.

**Comment by brysem** [comment]
Really love the tool but a feature to disable NVM would be very useful. We use volta internally. The work around now is to manually remove the injected NVM configuration in our profiles.

**Comment by JoshTristram** [comment]
Jumping on here to add my support for allowing Node to be disabled. I cd'ed into a project yesterday, and then Node *just* started installing.
