### ISSUE TITLE
[Feature Request]: add xdebug extension for code coverage

### ISSUE THREAD

**Issue by alfonsobries** [beyondcode/herd-community#39]
### Feature Description

Currently if you try to run pest with `--coverage` option you see this error

```
ERROR  Code coverage driver not available. Did you install Xdebug or PCOV?
```

### Is this feature valuable for other users as well and why?

Use xdebug in general and for code coverage is most likely a common use case for a lot of users

**Comment by alfonsobries** [comment]
My bad seems that it was already enabled, what its not enabled is debug mode, in case someone have the same issue you just need to add 

`xdebug.mode=coverage`

on the herd php.ini file

**Comment by ronfuller** [comment]
@alfonsobries I tried the same setting but since xdebug is not installed with Herd, how are you getting this to work?
