### ISSUE TITLE
[Bug]: Weird menu options

### ISSUE THREAD

**Issue by blastedcode** [beyondcode/herd-community#392]
### Operating system version

macOS Sonoma 14.2.1

### System architecture

Intel (x86)

### Herd Version

1.4.0

### Bug description

![Screenshot 2024-02-11 at 09 11 15](https://github.com/beyondcode/herd-community/assets/11173651/0a4e938b-a672-4d44-9647-9f3376488c6f)

When I go to any option that opens the dialog box, I get lots of buttons in my title with the word custom.

### Steps to reproduce

Open any dialog box

**Comment by mpociot** [comment]
What do you mean with Dialog Box? Like the "About Herd" entry?

**Comment by blastedcode** [comment]
No, its anything, if I press anything like, "settings", "dumps", "mail" 

BTW, it's not stopping me from using it. I just noticed it as it was not there in previous version. I have the pro version if that matters.

**Comment by blastedcode** [comment]
So restarting Herd fixes it.

I have been able to replicate it by doing the following:

if you edit php code and put in dd('test');

This brings up the first custom button.

If you close Herd debug window down and a while later open it up again you get and additional custom button.

**Comment by sschlein** [comment]
It's more than opening the dumps window seems to adding that custom menu item – I can reproduce the issue and we'll look into that!

**Comment by mpociot** [comment]
We just released Herd 1.4.1 which fixes this
