### ISSUE TITLE
[Bug]: Mail never shown

### ISSUE THREAD

**Issue by novocent** [beyondcode/herd-community#393]
### Operating system version

macOS Sonoma 14.2.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.4.0 (Build 20)

### PHP Version

PHP 8.3

### Bug description

After upgrading to Pro the mail server starts, the mail log shows email being sent, but no email is ever displayed. 
<img width="877" alt="Screenshot 2024-02-12 at 2 10 27 PM" src="https://github.com/beyondcode/herd-community/assets/3177296/01faafc6-ef80-483d-9c33-f2b4a1603cb8">

### Relevant log output

```shell
Herd mail Log: 
Port 2525 is free. Starting mailserver.
Mailserver listening on port 2525
Test Email from test@test.com (Mailbox: Testmail)
Sending mail to Herd
```

**Comment by mpociot** [comment]
Which application / framework do you use to send the mail?

**Comment by novocent** [comment]
Laravel v10.43.0
`Mail::raw('Hello World!', function($msg) {$msg->to('test@example.com')->subject('Test Email'); });`

**Comment by mechelon** [comment]
This will be fixed in the upcoming release.
Until then, you should be able to send HTML/Markdown mails, for example
```php
Mail::to("herd@example.org")->send(new MyNewMail());
```
