### ISSUE TITLE
[Bug]: artisan not loading php.ini

### ISSUE THREAD

**Issue by fabiowallner** [beyondcode/herd-community#397]
### Operating system version

macOS Sonoma 14.3.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.4.0 (Build: 20)

### PHP Version

PHP 8.2.15

### Bug description

The respective ini for 8.2 is loaded in the terminal:
![Screenshot 2024-02-13 at 12 01 54](https://github.com/beyondcode/herd-community/assets/18308739/a01833a1-e357-4a03-9a48-91480121257f)

But when I start php artisan serve it is not loaded there:
![Screenshot 2024-02-13 at 12 03 37](https://github.com/beyondcode/herd-community/assets/18308739/a92f542a-a8d5-4813-929b-e5ecae4531b6)

I restarted my mac multiple times, killed all herd processes, etc but the error persists.

**Comment by sschlein** [comment]
@fabiowallner With Herd, you don't need `php artisan serve` but can go to your foldername.test

**Comment by fabiowallner** [comment]
I would still like artisan serve to recognize my php.ini. 🤔
For example I cannot set mails locally because the cacert field is empty because it is not reading it from the .ini file.

**Comment by mpociot** [comment]
To give some behind-the-scenes details:
We check for a `HERD_PHP_82_INI_SCAN_DIR` environment variable, which instructs PHP to load the ini file from that directory.

When running `php artisan serve`, Laravel internally spawns a new "php" command, which does not include that environment variable.
The list of passthrough environment variables can be found here: https://github.com/laravel/framework/blob/52305ed8a857b4e0e729c68455d60a608d1a75d3/src/Illuminate/Foundation/Console/ServeCommand.php#L58-L69

You should be able to manually fix this by appending environment variables to it in your `AppServiceProvider`:

```php
\Illuminate\Foundation\Console\ServeCommand::$passthroughVariables[] = 'HERD_PHP_81_INI_SCAN_DIR';
\Illuminate\Foundation\Console\ServeCommand::$passthroughVariables[] = 'HERD_PHP_82_INI_SCAN_DIR';
\Illuminate\Foundation\Console\ServeCommand::$passthroughVariables[] = 'HERD_PHP_83_INI_SCAN_DIR';
```
