### ISSUE TITLE
[Bug]: `null` in config/herd.json causes warning error

### ISSUE THREAD

**Issue by jacksleight** [beyondcode/herd-community#398]
### Operating system version

macOS Ventura 13.3.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.4.0 (Build: 20)

### Bug description

I'm seeing this warning in page responses:

> Warning: array_merge(): Expected parameter 1 to be an array, null given in /Applications/Herd.app/Contents/Resources/valet/server.php on line 118

It looks like somehow the `config/herd.json` has ended up with a `null` value. Changing it to `{}` fixes it.

I've never touched `herd.json` myself so I'm guessing there must be something internally that's setting it to `null`.

**Comment by mpociot** [comment]
This was already fixed in Herd 1.4.1 which was released a couple of minutes ago :)
