### ISSUE TITLE
[Bug]: After update to 1.4.1, all sites (exp. one) response with: 502 bad gateway

### ISSUE THREAD

**Issue by chrbox** [beyondcode/herd-community#399]
### Operating system version

macOS Sonoma 14.3.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.4.1(Build 21)

### Bug description

After update all sites response with 502 bad gateway, only one site is working as expected.

**Comment by mpociot** [comment]
Can you force stop/force start the services using the dropdown? Simply press the option key to see the force option. 
Sometimes a stray service could be still around when the app gets killed

**Comment by chrbox** [comment]
force stop/force start and restarting the system does not solve the problem

**Comment by mpociot** [comment]
What's in your nginx log? It's in ~/Library/Application Support/Herd/Logs

**Comment by chrbox** [comment]
[nginx-error.log](https://github.com/beyondcode/herd-community/files/14270143/nginx-error.log)

**Comment by mpociot** [comment]
Connection refused means that the socket is unavailable. If restarting didn't work, try running "herd use 8.3" (or whichever version you use) via the CLI to recreate it. You can also switch PHP versions in the menubar

**Comment by chrbox** [comment]
Recreating the socket resolves the error. Thank you, for support!
