### ISSUE TITLE
[Bug]: Mixed Content error(s) prevents site shared publicly from working, even though there is no http (or https)-specific code in app

### ISSUE THREAD

**Issue by connecteev** [beyondcode/herd-community#40]
### Operating system version

MacOS Monterey 12.5.1 (21G83)

### System architecture

Intel (x86)

### Herd Version

1.0.8

### PHP Version

8.3

### Bug description

[Bug]: Mixed Content error(s) prevents site shared publicly from working, even though there is no http (or https)-specific code in app

I am running a Laravel Inertiajs + Vue app, and using Herd to attempt to share my site publicly.

I then navigate to the public URL, shared via Herd + Expose:
https://4vpw3vnhqs.sharedwithexpose.com/discuss

This is the error I get in the console:
```
Mixed Content: The page at 'https://4vpw3vnhqs.sharedwithexpose.com/discuss' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://4vpw3vnhqs.sharedwithexpose.com/discuss?fresh=1'. This request has been blocked; the content must be served over HTTPS.
```

This happens whether I go to the http or the https version of the URL:
* http://4vpw3vnhqs.sharedwithexpose.com/discuss
* https://4vpw3vnhqs.sharedwithexpose.com/discuss

### Steps to reproduce

Note that the site has not been secured in Herd:
![image](https://github.com/beyondcode/herd-community/assets/64816/0b53e539-98e2-4fd4-93e3-09b45f9cb094)

I run `herd share` to share the site publicly.
![image](https://github.com/beyondcode/herd-community/assets/64816/a62af5d9-00bb-4b0d-8e65-a53ad6fdf9e8)

I then go to the URL, example: http://4vpw3vnhqs.sharedwithexpose.com/discuss. The initial page loads, but subsequent clicks do not work, even though I do not have http (or https) specific code in my app.
![image](https://github.com/beyondcode/herd-community/assets/64816/5934846a-7997-4a80-aaf8-8dfe4f99ec57)

This is the error I get in the console:
```
xhr.js:251 Mixed Content: The page at 'https://4vpw3vnhqs.sharedwithexpose.com/discuss' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://4vpw3vnhqs.sharedwithexpose.com/discuss/minus-non-cum-doloremque-ut-mollitia-placeat'. This request has been blocked; the content must be served over HTTPS.

Uncaught (in promise) AxiosErrorcode: "ERR_NETWORK"config: {transitional: {…}, adapter: Array(2), transformRequest: Array(1), transformResponse: Array(1), timeout: 0, …}message: "Network Error"name: "AxiosError"request: XMLHttpRequest {onreadystatechange: null, readyState: 4, timeout: 0, withCredentials: false, upload: XMLHttpRequestUpload, …}stack: "AxiosError: Network Error\n    at XMLHttpRequest.handleError (http://[::1]:5173/node_modules/.vite/deps/chunk-WZ76Y7S7.js?v=cfb1dc08:1445:14)"[[Prototype]]: Error
xhr.js:251 Mixed Content: The page at 'https://4vpw3vnhqs.sharedwithexpose.com/discuss' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://4vpw3vnhqs.sharedwithexpose.com/discuss?solved=1'. This request has been blocked; the content must be served over HTTPS.
dispatchXhrRequest @ xhr.js:251
Show 1 more frame
```

This happens whether I go to the http or the https version of the URL:
* http://4vpw3vnhqs.sharedwithexpose.com/discuss
* https://4vpw3vnhqs.sharedwithexpose.com/discuss

**Comment by mpociot** [comment]
Is the site you're sharing secured with an SSL certificate by Herd?

**Comment by mpociot** [comment]
Nevermind, this was actually an issue on the free Expose server redirecting all sites to HTTPS.
This is now fixed 👍

**Comment by connecteev** [comment]
@mpociot I think this works now...ignore my last message which (for now) I think was user error.

Thank you for the quick turnaround on fixing the original issue.
