### ISSUE TITLE
[Bug]:  No redis No Mysql, cannot replace mamp No good ， Please give me a reason to use herd pro. Thank you,

### ISSUE THREAD

**Issue by BeiAduo** [beyondcode/herd-community#401]
### Operating system version

Mac M3 

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

Last version

### Bug description

 No redis No Mysql, cannot replace mamp No good ，
Please give me a reason to use herd pro. Thank you,

**Comment by mpociot** [comment]
You should check out DBngin as a perfect companion for Herd, it allows you to setup REDIS, MySQL and Postgres easily. 
https://dbngin.com/
