### ISSUE TITLE
[Bug]: Herd remains in Application Switcher

### ISSUE THREAD

**Issue by marcorieser** [beyondcode/herd-community#403]
### Operating system version

macOS Sonoma 14.3 (23D56)

### System architecture

Intel (x86)

### Herd Version

1.4.1 (Build: 21)

### Bug description

When I open the settings of Herd and then close it via the red close button, Herd remains in the application switcher (Cmd+Tab). I have to close and restart Herd so that it only remains in the menu bar.

It's not a real bug but a bit annoying.

### Steps to reproduce

- Start Herd
- Access Settings
- Close window by pressing the red close button
- Press Cmd+Tab and see Herd appearing

**Comment by sowrensen** [comment]
It also remains in the dock.

<img width="1440" alt="image" src="https://github.com/beyondcode/herd-community/assets/13097375/09bf9bcc-7130-408d-a3a0-60ccf78523dd">

**Comment by mechelon** [comment]
How many monitors do you use?

**Comment by marcorieser** [comment]
> How many monitors do you use?

MacBook Pro (open) plus 2 external Screens

**Comment by sowrensen** [comment]
I don't use any external monitor.

**Comment by marcorieser** [comment]
With just my MacBook clicking the red close button removes it from the Dock and the Application Switcher.

**Comment by mpociot** [comment]
> With just my MacBook clicking the red close button removes it from the Dock and the Application Switcher.

But as soon as you've connected external displays it no longer works?

**Comment by marcorieser** [comment]
> > With just my MacBook clicking the red close button removes it from the Dock and the Application Switcher.
> 
> But as soon as you've connected external displays it no longer works?

Yes, just checked.
