### ISSUE TITLE
[Bug]: Cannot remove herd path

### ISSUE THREAD

**Issue by esyede** [beyondcode/herd-community#405]
### Operating system version

macOS Monterey 12.7.3

### System architecture

Intel (x86)

### Herd Version

1.4.1 (Build: 21)

### Bug description

Cannot remove herd path, delete button (-) was unclickable.
Add (+) button is working

![image](https://github.com/beyondcode/herd-community/assets/10582583/9e6dca4f-5111-4082-be7f-2d93b192b279)

### Steps to reproduce

  1. Add new path via Settings
  2. Click the delete (-) button

### Relevant log output

```shell
None
```

**Comment by sschlein** [comment]
I can't reproduce the issue nor do we have other users reporting this. Does the patch actually exists? Does a restart fix it?

**Comment by esyede** [comment]
@sschlein Yes, restarting the app does fixed it. Thank you!

**Comment by Thirstypooch** [comment]
tried to uninstalling and reinstalling but wouldn't do the charm

**Comment by diannall** [comment]
FYI, this happened to me too... and restarting the app fixed it.

**Comment by olimortimer** [comment]
Same issue in 1.20.0.  Restarting Herd then allowed me to delete a Herd path.

**Comment by studio-sixtyeight** [comment]
Latest version:

i was unable to remove a path, as i renamed the folder.
So in order to remove the path I had to rename, the renamed folder.
Then remove the path.
Then rename the folder.

**Comment by sschlein** [comment]
That's fixed for the next version 🙂
