### ISSUE TITLE
[Bug]: Herd 1.4.0 instead Herd 1.4.1

### ISSUE THREAD

**Issue by davideprevosto** [beyondcode/herd-community#408]
### Operating system version

macOS Sonoma - 14.3.1

### System architecture

Intel (x86)

### Herd Version

1.4.1 (Build 21)

### Bug description

Running `herd` through the command line still gives me 1.4.0 instead of 1.4.1
Of course it is neither serious nor urgent, but it is rather misleading.

**Comment by sschlein** [comment]
Good point, looks like we missed to upgrade this.

**Comment by mpociot** [comment]
Fixed in Herd 1.4.2
