### ISSUE TITLE
[Feature Request]: PDO Driver for PostgreSQL for php@7.4

### ISSUE THREAD

**Issue by jason-beach** [beyondcode/herd-community#41]
### Feature Description

Support for php 7.4

Command: herd php -i in a project using php@7.4 I'm not seeing the following extensions:

```shell
pdo_pgsql

PDO Driver for PostgreSQL => enabled
PostgreSQL(libpq) Version => 15.1

pgsql

PostgreSQL Support => enabled
PostgreSQL (libpq) Version => 15.1
Multibyte character support => enabled
Active Persistent Links => 0
Active Links => 0
```

### Is this feature valuable for other users as well and why?

For projects using php 7.4

**Comment by mpociot** [comment]
I just triggered the build for 7.4 and 8.0 binaries, which will be available within the next 1-2 hours. 🦖

**Comment by jason-beach** [comment]
Hello Marecl,

I see that you closed this and I just did one last check but I'm not seeing the updates you mentioned will be available. I did see two new updates for 7.4 and 8.0 so I downloaded them and I'm still not seeing them. Below is all I see for php7.4

```shell
PDO

PDO support => enabled
PDO drivers => mysql, sqlite

pdo_mysql

PDO Driver for MySQL => enabled
Client API version => mysqlnd 7.4.33

Directive => Local Value => Master Value
pdo_mysql.default_socket => /tmp/mysql.sock => /tmp/mysql.sock

pdo_sqlite

PDO Driver for SQLite 3.x => enabled
SQLite Library => 3.41.1
```

Am I missing something or is it still in the process of building on your side?
Cheers!

**Comment by mpociot** [comment]
Which OS arch are you on? Intel or arm?

**Comment by mpociot** [comment]
I just downloaded 7.4 again and it looks good to me:

![image](https://github.com/beyondcode/herd-community/assets/804684/79035008-0728-44da-94a8-bec8c8ce8ecd)

**Comment by jason-beach** [comment]
> Which OS arch are you on? Intel or arm?

I'm on Intel.

**Comment by jason-beach** [comment]
@mpociot , Yes I did and get this message: Herd 1.0.8 is currently the newest version available. Nothing else indicates an update. As I mentioned, this morning I did do this and did download 7.4 and 8.0 php updates. However, when in the project directory running this command: herd php -i | grep pdo I don't see pdo_pgsql. 🤔

**Comment by jason-beach** [comment]
@mpociot , 

PHP 7.4.33 (cli) (built: Jun 22 2023 15:27:04) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

I notice it's not saying Jul 25... even though I updated 7.4 from this morning.

**Comment by mpociot** [comment]
Nope, there shouldn't be any caching.
Could you please do the following:

1. Stop Herd
2. Delete `~/Library/Application Support/Herd/bin/php74` and `~/Library/Application Support/Herd/bin/php74-fpm`
3. Start Herd

You can now re-download PHP 7.4.

**Comment by jason-beach** [comment]
@mpociot , 

That did it!

```shell
herd php -v
PHP 7.4.33 (cli) (built: Jul 25 2023 12:28:54) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
```

Thanks!
