### ISSUE TITLE
[Bug]: When activating SSL it doesn't need my password

### ISSUE THREAD

**Issue by Moise-VK** [beyondcode/herd-community#411]
### Operating system version

macOS Sonoma 14.3.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.4.1

### What happend:
I clicked the lock on a site to activiate SSL. When I clicked a popup for my password or fingerprint came up. I clicked cancel yet SSL still was enabled or at least the lock-icon was locked.
### What I expected to happen:
I click the lock, decide to click cancel when the popup comes up and SSL isn't activated.

### Steps to reproduce

1. Click the lock on a site
2. When the popup comes up for fingerprint or password, click cancel
3. The lock-icon will turn to locked anyway

**Comment by mpociot** [comment]
There's not a lof we can do here as verifying the trust status of a certificate seems to be pretty complicated.
If a user explicitly cancels a "secure" action in the middle of it, they simply need to run "unsecure" again to fix any invalid state.
