### ISSUE TITLE
[Bug]: 502 Bad Gateway when loading route with debugging enabled on PHP Storm

### ISSUE THREAD

**Issue by triumph-isingh** [beyondcode/herd-community#412]
### Operating system version

macOS 13.2.1 (22D68)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.4.1 (Build 21)

### PHP Version

PHP 8.1.26

### Bug description

When i start to listen for PHP Debug Connections in PHPStorm after settings the breakpoint so that Xdebug can connect to PHPStorm properly, my routes start returning a 502 gateway error.

It starts working again after I stop listening for PHP Debug Connections in PHPStorm, but without that the breakpoints do not work.

I am using Laravel v10.43.0, Inertia

**Comment by mpociot** [comment]
It seems like in some cases the debug socket symlink does not get created.
Could you try if that's the case for you as well and manually create the symlink?

https://github.com/beyondcode/herd-community/issues/343

**Comment by triumph-isingh** [comment]
Can you please specify what is the path to target and symlink ?
Thank you

**Comment by triumph-isingh** [comment]
Sry, I didnt look at the link you referred to in your previous comment.
I see that the symlink exists already:

![Screenshot 2024-02-20 at 11 46 58](https://github.com/beyondcode/herd-community/assets/120404365/1de1c8f7-66bd-4230-a101-0df5d61f070e)

**Comment by mpociot** [comment]
Gotcha - that looks good then.
What error do you get in your nginx-error.log?
You can find it in `~/Library/Application Support/Herd/Logs`

You can also try and force stop / restart the Herd services. You get the force stop option, by pressing the "Option" key when the Herd menu is visible

**Comment by incon** [comment]
https://github.com/nicoverbruggen/phpmon/discussions/280

**Comment by mpociot** [comment]
Thanks for linking this @incon 
So it seems to be an Xdebug bug that only occurs on 8.1 and ARM64 if I understood it correctly?

**Comment by incon** [comment]
I have not tested an x86 Mac.

**Comment by incon** [comment]
Note; only larger projects (and maybe certain packages) seem to trigger the issue.

**Comment by mpociot** [comment]
And downgrading Xdebug fixes it?

**Comment by incon** [comment]
Yes

**Comment by incon** [comment]
https://bugs.xdebug.org/view.php?id=2246#c6852

**Comment by mpociot** [comment]
Thanks @incon 
I'll downgrade xdebug for PHP 8.1 to work around this issue for now

**Comment by buby84** [comment]
uhm i still have this issue, 
herd 1.10.0
windows
php 8.1

**Comment by sergyu91ma** [comment]
i also have this issue with herd 1.17 windows 11 - spent many hours thinking is a config/project problem
PHP 8.1.31 (cli) (built: Nov 19 2024 16:43:34) (NTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.1.31, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.31, Copyright (c), by Zend Technologies
    with Xdebug v3.3.0, Copyright (c) 2002-2023, by Derick Rethans
