### ISSUE TITLE
[Bug]: Unable to change memory_limit. Stuck at 512M

### ISSUE THREAD

**Issue by neurotools** [beyondcode/herd-community#414]
### Operating system version

macOS Ventura 13.5

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.4.1 (Build: 21(

### PHP Version

PHP 7.4.33 (cli) (built: Dec 13 2023 21:52:05) ( NTS )

### Bug description

Tried to change memory_limit value using the GUI: Value is mantained in GUI interface, also change in Herd's php.ini files for all installed PHP versions, but running phpinfo() shows no change: 512M set for "local value" and "master value". Correct php.ini file is loaded: "/Users/myusername/Library/Application Support/Herd/config/php/74/php.ini"

Tried changing PHP version and has the same issue.

### Steps to reproduce

1.- Create a new site with an index.php file with just a phpinfo();
2.- Set Memory Limit in Herd GUI to a value different than 512 (i.e.: 1024)
3.- Load http://test.test site and check memory_limit value on PHP settings

**Comment by mpociot** [comment]
What's the content of your FPM configuration file? 
You can find it here: '~/Library/Application Support/Herd/config/fpm/7.4-fpm.conf`

**Comment by neurotools** [comment]
Oh. My mistake... it's set in that file and it takes precedence, as stated... Thanks!

```
; FPM pool configuration for Valet
[global]
error_log = /Users/myusername/Library/Application Support/Herd/Log/php-fpm.log

[herd]
user = myusername
group = staff
listen = /Users/myusername/Library/Application Support/Herd/herd74.sock
listen.owner = myusername
listen.group = staff
listen.mode = 0777

;; When uncommented, the following values will take precedence over settings declared elsewhere
php_admin_value[memory_limit] = 512M
;php_admin_value[upload_max_filesize] = 128M
;php_admin_value[post_max_size] = 128M

;php_admin_value[error_log] = /Users/myusername/Library/Application Support/Herd/Log/php-fpm.log
;php_admin_flag[log_errors] = on


;; Note: increasing these values will increase the demand on your CPU and RAM resources
pm = dynamic
pm.max_children = 5
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3
```
