### ISSUE TITLE
[Bug]:  The application does not show when clicking on the Herd icon.

### ISSUE THREAD

**Issue by ODDCODE** [beyondcode/herd-community#416]
### Operating system version

MacOS Sonoma 14.3.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

Latest version

### Bug description

Downloaded the Herd application, then installed the app. When I click on the application to run it, the GUI does not show, but if I open the activity monitor I see it running. The application works on my Mac mini Intel computer, but not on my MacBook Pro M1. I restarted my laptop, tried running the program again, nothing happened.

![CleanShot 2024-02-22 at 06 19 29@2x](https://github.com/beyondcode/herd-community/assets/149148/43352e02-62e1-4f57-a42c-98a126f79cb1)

**Comment by mpociot** [comment]
99% of the time this issue happens when the macOS menubar is too full to show additional icons. Can you verify that this is not the case?

**Comment by mpociot** [comment]
@ODDCODE I can't see any screenshot in the issue, if you uploaded something.
Do you mean that you can see the icon in the menubar, but not in the dock?

**Comment by mpociot** [comment]
You only need to interact with the app to switch PHP versions or open settings - for the most part, you don't interact with it as it's running in the background. That's why there's no dock icon by default.

Glad it's working now.
