### ISSUE TITLE
[Feature Request]: Include mb_split

### ISSUE THREAD

**Issue by jreviews** [beyondcode/herd-community#42]
### Feature Description

Would it be possible to include the mb_split function as part of the mbstring extension? 

I updated PHP which fixed this request https://github.com/beyondcode/herd-community/issues/5 but now I am facing this new issue with mb_split.

### Is this feature valuable for other users as well and why?

Other functions like mb_strlen, mb_strrpos, mb_strrpos work, but not mb_split.

**Comment by jreviews** [comment]
@jacksleight `mb_regex_encoding` was already added in the last php 8.2 update.

**Comment by jreviews** [comment]
@mpociot I am testing with 8.2. The last update from yesterday did fix the `mb_regex_encoding` for me, but then I saw `mb_split` errors. When I check with function_exists it returns false. In my case, all the other mb string functions I listed are working except for this one.

**Comment by jacksleight** [comment]
@jreviews Ah, this is on a legacy site running PHP 7.4, can that include `mb_regex_encoding`?

**Comment by jreviews** [comment]
@jacksleight No idea, I think @mpociot is in the process of updating all the php binaries.

**Comment by mpociot** [comment]
Yeah, the other binaries will be available in the next 1-2 hours.

Hm that's weird, as 8.2 is working fine for me.
Are you on Intel or ARM64?
What does `php -v` give you?
It should say that it was built yesterday.

![CleanShot 2023-07-25 at 13 54 40](https://github.com/beyondcode/herd-community/assets/804684/15b9478c-324e-417a-b5f6-968ba7e5b6e1)

**Comment by jreviews** [comment]
I am sorry @mpociot I quit the app, and now after restarting it it works! 🤦‍♂️
