### ISSUE TITLE
[Bug]: List of local sites is empty despite sites working fine

### ISSUE THREAD

**Issue by MrWeb** [beyondcode/herd-community#420]
### Operating system version

macOS Sonoma 14.3 (23D56)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.4.1 (21)

### PHP Version

Any

### Bug description

Opening the app, going to Sites, list is empty.

`herd park` and `herd secure` work fine and the list does not get updated.
`herd links` outputs 18 links

![Screenshot 2024-02-24 at 12 08 27](https://github.com/beyondcode/herd-community/assets/4120466/2762d6ba-8256-4f3d-a7ee-4dd2d9cb9839)

### Steps to reproduce

Opening the app, going to Sites, list is empty.
I tried closing and restarting app, rebooting, no change.

**Comment by mpociot** [comment]
Which PHP versions do you have installed via Herd?

**Comment by MrWeb** [comment]
![Screenshot 2024-02-24 at 13 14 48](https://github.com/beyondcode/herd-community/assets/4120466/6ce9c929-3c8a-42a9-8ac8-b703217c44ca)

**Comment by MrWeb** [comment]
Update, I found out how to reproduce the issue:

Terminal: go to any folder and do `herd park mydemo`

Inside Herd paths (General > Herd paths) you'll now find a `mydemo` item which is not a path.

From that point on, the site list is empty.
If you remove `mydemo` the site list comes back to normal.

![Screenshot 2024-02-24 at 13 20 12](https://github.com/beyondcode/herd-community/assets/4120466/9f1d0ed5-63c3-4a0f-b817-0ba046e2bd24)

**Comment by mpociot** [comment]
Could you check the output of "herd parked --json" in the faulty case?
Must be a typing issue where a string is suddenly null or something like that

**Comment by MrWeb** [comment]
The JSON is unchanged. Before parking "mydemo" and after parking "mydemo" they are both identical which also means after parking "mydemo" there is no track of "mydemo" inside the JSON.

**Comment by mpociot** [comment]
I think this is more of a configuration issue, as the error occurs when you park a folder that is not writable/does not exist and is more an edge case.
