### ISSUE TITLE
[Bug]: When adding a site from my custom local path I receive a 404

### ISSUE THREAD

**Issue by renzocastillo** [beyondcode/herd-community#425]
### Operating system version

mac OS Ventura 13.0

### System architecture

ARM64 M1

### Herd Version

1.4.1

### PHP Version

PHP 7.4

### Bug description

I am intending to create a new site using the plus icon at the Sites tab, but when I open the site at the browser it doesn't show the default laravel page and instead it gives me a 404.

https://github.com/beyondcode/herd-community/assets/21372177/9d0b3f4a-06e4-48be-b06a-d6454f6a6938

### Steps to reproduce

- Intend to add a site using the plus icon
- Put a name for your site
- Leave the location as the default 
- Add the site
- Click open in browser
- You'll get a 404

**Comment by renzocastillo** [comment]
I must also say that this is my default location:

<img width="914" alt="image" src="https://github.com/beyondcode/herd-community/assets/21372177/18281134-0982-470a-8316-7dd31c536dec">

**Comment by renzocastillo** [comment]
Ahh, that's good point to test out:


https://github.com/beyondcode/herd-community/assets/21372177/58ab726c-e8a8-4dec-b9b8-6888f0e89e27

<img width="903" alt="image" src="https://github.com/beyondcode/herd-community/assets/21372177/9236decd-05bb-4f08-aa3d-c8a100c1ae1a">

Seems like the composer is not correctly synced with my PHP 7.4?

**Comment by renzocastillo** [comment]
Update:

Switched to PHP 8.3 as my default PHP version and I was able to install my `example` project, although my main intention was to install a 7.4 version instead.



https://github.com/beyondcode/herd-community/assets/21372177/25169fb1-784a-4d9b-b450-c7cf3d2c687c

**Comment by mpociot** [comment]
Fixed in Herd 1.4.2
