### ISSUE TITLE
[Bug]: Swift connection refused when setting up .env parameters for Herd Mail Server

### ISSUE THREAD

**Issue by renzocastillo** [beyondcode/herd-community#426]
### Operating system version

macOS Ventura 13.0

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.4.1

### PHP Version

PHP 7.4

### Bug description

I tried to send an email through my PHP 7.4 Laravel app using the following .env parameters

```
APP_NAME="American Psycho"
APP_URL= https://localhost:777
MAIL_MAILER=smtp
MAIL_HOST=127.0.0.1
MAIL_PORT=2525
MAIL_USERNAME="${APP_NAME}"
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS=the@cheese.com
MAIL_FROM_NAME="The Cheese"

```
![image](https://github.com/beyondcode/herd-community/assets/21372177/8276a2a1-3d53-4c2a-af85-46ad4598cbcb)

Not sure if relevant but my current site which throws this error is a secured SSL site, let's say `https://cheese.test` 

### Steps to reproduce

Send a regular email through Laravel Mail PHP. 

### Relevant log output

```shell
[2024-02-26 10:19:19] local.ERROR: Connection could not be established with host 127.0.0.1 :stream_socket_client(): unable to connect to tcp://127.0.0.1:2525 (Connection refused) {"exception":"[object] (Swift_TransportException(code: 0): Connection could not be established with host 127.0.0.1 :stream_socket_client(): unable to connect to tcp://127.0.0.1:2525 (Connection refused) at /Users/renzocastillo/Dev/build-laravel/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php:261)
```
```

**Comment by mpociot** [comment]
Do you see any log when you click on the log icon for the mail server in Herd's menubar?

**Comment by renzocastillo** [comment]
Nope, not at all.

**Comment by mpociot** [comment]
Connection refused indicates that the server isn't properly running. Could you try changing the port (lets say to 2524) - wait a second before it restarts - and then change it back?

**Comment by renzocastillo** [comment]
Ahh the server was available, since I did that test previously but also kept failing. Not sure if this is related but when I change my `APP_URL` env variable to the same domain I am accessing my web app from, then the email was properly sent.

https://laracasts.com/discuss/channels/site-improvements/connection-could-not-be-established-with-host-1270012525-stream-socket-client-unable-to-connect-to-1270012525-operation-timed-out?page=1&replyId=926337

**Comment by mpociot** [comment]
I don't really understand why changing the APP_URL affects sending emails, but I'm glad that it works now
