### ISSUE TITLE
[Bug]: Changing php memory limit doesn't change

### ISSUE THREAD

**Issue by enjinabner** [beyondcode/herd-community#428]
### Operating system version

macOS venutra

### System architecture

Intel (x86)

### Herd Version

1.4.1 (Build21)

### PHP Version

PHP 8.3.3

### Bug description

Tried changing php memory limit on herd ui but it doesn't get updated. As a workaround,  I created a php.ini inside herd's home directory and it worked

### Steps to reproduce

php -i | grep memory_limit

**Comment by mpociot** [comment]
What do you get when you run `php --ini`?
Herd checks for the `HERD_PHP_83_INI_SCAN_DIR` environment variable

**Comment by enjinabner** [comment]
> What do you get when you run `php --ini`? Herd checks for the `HERD_PHP_83_INI_SCAN_DIR` environment variable

This is what i get

```
Configuration File (php.ini) Path: /lib
Loaded Configuration File:         /Users/atudz/Library/Application Support/Herd/bin/php.ini
Scan for additional .ini files in: (none)
Additional .ini files parsed:      (none)
```

**Comment by mpociot** [comment]
Okay, so it picks up your php.ini (which is the fallback location for it)
Does your .zshrc/.bashrc file have the HERD_PHP_83_INI_SCAN_DIR environment variable?

**Comment by enjinabner** [comment]
It definitely has
```
# Herd injected PHP 8.2 configuration.
export HERD_PHP_82_INI_SCAN_DIR="/Users/atudz/Library/Application Support/Herd/config/php/82/"


# Herd injected PHP binary.
export PATH="/Users/atudz/Library/Application Support/Herd/bin/":$PATH


# Herd injected PHP 8.3 configuration.
export HERD_PHP_83_INI_SCAN_DIR="/Users/atudz/Library/Application Support/Herd/config/php/83/"


# Herd injected PHP 8.1 configuration.
export HERD_PHP_81_INI_SCAN_DIR="/Users/atudz/Library/Application Support/Herd/config/php/81/"
```

**Comment by mpociot** [comment]
Does your shell have access to the environment variable too?
<img width="899" alt="CleanShot 2024-03-11 at 09 39 12@2x" src="https://github.com/beyondcode/herd-community/assets/804684/38228489-223b-40b6-a904-180efffeb050">

**Comment by enjinabner** [comment]
<img width="780" alt="Screenshot 2024-03-12 at 8 54 48 AM" src="https://github.com/beyondcode/herd-community/assets/114082473/ea00dbfa-d0ea-4ba4-bc5a-bc37be04c0ec">

It's still the same though. I've update my Herd with the latest version.

**Comment by sschlein** [comment]
The latest version should have PHP ini files at specific locations per PHP version like you can see it in Marcels screenshot. There seem to be something wrong with your Herd version as we have migrated that a few versions ago and these migrations check if files exist and run them if they don't.

It somehow looks like this is an old php process or configuration 🤔

**Comment by pedestrianlove** [comment]
I just ran into the exact same issue earlier, but a [fresh install](https://herd.laravel.com/docs/1/troubleshooting/uninstalling) solves the problem for my case.

**Comment by megawubs** [comment]
I also ran into this problem. I've fixed it by running the following

```fish
set -Ux HERD_PHP_83_INI_SCAN_DIR "/Users/bramwubs/Library/Application Support/Herd/config/php/83/"
```

Note: I'm using the Fish shell

**Comment by sschlein** [comment]
@megawubs It's slightly offtopic, but why do you actually prefer the fish shell?

**Comment by megawubs** [comment]
I'ts what I'm used to these days 🙈 Always when I try another shell, I find myself back with Fish. I can't name a specific feature, it's just what I'm used to I think.

**Comment by GoranSoce** [comment]
Why was this closed? This is still an issue...

**Comment by rginnow** [comment]
Apologies for the comment on an old issue, but this is for anyone else searching Google like me, because I just ran into this with the Fish shell.

When using ZSH or BASH, Herd will auto-inject the `.ini` and `nvm` directories into your environment.

My `.zshrc` Example:
```sh
# Herd injected PHP binary.
export PATH="/Users/YOURNAME/Library/Application Support/Herd/bin/":$PATH

# Herd injected PHP 8.4 configuration.
export HERD_PHP_84_INI_SCAN_DIR="/Users/YOURNAME/Library/Application Support/Herd/config/php/84/"

# ...

# Herd injected NVM configuration
export NVM_DIR="$HOME/Library/Application Support/Herd/config/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

# Herd ZSH completions
[[ -f "/Applications/Herd.app/Contents/Resources/config/shell/zshrc.zsh" ]] && builtin source "/Applications/Herd.app/Contents/Resources/config/shell/zshrc.zsh"
```

To get it working in Fish, you just need to manually do the same steps. So, in your `config.fish` you can do this:
```fish
# Laravel Herd PHP configurations
set -Ux HERD_PHP_83_INI_SCAN_DIR "$HOME/Library/Application Support/Herd/config/php/83/"
set -Ux HERD_PHP_84_INI_SCAN_DIR "$HOME/Library/Application Support/Herd/config/php/84/"
```

But you need NVM to work as well. There's two options:

OPTION 1)
Use the following package manually on your own (essentially a clone of NVM for fish): https://github.com/jorgebucaran/nvm.fish

OPTION 2)
Use Herd's installation, but manually through the CLI. Here's my setup...

Step 1: Install [Fisher](https://github.com/jorgebucaran/fisher) if you don't already have it.
Step 2: Get the [edc/bass plugin](https://github.com/edc/bass)
Step 3: Set your NVM_DIR environment variable in `config.fish`
```fish
# Laravel Herd NVM path
set -Ux NVM_DIR "$HOME/Library/Application Support/Herd/config/nvm"
```

Step 4: build functions for NVM in your `$__fish_config_dir/functions/` directory
```fish
# functions/nvm.fish
function nvm
    # Need to escape the Application Support path for bash
    set -l DIR (string replace ' ' '\ ' $NVM_DIR)

    # Now run it and port it into fish for us to use (yay!)
    bass source $DIR/nvm.sh --no-use ';' nvm $argv
end

# functions/nvm_find_nvmrc.fish
function nvm_find_nvmrc
    set -l DIR (string replace ' ' '\ ' $NVM_DIR)
    bass source $DIR/nvm.sh --no-use ';' nvm_find_nvmrc
end

# functions/load_nvm.fish
function load_nvm --on-variable="PWD"
    set -l default_node_version (nvm version default)
    set -l node_version (nvm version)
    set -l nvmrc_path (nvm_find_nvmrc)

    if test -n "$nvmrc_path"
        set -l nvmrc_node_version (nvm version (cat $nvmrc_path))
        if test "$nvmrc_node_version" = "N/A"
            nvm install (cat $nvmrc_path)
        else if test "$nvmrc_node_version" != "$node_version"
            nvm use $nvmrc_node_version
        end
    else if test "$node_version" != "$default_node_version"
        echo "Reverting to default Node version"
        nvm use default
    end
end
```

Step 5 (optional): pull the completions from the nvm.fish repo mentioned in OPTION 1
https://github.com/jorgebucaran/nvm.fish/blob/main/completions/nvm.fish
