### ISSUE TITLE
[Bug]: Wrong log paths, log viewer is empty

### ISSUE THREAD

**Issue by danielpost** [beyondcode/herd-community#431]
### Operating system version

macOS Sonoma 14.3.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.4.1 (Build: 21)

### Bug description

When I open the Log viewer, the screen is completely empty and I can't select a site:

![Screenshot 2024-02-28 at 15 12 16@2x](https://github.com/beyondcode/herd-community/assets/1713699/93283a0f-7a5b-4b23-9549-a7d8bcda6f9d)

When I run `herd log`, the paths to the log files seem wrong and the files are empty.

If I go to `/Users/danielpost/Library/Application Support/Herd/Log`, the correct log files are there and not empty.

### Relevant log output

```shell
+---------+-------------------------------------------------------------------------------------+
| Keys    | Files                                                                               |
+---------+-------------------------------------------------------------------------------------+
| mailhog | /opt/homebrew/var/log/mailhog.log                                                   |
| nginx   | /Users/danielpost/Library/Application Support/Herd/config/valet/Log/nginx-error.log |
| php-fpm | /opt/homebrew/var/log/php-fpm.log                                                   |
| redis   | /opt/homebrew/var/log/redis.log                                                     |
+---------+-------------------------------------------------------------------------------------+
```

**Comment by mpociot** [comment]
`herd log` and the log viewer are two separate things.

Do you have parked sites? You should be able to select those in the dropdown.

**Comment by viktorbijlenga** [comment]
If it matters, I get the same list of log files when I use `herd log`.

**Comment by viktorbijlenga** [comment]
Is the parked site using Laravel? When I tried our Herd Pro, I only got our Laravel projects in the log viewer.

**Comment by mpociot** [comment]
I'll close this issue for now as we currently don't support sites other than Laravel for the log viewer.
