### ISSUE TITLE
[Bug]: Herd is not sending all necessary headers

### ISSUE THREAD

**Issue by larskoole** [beyondcode/herd-community#434]
### Operating system version

macOS Sonoma 14.2.1

### System architecture

Intel (x86)

### Herd Version

1.4.1

### PHP Version

PHP 8.3.3

### Bug description

I updated php 8.3 to the latest version (8.3.3) and after that Herd is not sending all headers in responses.

The issue is that all responses are missing crucial headers like the XSRF headers and file related headers. Probably because they are too big/long.

The first issue I'm facing is that I'm getting `All Inertia requests must receive a valid Inertia response, however a plain JSON response was received.` responses when navigating Laravel projects. Same as #96.

To verify that it's something with PHP/Herd I've added `output_buffering=16384` to the php.ini and that solved the plain JSON response issues.

Now the only thing I'm left with is the inability to return files from controllers:
```php
return Storage::disk('s3')->response($media->s3_key);
```

Result: (a broken image)
<img width="53" alt="image" src="https://github.com/beyondcode/herd-community/assets/8629456/58daf6c9-e51d-454b-9765-ee78247a8265">

### Steps to reproduce

I truly have no clue, I updated to php 8.3.3 and then it broke.
My colleague is facing the same issues on php 8.3.3.

Let me know if you want me to test some things on my machine.

**Comment by mpociot** [comment]
@larskoole I sent you a DM on Twitter, maybe we can jump on a quick Tuple call?
