### ISSUE TITLE
[Bug]: Node.js Updates alert appears even when "Notify about Node updates" is disabled

### ISSUE THREAD

**Issue by aaronbushnell** [beyondcode/herd-community#436]
### Operating system version

macOS Sonoma 14.3.1

### System architecture

Intel (x86)

### Herd Version

1.4.1 (Build: 21)

### Bug description

I'm currently using `nvm` to manage my Node versions. Because of that I have "Notify about Node updates" disabled. However, even when this option disabled I still am being notified by Herd when my Node.js versions are out-of-date:

![Screenshot 2024-03-03 at 9 48 18 AM](https://github.com/beyondcode/herd-community/assets/315202/7d340dc3-b8c5-457b-b937-fdf505e0a748)
![Screenshot 2024-03-03 at 9 48 13 AM](https://github.com/beyondcode/herd-community/assets/315202/2dd31772-62fb-4836-bc72-57979adb16f0)

Possibly related #388

### Steps to reproduce

1. Install `nvm`
2. Install outdated versions of Node using `nvm`
3. Disable "Notify about Node updates" in Herd
4. The Node.js notifications are still shown in Herd's menu bar icon

**Comment by mechelon** [comment]
Fixed in 1.5.0
