### ISSUE TITLE
[Bug]: libsodium not up-to-date, missing proper ARM support

### ISSUE THREAD

**Issue by Rkallenkoot** [beyondcode/herd-community#437]
### Operating system version

macOS 14.3

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.4.1

### PHP Version

PHP 8.2.16 (cli) (built: Feb 16 2024 00:30:02) (NTS)

### Bug description

Current Herd PHP versions are using an outdated version of libsodium (1.0.18), which does not have AES-GCM and a lot of performance improvements: https://github.com/jedisct1/libsodium/releases/tag/1.0.19-RELEASE

**PHP Versions:**
PHP 8.3.3 (cli) (built: Feb 16 2024 00:15:01) (NTS)
PHP 8.2.16 (cli) (built: Feb 16 2024 00:30:02) (NTS)
PHP 8.1.26 (cli) (built: Dec 21 2023 08:51:01) (NTS)

All using libsodium 1.0.18 instead of the latest 1.0.19 that was released in September 2023.

### Steps to reproduce

Default installation of Herd.

**Comment by mpociot** [comment]
Thanks, will be fixed with the next PHP update 👍
