### ISSUE TITLE
[Bug]: Unable to start nginx, dnsmasq, php-fpm

### ISSUE THREAD

**Issue by ikari7789** [beyondcode/herd-community#44]
### Operating system version

macOS Ventura 13.4.1 (c)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.0.8 (Build:10)

### Bug description

I believe this to be a permissions issue due to corporate security tools, but I feel there should be a better way to manage and view issues happening within the application. Seems that there are some missing sudo prompts via UI for commands attempting to be ran in the background. I do have full sudo permissions on my machine, but the corporate security tools force some defaults (`timestamp_timeout=0` and `secure_path=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin`) which make using sudo a little annoying. I have no way around these, but it hasn't impacted any other applications I use so far, so I don't see any reason why we shouldn't be able to figure out a solution for Herd to work as well :)

Trying to start the Herd applications, it just returns "starting" messages, but I never am able to see the application status as turning green. When I attempt to view logs, I'm simply given a terminal screen with the following output for both nginx and dnsmasq:

```shell
sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
sudo: a password is required
```

When trying to view the php-fpm logs, I get the following logs:

```shell
[25-Jul-2023 13:01:03] NOTICE: [pool herd] 'user' directive is ignored when FPM is not running as root
[25-Jul-2023 13:01:03] NOTICE: [pool herd] 'group' directive is ignored when FPM is not running as root
[25-Jul-2023 13:01:03] ERROR: [pool herd] failed to chown() the socket '/Users/andrew.miller/Library/Application Support/Herd/herd81.sock': Operation not permitted (1)
[25-Jul-2023 13:01:03] ERROR: FPM initialized failed
```

I've already confirmed that I am the owner for the files in these folders and the group is also one I belong to. Is there an expected configuration for what is allowed via sudo/paths/users/groups that isn't documented?

More than willing to help troubleshoot this, but not sure where to start. Not seeing anything specific in Console neither when attempting to start the applications.

### Steps to reproduce

1. Open Herd
2. Attempt to start services

**Comment by fylzero** [comment]
Having the same issue but only with DNSMasq. Error log says:  dnsmasq: failed to create listening socket for 127.0.0.1: Permission denied

**Comment by fylzero** [comment]
@mpociot I verified this file exists - dnsmasq still is not starting for me. I have also tried the above suggestion of stopping it in Brew first with no luck. Any other thoughts?

**Comment by ikari7789** [comment]
Doesn’t really feel like a solution to the problem? Is there any way to make it work without passwordless Sudo permissions?

**Comment by fylzero** [comment]
What finally worked for me:

- Restarted my machine
- Quit Herd
- Ran these commands:

```
sudo brew services stop dnsmasq
brew services stop dnsmasq
```

- Restarted Herd

Had to run both of these for some reason.

**Comment by mpociot** [comment]
> Doesn’t really feel like a solution to the problem? Is there any way to make it work without passwordless Sudo permissions?

Unfortunately not at the moment, I'm afraid. I'll see if I can add it to Herd so that it asks for a password in case the sudoers file does not exist.

**Comment by ikari7789** [comment]
I understand. Thanks for the quick reply. Hope I can try out Herd eventually as it seems like an amazing setup. Great work.

**Comment by jjsanderson** [comment]
> Herd adds its path to the `/etc/sudoers.d` in order to start/stop these services without prompting for a sudo password every time. Could you verify that the following file/content exists on your mac? Maybe this failed in the onboarding due to your security restrictions:
> 
> File: `/etc/sudoers.d/herd` Content:
> 
> ```
> %admin ALL=(root) NOPASSWD:SETENV: /Applications/Herd.app/Contents/Resources/*
> ```
> 
> Adding this will fix the permission denied errors 👍

`sudo brew services stop dnsmasq` fixed the dnsmasq issue for me, but I still get the 'failed to chown() the socket' error from PHP-FPM. `/etc/sudoers.d/herd` exists, and reads as given here.

**Comment by gamerboy** [comment]
Same here.

MacOS Sonoma, with a user not present in the sudoers file due to company policy.
Herd file is present in the **/etc/sudoers.d** path with the following content:

```bash
%admin ALL=(root) NOPASSWD:SETENV: /usr/bin/security
```

Is there any way to run FPM without root privileges?

Thank you.
