### ISSUE TITLE
[Bug]: "Warpify'd" shell files break the NodeJS manager

### ISSUE THREAD

**Issue by jpmorby** [beyondcode/herd-community#440]
### Operating system version

macOS 14.3.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.4.2 (Build 22)

### Bug description

When clicking on the "Node" manager in Settings, you're prompted to "Install NVM by clicking below" but nothing actually happens and Herd simply shows "unknown" as the installed version of Node on each site.

After much digging it turns out that if you have Warp shell installed and have opted to "Warpify" your shell then it adds the following line to your .zsh_rc which in turn breaks Herd.app

printf '\eP$f{"hook": "SourcedRcFileForWarp", "value": { "shell": "zsh"}}\x9c'

Removing this line from .zsh_rc resolved the issue for me, but Warp may well just try and add it back in at a later date.

### Steps to reproduce

Install Warp shell

"Warpify" your shell ^|

Watch Herd get confused

### Relevant log output

```shell
No logs are produced (that I could find) which is what made this hard to find!
```

**Comment by mpociot** [comment]
I was finally able to fix this. Will be patched in the next update 👍
