### ISSUE TITLE
NGINX Not Working

### ISSUE THREAD

**Issue by noeurphireak** [beyondcode/herd-community#444]
### Operating system version

macOS Sonoma 14.4

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.4.2

### PHP Version

PHP 8.2

### Bug description
Check on nginx log

`SSL_CTX_new() failed (SSL: error:0A0000A1:SSL routines::library has no ciphers)`

**Comment by noeurphireak** [comment]
I checked on nginx log. I set herd to run on start up.  Yes all my side served over secured site and I try to disable secured site, but it still doesn't work and the nginx log still show the log that I sent above.

**Comment by mpociot** [comment]
@noeurphireak could you solve this issue? I'm unable to reproduce it.
