### ISSUE TITLE
[Bug]:  have updated the nodejs ,but stilled have the notification.

### ISSUE THREAD

**Issue by dcdebug** [beyondcode/herd-community#445]
### Operating system version

macOS Ventura Version 13.4

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.4.2(build:22)

### PHP Version

php8.3(8.3.3)

### Bug description

<img width="896" alt="image" src="https://github.com/beyondcode/herd-community/assets/28588794/e5134aac-e7c5-47f6-9bfe-053808b988cd">
the image

### Steps to reproduce

updated the latest nodejs (Herd notification) .

**Comment by dcdebug** [comment]
What's wrong ?

**Comment by ju5t** [comment]
I have the same issue.

**Comment by mpociot** [comment]
This should be fixed with Herd 1.5 🤞
