### ISSUE TITLE
[Bug]: Can't change "post_max_size"

### ISSUE THREAD

**Issue by magarrent** [beyondcode/herd-community#447]
### Operating system version

macOS Sonoma 14.3.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.4.2 (22)

### PHP Version

php 8.2.16

### Bug description

I'm trying to change the **post_max_size** option but I can't. These are the files I changed, but still appearing 8M at the phpinfo. (I already restarted all herd and php services)

<img width="371" alt="image" src="https://github.com/beyondcode/herd-community/assets/6561770/38bc8e63-0499-4d5d-9b6e-6fdb2bf7c60a">

<img width="487" alt="image" src="https://github.com/beyondcode/herd-community/assets/6561770/6320deff-c989-4c07-931c-b56e469fe331">

But still stuck in 8M, and I didn't find any file that contains that 8M

<img width="791" alt="image" src="https://github.com/beyondcode/herd-community/assets/6561770/5083b4ec-56e7-47dd-881b-9e69b5a5a365">
<img width="745" alt="image" src="https://github.com/beyondcode/herd-community/assets/6561770/508e7cf4-c52d-4250-829d-be8b15c72a48">

**Comment by adxmcollins** [comment]
I had this issue a few months ago and can't actually remember what I did to resolve it. I *think* it was adding or adjusting `client_max_body_size` in `nginx/herd.conf` that did it (in addition to changing in the PHP config files).

![CleanShot 2024-03-13 at 11 46 52@2x](https://github.com/beyondcode/herd-community/assets/25459663/c86fbc9a-405f-4b72-9512-4bbf8e1c8a0d)

**Comment by magarrent** [comment]
> I had this issue a few months ago and can't actually remember what I did to resolve it. I _think_ it was adding or adjusting `client_max_body_size` in `nginx/herd.conf` that did it (in addition to changing in the PHP config files).
> 
> ![CleanShot 2024-03-13 at 11 46 52@2x](https://private-user-images.githubusercontent.com/25459663/312439685-c86fbc9a-405f-4b72-9512-4bbf8e1c8a0d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMzA4NTgsIm5iZiI6MTcxMDMzMDU1OCwicGF0aCI6Ii8yNTQ1OTY2My8zMTI0Mzk2ODUtYzg2ZmJjOWEtNDA1Zi00YjcyLTk1MTItNGJiZjhlMWM4YTBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDExNDkxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiMTI4YzFlMjc1Njc4YjQyMTVhNzQ1MWIwMDFiMDM4OWQ2NTYxNzgyZTBjY2U2NGE4ZjBmMjRiNjFjNzAwZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jQfVqmIfaDR7_0sN5DBslOGog5ivMiGBfik0syQJyVk)

I also checked this one, but it's configured (by default) at 128M and I'm uploading a 30MB file :/

**Comment by adxmcollins** [comment]
Do you also have the same value in `nginx/nginx.conf`. I do, but not sure if I added it or if it was always there!

**Comment by mpociot** [comment]
Yeah, right now you need to add it to the `config/nginx/herd.conf` and modify `client_max_body_size` as well.
Also make sure that you restart all Herd services.

We will adjust Herd so that setting the values in the PHP settings also modifies nginx and properly sets your post_max_site

**Comment by magarrent** [comment]
Hey @mpociot, yeah but the problem is not the nginx `client_max_body_size`, which is set to 128M by default. The problem is that the PHP `post_max_size` is stuck to 8M, and I cannot modify it, I've tried in all the files.

I'm trying to upload a 30MB file, so the nginx and the other PHP props are right

```
POST Content-Length of 30331526 bytes exceeds the limit of 8388608 bytes in Unknown on line 0
{ "message": "", "exception":
```

Thanks mate!

**Comment by magarrent** [comment]
@mpociot thanks mate! It works now.
Fixed in 1.5 🚀

**Comment by DarrenChowles** [comment]
Can we have this fixed for Herd Windows too? Changing `upload_max_filesize` via Herd's control panel keeps `post_max_size` on 8M instead of updating it too.

**Comment by kratos-digital** [comment]
I updated to the latest version of Herd 1.6.0 on MacOS and still there is only 8M for post_max_size.

In this case I am using WP and this is what I get:

upload_max_filesize: 268435456
post_max_size: 8388608

Changing Max File Upload Size in Herd only updates the upload_max_filesize and there is no option to update the post_max_size via Herd. I need to use ini_set in PHP or search for ini files and update them manually.

**Comment by keisto** [comment]
I'm still running into this:
![CleanShot 2024-07-29 at 21 50 40@2x](https://github.com/user-attachments/assets/16d2e95c-b149-424c-a5bf-d98032a06a8b)

I reinstalled Herd and made sure I had no references to multiple php installations...

**Comment by keisto** [comment]
> I'm still running into this: ![CleanShot 2024-07-29 at 21 50 40@2x](https://private-user-images.githubusercontent.com/2490903/353099814-16d2e95c-b149-424c-a5bf-d98032a06a8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MDU4ODAsIm5iZiI6MTcyMjUwNTU4MCwicGF0aCI6Ii8yNDkwOTAzLzM1MzA5OTgxNC0xNmQyZTk1Yy1iMTQ5LTQyNGMtYTViZi1kOTgwMzJhMDZhOGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDFUMDk0NjIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDU1MzYyOGFkYTA0NjM3OGEzZWU4ZTBhZWJmMTQ0ZmYxYWE1OTZhNWNiOGIzY2MzYjU4ZmI4NjMzZjE3OThjMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.tEez36E8r4cMVuA7whVL7QScNKJOXGE_UBo2cm-Gg5I)
> 
> I reinstalled Herd and made sure I had no references to multiple php installations...

Providing feedback... This issues is present when running `php artisan serve`

This issues goes aways when adding the site and using the valet project domain instead of localhost:8000

**Comment by jdockwarder** [comment]
I'm having the same issue. Interesting the issues only occurs when using PHP 8.3. When I try it on my WordPress site with PHP 8.3 the post_max_size, etc, are set to 8M (I configured them to 64M in all php.ini files). When I switch my site over to PHP 8.2, the post_max_size is correct. When I switch back to PHP 8.3 the value is 8M again. Hope this helps in any way.
