### ISSUE TITLE
[Bug]: PHPStan always runs out of memory

### ISSUE THREAD

**Issue by faustbrian** [beyondcode/herd-community#45]
### Operating system version

macOS Ventura 13.4.1 (c) (22F770820d)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.0.8 (Build: 10)

### PHP Version

PHP 8.2.8 (cli) (built: Jul 24 2023 11:48:23) (NTS)

### Bug description

Since switching from Valet to Herd I'm running into issues where PHPStan always runs out of memory, no matter what project or size of project. As a workaround I'm currently running `./vendor/bin/phpstan analyse --memory-limit=-1` to get it working. **Switching back to Valet resolves this issue.**

### Steps to reproduce

Run `./vendor/bin/phpstan analyse` and it'll _(maybe?)_ run out of memory.

### Relevant log output

```shell
~/Developer/f/laravel-jupiter on  main via 🦕 v1.35.2 via 🐘 v8.2.8 took 18ms
25.07.2023 08:32:08 ❯❯ ./vendor/bin/phpstan analyse
Note: Using configuration file /Users/brian/Developer/f/laravel-jupiter/phpstan.neon.dist.
 13/13 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

 -- -------------------------------------------------------------------------------------------------------------------------------------------------
     Error
 -- -------------------------------------------------------------------------------------------------------------------------------------------------
     Child process error (exit code 255): Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 528384 bytes) in
     phar:///Users/brian/Developer/f/laravel-jupiter/vendor/phpstan/phpstan/phpstan.phar/vendor/phpstan/phpdoc-parser/src/Lexer/Lexer.php on line 75

     PHPStan process crashed because it reached configured PHP memory limit: 128M
     Increase your memory limit in php.ini or run PHPStan with --memory-limit CLI option.
     Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 65536 bytes) in
     /Users/brian/Developer/f/laravel-jupiter/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php on line 81

 -- -------------------------------------------------------------------------------------------------------------------------------------------------



 [ERROR] Found 1 error
```

**Comment by mpociot** [comment]
You might want to increase your memory limit in your php.ini file 👍

**Comment by mpociot** [comment]
What is your memory limit with Hombrew PHP? The default one in Herd is set to 128M if you haven't changed it.

**Comment by faustbrian** [comment]
128M with Homewbrew/Valet, that's why I'm confused why PHPStan started to run out of memory after switching to Herd.

**Comment by mpociot** [comment]
Interesting - I only heard from people that Herd uses _less_ memory than Valet/Homebrew. 
I'll see if I can reproduce this in a fresh Laravel installation. 
But regardless, I don't think there's much I can do tbh

**Comment by StanBarrows** [comment]
I confirm this behaviour when using Scout  (Import Files to Algolia) or Pest on a large Test suite.

<img width="1012" alt="CleanShot 2023-08-26 at 18 10 15@2x" src="https://github.com/beyondcode/herd-community/assets/10268813/bb7982cc-4126-4fdb-98f4-13019cf714ba">
