### ISSUE TITLE
[Bug]: Unable to start Reverb

### ISSUE THREAD

**Issue by labomatik** [beyondcode/herd-community#457]
### Operating system version

mac OS M1 14.2.1 (23C71)

### System architecture

Intel (x86)

### Herd Version

1.5.0 build 23

### Bug description

When the service starts, an error is displayed in the log

### Steps to reproduce

install the real-time app

### Relevant log output

```shell
Warning: require(/Users/Shared/Herd/services/reverb/beta/vendor/autoload.php): Failed to open stream: No such file or directory in /Users/Shared/Herd/services/reverb/beta/artisan on line 18

Fatal error: Uncaught Error: Failed opening required '/Users/Shared/Herd/services/reverb/beta/vendor/autoload.php' (include_path='.:') in /Users/Shared/Herd/services/reverb/beta/artisan:18
Stack trace:
#0 {main}
  thrown in /Users/Shared/Herd/services/reverb/beta/artisan on line 18
```

**Comment by mpociot** [comment]
Which PHP versions do you have installed? It seems like the composer dependencies were not properly installed during service initialization.

You can manually do this by running these commands:

```bash
cd /Users/Shared/Herd/services/reverb/beta/
composer install
```

**Comment by labomatik** [comment]
Indeed, the php version globally installed is 8.1 but 8.2 and 8.3 are installed and linked to specific sites.

`
    - laravel/reverb v1.0.0-beta1 requires php ^8.2 -> your php version (8.1.26) does not satisfy that requirement.
`

Can i specify reverb to use 8.2 (like in the sites panel)? or do i need to switch the global to 8.2 (but will force me to update in the site panel nearly 10 sites to stay on 8.1 :-) )

**Comment by mpociot** [comment]
@labomatik when you start Reverb, we will automatically use PHP 8.2+.
The problem only occurred, when you try and install Reverb while having a global version of PHP activated that is below 8.2
