### ISSUE TITLE
[Bug]:  Error recovering password

### ISSUE THREAD

**Issue by serderovsh** [beyondcode/herd-community#458]
### Operating system version

Windows 11

### System architecture

Intel (x86)

### Herd Version

1.0.6

### Bug description

https://herd.laravel.com/forgot-password

When I try to recover my password on the site, a 500 error is shown.
When I tried to create an account, I did not receive an email.

**Comment by sschlein** [comment]
Can you please send be a email from the account that you want to recover to support@beyondco.de ?

I can't see a problem for others, so it must be specific for your email address.
