### ISSUE TITLE
[Feature Request]: Offer a way to manually refresh sites list in Herd

### ISSUE THREAD

**Issue by genericmilk** [beyondcode/herd-community#46]
### Feature Description

Either a reload sites button or for the list of sites to update on settings window open would be ideal as right now if a site has been recently created, the only way to reload the sites list is to navigate away (To general etc) and then back again.

**Comment by mpociot** [comment]
Good idea 👍

**Comment by mpociot** [comment]
This is now available in Herd 1.1.0
