### ISSUE TITLE
[Bug]: Can't get Lavaral 10 anymore.

### ISSUE THREAD

**Issue by AllTheUserNamesAreGone** [beyondcode/herd-community#462]
### Operating system version

macOS Sanoma 14.4

### System architecture

Intel (x86)

### Herd Version

1.5.0

### PHP Version

8.3.3

### Bug description

Herd only deploys the latest version 11 which I can not use, there's no way to make it install the last version 10. May as well delete Herd and go back to Composer. 

### Steps to reproduce

Use Herd to do a Laravel install

**Comment by sschlein** [comment]
Hey, you don't need to delete, you can simply do a laravel install via composer and serve it via herd. That's not a Herd thing at all but the default of the Laravel installer:

`composer create-project laravel/laravel your-project 10.x`

**Comment by vassilidev** [comment]
that's can be a great choice, only to support n-1 version, we dont need to create laravel 9 or 8 projects, 11 is too fresh for some package and we need to stay at 10.

**Comment by AllTheUserNamesAreGone** [comment]
> that's can be a great choice, only to support n-1 version, we dont need to create laravel 9 or 8 projects, 11 is too fresh for some package and we need to stay at 10.

Exactly! 👍🏻
Plus hard disc space is at a premium on my PC so don't need software that is no longer of use (Herd).
