### ISSUE TITLE
[Bug]: MySQL: Unknown or incorrect time zone

### ISSUE THREAD

**Issue by devajmeireles** [beyondcode/herd-community#464]
### Operating system version

macOS Sonoma 14.4

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.5.0

### PHP Version

8.2

### Bug description

I just started a MySQL server and I got this error when I tried to run `php artisan migrate:fresh --seed`:

![CleanShot 2024-03-14 at 01 04 38](https://github.com/beyondcode/herd-community/assets/60591772/d63fce10-78e9-440b-a45b-4a831fff674d)

My timezone is really `America/Sao_Paulo` because I'm Brazilian.

### Steps to reproduce

1. Set your machine timezone `America/Sao_Paulo`
2. Try to start the MySQL Server
3. Run: `php artisan migrate:fresh --seed`

**Comment by vassilidev** [comment]
@devajmeireles Solution ? Where did you create the database ? herd pro or other soft ?

**Comment by devajmeireles** [comment]
> @devajmeireles Solution ? Where did you create the database ? herd pro or other soft ?

I just gave up and went back to using Docker.

**Comment by joeyrush** [comment]
You need to install timezone info on the Herd MySQL instance:

```
mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root -h 127.0.0.1 -p mysql
```

**Comment by mpociot** [comment]
> Would it be possible to ship the binary for `mysql_tzinfo_to_sql` with Herd?

Is this a binary that ships with MySQL? It so, then it's available - just not symlinked by default. 

You can find it here: /Users/Shared/Herd/services/mysql/VERSION/bin

**Comment by joelstein** [comment]
Thanks! I found it at `/Users/Shared/Herd/services/mysql/8.0.36/bin/mysql_tzinfo_to_sql`.

This command worked for me:

```
/Users/Shared/Herd/services/mysql/8.0.36/bin/mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root -h 127.0.0.1 -P 3306 mysql
```

Would it be possible to symlink this by default for other users?
