### ISSUE TITLE
[Bug]: Securing sites result in "Your connection is not private"

### ISSUE THREAD

**Issue by dwabuu** [beyondcode/herd-community#465]
### Operating system version

macOS Sonoma 14.3.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.4.2

### PHP Version

PHP 8.2.16

### Bug description

When securing a site via cli or ui results in "Your connection is not private" in browser. Chrome and Safari.

### Steps to reproduce

Via CLI:
1. Link site
2. Secure site
3. Open browser

Via UI:
1. Open Herd
2. Click Sites tab
3. Press lock icon for specific site 
4. Open browser

### Relevant log output

```shell
Migrated from Laravel Valet to Herd.
```

**Comment by dwabuu** [comment]
@mpociot sure, i will add the .cer file zipped.
[iv-groep.test.cer.zip](https://github.com/beyondcode/herd-community/files/14636891/iv-groep.test.cer.zip)

**Comment by mpociot** [comment]
Could you also share a screenshot of the certificate details in your browser?

**Comment by dwabuu** [comment]
Sure! 
<img width="547" alt="Screenshot 2024-03-18 at 2 29 18 PM" src="https://github.com/beyondcode/herd-community/assets/163402314/69a98ffe-f80d-4a95-b513-0f617e5a75cc">

**Comment by mpociot** [comment]
This looks pretty good to me to be honest.
Do you have admin rights on your mac? The only thing I can think of is that the root certificate could not be trusted because of some access right issues.

**Comment by dwabuu** [comment]
Okay, strange. I didn't see anything crazy in this myself. I log into my mac through a Microsoft account. But I do have full admin/sudo rights. How could I check if it is indeed a permissions issue?

**Comment by sschlein** [comment]
I can only come up with the Keychain Access utility – is the certificate there and does it look good? The certificate itself is on your Herd config/Valet folder that you can locate via the "Open configuration files" menu items.

**Comment by megawubs** [comment]
For me the message went away after a restart
