### ISSUE TITLE
[Bug]: Herd Pro Reverb does not work with a secure SSL connection

### ISSUE THREAD

**Issue by fylzero** [beyondcode/herd-community#467]
### Operating system version

macOS Sonoma 14.2.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.5.0 (Build 23)

### PHP Version

PHP 8.3.3 (cli) (built: Feb 16 2024 00:15:01) (NTS)

### Bug description

When using Laravel Reverb with the Herd Reverb service - this works fine without an SSL provided by Herd.

Once an SSL is added, even with the correct config - setting REVERB_HOST to the domain being served by Herd, and REVERB_SCHEME=https - Reverb simply no longer works.

### Steps to reproduce

Test Reverb with an SSL using the Herd Reverb service - websocket communication no longer works

**Comment by fylzero** [comment]
Related to: https://github.com/laravel/reverb/issues/78

**Comment by conradfuhrman** [comment]
I got this Reverb working with Herd Pro and SSL. Hopefully this can be used to upgrade Herd's internals so that this setup won't trouble anyone else:

https://gist.github.com/conradfuhrman/f0f731d39318b6a694e37f986b8d5c3f

**Comment by belzaaron** [comment]
> I got Reverb working with Herd Pro and SSL. Hopefully this can be used to upgrade Herd's internals so that this setup won't trouble anyone else:
> 
> https://gist.github.com/conradfuhrman/f0f731d39318b6a694e37f986b8d5c3f

Good workaround; thanks. Agreed- could become easier/smoother.

**Comment by sschlein** [comment]
You can run HTTPS Reverb servers with the upcoming 1.10 release :)

**Comment by joshstobbs** [comment]
> You can run HTTPS Reverb servers with the upcoming 1.10 release :)

@sschlein any idea when the next release will be coming?  I'd love to get this working!

**Comment by sschlein** [comment]
Next week 🙂

**Comment by joshstobbs** [comment]
Amazing!  Super stoked, thanks so much!
