### ISSUE TITLE
[Bug]: Changing the port for MinIO does not update the Environment Variables

### ISSUE THREAD

**Issue by thuiorg** [beyondcode/herd-community#473]
### Operating system version

macOS Sonoma 14.3.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.5.0 (Build: 23)

### Bug description

I added the MinIO service with the default port of 9000. The Environment Variables showed with 9000 everywhere. I then decided to change the port from 9000 to 9001. I stopped the service and restarted it. I noticed that the Environment Variables still showed 9000. The logs showed 9001.

**Comment by mpociot** [comment]
Could this be just an issue with the UI? When you edit a service, the current one will be deselected. Clicking on the device again will show you the updated env variables.
