### ISSUE TITLE
[Bug]: Drop MAMP Pro

### ISSUE THREAD

**Issue by Tklaversma** [beyondcode/herd-community#474]
### Operating system version

macOS

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.5.0

### PHP Version

8.3

### Bug description

It's almost time to finally replace MAMP Pro, but we're still missing some stuff. 

When can we expect to see:
- MariaDB, Postgres, SQLite, ...
- Different versions of each service, especially Redis and MariaDB
- Apache

The reason for these musts, is that as a developer you want to have one to-go tool, which Herd is trying to be. But in real life, you work on different projects, new ones, but especially older ones. Those old projects require stuff that Herd cannot fullfill at this moment in time, which MAMP Pro does. 

Please add Apache, MariaDB (10.4 and up) and Redis (from 5.0 and up), so we all can say goodbye to MAMP Pro 🙏🏻

Or, maybe let us add our own services 🧐?

**Comment by sschlein** [comment]
Hi @Tklaversma Herd is an _opinionated_ development environment and does not aim to be a solution that fits every niche.

That said, Postgres and MariaDB are on our short term list that we'll release once the Windows version is available.

Please also open a feature requests for these things or use one of the existing ones and don't open a bug.
