### ISSUE TITLE
[Bug]: Warning: Undefined variable $handle in /Applications/Herd.app/Contents/Resources/valet/server.php on line 139

### ISSUE THREAD

**Issue by brendt** [beyondcode/herd-community#475]
### Operating system version

macOS Ventura

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.5.0

### PHP Version

PHP 8.3

### Bug description

This message is printed at the bottom on all pages:

```
Warning: Undefined variable $handle in /Applications/Herd.app/Contents/Resources/valet/server.php on line 139
```

### Steps to reproduce

I installed a clean version of Herd, and it popped up

**Comment by mpociot** [comment]
Please see https://github.com/beyondcode/herd-community/issues/451#issuecomment-1994080899

**Comment by mpociot** [comment]
Closing this as it's a duplicate
