### ISSUE TITLE
[Bug]:  Herd Pro - Unknown database "laravel"

### ISSUE THREAD

**Issue by vassilidev** [beyondcode/herd-community#477]
### Operating system version

macOs Sonoma 14.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.5.0

### PHP Version

PHP 8.3

### Bug description

I can't migrate after copy and paste the fresh new mysql service, the only way to make it work is to create manually the laravel database schema on the connection and after it work.

<img width="313" alt="image" src="https://github.com/beyondcode/herd-community/assets/51865639/3819dad8-acbe-4e1b-b5b4-23e3cf0b874f">

### Steps to reproduce

1. Create a new MySQL service on Herd Pro
2. Copy and Paste .env config in my laravel application
3. php artisan migrate:fresh --seed
4. Error
<img width="593" alt="Capture d’écran 2024-03-16 à 14 34 21" src="https://github.com/beyondcode/herd-community/assets/51865639/170f43c7-0cb7-408a-a991-d9714f6c3ec8">
<img width="918" alt="Capture d’écran 2024-03-16 à 14 34 49" src="https://github.com/beyondcode/herd-community/assets/51865639/25ccbd50-d96a-4de6-9e42-2a05a42267e0">
<img width="472" alt="Capture d’écran 2024-03-16 à 14 35 02" src="https://github.com/beyondcode/herd-community/assets/51865639/f5f2e7ca-a7cd-4d6b-aadb-4ae217052aad">
<img width="1466" alt="Capture d’écran 2024-03-16 à 14 35 24" src="https://github.com/beyondcode/herd-community/assets/51865639/26e5ef95-88c7-4854-9404-dbfdad13cddd">

### Relevant log output

```shell
2024-03-16T13:34:26.6NZ mysqld_safe Logging to '/Users/vassilijoffroy/Library/Application Support/Herd/config/services/BB9DC3AB-42D1-4133-9BC2-C0D5825786E9//error.log'.
2024-03-16T13:34:26.6NZ mysqld_safe Starting mysqld daemon with databases from /Users/vassilijoffroy/Library/Application Support/Herd/config/services/BB9DC3AB-42D1-4133-9BC2-C0D5825786E9


 SQLSTATE[HY000] [1049] Unknown database 'laravel' (Connection: mysql, SQL: select table_name as `name`, (data_length + index_length) as `size`, table_comment as `comment`, engine as `engine`, table_collation as `collation` from information_schema.tables where table_schema = 'laravel' and table_type in ('BASE TABLE', 'SYSTEM VERSIONED') order by table_name)
```

**Comment by mpociot** [comment]
Herd only creates and starts the database server. You still need to create a database manually on that server - for example by using a tool such as TablePlus.

**Comment by vassilidev** [comment]
That's what i'm already doing, can you make a quick script to auto create laravel schema ? 

The power of Herd is the simplicity, why should I need to create manually a database ? 
I just need to c/p the .env
or maybe remove the "laravel" from the env section.

Thank god we have 14 days trial to test and cancel the payment

**Comment by mpociot** [comment]
The Laravel migration script already takes care of creating new databases for you: 

<img width="517" alt="image" src="https://github.com/beyondcode/herd-community/assets/804684/47054d31-494b-48ba-907d-5381be6f52e5">

If you are migrating any older projects over to Herd's database services you will of course need to make sure that those databases exist.
