### ISSUE TITLE
[Bug]: Remove default php binaries after php binaries update

### ISSUE THREAD

**Issue by trippo** [beyondcode/herd-community#48]
### Operating system version

macOs Ventura 13.4.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.0.8

### PHP Version

8.2.8

### Bug description

After the update of php binaries on Application Support folder is possible to delete the default php binaries on `Herd/Contents/Resources`
<img width="178" alt="image" src="https://github.com/beyondcode/herd-community/assets/497169/227ec9a6-8cdc-4bf1-9a55-1c0a2b06d03a">

**Comment by mpociot** [comment]
I don't quite understand what you mean. 
Those binaries are bundled in the app itself, so it doesn't make much sense to delete them as an app update would make them appear again.

**Comment by trippo** [comment]
Sorry @mpociot i don't know native app approch sorry.
