### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by wyxos** [beyondcode/herd-community#481]
### Operating system version

macOS Sonoma 14.4

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.5.0

### Bug description

I am unable to install any node version. When I click on "install" nothing happens for any of the version listed.

**Comment by wyxos** [comment]
Maybe worth noting that, this is a Mac I recently acquired and installed valet, nvm, etc prior to Herd. When I found about herd, I was unaware of the migrating capabilities, uninstalled everything, and then installed Herd. PHP, SQL service, certificates, etc seems to work. Only the node installation. I have installed nvm in the meantime to be able to proceed.

**Comment by mpociot** [comment]
Which shell do you use? Herd needs to run a "sourced" shell in order to install node versions

**Comment by wyxos** [comment]
> Which shell do you use? Herd needs to run a "sourced" shell in order to install node versions

I am new to Mac and struggling a bit with your question, my understanding is I am using zsh, found the following in there when using nano

```
# Herd injected PHP 8.3 configuration.
export HERD_PHP_83_INI_SCAN_DIR="/Users/myusername/Library/Application Support/Herd/config/php/83/"


# Herd injected PHP binary.
export PATH="/Users/myusername/Library/Application Support/Herd/bin/":$PATH
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
```

I understand the above suggests Herd did install correctly?

**Comment by mpociot** [comment]
Sorry, yeah that's correct. 

Can you run "nvm install [NODE_VERSIOn]" manually in your terminal?
For example: nvm install 18

This should install the node version, and Herd should also mark the version as installed in the UI.

**Comment by wyxos** [comment]
> Sorry, yeah that's correct.
> 
> Can you run "nvm install [NODE_VERSIOn]" manually in your terminal? For example: nvm install 18
> 
> This should install the node version, and Herd should also mark the version as installed in the UI.

Thank you. I found the cause of the issue, turns out there was still a pointer to the previous nvm installation made by homebrew. Removing it fixed the issue and allows me to install using Herd.
