### ISSUE TITLE
[Bug]: Sites can be isolated with non existent php versions

### ISSUE THREAD

**Issue by SamuelNitsche** [beyondcode/herd-community#482]
### Operating system version

macOS Sonoma 14.4

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.5.0

### Bug description

`herd isolate` can be run with a php version which is not installed.

### Steps to reproduce

Run `herd isolate <version>` with a version which is not installed using Herd.

**Comment by sschlein** [comment]
While this is worth an improvement at some point in the future, I am closing this for now since there are not many people having a problem with this after many installs
