### ISSUE TITLE
[Bug]: PRO - Dumps & Mails are empty

### ISSUE THREAD

**Issue by AKurkaOrvea** [beyondcode/herd-community#493]
### Operating system version

MacOS Sonoma 14.0

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.5.0 (Build: 23)

### PHP Version

8.2.16 & 8.3.3

### Bug description

**DUMPS :** 

When sending a dump() or dd() from my code, the dumps windows turns gray like there was something do display but the list is empty.
I tried to change the port, restart, force restart my herd services but the same issue is occurring all the time.

Here is a screenshot :
![CleanShot 2024-03-20 at 11 28 14](https://github.com/beyondcode/herd-community/assets/148792796/307c5f26-68af-4a25-bfd0-0dd5b71708b8)

**MAILS :** 

Same for the mails. I used Helo before but when switching to Herd mails, I have the right list of sent mails but the content is empty all the time.

Here is a screenshot :
![CleanShot 2024-03-20 at 11 29 24](https://github.com/beyondcode/herd-community/assets/148792796/727d173f-ade8-4e7c-b1ce-5e45fb35fc4f)

**Comment by mechelon** [comment]
Without more details this is hard to reproduce...
What are you trying to dump? Does the email contain anything special? Does it work if you try something like

```php
Mail::raw("Hello World!", function ($msg) {
    $msg->to("test@example.com")->subject("Test Email");
});
```

Do you have any packages installed that modify emails or the output of the Laravel app? Does the Mails log (you can access it via the menu bar) output any errors?

**Comment by AKurkaOrvea** [comment]
Hello,

First, thanks for your response.

For the dumps, as an example, I just try do do this :
```php
$user = User::find(1);
dump($user);
```
And I get the blank page like my first screenshot : 
![Screenshot 2024-03-21 at 15 21 46](https://github.com/beyondcode/herd-community/assets/148792796/e80afad8-105d-4f91-a2bb-d8db507a933b)


For the mails, I just used the code you sent and I have this in the mails window :
![Screenshot 2024-03-21 at 15 19 22](https://github.com/beyondcode/herd-community/assets/148792796/4eb5fb93-b1b5-4ae4-8115-7e9c142e13e0)

Before using Herd, I used Helo on a different port (25251) and it worked perfectly fine.

Yesterday I tried to uninstall and reinstall Herd but I still have the same issue.

**Comment by buhbailey** [comment]
Did this get resolved? My dumps are empty as well. Was working fine with Spatie Ray, but after creating a new project with Herd Pro, I get nothing but blank screens. Dump not picking up anything.

**Comment by sschlein** [comment]
I'd like to debug this, could you please check if you can find the sqlite file of herd at `/Users/seb/Library/Application Support/Herd` (replace your username) and email me the zipped file to support@beyondco.de ?

The database should contain dumps as well as mails and I want to check what happens if I open them on my machine and try to display these emails with my debug version.

**Comment by PixelBeardCo** [comment]
I am also facing this issue with empty dd() and dump() across all of my apps using Herd, Windows.

**Comment by Jeordy** [comment]
It helps, sometimes, to stop/start the interception by clicking on the little antenna in the dump window. But overall, dumps mostly aren't working on macOS 14 Sonoma.

I just opend the sqlite /Users/<yourusername>/Library/Application Support/Herd/HerdCoreData.sqlite file and emptied the ZCDDUMP table. After restarting all services the Dump window showed dumps again.

**Comment by mpociot** [comment]
@Jeordy Are you able to reproduce this issue in some way?

**Comment by Jeordy** [comment]
> @Jeordy Are you able to reproduce this issue in some way?

It's not possible to reproduce the issue, it just at some point shows up. So, I have to wait until the dumps aren't showing anymore. If this happens, what do you need?

**Comment by mpociot** [comment]
There are sqlite database files in `~/Library/Application Support/Herd`, I suppose it must be something in there. So it would be great if you could send them over in this case.
