### ISSUE TITLE
[Bug]: On Mac Herd starts Service on computer start up although "launch at login" is not checked

### ISSUE THREAD

**Issue by devpixde** [beyondcode/herd-community#495]
### Operating system version

macOS Sonoma 14.4

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.5.0

### PHP Version

8.3

### Bug description

I want to start Herd manually if I start my computer but Herd starts automatically and serves project.

### Steps to reproduce

Uncheck Checkbox Start - Lauch at login
Restart computer

**Comment by mechelon** [comment]
Can you check if Herd is still present in the login items if you uncheck the checkbox? And is the whole app starting (menu bar etc.) or just the processes for nginx, PHP etc.?
![CleanShot 2024-04-17 at 09 24 00@2x](https://github.com/beyondcode/herd-community/assets/26432041/d74df6c3-75f9-45d5-9ced-e76b22ce719f)
