### ISSUE TITLE
[Bug]: requires ext-xsl on 7.4 since 1.5.0

### ISSUE THREAD

**Issue by kayintveen** [beyondcode/herd-community#499]
### Operating system version

MacOS Sonoma 14.4

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.5.0 (build: 23)

### PHP Version

php PHP 7.4.33 (cli) (built: Dec 13 2023 21:52:05) 

### Bug description

Since the 1.5.0 all of a sudden I get these errors with composer install and update commands

requires ext-xsl * -> it is missing from your system. Install or enable PHP's

With pecl it does not seem to be installable. but I think it should be included right?

### Steps to reproduce

composer require a package that needs this (for example magento 2)

### Relevant log output

```shell
Problem 1
    - magento/framework is locked to version 103.0.3-p1 and an update of this package was not requested.
    - magento/framework 103.0.3-p1 requires ext-xsl * -> it is missing from your system. Install or enable PHP's xsl extension.
  Problem 2
    - magento/product-community-edition is locked to version 2.4.3-p1 and an update of this package was not requested.
    - magento/product-community-edition 2.4.3-p1 requires ext-xsl * -> it is missing from your system. Install or enable PHP's xsl extension.
```

**Comment by kayintveen** [comment]
I've kept checking.  but the default php 7.4 from bew (php@7.4) does include xsl.
Tried installing with pecl but not available.

**Comment by JeremyDunn** [comment]
I'm having the same issue trying to run Magento 2.3

**Comment by kayintveen** [comment]
Had to do a long workaround on this one. 

in the end, I installed Macports and did the following 

```
sudo port install php74-xsl
// had some force activations I needed to do follow logs

cp /opt/local/lib/php74/extensions/no-debug-non-zts-20190902/xsl.so /opt/homebrew/lib/php/pecl/20210902/
// version folder could be different

then in php.ini I added 
extension=/opt/homebrew/lib/php/pecl/20210902/xsl.so
```

finally fixed it.
