### ISSUE TITLE
[Bug]: Sites becomes slow when Herd Pro is enabled.

### ISSUE THREAD

**Issue by kuoppa** [beyondcode/herd-community#504]
### Operating system version

macOS Sonoma

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.5.0

### PHP Version

php 8.3

### Bug description

When enabling Herd Pro the sites becomes slower, and when deactivating it again it speeds up.

### Steps to reproduce

Activate Pro

**Comment by sschlein** [comment]
What do you mean by slow and do you have the Xdebug browser extension enabled or is there a breapoint somewhere in PHPStorm?

**Comment by kuoppa** [comment]
The response and loading time is longer when I'm activating Pro. When I'm disabling the debugger it's getting way faster, but it's still slower for some reason.

**Comment by kuoppa** [comment]
With Pro activated
<img width="218" alt="Screenshot 2024-03-26 at 12 11 14" src="https://github.com/beyondcode/herd-community/assets/6337247/e6990af3-2729-4158-9a34-a0066c7ccf8f">

Without
<img width="280" alt="Screenshot 2024-03-26 at 12 11 49" src="https://github.com/beyondcode/herd-community/assets/6337247/db2cb346-9852-486f-8449-76ef799a725b">

**Comment by mpociot** [comment]
This must be related to Xdebug being active.
Could you try and load a dummy route that just returns `phpinfo();` and see if Xdebug is loaded?

**Comment by kuoppa** [comment]
It seems like Xdebug got stuck for some reason. I removed a breakpoint from phpstorm and enabled the breakpoint checkbox in Herd and then disabled it and xdebug is now disabled again.
