### ISSUE TITLE
[Bug]: Running tests parallel fails

### ISSUE THREAD

**Issue by gizburdt** [beyondcode/herd-community#506]
### Operating system version

14.4.

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.5

### PHP Version

8.3.3

### Bug description

When I run test with `artisan test`, I get this error. Not sure if it's a bug.

```
Output:
================

Error Output:
================
sh: mysql: command not found
```

### Steps to reproduce

run `artisan test`

### Relevant log output

```shell
Output:
================

Error Output:
================
sh: mysql: command not found
```

**Comment by mpociot** [comment]
I'm not sure where in your test suite you are using `mysql` as a command.
Make sure that the binary is added to your PATH. If you are using Herd Pro, the binaries can be found in `/Users/Shared/Herd/services/mysql/8.0.36/bin`

**Comment by msucevan** [comment]
Hi @mpociot I have the same problem. When I run normally the migration everything works fine, when I use the `database/schema/mysql-schema.sql` file I get this error. What can be the issue?

**Comment by mpociot** [comment]
You can right-click on the MySQL service and select "symlink" to make the MySQL binary available to your PATH

**Comment by msucevan** [comment]
@mpociot I still don't have the pro version. This will work only with the pro version, right? I'm using DBngin for the MySQL service

**Comment by mpociot** [comment]
Oh right. If you get the error without pro, you'll need to add the mysql binary to your PATH.

**Comment by msucevan** [comment]
> Oh right. If you get the error without pro, you'll need to add the mysql binary to your PATH.

Ooh yeah, forget about that. Many thanks! Happy coding!
