### ISSUE TITLE
[Bug]: Commands not installed

### ISSUE THREAD

**Issue by chris-ware-evo** [beyondcode/herd-community#509]
### Operating system version

Windows 10

### System architecture

Intel (x86)

### Herd Version

1.0.0

### Bug description

Herd itself seems to have installed fine and works fine for visiting localhost, but the commands that should be available as per https://herd.laravel.com/docs/windows/1/getting-started/installation are not available. I've tried a full uninstall and reinstall, both not as administrator and giving it permission when needed or running the installer as administrator. I've also tried several restarts between installs.

### Relevant log output

```shell
herd : The term 'herd' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ herd
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (herd:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by mpociot** [comment]
Can you verify that the ~/.config/herd/bin folder is not in your user PATH environment variable?

**Comment by chris-ware-evo** [comment]
nvm was in the PATH, but not the folder itself. Adding the ~/.config/herd/bin path to the env variable sorted that, then just had to clean up nvm and re-install it. All works now.
