### ISSUE TITLE
[Bug]: DNS_PROBE_FINISHED_NXDOMAIN

### ISSUE THREAD

**Issue by shornuk** [beyondcode/herd-community#51]
### Operating system version

Ventura

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.0.8

### Bug description

Just installed, all seemed to work fine. Decided to remove valet and no longer works. All green in Herds settings, sites are all still there (imported from valet) however when going to any of these, I get DNS_PROBE_FINISHED_NXDOMAIN and site's not found.

Not sure where to start?

**Comment by mpociot** [comment]
Right. I just helped to debug this with someone. I think the Valet uninstalled actually deletes a file that Herd uses. 
Could you check if the following file exists:
/etc/resolvers/test

**Comment by shornuk** [comment]
No, doesn't seem to. I have a `private/etc/resolver` folder, but no files.

**Comment by mpociot** [comment]
Please create a file in there called "test"

cd /etc/resolvers/
sudo touch test 
sudo nano test 

In there, add:

nameserver 127.0.0.1

Then restart Herd.

**Comment by mpociot** [comment]
I'll see if I can submit a PR to valet so that the file doesn't get deleted when Herd is available

**Comment by shornuk** [comment]
OK, that's worked. Thank you!
To just confirm, the folder was `resolver` not `resolvers`.

Many thanks.

**Comment by mpociot** [comment]
Oh right. Sorry, replied on my phone 😅
