### ISSUE TITLE
[Bug]: Node Nvm not detected on windows

### ISSUE THREAD

**Issue by rahulsya** [beyondcode/herd-community#510]
### Operating system version

windows 10

### System architecture

Intel (x86)

### Herd Version

1.0.0

### Bug description

I have installed nvm on my machine and registered environment variable path, But still not detected on the menu node

### Steps to reproduce

here is menu node
![image](https://github.com/beyondcode/herd-community/assets/48597821/96fac8bf-f578-4e90-bd2b-403facb61dbf)

my env variable setup
![image](https://github.com/beyondcode/herd-community/assets/48597821/10a0a5d9-2b9f-4b29-8d69-4fe1a2d5286c)
![image](https://github.com/beyondcode/herd-community/assets/48597821/1ed3c69e-3879-4739-9ae2-17fca1ab47ae)

my nvm worked when I ran on cmd
![image](https://github.com/beyondcode/herd-community/assets/48597821/4af3ea33-bce3-47c3-a9b9-77abc62279ab)

**Comment by gustavobigardi** [comment]
Same on Windows 11 here.

![image](https://github.com/beyondcode/herd-community/assets/8357566/df0caaa1-9896-48f4-8ec9-354e30f011ab)

![image](https://github.com/beyondcode/herd-community/assets/8357566/50a77cd5-f4f0-4e65-918d-aa4a4054dadd)

**Comment by rijavecb** [comment]
Same here, but I have NVM installed on Windows 11 via nvm-windows  as that seems to be the recommended way by Microsoft 

- https://github.com/coreybutler/nvm-windows
- https://learn.microsoft.com/en-us/windows/dev-environment/javascript/nodejs-on-windows
- 
![image](https://github.com/beyondcode/herd-community/assets/15850530/f5f6f396-bf2d-47f6-acae-2dc9edafb507)

**Comment by isimmons** [comment]
Same Windows 10 64bit.
Same variables and locations as rijavecb above.
node --version v20.11.0
nvm version 1.1.8

Strange message. How it sees NVM variables but can't follow them to the installation?

**Comment by graememullins** [comment]
Got the same issue here, I'm moving over from Wamp to Herd

**Comment by isimmons** [comment]
I think I found part of the problem.

Herd creates an empty nvm folder inside .config/herd/bin. I think it's trying to create a symbolic link to where the NVM_HOME variable shows it is located.

After I delete that folder and in a terminal (as administrator) go to that herd/bin folder and run `mklink /D nvm "C:\Users\isimm\AppData\Roaming\nvm"`  I get a dialog telling me nvm should be run in terminal such as cmd or powershell. When I click 'ok' Herd now shows available versions with 'install' buttons

However it does not see that I already have several versions installed and the buttons just cause the same dialog to pop up and nothing happens after clicking 'ok'

I feel like this is a step forward that it at least recognizes NVM is installed.

**Comment by rahulsya** [comment]
@isimmons  it works on machine, I have various node version that already install, but on herd not show. 
are you facing same issue ? 
![image](https://github.com/beyondcode/herd-community/assets/48597821/97c4bc90-7b20-4d14-abaa-81d6ff2c767f)
![image](https://github.com/beyondcode/herd-community/assets/48597821/af50713b-32ee-42c0-b306-4273f530dda3)

**Comment by rahulsya** [comment]
@isimmons it worked on me, ya I facing the same problem, the node version that was already installed is not shown on the App

**Comment by bennajah** [comment]
![image](https://github.com/beyondcode/herd-community/assets/38137719/ce9c2d56-1753-4a7e-b2e8-86e040df7dce)
same

**Comment by mpociot** [comment]
The problem occurs when you've previously installed NVM. Herd works in combination with the NVM version that we install.

To fix the issue, you may manually remove the `NVM_HOME` and `NVM_SYMLINK` environment variables. After restarting Herd, you should see a button that prompts you to install NVM again.

We're also going to adjust the documentation accordingly.

**Comment by TommiTMX** [comment]
This occurs if you trash your .config folder too, I cleared it out to fix a weird issue where all of my sites showed no PHP version and when I set one it caused an "empty replacement" error (https://github.com/beyondcode/herd-community/issues/514) 

After deleting the config everything was working OK again but the NVM_HOME and NVM_SYMLINK environment variables were set from the initial installation causing this error. 

Deleting those environment variables did then let me re-install NVM

**Comment by simonl65** [comment]
> The problem occurs when you've previously installed NVM. Herd works in combination with the NVM version that we install.
> 
> To fix the issue, you may manually remove the `NVM_HOME` and `NVM_SYMLINK` environment variables. After restarting Herd, you should see a button that prompts you to install NVM again.
> 
> We're also going to adjust the documentation accordingly.

Unfortunately that had no effect for me - Win11 with nvm already installed prior to Herd install.

**Comment by isimmons** [comment]
@simonl65 
In case it helps, I had NVM_HOME set in both my user variables and the system variables and deleted them both. Then quit the herd app and clicked to restart it. Then the UI showed the install NVM button.

@mpociot 
Though I could just opt out of letting Herd control my node versions, I really like how easy it makes things. But it seems "not right" to me that Herd can't use my existing setup. None of my previously installed node versions are there so I've got this "AppData/roaming/" folder in the standard location full of different versions of node and then again in a non standard location inside a "username/.config" folder.
Maybe in the future when troubleshooting node/nvm issues I won't forget where it's located :-)  As I said, I like it so I'm going to keep it all Herd way. Just slightly concerned.

**Comment by simonl65** [comment]
@isimmons Thanks for the update. Having now removed both sets - I hadn't realised there were two - I still had the same issue. BUT I *have* now found a solution:

1. Remove all environment variables for NVM_HOME and NVM_SYMLINK
2. Delete the nvm folder at C:\users\<YOUR LOGIN>\.config\herd\bin\nvm
3. mklink /D c:\users\<YOUR LOGIN>\.config\herd\bin\nvm c:\nvm
   - where c:\nvm is your existing nvm folder
4. Restart Herd

Doing all of this has left me with Herd managing all my existing node versions too 👍

**Comment by quizafebrick** [comment]
> @isimmons Thanks for the update. Having now removed both sets - I hadn't realised there were two - I still had the same issue. BUT I _have_ now found a solution:
> 
> 1. Remove all environment variables for NVM_HOME and NVM_SYMLINK
> 2. Delete the _nvm_ folder at `C:\users\<YOUR LOGIN>\.config\herd\bin\nvm`
> 3. `mklink /D c:\users\<YOUR LOGIN>\.config\herd\bin\nvm c:\nvm`
>    
>    * where c:\nvm is your _existing_ nvm folder
> 4. Restart Herd
> 
> Doing all of this has left me with Herd managing all my existing node versions too 👍

In my case these still not working

**Comment by sschlein** [comment]
@simonl65 It is great that this is working but please keep in mind that this is not officially supported and it might break in the future. Herd ships with assumptions and less flexible than other setups but that is the small price that you pay for an app that can manage everything in one place: Less flexibility

According to the other answers here, the problem is solved and I am closing this issue. We'll improve the docs and error message within Herd.

**Comment by DannJohnrem** [comment]
> @isimmons Thanks for the update. Having now removed both sets - I hadn't realised there were two - I still had the same issue. BUT I _have_ now found a solution:
> 
> 1. Remove all environment variables for NVM_HOME and NVM_SYMLINK
> 2. Delete the _nvm_ folder at `C:\users\<YOUR LOGIN>\.config\herd\bin\nvm`
> 3. `mklink /D c:\users\<YOUR LOGIN>\.config\herd\bin\nvm c:\nvm`
>    
>    * where c:\nvm is your _existing_ nvm folder
> 4. Restart Herd
> 
> Doing all of this has left me with Herd managing all my existing node versions too 👍

it works but this is the problem

![image](https://github.com/user-attachments/assets/7ffac379-24fa-433b-a591-12126c536990)

and when I try to install it directly in laravel herd it has a propt like this image below:

![image](https://github.com/user-attachments/assets/6f4b04f9-eaf4-4568-8f0b-33ce20d88258)

**Comment by sschlein** [comment]
This is exactly why it's not supported 😉

**Comment by Moibe** [comment]
> the standard location full of different versions of node and then again in a non standa

Hope you didn't close it because the problem aftert those solution persists in my Windows 10 x64 pc. I did it and now the Install button appears in Herd, now the problem is that the button does nothing. I click it, several times and seems not to respond at all.
![versionsgrayed](https://github.com/user-attachments/assets/84c3fe11-d4eb-4b24-91c7-1e5242be1143)

So not applying the solution of [simonl65](https://github.com/simonl65) since it is not supported, leaves me exactly in the same point. Not being able to install. 

Is there then a way to install it manually or via command line directly to herd without using the graphic interface that seems not to work?

**Comment by marcusrox** [comment]
Same problem here. Windows 11 24H2, Herd 1.13.0
I've uninstalled and restarted Herd several times, deleted NVM variables, deleted the folders created by Herd in my user profile, nothing works. The install Node button doesn't work and the main.log always shows:

 [NodeVersionManager] installedNodeVersions: '"C:\\Users\\msouza\\.config\\herd\\bin\\nvm\\nvm.exe"' not recognized as an internal command or external, an operable program or a batch file. *
* (translated from portuguese)

I think is necessary more verbose log on install to discover this problem.

**Comment by felipepitol** [comment]
> The problem occurs when you've previously installed NVM. Herd works in combination with the NVM version that we install.
> 
> To fix the issue, you may manually remove the `NVM_HOME` and `NVM_SYMLINK` environment variables. After restarting Herd, you should see a button that prompts you to install NVM again.
> 
> We're also going to adjust the documentation accordingly.

This works perfectly! But make sure to set the Herd application to open as an administrator.

**Comment by nannnmuzaki** [comment]
> > The problem occurs when you've previously installed NVM. Herd works in combination with the NVM version that we install.
> > To fix the issue, you may manually remove the `NVM_HOME` and `NVM_SYMLINK` environment variables. After restarting Herd, you should see a button that prompts you to install NVM again.
> > We're also going to adjust the documentation accordingly.
> 
> This works perfectly! But make sure to set the Herd application to open as an administrator.

Thanks man, you saved me from hours of wasted time wrestling with this nonsense. 

Herd docs should mention that you need to open the Herd app as an administrator after removing the NVM_HOME and NVM_SYMLINK environment variables!

**Comment by Boberro** [comment]
A year later, on the latest version, issue still persists. ~~Thank you, Simon.~~

Documentation says nothing about me having to delete all the environmental variables (it appears to have helped), but ont the funny side, ai chatbot on the website decided that nvm is a mac os only feature :D
