### ISSUE TITLE
[Bug]: Terminal isn't using Herd's PHP 8.3

### ISSUE THREAD

**Issue by amirhajipoor** [beyondcode/herd-community#511]
### Operating system version

Windows 11

### System architecture

Intel (x86)

### Herd Version

1.0.0

### PHP Version

PHP 8.3

### Bug description

I already have php v8.2 installed on my Windows with Xampp. After installing Laravel Herd and restarting the operating system, Windows terminal is not using Herd's PHP version. Also, I tried to add Herd PHP path to my system environment variables manually but nothing changed.

![Screenshot 2024-03-26 202305](https://github.com/beyondcode/herd-community/assets/136118014/7f0ec21a-c38e-4e22-b51f-cf67c742d34e)
![Screenshot 2024-03-26 202742](https://github.com/beyondcode/herd-community/assets/136118014/b9bda87c-5b79-437a-8b5d-6a63459cd575)

**Comment by mechelon** [comment]
Can you check if `C:\Users\YOUR-USER\.config\herd\bin` is also in your path and if yes, at which position? (Before/after XAMPP)? If you have another PHP binary installed via choco, this might also influence that problem.

**Comment by amirhajipoor** [comment]
I just added `C:\Users\myUserName\.config\herd\bin` and fixed `C:\Users\myUserName\.config\herd\bin\php83` in my system path and now `php -v` & `composer -v` shows it's using herd. Thanks
