### ISSUE TITLE
[Bug]: Site creation not working on Windows

### ISSUE THREAD

**Issue by gustavobigardi** [beyondcode/herd-community#518]
### Operating system version

Windows 11

### System architecture

Intel (x86)

### Herd Version

1.0.0

### PHP Version

PHP 8.3

### Bug description

When I try to create a new Site using Heard, is quickly shows that it ended with the site creation, but no website, no folder, no DNS address are created.

### Steps to reproduce

I'm sending a gif below with the steps:

![HerdBug](https://github.com/beyondcode/herd-community/assets/8357566/b9164b25-ead5-4c68-be9f-d434a9b26105)

### Relevant log output

```shell
No logs found related this issue
```

**Comment by mpociot** [comment]
Which PHP versions do you have installed?
There was an issue where some binaries were not available immediately after the first application start. Could you try and restart Herd to see if this changes anything?
