### ISSUE TITLE
[Feature Request]: Use custom PHP installation (Homebrew?)

### ISSUE THREAD

**Issue by peterbrinck** [beyondcode/herd-community#52]
### Feature Description

I know the whole point of Herd is to bundle static PHP binaries for better performance and so on.
But for more experienced users, who still likes a UI, it would be nice if we could still use Herd for the UI, nginx and dnsmasq (replace Valet), but define our own custom PHP.

Maybe it could be an option that allows the usage of Homebrew for PHP?

### Is this feature valuable for other users as well and why?

This would allow for a more customizable setup, while still using Herd.
There's a lot of PHP extensions, and people use different kinds on different projects.

So allowing users to define their own PHP installation (probably via Homebrew), it would require less maintenance from the Beyond Code/Laravel team, and the maintenance and decision to use extensions falls back on the user.

**Comment by mpociot** [comment]
It sounds like you are describing [PHPMon](https://phpmon.app/), which is essentially a GUI to manage your Homebrew PHP version + extensions.

I don't see us building something similar into Herd at the moment, as its main purpose is to deal with static PHP binaries.

I already have some ideas on how we can support more/individual PHP extensions though 🤞
