### ISSUE TITLE
[Bug]: WIN: "Create new site" shows success on error

### ISSUE THREAD

**Issue by hulkur** [beyondcode/herd-community#520]
### Operating system version

Windows 11 Pro

### System architecture

Intel (x86)

### Herd Version

1.0.0

### Bug description

"Create new site"

After selecting options and pressing next, switches to "Creating your project"
Then some other screen appears for a blink (probably error message)
Then instantly goes to "Your application was created successfully". 
Nothing was actually created.

**Comment by nicklleite** [comment]
Same here!

**Comment by Adine07** [comment]
Try to reinstalling Microsoft Visual C++ Redistributable, my problem solve with this.

link: https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022

**Comment by mpociot** [comment]
This seems to occur immediately after the first start of Herd when the PATH variable is not yet properly available. 
Try restarting Herd, this should fix it.

**Comment by hulkur** [comment]
Yes, that fixed it. 
Issue still remains that error is not shown and goes to success automatically.

Same with tinker - window opens, then error and window is closed. 
I'm not sure herd can actually do anything about it though.
