### ISSUE TITLE
[Bug]: Node does not install by default on mac

### ISSUE THREAD

**Issue by julienallexandre** [beyondcode/herd-community#521]
### Operating system version

macOS Sonoma 14.4.1

### System architecture

Intel (x86)

### Herd Version

1.5.0 (Build: 23)

### Bug description

Is it normal that when Herd is installed on a Mac, Node is not installed? Whereas on Windows it is.

### Steps to reproduce

Download Herd and install

**Comment by mpociot** [comment]
During onboarding, we detect if you have NVM_ environment variables set (and therefor already installed NVM manually)
If that's the case we don't install it automatically

You can always install NVM in the Node settings manually though

**Comment by julienallexandre** [comment]
My mac was reset to factory state a week ago and I have never reinstalled nvm or node, so there is a problem that doesn't come from there.

**Comment by julienallexandre** [comment]
> During onboarding, we detect if you have NVM_ environment variables set (and therefor already installed NVM manually) If that's the case we don't install it automatically
> 
> You can always install NVM in the Node settings manually though

My mac was reset to factory state a week ago and I have never reinstalled nvm or node, so there is a problem that doesn't come from there.

**Comment by julienallexandre** [comment]
After verification Herd has installed nvm but not Node

<img width="1127" alt="Capture d’écran 2024-03-27 à 23 28 53" src="https://github.com/beyondcode/herd-community/assets/58303569/34b77350-91f4-477f-911f-25fa2ecf4d99">
<img width="905" alt="Capture d’écran 2024-03-27 à 23 30 27" src="https://github.com/beyondcode/herd-community/assets/58303569/c8fe9d12-e2ba-4694-a8ac-5ece4fa7cad6">

**Comment by BWBama85** [comment]
This is happening for me on MacOS 15.4 and Herd 1.19.0. This is a brand new Macbook Air that has never had Node installed.
