### ISSUE TITLE
[Bug]: No mailboxes recognized

### ISSUE THREAD

**Issue by datamaze21** [beyondcode/herd-community#522]
### Operating system version

mac OS Sonoma 14.1.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.5.0 (Build: 23)

### Bug description

On two different computers, have tried creating project with Herd Wizard, and setting env variables as directed in Mail docs.  Mail indicator is green, logs say Port 2525 is free.  Starting mail server.  Mailserver listening on port 2525.  However the Mail window simply says No mailboxes (with the panes button grayed out).  Installing mailpit and running on different port, 1025, seems to work.  Herd says it can not run on port 1025, another service is running.

### Steps to reproduce

Suspect I am missing something to get Herd mail process to recognize the application mailboxes.  Is there a place that userʻs can check to see if the mailbox is created and accessible by Herd mail client?

**Comment by sschlein** [comment]
Thanks, I've created an internal issue for that!

**Comment by datamaze21** [comment]
Mahalo! (Thank you)


--
"Helping you solve your data-maze"


Kent Silveira
Claris FileMaker Certified Developer
***@***.***
(805) 807-3637
http://data.konakoncepts.net <http://data.konakoncepts.net/>

**Comment by sschlein** [comment]
@datamaze21 I read your description a few more times but I am not sure that is spot the issue.

Are you able to send mails from your application without errors if you add the mail configuration from Herd?

It should look like this:

```
MAIL_DRIVER=smtp
MAIL_HOST=127.0.0.1
MAIL_PORT=2525
MAIL_USERNAME="Herd Inbox"
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
```

After you've send a mail with this, is should create an inbox and be visible there.
