### ISSUE TITLE
[Bug]: PHP rejected on Windows

### ISSUE THREAD

**Issue by iEXExchanger** [beyondcode/herd-community#524]
### Operating system version

Windows 11

### System architecture

Intel (x86)

### Herd Version

1

### PHP Version

PHP 8.2

### Bug description

After starting the services, after a while PHP automatically turns off
![2024-03-27_09-49-08](https://github.com/beyondcode/herd-community/assets/163338500/ebae9c27-128b-4a5f-a4dc-0fd24a6daa7c)

**Comment by mpociot** [comment]
This usually means that something else might be blocking the port. 

To calculate the used ports for PHP, we use the base port (9000) and the normalized version number (82). 
Can you verify that port 9082 is free?
Alternatively, does changing the base php port in the settings fix this?

**Comment by iEXExchanger** [comment]
@mpociot Tested on many ports, at first everything starts up successfully and then after an hour or 2, it turns off automatically

**Comment by mpociot** [comment]
Fixed in version 1.0.1 
https://herd.laravel.com/changelog/windows#101
