### ISSUE TITLE
[Bug]: Error on Herd starting - WIN

### ISSUE THREAD

**Issue by sbc640964** [beyondcode/herd-community#525]
### Operating system version

Windows 11

### System architecture

Intel (x86)

### Herd Version

1.0.0

### Bug description

ERROR on Herd starting
![image](https://github.com/beyondcode/herd-community/assets/46646044/9df642aa-9603-401b-b72f-53ca65f6f4c9)

**Comment by mpociot** [comment]
The error suggests that you already have something running on port 9001. 
if possible, can you stop this other service and try again?

**Comment by sbc640964** [comment]
@mpociot 
![image](https://github.com/beyondcode/herd-community/assets/46646044/6cf5372f-1e69-46a0-b19e-24e020d37a3f)

**Comment by mpociot** [comment]
Are you on a somewhat restricted user account? Seems like your user does not have access to start a service on the port

**Comment by Fludem** [comment]
> Are you on a somewhat restricted user account? Seems like your user does not have access to start a service on the port

Idk if I'm misreading but does his command prompt not say 9001 is listening, like something is actively running on that port already?

**Comment by sbc640964** [comment]
> Are you on a somewhat restricted user account? Seems like your user does not have access to start a service on the port

@mpociot My account is not restricted it is Admintrator

**Comment by sbc640964** [comment]
@mpociot 
Even in the installation it did not install php8.3
And I can't install anything because...
![image](https://github.com/beyondcode/herd-community/assets/46646044/e467cf13-3380-4d99-bc3f-6ebbce1b7293)

**Comment by mpociot** [comment]
Can you verify that Herd is not blocked in your firewall?

**Comment by sbc640964** [comment]
These are two different problems
The problem with the port was taken care of, it happened because of another software, I uninstalled it, and it worked out.

The problem with the lack of communication: 
doesn't download PHP8.3 at first.
can't install or manage PHP.
can't manage the sites.
can't activate the license (which by the way I bought, and for now I can't work... :( ).
This is a Another problem that exists only in my win11, I tried win10 and it works great..


![image](https://github.com/beyondcode/herd-community/assets/46646044/35856add-2144-4c64-8bb1-ffed0de03e23)
![image](https://github.com/beyondcode/herd-community/assets/46646044/47e0c18b-bf19-4596-b690-e1165da9e288)
![image](https://github.com/beyondcode/herd-community/assets/46646044/b2984c8f-5ada-4c72-bce6-f1bf24331e92)
![image](https://github.com/beyondcode/herd-community/assets/46646044/db4a1184-a8ea-4e86-9d22-8530ac492749)


To your dedicated care.

**Comment by sbc640964** [comment]
@mpociot I found the black mouse... :)
I fixed it, it was really a problem with the security of the computer.
Everything works fine, thank you very much.

**Comment by Fludem** [comment]
@mpociot Does herd on windows run as a service? Or is it a process that is executing the php binary?

**Comment by SuryaJD** [comment]
> I fixed it, it was really a problem with the security of the computer.

Do you mind sharing what was wrong? I am facing same problem
