### ISSUE TITLE
[Bug]: command not found: herd

### ISSUE THREAD

**Issue by iammursal** [beyondcode/herd-community#526]
### Operating system version

Windows 11

### System architecture

Intel (x86)

### Herd Version

1.0.0

### PHP Version

8.1

### Bug description

CLI commands not working

### Steps to reproduce

1. Open Terminal in project root
2. Run cmd "herd park"

### Relevant log output

```shell
zsh: command not found: herd
```

**Comment by mpociot** [comment]
Herd should automatically add the ~\.config\herd\bin folder to your PATH. 
Can you verify that this is in there?
Maybe you need to restart power shell/terminal to make it appear if it's already in there. 

Otherwise, please add the path entry yourself.

**Comment by iammursal** [comment]
Thanks for you quick response. It seem to be working with Command Prompt, but not with my zsh setup on windows.
For anyone using zsh, try adding similar alias to your ~/.zshrc file.

```shell
# herd
alias herd="/c/Users/Murshal/.config/herd/bin/herd.bat"
alias php="/c/Users/Murshal/.config/herd/bin/php.bat"
alias composer="/c/Users/Murshal/.config/herd/bin/composer.bat"
alias expose="/c/Users/Murshal/.config/herd/bin/expose.bat"
alias laravel="/c/Users/Murshal/.config/herd/bin/laravel.bat"
```
