### ISSUE TITLE
[Bug]: Not possible to create sites

### ISSUE THREAD

**Issue by rolgru** [beyondcode/herd-community#528]
### Operating system version

Windows 11

### System architecture

Intel (x86)

### Herd Version

1.0.0

### PHP Version

PHP 8.3.4

### Bug description

Not possible to create a new project. After adding a new project there is no folder in the project-folder and no entry in the sites list. Changed Herd path to a folder on drive D:.

**Comment by mpociot** [comment]
Can you try and restart Herd? Might be related to PATH changes not being properly detected.

**Comment by sschlein** [comment]
You can verify the path problem by running `php -v` and `laravel -v` in your shell. If they fail, it's a path issue.

**Comment by rolgru** [comment]
> Can you try and restart Herd? Might be related to PATH changes not being properly detected.

Perfect. Thanks for your fast reply.
