### ISSUE TITLE
[Bug]: 502 Bad gateway on a different setup

### ISSUE THREAD

**Issue by AlexVanSteenhoven** [beyondcode/herd-community#529]
### Operating system version

Windows 11

### System architecture

Intel (x86)

### Herd Version

1.0.0

### PHP Version

8.0

### Bug description

Some of our applications are having a weird structure, for example a project is stored in private_html and the public folder is outside of this map, in project A, I am getting a 502 Bad Gateway. And in project B, I am getting a 404 that the application is not found.

**Comment by mpociot** [comment]
The 404 error is related to Herd not properly detecting the application structure and therefore not knowing how to bootstrap your app.
In this case, you should look into creating a custom Valet driver - see https://herd.laravel.com/docs/windows/1/extending-herd/custom-drivers#custom-drivers

Regarding the bad gateway: Is the site using a custom PHP version or was secured? Usually a bad gateway means that the PHP process is not running properly. Could you check the service status and/or try restarting Herd services to see if this fixes the issue?

**Comment by AlexVanSteenhoven** [comment]
Thanks for the quick response, but unfortunately the 404 is not gone even with creating a custom driver. 
Maybe I am doing this wrong or do I have to enable it somewhere for that specific project.

This is my folder structure:
```
my-laravel-application/
├─ private/
│  ├─ app/
│  ├─ bootstrap/
│  ├─ resources/
├─ public_html/
│  ├─ index.php
```

This is how I setup my driver
```php
<?php

use Valet\Drivers\ValetDriver;

class CustomLaravelDriver extends ValetDriver
{
    public function serves($sitePath, $siteName, $uri)
    {
        return is_dir($sitePath.'/private');
    }

    public function frontControllerPath($sitePath, $siteName, $uri)
    {
        $publicPath = $sitePath.'/public_html';

        if (file_exists($publicPath.$uri) && !is_dir($publicPath.$uri)) {
            return $publicPath.$uri;
        }

        return $publicPath.'/index.php';
    }
}
```


The Bad gateway is fixed, so that's really nice!

**Comment by mpociot** [comment]
Can you try adding the driver as a "local" driver?

For this to work, call the file `LocalValetDriver.php` and the class name should also be `LocalValetDriver`

See: https://laravel.com/docs/11.x/valet#local-drivers

Besides that, the logic looks good to me

**Comment by AlexVanSteenhoven** [comment]
I've tried to do that, but then I get the following message:
> Fatal error: Uncaught Error: Class "Valet\Drivers\Custom\LocalValetDriver" not found in C:\Program Files\Herd\resources\app.asar.unpacked\resources\valet\cli\Valet\Drivers\ValetDriver.php:58 Stack trace: #0 C:\Program Files\Herd\resources\app.asar.unpacked\resources\valet\server.php(54): Valet\Drivers\ValetDriver::assign('D:\\projects\\php...', 'batteryspray', '/') #1 {main} thrown in C:\Program Files\Herd\resources\app.asar.unpacked\resources\valet\cli\Valet\Drivers\ValetDriver.php on line 58

Also I get this error sometimes after restarting herd:
```
2024/03/27 10:56:40 [emerg] 28520#19444: empty replacement in C:/Users/alexs/.config/herd/config/valet/Nginx/sharebtn.test.conf:28
```

**Comment by AlexVanSteenhoven** [comment]
@mpociot I saw that I made a mistake, I did not create a `Custom` folder. Now it works sort of.

I can see my application in a way but it said: `Service workers are not supported`. Also it cannot find my resources. They just return 404.

Still have some issues with the empty replacement thingy

**Comment by AlexVanSteenhoven** [comment]
Can I set a custom driver for each application? Because now my other project is using also public_html which it don't have?
Also I did not saw your reaction so the empty replacement suggestion you did, i've not tried that yet.

**Comment by mpociot** [comment]
Yes you can create a custom local driver for each of your sites, if needed

**Comment by AlexVanSteenhoven** [comment]
Sweet where can I set this up?

**Comment by mpociot** [comment]
You would just need to create this "LocalValetDriver.php" within each project directory :)

**Comment by mpociot** [comment]
Yeah, just in the root is fine

**Comment by mpociot** [comment]
@AlexVanSteenhoven Can this issue be closed then? 🤔

**Comment by AlexVanSteenhoven** [comment]
@mpociot I've not got the time to try the custom driver on project basis.

I will try this in a few minutes. If it works I will close the issue. If not you will see a response!

**Comment by AlexVanSteenhoven** [comment]
Yes it works, there is something that is being loaded. But some things aren't working as before.

Now I get thismessage regarding service workers.
![chrome_2OyUv1aYpq](https://github.com/beyondcode/herd-community/assets/67007082/82fdbd7d-7f79-48cf-a2ba-0afddfcab2cd)

**Comment by martin55** [comment]
I'm also getting "empty replacement" error after multiple sites added (and selected php7.4). Then after the herd restart I can see the error. When I checked \.config\herd\config\valet\Nginx\*.conf file, it was  missing path to the server.php (C:/Program Files/Herd/resources/app.asar.unpacked/resources/valet/server.php)

Looked like this:
```
 location / {
        rewrite ^ "" last;
    }
```

I could fix it by adding the path/copying from the working .conf file (strange that first site worked).

Should look like this:
```
 location / {
        rewrite ^ "C:/Program Files/Herd/resources/app.asar.unpacked/resources/valet/server.php" last;
    }
```

**Comment by mpociot** [comment]
@AlexVanSteenhoven It seems like your custom driver does not properly detect your static files.
You need to add this method and adjust it to your setup:

```php
/**
 * Determine if the incoming request is for a static file.
 *
 * @return string|false
 */
public function isStaticFile(string $sitePath, string $siteName, string $uri)
{
    if (file_exists($staticFilePath = $sitePath.'/public/'.$uri)) {
        return $staticFilePath;
    }
 
    return false;
}
```

Change the logic to match your local static files

**Comment by AlexVanSteenhoven** [comment]
Yes, that wash it. I cannot thank you enough for your great support!

Closing the issue now.
