### ISSUE TITLE
[Bug]: Sites Not Loading in UI from Custom Parked Directory

### ISSUE THREAD

**Issue by blhylton** [beyondcode/herd-community#53]
### Operating system version

macOS Ventura 13.4.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.0.8 (Build:10)

### PHP Version

N/A (I have all except 8.3 installed, in case that is some how relevant)

### Bug description

The sites tab on the UI is not listing any sites in my parked directory, despite them being listed within the CLI table from `herd parked`. At a guess, there is a cache that isn't refreshing, even when navigating away and back or when closing and re-opening the app. Could be related to https://github.com/beyondcode/herd-community/issues/46.

![Screenshot 2023-07-26 at 10 10 43](https://github.com/beyondcode/herd-community/assets/1297591/5886aa9e-a326-4854-b7ab-6063583905e0)
![Screenshot 2023-07-26 at 10 11 17](https://github.com/beyondcode/herd-community/assets/1297591/1f37e9e5-66ad-4b1a-8600-479827c96a2f)

### Steps to reproduce

I'm unsure how I ended up in this state specifically, as I've followed these steps before with zero issues, but just in case there is something relevant here:

1. Install Herd
2. Add a custom parked directory via UI
3. Remove default parked directories
4. Navigate to "Sites" tab

EDIT: This appears to happen as a result of uninstalling Valet, even if you reinstall Herd after removing it. Unclear if it still happens if you never installed Valet in the first place.

**Comment by blhylton** [comment]
Apologies for the lousy title; still waking up this morning. Feel free to let me know if you need any more information.

**Comment by mpociot** [comment]
There's an existing bug that sites don't show up when they only contain numbers. Could you see if that's the case for you?
Just rename the folder to see if it makes a difference

**Comment by blhylton** [comment]
@mpociot Thanks for the quick reply.

Unfortunately, that doesn't apply here. The first folder starts with a number, but that's it. 

Worth noting this folder worked previously. I reinstalled the app this morning.

**Comment by blhylton** [comment]
I'm using ZSH, but I do use [prezto](https://github.com/sorin-ionescu/prezto) and have custom configuration file locations. I copied the lines added by herd to my custom location to ensure they loaded the correct things for my shell, but I left them in the default `.zshrc` as well.

**Comment by keenminded** [comment]
Hi, all!

+1 on this for me. I just uninstalled valet after using Herd (all was working), and the sites tab is not loading anything. Directories exist. Reinstalled Herd after removing everything with AppCleaner, and still the same results. Should show at least two sites from Sites folder. No numbers in folder names either.

I hope this helps!

**Comment by mpociot** [comment]
> Hi, all!
> 
> 
> 
> +1 on this for me. I just uninstalled valet after using Herd (all was working), and the sites tab is not loading anything. Directories exist. Reinstalled Herd after removing everything with AppCleaner, and still the same results. Should show at least two sites from Sites folder. No numbers in folder names either.
> 
> 
> 
> I hope this helps!
> 
> 
> 
> 

So it once worked for you, but after uninstalling Valet it stopped working? Or did the sites list never work?

**Comment by blhylton** [comment]
@keenminded That might be the key. I uninstalled and reinstalled Herd as part of removing Valet and all of the Homebrew packages. I didn't think about it being related, but here's the process I followed:

1. Followed the [instructions to remove Herd](https://herd.laravel.com/docs/1/troubleshooting/uninstalling)
2. Ran `valet uninstall` and followed the prompts/instructions to remove the software via Homebrew (rather than telling Valet to force it)
3. `composer global remove laravel/valet`
4. Reinstalled Herd from a fresh download

As an experiment, I just reinstalled Valet and ran `valet park` on the directory in question and it brought the list back, so this is definitely the root cause in my case.

**Comment by keenminded** [comment]
> 

Yes, precisely.

**Comment by mpociot** [comment]
If you uninstall Valet and then re-install Herd, Herd will not migrate any settings. This means that your parked sites will be blank.

I'm having a hard time reproducing this.
Yes, my sites list is empty after uninstalling Valet and then re-installing Herd. But that's because my usual Sites folder is not yet added.
If I add it (the "Code" folder at the bottom) in my settings, it works again:

<img width="910" alt="CleanShot 2023-07-26 at 21 09 21@2x" src="https://github.com/beyondcode/herd-community/assets/804684/c68dd5c7-c37f-43c3-aaa1-07633c8bb5c5">

**Comment by blhylton** [comment]
@mpociot That's strange. Here's what I'm seeing with a fresh install of Herd:
![image](https://github.com/beyondcode/herd-community/assets/1297591/20d3f972-890e-4880-9fd7-fa6461374fd6)
![image](https://github.com/beyondcode/herd-community/assets/1297591/36a258a0-9916-45ca-93f5-7fe9eb572a95)
![Screenshot 2023-07-26 at 15 14 30](https://github.com/beyondcode/herd-community/assets/1297591/a283a79b-4a47-47d1-b6cc-7443219c2cdd)

Based on my previous experiments, if I run `valet install` and `valet park` at this point, the sites will show up in the Herd UI, but as soon as I run `valet uninstall`, it will blank out again.

If it's any help, I'm available to jump into a Zoom/Meet/whatever call to share my screen so we can troubleshoot and get to the bottom of this. Just let me know.

**Comment by keenminded** [comment]
I too can confirm that `herd parked` returns a list of sites, while the sites table in the settings is blank.

**Comment by mpociot** [comment]
I still can't reproduce this. Would be great if one of you could ping me on [Twitter](https://twitter.com/marcelpociot) so I can send you a debug build to figure out what's going on here

**Comment by blhylton** [comment]
@mpociot Twitter DM sent. Let me know what I can do to help. This isn't really affecting my workflow since I can just go back to using it like valet, but I still want to help work through it.

**Comment by mpociot** [comment]
Alright... @blhylton and I were able to figure out what's going on
I'll publish an update tomorrow 👍

**Comment by keenminded** [comment]
Sorry, I just saw this. Glad you were able to figure this out!

**Comment by blhylton** [comment]
Confirming again that this is fixed in 1.1.0. Thanks for the quick work.

**Comment by ulziibat-n** [comment]
Hello @blhylton 👋
I am having difficulty accessing the list of sites even though I am using version 1.1.1. Could you please take a look at this screencast to help me resolve the issue? Here is the link: 👉 https://jmp.sh/mS0WGnIr.
Thanks.

**Comment by keenminded** [comment]
Hey, @mpociot @blhylton!
So, something else happened today. I had the debug version running OK but decided to start from scratch. First, I followed the uninstallation instructions in the docs (thank you, Marcel), then I installed the latest Herd 1.1.1. Installation went fine without errors, and this time without previously install Valet configs. I expected everything to be working, but... they didn't. So, sites are again not showing, just as before. When I tried to run `herd parked` this error popped up in the terminal:

```
/Users/*******/Library/Application Support/Herd/bin//herd: line 12: php: command not found
Error finding executable PHP. Quitting for safety.
Provided output from find-usable-php.php:
```

Any ideas would be appreciated. Thank you in advance!

P.S. If that matters, on removing Herd from the Applications folder, I run the AppCleaner app, which removed some other Herd remnants from the system besides the app itself.

**Comment by keenminded** [comment]
So, I think I have more clues for you. Please let me know if we need to separate this into a different ticket.

By default, the Herd installation will install PHP 8.1. Running `php -v` in the terminal after the initial install returns the error that PHP cannot be found.

However, running `php81 -v` does work as expected.

Going into settings and installing PHP 8.2, and then going back to the menu bar and forcing the use of PHP 8.2 fixed the error, and running `php -v` in the terminal session now returns the correct version.

I think the issue could reside with the initial creation of the symbolic link to the executable during the installation.

I hope this helps!

**Comment by blhylton** [comment]
@keenminded Just to rule it out, go to your `.zshrc` file and remove that extra slash. I noticed that and removed it when I was trying to figure out the previous issue, and I'm wondering if it's relevant.

**Comment by keenminded** [comment]
@blhylton Which one? All lines end with slashes, and I think it's correct. All are pointing to directories, and bin folder contains the symbolic link to whatever PHP version is active.

All is working correctly now with the end slashes after a new PHP version is installed and activated.

**Comment by blhylton** [comment]
@keenminded Interesting. Wonder why that wasn't an issue in my case.

But from your path: `/Users/*******/Library/Application Support/Herd/bin//herd` There's an extra slash after `bin`. It shouldn't matter really, but I've had stranger things happen. I removed it from my path when I was trying to troubleshoot, but it may not do anything.

**Comment by keenminded** [comment]
Thank you, @blhylton!
After your message, I uninstalled everything again to look at the original symlink that is created, reinstalled the app, and now it is installing version 8.2 during the initial app run. However, while `php -v` works from the start, the other services didn't get installed properly, as they are not running from the menu bar. Not sure why, or how this changed from it installing 8.1 previously during the initial run.

<img width="198" alt="Screenshot 2023-07-29 at 21 11 47" src="https://github.com/beyondcode/herd-community/assets/4564549/46ca1b2f-faea-41c5-8007-dfeb0daf01d9">

**Comment by jeremy-at-evosus** [comment]
Still an issue.

**Comment by cambur** [comment]
this also happened to me today, want to use herd but doesnt show me the list of sites

**Comment by cambur** [comment]
I did not uninstalled valet, I just installed Herd and I can't see the list of sites.

**Comment by cambur** [comment]
I just uninstalled valet and herd and it works now :D I am sold on the pro! maybe github/bitbuket integration?

**Comment by jonjieviduya** [comment]
I am also experiencing this issue right now. And still not fixed. Any update to this?

**Comment by hallowcard13** [comment]
I have experienced this as well, what I did was install PHP 8.3 and restart the Laravel herd and I can see my projects on the sites tab
