### ISSUE TITLE
[Bug]: Site section not working, showing loading

### ISSUE THREAD

**Issue by iammursal** [beyondcode/herd-community#530]
### Operating system version

Windows 11

### System architecture

Intel (x86)

### Herd Version

1.0.0

### PHP Version

PHP 8.2

### Bug description

When I add new herd path, the 'Sites' section stops show all the list of pard sites. Though the site in the new folder are working
![image](https://github.com/beyondcode/herd-community/assets/52567409/6ff027cc-4c8d-436b-a337-5c576d196b42)

### Steps to reproduce

1. Open Herd GUI
2. Go to General Section
3. Add new path to Herd Path

**Comment by mpociot** [comment]
What do you get when you run `herd parked` via CLI?

**Comment by iammursal** [comment]
@mpociot Thanks a bunch. Solved the issue. After running "herd parked", I found out that as I was using some symlinks in this newly parked project that are broken. I removed those broken symlinks and started working.
<details><summary>Logs</summary>
<p>

PHP Warning:  readlink(): readlink failed to read the symbolic link (C:\laragon\www/alfaghih), error 2) in phar://C:/Users/Murshal/.config/herd/bin/herd.phar/cli/Valet/Filesystem.php on line 237

Warning: readlink(): readlink failed to read the symbolic link (C:\laragon\www/alfaghih), error 2) in phar://C:/Users/Murshal/.config/herd/bin/herd.phar/cli/Valet/Filesystem.php on line 237
PHP Warning:  readlink(): readlink failed to read the symbolic link (C:\laragon\www/public_html), error 2) in phar://C:/Users/Murshal/.config/herd/bin/herd.phar/cli/Valet/Filesystem.php on line 237

Warning: readlink(): readlink failed to read the symbolic link (C:\laragon\www/public_html), error 2) in phar://C:/Users/Murshal/.config/herd/bin/herd.phar/cli/Valet/Filesystem.php on line 237
.....
</p>
</details>
