### ISSUE TITLE
[Bug]: Herd Application is not working. Only running in the background

### ISSUE THREAD

**Issue by matheenshariff-webo** [beyondcode/herd-community#533]
### Platform

Windows

### Operating system version

windows 11

### System architecture

Windows

### Herd Version

1.0.0

### Bug description

After successfull installation. I tried clicking on the app to open the application, but it was not opening. When I attempt to start it using the command line ```start herd.exe```, I'm encountering the following errors.

```
[DEP0128] DeprecationWarning: Invalid 'main' field in 'C:\Program Files\Herd\resources\app.asar\node_modules\ini-api\package.json' of './dist/index.js'. Please either fix that or report it to the module author
(Use `herd --trace-deprecation ...` to show where the warning was created)
FATAL ERROR: Error::ThrowAsJavaScriptException napi_throw
 1: 00007FF75F688506 node::SetTracingController+86134
 2: 00007FF75F688644 node::OnFatalError+276
 3: 00007FF75FE56B20 napi_fatal_error+144
 4: 00007FFD06DF19D7
 5: 00007FFD06DF1DA6
 6: 00007FFD06E0ADC9
 7: 00007FF75FE59603 node_api_get_module_file_name+1987
 8: 00007FF75FD6CA3C uv_dlerror+71276
 9: 00007FF75FD6C893 uv_dlerror+70851
10: 00007FF75FE7FA34 uv_fs_poll_getpath+1444
11: 00007FF75F70B2D0 uv_run+1888
12: 00007FF75F70AD6B uv_run+507
13: 00007FF75F6D741C node::loader::ModuleWrap::Initialize+164380
14: 00007FF75F6D7D42 node::loader::ModuleWrap::Initialize+166722
15: 00007FF75F70340A node::FreeEnvironment+186
16: 00007FF75D83FE95 v8::Extension::auto_enable+981
17: 00007FF75D78BCD6 std::__Cr::vector<v8::CpuProfileDeoptFrame,std::__Cr::allocator<v8::CpuProfileDeoptFrame> >::__alloc+75606
18: 00007FF75E784254 uv_fs_get_path+118644
19: 00007FF75E785EEE uv_fs_get_path+125966
20: 00007FF75E7810C0 uv_fs_get_path+105952
21: 00007FF75D94D582 v8::internal::StrongRootAllocatorBase::StrongRootAllocatorBase+541458
22: 00007FF75D94E924 v8::internal::StrongRootAllocatorBase::StrongRootAllocatorBase+546484
23: 00007FF75D94E6A4 v8::internal::StrongRootAllocatorBase::StrongRootAllocatorBase+545844
24: 00007FF75D94A9E0 v8::internal::StrongRootAllocatorBase::StrongRootAllocatorBase+530288
25: 00007FF75D94AB5D v8::internal::StrongRootAllocatorBase::StrongRootAllocatorBase+530669
26: 00007FF75D68CBC5 std::__Cr::vector<v8::CpuProfileDeoptInfo,std::__Cr::allocator<v8::CpuProfileDeoptInfo> >::vector<v8::CpuProfileDeoptInfo,std::__Cr::allocator<v8::CpuProfileDeoptInfo> >+60933
27: 00007FF761D28642 Cr_z_adler32+4755858
28: 00007FFD4AD4257D BaseThreadInitThunk+29
29: 00007FFD4B8AAA58 RtlUserThreadStart+40

```

**Comment by mpociot** [comment]
Can you share your `%USERPROFILE%\AppData\Roaming\herd\logs\main.log` file?

I'm guessing the application was somehow modified during installation - maybe via an anti virus software?

**Comment by matheenshariff-webo** [comment]
Sure this is my main.log file 

[main.log](https://github.com/beyondcode/herd-community/files/14772581/main.log)

**Comment by mpociot** [comment]
So you've been able to successfully go through the onboarding process, right?
At least according to the logs.

Are you sure that Herd isn't running in the task bar?

**Comment by matheenshariff-webo** [comment]
The herd is running in the taskbar, but the ```GUI``` is not opening to download the previous version of PHP or to ```start``` or ```stop``` services  like below

<img width="287" alt="image" src="https://github.com/beyondcode/herd-community/assets/85162514/46d422cd-b3af-4b62-9a78-8d1f9462342c">

**Comment by mpociot** [comment]
@matheenshariff-webo but the GUI worked in order to install PHP 8.2, Redis and MySQL?

**Comment by matheenshariff-webo** [comment]
I didn't see the ```GUI``` itself until it was installed for the first time; thereafter, I was unable to open it.

**Comment by mpociot** [comment]
What happens if you left click/right click on the icon? Can you record a video?
I'm not sure that I understand entirely what your problem is as you (according to your screenshot at least) were able to install Redis, MySQL, PHP 8.2 and activate Herd Pro

**Comment by hatchman64** [comment]
I have same issue.  After install, app opened with "lets get started" and links to tinkerwell and expose. When I clicked the "lets get started" link, app disappeared.  Can find in running in Task Manager along with 9 nginx.exe's running.  I can open powershell and access the herd cli.  Have uninstalled and re-installed herd but never saw the opening app panel again even though herd show running in Task Manager.
Here is main log from \AppData\Roaming\Herd\logs
[main.log](https://github.com/beyondcode/herd-community/files/14794505/main.log)

Thanks

**Comment by sschlein** [comment]
@philc-d This is actually the intended behaviour :)

**Comment by Masri-Programmer** [comment]
> I experienced a similar issue on Windows. Clicking on the Herd desktop shortcut started herd in the background (visible from Task Manager), but did not open the GUI. Clicking on the system tray icon opened the GUI as expected.

I am experiencing the same issue since this morning! tried reinstalling and restarting my PC.

**Comment by ghost** [comment]
> Can you share your `%USERPROFILE%\AppData\Roaming\herd\logs\main.log` file?
> 
> I'm guessing the application was somehow modified during installation - maybe via an anti virus software?

**Comment by Souvik-223** [comment]
> [@philc-d](https://github.com/philc-d) This is actually the intended behaviour :)

Feature so goated people think of it as a bug lol 😂😂, it took me 30 min to understand i have to open it from the system tray, can't even explain how stupid i feel now.

**Comment by sschlein** [comment]
The most recent version actually opens the settings if you try to start it twice because there's just no macOS option to show the icons that you need.

**Comment by Souvik-223** [comment]
> The most recent version actually opens the settings if you try to start it twice because there's just no macOS option to show the icons that you need.

I tried opening it like 10 times and all it did was to close and restart the background process. It didn't open the setting or the app screen for me.
