### ISSUE TITLE
[Bug]: Sites list doesnt work if global PHP is 7.4

### ISSUE THREAD

**Issue by yabdab** [beyondcode/herd-community#537]
### Platform

macOS

### Operating system version

Ventura 13.6.5

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.5

### PHP Version

php 7.4

### Bug description

Settings -> Sites shows no sites when PHP 7.4 is default version? Works when the default PHP version is 8.1 or higher

### Steps to reproduce

Make PHP 7.4 the default, then click Sites tab

**Comment by mechelon** [comment]
Yes, the sites list only works with newer PHP versions. I'll see if we can force the usage of one of these (as long as they're installed).

**Comment by sschlein** [comment]
Hi @yabdab – I am trying to reproduce the issue but can't.

Can you please run `php -v` and `which php` and paste teir output here? Is this with Xdebug enabled or without?

**Comment by yabdab** [comment]
Here is a video showing the issue ...

https://share.zight.com/7KunOzw2

**Comment by yabdab** [comment]
Does this on my M1 Macbook Pro as well ( running Sonoma )

**Comment by mechelon** [comment]
@yabdab What happens when you run `herd parked --json` in your terminal with PHP 7.4?
I also noticed from your video that you seem to use the Warp terminal? Can you check if you have enabled subshell support (https://docs.warp.dev/features/subshells)? We're not sure why yet, but that can lead to problems sometimes.

**Comment by yabdab** [comment]
```bash
$ herd parked --json                                            
Error finding executable PHP. Quitting for safety.
Provided output from find-usable-php.php:
/Users/mikeyrab/Library/Application Support/Herd/bin/php83
```

**Comment by yabdab** [comment]
Aha! I did not have PHP 8.3 installed. Once I did that, the sites show up even when I have  7.4 selected globally.
Not sure if this is a bug or not,  but that was the reason it was not working.

**Comment by mechelon** [comment]
Thanks for that, it helped a lot! This will be fixed in the next release. :)
