### ISSUE TITLE
[Bug]: Xdebug on PHP 7.4 not working

### ISSUE THREAD

**Issue by darioierimonti** [beyondcode/herd-community#538]
### Platform

Windows

### Operating system version

Windows 11

### System architecture

Windows

### Herd Version

1.0.0

### PHP Version

PHP 7.4

### Bug description

I have PHP 8.3 and PHP 7.4 installed. When I activate HERD PRO license, switching to PHP 7.4 does not find the xdebug dll file and throws this error:
![image](https://github.com/beyondcode/herd-community/assets/105490670/b0c2fa88-8d74-4723-bd2d-415e5ef262d9)

**Comment by mpociot** [comment]
Thanks for reporting this. This will be fixed in the next release.
