### ISSUE TITLE
[Bug]: Cannot start Nginx 

### ISSUE THREAD

**Issue by alexfleites** [beyondcode/herd-community#54]
### Operating system version

macOS Ventura 13.4.1 (c)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.0.8 (Build 10)

### PHP Version

PHP 8.2

### Bug description

Cannot start Nginx loading Herd

### Steps to reproduce

Load Herd

**Comment by alexfleites** [comment]
![Nginx logs 2023-07-26 at 11 42 53 AM](https://github.com/beyondcode/herd-community/assets/962479/d8b80f79-c255-48a4-ab15-bf3a348f9f5a)

**Comment by mpociot** [comment]
It seems like nginx is still running via brew. 
Make sure you stop all running services. 

sudo brew services stop nginx

**Comment by alexfleites** [comment]
Yeah, found the issue.. was docker because I am using Lando before... Thank You!
