### ISSUE TITLE
[Bug]:  PHP Crashes from a high number of requests

### ISSUE THREAD

**Issue by rubendn** [beyondcode/herd-community#541]
### Platform

Windows

### Operating system version

Windows 11

### System architecture

Windows

### Herd Version

1.0 Pro

### PHP Version

PHP 8.2.17

### Bug description

I have a livewire page that loads a lot of images on one page (about 750).  It loads about 3/4 of them and then PHP crashes (light turns red on Active Services dashboard).  It worked fine using Apache/Laragon.

![Screenshot 2024-03-27 132336](https://github.com/beyondcode/herd-community/assets/8990606/264182fd-3a14-4717-97bc-8d82c69bb7fe)

It produces this in the nginx-e error log for each failed image:
2024/03/27 11:49:12 [error] 37900#35092: *78 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while reading response header from upstream, client: 127.0.0.1, server: cardtools.test, request: "GET /images/1911.jpg?1711554550 HTTP/2.0", upstream: "fastcgi://127.0.0.1:162", host: "cardtools.test", referrer: "https://cardtools.test/admin/images"

Anyone experience something similar on a page with many connections to PHP/NGINX using Herd?

**Comment by douglasroos** [comment]
Same issue here

**Comment by rubendn** [comment]
From the debugging I have done, the page is completed served by the server and then the crash is happening when the browser is requesting all the images from the server.  Seems like either PHP or NGINX is overwhelmed by the number of requests.

Is there a log for PHP that is generated by Herd?  I don't see one anywhere.

This is what is in the Network tab in Google Chrome....
![image](https://github.com/beyondcode/herd-community/assets/8990606/84f41acd-154d-445b-a3cb-b20358c1342b)

**Comment by mpociot** [comment]
Fixed in version 1.0.1 
https://herd.laravel.com/changelog/windows#101
