### ISSUE TITLE
[Bug]: herd tinker not working

### ISSUE THREAD

**Issue by carstenjaksch** [beyondcode/herd-community#542]
### Platform

Windows

### Operating system version

Windows 11 Pro (23H2 22631.3296)

### System architecture

Windows

### Herd Version

1.0.0

### PHP Version

PHP 8.3.4

### Bug description

`herd tinker` or clicking the Tinker button in the app opens a terminal for half a second and nothing happens. Newest Tinkerwell is installed.

### Relevant log output

```shell
Don't know if Herd has logs for something like that.
```

**Comment by carstenjaksch** [comment]
After restarting Herd, the terminal stays open with a Tinker prompt I guess. But Tinkerwell doesn't open instead. I tried that with Tinkerwell closed and open.

**Comment by sbc640964** [comment]
I also have the same problem
Tinkerwell doesn't just open the command line with Tinker

**Comment by mpociot** [comment]
On Windows, the Herd UI can only open the "php artisan tinker" CLI at the moment. For now, you need to open Tinkerwell manually.
