### ISSUE TITLE
[Bug]: Composer bin path is not added to user's PATH

### ISSUE THREAD

**Issue by godismyjudge95** [beyondcode/herd-community#546]
### Platform

Windows

### Operating system version

Windows 11 Pro (22H2 22621.3296)

### System architecture

Intel (x86)

### Herd Version

1.0.0

### Bug description

Running any `composer global require` installs the package but then the binary isn't available to execute from the command prompt.  This is because the user's PATH does not contain the path: `C:\Users\username\AppData\Roaming\Composer\vendor\bin`

### Steps to reproduce

1. Run `composer global require statamic/cli`
2. After it is done installing, one would expect you can run `statamic new my-site` but this is met with an error

**Comment by rubendn** [comment]
In my installation it added the following path to the USER PATH environment variable:

```C:\Users\<username>\.config\herd\bin```

In that directory there is a composer.bat that points to the composer.phar file in that directory that should run based on the Path entry.

**Comment by rdvr** [comment]
I use Git Bash as my default terminal in Windows. Git bash doesn't recognise the .bat extension by default so in order to run command line composer and php you need to add the .bat extension e.g. composer.bat.

**Comment by mpociot** [comment]
Please add the vendor/bin folder manually to your PATH if you need globally installed composer packages.
