### ISSUE TITLE
[Bug]: Herd secure Error

### ISSUE THREAD

**Issue by nbolink** [beyondcode/herd-community#549]
### Platform

Windows

### Operating system version

Windows 11

### System architecture

Intel (x86)

### Herd Version

1.0.0

### PHP Version

PHP 8.2

### Bug description

Securing a site doesn't work. Not in the GUI and not with an admin CLI command.

PS C:\Users\nickb\Herd\herdtest> herd secure

PHP Fatal error:  Uncaught Error: Call to undefined function Valet\error() in phar://C:/Users/nickb/.config/herd/bin/herd.phar/cli/Valet/Site.php:827
Stack trace:
#0 phar://C:/Users/nickb/.config/herd/bin/herd.phar/cli/Valet/CommandLine.php(103): Valet\Site->Valet\{closure}(1, ''powershell' is...')
#1 phar://C:/Users/nickb/.config/herd/bin/herd.phar/cli/Valet/CommandLine.php(42): Valet\CommandLine->runCommand('powershell -com...', Object(Closure))
#2 phar://C:/Users/nickb/.config/herd/bin/herd.phar/cli/Valet/Site.php(826): Valet\CommandLine->powershell('Start-Process P...', Object(Closure))
#3 phar://C:/Users/nickb/.config/herd/bin/herd.phar/cli/Valet/Site.php(463): Valet\Site->unsecure('herdtest.test')
#4 phar://C:/Users/nickb/.config/herd/bin/herd.phar/cli/includes/facades.php(22): Valet\Site->secure('herdtest.test', NULL, 368)
#5 phar://C:/Users/nickb/.config/herd/bin/herd.phar/cli/app.php(202): Facade::__callStatic('secure', Array)
#6 [internal function]: Silly\Application->{closure}(Object(Symfony\Component\Console\Output\ConsoleOutput), NULL, 368)
#7 phar://C:/Users/nickb/.config/herd/bin/herd.phar/vendor/php-di/invoker/src/Invoker.php(74): call_user_func_array(Object(Closure), Array)
#8 phar://C:/Users/nickb/.config/herd/bin/herd.phar/vendor/mnapoli/silly/src/Application.php(95): Invoker\Invoker->call(Object(Closure), Array)
#9 phar://C:/Users/nickb/.config/herd/bin/herd.phar/vendor/symfony/console/Command/Command.php(324): Silly\Application->Silly\{closure}(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 phar://C:/Users/nickb/.config/herd/bin/herd.phar/vendor/symfony/console/Application.php(1096): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 phar://C:/Users/nickb/.config/herd/bin/herd.phar/vendor/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand(Object(Silly\Command\Command), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 phar://C:/Users/nickb/.config/herd/bin/herd.phar/vendor/symfony/console/Application.php(175): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 phar://C:/Users/nickb/.config/herd/bin/herd.phar/cli/herd.php(8): Symfony\Component\Console\Application->run()
#14 C:\Users\nickb\.config\herd\bin\herd.phar(13): require('phar://C:/Users...')

**Comment by isimmons** [comment]
Windows 10 here, The site secured for me after clicking ok on 5 admin access prompts in a row. Now it won't un-secure. Prompts 2 times for admin access and then doesn't work.

**Comment by nbolink** [comment]
**Herd version 1.0.1**

Securing in the GUI gives no errors anymore but with the CLI command there is still an error.


```
C:\Users\nickb\Herd\herdtest> herd secure
Failed to trust certificate: 'powershell' is not recognized as an internal or external command,
operable program or batch file.

Restarting NGINX...
The [herdtest.test] site has been secured with a fresh TLS certificate.
```

And finally in the browser:
```
chrome: NET::ERR_CERT_AUTHORITY_INVALID

firefox: Error code: [SEC_ERROR_UNKNOWN_ISSUER](about:certerror?e=nssBadCert&u=https%3A//herdtest.test/&c=UTF-8&d=%20#certificateErrorDebugInformation)
```

**Comment by mpociot** [comment]
@nbolink The error message says "'powershell' is not recognized as an internal or external command"

Is there a reason you don't have powershell available on your system?

**Comment by mpociot** [comment]
> Windows 10 here, The site secured for me after clicking ok on 5 admin access prompts in a row. Now it won't un-secure. Prompts 2 times for admin access and then doesn't work.

What does "doesn't work" mean? Is the site still marked as secured when you run `herd secured`?

**Comment by isimmons** [comment]
Yes. Sorry to be vague. The site is still marked as secured. I've restarted Herd a couple of times and retried un-securing the site with the same result.  2 quick back to back prompts for admin access back to back. Then the Herd UI dims and looks like it's doing something for a second and then appears finished. But the site is still secured. 

I just realized I'm only assuming that clicking the locked lock button is supposed to unlock/unsecure the site. Is it supposed to be a toggle ?

**Comment by nbolink** [comment]
> @nbolink The error message says "'powershell' is not recognized as an internal or external command"
> 
> Is there a reason you don't have powershell available on your system?

there is no reason for that, 
I added the %SYSTEMROOT%\System32\WindowsPowerShell\v1.0\ to my path in the environment variables and that fixed the error in the CLI but the site in the browser is still unsecure
```
chrome: NET::ERR_CERT_AUTHORITY_INVALID

firefox: Error code: [SEC_ERROR_UNKNOWN_ISSUER](about:certerror?e=nssBadCert&u=https%3A//herdtest.test/&c=UTF-8&d=%20#certificateErrorDebugInformation)
```

**Comment by mpociot** [comment]
@nbolink Yeah I guess because of this, the root certificate was created but not properly trusted.
Delete this folder: `%USERPROFILE%\.config\herd\config\valet\CA\` and secure again 👍

**Comment by isimmons** [comment]
Sorry, at first I thought our issues were related. I'll post a separate issue for not able to unsecure site.

**Comment by mpociot** [comment]
@nbolink feel free to close the issue if it worked after deleting the certificates

**Comment by lmonteiro90** [comment]
thx @mpociot, but that didn't work for me. I had to open the certificate in this folder, trust it, and then run `herd secure` again.
