### ISSUE TITLE
[Bug]: Dumps aren't displayed in the Dumps window (Windows)

### ISSUE THREAD

**Issue by jrd-lewis** [beyondcode/herd-community#551]
### Platform

Windows

### Operating system version

Windows 11

### System architecture

Intel (x86)

### Herd Version

1.0.1

### Bug description

Follow up issue from #517

Calling `dump()` does intercept the dumped model(s) or text from appearing in the browser, after clicking the antenna button to turn on the interception. However, the dump does not appear in the Dumps window.

It seems like it may be unrelated to similar issues for others with the payload size.

### Steps to reproduce

- Add a call to `dump()` as part of a route.
- Turn on the dump interception by pressing the antenna icon in the Dumps window.
- Visit the route in the browser.

**Comment by IvanKovachev** [comment]
The same issue on 1.0.1. Intercepted, but not displayed in the Dumps window.

**Comment by mpociot** [comment]
Can you reproduce in a fresh laravel application created by "laravel new"?
Which PHP version are you using?

**Comment by jrd-lewis** [comment]
> Can you reproduce in a fresh laravel application created by "laravel new"? Which PHP version are you using?

I can reproduce the issue with a fresh Laravel application. I've mainly used PHP 8.3.4, but I tested it against PHP 8.2.17 too.

**Comment by mpociot** [comment]
There's a .sqlite file in the `%USERPROFILE%\.config\herd` folder which should store the incoming dumps. Could you upload that file?

I feel like this has something to do with some kind of firewall blocking the PHP application to send the dumps to Herd

**Comment by jrd-lewis** [comment]
[herd.zip](https://github.com/beyondcode/herd-community/files/14791488/herd.zip)

Had to attach it as a zip since GitHub didn't let me attach it directly.

**Comment by frasermurraysco** [comment]
I've got the same issue when using a browser (v1.0.1), however if I run a phpunit test it's shown in the dump window as expected.

**Comment by mpociot** [comment]
> I've got the same issue when using a browser (v1.0.1), however if I run a phpunit test it's shown in the dump window as expected.

Have you tried restarting the Herd services?

**Comment by frasermurraysco** [comment]
> > I've got the same issue when using a browser (v1.0.1), however if I run a phpunit test it's shown in the dump window as expected.
> 
> Have you tried restarting the Herd services?

Yes, it's made no difference.

**Comment by jrd-lewis** [comment]
> > I've got the same issue when using a browser (v1.0.1), however if I run a phpunit test it's shown in the dump window as expected.
> 
> Have you tried restarting the Herd services?

I can restart via the CLI this time unlike my attempt in the previous issue. Everything except "PHP-8.3 (Debug)" restarts fine; but that may be unrelated to the Dumps not being displayed, and I can manually restart it from within the GUI just fine. In any case, restarting the services doesn't resolve the issue for me.

Interestingly, it doesn't display dumps for me from a PHPUnit test either.

**Comment by dinhquochan** [comment]
@mpociot I've got the same issue when using a browser - when `dd` -> browser is blank and Herd shows nothing, phpunit test it's shown in the dump window as expected. 
I use the latest version, and PHP 8.2.

**Comment by Gelidan** [comment]
@mpociot I've the same issue. 
All are green, but the debug screen stays empty. 
From the blade it intercepts the @dd('string') but not shows it. From the controller it throws a 500 error, but the nginx error log stays empty (and the laravel log stays too).
If I turn off the dumps, everything works as used to be.

In the config path (C:\Users\xxx\.config\herd there is one  herd.sqlite file but it contains only the one test mail.

![image](https://github.com/beyondcode/herd-community/assets/13830917/8b448064-32cb-4dad-be6a-10f9b24a53d8)

**Comment by mpociot** [comment]
@Gelidan do you maybe have time for screen sharing so we can look at this together?

**Comment by Gelidan** [comment]
> @Gelidan do you maybe have time for screen sharing so we can look at this together?

Sure

**Comment by mpociot** [comment]
@Gelidan awesome - https://meet.google.com/rns-cidd-pxu

**Comment by mpociot** [comment]
I was finally able to figure out what's going on and this will be fixed in the next release 🎉 
Thanks again @Gelidan for taking the time 🙏

**Comment by Gelidan** [comment]
@mpociot Thanks for the help, hope it fixes for the others too. Keep it up!

**Comment by mpociot** [comment]
This is now fixed with Herd 1.1.0
