### ISSUE TITLE
[Bug]: Expose explaination contains a typo

### ISSUE THREAD

**Issue by Studio384** [beyondcode/herd-community#553]
### Platform

Windows

### Operating system version

Winodws 11, version 23H2, build 22631.3374

### System architecture

Windows

### Herd Version

1.0.1

### Bug description

A tiny error that bothers me a bit:

> Expose allows your to share your local site with others [...].

That first "your" should be "you".

**Comment by mpociot** [comment]
This is now fixed with Herd 1.1.0
