### ISSUE TITLE
[Bug]: PHP is not installed (Herd Pro)

### ISSUE THREAD

**Issue by asciito** [beyondcode/herd-community#557]
### Platform

Windows

### Operating system version

Windows 11 Pro - version 23H2 - build 22631.3296

### System architecture

Windows

### Herd Version

1.0.1

### Bug description

When I first installed Herd, I was asked to download PHP v8.3. Everything looked fine but I realized that PHP was not working, Even when I tried to install another version it wasn't possible, the PHP installation page/window kept loading and I could not do anything. 

**PHP page/window**
![image](https://github.com/beyondcode/herd-community/assets/63119899/96e656c8-6cd1-4888-9ed2-3c16ec0f4983)

When I looked for the `C:\<MY_USER_DIR>\.config\herd\bin\php83\php-cgi.exe`, the `php*` folder doesn't exist.

### Relevant log output

```shell
Error: spawn C:\<MY_USER_DIR>\.config\herd\bin\php83\php-cgi.exe ENOENT
```

**Comment by sschlein** [comment]
Since you have the Pro version, did activating the license work without issues? Does this installing a service work?

It sounds like Herd has no internet access 🤔

**Comment by d3st0y3r** [comment]
I have encountered this problem today, and the solution was simply to delete the whole folder which located in (C:\<MY_USER_DIR>\.config\herd\), then run Herd again, works fine.

**Comment by erkdgn** [comment]
> I have encountered this problem today, and the solution was simply to delete the whole folder which located in (C:<MY_USER_DIR>.config\herd), then run Herd again, works fine.

Thanks.

**Comment by asciito** [comment]
> I have encountered this problem today, and the solution was simply to delete the whole folder which located in (C:\<MY_USER_DIR>\.config\herd\), then run Herd again, works fine.  
> 
> 

Thanks for your help, if I get the same error in the future I will use this solution to solve it.

**Comment by pyquinnnarlo** [comment]
Delete the "herd" folder located in "C:\Users\your username \.config".
Next open the "herd" app and PHP will gets install automatically.

**Note: You need to be connected to the internet.**

**Comment by maxaltgithub** [comment]
In an absolute bizzare turn of events mine only worked if I deleted the afformentioned folder and also enabled a VPN. This in turn allowed the installer to download PHP 8.3.

**Comment by y0vche** [comment]
Issue is still unresolved. I have two installations of Herd on two machines running Windows 10 & 11 and none of them work as expected. I tried the above mentioned trick, with deleting the 'herd' folder but that did not work. The php>83 folder is empty. Tried to install a different version through Herd GUI but that just creates an empty folder, say empty folder 82. 

![herd php issue](https://github.com/beyondcode/herd-community/assets/70894119/35c3b973-4a37-4c50-8bc0-05c18c908828)

**Comment by dumprino** [comment]
Exclua a pasta "herd" localizada em "C:\Usuários\seu nome de usuário .config".
Em seguida, abra o aplicativo "herd" e o PHP será instalado automaticamente.

Observação: você precisa estar conectado à internet.

CONGRATULATIONS FRYEND !!!!!!!!!!!!!!!

**Comment by gadzooki87** [comment]
Win10. For me the issue was similar like with this friend (asciito). However when I coudn't delete the herd directory it wasn't because of ngnix process but herdHelper.exe that was in that folder. When I closed the herdHelper.exe in task manager (which was running by itself even after restarting the machine), I was able to delete the (C:<MY_USER_DIR>.config\herd) directory and restart the herd app, after which php was installed properly. Greetings and cheers!

(asciito) 
> > I have encountered this problem today, and the solution was simply to delete the whole folder which located in (C:<MY_USER_DIR>.config\herd), then run Herd again, works fine.
> 
> Thanks for your help, if I get the same error in the future I will use this solution to solve it.

**Comment by sschlein** [comment]
You can also delete the related php folder within the binaries folder from Herd and try to install php again via the UI.

**Comment by arezoofde** [comment]
I have this problem for two days. Thank you very much for your help.

**Comment by sschlein** [comment]
Would you all share the anti virus software that you use? I am pretty sure that there are similarities and the anti virus program messes with Herd data and binaries so that deleting the folder and installing them again fixes this. It should be helpful to exclude this directory from being scanned because Herd downloads exe files, etc and this might trigger suspicious warnings/actions.

**Comment by syedirtazahasnain** [comment]
how to install php 7.1 in Laravel Herd.?

**Comment by dinhhoangbaochan** [comment]
> Issue is still unresolved. I have two installations of Herd on two machines running Windows 10 & 11 and none of them work as expected. I tried the above mentioned trick, with deleting the 'herd' folder but that did not work. The php>83 folder is empty. Tried to install a different version through Herd GUI but that just creates an empty folder, say empty folder 82.
> 
> # ![herd php issue](https://private-user-images.githubusercontent.com/70894119/341086158-35c3b973-4a37-4c50-8bc0-05c18c908828.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0NDgzOTIsIm5iZiI6MTczNDQ0ODA5MiwicGF0aCI6Ii83MDg5NDExOS8zNDEwODYxNTgtMzVjM2I5NzMtNGEzNy00YzUwLThiYzAtMDVjMThjOTA4ODI4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDE1MDgxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhOTEyMWU4ZjcyOTc3MzljNTExZWI5ZjkyNmIwM2FhZjQxMjFlNGU4NGIyMDA4YTQxMTJlZTJkNTk5OGM0ZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pT7RnkSt-FJGgp7nZM4D7EJ8MTU8ZHygJQkXpXipz1U)
> Edit: My workaround is to manually install the desired PHP version in the corresponding Herd's folder.
> 
> Steps:
> 
> 1. Download the PHP version in zip from: https://windows.php.net/download/ Note: Make sure you pick the " Thread Safe" version
> 2. Unzip the folder, & move it's contents to C:\Users\YourUsername.config\herd\config\php\83 - this is for PHP v 8.3. If want for say version 8.2.3, create a folder named 82.
> 3. Have a cup of tea. You're good to go!

Even when I deleted the `herd` folder under `.config`, it didn't work. I tried out this solution and it worked.
