### ISSUE TITLE
[Feature Request]: Custom version of extension instead of bundled one

### ISSUE THREAD

**Issue by slovenianGooner** [beyondcode/herd-community#56]
### Feature Description

I am having some issues with an old API when trying to use the Http facade, because it doesn't use TLS1.2. I currently use curl version 7.8.* which allows to overcome that.

Herd is bundled with curl version 8.2.* which doesn't allow API calls if less than TLS1.1.

It would be nice if we could specify which curl to use.

**Comment by mpociot** [comment]
As curl is not a PHP "extension" but rather a built-in extension, there's no way for you to modify the version of it.

Maybe there's a curl/PHP ini setting in order to make this work for you? 
Using the latest version of curl feels better than using 7.8 though 😅

**Comment by slovenianGooner** [comment]
Sorry, yeah. That was my thought, that I won't be able to modify this in any way.

I mean, ideally I'd use 8.* but the older API fails then. Guess I'm stuck with Valet until we ditch the project using the old API :)
