### ISSUE TITLE
[Bug]:  herd and php not recognized from git bash terminal 

### ISSUE THREAD

**Issue by peter-emad99** [beyondcode/herd-community#564]
### Platform

Windows

### Operating system version

Window 11 23h2

### System architecture

Windows

### Herd Version

1.0.1

### PHP Version

8.3

### Bug description

when trying to access php or herd cli from git bash terminal on windows  ..it didn't recognize them

**Comment by mpociot** [comment]
Please use php.bat and herd.bat instead 👍

**Comment by peter-emad99** [comment]
thanks it worked .. i created aliases in .bash_profile for them
```
# for herd on windows
alias php="php.bat"
alias herd="herd.bat"
alias laravel="laravel.bat"
alias composer="composer.bat"
```
