### ISSUE TITLE
[Bug]: Incorrect PHP config in debug mode

### ISSUE THREAD

**Issue by johnluxor** [beyondcode/herd-community#565]
### Platform

Windows

### Operating system version

11

### System architecture

Windows

### Herd Version

1.0.1

### PHP Version

8.2

### Bug description

When PHP is in debug mode it uses a different config, than in regular mode.
The problem is that debug.ini config does not contain any php configs beside xdebug.

My config:
```
zend_extension=C:\Users\user\.config\herd\bin\xdebug\xdebug-8.2.dll
xdebug.mode=debug,develop
xdebug.start_with_request=yes
xdebug.start_upon_error=yes
```

So, in debug mode, PHP doesn't have any extensions enabled and all configs are set in default values

**Comment by lucasromanojf** [comment]
Is there any workaround for this?

**Comment by mechelon** [comment]
We will fix that in an upcoming release - you can activate the extension inside the debug.ini as a workaround.
