### ISSUE TITLE
[Bug]: Running herd commands in bash shell doesn't work

### ISSUE THREAD

**Issue by frasermurraysco** [beyondcode/herd-community#568]
### Platform

Windows

### Operating system version

Windows 11

### System architecture

Intel (x86)

### Herd Version

1.0.1

### Bug description

Running herd commands in bash shell doesn't work, need to run herd.bat

### Steps to reproduce

herd use 8.2

### Relevant log output

```shell
No such file or directory
```

**Comment by mpociot** [comment]
Please create a bash alias in this case https://github.com/beyondcode/herd-community/issues/564#issuecomment-2027188579
