### ISSUE TITLE
[Bug]: Nginx won't start anymore after securing site, after unsecuring and deleting site still does not work

### ISSUE THREAD

**Issue by Mikail-1022063** [beyondcode/herd-community#569]
### Platform

Windows

### Operating system version

Windows 10 22H2 19045.4170

### System architecture

Windows

### Herd Version

1.0.1

### PHP Version

8.3.4

### Bug description

Nginx log: 2024/03/30 01:46:45 [emerg] 5388#8608: bind() to 127.0.0.1:443 failed (10013: An attempt was made to access a socket in a way forbidden by its access permissions)

This suddenly happend after securing a site, after unsecuring unlinking and deleting still happens.

**Comment by Mikail-1022063** [comment]
After removing the site certs and nginx config, it works again. But securing the site again gives me again the same nginx error: 2024/03/30 01:55:10 [emerg] 20628#27552: bind() to 127.0.0.1:443 failed (10013: An attempt was made to access a socket in a way forbidden by its access permissions)

**Comment by Mikail-1022063** [comment]
Yes so after securing a site, nginx goes on red and when i check the log it gives the error in my last comment.

**Comment by mpociot** [comment]
@Mikail-1022063 The error message means that something else is already running on port 443 so that Herd/nginx is unable to bind to that port.
Please stop any existing web-servers/services that could use that port.
