### ISSUE TITLE
[Bug]: nginx dyld library not loaded

### ISSUE THREAD

**Issue by gtmassey** [beyondcode/herd-community#57]
### Operating system version

macOS Monterey 12.6

### System architecture

Intel (x86)

### Herd Version

1.0.8 (Build 10)

### Bug description

Before installing Herd, I uninstalled Homebrew and all brew packages, and I wanted to start fresh. I installed Herd, and after following the installation instructions, nginx cannot start. I have tried uninstalling Herd and reinstalling it, and I have also tried stopping the services through the Herd menu and restarting them. Neither attempts have succeeded.

### Steps to reproduce

1. Uninstall Homebrew
2. Force rm any brew files, directories, casks, etc
3. Install Herd

### Relevant log output

```shell
dyld[99526]: Library not loaded: 'usr/local/opt/pcre2/lib/libpcre2-8.0dylib'
    Referenced from: '/Applications/Herd.app/Contents/Resources/nginx-x86'
    Reason: tried: '/usr/local/opt/pcre2/lib/libpcre2-8.0.dylib' (no such file), '/usr/lib/libpcre2-8.0.dylib' (no such file)
```

**Comment by mpociot** [comment]
Yeah, I just noticed this as well. The arm64 library does have all dependencies included. I'll fix this in tomorrow's Herd release - sorry about that 👍

**Comment by basherdesigns** [comment]
Same error for me, thanks for responding to this issue!

**Comment by mpociot** [comment]
This is now fixed in Herd 1.1.0

**Comment by gtmassey** [comment]
Just updated and it works beautifully!

**Comment by Quaap70** [comment]
works perfectly now!
