### ISSUE TITLE
 [Bug]: Install NVM click not working (Herd Pro)

### ISSUE THREAD

**Issue by sudip-fe** [beyondcode/herd-community#573]
### Platform

Windows

### Operating system version

Windows 11

### System architecture

Windows

### Herd Version

1.0.1

### Bug description

After Uninstall and Reinstall node not install automatically. And install NVM click also not working. Please check the video.

### Steps to reproduce

[screen-capture.webm](https://github.com/beyondcode/herd-community/assets/141113076/f824d1d3-402e-4b46-ac85-88fca949b1f4)

**Comment by amindu-fe** [comment]
Same issue for me today. (Herd Pro)

**Comment by mpociot** [comment]
@sudip-fe Can you share the contents of your `%USERPROFILE%\AppData\Roaming\herd\logs\main.log` file?

**Comment by ccsliinc** [comment]
Same here on a Mac M1

**Comment by zedix** [comment]
Same here on Mac M1 (Sonoma 14.3, Herd 1.5.0). Can share a log if you tell me the file path.

**Comment by sudip-fe** [comment]
I fixed this at my end. The issue is if system has previously installed NodeJS. Then herd can't install there NodeJS version. After i uninstall previously installed NodeJS and removed all node related environment variable I can install node from herd. But this process not present in installation doc.

**Comment by croustibat** [comment]
I've found that Install NVM button is not working on macos with Bash as default interpreter. I made it working by swtiching to zsh, removing ~/Library/Application\ Support/Herd/config/nvm, and re-click on Install NVM finally works !

**Comment by davidbarker** [comment]
I fixed it on my system by temporarily removing my `~/.zshrc` file.

https://github.com/beyondcode/herd-community/issues/787#issuecomment-2192606573

**Comment by renzocastillo** [comment]
@mpociot I'm experiencing the same issue with Herd Pro 1.1.10 at W11.

Here are my logs:

[2024-09-15 12:29:50.421] [info]  [NodeVersionManager] installedNodeVersions: 
[2024-09-15 12:29:50.421] [info]  [NodeVersionManager] parseNodeVersionList: [ '' ]
[2024-09-15 12:29:50.421] [info]  [NodeVersionManager] installedNodeVersions: 
ERROR open C:\Users\renzo\.config\herd\bin\nvm\settings.txt: The system cannot find the file specified.

[2024-09-15 12:29:50.422] [info]  [NodeVersionManager] parseNodeVersionList: [
  '',
  'ERROR open C:\\Users\\renzo\\.config\\herd\\bin\\nvm\\settings.txt: The system cannot find the file specified.',
  ''
]
[2024-09-15 12:29:51.650] [info]  [NodeVersionManager] install: 
[2024-09-15 12:29:51.651] [info]  [NodeVersionManager] install: 
ERROR open C:\Users\renzo\.config\herd\bin\nvm\settings.txt: The system cannot find the file specified.

[2024-09-15 12:29:51.840] [info]  [NodeVersionManager] installedNodeVersions: 
[2024-09-15 12:29:51.840] [info]  [NodeVersionManager] parseNodeVersionList: [ '' ]
[2024-09-15 12:29:51.840] [info]  [NodeVersionManager] installedNodeVersions: 
ERROR open C:\Users\renzo\.config\herd\bin\nvm\settings.txt: The system cannot find the file specified.

[2024-09-15 12:29:51.841] [info]  [NodeVersionManager] parseNodeVersionList: [
  '',
  'ERROR open C:\\Users\\renzo\\.config\\herd\\bin\\nvm\\settings.txt: The system cannot find the file specified.',
  ''
]

I don't have any environmental variables for any node version.

**Comment by renzocastillo** [comment]
@mpociot I just tried to delete the entire nvm directory from `%USERPROFILE%\.config\herd\bin` and then returned to the Herd GUI. I was prompted with a clean interface asking me to reinstall Node JS from scratch. I followed the prompt and now I'm able to install any Node JS version.
