### ISSUE TITLE
[Bug]: Restore CLI functionality after ohmyzsh install

### ISSUE THREAD

**Issue by KiritoXD01** [beyondcode/herd-community#58]
### Operating system version

macOS Ventura 13.5

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.0.8

### Bug description

This is more of an advice for people who started fresh and installed Herd and them when to install ohmyzsh which overwrites the `.zshrc` file, then PHP, composer and the laravel installer won't work, here is what you need to do:

After you install ohmyzsh, go to the .zshrc file and add this at the end:

`export PATH="/Users/YOUR USER/Library/Application Support/Herd/bin/":$PATH
export PHP_INI_SCAN_DIR="/Users/YOUR USER/Library/Application Support/Herd/config/php/":$PHP_INI_SCAN_DIR`

Remember to replace your user with your actual user, or use the env variable (I don't remember it)

### Steps to reproduce

Install Laravel Herd and then ohmyzsh

**Comment by mpociot** [comment]
I'll make sure to add this to the documentation, thanks for bringing it up!
