### ISSUE TITLE
[Bug]: Open last visited path in tinker shortcut conflicts with browser shortcuts

### ISSUE THREAD

**Issue by Donneh** [beyondcode/herd-community#583]
### Platform

Windows

### Operating system version

Windows 11 (23H2 22631.3296)

### System architecture

Windows

### Herd Version

1.0.1

### Bug description

Trying to open the recently closed tab in your webbrowser with the Ctrl+shift+T shortcut no longer works when you have herd running. This is because the same shortcut is used by herd for opening the last visited site path in tinker/tinkerwel.

I think it would be a good idea to change the default shortcut for this.

### Steps to reproduce

- Run Herd on windows
- Open chrome/edge/firefox
- Try to reopen closed tab with the Ctrl+Shift+T shortcut

**Comment by mpociot** [comment]
This is now fixed with Herd 1.1.0
