### ISSUE TITLE
[Bug]: Bad Gateway on just one route

### ISSUE THREAD

**Issue by ulfie22** [beyondcode/herd-community#584]
### Platform

macOS

### Operating system version

macOS Sonoma 14.3.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.5 build 23

### Bug description

When I try to access one route of my site `/search` I get a 502 Bad Gateway error. All other routes are working correctly. The error in the nginx log is
```
 [error] 91186#27758597: *1 upstream prematurely closed connection while reading response header from upstream, client: 127.0.0.1, server: , request: "GET /search HTTP/1.1", upstream: "fastcgi://unix:/Users/andy/Library/Application Support/Herd/herd-debug.sock:", host: "zmr.test"
```
The herd sockets are correctly linked. I do not understand what would cause this error on just one route - the route works correctly on non-Herd machines (Windows environment, Vapor) but not here. Help please! Thank you!

**Comment by mechelon** [comment]
Is the site using a custom PHP version or was secured? Usually a bad gateway means that the PHP process is not running properly

**Comment by ulfie22** [comment]
Thanks for your response. I am using PHP 8.3 that comes with Herd. Literally EVERY other route works correctly - just this one route gets the Bad Gateway error.

**Comment by ulfie22** [comment]
I finally sorted this out - it turns out that many levels deep in the initialization for the Livewire component on this page there was a query which was consistently causing a memory error. This error did not get logged or cause a Flare but it somehow did trigger the Bad Gateway error. I'm not sure what or if something could be done differently in the stack to help detect this.
