### ISSUE TITLE
502 bad gateway 

### ISSUE THREAD

**Issue by altugsogutoglu** [beyondcode/herd-community#585]
### Platform

Windows

### Operating system version

Windows 11

### System architecture

Windows

### Herd Version

1.4

### PHP Version

Php 8.3

### Bug description

I installed Hard a week ago with no problems but today i wanted to visit a site i created and i got a 502. And i got the same issue for all other sites. But the services are running and i uninstalled it and restarted several times with no succes

**Comment by mechelon** [comment]
Is the site using a custom PHP version or was secured? Usually a bad gateway means that the PHP process is not running properly. Can you post the PHP and nginx logs if there's anything in it?

**Comment by altugsogutoglu** [comment]
@mechelon , im trying to get the logs but each time i look into it it says no logs found. I have to figure out how i can get the logs first (Thanks for replying btw)

**Comment by altugsogutoglu** [comment]
@mechelon it seems like i still had Valet installed for Windows. After uninstalling, removing and restarting i installed Laravel Herd again and its working fine now. (i thought i deleted valet)
