### ISSUE TITLE
[Bug]: One specific sites isolation to 7.4 changes all other sites php version

### ISSUE THREAD

**Issue by inevat** [beyondcode/herd-community#586]
### Platform

macOS

### Operating system version

14.4.1 (23E224)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.5.0 (Build:23)

### Bug description

For most sites, isolating to a specific version does not affect any other sites, but one specific site on my system changes all other sites php version. Unisolating and renaming the site i can then isolate without issue. Valet was previously installed on the system.

### Steps to reproduce

1. Isolate site when named original xxx.com.test to a specific version of php (7.4)
2. Try to access any other site (site will show php being the isolated version of php)
3. Change isolated sites version of php
4. All other sites will have that same version
5. Unisolate and rename site
6. Isolate site again with new name and all works as intended.

**Comment by mpociot** [comment]
I'm having a hard time reproducing this.
And this only happens with this specific site? Could you share the site name with me? Feel free to share it privately by sending me a DM if you want: https://twitter.com/marcelpociot
