### ISSUE TITLE
[Bug]: Herd Share for domain

### ISSUE THREAD

**Issue by iEXExchanger** [beyondcode/herd-community#587]
### Platform

Windows

### Operating system version

Windows 11

### System architecture

Windows

### Herd Version

1.1

### PHP Version

PHP 8.2

### Bug description

When running "herd share", everything works fine.
But when I run "herd share https://domain.test", the command line closes automatically

**Comment by mechelon** [comment]
We will fix that in an upcoming release. In the meantime, you should be able to use the `expose`  binary itself, e.g. `expose share https://example-app.test`.

**Comment by mpociot** [comment]
This is now fixed with Herd 1.1.0
