### ISSUE TITLE
[Bug]: Installing additional PHP Extensions - docs incorrect?

### ISSUE THREAD

**Issue by CNSam** [beyondcode/herd-community#588]
### Platform

Windows

### Operating system version

Windows 11

### System architecture

Intel (x86)

### Herd Version

1.0.1

### PHP Version

PHP 8.3

### Bug description

Unless I am missing something I believe the docs for installing additional PHP Extensions on the Windows platform are incorrect as we can't install Homebrew on Windows?

Can an accepted approach for adding new extensions for PHP to Windows be shared please?

**Comment by mechelon** [comment]
Hey there - looks like you got to the Mac docs for some reason 🤔  Installing PHP extensions on Windows is explained here: https://herd.laravel.com/docs/windows/1/advanced-usage/additional-extensions

**Comment by CNSam** [comment]
Thanks a million!
