### ISSUE TITLE
[Bug]: Error With Previous Environments

### ISSUE THREAD

**Issue by rmunate** [beyondcode/herd-community#59]
### Operating system version

MAC Ventura 13.4

### System architecture

Intel (x86)

### Herd Version

1.0.8

### PHP Version

PHP 8.1 / PHP8.2

### Bug description

In my team for a long time I have been working with manual installation, in fact this article "https://getgrav.org/blog/macos-ventura-apache-multiple-php-versions" was the one I used when I bought my last computer, I really liked this new tool but when I installed it I found many things that prevented my work when compared to the previous manul configuration.

1. Even if I do a dd() in the Laravel code, it returns a 200 response to the console. It should be a 500. AJAX requests

2. The projects connect to SQLServer but I can't find a way to install the extensions.

3. I must configure openSSL manually and I can't find how to adjust it within HEARD "Some lines must be adjusted"

4. I don't have access to the localhost IP and I have some script that I run entering the route from the base. there should be a unified access point.

I would gladly contribute from my knowledge.

### Steps to reproduce

Most likely, this error will happen on machines where they already had an environment mounted similar to the one in this link "https://getgrav.org/blog/macos-ventura-apache-multiple-php-versions" I clarify that this link I found browsing the internet and my current configuration remains with after uninstalling Herd is the one shown in that guide

**Comment by mpociot** [comment]
You can now install custom PHP extensions by following the documentation: https://herd.laravel.com/docs/1/advanced-usage/additional-extensions

The OpenSSL configuration can not yet be modified manually, please see #148
