### ISSUE TITLE
[Bug]: XDebug not loading when using Browser extensions in Profile / Trace mode (Herd Pro)

### ISSUE THREAD

**Issue by o1y** [beyondcode/herd-community#591]
### Platform

macOS

### Operating system version

macOS Sonoma 14.2.1 (23C71)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.5.0

### PHP Version

PHP 8.2.16

### Bug description

I'm using Herd Pro. When using the XDebug helper extension for Firefox, Herd automatically loads the XDebug php extension when enabling debug mode, but not when I want to create a profile or trace. The readme states that `Once you enable an Xdebug feature [...] Herd serves the request via a PHP process with an enabled Xdebug extensions`. Unfortunately, that's only the case for the Debug Feature, not Profile / Trace.

### Steps to reproduce

1. Buy Herd Pro
2. Install Firefox XDebug helper
3. Click on Profile or Trace
4. Xdebug extension is not loaded

**Comment by mpociot** [comment]
This fixed with Herd 1.6.0
