### ISSUE TITLE
[Bug]: Install Herd, Create new site, click to open in browser. Error: could not find driver

### ISSUE THREAD

**Issue by greggh** [beyondcode/herd-community#594]
### Platform

Windows

### Operating system version

Windows 11

### System architecture

Intel (x86)

### Herd Version

1.0.1

### PHP Version

PHP 8.3.4

### Bug description

This is my first use. I tried to start a new site and got an error page. I was expecting it to work. Obviously, I can sit here and debug for a while, but I don't think this is expected behavior.

Edit: adding more info, during the creation of the site I can see the sqlite get created and the migration runs fine. If I switch over to MySQL, create the database, and then run the migration it also runs fine. So in artisan that's working.

### Steps to reproduce

1. Install Herd, add pro license.
2. Click on Sites
3. Click the +
4. No Starter Kit, name the site
5. Let it finish creating, click "open in browser"
6. Get error message in Ignition, "[could not find driver (Connection: sqlite, SQL: PRAGMA foreign_keys = ON;)](http://testing.test/#top)"

**Comment by greggh** [comment]
Followup. It happens when debug is on. I am using the xdebug helper chrome extension. Whenever that is on many PHP extensions don't get loaded. It's not even trying to load a php.ini with all the settings, just the debug.ini that only loads xdebug and nothing else.

**Comment by sschlein** [comment]
We currently have a problem with the php ini file for Xdebug - this has been fixed and will be released early next week.

In the meantime, I recommend not using Xdebug in thw browser. You can also modify the debug.ini file and load the extensions there but this will likely break again in the next release when the fix for the problem breaks this workaround.

**Comment by mpociot** [comment]
This is now fixed with Herd 1.1.0
