### ISSUE TITLE
[Bug]: The Herd Desktop application is not running. Please start Herd and try again.

### ISSUE THREAD

**Issue by Cegem-360** [beyondcode/herd-community#595]
### Platform

Windows

### Operating system version

Windows 11, version 23H2

### System architecture

Intel (x86)

### Herd Version

1.1.0

### PHP Version

8.3

### Bug description

In fresh install or reinstall, any time i want use GUI sites page infinite loading happening, but  i see the application GUI is active and small icon also useable and active. 

### Steps to reproduce

Any version after install cant use sites page. And after i open GUI the sites page showing this 
![image](https://github.com/beyondcode/herd-community/assets/144362694/6b634ff9-4d43-4506-b3cf-7822b086566d)
The Cmd promt say this.
![image](https://github.com/beyondcode/herd-community/assets/144362694/c898a495-6b25-4e30-8fc8-81c96b0a5e29)
![image](https://github.com/beyondcode/herd-community/assets/144362694/a7febe96-04c8-4317-9307-154f959ffae1)

### Relevant log output

```shell
[2024-04-03 00:19:56.950] [info]  Stopping NGINX
[2024-04-03 00:19:56.950] [info]  Stopping NGINX with PID 9952
[2024-04-03 00:19:57.145] [info]  Stopped NGINX
[2024-04-03 00:19:57.146] [info]  Stopping Mail
[2024-04-03 00:19:57.146] [info]  Stopping Dumps
[2024-04-03 00:19:57.147] [info]  Notifying windows of service update: Dumps - inactive
[2024-04-03 00:19:57.157] [info]  Stopping PHP-8.3
[2024-04-03 00:19:57.158] [info]  Stopping PHP-8.3 with PID 8252
[2024-04-03 00:19:57.356] [info]  Stopped PHP-8.3
[2024-04-03 00:19:57.664] [info]  [Mails] stopped inactive
[2024-04-03 00:19:57.664] [info]  Notifying windows of service update: Mail - inactive
[2024-04-03 00:19:57.677] [info]  NGINX exited
[2024-04-03 00:19:57.677] [info]  Deleted PID file C:\Users\Tulajdonos\.config\herd\.pid\nginx.pid
[2024-04-03 00:19:57.678] [info]  Notifying windows of service update: NGINX - inactive
[2024-04-03 00:19:57.679] [info]  PHP-8.3 exited
[2024-04-03 00:19:57.680] [info]  Deleted PID file C:\Users\Tulajdonos\.config\herd\.pid\php-8_3.pid
[2024-04-03 00:19:57.680] [info]  Notifying windows of service update: PHP-8.3 - inactive
[2024-04-03 00:19:57.682] [info]  PHP-8.3 exited with code 1 - PID: 8252
[2024-04-03 00:19:57.682] [info]  Notifying windows of service update: PHP-8.3 - inactive
[2024-04-03 00:19:57.683] [info]  NGINX exited with code 1 - PID: 9952
[2024-04-03 00:19:57.684] [info]  Notifying windows of service update: NGINX - inactive
[2024-04-03 00:19:58.335] [info]  [nginx] Starting Nginx...
[2024-04-03 00:19:58.336] [info]  [nginx] Config: C:\Users\Tulajdonos\.config\herd\config\nginx\nginx.conf
[2024-04-03 00:19:58.343] [info]  log-pid.
[2024-04-03 00:19:58.344] [info]  Wrote PID (19572) to C:\Users\Tulajdonos\.config\herd\.pid\nginx.pid
[2024-04-03 00:19:58.372] [info]  Starting CGI
[2024-04-03 00:19:58.373] [info]  [PHP] Starting PHP 83 on port 9083
[2024-04-03 00:19:58.375] [info]  [PHP] Path: C:\Users\Tulajdonos\.config\herd\bin\php83\php-cgi.exe
[2024-04-03 00:19:58.381] [info]  log-pid.
[2024-04-03 00:19:58.382] [info]  Wrote PID (21628) to C:\Users\Tulajdonos\.config\herd\.pid\php-8_3.pid
[2024-04-03 00:19:58.398] [info]  Started NGINX with PID 19572
[2024-04-03 00:19:58.399] [info]  Notifying windows of service update: NGINX - active
[2024-04-03 00:19:58.400] [info]  Started PHP-8.3 with PID 21628
[2024-04-03 00:19:58.401] [info]  Notifying windows of service update: PHP-8.3 - active
[2024-04-03 00:19:58.403] [info]  Watching paths:  [ 'C:\\Users\\Tulajdonos\\Herd', 'D:\\herd' ]
[2024-04-03 00:19:58.414] [info]  Hosts watcher ready
[2024-04-03 00:19:58.417] [info]  Updating hosts file via HerdHelper Windows Service
```

**Comment by Cegem-360** [comment]
Sue,
![image](https://github.com/beyondcode/herd-community/assets/144362694/c81bf09f-546a-472f-836e-707053af3eda)
![image](https://github.com/beyondcode/herd-community/assets/144362694/3fca9c7f-e651-4ff8-bec9-857909b78053)

**Comment by Cegem-360** [comment]
I tried different port to see change anyting, but only that happend is the HerdHelper turned red. When i changed back then turned back to green.

**Comment by Cegem-360** [comment]
I find this error to
![image](https://github.com/beyondcode/herd-community/assets/144362694/6513610d-ba25-45b5-86ca-b8da8c72ab18)

**Comment by WillieHuizing** [comment]
Hello,

I am facing the same problem altough I'm using Herd Pro.
When I try to view Sites or try to use the log view I'm getting this error:  

```
Error occurred in handler for 'log-viewer.fetch-sites': Error: Command failed: "C:\Users\whu\.config\herd\bin\php83\php.exe" "C:\Users\whu\.config\herd\bin\herd.phar" parked --json


  Command "parked" is not defined.

    at ChildProcess.exithandler (node:child_process:422:12)
    at ChildProcess.emit (node:events:517:28)
    at maybeClose (node:internal/child_process:1098:16)
    at ChildProcess._handle.onexit (node:internal/child_process:303:5) {
  code: 1,
  killed: false,
  signal: null,
  cmd: '"C:\\Users\\whu\\.config\\herd\\bin\\php83\\php.exe" "C:\\Users\\whu\\.config\\herd\\bin\\herd.phar" parked --json'
}
```

**Comment by DCrepper** [comment]
This can be solved by installing by https://github.com/cretueusebiu/valet-windows, on PHP 8.1, not have 8.2 or 8.3 support yet.

**Comment by DCrepper** [comment]
I changed the port to different like 9010, 9110. Restart the servies and the application. but still i get this error. I restarted the computer nothig happend. When close the app in mini icon. Then i start the app from Administrator cli 
![image](https://github.com/beyondcode/herd-community/assets/72586295/99c4b4f7-7c9e-4938-9d80-976da37db3ff)
i get this and still herd isn't working accordingly.

**Comment by DCrepper** [comment]
i get this from consol also 
![image](https://github.com/beyondcode/herd-community/assets/72586295/192515d0-4a50-4e1c-aedd-a6839b487358)
and the Sites page is frozen and closed my app

**Comment by WillieHuizing** [comment]
I had a program listening on port 9001 so thank you @mpociot for pointing this out.   

For others. In your terminal / cmd type in the command `netstat -ab` and look for a process   
that is listening on 9001. If you close the app the problem will be solved without needing to   
change the port.

**Comment by DCrepper** [comment]
Only herd run on:
![image](https://github.com/beyondcode/herd-community/assets/72586295/257650f7-6e8c-44a3-88c2-2c7749bffde7)

**Comment by WillieHuizing** [comment]
Does `netstat -ab | findstr 9001` show you any results?  
I guess there could be more than 1 reason as to why this isn't working.

**Comment by DCrepper** [comment]
php-cgi.exe run on 9001
![image](https://github.com/beyondcode/herd-community/assets/72586295/4617cc9c-69db-4d2d-b1b3-191a28e44f0b)

**Comment by WillieHuizing** [comment]
@DCrepper   
Maybe change the port back to 9001?   
I'm assuming it's being used now because the default port has changed and it uses the available ports to run
services. But that would imply that changing the default port is whats causing this issue for you. At this point  
I'm just guessing though.

I had a HP process running that used port 9001. Removing it solved my problem.

**Comment by DCrepper** [comment]
If i change back to 9001. Then this:
![image](https://github.com/beyondcode/herd-community/assets/72586295/0a98c112-6377-42a5-9056-397dca4f705d)

**Comment by WillieHuizing** [comment]
What does `netstat -ab | findstr 9001` show you now?

**Comment by DCrepper** [comment]
laravel herd.exe runing, if i switching to sites page then more www:9001 liseners come
![image](https://github.com/beyondcode/herd-community/assets/72586295/28b75633-731c-4787-bb0c-0fa0302018b9)

**Comment by DCrepper** [comment]
@WillieHuizing  Now only herd exe runing but when i go to sites page then more liseners come online.
![image](https://github.com/beyondcode/herd-community/assets/72586295/731f0db5-5a91-42c8-ad90-a220bd70f4d3)

**Comment by DCrepper** [comment]
![image](https://github.com/beyondcode/herd-community/assets/72586295/9638485a-095e-413b-ac0f-53f609fbabfc)

**Comment by thatgardnerone** [comment]
Have you previously installed Laravel Valet (for Windows)?

Removing the valet from my Windows directory at `C:\Users\<username>\.config\valet` and restarting my PC solved this issue.

**Comment by Cegem-360** [comment]
@thatgardnerone No, it was not installed before :˙(

**Comment by thatgardnerone** [comment]
@Cegem-360 try checking the ports in use via the Resource Monitor (Windows - R, "resmon.exe") and head to the Network tab. 

Listening Ports at the bottom of the window will show you all services, similar to the netstat commands mentioned above. Check that it's definitely Herd.exe using 9001.

**Comment by Cegem-360** [comment]
@thatgardnerone im sue the 9001 is the only one 
![image](https://github.com/beyondcode/herd-community/assets/144362694/f86d0319-1945-4d28-b66f-42dfa844b0de)

**Comment by Cegem-360** [comment]
@thatgardnerone And the valet is working like in the prtScr
![image](https://github.com/beyondcode/herd-community/assets/144362694/dbc175a5-5383-4bc8-b647-358ad1ce277f)

**Comment by thatgardnerone** [comment]
> @thatgardnerone And the valet is working like in the prtScr only the Sites screen is freezing then loading infinitly
> 

Just checking @Cegem-360, you've said "valet is working" in that screenshot. Do you have valet installed separately? Or did you mean Herd?

If you have valet installed, it'll be in the `.config/valet` folder I mentioned previously, and you'll need to remove it.

**Comment by Cegem-360** [comment]
@thatgardnerone No, valet isn't installed installed separately.

**Comment by Claudao01** [comment]
I think I’ve found a workaround for the empty Sites page on Windows 11:

- I opened the terminal and used ‘cd <path>’ to navigate to the location where my projects will be, replace <path> with your own path
- I executed ‘herd link’
- I finished Herd in the notification bar and opened it again

After doing this, one of the folders appeared in the Sites menu. Then I clicked on the ‘+’ button and created a new project. The page that previously went straight to ‘open on browser’ started to bring creation logs, and a folder was created in my chosen path with all the standard files of the new project.

Maybe this will help

**Comment by Cegem-360** [comment]
> I think I’ve found a workaround for the empty Sites page on Windows 11:
> 
> * I opened the terminal and used ‘cd S:\’ to navigate to the location where my projects will be, replace with your own path
> * I executed ‘herd link’
> * I finished Herd in the notification bar and opened it again
> 
> After doing this, one of the folders appeared in the Sites menu. Then I clicked on the ‘+’ button and created a new project. The page that previously went straight to ‘open on browser’ started to bring creation logs, and a folder was created in my chosen path with all the standard files of the new project.
> 
> Maybe this will help

![image](https://github.com/beyondcode/herd-community/assets/144362694/e4936ad3-cb30-411a-9809-10bf532fa5c1)
Sadly nothing changed :(

**Comment by sschlein** [comment]
I am pretty sure I've fixed that problem today. Can you all please verify if there is something (not Herd) on port 9001? 

There was a situation where a changed setting in the app wasn't used and so the herd cli couldn't connect to the app with the error of this issue.

**Comment by Cegem-360** [comment]
im 100% sue nothing else runing on 9001 
![image](https://github.com/beyondcode/herd-community/assets/144362694/113e5700-7ef7-46d6-be57-4b5b6f08fd50)

**Comment by ivanmafl** [comment]
I know this solution to the problem will probably only apply to me, but what worked for me was to remove the extension in php.ini. Specifically for ImageMagick, which I had previously installed.
