### ISSUE TITLE
[Bug]: DNS errors when accessing *.test

### ISSUE THREAD

**Issue by lukvec** [beyondcode/herd-community#599]
### Platform

macOS

### Operating system version

macOS Sonoma 14.4.1

### System architecture

Intel (x86)

### Herd Version

1.5.0

### Bug description

I've recently downloaded Herd (unpaid version) to try it out. To get all of the systems (Nginx and DNSMasq) running I had to close all nginx tasks and removed dnsmasq from homebrew. Afterwards, the X.test website became inaccessible with errors: DNS_PROBE_FINISHED_NXDOMAIN (when using Google) and DNS_PROBE_POSSIBLE (when using Brave). I tried reinstalling Herd and dnsmasq with homebrew, however, I'm still not able to reach the website of my project. Although, this may not be a bug, I would be very thankful for every advice on how to solve this issue.

**Comment by sschlein** [comment]
Hey @lukvec – is dnsmasq running on your machine? Does nginx work? You should see this when clicking on the Herd icon.

Completely removing it from homebrew also sounds a bit hard, stopping the service would have been enough.

**Comment by lukvec** [comment]
@sschlein, yes, both, dnsmasq and nginx are running. I tried to stop dnsmasq after getting errors, but I wasn't able to, that's why I tried to uninstall it from homebrew

**Comment by sschlein** [comment]
Is there a test file at `/etc/resolver/` ? if yes, what's in this file?

How do you check if they are running? Are there processes in the activity manager or can you see green icons in Herd?

**Comment by lukvec** [comment]
I'm sorry, I'm kinda new to this. I was trying to find the path `/etc/resolver/`, but I wasn't able to. Could you please tell me how can I check this path? Also, nginx and dnsmasq are not only green in Herd, I've also found the processes in activity manager.

**Comment by sschlein** [comment]
you can go to your terminal and do `cd /etc/resolver` or `nano /etc/resolver/test`

This should open the file in the terminal and display something like 127.0.0.1

**Comment by lukvec** [comment]
My system doesn't have the directory `/etc/resolver/ `. `nano /etc/resolver/test` opens a blank file in terminal.

**Comment by sschlein** [comment]
Ok, sounds like this was removed somehow during one of your uninstall actions. I suggestion would be to install Herd from scratch after you've made sure to follow the uninstall instrcutions from https://herd.laravel.com/docs/1/troubleshooting/uninstalling

You can also try to create the directory and file and add 
`nameserver 127.0.0.1` to it but my advice would be to install herd again because I have no idea if there are other side effects.

**Comment by lukvec** [comment]
I reinstalled Herd according to the instructions and everything works perfectly. Thank you for your time and helpful advice.

**Comment by sschlein** [comment]
Sounds like a great opportunity to pitch the Pro version 😂

**Comment by lukvec** [comment]
This was the only thing stopping me from getting Pro version 😁 that's why I'm glad for your quick and helpful response. TY 👍
