### ISSUE TITLE
[Bug]: Patches don't work with Herd

### ISSUE THREAD

**Issue by iruoy** [beyondcode/herd-community#61]
### Operating system version

macOS Ventura 13.4.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.0.8 (Build: 10)

### PHP Version

PHP 8.2.8 (cli) (built: Jul 24 2023 11:48:23) (NTS)

### Bug description

When applying patches during `composer install` something is going wrong. It only happens with Herd.

I've made a demo app to show what's happening. But it doesn't behave exactly like the client projects. In the demo project I can just use `composer install -vvv` and press enter a few times. On the client projects this doesn't work. I can try to make a better demo if needed.

### Steps to reproduce

Clone https://github.com/iruoy/herd-hang-demo
Run `composer install`

**Comment by mpociot** [comment]
I can reproduce the issue, but it seems like the patches are wrong.

The patch in your repository looks like this:

```patch
--- /dev/null
+++ ../src/Index.php
@@ -2,8 +2,8 @@
 namespace Inventkg\HelloComposer;
 class Index 
 {
-    public function greet($greet = 'Hello, World!')
+    public function greet($greet = 'Hello World')
     {
         return $greet;
     }
 }
```

So it tries to **remove** the exclamation mark and change it into "Hello World" (no comma, no exclamation mark).
But the `Index.php` in the vendor folder can not apply this patch as its just "Hello World" to begin with.

If you change the patch into:

```patch
--- /dev/null
+++ ../src/Index.php
@@ -2,8 +2,8 @@
 namespace Inventkg\HelloComposer;
 class Index 
 {
-    public function greet($greet = 'Hello World')
+    public function greet($greet = 'Hello, World!')
     {
         return $greet;
     }
 }
```

It works just fine.
I also don't see a reason why Herd's composer should behave differently here, as it's just using the `patch` command.
