### ISSUE TITLE
[Bug]: Herd restart

### ISSUE THREAD

**Issue by iEXExchanger** [beyondcode/herd-community#611]
### Platform

macOS

### Operating system version

Windows 11

### System architecture

Intel (x86)

### Herd Version

1.0.6

### Bug description

When rebooting herd, errors appear.
Also, mysql stopped working, rebooting does not help.

![2024-04-07_09-55-40](https://github.com/beyondcode/herd-community/assets/163338500/cdb6d10b-99ea-4070-abd6-e10d415f4f09)

**Comment by iEXExchanger** [comment]
![2024-04-07_09-57-31](https://github.com/beyondcode/herd-community/assets/163338500/5613a6a4-e743-4c0e-bd4c-2c974950b16e)

**Comment by iEXExchanger** [comment]
![2024-04-07_09-58-40](https://github.com/beyondcode/herd-community/assets/163338500/ead0b118-88a9-42a3-956e-805621bcf969)
The websites section doesn't load either.

**Comment by iEXExchanger** [comment]
Restarting the computer completely doesn't even help.

**Comment by mpociot** [comment]
Can you run "where.exe php" and tell me if this gives you the correct PHP binary from Herd? 
Seems like Herds binary path is no longer in your PATH/not in front.
