### ISSUE TITLE
[Bug]: Herd doesn't create a site

### ISSUE THREAD

**Issue by seekaplayer** [beyondcode/herd-community#612]
### Platform

macOS

### Operating system version

macOS 14.4.1 (23E224)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

Version 1.5.0 (Build: 23)

### PHP Version

PHP 8.3 (8.3.3)

### Bug description

Yes I have a problem with Herd not creating any sites/test URLs. Here is what I do. I have tried uninstalling Herd and reinstalling it and nothing has worked. It was working just fine until I did the update so I'm not sure if there was an issue with the update build. 

1. Open up Herd.
2. Click on the icon.
3. Go to Settings.
4. Click on the "Sites" tab.
5. Click the "+" icon.
6. I choose "No Starter Kit" or any other option none of them work anyway.
7. Click "Next".
8. Put in the project name "testing".
10. Choose the folder destination. In this case "Herd".
11. Then I click "Next". 
12. It spins and says, "Your application was created successfully. Build something amazing!
13. I click "View in browser" 
14. Then I see an error. 
15. I click on the refresh Icon and nothing is there.

### Steps to reproduce

Here are the steps via Screenshots.

![Screenshot 2024-04-07 at 12 07 48 PM](https://github.com/beyondcode/herd-community/assets/44986525/c2ad0597-62f1-453d-9d9c-8dfc3a2e3f9e)
![Screenshot 2024-04-07 at 12 08 00 PM](https://github.com/beyondcode/herd-community/assets/44986525/f6f50e68-d9ad-4a3b-bc82-0cd657701218)
![Screenshot 2024-04-07 at 12 08 08 PM](https://github.com/beyondcode/herd-community/assets/44986525/296c6838-2ddb-43e5-b5dc-507f227ac4e9)
![Screenshot 2024-04-07 at 12 08 17 PM](https://github.com/beyondcode/herd-community/assets/44986525/6bb93152-d951-41f1-9e21-1d06c10e1101)
![Screenshot 2024-04-07 at 12 08 26 PM](https://github.com/beyondcode/herd-community/assets/44986525/090d6984-0f72-4bfd-bbb3-709e608220c5)
![Screenshot 2024-04-07 at 12 08 34 PM](https://github.com/beyondcode/herd-community/assets/44986525/415320e6-ca9c-4abb-b0bf-63e76b806ed7)
![Screenshot 2024-04-07 at 12 08 55 PM](https://github.com/beyondcode/herd-community/assets/44986525/058c0ddb-d7eb-4a29-98f4-1c7bd8d27e4f)
![Screenshot 2024-04-07 at 12 09 11 PM](https://github.com/beyondcode/herd-community/assets/44986525/f7230c39-3641-498c-a656-ac4e9f31579d)

**Comment by seekaplayer** [comment]
Also I just checked to see if I could pull the information for the services such as PHP, ETC and it looks like nothing can be found, so there is definitely something wrong here.
![Screenshot 2024-04-07 at 12 16 31 PM](https://github.com/beyondcode/herd-community/assets/44986525/e3e6fc15-3109-4ac0-a02d-fb65022b2906)

**Comment by seekaplayer** [comment]
Not sure if this will help but I tried running the "herd" command and got this.
![Screenshot 2024-04-07 at 12 25 34 PM](https://github.com/beyondcode/herd-community/assets/44986525/62b8f7b4-f679-4ec5-a835-b3b2df131164)

**Comment by mpociot** [comment]
Just to be sure: did you try running the command in a new terminal tab?
Which shell do you use? Bash/ZSH?

**Comment by seekaplayer** [comment]
Hey, great news, Looks like the uninstallation I might have forgotten to delete something but now I was able to uninstall it and was able to get it fully working :) 
![Screenshot 2024-04-07 at 12 42 34 PM](https://github.com/beyondcode/herd-community/assets/44986525/520006de-5b68-4b97-b416-fd4a9d694011)

**Comment by seekaplayer** [comment]
I'm all set to go :)
