### ISSUE TITLE
[Bug]: Getting error to install 'pcntl' extension. However this extension is not supported on Windows

### ISSUE THREAD

**Issue by y0vche** [beyondcode/herd-community#613]
### Platform

Windows

### Operating system version

Windows 10

### System architecture

Intel (x86)

### Herd Version

1.0.1.

### PHP Version

PHP 8.3.0

### Bug description

When I run `composer update` get error to install 'pcntl' on Win 10 but such extension is not supported on Windows. [Reference](https://www.php.net/manual/en/pcntl.installation.php).

`Problem 1

laravel/horizon[v5.23.0, ..., v5.23.2] require ext-pcntl -> it is missing from your system. Install or enable PHP's pcntl extension`

### Steps to reproduce

1. Install Laravel Horizon package
2. Try to install other composer package & the problem persists.

**Comment by mpociot** [comment]
Laravel Horizon is not working on Windows, as the pcntl extension is not available. 
You could install the dependencies using:
composer update --ignore-platform-reqs
