### ISSUE TITLE
[Bug]: Uninstalling  and Re-installing Herd

### ISSUE THREAD

**Issue by pchege** [beyondcode/herd-community#615]
### Platform

Windows

### Operating system version

Windows 11

### System architecture

Intel (x86)

### Herd Version

1.0.0

### PHP Version

PHP 8.3

### Bug description

On Step 4 for uninstalling Herd "Uninstall nvm if you've installed it via Herd",  Kindly provide a details explanation on how to go about this step since i am unable to uninstall NVM using windows installer since i can't locate nvm

### Steps to reproduce

Uninstalling Herd on windows 11

### Relevant log output

```shell
It looks like you don't have NVM installed yet, but you do have nvm variables set. Please verify your NVM installation and try again.
```

**Comment by mpociot** [comment]
You only need to remove two environment variables:
`NVM_HOME` and `NVM_SYMLINK`
