### ISSUE TITLE
[Feature Request]: Changelog

### ISSUE THREAD

**Issue by blhylton** [beyondcode/herd-community#62]
### Feature Description

I would like to see the changelog added to the settings pane or website. As of right now, the only place it can be seen (that I'm aware of) is on the update prompt when there is a new update to install, and even then, it's only for the version you're installing.

If this info is available somewhere, change this feature request to "make it easier to find."

### Is this feature valuable for other users as well and why?

For many reasons, someone might want to see what changed between versions. This is a suggestion to include that information somewhere more readily available. It's likely more of a UX nicety than any actual functionality since you have a changelog for the installer prompt.

**Comment by mpociot** [comment]
Done: https://herd.laravel.com/changelog
