### ISSUE TITLE
[Bug]: Issue with app.css and app.js

### ISSUE THREAD

**Issue by ccievoiceoks** [beyondcode/herd-community#620]
### Platform

macOS

### Operating system version

Mac OS 14.4.1 (23E224)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.5.0 Build 23

### Bug description

Hi all ,

I've switched on my machine from Container to Herd for facilities but  application will always run on container in the future so I want to keep my infrastructure with under the root , the definition of my docker components and keep my code under a folder /src for example .

So that I can keep my container for later and redeploy when needed but nevermind.
 
I found that it is possible to define the Path by using a LocalValetDriver
This is what I have implemented to run my app under Herd
Here is the definition of the driver that I found on the documentation

```php
<?php 

use Valet\Drivers\LaravelValetDriver;
 
class LocalValetDriver extends LaravelValetDriver
{
    /**
     * Determine if the driver serves the request.
     */
    public function serves(string $sitePath, string $siteName, string $uri): bool
    {
        return true;
    }
 
    /**
     * Get the fully resolved path to the application's front controller.
     */
    public function frontControllerPath(string $sitePath, string $siteName, string $uri): string
    {
        return $sitePath.'/src/public/index.php';
    }
}
?>
```

It is working as my app is running well now under Herd .
The only issue is that my app.css and app.js are not found by the config even if they are present in the folder that I'm servicing.

I got always a 404 for these files or other files in that folder . With php artisan serve commands , it is working fine

As I'm not understanding fully the driver , can you help me on this ?
I think that it has to do with the last function but what I need to replace in order to permit the other files without any issues?

Many thanks

Olivier

**Comment by mpociot** [comment]
Your custom driver needs to implement the `isStaticFile` method

```php
/**
 * Determine if the incoming request is for a static file.
 *
 * @return string|false
 */
public function isStaticFile(string $sitePath, string $siteName, string $uri)
{
    if (file_exists($staticFilePath = $sitePath.'/public/'.$uri)) {
        return $staticFilePath;
    }
 
    return false;
}
```

**Comment by ccievoiceoks** [comment]
Thank you for your help ! indeed I have not read the documentation completely
