### ISSUE TITLE
[Bug]: Bad Gateway - herd.sock failed (61: Connection refused)

### ISSUE THREAD

**Issue by carnevalle** [beyondcode/herd-community#621]
### Platform

macOS

### Operating system version

macOS Sonoma 14.4.1

### System architecture

Intel (x86)

### Herd Version

1.5.0 (Build: 23)

### Bug description

All my sites suddenly throws a Bad Gateway. I have no idea what has changed. I have tried solutions in all related bug reports I could find.

### Steps to reproduce

I have no idea

### Relevant log output

```shell
2024/04/09 15:13:47 [error] 5575#51052: *1 connect() to unix:/Users/***/Library/Application Support/Herd/herd.sock failed (61: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://unix:/Users/***/Library/Application Support/Herd/herd.sock:", host: "herd.test", referrer: "http://herd.test/"
```

**Comment by mpociot** [comment]
What's the status of your PHP services and which version(s) do you use?
Have you tried force-stopping all services?

**Comment by carnevalle** [comment]
I had tried everything. And have uninstalled and installed several times. Until i opened the fpm-conf files and saw that permission where set to the "staff" group. This rang a bell. Changing this to admin seems to have fixed the issue.

https://github.com/beyondcode/herd-community/issues/10#issuecomment-1646678682
