### ISSUE TITLE
[Bug]: The license is reset

### ISSUE THREAD

**Issue by iEXExchanger** [beyondcode/herd-community#622]
### Platform

Windows

### Operating system version

Windows 11

### System architecture

Intel (x86)

### Herd Version

1.0.6

### Bug description

I have already seen the license reset 3 times, I activated the license, and after some time, I need to add the key and email again.
This happens randomly, already the 3rd time

The problem is in Windows, I haven’t seen this on MAC.

**Comment by mpociot** [comment]
Yeah, there's a bug where the license gets deactivated when you're offline. This will be fixed in the next release, most likely coming out tomorrow!

**Comment by mpociot** [comment]
This is now fixed with Herd 1.1.0
