### ISSUE TITLE
[Bug]: npm ERR! 

### ISSUE THREAD

**Issue by digimumo** [beyondcode/herd-community#624]
### Platform

Windows

### Operating system version

Windows 11 

### System architecture

Windows

### Herd Version

1.0.1

### PHP Version

php 8.2

### Bug description

Can't run NPM install or NPM run dev. I tried new installs of Laravel and repo clones. 

### Steps to reproduce

try to run NPM install after cloning my repo site.

### Relevant log output

```shell
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for n@9.2.1: wanted {"os":"!win32"} (current: {"os":"win32"})
npm ERR! notsup Valid os:  !win32
npm ERR! notsup Actual os: win32
```

**Comment by mpociot** [comment]
The project you're trying to install requires "n" in its package.json, which does not work on windows. That's why NPM can not install the dependencies. 
The error is unrelated to Herd itself.
