### ISSUE TITLE
[Bug]: Fail Shortcut for Open terminal from Herd (Ctrl + Shift + C): A javascript error ocurred in the main proccess

### ISSUE THREAD

**Issue by YouDevs** [beyondcode/herd-community#627]
### Platform

Windows

### Operating system version

Windows 11

### System architecture

Intel (x86)

### Herd Version

1.0.1

### Bug description

To use shortcut (Ctrl + Shift + C) to Open the terminal from Herd fails and shows this error:
"A javascript error ocurred in the main proccess
Uncaught Exception:
TypeError [ERR_INVALID_ARG_TYPE]: The "Paths[0]" argument must be string."

### Steps to reproduce

![Screenshot 2024-04-10 073732](https://github.com/beyondcode/herd-community/assets/20060274/d1ecdbdf-a35f-4e3a-a654-68f816cec787)
A few days ago I installed and uninstalled it (and deleted the Herd folder from .config)

Yesterday I wanted to try it again so I installed it and then when I wanted to open the terminal from Herd with the shortcut I got that error, that's the only thing that seems to be going wrong.

**Comment by mpociot** [comment]
This will be fixed in the next release
