### ISSUE TITLE
[Bug]: Securing sites via Herd returns a CERT_AUTHORITY_INVALID error

### ISSUE THREAD

**Issue by syntaxsoftware** [beyondcode/herd-community#63]
### Operating system version

MacOS Ventura 13.4.1 (c)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.1.1 (build 12) in app, 1.0.0 at CLI.

### Bug description

As noted in a previous report, an error:
NET::ERR_CERT_COMMON_NAME_INVALID
is shown after clicking the padlock in the app, even after upgrading just now from 1.0.8 to 1.1.1.

My point of difference is that I also get the same error after using 'herd secure' at the command line.
Also, I note that the error message in the browser is showing that the site is picking up a different site's certificate, causing the error.

<img width="629" alt="Screenshot 2023-07-29 at 07 44 44" src="https://github.com/beyondcode/herd-community/assets/5267475/3de6bbbe-9b6b-441f-9e8b-57f4bbd20e10">

### Steps to reproduce

Click the padlock icon or run herd secure.

**Comment by mpociot** [comment]
Is your site also linked with a different name? This could be the case so that Herd does not know which site/alias to secure.

Could you show me the output of `herd links` and `herd parked` (feel free to only show the snippet matching tenone.test / classicfamilies2022.test

**Comment by syntaxsoftware** [comment]
I don't know about being linked with a different name. I did create the folder by copying from another, but it wasn't 'classicfamilies2022'.

Output of herd links:
<img width="459" alt="Screenshot 2023-07-31 at 19 55 18" src="https://github.com/beyondcode/herd-community/assets/5267475/cdd74166-0ff7-4e74-ad67-0596bdf677f5">

Sections of herd parked for tenone and classicfamilies2022

<img width="1568" alt="Screenshot 2023-07-31 at 19 56 48" src="https://github.com/beyondcode/herd-community/assets/5267475/e4fa6f4c-62cd-463c-8ddd-0d2192354732">

<img width="1617" alt="Screenshot 2023-07-31 at 19 57 10" src="https://github.com/beyondcode/herd-community/assets/5267475/523a3222-455a-4b64-bdea-a76bb561d1c2">

Thanks for having a look.

**Comment by neurotools** [comment]
@syntaxsoftware maybe your problem is because Firefox doesn't use the same certificate authorities than other browsers (Safary, Chrome). You need to install the CA Authority certificate from Herd folder on Firefox.

Same problem happens with Laravel Valet: https://github.com/laravel/valet/issues/296

**Comment by syntaxsoftware** [comment]
@neurotools , I didn't know how to do the CA Install you mentioned, but while looking around I noticed that the nginx indicator in the Herd toolbar app was not illuminated, even though my local dev sites were running (as HTTP). I figured a MacOS restart wouldn't hurt and after that the nginx indicator is green and my sites are now running as HTTPS in Chrome and Safari, but still not Firefox.

I used the steps in the other issue you linked to, but was unable to see a Herd folder, so I ended up importing the Valet CA.  This has changed the Firefox error to:

<img width="842" alt="Screenshot 2023-08-01 at 08 02 56" src="https://github.com/beyondcode/herd-community/assets/5267475/1cb53c7c-8fb7-401a-9b6e-a1149212f690">

I'm not that worried about not using Firefox, but interested in seeing this through.

**Comment by connecteev** [comment]
@mpociot @neurotools fwiw I seem to be having the same issue that @syntaxsoftware is reporting here. HTTPS does not seem to work when using Herd, and I am on the latest version of Chrome.

The site is secured in Herd:
![image](https://github.com/beyondcode/herd-community/assets/64816/974b6ff9-c546-473d-ab57-5523f1a854a1)

However, HTTPS does not work:
![image](https://github.com/beyondcode/herd-community/assets/64816/d006a9fc-5d37-424e-a97c-3223aa96e625)


This is what Stripe shows in the console (you can also see this in the screenshot I have attached)
```
SSL certificate is not valid. Security level: DANGEROUS.
subscribe:1 No UI will be shown. CanMakePayment and hasEnrolledInstrument will always return false. Show will be rejected with NotSupportedError.
Error with Permissions-Policy header: Unrecognized feature: 'ch-ua-form-factor'.
```


Also, here is the output of the `herd parked` and `herd links` commands:
```
herd parked
+---------------------------------------------------------------------------------+-----+---------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------+-----+
| Site                                                                            | SSL | URL                                                                                         | Path                                                                                                                |     |
+---------------------------------------------------------------------------------+-----+---------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------+-----+
| codecourse_laravel_subscriptions                                                |  X  | https://codecourse_laravel_subscriptions.test                                               | /Users/kp/Code/web/__Herd/codecourse_laravel_subscriptions                                                | 8.2 |
+---------------------------------------------------------------------------------+-----+---------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------+-----+
```

```
herd links
+------+-----+-----+------+-------------+
| Site | SSL | URL | Path | PHP Version |
+------+-----+-----+------+-------------+
```

This is especially a problem for me right now because I am working on Stripe Payment Element integration and the new API requires HTTPS, otherwise it won't render elements for Apple Pay, Google Pay, among other things (SCA).

Does a certificate need to be installed, or am I missing some other step? Appreciate any help here to get this working!

**Comment by connecteev** [comment]
Okay, ignore my last comment. Restarted Herd and that fixed the problem for me. Apple Pay, Google Pay are still not showing up, but that is likely unrelated.
Hope this helps someone..

**Comment by iMateo** [comment]
I did simple reboot of my macbook and the problem is gone.
