### ISSUE TITLE
[Bug]: Running PHP linters with php-parallel-lint throws an executable related issue

### ISSUE THREAD

**Issue by piqusy** [beyondcode/herd-community#631]
### Platform

macOS

### Operating system version

macOS 14.4.1 (23E224)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.50 (Build 23)

### PHP Version

PHP 8.3.4 (cli) (built: Apr  9 2024 10:42:16) (NTS)

### Bug description

Running `php ./vendor/php-parallel-lint/php-parallel-lint/parallel-lint .` throws  `Unable to execute '/Users/{username}/Library/Application Support/Herd/bin/php83'`.

Traced the issues to method `getPhpExecutable`at L:97 - https://github.com/JakubOnderka/PHP-Parallel-Lint/blob/9df953cd03414e88dca163b4a3e8e9e972252513/src/Process/PhpExecutable.php#L97

`php-parallel-lint/php-parallel-lint` Package version 1.3.2

### Steps to reproduce

1. Install Herd by Laravel for local development
2. Initialize composer
3. Install `php-parallel-lint/php-parallel-lint` package
4. Run the following in the project folder: `php ./vendor/php-parallel-lint/php-parallel-lint/parallel-lint .`

**Comment by mpociot** [comment]
This is an issue within the parallel-lint package, as it does not properly wrap the php executable in quotes to handle the space in the folder name.

I forked the package and applied the fix to make it work: https://github.com/JakubOnderka/PHP-Parallel-Lint/commit/766d5f1265dd20706c891eab9af3e1822789e930

Unfortunately, the package is archived, which means that I can not PR my changes back to the project. Feel free to fork parallel-lint yourself with the changes from my commit above.
