### ISSUE TITLE
[Bug]: Access service binaries via the command line

### ISSUE THREAD

**Issue by vinkla** [beyondcode/herd-community#633]
### Platform

macOS

### Operating system version

macOS 14.4.1 (23E224)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.5.0 (Build: 23)

### PHP Version

8.3.4

### Bug description

Installing services like MySQL is not available on the command line. When I run `mysql` in my terminal, it returns: 
```
Unknown command: mysql
```

### Steps to reproduce

1. Install Herd
2. Install MySQL
3. Open terminal and run `mysql`

**Comment by mpociot** [comment]
Yup - version 1.6.0 will fix this, which will be released later today. 

In the meantime, you can manually symlink the required services. They are in /Users/Shared/Herd/services

**Comment by vinkla** [comment]
Amazing! Keep up the good work 💪

**Comment by cyppe** [comment]
@mpociot Any news about release?

**Comment by vinkla** [comment]
This has been shipped in 1.6.0 🥳 

> Service binaries now get symlinked during installation for easier access

How can you create symlinks for existing installations?

**Comment by mpociot** [comment]
Right click the service and select "symlink"

**Comment by mpociot** [comment]
This fixed with Herd 1.6.0
