### ISSUE TITLE
[Bug]: Laravel Reverb doesn't work with secured Herd site

### ISSUE THREAD

**Issue by Kenneth-Inkum** [beyondcode/herd-community#635]
### Platform

Windows

### Operating system version

Windows 11 (23H2 22635.3430)

### System architecture

Intel (x86)

### Herd Version

1.0.1

### Bug description

When Herd site is secured; accessing laravel reverb websocket fails with console log output: **The page at 'https://example.test' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://example.test/ws'. This request has been blocked; this endpoint must be available over WSS.**

**Comment by mpociot** [comment]
There is still an outstanding issue with Reverb, TLS and Chrome. Once this is fixed, we'll see how we can implement this in Herd.
