### ISSUE TITLE
[Bug]: Update PHP version, change PHP.ini file

### ISSUE THREAD

**Issue by luciano-work** [beyondcode/herd-community#640]
### Platform

Windows

### Operating system version

Windows 10

### System architecture

Windows

### Herd Version

1.0.1

### PHP Version

8.3.6

### Bug description

I made some changes to the php.ini file (8.3). Today Herd suggested updating php and I did. After that my php.ini was overwritten

### Steps to reproduce

Change php.ini and update the PHP version. Your change will be lost

**Comment by mpociot** [comment]
This is now fixed with Herd 1.1.0

**Comment by luciano-work** [comment]
Thank you :)
