### ISSUE TITLE
[Bug]: Cant lunch herd in windows after installation

### ISSUE THREAD

**Issue by AHMED-GAMAL-AG** [beyondcode/herd-community#642]
### Platform

Windows

### Operating system version

windows 11

### System architecture

Windows

### Herd Version

latest version cant lunch herd to access about tab

### PHP Version

8.3

### Bug description

I've just started using Laravel Herd on my Windows 11. But I can't seem to find the Herd interface (GUI) or settings that let me switch between PHP versions. Even though Herd is running in the background, according to the task manager, the actual application window doesn't show up. I'm not sure if I'm missing something. i reinstalled it many times but it doesn't help

Thanks for the help

https://github.com/beyondcode/herd-community/assets/76778937/66b4d114-ff33-45b3-8d92-8b1f04ff1232

**Comment by mpociot** [comment]
Did you get the Herd onboarding UI at one point?

**Comment by AHMED-GAMAL-AG** [comment]
Yes, but after I clicked Get Started, it disappeared. Even when I reinstalled the app, I didn't get the onboarding UI again. there are some one also reported the same problem on laracats website 

https://laracasts.com/discuss/channels/laravel/laravel-herd-in-windows

**Comment by mpociot** [comment]
Laravel Herd is a taskbar only application. Please check your taskbar and you will see the Herd icon next to the clock etc.

**Comment by AHMED-GAMAL-AG** [comment]
I can lunch it normally from the taskbar now. Thanks for the help It is a bit unclear though

![image](https://github.com/beyondcode/herd-community/assets/76778937/34e0e174-c082-4aa6-be97-8ded9f28dbde)

**Comment by mpociot** [comment]
Great. I'll improve the onboarding process, so it becomes clearer.
