### ISSUE TITLE
[Bug]: Confirmation mail not send

### ISSUE THREAD

**Issue by EdwinvanDessel** [beyondcode/herd-community#643]
### Platform

Windows

### Operating system version

Windwos 11

### System architecture

Windows

### Herd Version

1

### PHP Version

PHP 8.3

### Bug description

After registration I need to receive a confirmation email but that seems to be never send. At least I do not receive one, not in my inbox, not in my spam-folder and not in the spam logs of the filter my provider uses. And therefore after login I do not see anything else than: PLease confirm your email.

### Steps to reproduce

Every time I log in. Clicking the resend confirmation email leads to nothing

### Relevant log output

```shell
None available
```

**Comment by mechelon** [comment]
Can you send the email address you have registered with to our support inbox? support@beyondco.de

**Comment by EdwinvanDessel** [comment]
By now I have send 4 emails to the email address requested but so far no result. Is there anybody checking that support address?

**Comment by mechelon** [comment]
Yes, several times, every day. We did not get an email from you.

**Comment by EdwinvanDessel** [comment]
But now you did so I hope you can resolve the issue of me not receiving the email to confirm my registration (not regular, not in my spam-folder and not in the spam-filter of my provider). Is there any way around that. I registered (and paid) with the email address: ***@***.***

Met vriendelijke groet,

Edwin van Dessel
06-53165896
________________________________
Van: Di ***@***.***>
Verzonden: maandag 22 april 2024 09:08
Aan: beyondcode/herd-community ***@***.***>
CC: Edwin van Dessel ***@***.***>; Author ***@***.***>
Onderwerp: Re: [beyondcode/herd-community] [Bug]: Confirmation mail not send (Issue #643)


Yes, several times, every day. We did not get an email from you.

**Comment by mechelon** [comment]
Your email address was redacted in this comment. However, I could guess it from your name, and we don't have anything in our support inbox. Our email provider also lists every email as delivered, so it must be a problem in your inbox - a local spam filter or similar.

![CleanShot 2024-04-23 at 14 08 16@2x](https://github.com/beyondcode/herd-community/assets/26432041/f2415416-70b4-4151-a7f7-482e8a657467)

If you can provide another email address I can move the license to this one so you get your emails or I can give you a refund.

**Comment by EdwinvanDessel** [comment]
Could you try with ***@***.***?

Met vriendelijke groet,

Edwin van Dessel
06-53165896
________________________________
Van: Di ***@***.***>
Verzonden: dinsdag 23 april 2024 16:19
Aan: beyondcode/herd-community ***@***.***>
CC: Edwin van Dessel ***@***.***>; Author ***@***.***>
Onderwerp: Re: [beyondcode/herd-community] [Bug]: Confirmation mail not send (Issue #643)


Your email address was redacted in this comment. However, I could guess it from your name, and we don't have anything in our support inbox. Our email provider also lists every email as delivered, so it must be a problem in your inbox - a local spam filter or similar.

***@***.*** (view on web)<https://github.com/beyondcode/herd-community/assets/26432041/f2415416-70b4-4151-a7f7-482e8a657467>

If you can provide another email address I can move the license to this one so you get your emails or I can give you a refund.
