### ISSUE TITLE
[Bug]: Vite CSS not loading 

### ISSUE THREAD

**Issue by vcardillo** [beyondcode/herd-community#648]
### Platform

macOS

### Operating system version

Monterey 12.6.5

### System architecture

Intel (x86)

### Herd Version

1.6.0 build 24

### PHP Version

8.3.6

### Bug description

<img width="731" alt="Screen Shot 2024-04-15 at 12 24 29" src="https://github.com/beyondcode/herd-community/assets/567807/a49de8a1-957d-4cf4-bfe4-63ece08c7231">

It seems like Vite CSS isn't loading with Herd, and I don't know enough about Herd yet to debug what is happening here. However, I will say that the CSS loads fine when using the exact same codebase via the Sail docker config.

I can provide additional information as needed.

**Comment by mpociot** [comment]
The "ERR_BLOCKED_BY_CLIENT" error means that your browser is blocking the requests.
Usually this happens because of some overly aggressive adblocker.

Please take a look here: https://github.com/laravel/vite-plugin/issues/47#issuecomment-1817510750

**Comment by iamafasha** [comment]
Thank you 

> The "ERR_BLOCKED_BY_CLIENT" error means that your browser is blocking the requests. Usually this happens because of some overly aggressive adblocker.
> 
> Please take a look here: [laravel/vite-plugin#47 (comment)](https://github.com/laravel/vite-plugin/issues/47#issuecomment-1817510750)

thank you this worked for me

**Comment by Priyank57** [comment]
@mpociot yes you are right on right on this, I had the same issue on this configuration, What I concluded id I am getting this error because I am using an aggressive adblocker browser which is Brave.
