### ISSUE TITLE
[Feature Request]: Would be useful to host from sub-directories or just to adjust the URL and/or Path

### ISSUE THREAD

**Issue by fylzero** [beyondcode/herd-community#65]
### Feature Description

At my work, our dev ops team has insisted on having a /src directory for all projects to be consistent, including Laravel projects. I typically have added a LocalValetDriver.php file to steer to /src in Valet but there seems to be no way to accomplish this with Herd. I loathe using Sail/Docker when Valet is so much faster and would love to speed my workflow up even more by using Herd.

I know I can link the /src directory but the url will be src.test and I can't seem to change that either.

Making it so that it is possible to customize the URL and/or Path would be amazing.

### Is this feature valuable for other users as well and why?

Probably not a super common problem but seeing that this has been addressed by Valet (https://laravel.com/docs/10.x/valet#local-drivers) it might be worth having a solution for Herd as well.

**Comment by IHIutch** [comment]
Would love this as well. Getting back into the PHP world and being able to control .htaccess or nginx.conf would make it a lot easier to make the jump from MAMP

**Comment by MadMikeyB** [comment]
+1 Custom Drivers would allow me to use this as more than just a Laravel Dev Environment. Things like Drupal don't work right now because I can't add a custom driver such as https://gist.github.com/dustinleblanc/f70e14bfcd533c1b13ec969714aa6806

**Comment by cord** [comment]
Works with custom LocalValetDriver https://github.com/beyondcode/herd-community/issues/122

**Comment by fylzero** [comment]
Resolved by v1.2.0 release. Thanks all!
