### ISSUE TITLE
[Bug]: Fresh install of Herd not resolving URLs to a parked folder

### ISSUE THREAD

**Issue by aaronbushnell** [beyondcode/herd-community#650]
### Platform

macOS

### Operating system version

macOS Sonoma 14.4.1 (23E224)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.6.0 (Build: 24)

### PHP Version

PHP 8.3.6 (cli) (built: Apr 12 2024 00:13:56) (NTS)

### Bug description

I set up a new MacBook Pro (M3) with Herd and, while all of the services start and I can access my Herd sites, it's _only_ if I manually add each domain to the `/etc/hosts` file.

I presume this means DNSMasq is not behaving as expected. I checked around at similar issues and can confirm a couple things:

```sh
$ cat /etc/sudoers.d/herd
%admin ALL=(root) NOPASSWD:SETENV: /Applications/Herd.app/Contents/Resources/*, /bin/kill, /usr/bin/security
```

```sh
$ cat /etc/resolver/test
nameserver 127.0.0.1
nameserver 127.0.0.1
nameserver 127.0.0.1
```

```sh
$ ping mysite.test
ping: cannot resolve mysite.test: Unknown host
```

If I manually add the following to `/etc/hosts`:
```
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1	localhost
255.255.255.255	broadcasthost
::1             localhost

127.0.0.1 mysite.test
```

I now get:
```sh
$ ping mysite.test
PING mysite.test (127.0.0.1): 56 data bytes
```

## Additional notes:
- I do not have DNSMasq installed via Homebrew
- I have not installed Valet on this machine
- I can see all of my correct domains if I run `herd parked`

Happy to supply any logs that might be useful!

### Steps to reproduce

1. Install Herd on a clean macOS install (likely requires Apple Silicon)
2. Setup a site in a directory of your choosing
3. Use `herd park` to auto-detect the domains
4. Try to access one of the sites

**Comment by kirchevsky** [comment]
I have another problem with the Herd fresh install. Once it was installed, it worked correctly. However, after I changed the site's secure option to unsecured, I had a 500 error when trying to access the site. Nothing can help now—restarting the computer, changing the options rolled back to secure/unsecure. I can't access my website, but it previously worked from the box.

**Comment by max-menshenin** [comment]
Just try to restart mac, for me helped.

**Comment by mpociot** [comment]
@aaronbushnell is the status of DNSMasq green in the menubar application?

Do you see that DNSMasq is running?

```
ps aux | grep [d]nsmasq
```

**Comment by aaronbushnell** [comment]
Hi @mpociot, thanks for the follow up!

It looks like since my initial request this eventually resolved on its own. Hate that it doesn't help you here or any others with a similar issue. 

A couple things I can say in case it's useful for other issues:
- 2-3 restarts and shutdowns didn't resolve this issue for me
- Running `ps aux` _did_ show DNSMasq. One of them with the user of `nobody`
- DNSMasq was showing as enabled within the Herd app
- My machine _is_ managed by my company's IT. It's highly possible a required process was being caught by the firewall but then resolved shortly afterwards.

Sorry that doesn't help you much. But feel free to close this one out. Hope those extra details helps another person with similar issues.

**Comment by mpociot** [comment]
I'm glad that it's now working for you 👍
