### ISSUE TITLE
[Bug]: Extension not added

### ISSUE THREAD

**Issue by iEXExchanger** [beyondcode/herd-community#652]
### Platform

macOS

### Operating system version

Windows 11

### System architecture

Windows

### Herd Version

1.0.6

### PHP Version

PHP 8.2

### Bug description

I've been trying to add an extension for a long time, but it always gives me an error
![2024-04-16_20-53-27](https://github.com/beyondcode/herd-community/assets/163338500/cc22e905-1313-4f0b-a489-4c07ab1bfff8)
![2024-04-16_20-54-46](https://github.com/beyondcode/herd-community/assets/163338500/86903b42-5f71-4641-85f8-ba7c12428185)

**Comment by mpociot** [comment]
I just downloaded the ioncube loader for PHP 8.2 and was able to activate it successfully.

Ioncube needs to be placed at the very first line in your php.ini - that's unrelated to Herd though.

Please run `php -v` from the terminal to see the error message.

![image](https://github.com/beyondcode/herd-community/assets/804684/296ebe95-81a8-4109-96e6-c2201b8627fa)
