### ISSUE TITLE
[Bug]: Terminal access error for MySQL

### ISSUE THREAD

**Issue by damms005** [beyondcode/herd-community#653]
### Platform

macOS

### Operating system version

macOS 14.4.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.6.0 (Build: 24)

### Bug description

Firstly, this is a brand new MacBook Pro M3.

Laravel migration fails with error: 

```
php artisan migrate:fresh --seed

  Dropping all tables ..................................................................................................................... 1ms FAIL

   Illuminate\Database\QueryException 

  SQLSTATE[HY000] [2002] Connection refused (Connection: mysql, SQL: select table_name as `name`, (data_length + index_length) as `size`, table_comment as `comment`, engine as `engine`, table_collation as `collation` from information_schema.tables where table_schema = 'tims' and table_type in ('BASE TABLE', 'SYSTEM VERSIONED') order by table_name)
```

To further debug, I tried running mysql directly from terminal, but still couldn't connect:
```
mysql -uroot 
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)
```

If it helps, output of `whereis mysql` is:
```
whereis mysql
mysql: /Users/damms005/Library/Application Support/Herd/bin//mysql
```

### Steps to reproduce

- install Herd
- park a folder that has a Laravel app
- run the app's migration

### Relevant log output

```shell
damms005@Damilolas-MacBook-Pro tims % php artisan migrate:fresh --seed

  Dropping all tables ..................................................................................................................... 1ms FAIL

   Illuminate\Database\QueryException 

  SQLSTATE[HY000] [2002] Connection refused (Connection: mysql, SQL: select table_name as `name`, (data_length + index_length) as `size`, table_comment as `comment`, engine as `engine`, table_collation as `collation` from information_schema.tables where table_schema = 'tims' and table_type in ('BASE TABLE', 'SYSTEM VERSIONED') order by table_name)

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:829
    825▕                     $this->getName(), $query, $this->prepareBindings($bindings), $e
    826▕                 );
    827▕             }
    828▕ 
  ➜ 829▕             throw new QueryException(
    830▕                 $this->getName(), $query, $this->prepareBindings($bindings), $e
    831▕             );
    832▕         }
    833▕     }

      +46 vendor frames 

  47  artisan:35
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

damms005@Damilolas-MacBook-Pro tims % mysql -uroot 
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)
damms005@Damilolas-MacBook-Pro tims % whereis mysql
mysql: /Users/damms005/Library/Application Support/Herd/bin//mysql
```

***EDIT***:
db config section in `.env`:
```
DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3309
DB_DATABASE=tims
DB_USERNAME=root
DB_PASSWORD=
```

Note: Maybe irrelevant, but I want to mention that I already used TablePlus to ensure db named `tims` exists.

**Comment by damms005** [comment]
After the "EDIT" in my original issue above, it was straight up obvious to me that I was using the wrong port: `3309` instead of `3306`.\
So the seeding issue is fixed.

But the the terminal access issue still remains, so...🤔

**Comment by mpociot** [comment]
As Laravel Herd allows you to start multiple MySQL servers, each server has an individual socket name.
You can either lookup connect via the CLI using localhost and your port:
```
mysql -u root -h 127.0.0.1 -P 3306 -p
```

Or lookup the socket name, and use that on the CLI. 
Here's how you can do this:

Right click on the MySQL server you want to connect to and choose "Open service folder":
<img width="377" alt="image" src="https://github.com/beyondcode/herd-community/assets/804684/03548a8a-b21a-4d63-9cca-d164602ae061">

The folder has a UUID as the name:
<img width="334" alt="image" src="https://github.com/beyondcode/herd-community/assets/804684/15bb6d70-e0be-43b4-a184-50f4eb2524a9">

Use this folder name as the socket name:

```
mysql -u root --socket=/tmp/mysql-FA48B5C6-2000-4C1C-A239-AFA770E7CFA5.sock
```

**Comment by clementmas** [comment]
These right click options are not available anymore.

Is there a simpler way to alias `mysql` to `mysql --socket=...`?
