### ISSUE TITLE
Open in editor option not found. (Herd Pro)

### ISSUE THREAD

**Issue by sudip-fe** [beyondcode/herd-community#654]
### Platform

Windows

### Operating system version

Windows 11

### System architecture

Windows

### Herd Version

1.1.0

### Bug description

When i use herd in my mac I found a option to open project in editor but in windows it's missing. Its a very important feature.

![image](https://github.com/beyondcode/herd-community/assets/141113076/9c6359d8-733a-43d9-aa37-25b686e7e33f)

**Comment by mpociot** [comment]
Do you have any example applications on Windows that have a similar feature?
We tried to use the same approach via URL schemes, but it doesn't seem to be available on Windows

**Comment by jaguarman** [comment]
@mpociot 
Am I right, herd does not use the .env file in my project directory?
If so, the pro version is useless. That's what I wanted to use, an IDE that starts the corresponding SQL server for my project.
So if I select a project and click "open in broswer", that's what I expect:
Herd starts the corresponding SQL server for the selected project. 

Best regards
Peter
