### ISSUE TITLE
[Bug]: Command "share-tool" is not defined. 

### ISSUE THREAD

**Issue by jtrod** [beyondcode/herd-community#656]
### Platform

macOS

### Operating system version

macOS Sonoma 14.4.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.6.0 Build 24

### Bug description

After updating to latest version, when running herd share-tool ngrok I get: Command "share-tool" is not defined.

**Comment by mpociot** [comment]
Yeah, the previous version of Herd already didn't ship with the ngrok binaries, which had us remove ngrok as a share tool.
Feel free to manually download and use ngrok though 👍

**Comment by jtrod** [comment]
I tried but I get a 404 coming from Herd
