### ISSUE TITLE
[Bug]: Herd CLI shows wrong version

### ISSUE THREAD

**Issue by SamuelNitsche** [beyondcode/herd-community#66]
### Operating system version

macOS Ventura 13.4

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.1.1 (Build 12)

### Bug description

The Herd app shows a different version than the Herd CLI.

App:
<img width="372" alt="image" src="https://github.com/beyondcode/herd-community/assets/24483576/d21b003a-18fd-43e3-bb29-c85677ef5fe9">

CLI:
<img width="262" alt="image" src="https://github.com/beyondcode/herd-community/assets/24483576/721b6d8d-f01c-416b-bfdb-683388ae942e">

**Comment by mpociot** [comment]
Right - thanks for bringing this up, I'll fix this in the next release!
