### ISSUE TITLE
[Bug]: Random Empty Node Versions

### ISSUE THREAD

**Issue by kylekanderson** [beyondcode/herd-community#660]
### Platform

macOS

### Operating system version

macOS Sonoma 14.4.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.6.0 (Build: 24)

### PHP Version

Any

### Bug description

I believe this just started happening in Herd v1.6.0.

On the Node tab in the Herd settings, after loading the installed Node versions, one of the listed versions is replaced with "()". It seems like the version replaced with "()" is random every time the tab is opened.

Here are some example screenshots showing different Node versions being replaced with "()":
![2024-04-17 at 12 30 50](https://github.com/beyondcode/herd-community/assets/24831484/0ef9124b-5aab-4e52-88fb-beab21d919c3)
![2024-04-17 at 12 31 44](https://github.com/beyondcode/herd-community/assets/24831484/85f54be3-a081-477d-ab45-cd07293167d2)

You'll also notice in those screenshots that the Node version replaced with "()" also has an "Update" button listed for it, even though all of the installed Node versions on my system are at their latest version. This also manifests to a notification icon on the Herd system tray icon, and when clicking on the system tray icon, it says that a Node update is available (even though that's not the case):
![2024-04-17 at 12 37 29](https://github.com/beyondcode/herd-community/assets/24831484/b048da82-c7e6-4456-a654-3dee4443ff81)

**Comment by mpociot** [comment]
Could you share the output when you run`nvm ls node` in your terminal?

**Comment by kylekanderson** [comment]
Sure thing:
![2024-04-17 at 13 20 20](https://github.com/beyondcode/herd-community/assets/24831484/e27dad19-1b18-443e-b4bc-e968a5856542)

**Comment by mpociot** [comment]
Can you run the following code:
```
/bin/zsh -l -c source ~/.zshrc; tput reset; echo LARAVEL-HERD-MARKER; nvm ls; echo LARAVEL-HERD-MARKER;
```

And copy/paste the result in here?

**Comment by kylekanderson** [comment]
Sure, see below:

```bash
❯ /bin/zsh -l -c source ~/.zshrc; tput reset; echo LARAVEL-HERD-MARKER; nvm ls; echo LARAVEL-HERD-MARKER;

zsh:source:1: not enough arguments
LARAVEL-HERD-MARKER
        v6.17.1
       v10.24.1
      v12.22.12
       v14.21.3
       v16.20.2
       v18.19.0
       v18.19.1
       v18.20.0
       v18.20.1
       v18.20.2
        v20.9.0
       v20.11.0
       v20.11.1
       v20.12.0
       v20.12.1
->     v20.12.2
        v21.6.1
        v21.6.2
        v21.7.0
        v21.7.1
        v21.7.2
        v21.7.3
         system
default -> lts/* (-> v20.12.2)
iojs -> N/A (default)
unstable -> N/A (default)
node -> stable (-> v21.7.3) (default)
stable -> 21.7 (-> v21.7.3) (default)
lts/* -> lts/iron (-> v20.12.2)
lts/argon -> v4.9.1 (-> N/A)
lts/boron -> v6.17.1
lts/carbon -> v8.17.0 (-> N/A)
lts/dubnium -> v10.24.1
lts/erbium -> v12.22.12
lts/fermium -> v14.21.3
lts/gallium -> v16.20.2
lts/hydrogen -> v18.20.2
lts/iron -> v20.12.2
LARAVEL-HERD-MARKER
```

**Comment by kylekanderson** [comment]
Not sure if this matters, but I also noticed that the Herd injected PHP 8.2 configuration (the current version I'm using) is _above_ the NVM initialization script in my .zshrc, while the other Herd injected PHP configurations are below it:

```bash
# Herd injected PHP binary.
export PATH="/Users/kyleanderson/Library/Application Support/Herd/bin/":$PATH


# Herd injected PHP 8.2 configuration.
export HERD_PHP_82_INI_SCAN_DIR="/Users/kyleanderson/Library/Application Support/Herd/config/php/82/"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Herd injected PHP 8.1 configuration.
export HERD_PHP_81_INI_SCAN_DIR="/Users/kyleanderson/Library/Application Support/Herd/config/php/81/"


# Herd injected PHP 8.0 configuration.
export HERD_PHP_80_INI_SCAN_DIR="/Users/kyleanderson/Library/Application Support/Herd/config/php/80/"


# Herd injected PHP 7.4 configuration.
export HERD_PHP_74_INI_SCAN_DIR="/Users/kyleanderson/Library/Application Support/Herd/config/php/74/"


# Herd injected PHP 8.3 configuration.
export HERD_PHP_83_INI_SCAN_DIR="/Users/kyleanderson/Library/Application Support/Herd/config/php/83/"
```

**Comment by mpociot** [comment]
Thanks, this will be fixed in the next release. The order in the zshrc file doesn't matter
