### ISSUE TITLE
[Bug]: Isolated PHP Version Incorrect When Using Unsecured Site

### ISSUE THREAD

**Issue by chunterb** [beyondcode/herd-community#661]
### Platform

macOS

### Operating system version

macOS Sonoma 14.5 Beta (23F5049f)

### System architecture

Intel (x86)

### Herd Version

1.6.0 (Build: 24)

### Bug description

When I am working on an unsecured site that is served setup through Herd, it does not honor the isolated PHP version that I set. 

### What I have tried
- Restarting Herd.
- Unlinking and linking the site back. 
- Securing and un-securing the site.
- Uninstalled Herd using the guide [here](https://herd.laravel.com/docs/1/troubleshooting/uninstalling), and then a fresh install afterwards.
- Made sure that there were no conflicts with nginx and dnsmasq. It's using the versions that Herd provides, and nothing installed by Brew. 
- Ensured that the PHP Loaded Configuration File is coming from Herd, and not a system/brew installed PHP.

### Steps to reproduce

1. Make sure that your project is un-secure in Herd. Either run the CLI command `herd unsecure` inside of a linked project folder, or through the Herd interface.
2. Set an isolated PHP version either through the Herd interface or by running `herd isolate php@x.x` through the CLI inside of the project folder. 
3. Dump your PHP info by using `phpinfo()` or equivalent. Visit the site and see that the isolated PHP version does not match the version being dumped.

**Comment by mpociot** [comment]
I'm unable to reproduce this locally.
What do you get when you run `herd isolated`?

**Comment by flatcapco** [comment]
I know this is old but the fix for me was herd unlink and then herd link --isolate 8.2 --secure 
replacing 8.2 which whichever php version you want. I'm also assuming there was something from an old valet install causing a conflict potentially but this seemed to overwrite it.
