### ISSUE TITLE
[Bug]: Cannot increase nginx timeout settings on Herd Pro.

### ISSUE THREAD

**Issue by zgjimgjonbalaj** [beyondcode/herd-community#666]
### Platform

macOS

### Operating system version

macOS Sonoma Version 14.4.1 (23E224)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.6.0 (Build: 24)

### PHP Version

PHP 8.2.16 (cli) (built: Feb 16 2024 00:30:02) (NTS)

### Bug description

Have a fresh install of Herd and am working with a WP site. On the first page view the site will take quite a bit to load up everything. Subsequent views are much much less however. I am unable to get to that first view at all due to 504 errors from nginx. I've tried everything to get past the 60 second timeout with no luck.

- I've tried adding the following params to `~/Library/Application Support/Herd/config/nginx/herd.conf` and the `nginx.conf` and the `fastcgi_params`file in the same directly:

```
        fastcgi_buffer_size 4096k;
        fastcgi_buffers 128 4096k;
        fastcgi_busy_buffers_size 4096k;

        proxy_connect_timeout 600;
        proxy_send_timeout 600;
        proxy_read_timeout 600;
        
        send_timeout 600;
        client_body_timeout 600;
```

- I've also attempted to increase default_socket_timeout in PHP and confirmed it was set with phpinfo() with no luck;
- Other sites that load quicker have no issues.
- I've tried testing the config file with `.../nginx-arm -c ~/Library/Application Support/Herd/config/nginx/herd.conf -T` and it checks out.

No matter what I do though it won't get past the 60 second timeout and a 504 is consistently returned.

### Steps to reproduce

Have a long running PHP process that will take past 60 seconds.

**Comment by mpociot** [comment]
You forgot one nginx config directive which solves the gateway timeout issue:

```
fastcgi_read_timeout 600;
```
