### ISSUE TITLE
[Bug]: dumps doesnt work on magento

### ISSUE THREAD

**Issue by Redouan-Hajjari** [beyondcode/herd-community#668]
### Platform

macOS

### Operating system version

Mac Ventura 13.0

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.6

### PHP Version

php 8.1

### Bug description

i tried the dump function for my magento shop. but it doesnt work.

**Comment by mechelon** [comment]
Can you provide any more information, do you get any errors? Which code are you trying to execute in Magento and how? Which Magento version is it?

**Comment by Redouan-Hajjari** [comment]
> Can you provide any more information, do you get any errors? Which code are you trying to execute in Magento and how? Which Magento version is it?

Never mind. i send already an email to refund my licentie.
