### ISSUE TITLE
[Bug]:We improved the NVM installation and detection error handling

### ISSUE THREAD

**Issue by GoFRCor** [beyondcode/herd-community#669]
### Platform

macOS

### Operating system version

14.4.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.6

### PHP Version

8.3

### Bug description

Herd Pro
Fresh install of v1.6 - it tells me node.js needs updating, takes me to the node.js setting screen, has a big red button to "install nvm, which is already installed. The button appears to click but nothing happens.

I go to the terminal and use the command line for node.js 21. Still, same behavior in the GUI.

### Steps to reproduce

1. Click Herd in menu bar. Top line will display update available for node.js
2. Click top line and the Settings open to node.js screen. Big red button to install NVM
3. Click big red NVM button, it clicks but nothing changes.

**Comment by GoFRCor** [comment]
npm run dev

> @ dev /Volumes/MyRAID/DEVELOPMENT/PHP/LARAVEL/chirper
> vite

(node:4192) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token '??='
    at Loader.moduleStrategy (internal/modules/esm/translators.js:141:18)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4192) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4192) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by sschlein** [comment]
We've removed the annoying node js update bubble in 1.6.1
