### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by abhijeetcpu** [beyondcode/herd-community#67]
### Feature Description

Presently Herd only supporting laravel applications to execute using nginx. it should also support core php web applications too using nginx.

I have presently few applications in core php and other are in laravel. I am not able to run core php application from nginx using HERD. 

### Is this feature valuable for other users as well and why?

yes it will be valuable for all other users, who are working in both core php and laravel.
In my case I was using XAMP for both core and laravel applications. Once I started using HERD I loved it and it works well for laravel applications. but I have to use XAMP to work with core php application that is a pain for me to manage two softwares for same thing.

**Comment by rabiibrahimi** [comment]
I remember in laravel valet there was a possibility to create a custom nginx config file per each site which worked well. i can't find how to do it in Larave Herd, this is an example of a nginx custom config file for an open source crm called espocrm https://docs.espocrm.com/administration/nginx-virtual-host/#espocrm-v7

**Comment by mpociot** [comment]
> I remember in laravel valet there was a possibility to create a custom nginx config file per each site which worked well. i can't find how to do it in Larave Herd, this is an example of a nginx custom config file for an open source crm called espocrm https://docs.espocrm.com/administration/nginx-virtual-host/#espocrm-v7

You can do this by isolating a sites PHP version. For example by running "herd isolate 8.3" in the project root directory. This will create a custom nginx config file

**Comment by rabiibrahimi** [comment]
thanks @mpociot where these custom nginx files will be generated. i have checked under Herd/nginx and couldn't find them.
