### ISSUE TITLE
[Bug]: Minor Menu Bar Annoyance

### ISSUE THREAD

**Issue by garyross** [beyondcode/herd-community#670]
### Platform

macOS

### Operating system version

macOS Sonoma 14.4.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.6.0 (Build: 24)

### Bug description

The Menu Bar shows a red ! for Node.js updates when you have notifications of**f. It's a** bit of a nuisance because you can't get rid of it without updating Node which may not be desirable. 
<img width="943" alt="Screenshot 2024-04-18 at 23 36 10" src="https://github.com/beyondcode/herd-community/assets/173042/67263cd3-c24c-4072-a54f-247823cad80d">

### Steps to reproduce

Set Preferences to have _Notify about Node updates_ unchecked.

Wait till Node needs an update, and the red dot appears as in the image. 

It makes sense to notify that the update is available in the menu itself but not to have a red dot notification.

**Comment by mpociot** [comment]
The whole Node.js update notification was kinda annoying, so 1.6.1 removed it 😅
