### ISSUE TITLE
Laravel Herd: Missing sites in Windows [Bug]: 

### ISSUE THREAD

**Issue by BogdanGewaldCosnova** [beyondcode/herd-community#672]
### Platform

Windows

### Operating system version

Windows 11

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.1.0

### PHP Version

PHP 8.3

### Bug description

After I install a Laravel project, regardless of whether I do it through the terminal or GUI, the sites are not displayed in the 'sites' tab. Everything else works fine. I can access the sites in the browser, but in Laravel Herd under 'Sites', I only get a loading animation and no sites are loaded.
![grafik](https://github.com/beyondcode/herd-community/assets/165886196/e7d076dd-c321-4368-a531-4c3d97654c9a)

### Steps to reproduce

instal project, and the go to Sites Tab

**Comment by mpociot** [comment]
Which output do you get when you run "herd parked --json" via CLI?

**Comment by danilobb** [comment]
I'm getting the same thing for that same problem.

herd parked --json

The Herd Desktop application is not running. Please start Herd and try again.
Command "parked" is not defined.

**Comment by laurenceioannou** [comment]
same issue

**Comment by Elitondev-sisp** [comment]
the same here, using Windows 11 Pro

**Comment by Elitondev-sisp** [comment]
Hello, I managed to solve it by removing the xampp that I had installed on my machine, as it had a different php version than the one the laravel project works with, and this ended up causing some conflict.

In my case, I just uninstalled xampp and reinstalled herd and everything worked fine.

**Comment by mpociot** [comment]
This must be a duplicate of #595
