### ISSUE TITLE
[Bug]: cURL error 60: SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by jozeflambrecht** [beyondcode/herd-community#673]
### Platform

Windows

### Operating system version

Windows 11

### System architecture

Windows

### Herd Version

1.1.0

### PHP Version

PHP 8.3

### Bug description

When I use Laravel Socialite to authenticate a client app, I get this error:
`cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://example.test/oauth/token`

I went into my php.ini (location C:\Users\jozef\.config\herd\bin\php83) and put 
`curl.cainfo ="C:\test\cacert.pem"`
Downloaded the file here: https://curl.haxx.se/ca/cacert.pem

I restarted the services, herd, my computer, still the same error.

### Steps to reproduce

Use Laravel Socialite `$globalUser = Socialite::driver('laravelpassport')->user();`

**Comment by sschlein** [comment]
Do you use https for your local endpoint or Expose for the webhook redirect?

It would be great to learn more about your local setup and your local oauth domain to be able to reproduce the issue.

**Comment by muhammadessam** [comment]
Same error here i have done the same soultion with not hope to make it work

**Comment by muhammadessam** [comment]
![image](https://github.com/beyondcode/herd-community/assets/14132452/207f67da-9e0b-459f-a69c-0e2f2d3777e6)
for me i have two main projects one for the front end uses vue and calls back some api endpoints on the back end
i have tried a lot of solution but the main one is to change the php.ini cafile location with not luck to makeit work

**Comment by jozeflambrecht** [comment]
both the "client" and the "host/server" are on my local machine
my .env of the client
```
LARAVELPASSPORT_CLIENT_ID=***
LARAVELPASSPORT_CLIENT_SECRET=***
LARAVELPASSPORT_REDIRECT_URI=https://client.test/auth/callback
LARAVELPASSPORT_HOST=https://host.test/
```
it does work on my production server, but not locally.
I don't know if that answers your question..

**Comment by jozeflambrecht** [comment]
fixed in next release?

**Comment by mpociot** [comment]
GitHub seems to automatically close issues as soon as they get merged in master. 
I'll publish the update in the next hour 🙂

**Comment by igormages** [comment]
Some news about this issue ?

**Comment by Logarithmique51** [comment]
Solution : 

1. Download the certificate file [here](https://curl.haxx.se/ca/cacert.pem) 
2. Modify the value of **curl.cainfo** in your php.ini to and set the absolute path to the downloaded certificate. 
3. Restart you php serv

**Comment by vinhthai2905** [comment]
@Logarithmique51 i tried your method but it didnt work, any more leads🤕🤕 ive been stuck at this problem for 2 days

**Comment by vinhthai2905** [comment]
@jozeflambrecht i encountered the same issue as you today. Did you find a way to fix it

**Comment by akoper** [comment]
I have this problem, too.

When you use Laravel's socialite package, you are not writing your own HTTP instance that you can modify (verify = false)

**Comment by Josimar7** [comment]
Hey! II still have the same problem, but the weird part is, at first everything was working just fine, and now i have this errorno:60...

**Comment by elbereth** [comment]
Sorry this is old and closed, but I was having same problem and it was caused by my AV/Firewall solution replacing the CA by the one of the AV to "check" the HTTPS contain. Fortunately Avast has an option to deactivate that behaviour and then it works fine.
I know other AV do that but with no obvious way to disable it (Bitdefender and Kaspersky to name two I abandonned because of that). Hope this can help.

<img width="642" alt="Image" src="https://github.com/user-attachments/assets/29bb613f-8823-4652-905f-38d03c982c4f" />

**Comment by nawanTSL** [comment]
> Sorry this is old and closed, but I was having same problem and it was caused by my AV/Firewall solution replacing the CA by the one of the AV to "check" the HTTPS contain. Fortunately Avast has an option to deactivate that behaviour and then it works fine. I know other AV do that but with no obvious way to disable it (Bitdefender and Kaspersky to name two I abandonned because of that). Hope this can help.
> <img alt="Image" width="642" src="https://private-user-images.githubusercontent.com/1632446/434848843-29bb613f-8823-4652-905f-38d03c982c4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTQ1NDgzODIsIm5iZiI6MTc1NDU0ODA4MiwicGF0aCI6Ii8xNjMyNDQ2LzQzNDg0ODg0My0yOWJiNjEzZi04ODIzLTQ2NTItOTA1Zi0zOGQwM2M5ODJjNGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDgwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA4MDdUMDYyODAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGMzYzkxNzBhMDVjNzk0YmMxYzViODA5YjA0YmQzZTAwNjcwZDgwNTc0NzM3ZmQwMzJmMDhhMTMzYjZlZWU5YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.5La2wgKe3XoMGj6Qf2Y-iBqTBd-9NQ-mzNhtOrseHQY">

This is worked for me. Thank you so much for the update
