### ISSUE TITLE
[Bug]: Can't access my .test websites

### ISSUE THREAD

**Issue by HyakuAr** [beyondcode/herd-community#674]
### Platform

Windows

### Operating system version

Windows 10 22H2 19045

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.1.0

### PHP Version

PHP 8.3.6

### Bug description

I can create the websites but I'm unable to show them as my .test doesn't work and return a dns error. DNS_PROBE_POSSIBLE

Note that when I start Herd sometimes HerdHelper Port doesn't seem to be running.

**Comment by mechelon** [comment]
The HerdHelper has to be running to access sites. Can you ensure it runs on a free port, restart Herd and try again?

**Comment by HyakuAr** [comment]
> The HerdHelper has to be running to access sites. Can you ensure it runs on a free port, restart Herd and try again?

I can restart herd, change herdhelper it doesn't work the icon stay red and my .test don't work.
I can see it listening tho I put it on port 6000 and it run 0.0.0.0:6000. But herdhelper is still red.

**Comment by mpociot** [comment]
Can you take a look at your Windows services and see if the Herd Helper service is running?

**Comment by andreassbayu** [comment]
I also have the same issue. In my case, the HerdHelper service is running, and its status is green. But I cannot access the .test website. 
If I run localhost or 127.0.0.1, then Herd will display a page not found. If I check the host file, there are no changes either. Is this an issue with the host file?

**Comment by andreassbayu** [comment]
> I also have the same issue. In my case, the HerdHelper service is running, and its status is green. But I cannot access the .test website. If I run localhost or 127.0.0.1, then Herd will display a page not found. If I check the host file, there are no changes either. Is this an issue with the host file?

If I add manually in host file it is working. Must be because Admin Privillege
`127.0.0.1          testing.test`

**Comment by sschlein** [comment]
The HerdHelper should run as a system service with admin privileges so that it's able to change the hosts file – could this be the issue? If yes, I wonder how it got installed and how your system setup looks like for our internal tests to verify and fix the issue.

**Comment by sschlein** [comment]
Please follow these instructions to get some debug data?

Please go to C:\ProgramData\Herd and open the services.json and add the debug flag there?

It should look like this:

{
	"herdHelperPort": 5000,
	"logLevel": "debug"
}
After that, please restart the service.

Then go to C:\Windows\System32\logs and open the latest HerdHelper log – if you think there is anything sensitive and you don't want to share it shere, please email it to [support@beyondco.de](mailto:support@beyondco.de) but there should usually just be an indicator if something wasn't able to start.

**Comment by HyakuAr** [comment]
> Please follow these instructions to get some debug data?
> 
> Please go to C:\ProgramData\Herd and open the services.json and add the debug flag there?
> 
> It should look like this:
> 
> ```
> {
> 	"herdHelperPort": 5000,
> 	"logLevel": "debug"
> }
> ```
> 
> After that, please restart the service.
> 
> Then go to C:\Windows\System32\logs and open the latest HerdHelper log – if you think there is anything sensitive and you don't want to share it shere, please email it to [support@beyondco.de](mailto:support@beyondco.de) but there should usually just be an indicator if something wasn't able to start.

Here is the logs after I restarted herd and tried to go on my site. Btw I put port 5000 on Herd so idk why it's trying to do something on port 6000.


`2024-05-20 10:14:32.538 +02:00 [DBG] Hosting starting
2024-05-20 10:14:32.942 +02:00 [INF] Config path: C:\ProgramData\Herd\service.json.
2024-05-20 10:14:33.042 +02:00 [INF] Application started. Hosting environment: Production; Content root path: C:\Users\WINDOWS\.config\herd\bin\
2024-05-20 10:14:33.043 +02:00 [DBG] Hosting started
2024-05-20 10:14:33.058 +02:00 [INF] Config file with port exists, using port: 6000.
2024-05-20 10:14:33.179 +02:00 [INF] HTTP Server started on http://localhost:6000/.
`

**Comment by sschlein** [comment]
Just do double check that, your normal username is "WINDOWS" and that's not something that somehow went into the logs manually?

**Comment by sschlein** [comment]
@HyakuAr ?

**Comment by HyakuAr** [comment]
> Just do double check that, your normal username is "WINDOWS" and that's not something that somehow went into the logs manually?

Yes WINDOWS is my only user, and the one that I use

**Comment by sschlein** [comment]
Hey folks, can you please try this debug version?

[Download](https://herd-dev.fra1.digitaloceanspaces.com/test-builds/Herd-1.6.1-setup_preview.zip)

* Install debug version
* Go to General settings and enable the HerdHelper debug mode
* Restart Herd
* Check the logs (linked at the general settings, click on the path to get there)
* Also check the logs at %USERPROFILE%\AppData\Roaming\Herd\logs

You can either post the logs here or send them to support@beyondco.de (and please mention this issue #674

**Comment by HyakuAr** [comment]
I just sent a mail to the said email, with the number of the ticket.

**Comment by HyakuAr** [comment]
Okay, I fixed the issue to do that I had to fix the hosts file on my PC that was on read only and seemed to be bugged. I had to grant myself permissions to modify it. And after that I replaced the original hosts file on my PC with the hosts file from my laptop, that worked fine. I can now go on the .test sites.

**Comment by sschlein** [comment]
@HyakuAr if you create a new site, is this available directly? If yes, Herd can properly write to the hosts file. 

Please make sure to disable debug output, its logging quite a bit of information.

**Comment by HyakuAr** [comment]
Yep everything is working just fine.

**Comment by clausbertels** [comment]
I'm having the same issue (see above) on mac, but whatever I do, Herd doesn't seem to write to hosts.

**Comment by mechelon** [comment]
@clausbertels Herd on Mac does not write to the hosts file, it is using Dnsmasq for routing. You can check if it's running correctly via the menu bar (logs are there too), so feel free to create a new issue if you continue to have problems.

**Comment by clausbertels** [comment]
@mechelon Thanks for the reply. I made an issue here: https://github.com/beyondcode/herd-community/issues/1008

All seems to run fine. Herd's dnsmasq shows an empty log when I click this

<img width="266" alt="Scherm­afbeelding 2024-09-20 om 18 34 31" src="https://github.com/user-attachments/assets/6e4343be-73ed-408e-93df-569057252199">

**Comment by kabalaandrew** [comment]
I have the same problem on Windows. The I have tried all ways of resolving the Herdhelper issue, but no fix has worked.

**Comment by zakblacki** [comment]
2026-01-27 14:31:30.982 +01:00 [INF] No Herd-specific sections found. Adding new ones.
2026-01-27 14:31:30.982 +01:00 [INF] Writing updated contents to the hosts file.
2026-01-27 14:31:30.982 +01:00 [ERR] Error while writing to hosts file: Access to the path 'C:\Windows\System32\drivers\etc\hosts' is denied.
