### ISSUE TITLE
[Bug]: mysql command not found

### ISSUE THREAD

**Issue by saschagysel** [beyondcode/herd-community#677]
### Platform

Windows

### Operating system version

Windows 11

### System architecture

Windows

### Herd Version

1.1.0

### Bug description

I installed a fresh installation of Laravel Herd for Windows and enabled Pro features. Then I installed the MySQL service with the standard settings and I checked with TablePlus whether the server is working correctly (everything ok). In my projects terminal (in the PowerShell or PHPStorm) when I try to run `php artisan migrate` for the first time I am getting an error that the command mysql was not found.

According to the documentation (https://herd.laravel.com/docs/1/herd-pro-services/mysql#connecting-via-cli) Herd symlinks MySQL. I suspect that Herd did not create the environment variable / symlink correctly for MySQL and therefore PowerShell does not recognize the command.

Is there a way / command to manually create the environment variable / symlink?

I also tried to run Herd "As an administrator" and re-create the database service in hope that the environment variable will be created but it did not solve the problem.

An additional button in the mySQL section of Herd to create the variable would be helpful in this case.

### Relevant log output

```shell
The command "mysql  --user="${:LARAVEL_LOAD_USER}" --password="${:LARAVEL_LOAD_PASSWORD}" --host="${:LARAVEL_LOAD_HOST}" --port="${:LARAVEL_LOAD_PORT}" --database="${:LARAVEL_LOAD_DATABASE}" < "${:LARAVEL_LOAD_PATH}"" failed.

Error Output:
================
'mysql' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by mpociot** [comment]
Which Laravel version is this? I didn't have any issues migrating, even without MySQL being in my PATH. 

You can manually place the folder in your PATH, it's in %USERPROFILE%\.config\herd\bin\services

I'm not in front of my computer right now, so I don't know the exact location. It should be in a subdirectory there 🙂

**Comment by saschagysel** [comment]
> Which Laravel version is this? I didn't have any issues migrating, even without MySQL being in my PATH.
> 
> You can manually place the folder in your PATH, it's in %USERPROFILE%.config\herd\bin\services
> 
> I'm not in front of my computer right now, so I don't know the exact location. It should be in a subdirectory there 🙂

It's Laravel 11 latest version

**Comment by saschagysel** [comment]
Thanks Marcel for the hint. Adding this to the "Path" system variable worked:

![image](https://github.com/beyondcode/herd-community/assets/58490316/d4ff525b-b246-4496-b818-7d95b1710365)

I suggest that Herd adds that automatically to make it convenient. Also what happens when the MySQL version and therefore the path to it changes? Does Herd modify the environment variable?

**Comment by mpociot** [comment]
Herd does not allow updating services, due to potential data loss. Instead you would need to manually create a new version of the service yourself. 

The macOS version for example allows you to define which service gets symlinked/added to the PATH. 
I think we'll add something similar to the Windows version.

**Comment by chris-bkjg** [comment]
@mpociot at a minimum, this should probably be documented.  https://herd.laravel.com/docs/windows/1/herd-pro-services/mysql makes it seem like Herd is just point and click installs of MySQL on Windows, but the step covered in this issue are still required to get a fresh install of Herd working on a fresh install of Windows.

**Comment by sschlein** [comment]
@chris-bkjg 

I've added it to the docs 👍

**Comment by chris-bkjg** [comment]
@sschlein it's not just command line connections.  This is also an issue if the Laravel application has squashed migrations.

**Comment by sschlein** [comment]
Whoops missed that, it's added now.

**Comment by dasundev** [comment]
i am experiencing a similar issue on macos. my project has squashed migrations.

Herd 1.28.0 (Build: 64)
PHP 8.4.21
Laravel 12.60.2

P.S.

i was able to fix it by creating a mysql binary symlink. if anyone is looking for a solution on macos, run the following command:

```bash
sudo ln -s "/Users/dasun/Library/Application Support/Herd/bin/mysql" /usr/local/bin/mysql
```

cc: @mpociot @sschlein
