### ISSUE TITLE
[Bug]: Herd Installation Crash on Launch

### ISSUE THREAD

**Issue by mmourani** [beyondcode/herd-community#679]
### Platform

macOS

### Operating system version

macOS Sonoma 14.4.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.6.0

### Bug description

I've encountered an issue with the Herd application for Laravel. After downloading the latest .dmg file from the official website, I attempted to install it on my system. However, every attempt to start the application results in an immediate crash without the application window even appearing.

### Steps to reproduce

Download the .dmg file from [Herd official website].
Open the .dmg file and move Herd to the Applications folder.
Double-click to launch Herd from the Applications folder.

### Relevant log output

```shell
The application crashes instantly on startup.
```

**Comment by mmourani** [comment]
no display of a report on the screen. I can check the log file. Where is it located ?

**Comment by mpociot** [comment]
How do you know that it crashes when there's no crash-report window? 🤔 
Are you sure it's not running in the activity monitor?

**Comment by mmourani** [comment]
I try to run it, I see it very briefly appearing on the activity monitor and then just disappear without any error or crash report. I had it running before but i removed it and reinstalled due to the fact i could get it to resolve and display the active folders that i had registered with it.
