### ISSUE TITLE
[Bug]: Error with Mail feature when sending Emails  within a loop

### ISSUE THREAD

**Issue by rockblings** [beyondcode/herd-community#681]
### Platform

macOS

### Operating system version

macOs Sonoma 14.4.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.6.0 (Build: 24)

### PHP Version

PHP: 8.3

### Bug description

I have an email services that sends email to a # of users. So the emails are added to a queue, then loop over each one to send. i got the error after the 2nd email `"Expected response code "354" but got code "421", with message "421 Error: too many unauthenticated commands" `everytime.
here is my .env mail config

MAIL_MAILER=smtp
MAIL_HOST=127.0.0.1
MAIL_PORT=2525
MAIL_FROM_NAME="${APP_NAME}"

**Comment by mechelon** [comment]
What value has `MAIL_ENCRYPTION`? Which queue driver are you using and how many emails (approximately) are you trying to send?

**Comment by rockblings** [comment]
> What value has `MAIL_ENCRYPTION`? Which queue driver are you using and how many emails (approximately) are you trying to send?

it is `tls`

**Comment by mechelon** [comment]
Can you please set the `MAIL_ENCRYPTION` setting to null (like this: `MAIL_ENCRYPTION=`) and try again?

**Comment by rockblings** [comment]
> Can you please set the `MAIL_ENCRYPTION` setting to null (like this: `MAIL_ENCRYPTION=NULL`) and try again?

Yes it worked now. Thanks
