### ISSUE TITLE
[Bug]: Run php artisan, no additional .ini files

### ISSUE THREAD

**Issue by phanuwit267** [beyondcode/herd-community#684]
### Platform

macOS

### Operating system version

macOS Sonoma Version 14.4.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.6.0

### PHP Version

8.2.18

### Bug description

Run php artisan, no additional .ini files
<img width="979" alt="Screenshot 2567-04-22 at 22 49 59" src="https://github.com/beyondcode/herd-community/assets/24976372/11e5931d-6a26-4bfe-9aa0-6735c6d5eb83">

This run command: php -S localhost:8000 public/index.php
<img width="979" alt="Screenshot 2567-04-22 at 22 49 50" src="https://github.com/beyondcode/herd-community/assets/24976372/7221fb39-d50a-42bc-83a5-b9e18c200470">

**Comment by sschlein** [comment]
I am afraid that I don't understand what you mean with running `php artisan` and then get a phpinfo output.I am also wondering why you are starting the local php server with php instad of using nginx with Herd and accessing your project via it's `.test` domain.

**Comment by phanuwit267** [comment]
Use php of herd program
And I run the ```php artisan``` command and compared it with the command ```php -S localhost:8000 public/index.php```


which ```php artisan``` command
Additional .ini files do not work.

**Comment by sschlein** [comment]
We do not recommend using this in a Herd environment, Herd ships with nginx as a web server, so that you can access your sites via a local domain. This takes care of loading php ini files.

**Comment by phanuwit267** [comment]
So I use php with homebrew which is probably the easiest way to develop.

**Comment by sschlein** [comment]
If you are using Homebrew PHP, this is not the right place to create an issue. This is the community repository of Laravel Herd (https://herd.laravel.com/) which is an alternative to Homebrew.

**Comment by mpociot** [comment]
This is an issue in your Laravel version. This was sent as a PR to Laravel 10.

**Comment by phanuwit267** [comment]
Interesting!
Thank you @mpociot
