### ISSUE TITLE
[Bug]: NVM not working

### ISSUE THREAD

**Issue by draske79** [beyondcode/herd-community#685]
### Platform

Windows

### Operating system version

Windows 11

### System architecture

Windows

### Herd Version

1.1.0

### PHP Version

PHP 8.2

### Bug description

After removing the old NVM, node, etc on Windows and removing the system variables as mentioned before Herd offers to install node on my pc. The process completes, I see very quickly the interface to install different node versions and then I get below.

![image](https://github.com/beyondcode/herd-community/assets/37485861/3e73c807-7784-49cc-a612-6b9ec63574bb)

Several cleaning, reinstalling processses where attemted without avail. Node does work from the command line and all paths point to the one installed by Herd.

In the main.log I noticed the line below. Note that my last name is in the user.

[2024-04-04 08:15:37.154] [info]  [NodeVersionManager] parseNodeVersionList: [
  "'C:\\Users\\Andreas' is not recognized as an internal or external command,\r",
  'operable program or batch file.\r',
  ''
]

So i would expect a link like this:
C:\\Users\\FirstName LastName\Herd\...

This seems to happen correctly in all other references I find in the log.

### Steps to reproduce

Windows username has a space.
We remove old node from Windows 11, and remove the system variables. Then we install herd. Herd offers to install NVM which completes.

### Relevant log output

```shell
[2024-04-04 08:15:37.153] [info]  [NodeVersionManager] installedNodeVersions: 'C:\Users\Andreas' is not recognized as an internal or external command,
operable program or batch file.

[2024-04-04 08:15:37.154] [info]  [NodeVersionManager] parseNodeVersionList: [
  "'C:\\Users\\Andreas' is not recognized as an internal or external command,\r",
  'operable program or batch file.\r',
  ''
]
[2024-04-04 08:15:37.156] [info]  [NodeVersionManager] installedNodeVersions: 
[2024-04-04 08:15:37.157] [info]  [NodeVersionManager] parseNodeVersionList: [ '' ]
```

**Comment by OscarKolsrud** [comment]
Seems like I am experiencing the same issue here!

NVM etc. all installed correctly, but not being detected by Herd.

My username in windows has a space in it which i suspect is causing the issue aswell, holding a bit back from purchasing a Pro license until i know it will work.
