### ISSUE TITLE
[Feature Request]: Uninstall PHP version

### ISSUE THREAD

**Issue by Quaap70** [beyondcode/herd-community#69]
### Feature Description

Now you can install all versions of PHP from version 7.4. Will there also be an option to uninstall a version in the future, because otherwise the list could become very long.

**Comment by mpociot** [comment]
Right now you can easily uninstall a PHP version by simply deleting the binaries from your `~/Library/Application Support/Herd/bin` folder. Just make sure that there is no FPM instance currently using this version/stop Herd before.

The main problem with "uninstalling" PHP version is that it's not as simple as it seems.
You could run `herd isolate 7.4` to isolate a specific site to always use PHP 7.4. If you would then delete PHP 7.4 this site would no longer work, which might be confusing.

**Comment by GDanielRG** [comment]
I imagine this also applies to Node? @mpociot
