### ISSUE TITLE
[Bug]: Herd installed PHP version will not use the Herd configuration files without specifying them manually

### ISSUE THREAD

**Issue by trueparallels** [beyondcode/herd-community#693]
### Platform

macOS

### Operating system version

macOS Ventura 13.6.3

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.6 (build 24)

### PHP Version

PHP 8.3.6 (cli) (built: Apr 12 2024 00:13:56) (NTS)

### Bug description

I specifically need Memcached installed to run our local test suite, and the current iteration of Herd does not include the module by default. I compiled the memcached module using the instructions [here](https://herd.laravel.com/docs/1/advanced-usage/additional-extensions).

Here is my current `php.ini` file at `~/Library/Application Support/Herd/config/php/83/php.ini`:
```
extension=/opt/homebrew/lib/php/pecl/20230831/memcached.so

auto_prepend_file = /Users/<redacted>/.composer/vendor/spatie/global-ray/src/scripts/global-ray-loader.php
curl.cainfo=/Users/<redacted>/Library/Application Support/Herd/config/php/cacert.pem
openssl.cafile=/Users/<redacted>/Library/Application Support/Herd/config/php/cacert.pem
pcre.jit=0

memory_limit=2048M
upload_max_filesize=2M

zend_extension=/Applications/Herd.app/Contents/Resources/xdebug/xdebug-83-arm64.so
xdebug.mode=debug,develop
xdebug.start_with_request=yes
xdebug.start_upon_error=yes
xdebug.log_level=0
```

Here's my installed version:
```
$ which php && php -v
/Users/<redacted>/Library/Application Support/Herd/bin/php
PHP 8.3.6 (cli) (built: Apr 12 2024 00:13:56) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.3.6, Copyright (c) Zend Technologies
    with Zend OPcache v8.3.6, Copyright (c), by Zend Technologies
```

And here's the output when using `php -m` on the CLI (with and without specifying the config manually)
```
$ herd php -m | grep -i memcached
$ herd php -c ~/Library/Application\ Support/Herd/config/php/83/php.ini -m | grep -i memcached
memcached
$
```

I assuming this is a bug based on this snippet from the [Changing PHP.ini settings page](https://herd.laravel.com/docs/1/advanced-usage/php-settings) of the docs:
> The changes will be immediately available to the PHP CLI version, but you will need to restart all Herd services to apply the changes to HTTP requests via nginx.

**Comment by mpociot** [comment]
What do you get when you run `herd php --ini`?

**Comment by mpociot** [comment]
Which shell are you using? 
Herd uses environment variables to load php.ini files.

For example:
```
export HERD_PHP_83_INI_SCAN_DIR="/Users/marcelpociot/Library/Application Support/Herd/config/php/83/"
```

But `herd php -v` gives you PHP 8.3.6?

**Comment by trueparallels** [comment]
I'm using Fish shell. I don't have any Herd-specific environment variables set. `herd php -v` does indeed give me 8.3.6.

Am I get some sort of weird experience because I'm not using Herd in the context of a parked site(s)? Our applications are not Laravel currently, and I'm not using the parked directory features because all our stuff is Dockerized on local.

**Comment by mpociot** [comment]
You don't need to use the parked directory feature as you can also just manually link sites, that's not a problem.

The fish shell is not officially supported, which is why you're missing the environment variables.

Please see:

https://github.com/beyondcode/herd-community/issues/428#issuecomment-2042930061

**Comment by trueparallels** [comment]
Ah, ok. Thanks for all your help.

Out of curiosity, how does that work? Is Herd just appending exports to `.bashrc`/`.zshrc`?

**Comment by ndberg** [comment]
It might be helpful to add this information to the documentation, as it's a bit [misleading](https://herd.laravel.com/docs/macos/getting-started/installation#using-herd-with-fish) — it gives the impression that it should work with Fish after adding the path using fish_add_path.

Took me a while to figure this out — glad I finally found the info here.
