### ISSUE TITLE
[Bug]: Version mismatch

### ISSUE THREAD

**Issue by nielspeen** [beyondcode/herd-community#7]
### Operating system version

macOS 13.4.1

### Herd Version

1.0.8 (Build: 10)

### Bug description

Herd Settings shows 8.2 (8.2.7) as installed.

PHP however claims to be version 8.2.6:

```
 "/Users/niels/Library/Application Support/Herd/bin/php" -v
PHP 8.2.6 (cli) (built: Jun  2 2023 23:59:34) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.6, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.6, Copyright (c), by Zend Technologies
```

**Comment by neurotools** [comment]
Can confirm...

<img width="491" alt="imagen" src="https://github.com/beyondcode/herd-community/assets/6556055/67c7e8cc-97de-41f3-8ea8-07a56b94a161">

**Comment by mpociot** [comment]
We published a new PHP update yesterday. Please open your settings to update to the new version 👍
