### ISSUE TITLE
[Bug]: Herd does not use the global php.ini file

### ISSUE THREAD

**Issue by dmorda** [beyondcode/herd-community#70]
### Operating system version

macOS Ventura 13.5

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.1.1 (Build 12)

### Bug description

I've created a php.ini file in the following location:

`~/Library/Application Support/Herd/config/php/php.ini`

I've added the following lines to it:

```
log_errors = On
error_reporting = E_ALL & ~E_NOTICE
```

After making the change, I've run:

`herd restart`

After doing this and using the <?php php_info(); ?> to display the configuration, log_errors is still off. However, if I make the same change to the php.ini in the "82" or "81" folders, it works as expected. It's almost as though Herd is ignoring the global php.ini.

**Comment by mpociot** [comment]
Right - this behavior changed with the latest release of Herd. 
All PHP versions now have individual php.ini files, which makes it easier to customize version specific settings

**Comment by dmorda** [comment]
Ok, so then I think what confused me is the documentation here that still says you can add a global php.ini file. 

https://herd.laravel.com/docs/1/advanced-usage/php-settings
