### ISSUE TITLE
[Bug]: Laravel CLI and Composer version

### ISSUE THREAD

**Issue by Nothing-Works** [beyondcode/herd-community#701]
### Platform

Windows

### Operating system version

Win 10

### System architecture

Windows

### Herd Version

latest

### PHP Version

8.3

### Bug description

Does herd update Laravel cli and composer version? I can see Laravel and composer are not the latest version.

**Comment by sschlein** [comment]
Yes, we do that with Herd updates, so there's no need to do that manually :)

We sometimes might miss an update but we try to keep both of them updated.
