### ISSUE TITLE
[Bug]: node version 22 not listed on UI

### ISSUE THREAD

**Issue by Nothing-Works** [beyondcode/herd-community#702]
### Platform

macos monterey

### Operating system version

macos

### System architecture

Intel (x86)

### Herd Version

1.6

### PHP Version

8.3

### Bug description

<img width="795" alt="image" src="https://github.com/beyondcode/herd-community/assets/18606648/3c959169-434b-4b21-b800-d689d229b7b1">
node 22 is not listed,

**Comment by sschlein** [comment]
Looks like we forgot to close this issue, it's there for a while :)
