### ISSUE TITLE
[Bug]: I get a 404 - Site not found when trying to access my .test websites

### ISSUE THREAD

**Issue by loddaa** [beyondcode/herd-community#703]
### Platform

macOS

### Operating system version

macOS Sonoma 14.4.1 (23E224)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.6.0

### PHP Version

PHP 8.3.6 (cli) (built: Apr 12 2024 00:13:56) (NTS)

### Bug description

# I get a 404 - Site not found for my hello.php

- I can't access my .test websites in `~/Programming/laravel/` even after doing `herd park laravel`. 
- I tried to restart Herd services via the GUI first with `Stop all` and `Force stop all` but nothing changed.

### Here is the project tree : 
laravel
└── abc
    └── hello.php

2 directories, 1 file

### Here are some screenshots : 

**NOTE** The first Herd path was generated in the terminal using `herd park laravel` in `~/Programming/` and the second Herd path was generated using the GUI :
<img width="978" alt="Screenshot 2024-04-29 at 11 24 08" src="https://github.com/beyondcode/herd-community/assets/122743614/75f329cc-a2d5-4ca8-b775-46d462cda543">

Here is the page when I try to access http://abc.test : 
<img width="1470" alt="Screenshot 2024-04-29 at 11 24 26" src="https://github.com/beyondcode/herd-community/assets/122743614/89ddb5a0-11bf-4360-82ae-316359b52709">

### Relevant log output

```shell
Warning
: opendir(laravel): Failed to open directory: No such file or directory in
/Applications/Herd.app/Contents/Resources/valet/cli/Valet/Server.php
on line
163

----

Request URL:
http://abd.test/
Request Method:
GET
Status Code:
404 Not Found
Remote Address:
127.0.0.1:80
Referrer Policy:
strict-origin-when-cross-origin
```

**Comment by mpociot** [comment]
Seems like the `laravel` is resulting in an error.
When parking, you should provide the absolute path to the folder that contains your projects.

Remove the `laravel` folder and you're good to go.
