### ISSUE TITLE
How to change Shortcut Ctrl + C to open Herd?

### ISSUE THREAD

**Issue by ocontreras4** [beyondcode/herd-community#705]
### Platform

Windows

### Operating system version

windows 11

### System architecture

Intel (x86)

### Herd Version

1.1.0

### PHP Version

PHP 8.3.6

### Bug description

Hi, how to change the shortcut to open Herd with Ctrl + C for another keys? 
It is annoying since I use it for copy in windows ![Bug]: 

### Relevant log output

```shell
change shortcuts configuration ?
```

**Comment by mpociot** [comment]
I'm not sure which shortcut you mean, but you can configure all Herd shortcuts here:

![image](https://github.com/beyondcode/herd-community/assets/804684/c023d4ad-ba2a-4252-8733-4fea62f4bbe4)

**Comment by ocontreras4** [comment]
Hi, Thanks for your support , I change back the shortcuts keys and I solved the problem that every time I press Ctrl + C keys for copy something in windows instead open the Herd windows  so the combination keys in the shortcut keys Ctrl + Up + C is = Ctrl + C  anyway this was solved but now I cannot open the window of Herd anymore ! I even uninstalled it twice but i only can see that is running in background because I see it in the task manager as you can see in the attached file!  What Can I Do ?

I tried for some days and I did like too much and would like to pay for the pro version !

Sincerely

Oscar Contreras
Ph. +1-786-729-0406  Email: ***@***.***

The information transmitted by this e-mail and in any attachments is
intended only for the addressee and is considered confidential and/or
privileged material. Unauthorized forwarding, printing, copying,
distributing or using any information contained in this e-mail is strictly
prohibited and may be unlawful. If you are not the addressee, please
promptly delete this message and notify the sender of the delivery error
by return e-mail.



________________________________

**Comment by mpociot** [comment]
Herd is a system tray application. The Herd icon should be there, next to your system clock.

**Comment by ocontreras4** [comment]
ok. Thanks, I just found ! It should give a message when I click the Icon !

Sincerely

Oscar Contreras
Ph. +1-786-729-0406 Email: ***@***.***

The information transmitted by this e-mail and in any attachments is
intended only for the addressee and is considered confidential and/or
privileged material. Unauthorized forwarding, printing, copying,
distributing or using any information contained in this e-mail is strictly
prohibited and may be unlawful. If you are not the addressee, please
promptly delete this message and notify the sender of the delivery error
by return e-mail.



________________________________
