### ISSUE TITLE
[Bug]: PHP installation fails unrecoverably when offline [Might sound like a silly issue, please read it though]

### ISSUE THREAD

**Issue by tmbenhura** [beyondcode/herd-community#707]
### Platform

Windows

### Operating system version

Windows 11 23h2 22631.3447

### System architecture

Intel (x86)

### Herd Version

1.1.0

### PHP Version

None

### Bug description

If you setup Herd whilst offline, it attempts to install PHP 8.3. This fails as an active internet connection is required, even if the internet is enabled whilst it is waiting/attempting to execute. A check for an active internet connection is needed.

Presumably it times out quietly and despite this failure, the configuration is updated to reflect a successful installation of PHP 8.3.

Opening herd services will have PHP in red with an info:
C:\Users\xxx\.config\herd\bin\php83\php-cgi.exe ENOENT

The C:\Users\xxx\.config\herd\bin\php83\ directory does not exist.

Opening the PHP section infinitely shows the red bubble loader, but also included the list of PHP versions. With PHP 8.3 showing an Install button, implying it is not installed, but nothing is clickable presumably as the loader is trying to resolve the ghost PHP installation. As a result, none of the PHP versions can be installed. A re-install option would also help to fix corrupted PHP installations.

Uninstalling and re-installing Herd doesn't directly resolve the problem as configuration files are preserved between installations, so a "preserve settings" option in the installer would also be great.

Deleting the .config directory and re-installing Herd, whilst online, resolves the primary issues faced. 

### Steps to reproduce

1. Turn off/disable Internet connection
2. Install Herd
3. Open Herd
4. Re-activate Internet connection
5. Attempt to create a site

**Comment by sschlein** [comment]
Hi @tmbenhura 

We consider this a super edge case and assume that people who download Herd also install it directly and then have an internet connection. Happy to implement a solution for this once this happens regularly to people but for now, it doesn't seem to happen that often for many many installs.
