### ISSUE TITLE
[Bug]: Herd Pro Mail SSL error

### ISSUE THREAD

**Issue by otrsw** [beyondcode/herd-community#708]
### Platform

Windows

### Operating system version

Windows 11

### System architecture

Intel (x86)

### Herd Version

1.1.0

### PHP Version

PHP 8.3

### Bug description

I followed all the default installation and setup instructions for using the Mail service.
When sending a mail, the Herd service is reached (since I can see an error message in the logs).
Since the secure serve is working, I assume it is not CA cert related - but I am unsure how to proceed

### Relevant log output

```shell
1057216:error:10000418:SSL routines:OPENSSL_internal:TLSV1_ALERT_UNKNOWN_CA:..\..\third_party\boringssl\src\ssl\tls_record.cc:592:SSL alert number 48
```

**Comment by mpociot** [comment]
Can you try and make sure that `MAIL_ENCRYPTION=null` is in your .env file?

**Comment by otrsw** [comment]
Geez that was fast and simple!

I added that and it resolved (previously tried MAIL_ENCRYPTION=false).
Did I miss that in the docs somewhere?

Thank you for a great product and super support!

Heinz
________________________________

**Comment by mpociot** [comment]
It'll be fixed in the next Herd release, and I'll adjust the docs now!
