### ISSUE TITLE
[Bug]: Securing site via herd results in nginx failure: "cannot load certificate" and "no such file or directory"

### ISSUE THREAD

**Issue by gtmassey** [beyondcode/herd-community#709]
### Platform

macOS

### Operating system version

macOS Sonoma 14.4.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.6.0 (Build: 24)

### Bug description

The issue seems to be directly related to #396, where a user is attempting to run Herd on a non-admin account. 

When trying to secure a site via Herd (both through the GUI and the terminal), nginx stops, and fails with variations of the following error:

```
2024/05/02 11:18:46 [emerg] 2360#12921: cannot load certificate "/Users/myuser/Library/Application Support/Herd/config/valet/Certificates/mysite.test.crt": BIO_new_file() failed (SSL: error:80000002:system library::No such file or directory:calling fopen(/Users/myuser/Library/Application Support/Herd/config/valet/Certificates/mysite.test.crt, r) error:10000080:BIO routines::no such file)
```

To get Herd to restart nginx properly, I have to go in and delete `Users/myuser/Library/Application Support/Herd/config/valet/nginx/mysite.test`

once deleted, I can successfully restart Herd's services, but the site is still unsecured, and the error returns if I try to secure the site.

### Steps to reproduce

1. Install Herd 1.6 on MacOS Sonoma in a non-admin account using an elevated admin account for installation.
2. Enter the admin account credentials when prompted by osscript
3. once installed, Herd services cannot start, so find and edit the `etc/sudoers.d/herd` file:
**Original:**
`%staff ALL=(root) NOPASSWD:SETENV: /Applications/Herd.app/Contents/Resources/*, /usr/bin/security, /bin/kill`
**Edited:**
`myuser ALL=(root) NOPASSWD:SETENV: /Applications/Herd.app/Contents/Resources/*, /usr/bin/security, /bin/kill`
OR
`%staff ALL=(root) NOPASSWD:SETENV: /Applications/Herd.app/Contents/Resources/*, /usr/bin/security, /bin/kill`
if your user is part of a specific managed group. Both options lead to the same behavior.
4. Restart Herd Services. You may need to restart the machine.
5. Create a new test site
6. If using the GUI, secure the new site, and you should see that nginx fails with a similar error
7. If not using GUI and instead using the terminal, navigate to the site's directory and run `herd secure`

I believe, like I mentioned before, this is directly related to the way Herd tries to spoof sudo access / expects admin access for certain commands as mentioned in #396 but I am unable to get Herd's secure / SSL certs to work with the current setup. I can get herd to run and to serve sites without SSL certificates over HTTP, but for specific sites, we require testing over https to work with our oAuth.

### Relevant log output

```shell
2024/05/02 11:18:46 [emerg] 2360#12921: cannot load certificate "/Users/myuser/Library/Application Support/Herd/config/valet/Certificates/mysite.test.crt": BIO_new_file() failed (SSL: error:80000002:system library::No such file or directory:calling fopen(/Users/myuser/Library/Application Support/Herd/config/valet/Certificates/mysite.test.crt, r) error:10000080:BIO routines::no such file)
```

**Comment by garrettmassey1** [comment]
I was able to get the SSL certificates to work by adding my username specifically to the sudoers file (not the herd sudoers), and granting explicit permissions to run all openssl commands, but this is still a temporary workaround since my sudoers file is not controlled by my user, but by the workspace admin, and I only have temporary admin rights for that file. It works for now, but some kind of permission elevation / management feature would be great.

**Comment by mpociot** [comment]
The next macOS update will introduce a different permission management, so hopefully manually modifying this is no longer needed.
