### ISSUE TITLE
(please leave open!) THANK YOU for Herd!

### ISSUE THREAD

**Issue by connecteev** [beyondcode/herd-community#71]
Just want to thank @mpociot and everyone involved for the amazing work with Herd - it's the tool I didn't know I needed. It's just one of those things that makes development with Laravel slightly less painful, and the Laravel community so awesome.

**Comment by mpociot** [comment]
Thank you very much! ❤️ 
I'll still close this issue though, as I don't want too many open issues on this repo haha
