### ISSUE TITLE
[Bug]: xDebug ini not loaded

### ISSUE THREAD

**Issue by DavidLambauer** [beyondcode/herd-community#714]
### Platform

macOS

### Operating system version

macOS Sonoma 14.4.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.6.0

### PHP Version

PHP 8.1.26 (cli) (built: Dec 21 2023 08:51:01) (NTS)

### Bug description

I followed the documentation for debugging with xDebug. It didn't work out of the box. A `php_info()` and a `php -m | grep debug` showed that xDebug is not yet present. Although the `debug.ini` file exists under `/Users/<MYUSER>/Library/Application Support/Herd/config/php/81/php.ini`, it was not loaded. 

![CleanShot 2024-05-07 at 14 17 53](https://github.com/beyondcode/herd-community/assets/1841317/2baaf934-6363-4a47-ad70-931c1f717035)

After moving the `debug.ini` to the same directory as the `php.ini`, xDebug was loaded and worked as expected.

![CleanShot 2024-05-07 at 14 19 05](https://github.com/beyondcode/herd-community/assets/1841317/7d1bac8a-bf3c-4f06-aa74-9489a8ddb7e6)

### Steps to reproduce

...

### Relevant log output

```shell
...
```

**Comment by mpociot** [comment]
There's no need to move the ini file.
You can use `herd debug` to dynamically enable xdebug/load the debug.ini 

See https://herd.laravel.com/docs/1/herd-pro/xdebug#using-xdebug-on-the-command-line

**Comment by DavidLambauer** [comment]
If that only would be available...

![CleanShot 2024-05-07 at 14 24 56](https://github.com/beyondcode/herd-community/assets/1841317/06544b77-d6e4-4798-b1e9-437f95b669ec)
