### ISSUE TITLE
[Bug]: `herd`, `php` and `composer` commands are not recognized

### ISSUE THREAD

**Issue by AnaelBonnafous** [beyondcode/herd-community#715]
### Platform

Windows

### Operating system version

Windows 11 (23H2 22631.3447)

### System architecture

Windows

### Herd Version

1.1.0

### Bug description

`herd`, `php` and `composer` commands are not recognized when used globally : 'Path not found', but `.phar` files are here.

I have `C:\Users\<user>\.config\herd\bin` added to my user paths as you can see :

![image](https://github.com/beyondcode/herd-community/assets/71386173/406f1f92-5b57-4494-acdd-77dc62c52518)

My Windows username is 'Anaël', so maybe it has to be related with special char and wrong path resolution ?

### Steps to reproduce

Fresh install of Herd 1.1.0 on Windows 11 with an user that have special char in name.

**Comment by mpociot** [comment]
Which shell are you using there? 
`herd`, `php` and `composer` are all `.bat` files.
Does it work by running `php.bat -v`?

**Comment by AnaelBonnafous** [comment]
I'm using Cmder as my main terminal.
Okay I see, all `.bat` files are here too.
No, I got the same output, but it work when running `php.exe -v`

**Comment by mpociot** [comment]
This is a duplicate of https://github.com/beyondcode/herd-community/issues/651

Before this is patched, you can manually modify the .bat files and replace your username with %USERPROFILE%

**Comment by AnaelBonnafous** [comment]
Thanks you, this fix works !
I just have to do it for the `php.bat` file each time I change the active php version but that's okay
Waiting for the patch and other new features, good continuation to you and your team 🙏
