### ISSUE TITLE
[Bug]: Herd Debug not loading extensions

### ISSUE THREAD

**Issue by dkdev420** [beyondcode/herd-community#720]
### Platform

Windows

### Operating system version

Windows 11

### System architecture

Windows

### Herd Version

1.1.0

### Bug description

When trying to debug using the `herd debug` command, PHP extensions are not loaded. 
Running  `herd debug --ini` I see that only debug.ini is loaded:

```
Loaded Configuration File:         C:\Users\*****\.config\herd\config\php\83\debug\debug.ini
Scan for additional .ini files in: (none)
Additional .ini files parsed:      (none)
```

which contains 

```
zend_extension=C:\Users\*****\.config\herd\bin\xdebug\xdebug-8.3.dll
xdebug.mode=debug,develop
xdebug.start_with_request=yes
xdebug.start_upon_error=yes
```

As an example, a simple command like
```
$var = "Hello World";
$this->line($var);
```

debugs just fine, but as soon as you add queries or something that requires an extension, it results in _could not find driver_ error.

Am I missing something?

**Comment by mpociot** [comment]
This will be fixed in the next release 👍
