### ISSUE TITLE
[Bug]: unable to change Environment Variables of Reverb service ?

### ISSUE THREAD

**Issue by ValoXya** [beyondcode/herd-community#722]
### Platform

macOS

### Operating system version

macOS SONOMA 14.4.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.6.1

### PHP Version

PHP 8.2.16

### Bug description

Hy there, 

Not sure if I missed something or if it's not possible but I faced a configuration issue by using Reverb. 

By default it is starting on Herd with variables set on **Environment Variables**
The thing is it doesn't work by default on my dev version of website. I had to change some parameters and when I launch on terminal reverb with those news params it is working fine (same as .env). 

I tried to reload services, restart, update but it seems to keep defaults values 

So, I would like to know if it's possible to adapt **Environment Variables** provided by Herd, because if I'm start Reverb throw it, it do not take in consideration my .env file and keep is defaults values instead of mines.

I would like to use log windows but now it is just showing the logs of running server where nothing is happening.

Thank for your reply

### Steps to reproduce

Just launch Reberb services with Herd

### Relevant log output

```shell
INFO  Starting server on 0.0.0.0:8080.  

  Pruning Stale Connections ..................................................  
  Pinging Inactive Connections ...............................................
```

**Comment by mpociot** [comment]
I haven't quite understood which environment variables you want to change.
The Herd service is installed at /Users/Shared/Herd/services/reverb - where the .env file can also be found that will be used for starting the actual server.
