### ISSUE TITLE
[Bug]: Herd Application won't start

### ISSUE THREAD

**Issue by dragoszapiet** [beyondcode/herd-community#728]
### Platform

macOS

### Operating system version

macOS Sonoma 14.1.1 Build 23B81

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

Latest Version (can't open UI, I don't know)

### PHP Version

PHP 8.3.7

### Bug description

Trying to open Herd application UI and it does not open.

### Steps to reproduce

Steps I did:

1. Download Herd from the official website
2. Drag the Herd into the Apps icon
3. Open Herd application
4. Not opening at all 
5. Restart/Shutdown Mac still the same issue.

I did uninstall and reinstall 2 times and with no luck.

**Comment by dragoszapiet** [comment]
Hey,

It wasn't active and visible at all. But it seems that somehow it manage to appear in the system tray after more time. Not sure if this was a bug or something, if you need anything from me maybe other people experienced the same issue?

(Now it works fine).
________________________________

**Comment by sschlein** [comment]
That sounds super odd and I'd consider this an anomaly that might be related to a virus scanner or something else. 

I don't think that there is something that we can actually do about it and so I am closing this issue for now. Please let me know if it disappears again but it should stay in the system tray as usual.

**Comment by Bracketstech** [comment]
Have the same issue with mac it opens and closes directly

**Comment by sschlein** [comment]
What about the activity monitor?

**Comment by FrenchMajesty** [comment]
For me, I can see that it's the Activity Monitor but no icon in the system tray. If I manually kill Herd and attempt to re-open, I still cannot get to the GUI.

**Comment by sschlein** [comment]
My guess is that you have too many icons there and your screen hides it. You can try closing other apps and reorder Herd to the right until it's permantently visible.

**Comment by zc632995195** [comment]
+1, I just download it, can see it in activity monitor, tried reboot + close other windows, but Herd somehow still cannot be opened as an app (no window)

**Comment by hironate** [comment]
@zc632995195 did you manage to get it worked? i am finding same issue. In activity monitor it shows, i have killed process multiple times, uninstalled and installed again. Still not working.

**Comment by sschlein** [comment]
Would you share a screenshot of your menu bar? The Herd icon is likely hidden.

You can also confirm that by checking if there are php, nginx and dnsmasq processes on your system.

**Comment by zc632995195** [comment]
I later figure it out... The app itself will not open an app like other apps, all it does is have the popup showing up on top-right corner. Then I need to click on it (and `sites` to view my doc..) 


<img width="227" alt="Screenshot 2024-09-10 at 9 39 31 AM" src="https://github.com/user-attachments/assets/b2ce8cc1-5f02-4035-b654-36e096b06f83">

**Comment by sschlein** [comment]
We plan to release the next Herd version later this week and launch massively improved docs and a better onboarding process for that. I hope that helps new users!

**Comment by FrenchMajesty** [comment]
I personally don't care for software docs, but easier-to-use software
that doesn't require docs. It would actually be100x better if you guys
simply launched a new software update that says:
" If user clicks on the Herd application from the Applications folder, open
the GUI"

This would go a LONG way to have an intuitive UX. Currently when I do that,
it simply launches Herd, but adds it to the tollbar (which is sometimes
hidden depending on user context). At best I have to do 2 extra clicks to
get to the GUI or at worst I end up on Google trying to figure out why I
can't open Herd...

I hope this is something we can see soon in the future

**Comment by sschlein** [comment]
The Herd icon in the menu bar is a required item, it's the only way to access many features and so there's no way around that.

I agree that it's useful to at least show an info that Herd is already running and how to access it if you're starting the app a 2nd time.

**Comment by SusanthCom** [comment]
<img width="641" height="180" alt="Image" src="https://github.com/user-attachments/assets/54eb3a48-6e16-4957-93a4-3c5d6f907c67" />

**Comment by SusanthCom** [comment]
I had same issue. Solved. The problem was that too many icons on menu bar.

**Comment by SusanthCom** [comment]
Best solution is to provide visibility in task tray/icon optionally or by default. Or the system must be able to detect the visibility of menu bar icons and provide alternative. In mac with camera notch gap, the menu bar space is limited. 

Another solution is to provide visibility in app switcher list. 

Current behaviour makes the first impression bad for some users. Many don't report or seek help. They just blame the Herd. 

Good ui design must consider all environments and less friction. Especially in getting started stage.

**Comment by marcin-sokalski** [comment]
What do you mean by "too many icons on menu bar"? I have as many icons as I need. It's a user's decision to have those icons. The developer's job is to make the program's window open when every user expects it to open. I'd uninstalled this application twice before I found this thread in the depths of the Internet. This is probably the single most peculiar UX idea I've ever heard of. What do you mean by "there's no way around that"? Well, find the way.
