### ISSUE TITLE
[Bug]:  Dumps are intercepting but also showing in the browser

### ISSUE THREAD

**Issue by AlexVanSteenhoven** [beyondcode/herd-community#729]
### Platform

Windows

### Operating system version

Windows 11 version 23H2 (OS Build 22631.3527)

### System architecture

Windows

### Herd Version

1.1.0

### PHP Version

PHP 8.3.7 (cli) (built: May  8 2024 08:56:34) (NTS Visual C++ 2019 x64)

### Bug description

According to the documentation, the dumps should only be seen in the dumps of Laravel Herd. But the dumps are actually also shown in the browser. Is there a solution for this or will this be a fix for the next release?

**What the docs specifies**
> Herd Pro can automatically intercept all dump() calls in your code and display them in a separate window instead of rendering them in the browser or CLI.

**Screenshots**
![image](https://github.com/beyondcode/herd-community/assets/67007082/c3d0eaa0-c276-435d-ae71-de19b0aa6f4a)

![image](https://github.com/beyondcode/herd-community/assets/67007082/b6671226-0874-4a87-8d60-b82f12d9cbee)

![image](https://github.com/beyondcode/herd-community/assets/67007082/00d0dd78-c6d0-4fff-a41e-d2a0f7649d0c)

### Steps to reproduce

1. Make sure that Herd is intercepting the dumps
2. Inside a (new) project add a `dump()` or `dd()` somewhere in your application and intercept this with Herd.
3. A message will popup inside Herd but also shown in the browser.

**Comment by mpociot** [comment]
Do you also see `dump` statements in the browser?
We show `dd()` in the browser as well, as it was a bit confusing to see just a blank website.

So `dd` is visible in the browser and the app.
`dump` is only visible in the app.

**Comment by AlexVanSteenhoven** [comment]
Ah okay, that makes more sense to me. 
Thanks than I will close this. And I see I did not read it correctly. I taught `dd` was also not showing on the page.

My bad 😅
