### ISSUE TITLE
[Bug]: DNSMasq stopped. the log message: "failed to create listening socket for 127.0.0.1 address already in use"

### ISSUE THREAD

**Issue by WatheqAlshowaiter** [beyondcode/herd-community#73]
### Operating system version

macOS Montery v12.5.1

### System architecture

Intel (x86)

### Herd Version

1.0.8

### Bug description

  DNSMasq is not working..  the expecting behavior is to work and it was working fine before.

![Screen Shot 2023-07-31 at 09 21 31](https://github.com/beyondcode/herd-community/assets/24838274/a4a719f3-78a3-4936-96a3-eb165d5b8328)
![Screen Shot 2023-07-31 at 09 21 23](https://github.com/beyondcode/herd-community/assets/24838274/79cae091-fb9f-41ca-a3c7-5a6f7531f702)

### Steps to reproduce

I have just download the app and stopped valet.. I have not changed a lot.

### Relevant log output

```shell
"failed to create listening socket for 127.0.0.1 address already in use"
```

**Comment by mpociot** [comment]
Hi!
Sometimes DNSmasq seems to not stop properly when Valet gets stopped. 

Please stop it manually:

sudo brew services stop dnsmasq 

This should fix it 👍
