### ISSUE TITLE
[Bug]: PHP Not Installed via Herd

### ISSUE THREAD

**Issue by Ssionn** [beyondcode/herd-community#732]
### Platform

macOS

### Operating system version

macOS Sonoma 14.4.1 (23E224)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.6.1 (Build: 25)

### Bug description

I have this issue where I've installed php with herd, but herd is not finding the executable.

![CleanShot 2024-05-14 at 09 40 12@2x](https://github.com/beyondcode/herd-community/assets/90753599/51958d51-d1be-44d4-9eb2-58b53971bf6f)

My directory:

![CleanShot 2024-05-14 at 09 43 33@2x](https://github.com/beyondcode/herd-community/assets/90753599/e9db90b7-c8b2-499d-b4aa-747b0066916e)

### Steps to reproduce

- Install Herd
- Install PHP using Herd
- Run ```herd php```

Error pops up.

**Comment by mpociot** [comment]
What do you get when you just run `php` and `which php`?

**Comment by Ssionn** [comment]
> What do you get when you just run `php` and `which php`?

Well, I don't have PHP installed on my machine, I use it through Herd. This used to work fine before.

![CleanShot 2024-05-14 at 09 46 54@2x](https://github.com/beyondcode/herd-community/assets/90753599/46e182eb-7a5d-47ac-9b9b-9ca78ebaedac)

**Comment by Ssionn** [comment]
Another note:

It seems it hasn't loaded any of my projects

![CleanShot 2024-05-14 at 09 48 05@2x](https://github.com/beyondcode/herd-community/assets/90753599/8ec14eac-3e20-4827-9b83-1defc9761bbd)

**Comment by mpociot** [comment]
It looks like you don't have a `php` symlink - which should point to the currently used version.
Can you try and run `herd use 8.3` (or whatever version you want to set as a default)?

This should create the symlink. You could also just select a PHP version in the menubar dropdown like this:

<img width="259" alt="image" src="https://github.com/beyondcode/herd-community/assets/804684/0b649442-11d7-46d9-a659-3ae69bcd02c9">

**Comment by Ssionn** [comment]
I've selected a version (even though it showed as one already selected) and it seems to go stuck on the command now
![CleanShot 2024-05-14 at 09 54 25@2x](https://github.com/beyondcode/herd-community/assets/90753599/4de0292a-6df5-440d-a111-55bffe9326d3)

**Comment by mpociot** [comment]
Do you now have a `php` symlink?
`php -v` and `which php` should now work

**Comment by Ssionn** [comment]
Yes.

![CleanShot 2024-05-14 at 10 01 32@2x](https://github.com/beyondcode/herd-community/assets/90753599/2f09d3bc-a0e9-4352-983a-188afa0847ff)

**Comment by mpociot** [comment]
Okay cool - then everything should be working.
`herd php` "hangs" as you are just starting the PHP interpreter without any additional arguments.

If you run `herd php -v` it'll work (or any other argument).

**Comment by Ssionn** [comment]
Gotcha, it seems to be working now, thanks for the help. I'm closing this issue. 😛

**Comment by mpociot** [comment]
Awesome - just out of interest, did you migrate from Valet when you ran into this?

**Comment by Ssionn** [comment]
I used to use valet a while back, since then I've just deleted it as a whole and installed herd (which in hindsight was a bad idea haha). It had some "issues" but haven't experienced it since. Also when dumping it's showing as a blank canvas. Don't know if this is a bug or not but it's a whole different issue.
