### ISSUE TITLE
[Bug]: Changing Max File Size via UI sometimes breaks

### ISSUE THREAD

**Issue by pxlrbt** [beyondcode/herd-community#735]
### Platform

macOS

### Operating system version

macOS Sonoma 14.4.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.6.1 Build 25

### PHP Version

PHP 8.3

### Bug description

When I change the "Max Upload File Size" value via the UI it works the first time, but after changing the value one or multiple times, I can't change any config until I restart my Mac.

- Can't change via UI
- Can't change via `php.ini`

- `herd restart` doesn't work
- Stopping and starting services via UI doesn't work
- Closing Herd app and starting doesn't work

Only a restart fixes it.

### Steps to reproduce

1) Go to Settings and change `Max Upload File Size"`
2) Check the file size via `dd(ini_get('max_upload_filesize'))`
3) Change it again
4) Maybe repeat 3 multiple times
5) See that nothing changes

**Comment by mpociot** [comment]
There seems to be a race condition that occurs when changing the value while the FPM service is currently restarting.
In this case, you can still "force stop" all services via the UI and then start them again:

![CleanShot 2024-05-14 at 14 18 11](https://github.com/beyondcode/herd-community/assets/804684/569ddf9b-a065-4c37-bab9-ace799b8d423)

The "Force stop all" option appears when you press the option key while the menubar is visible.

**Comment by pxlrbt** [comment]
"Force stop all" seems to fix this. Forgot about that option. Thanks.
