### ISSUE TITLE
[Bug]: php artisan serve is not working after the PHP 8.3.7 update

### ISSUE THREAD

**Issue by to-sanchez** [beyondcode/herd-community#737]
### Platform

Windows

### Operating system version

Windows 10 (22H2 19045.4046)

### System architecture

Intel (x86)

### Herd Version

1.6.1

### PHP Version

PHP 8.3.7

### Bug description

When I updated PHP to version 8.3.7 and then tried to run the command `php artisan serve`, I get the following error:
Failed to listen on 127.0.0.1:8000 (reason: ?).
Failed to listen on 127.0.0.1:8001 (reason: ?).
Failed to listen on 127.0.0.1:8002 (reason: ?).
Failed to listen on 127.0.0.1:8004 (reason: ?).

**Comment by mpociot** [comment]
Could you check in the task manager if you still have php processes running?

**Comment by to-sanchez** [comment]
> Could you check in the task manager if you still have php processes running?

I think so because all the other PHP commands work, and when I run the command `php -S localhost:8000 -t public`, it also works.

**Comment by EMeDesign** [comment]
> > Could you check in the task manager if you still have php processes running?
> 
> I think so because all the other PHP commands work, and when I run the command `php -S localhost:8000 -t public`, it also works.

Hi, I also encountered this problem.
I try to modify the php.ini of php83, then it works again.

before:
`variables_order = "EGPCS"`

after:
`variables_order = "GPCS"`

**Comment by kerrtt16** [comment]
same bro i tried all what they said but it does not work we might as well wait for the update to fix the bug... if your project is still on production for now use this command "php -S 127.0.0.1:8000 -t public/"

**Comment by mpociot** [comment]
Did you try the variable order in the php.ini as well?
Also: why are you using php artisan serve instead of nginx?

**Comment by davideprevosto** [comment]
@mpociot on my case I am using artisan serve instead of nginx to reach our mobile network. Is it not the right approach?

**Comment by spitfire64** [comment]
I can open tinker from Herd but not from CLI.
my php.ini has `variables_order = "GPCS"`. I 'm on PHP 8.3

**Comment by to-sanchez** [comment]
> > > Could you check in the task manager if you still have php processes running?
> > 
> > 
> > I think so because all the other PHP commands work, and when I run the command `php -S localhost:8000 -t public`, it also works.
> 
> Hi, I also encountered this problem. I try to modify the php.ini of php83, then it works again.
> 
> before: `variables_order = "EGPCS"`
> 
> after: `variables_order = "GPCS"`
> 
> Hope it will help you.

Is working with taht. Thank's

**Comment by to-sanchez** [comment]
@mpociot 
> Did you try the variable order in the php.ini as well? Also: why are you using php artisan serve instead of nginx?

I need it for something.

**Comment by RehamTammam1** [comment]
@mpociot #810 is solved using herd link,Thanks
