### ISSUE TITLE
[Bug]:  HerdHelper Port won't start when opening Herd, but does start when changing port

### ISSUE THREAD

**Issue by matthiasclaessen** [beyondcode/herd-community#738]
### Platform

Windows

### Operating system version

Windows 10 (10.0.19045 Build 19045)

### System architecture

Intel (x86)

### Herd Version

1.6.1

### Bug description

When opening Herd, the HerdHelper Port does not start, however it does start when changing the port. The status indicator remains red, but when changing the port, switching to another tab and then switching back to 'General', the status indicator is green.

**Comment by sschlein** [comment]
Hey, can you please try this debug version?

[Download](https://herd-dev.fra1.digitaloceanspaces.com/test-builds/Herd-1.6.1-setup_preview.zip)

* Install debug version
* Go to General settings and enable the HerdHelper debug mode
* Restart Herd
* Check the logs (linked at the general settings, click on the path to get there)
* Also check the logs at %USERPROFILE%\AppData\Roaming\Herd\logs

You can either post the logs here or send them to support@beyondco.de (and please mention this issue #674

**Comment by sschlein** [comment]
Hey folks, can you please try this NEW debug version?

This one should heal itself it the port is already in use.

[Download](https://herd-dev.fra1.digitaloceanspaces.com/test-builds/Herd-1.6.1-latest.exe.zip)

* Install debug version
* Restart Herd
* Also check the logs at %USERPROFILE%\AppData\Roaming\Herd\logs

You can either post the logs here or send them to [support@beyondco.de](mailto:support@beyondco.de) (and please mention this issue https://github.com/beyondcode/herd-community/issues/769

**Comment by matthiasclaessen** [comment]
Hi Sebastian,

I've placed the log file below. When checking or unchecking the 'Enable HerdHelper Logs' checkbox, a PowerShell screen pops up and afterwards the port light turns green. However, when starting Herd the light still remains red and the HerdHelper port does not start.

[main.log](https://github.com/user-attachments/files/15532968/main.log)

**Comment by sschlein** [comment]
Can you please also send the herdhelper log? You find ich when you click on the path in the general settings.

**Comment by matthiasclaessen** [comment]
Hi Sebastian,

Below the HerdHelper log.

[herdhelper20240603.txt](https://github.com/user-attachments/files/15546570/herdhelper20240603.txt)

**Comment by sschlein** [comment]
If you install Herd, it should prompt you for admin rights and the Helper should run as admin, so why could access to the file be denied? If you open the information for the file, are there any hints about access rights for the hosts file?

Can you manually edit it and add something like

```
127.0.0.1 herd.test
```

There and then access http://herd.test in your browser (should give a 404)

**Comment by matthiasclaessen** [comment]
It did indeed prompt me for admin rights, so I'm a bit confused too as why it's denied access to the hosts file.

I just added the 'herd.test' and did indeed get a 404 with the Herd layout.

I did however have to open Notepad with admin rights and then open the hosts file. Without admin rights it wouldn't work.

**Comment by sschlein** [comment]
Do these settings look identical to yours? Could the hosts file be already opened by another application or is there some scanner/anti virus software or firewall that would prevent the hosts file from being opened?

![CleanShot 2024-06-04 at 13 11 54](https://github.com/beyondcode/herd-community/assets/2911113/66a34805-fcfc-44b8-b839-f92c36086e56)

**Comment by matthiasclaessen** [comment]
I just checked, and my settings look identical to these. As far as I know, there's no other application that has the hosts file opened and I also turned off my anti virus temporarily for testing. So no interference from there either.

I just restarted Herd, and the HerdHelper log show the same message again concerning the hosts file. However when changing the port, I have an admin right request pop up for PowerShell and the HerdHelper port is running, so for some reason Herd isn't running with admin rights when started.

**Comment by sschlein** [comment]
Herd itself doesn't run as admin on purpose but the HerdHelper does. Herd basically tells the Helper which sites it wants to write to the Helper and the Helper writes to the hosts file. 

I am pretty confused why the Helper runs as local system (therefore it should have access rights) but can't access the file.

**Comment by sschlein** [comment]
So my last idea is to gather even more logs with this HerdHelper: [Download](https://herd-dev.fra1.digitaloceanspaces.com/test-builds/HerdHelper_permission_logs.zip)

Can you please download this and replace your current HerdHelper?

Steps:

1. Open powershell as admin:

```

sc.exe stop HerdHelper
```

2. Replace the HerdHelper.exe at `%USERPROFILE%\.config\herd\bin`
3. 
```

sc.exe start HerdHelper
```

This should write even more debug logs and display the permissions of the hosts file as well as the permissions of the user/system that runs the helper

**Comment by matthiasclaessen** [comment]
Applied these steps and the log does show more output. Here it is:

[herdhelper20240604.txt](https://github.com/user-attachments/files/15551455/herdhelper20240604.txt)

My OS language is set to Dutch, so some entries contains Dutch text. Apologies for this.

**Comment by matthiasclaessen** [comment]
Awesome, I unchecked the 'Deny' option on the hosts file, and now it's working!

I'm still curious as to why this was checked. Do you happen to know if this is this something that's done by default in Windows?

> As the HerdHelper has FullAccess, I could also do that automatically 🤔

What exactly do you mean by this?

**Comment by sschlein** [comment]
That's definitely not a default, I think I have read somewhere that some anti-malware tools set this option to the file as extra protection, because a malware could do something like mapping your-bank.com to their IP via the hosts file.

I just added a function to a new version of the HerdHelper that checks the access rights and sets them properly, writes to the file and then restores whatever there has been before. If you want to try this as well, you can do that with this one [Download](https://herd-dev.fra1.digitaloceanspaces.com/test-builds/HerdHelper_permission_changer.zip)

This version will likely end up in one of the next updates so that Herd can handle more of these problems itself.

Thanks a lot for your help on pinning this down. If you're good, we can close this issue! :)

**Comment by matthiasclaessen** [comment]
I did have an antivirus installed for some time, so that might have caused it.

Can I keep using the debug version provided earlier here or just revert to the latest version of Herd and replace the HerdHelper.exe with the one you have provided here in your latest post?

Many thanks for helping me solve this issue!

**Comment by sschlein** [comment]
Yeah, please keep the debug version! I am not even sure it can be easily reverted because it features the new dump feature with grouped dumps that we're going to release next week and some other updates.

Please make sure to disable logging for the herdhelper, otherwise it'll create tons of useless logs.

**Comment by matthiasclaessen** [comment]
Great, will do, and thanks again!

**Comment by matthiasclaessen** [comment]
Reopening this due to the same issue mentioned in previous comments.

When starting Herd, the HerdHelper once again fails to access the hosts file due to access being denied, even though the permissions on the file are set to 'FullControl'.

However, when changing the port, the HerdHelper status turns green.

**Herd Version**
1.8.0

**Comment by sschlein** [comment]
Argh. The helper not being green and the helper not being able to write to the file are two different issues, so I want to double check on them:

1) The helper status was red, then you changed the port and it turned green, but it still can't write to the hosts file?

2) When it can't write to the hosts file, you enabled the logs and got a permission error?

Thanks

**Comment by matthiasclaessen** [comment]
Correct, when adding a path to the list, the helper turns red again and looking at the logs, the access to the hosts files once again is denied, despite having 'FullControl' access rights.

I have the logs enabled by default just in case, and when looking at them, it did show the permission error, yes. Even with the logs disabled, the same issue occurs.

**Comment by sschlein** [comment]
@matthiasclaessen Could you please share the full HerdHelper log with the permissions and also make a screenshot of the permissions of the hosts file like these ones?
![CleanShot 2024-07-02 at 13 53 06](https://github.com/beyondcode/herd-community/assets/2911113/f6bb07d9-5f05-482e-8a48-ee36a239e08e)
![CleanShot 2024-07-02 at 13 53 44](https://github.com/beyondcode/herd-community/assets/2911113/acd7d015-3fa3-4396-be6a-64ac79514034)

If you don't want to share this information here, you can email them to support@beyondco.de.

I am still wondering what is going on there – the helper currently checks for read-only and fixes that but would not add access rights with groups or so.

**Comment by matthiasclaessen** [comment]
Hi Sebastian,

Below you can find the HerdHelper log. I've also emailed screenshots of my hosts file to the provided address.

[herdhelper20240702.txt](https://github.com/user-attachments/files/16069875/herdhelper20240702.txt)

**Comment by sschlein** [comment]
Fixed it, it was anti-virus software by Kaspersky that locked the file
