### ISSUE TITLE
[Bug]: HerdHelper dosnt start

### ISSUE THREAD

**Issue by seiff-khalifa** [beyondcode/herd-community#741]
### Platform

Windows

### Operating system version

Windows 11 223H2 22631.3527

### System architecture

Windows

### Herd Version

1.6,1

### PHP Version

8.3

### Bug description

HerdHelper dosnt start even when i change ports.
tried the following:
- sc.exe query HerdHelper
- sc.exe start HerdHelper

and here is the result
![image](https://github.com/beyondcode/herd-community/assets/96682828/592ebfbd-c293-4ce5-8e2b-56b37ff5a9df)

**Comment by KeithPrinkey-ops** [comment]
I too got an error regarding the Herd Helper. 
![image](https://github.com/beyondcode/herd-community/assets/68619799/96f8f38c-fade-471f-8eee-a5f12b23de9d)

**Comment by KeithPrinkey-ops** [comment]
UPDATE: I got HerdHelper Service started by killing all httpd instances on my Windows 11 Pro Laptop. 

Steps Taken: 

Finding the currently open ports: netstat 5000
Killing the processes: I personally opened task manager and stopped apache2, nginx, and mysql from the laragon installation which I have since removed and have had 0 issues with Herd moving forward.

**Comment by sschlein** [comment]
Hey folks, if there are still issues, can you please try this debug version?

[Download](https://herd-dev.fra1.digitaloceanspaces.com/test-builds/Herd-1.6.1-setup_preview.zip)

* Install debug version
* Go to General settings and enable the HerdHelper debug mode
* Restart Herd
* Check the logs (linked at the general settings, click on the path to get there)
* Also check the logs at %USERPROFILE%\AppData\Roaming\Herd\logs

You can either post the logs here or send them to support@beyondco.de (and please mention this issue #741

Please close the issue here if eversthing is already resolved!

**Comment by seiff-khalifa** [comment]
Heres the log file found in %USERPROFILE%\AppData\Roaming\Herd\logs:
[Uploading main.log…]()

**Comment by seiff-khalifa** [comment]
[main.log](https://github.com/user-attachments/files/15506476/main.log)

**Comment by seiff-khalifa** [comment]
[herdhelper20240328.txt](https://github.com/user-attachments/files/15513300/herdhelper20240328.txt)
[herdhelper20240329.txt](https://github.com/user-attachments/files/15513301/herdhelper20240329.txt)
[herdhelper20240330.txt](https://github.com/user-attachments/files/15513302/herdhelper20240330.txt)
[herdhelper20240331.txt](https://github.com/user-attachments/files/15513303/herdhelper20240331.txt)
These are the only logs when i click on the path

**Comment by sschlein** [comment]
Did you enable the debug mode in the general settings and then restarted Herd? If yes, how does your services.json in C:\ProgramData\Herd look like?

**Comment by seiff-khalifa** [comment]
[service.json](https://github.com/user-attachments/files/15513404/service.json)

**Comment by sschlein** [comment]
Any chance to get an answer to the first question? There's no log but the settings are correct, so the HerdHelper wasn't started with the debug mode of the latest version.

**Comment by seiff-khalifa** [comment]
yes i did enable the debug mode and quit the app and opened it again also heres a screenshot of the settings
![Screenshot 2024-05-31 151955](https://github.com/beyondcode/herd-community/assets/96682828/9154db68-808c-49f6-8f63-385df9dd4c19)

**Comment by sschlein** [comment]
Can you please check the HerdHelper in your Windows Services list? It should be running, it looks like it's not. You can force a restart by restarting your PC or changing the port and confirming this.

Is your hosts file locked or writable?

**Comment by seiff-khalifa** [comment]
so herdhelper does exist in my windows services list but its not running and when i click start service i get th error in the screenshot and my hostfile read only property isnt checked as shown
![Screenshot 2024-05-31 152856](https://github.com/beyondcode/herd-community/assets/96682828/999d8c96-29f7-4529-8fbf-193b5a707890)
![Screenshot 2024-05-31 152735](https://github.com/beyondcode/herd-community/assets/96682828/4c58f822-78fe-4271-b46a-850315d6712a)

**Comment by sschlein** [comment]
Hey folks, can you please try this NEW debug version?

This one should heal itself it the port is already in use, fix not existing hosts files, write to read-only hosts files and only use IPv6 in cases that this is properly configured on the host machine.

[Download](https://herd-dev.fra1.digitaloceanspaces.com/test-builds/Herd-1.6.1-latest.exe.zip)

* Install debug version
* Restart Herd
* Also check the logs at %USERPROFILE%\AppData\Roaming\Herd\logs

You can either post the logs here or send them to [support@beyondco.de](mailto:support@beyondco.de)

THanks for helping us with debugging.

**Comment by sschlein** [comment]
@seiff-khalifa 
Are there any logs at `%USERPROFILE%\AppData\Roaming\Herd\logs`or `C:\Windows\System32\logs` like I asked in my previous message?

**Comment by seiff-khalifa** [comment]
well i have those in my %USERPROFILE%\AppData\Roaming\Herd\logs
[main.log](https://github.com/user-attachments/files/15538763/main.log)
[main.old.log](https://github.com/user-attachments/files/15538764/main.old.log)

**Comment by sschlein** [comment]
So after I have asked about the HerdHelper logs multiple times and you haven't sent one, I assume there is none. It would be great to have a confirmation on that.

Is there a HerdHelper.exe in `%USERPROFILE%\.config\herd\bin`?

Please answer both questions

**Comment by seiff-khalifa** [comment]
Yes theres a herdhelper.exe in %USERPROFILE%\.config\herd\bin, as for the herdhelper logs...i did provide them before and they're still the same, and here they are once again:
[herdhelper20240329.txt](https://github.com/user-attachments/files/15544089/herdhelper20240329.txt)
[herdhelper20240330.txt](https://github.com/user-attachments/files/15544090/herdhelper20240330.txt)
[herdhelper20240331.txt](https://github.com/user-attachments/files/15544091/herdhelper20240331.txt)
[herdhelper20240328.txt](https://github.com/user-attachments/files/15544093/herdhelper20240328.txt)

**Comment by sschlein** [comment]
These logs are from March as you can see from the date in the filename, so your system doesn't even start the helper enough to write new ones.

Can you please open powershell as administrator and perform these commands to remove and install the Herdhelper again?

```
sc.exe stop HerdHelper
sc.exe delete HerdHelper
sc.exe create HerdHelper binPath="ABSOLUTE PATH TO Herdhelper.exe"
sc.exe start HerdHelper
sc.exe query HerdHelper
```

It would be great to get all the terminal output from all these commands.

One thing that I notice from your logs is that Herd seems to be at `C:\Program Files\Herd` but it should be at `%USERPROFILE%\AppData\Roaming\Herd` and I wonder why it's in Program Files.

**Comment by seiff-khalifa** [comment]
HYG
![image](https://github.com/beyondcode/herd-community/assets/96682828/19b12c94-49a5-4ae6-b223-e231d1e53107)

**Comment by sschlein** [comment]
what happens if you do that again but use the absolute path to the herdhelper.exe instead of just copy and pasting this line?

**Comment by seiff-khalifa** [comment]
lol sorry for that 
![image](https://github.com/beyondcode/herd-community/assets/96682828/6bffecdb-fe49-469a-ab32-18644a04f616)

**Comment by sschlein** [comment]
Does it work when using this?

```
sc.exe create HerdHelper binPath= "\"C:\Users\ALIENWARE M15 R3\.config\herd\bin\HerdHelper.exe\""
```

You can also try adding the exe to your path, currently it's only the path, not the exe file

**Comment by seiff-khalifa** [comment]
yepp same error (193)
![image](https://github.com/beyondcode/herd-community/assets/96682828/b609279d-ef35-49a1-ac71-adceecee6732)

**Comment by seiff-khalifa** [comment]
it worked! what a simple solution...thank you for your effort:)
