### ISSUE TITLE
[Bug]: Php not found when trying php -v from the git bash

### ISSUE THREAD

**Issue by AtiqurCode** [beyondcode/herd-community#744]
### Platform

Windows

### Operating system version

Windows 11

### System architecture

Intel (x86)

### Herd Version

1.6.1

### PHP Version

8.1, 8.2, 8.3

### Bug description

When I try any php command from the git bash it shows
![Screenshot 2024-05-16 220007](https://github.com/beyondcode/herd-community/assets/87328186/a933dde8-ec60-4067-bdb8-18af34404a99)
 not found.

### Steps to reproduce

1. Install the Laravel herd on a Windows machine.
2. Then install git bash
3. Then try any PHP command

### Relevant log output

```shell
$ php -v
bash: php: command not found
```

**Comment by AtiqurCode** [comment]
This can be a system environment variables setup issue. But I'm not sure why it's happened.

Note that I am not getting the same issue when I try from the Terminal / Powershes
![Uploading Screenshot 2024-05-16 220400.png…]()

**Comment by mpociot** [comment]
You might need to add these aliases to your .bash_profile file

See https://herd.laravel.com/docs/windows/1/advanced-usage/command-line#git-bash

**Comment by AtiqurCode** [comment]
@mpociot oh yeah. It's awsome it's working now.
Thanks, Dear
Awesome tool from you guys

**Step to solve**

- Add a ~/.bash_profilefile in ~/Users/{acount-name}/ || ~/.bash_profilenot available in my directory

- Paste all these lines

```
alias php="php.bat"
alias herd="herd.bat"
alias laravel="laravel.bat"
alias composer="composer.bat"
```

- close the git bash
- Open again and tried php -v
![Screenshot 2024-05-16 221934](https://github.com/beyondcode/herd-community/assets/87328186/b5db6415-8ac6-40fa-921f-0fcfb8716a99)

**Comment by amiralidev** [comment]
Navigate to the bin path of the "herd" folder within Application Support. Then, use the ls -la command to identify which version of PHP is linked to the "php" file.

If that version of PHP is missing, install it. This should resolve the issue I encountered where PHP was missing after installation.

**Comment by Mohamed-G2021** [comment]
> You might need to add these aliases to your .bash_profile file
> 
> See https://herd.laravel.com/docs/windows/1/advanced-usage/command-line#git-bash

that's very helpful
worked for me
