### ISSUE TITLE
[Bug]: Herd window closes immediately on launch

### ISSUE THREAD

**Issue by uberbrady** [beyondcode/herd-community#746]
### Platform

macOS

### Operating system version

MacOS Sonoma 14.5

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.6.1

### Bug description

I downloaded the app and copied to the Applications folder. I launched it to see if it was working, and got to the window where it said it wanted to stop valet. I got a little nervous - I mean, the text _tells_ you that you can start it right back up again; so it would've been _fine_ - but I got nervous, so I quit the app.

Then, I got ready to run it for real. So I launch the app again, it bounces once in the task bar - then poof. Disappears. I did eventually check activity monitor, and there is a little 22MB Herd app running. I've quit that, and re-launched regular Herd.app to no avail. When I did quit the little Herd thing from Activity Monitor and relaunched, the little Herd thing showed back up in the activity monitor. But the dock icon bounces one and then disappears.

I still have quite a few tricks up my sleeve - probably going to try to uninstall using these docs: https://herd.laravel.com/docs/1/troubleshooting/uninstalling , then try again. I'll update here with what does work and what doesn't work.

### Steps to reproduce

On a fresh machine, which is already running valet, launch Herd after copying into /Applications. Quit out right on the screen where it says it wants to stop Valet. Re-launch the app.

**Comment by uberbrady** [comment]
I wasn't sure, to be honest. It might've been hidden under the notch, I have a lot of stuff up there. My uninstall/reinstall seemed to do the trick - if there was a trick to be done. I quit out of PHPMonitor and now the 'H' is there - but, again, it could've been under the notch or somewhere else where I didn't see it.

**Comment by sschlein** [comment]
The next version will start with the dashboard open and not only disappear into the menubar. The menu bar item is still the way to open and manage it after the dashboard/settings were closed.

**Comment by Solomon04** [comment]
what was the solution to this? A dev on our team is currently experiencing this issue.

**Comment by sschlein** [comment]
Hi @Solomon04 what happens if you open Herd a 2nd time or click on the system tray icon?

**Comment by arn314** [comment]
I just installed Herd and I'm facing this issue. I don't see any system tray icon after opening Herd.

**Comment by sschlein** [comment]
Are you sure it's not running in your menu bar?

**Comment by arn314** [comment]
Damn. I got stung by this notch hiding icons [issue](https://www.jessesquires.com/blog/2023/12/16/macbook-notch-and-menu-bar-fixes/). After quitting a few programs, I can see Herd visible on the menu bar.

After installation, I was able to see Herd window open but then it immediately auto-closed. Was that not fixed? My version is 1.9.1 (build 31).
