### ISSUE TITLE
[Bug]: I cant access URL that created by HERD (This site can’t be reached) DNS_PROBE_FINISHED_BAD_CONFIG

### ISSUE THREAD

**Issue by goldypasulu** [beyondcode/herd-community#748]
### Platform

macOS

### Operating system version

macOS Sonoma (14.4.1)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.6.1 (Build 25)

### PHP Version

PHP 8.3.7

### Issue Report

After multiple installations of Herd on my Macbook M1, I still cannot use the URL created by Herd, which is http://"directory-name".test.

You can see this in the image below:
![image](https://github.com/beyondcode/herd-community/assets/85629724/d00e73f5-5fdf-49f7-a95f-232427c76f55)

The image above shows that Herd has created URLs for several of my projects. However, when I try to access them, I receive a message stating that the URL cannot be accessed. I have tried various browsers but still cannot access the URLs.
![image](https://github.com/beyondcode/herd-community/assets/85629724/4130caa6-d014-4b05-88aa-1ce27ddca90a)

The image below shows the browser display when it fails to access the URL:
![image](https://github.com/beyondcode/herd-community/assets/85629724/9be8e222-b20d-41bc-bdae-b5ac15b2b129)

I tried to find a solution and came across this issue: https://github.com/beyondcode/herd-community/issues/175. They found a solution by resetting the DNS settings to default in the browser, but it still does not work for me.
![image](https://github.com/beyondcode/herd-community/assets/85629724/0f07563b-5aaa-401b-841a-6a6ed2b145b3)

I would appreciate any help, as I have tried various methods but am still having trouble fixing this issue.

Thank you.

**Comment by mpociot** [comment]
What do you get when you run `ping demo.test` in your terminal?
If that resolves to 127.0.0.1, can you try and run `curl http://demo.test` from you terminal?

**Comment by goldypasulu** [comment]
this is what I get
![image](https://github.com/beyondcode/herd-community/assets/85629724/544a9a3b-4db8-4fb3-b98b-21f6e8122e81)


> What do you get when you run `ping demo.test` in your terminal? If that resolves to 127.0.0.1, can you try and run `curl http://demo.test` from you terminal?

**Comment by mpociot** [comment]
You should have a file at `/etc/resolver/test` 
With this content:

```
nameserver 127.0.0.1
```

**Comment by goldypasulu** [comment]
> You should have a file at `/etc/resolver/test` With this content:
> 
> ```
> nameserver 127.0.0.1
> ```

thank you so much, it works

**Comment by andiyudi** [comment]
> You should have a file at `/etc/resolver/test` With this content:
> 
> ```
> nameserver 127.0.0.1
> ```

hello i want to ask where is the '/etc/resolver/test' location for herd.
thanks before

**Comment by GaniyuWi** [comment]
> I am also facing this issue. How can fixed on windows?

I'm also facing this issue on windows

**Comment by cpenk84** [comment]
On Windows
cd %USERPROFILE%\Herd\your-project
herd link
work for me

**Comment by rafiromadhon** [comment]
> On Windows cd %USERPROFILE%\Herd\your-project herd link work for me

can you show me the picture how to put it?
