### ISSUE TITLE
[Bug]: Bad Gatway on Herd upgrade from valet on a mac

### ISSUE THREAD

**Issue by theoreaves** [beyondcode/herd-community#752]
### Platform

macOS

### Operating system version

macOS 14.4.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.6.1

### Bug description

Putting Herd on a co-workers computer.  With a herd license assigned to them.

After upgrading to Herd from Valet, nginx and mail did not start.  did a "valet stop" then herd stop and start from the menu.  At this point, mail started, but not nginx.  saw that nginx processes were still running for valet.  So I killed them at the prompt.  then did a herd stop/start.  nginx now show as running in herd,  but when I go to my site, I get a 502/bad gateway error.

I've checked to make sure that php is symlinked, and herd.sock is symlinked.  Both are (to 8.2, which is what I want).  I looked int he Log folder, but php-fpm logs and nginx logs are all blank.

### Steps to reproduce

Fresh install of herd on a mac that already has valet on it.

**Comment by sschlein** [comment]
That's odd. Could you share your herd.conf and nginx.conf from your Herd config/nginx directory?

You can also run `brew services list` to see if there is still nginx from Valet trying to fight with nginx from Herd.

**Comment by theoreaves** [comment]
[herd.txt](https://github.com/beyondcode/herd-community/files/15405992/herd.txt)
[nginx.txt](https://github.com/beyondcode/herd-community/files/15405993/nginx.txt)

Here is what I see under brew list services:

Name    Status User File
dnsmasq none


Thanks!

**Comment by mpociot** [comment]
@theoreaves sorry for the long delay. Were you able to fix this in the meantime?
"Bad gateway" usually means that FPM is not properly running.
