### ISSUE TITLE
[Bug]: 301 redirect on missing image

### ISSUE THREAD

**Issue by iruzevic** [beyondcode/herd-community#759]
### Platform

macOS

### Operating system version

macOs Sonoma 14.2.1 (23C71)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.6.1 (Build: 25) Pro

### PHP Version

PHP 8.3+

### Bug description

When you load an asset in the code, such as an image that is missing from the path, Nginx will attempt to open the image and then get redirected to the home page URL, resulting in another request. This could be problematic if you have numerous images, as it may slow down your setup.

This is not how it works in regular setups. If you receive a missing path, it should return a 404 error instead of redirecting the request.

<img width="1018" alt="Screenshot 2024-05-22 at 15 19 34" src="https://github.com/beyondcode/herd-community/assets/23283324/17e7c477-ff33-4b5d-9af6-be75f69c4cb0">
<img width="1009" alt="Screenshot 2024-05-22 at 15 19 43" src="https://github.com/beyondcode/herd-community/assets/23283324/a232a125-af4a-4b0f-a9d8-55c5c0bbfa2a">
<img width="1008" alt="Screenshot 2024-05-22 at 15 19 49" src="https://github.com/beyondcode/herd-community/assets/23283324/50f02422-32bd-47d0-86c8-386cb8086ec0">

### Steps to reproduce

1. Create and image tag in HTML
2. Add some missing path to src
3. Open Inspector and see two requests, one for the image > 301 and one for the home page.an

**Comment by sschlein** [comment]
That seems to be a WordPress feature. If you try that on a different application or on the WP frontend, it just does a 404. If you add /wp-admin in the path, it redirects.

**Comment by iruzevic** [comment]
Yes, I can confirm that this issue occurs only on WordPress. I have tested it on Laravel 11, and it does not occur there. Can you suggest how I can resolve this issue?

**Comment by sschlein** [comment]
Not really, that's a WordPress issue that should also happen on all other dev environments. If it doesn't there must be a specific nginx config in place that behaves differently, but we don't redirect on a 404 in Herd, especially when it only happens in the admin area.

**Comment by iruzevic** [comment]
I fixed it by adding 

```nginx
    location ~* \.(?!php$|html$)[a-zA-Z0-9]+$ {
        try_files $uri = 404;
    }
```

to my projects nginx.config.

@sschlein, is there a way I can use this or any kind of configuration and add it to herd, and will it use that configuration when creating a new server configuration?

**Comment by sschlein** [comment]
No, that's currently not possible. It's great that you've been able to fix that but I am closing this issue for now as it's not in the *current* scope of Herd. This might change in the future but I don't see it on the short term roadmap 🙂
