### ISSUE TITLE
[Bug]: Encountered "Looks like there was an error setting up Herd." during installation on macOS 14.5 (M2).

### ISSUE THREAD

**Issue by pcapp** [beyondcode/herd-community#763]
### Platform

macOS

### Operating system version

macOS Sonoma 14.5

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.6.1 (25)

### Bug description

I encountered this screen when installing Herd 1.6.1, 1.6.0, and 1.5.0.

<img width="1000" alt="image" src="https://github.com/beyondcode/herd-community/assets/2206447/05b13fea-5365-4761-997c-b4e7c3cb3555">

This appears after entering my system password correctly.

I expect the installer to continue with the installation or provide information on the error so I can continue to debug the installation.

More likely than not, I expect this is something on my side, but I am not sure how to debug this further. Are there log files I can look at to gain more insight into what might be causing this?

### Steps to reproduce

* Download the DMG file.
* Drag the Herd icon to the Applications folder.
* Double-click the Herd icon from the Applications folder.
* Enter the password for the logged-in account, which is an admin account if that matters.
* Observe the error text in the center of the display.

**Comment by sschlein** [comment]
This might be a dumb question but are you 100% sure that the password is correct? I believe that's the only reason why you could see the error.

**Comment by pcapp** [comment]
That's a great question. I tried entering the wrong password on purpose, and the login prompt jiggled to indicate a failed login. After that, I entered the correct password, and the prompt closed. After that, I saw the 'Looks like there was an error...' message.

**Comment by pcapp** [comment]
Hi Sebastian, may I get a macOS build? The above build is a Windows build (which works great, by the way!). I should have more availability this coming week to provide any help more quickly.

**Comment by pcapp** [comment]
Here's a video showing what happens.

https://github.com/beyondcode/herd-community/assets/2206447/398134e0-59a4-43e1-8ead-8b9e0ce157fb

**Comment by sschlein** [comment]
Meh sorry, I was posting this debug build to some other issues and missed thed OS label.

Can you please try this version? [Download](https://herd-dev.fra1.digitaloceanspaces.com/test-builds/Herd_1.7.0.dmg). After moving it to your Applications directory from the DMG file, please start it with a debug flag:

```
open /Applications/Herd.app --args --enable-logfile
```

This flag enabled a `Herd_Debug.log` file in your application directory. Sometimes the file is only written when the app is closed, so please make sure to try this and then either uploading the log here or sending it to support@beyondco.de

This version is the upcoming preview that also includes a new feature and an underlying change so that the app doesn't need admin permissions for many things anymore but runs with a system helper.

**Comment by pcapp** [comment]
Here's what I did:

* Installed the provided .dmg file.
* Ran the above `open` command from iTerm.
* I went through the installer, which appears to have been completed.
* I did not see the Herd icon in the Menu Bar.
* ps aux | grep Herd showed three processes running.
<img width="1711" alt="Screenshot 2024-06-05 at 10 12 26 AM" src="https://github.com/beyondcode/herd-community/assets/2206447/364f4208-1f97-4f2a-bcd1-2764bd450926">
* I killed them with `sudo -s SIGTERM <pid1> <pid2> <pid3>
* I searched for Herd_Debug.log and found an empty file in my Documents folder.

**Comment by pcapp** [comment]
I solved the problem. I am not sure why, but the permission for the Herd.app is now peter:admin rather than root:admin, which is what it was previously. I know have 1.6.1 installed and have successfully created a site. I am not sure why this changed.

Shall I close this?

**Comment by sschlein** [comment]
1.7.0 runs as normal user but has a service that runs as admin for some tasks. 

But if everything is working now, you can close it 🙂

**Comment by stanleyyylau** [comment]
i run into the same issue, permission is correct. is there a way to fix? where to download the debug version?  @sschlein
