### ISSUE TITLE
[Bug]: Herd GUI not opening

### ISSUE THREAD

**Issue by nmsavaliya** [beyondcode/herd-community#769]
### Platform

Windows

### Operating system version

Windows 10

### System architecture

Windows

### Herd Version

1.6.1

### Bug description

I updated the herd version to 1.6.1 but GUI not getting open after upgrade

![image](https://github.com/beyondcode/herd-community/assets/8054426/42d4f27a-69d8-4f70-a4bd-74952c50584d)

when I try as above screenshot but its give some error about, is this reason GUI not opening?

**Comment by mpociot** [comment]
Do you have anything in your log file at `%USERPROFILE%\AppData\Roaming\Herd\logs`?

**Comment by nmsavaliya** [comment]
@mpociot 

below is latest logs which comes after I tried to open herd

![image](https://github.com/beyondcode/herd-community/assets/8054426/e224ef0f-c05d-4d07-94ae-279632e6af67)

**Comment by sschlein** [comment]
Hey folks, can you please try this debug version?

[Download](https://herd-dev.fra1.digitaloceanspaces.com/test-builds/Herd-1.6.1-setup_preview.zip)

* Install debug version
* Restart Herd
* Also check the logs at %USERPROFILE%\AppData\Roaming\Herd\logs

You can either post the logs here or send them to support@beyondco.de (and please mention this issue #769

**Comment by sschlein** [comment]
Hey folks, can you please try this NEW debug version?

[Download](https://herd-dev.fra1.digitaloceanspaces.com/test-builds/Herd-1.6.1-latest.exe.zip)

* Install debug version
* Restart Herd
* Also check the logs at %USERPROFILE%\AppData\Roaming\Herd\logs

You can either post the logs here or send them to [support@beyondco.de](mailto:support@beyondco.de) (and please mention this issue https://github.com/beyondcode/herd-community/issues/769

**Comment by nmsavaliya** [comment]
@sschlein 

![image](https://github.com/beyondcode/herd-community/assets/8054426/ca17c065-b846-42dd-bdaa-771c75fb512e)

I don't know if this might be helpful for you or not, before this "Read Only" option was checked, when I unchecked it and applied for all subdirectory, and opened it again then it worked as before properly

when I checked in the logs it was a permission issue

C:\Users\USERNAME\.config\herd

**Comment by sschlein** [comment]
Thanks – 1.7.2 should actually work with files that are read-only 🙂
