### ISSUE TITLE
[Bug]: PHP Artisan - PCRE JIT will be disabled.

### ISSUE THREAD

**Issue by alexfleites** [beyondcode/herd-community#77]
### Operating system version

macOS Ventura 13.4.1 (c)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.0.8 (Build 10)

### PHP Version

PHP 7.4

### Bug description

I updated PHP 7.4 today and now I am receiving this error when I ran php artisan.

![2021_05_12_214818_create_zip_codes_table php — arng-web-lara 2023-07-31 at 12 28 11 PM](https://github.com/beyondcode/herd-community/assets/962479/c2aeec9c-498c-4a2e-9c92-4d65c44903bc)

![🧨 Cannot modify header information - headers already sent by (output started at ApplicationsHerd appContentsResourcesvaletcliValetServer php78) 2023-07-31 at 12 30 00 PM](https://github.com/beyondcode/herd-community/assets/962479/039f120c-ea7c-4dcd-bd29-1ffcf37a8b86)

### Steps to reproduce

Update PHP 7.4 (7.4.33)
Run ph artisan

**Comment by mpociot** [comment]
Could you please update to the latest version of Herd as well (1.1.1)?

**Comment by alexfleites** [comment]
Same issue with this version
![2021_05_12_214818_create_zip_codes_table php — arng-web-lara 2023-07-31 at 12 38 39 PM](https://github.com/beyondcode/herd-community/assets/962479/eb32ec67-bdbc-4428-9acc-870388a33511)

**Comment by mpociot** [comment]
What does "php74 --ini" give you and what's the content of that file?

**Comment by alexfleites** [comment]
alexanderfleites % php74 --ini
Configuration File (php.ini) Path: /lib
Loaded Configuration File:         (none)
Scan for additional .ini files in: /Users/alexanderfleites/Library/Application Support/Herd/config/php/:/Users/alexanderfleites/Library/Application Support/Herd/config/php/:
Additional .ini files parsed:      (none)
alexanderfleites % 

curl.cainfo=/Users/alexanderfleites/Library/Application Support/Herd/config/php/cacert.pem
openssl.cafile=/Users/alexanderfleites/Library/Application Support/Herd/config/php/cacert.pem
pcre.jit=0

**Comment by mpociot** [comment]
It seems like PHP doesn't detect your ini

> Additional .ini files parsed: (none)

Could you copy your php.ini file from the 74 folder to the "php" folder and see if that fixes it?

**Comment by alexfleites** [comment]
like this? 
![image](https://github.com/beyondcode/herd-community/assets/962479/2eb9cf55-ae82-4e26-b218-ab283fb33520)

**Comment by mpociot** [comment]
Yeah

**Comment by mpociot** [comment]
You can specify the PHP version that specific sites should use in the "Sites" UI
<img width="901" alt="image" src="https://github.com/beyondcode/herd-community/assets/804684/a44843c4-ed5d-4604-bfbf-b3fcb82fe1ed">
