### ISSUE TITLE
[Bug]: unable to change Environment Variables of Reverb service ?

### ISSUE THREAD

**Issue by ValoXya** [beyondcode/herd-community#770]
### Platform

macOS

### Operating system version

macOS Sonoma

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.6.1

### PHP Version

PHP 8.2

### Bug description

Hello,
My previous message wasn't clear sorry, I'll try to keep it more consis.
What I've tried to explain is by default service Reverb inside Heard has it own variables to work doesnt it ?

In my case, my .env file to use reverb is different from the one provide in Heard. 

I would like to know if that's possible to customise thoses variables inside Heard because it doesn't seems to use the ones I've got inside .env file what ever I tried 

Thank you

### Steps to reproduce

Lauch Reverb from Services panel

**Comment by mpociot** [comment]
The Reverb service configuration / environment files can be found here: `/Users/shared/Herd/services/reverb`
Feel free to edit the .env file to suit your needs

**Comment by ValoXya** [comment]
Thank you @mpociot that's perfect
