### ISSUE TITLE
[Bug]: FONTS are very small on herd pro, on logs , on dumps, make them larger please, its unviewable

### ISSUE THREAD

**Issue by SerjoA** [beyondcode/herd-community#771]
### Platform

macOS

### Operating system version

mac os sonoma

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.0.6

### PHP Version

php 8.2.8

### Bug description

FONTS are very small on herd pro, on logs , on dumps, make them larger please, its unviewable

### Steps to reproduce

do dumps or logs

**Comment by sschlein** [comment]
Can you please make a screenshot how it looks on your system?

**Comment by SerjoA** [comment]
here is a screenshot from my external monitor - the same happens on my internal mac 16 inch
barely visible, perhaps if i have the option to enlarge font size - that will fix it
same happens with logs btw.
![Uploading CleanShot 2024-05-30 at 23.02.53@2x.png…]()

**Comment by SerjoA** [comment]
thank u
