### ISSUE TITLE
[Bug]: Not able to identify nodejs

### ISSUE THREAD

**Issue by shahvirag** [beyondcode/herd-community#772]
### Platform

Windows

### Operating system version

Windows 11(23H2 22631.3593)

### System architecture

Windows

### Herd Version

1.6.1

### PHP Version

PHP 8.3.7

### Bug description

I have reinstalled Herd but not able to install nodejs properly.  PHP is working very well.

here are some screenshot.
![Screenshot 2024-05-30 224444](https://github.com/beyondcode/herd-community/assets/24240840/d3356df0-aa81-4ccb-bd73-6164359034ee)

Here is an environment variable setting.
![Screenshot 2024-05-30 224749](https://github.com/beyondcode/herd-community/assets/24240840/ead9b939-6b6b-4057-9042-c9f68963ac66)

![Screenshot 2024-05-30 224911](https://github.com/beyondcode/herd-community/assets/24240840/c967dba0-05c9-4d69-a58b-c796ee5a6ebf)

**Comment by mpociot** [comment]
I'll close this issue as it's been open for a long time. If this is still relevant on Herd 1.11.0, please open a new issue 👍
