### ISSUE TITLE
[Bug]: when trying to open a new project with herd sites the project folder gets deleted after herd site visit 

### ISSUE THREAD

**Issue by Masumrahmanhasan** [beyondcode/herd-community#774]
### Platform

macOS

### Operating system version

macos sonoma 

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.6.1

### Bug description

I downloaded a project from codecanyon and i tried to set it up in local but when i extract it works fine but after i go to herd settings to change the version of the php for that project it gets deleted.

**Comment by mpociot** [comment]
We don't have any code in Herd that deletes a project.
If you can reproduce this, let me know, but I'm sure this is unrelated to Herd.

**Comment by Masumrahmanhasan** [comment]
https://github.com/beyondcode/herd-community/assets/55694939/1ed08954-f165-4a52-a179-cf03d9024959

check this video
