### ISSUE TITLE
[Bug]: Mail viewer in darkmode not readable

### ISSUE THREAD

**Issue by OscarKolsrud** [beyondcode/herd-community#775]
### Platform

Windows

### Operating system version

Windows 10 Pro 22H2 19045.4412

### System architecture

Windows

### Herd Version

1.6.1

### Bug description

![image](https://github.com/beyondcode/herd-community/assets/30559109/5a51a0a9-9ae7-4adf-9fc3-ba593485a9ea)

Emails received into Herd when darkmode is enabled is not readable at all. Could we have a dark/light mode switcher for this view?

### Steps to reproduce

Have dark mode enabled in Windows, send/receive an email into herd

**Comment by mpociot** [comment]
I added an internal issue for us to track this. Thanks for reporting this

**Comment by sschlein** [comment]
Fixed in 1.7+
