### ISSUE TITLE
[Bug]: New sites don't appear in site list without refreshing.

### ISSUE THREAD

**Issue by avenjamin** [beyondcode/herd-community#777]
### Platform

macOS

### Operating system version

macOS Sonoma 14.5 (23F79)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.6.1 (Build: 25)

### Bug description

After creating a new site within Herd the sites list doesn't automatically update to include the new site.
You have to click the refresh button.

### Steps to reproduce

1. Create site in Herd.
2. Fill in the fields
3. On the last pane - Press the close button.
4. Observe the new site isn't listed in the Herd Sites list.
5. Press the refresh button
6. Observe the new site appears in the Herd Sites list.

**Comment by sschlein** [comment]
We'll fix that with the release of the new Sites window. You have a look at some early, partially unstyled version at https://twitter.com/marcelpociot/status/1797606332209705408

🙂
