### ISSUE TITLE
[Bug]: Trying to add a service (MySQL) and Herd Pro just crashes

### ISSUE THREAD

**Issue by xsd08tfu** [beyondcode/herd-community#779]
### Platform

macOS

### Operating system version

macOS Sonoma 14.5

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.6.1

### Bug description

Having upgraded to Herd Pro, I expected to be able to create a database service. Every time I try to add a MySQL database, Herd crashes with the following exception codes: 0x0000000000000001, 0x0000000193dedee0

### Steps to reproduce

Install Herd, Upgrade to Pro, try to create a service

**Comment by sschlein** [comment]
I am sorry for this experience!

Can you please check if Herd is able to download the binaries?

They are at `/Users/Shared/Herd/services/mysql/8.0.36/bin`

If they are available, is it able to create a data folder at `/Users/YOUR-USER/Library/Application Support/Herd/config/services` ?

If you want to give the upcoming version a try, you can download 1.7 [here](https://herd-dev.fra1.digitaloceanspaces.com/test-builds/Herd_1.7.0.dmg).

**Comment by xsd08tfu** [comment]
Thanks for coming back to me, I tried v1.7 and I get the same error. 

I have checked `/Users/Shared/` directory, and Herd does not have a folder in there. Once I created this directory, it downloaded the service and successfully ran. 

Sorry if I missed a step in installation of the need to create this directory manually!

**Comment by sschlein** [comment]
It does work now? If yes, please close this issue 🙂

The folder is normally created automatically, so I am super confused why that didn't happen on your machine and even lead to a crash...

**Comment by xsd08tfu** [comment]
After a bit of port juggling yes it does! Thanks!
