### ISSUE TITLE
[Bug]: Mails not showing

### ISSUE THREAD

**Issue by simonhamp** [beyondcode/herd-community#781]
### Platform

macOS

### Operating system version

macOS Sonoma 14.1 (23B74)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.6.1 build 25

### Bug description

The Mail window is no longer displaying mails. I just sent a mail, was viewing it, tabbed to another window, tabbed back to the mail and the message went blank.

Switching between messages also reveals nothing - all messages are blank.

I've cleared out that mailbox, then all mailboxes and tried quitting Herd and re-opening. It always comes back blank now

### Steps to reproduce

I'm not sure... I just tabbed between Herd's mail window and the browser a couple of times in a row.

**Comment by sschlein** [comment]
Can you check if there are still mails in the sqlite database in your Herd config directory? My guess is that some mail is somehow breaking something

**Comment by simonhamp** [comment]
@sschlein would that be this one?

![Screenshot 2024-06-07 at 11 49 06](https://github.com/beyondcode/herd-community/assets/31628/d0be37c8-79c5-4a12-9e49-2eb5208a0692)

**Comment by simonhamp** [comment]
I can see relevant tables in that file and when mails are received they populate. When I delete all the mailboxes via the Herd UI, the mail tables in this DB go completely empty - nothing appears to be hanging around

**Comment by sschlein** [comment]
Can you try this version? [Download](https://herd-dev.fra1.digitaloceanspaces.com/test-builds/Herd_1.7.0_240607.dmg)

That's the new build for the release next week with some changes in there.

I also wonder if that's just one specific email that causes the issue or if a test email of a different application does the same?

**Comment by simonhamp** [comment]
That hasn't fixed it unfortunately 😔

**Comment by simonhamp** [comment]
Ah! No, something has worked... I had no mails, tried one. It was received, but failed to show the mail content as before. But I cleared the box out using the Herd UI (back to no mails) and tried again and this time it works!

**Comment by simonhamp** [comment]
And almost as soon as that occurred, another clearing of the mailbox and sending another test and I can't get it to show the mail content again 😢

**Comment by sschlein** [comment]
I'm closing this because it has resolved directly and this seemed to be a local issue 🙂
