### ISSUE TITLE
[Bug]: max_execution_time not used

### ISSUE THREAD

**Issue by damms005** [beyondcode/herd-community#785]
### Platform

macOS

### Operating system version

macOS Sonama 14.5 (23F79)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.6.1 Build 25

### PHP Version

PHP 8.3

### Bug description

`max_execution_time` not used.

May be related to #267

I recorded a little video perhaps, helpful?

https://github.com/beyondcode/herd-community/assets/9839355/f59d7296-a532-4db1-a436-24236733b780

What I tried:

- Changing order
- Setting same value in all versions of PHP installed in herd

Please let me know if you need more info.

### Steps to reproduce

- update `max_execution_time` in php ini config file
- create a route that does `phpinfo()`
- load the route in the browser and confirm the php ini is loaded but the `max_execution_time` is ignored

### Screencast
https://github.com/beyondcode/herd-community/assets/9839355/f59d7296-a532-4db1-a436-24236733b780

**Comment by mpociot** [comment]
I'm unable to reproduce this.
Please "force stop" all Herd services via the UI and then start them again. I suppose that FPM is not properly reloading for some reason.

You can do this by pressing the option key when clicking on the Herd icon in the menubar.

![CleanShot 2024-06-11 at 10 35 31@2x](https://github.com/beyondcode/herd-community/assets/804684/a80d32da-e071-4352-8594-140b677f1e23)

**Comment by DevDavido** [comment]
Experienced the same issue also with Herd 1.9.1 / PHP 8.3, force stopping and restarting FPM as described by @mpociot helped.
