### ISSUE TITLE
[Bug]: Old composer version (2.6.5)

### ISSUE THREAD

**Issue by Kuldas** [beyondcode/herd-community#791]
### Platform

Windows

### Operating system version

Windows 10 (22H2 19045.4412)

### System architecture

Windows

### Herd Version

1.6.1

### PHP Version

PHP 8.3.7 (cli) (built: May  8 2024 08:56:34) (NTS Visual C++ 2019 x64)

### Bug description

I installed Herd today, but I found in the CLI that the version of Composer I'm using is 2.6.5, which is older than the current version. 

I thought Herd already had Composer in it and therefore would use some more current version. 

Could the error be due to the fact that I had Composer installed on my PC before I installed Herd? If so, how should I proceed?

I am attaching a picture from the CLI.
![composer-version](https://github.com/beyondcode/herd-community/assets/15139047/b089dcde-30e2-45da-906e-e21eeec6e7b2)

**Comment by sschlein** [comment]
This will be fixed in the next release later this week  🙂

**Comment by mpociot** [comment]
In the meantime, you can already update Composer yourself by running `composer self-update`
Just keep in mind that Herd will replace the composer version when you quit and relaunch Herd (for example on a computer restart)

**Comment by mpociot** [comment]
This is now fixed in Herd 1.7.0
