### ISSUE TITLE
[Bug]: Dumps don't show when running in jobs or via `php artisan serve`

### ISSUE THREAD

**Issue by IsraelOrtuno** [beyondcode/herd-community#792]
### Platform

macOS

### Operating system version

14.5 (23F79)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.6.1 (Build: 25)

### Bug description

I am not sure if this is how `dumps` are supposed to work. I am trying to debug some queued jobs but I can't get Herd to intercept the `dump` calls while processing them, it only works when I visit the `*.test` domains from the browser. It's not working either when using `php artisan serve` and dumping directly from any route. Not sure where to start debugging...

**Comment by sschlein** [comment]
@IsraelOrtuno 

I've attached a screenshot, could you please confirm that the dump-loader is on your php.ini?

![CleanShot 2024-06-12 at 11 39 12](https://github.com/beyondcode/herd-community/assets/2911113/b2b7930b-7e6a-4f99-b145-dc07b7f9b76c)

**Comment by IsraelOrtuno** [comment]
@sschlein 
<img width="1087" alt="image" src="https://github.com/beyondcode/herd-community/assets/1769417/cda7cca4-9b6d-485a-9a3e-cc4b11650e58">

<img width="1257" alt="image" src="https://github.com/beyondcode/herd-community/assets/1769417/f6c7e7a0-0471-473f-ba85-a7cbf0588596">

**Comment by sschlein** [comment]
May I ask why you run `php artisan serve` in the first place instead of using the `.test` domain like it's intended to be used?
