### ISSUE TITLE
[Bug]: Unable to setup service when installing MySQL service

### ISSUE THREAD

**Issue by danielpaddington** [beyondcode/herd-community#793]
### Platform

Windows

### Operating system version

Windows 10 Pro | 10.0.19045 Build 19045

### System architecture

Intel (x86)

### Herd Version

1.6.1

### Bug description

When adding a new MySQL service in Herd, an error occurs reading "Herd was unable to setup this service. Please check your log files and try again."

Upon inspection, the URL shown in the log file is unresponsive to all requests.

### Relevant log output

```shell
[2024-06-12 21:01:26.203] [info]  Saving service config {
  port: 3306,
  name: 'MySQL',
  type: 'mysql',
  version: '8.0.36',
  source: 'https://download.herdphp.com/databases/mysql/mysql-8.0.36-winx64.zip'
}
[2024-06-12 21:01:26.209] [info]  Service not installed. Attempting install
[2024-06-12 21:01:26.209] [info]  Can't install, an install is already running
[2024-06-12 21:01:26.219] [info]  Initialize MySQL
```

**Comment by sschlein** [comment]
Do you have any idea which install on your machine is still running?

**Comment by danielpaddington** [comment]
After uninstalling Laragon, there shouldn't be any other installations of MySQL present. I have tried adding the MySQL service in Herd after rebooting, still no luck

**Comment by sschlein** [comment]
As far as I know, this could be any install for any program but if you did a restart, there shouldn't be an install running. 

Are the MySQL binaries at %USERPROFILE%\.config\herd\bin\services\mysql\8.0.36?

**Comment by danielpaddington** [comment]
No binaries are present at that path. The folders for the services I tried to install are visible but empty.

**Comment by sschlein** [comment]
Can you please delete the 8.0.36 folder and try installing MySQL again? That should trigger the download, it seems like something went wrong during extraction of the binaries.

**Comment by danielpaddington** [comment]
The same issue occurred after deleting the folder.

I noticed that when visiting the direct link to MySQL found in the log file (`https://download.herdphp.com/databases/mysql/mysql-8.0.36-winx64.zip`,) it cannot be accessed. When attempting to download PostgreSQL, I still get the same error, though the direct download link in the log file does actually resolve and I can download it directly. Could be completely unrelated but still a possible cause.

**Comment by sschlein** [comment]
That might be the main course. Any idea why this would happen? This link goes through our Cloudflare CDN.

Where are you located? How does the permission error in your browser look like?

**Comment by danielpaddington** [comment]
After messing with some network config settings, the URL mysteriously appears to now be resolving correctly. The same error is still occurring in Herd though. I'm located in Australia and the error I was previously encountering (when trying to access the download link directly,) was a message saying "Error" where the download speed would normally be shown on a file download in Firefox.

**Comment by sschlein** [comment]
Any idea which network setting fixed it? If this was a DNS problem, Herd could still have it cached 🤔 

The origin servers are in Germany but CF should solve that and allow for fast download speeds everywhere.

As a temporary fix, you could extract the zip file to the path mentioned above and create a new Herd service from there. That should pick up the binaries and use them for the MySQL instance.

I'd love to get that solved without such a workaround to fix possible issues for everyone but I am a bit confused on how to debug this further.

**Comment by danielpaddington** [comment]
I believe it was a DNS issue on my end. 

I've extracted the contents of the zip file to the `8.0.36` folder and attempted to start the service. Still to no avail, but getting closer to a solution.

The MySQL log file is as follows:
```
2024-06-12T13:49:05.917847Z 0 [System] [MY-010116] [Server] C:\Users\User\.config\herd\bin\services\mysql\8.0.36\bin\mysqld.exe (mysqld 8.0.36) starting as process 20532
2024-06-12T13:49:05.932400Z 1 [ERROR] [MY-011011] [Server] Failed to find valid data directory.
2024-06-12T13:49:05.932896Z 0 [ERROR] [MY-010020] [Server] Data Dictionary initialization failed.
2024-06-12T13:49:05.933218Z 0 [ERROR] [MY-010119] [Server] Aborting
2024-06-12T13:49:05.933646Z 0 [System] [MY-010910] [Server] C:\Users\User\.config\herd\bin\services\mysql\8.0.36\bin\mysqld.exe: Shutdown complete (mysqld 8.0.36)  MySQL Community Server - GPL.
```

**Comment by sschlein** [comment]
If you delete the instance via right click from the services tab and create a new one, that should use the existing binaries and initialize the service properly. Just creating a new instance should do the same trick 🙂

**Comment by danielpaddington** [comment]
Creating a new instance after manually installing the binaries worked perfectly. I'll mark this issue as resolved.

Thanks!
