### ISSUE TITLE
[Bug]: Fresh install of Herd on macOS not finding [project].test sites 

### ISSUE THREAD

**Issue by nalenb** [beyondcode/herd-community#795]
### Platform

macOS

### Operating system version

macOS Sonoma 14.5 (23F79)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.7.0 (build 27)

### PHP Version

PHP 8.3.7 (cli) (built: May 10 2024 12:47:16) (NTS)

### Bug description

Seems [similar to #650](https://github.com/beyondcode/herd-community/issues/650)

I installed macOS, then Xcode, then Herd. I have not installed brew. The machine is my own and not managed by anyone.

I created a site via terminal and via Herd's add site button, both give me a 404 error when I visit the [project].test site.

I'm not running Herd pro and I see nothing in the logs. I also tried rebooting several times.

<img width="831" alt="Screenshot 2024-06-12 at 5 09 13 PM" src="https://github.com/beyondcode/herd-community/assets/139521/21b23da7-97ca-4c86-9e29-2879bbd63d2a">

### Steps to reproduce

I wiped my Mac today.
Downloaded Herd from https://herd.laravel.com today 6/12/2024
Copied Herd to my Applications folder
Ran Herd and had no issues in the install
Via Herd settings I installed Node 20 (20.14.0)
I created a new app in ~/Herd via Laravel new chirper from the terminal
I tried to open http://chirper.test in my browser and receive 404

Navigating to http://localhost gives me a nice Laravel Herd 404 error, so I think nginx is running.

Herd shows everything is running.

<img width="220" alt="Screenshot 2024-06-12 at 5 10 57 PM" src="https://github.com/beyondcode/herd-community/assets/139521/27cab228-f792-4929-b476-8a1c8d65bad7">

Running ps aux shows me that nginx, php-fpm, and dnsmasq are running, but dnsmasq is running under user "nobody"
nobody            1518   0.0  0.0 410751264   2240   ??  S     4:51PM   0:00.01 /Applications/Herd.app/Contents/Resources/dnsmasq-arm64 --keep-in-foreground --conf-file=/Users/nalenb/Library/Application Support/Herd/config/dnsmasq/dnsmasq.conf

Not sure what else I can provide

### Relevant log output

```shell
I see nothing in the logs.
```

**Comment by nalenb** [comment]
Can't ping the site either

ping chirper.test
ping: cannot resolve chirper.test: Unknown host

I did install Herd a few days ago and it was working fine. It's only after I reinstalled macOS that I'm having the issue.

**Comment by mpociot** [comment]
What happens when you run 

ping foo.test

?

**Comment by nalenb** [comment]
I assume you mean to replace foo with one of my sites?

ping chirper.test
ping: cannot resolve chirper.test: Unknown host

Also, clarification above, I'm not getting the nice Herd 404 page, I get the Safari server not found page.

<img width="513" alt="Screenshot 2024-06-12 at 11 27 48 PM" src="https://github.com/beyondcode/herd-community/assets/139521/c5089161-3198-4465-a66e-ceba9d927d57">

**Comment by mpociot** [comment]
As dnsmasq resolves any `*.test` domain to localhost, it actually doesn't matter.

You should have this file: `/etc/resolver/test`

With this content: `nameserver 127.0.0.1`

Can you confirm this?

**Comment by nalenb** [comment]
I do not have a /etc/resolver folder at all.

**Comment by mpociot** [comment]
That's weird. Could you run this in your terminal:
```
sudo mkdir -p /etc/resolver
echo "nameserver 127.0.0.1" | sudo tee -a /etc/resolver/test
```

This should fix it 👍

**Comment by nalenb** [comment]
That fixed it. I wonder why I don't have that folder by default. Does the Herd install create it or should it already exist on a fresh macOS install? I might try wiping again tomorrow and reinstalling Herd again.

**Comment by mpociot** [comment]
That's a regression bug in Herd 1.7.0 as we changed the way we run sudo code. I'm publishing a 1.7.1 version right now, so thanks for reporting this :)

**Comment by nalenb** [comment]
Ah, okay. I'll look for 1.7.1 and wipe and verify it :-)

**Comment by datune** [comment]
I can confirm this behaviour, I just went through the same ordeal before finding this bug report, running the suggestion by mpociot fixed it.

**Comment by sschlein** [comment]
We've just released Herd 1.7.1 which should fix that 🙂 Please let me know if it didn't.

This update follows a phased rollout, so you might not get it automatically today but be on a group that gets it next week. You can bypass this by manually trigger the update check and get the update directly.

**Comment by nalenb** [comment]
I just reinstalled macOS and then ran the installer for Herd 1.7.1. Everything works as expected. Thanks for fixing this so quickly.

**Comment by andersonbsp** [comment]
I'm having the same problem above even with version 1.7.1, it was working perfectly but I went to update it and now it doesn't recognize the host and I can't add any other one, where can I download the previous versions?

**Comment by mpociot** [comment]
> I'm having the same problem above even with version 1.7.1, it was working perfectly but I went to update it and now it doesn't recognize the host and I can't add any other one, where can I download the previous versions?

What exactly do you mean? Is dnsmasq running for you?

**Comment by andersonbsp** [comment]
Yes, everything works, but with this problem after I did the update, I even did a new installation and the problem continues.

**Comment by andersonbsp** [comment]
Is there somewhere I can find previous versions of herd for mac?

**Comment by GaniyuWi** [comment]
I'm having this same problem but on windows.

**Comment by fschroiff** [comment]
I had a DNS configuration profile installed, once I removed it Herd worked fine.

**Comment by idsosd** [comment]
I'm having the same problem as described by nalenb. I use Herb 1.7.1 but I can see my sites at http://127.0.0.1/site.test (instead of http://site.test). So in a way, it works, but the database connections fail and I don't know how to workaround that problem. All things seem to be up and running, including the line in '/etc/resolver/test'. In the dnsmasq-logfile there's one line saying that '127.0.0.1 is used by another daemon' or something like that.

Any suggestion?

**Comment by codearachnid** [comment]
Just wanted to come and say that I was having similar issues - i found that the `/etc/resolver/test` had the value of `nameserver 127.0.0.1nameserver 127.0.0.1` and was causing dns issues. Once i fixed that it worked again no issues. Currently using v1.22.1
