### ISSUE TITLE
[Question]: possibility of replacing included extension with an external one

### ISSUE THREAD

**Issue by Treggats** [beyondcode/herd-community#797]
### Platform

macOS

### Operating system version

macOS Sonoma Version 14.5 (23F79)

### System architecture

Intel (x86)

### Herd Version

1.7.0 (Build 27)

### PHP Version

PHP 8.3.7 (cli) (built: May 10 2024 12:59:07) (NTS)

### Bug description

I think this relates to #295

We use version six of the redis extension, however it seems that version 5 is included in Herd.

Is there a possibility where we can use the redis extension that is already present on my machine?
I am able to load additional extensions as described in the documentation.

### Steps to reproduce

1. create a new laravel project
2. add the following in the "require" key of `composer.json`
   - `"ext-redis": "^6.0",`
3. see the following error
   - `Root composer.json requires PHP extension ext-redis ^6.0 but it has the wrong version installed (5.3.7).`

### Relevant log output

```shell
~/P/todo-application ❯❯❯ composer update                                                                                                                  
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires PHP extension ext-redis ^6.0 but it has the wrong version installed (5.3.7).

To enable extensions, verify that they are enabled in your .ini files:
    - /Users/<user>/Library/Application Support/Herd/config/php/83/php.ini
You can also run `php --ini` in a terminal to see which files are used by PHP in CLI mode.
Alternatively, you can run Composer with `--ignore-platform-req=ext-redis` to temporarily ignore these required extensions.


---
curl.cainfo=/Users/<user>/Library/Application Support/Herd/config/php/cacert.pem
openssl.cafile=/Users/<user>/Library/Application Support/Herd/config/php/cacert.pem
pcre.jit=0
output_buffering=4096

memory_limit=2048M

;extension=/usr/local/lib/php/pecl/20230831/redis.so
;extension=/usr/local/lib/php/pecl/20230831/mongodb.so
```

**Comment by sschlein** [comment]
I think that this does not work at the moment as the extension is compiled into the binary for portability but need to verify this with the team. I'll also check why we have v5 and not using v6!

**Comment by Treggats** [comment]
@sschlein any update on this? Or should we just close this issue.

**Comment by sschlein** [comment]
You can't replace existing extensions but we still have it on our list to check if we can upgrade to v6 – there's just so much going on that we haven't made this a priority right now.

**Comment by edward-rw** [comment]
Too bad this is closed. 
This is a dealbreaker for our team using Herd.
We have dependencies on v6... and there seems to be no way to override the built in 5.3.7 driver.
Paid for Herd but now have to downgrade to Valet it seems like. The devs that use Valet can keep coding... but the devs using Herd are stuck.
Too bad since I loved Herd and kept poking the other devs to "upgrade".
