### ISSUE TITLE
[Bug]: Windows 11, can't move any of the pop up windows such as Dumps or Logs

### ISSUE THREAD

**Issue by itsmill3rtime** [beyondcode/herd-community#798]
### Platform

Windows

### Operating system version

Windows 11

### System architecture

Windows

### Herd Version

1.6.1

### PHP Version

php 8.3

### Bug description

When clicking title bar area, you can not drag to move the window around the screen for Dumps or Logs (or any pop up windows) so it is just stuck right in the middle of the screen. You can drag the edge of the window to resize and then the opposing edge to resize to get it to where you want on your screen, but that is less than ideal

### Steps to reproduce

Click on title bar area of pop up windows and try and drag the position of the popup window

**Comment by sschlein** [comment]
Hey, you can drag them on their icon 🙂

The next version (that we wanted to release today but found some bugs) improves that but the icons always work!
