### ISSUE TITLE
[Bug]: Small window open when starting on macOS 15

### ISSUE THREAD

**Issue by secondmanveran** [beyondcode/herd-community#799]
### Platform

macOS

### Operating system version

macOS Version 15.0 Beta (24A5264n)

### System architecture

Intel (x86)

### Herd Version

1.7.0 (27)

### Bug description

This is mostly just a heads up for when you guys start working on the version to support macOS 15. 

I'm guessing this may be related to Electron, but there's a small window that opens when launching the app, either manually or on startup.

<img width="213" alt="Screenshot 2024-06-13 at 2 17 23 PM" src="https://github.com/beyondcode/herd-community/assets/97000801/83efa319-fd33-402d-ba14-b3052432a4bd">

Nothing seems to go wrong when closing it so it's nothing but an inconvenience really.

Just wanted you to be aware that it's coming.

Cheers.

### Steps to reproduce

Install macOS 15.

**Comment by mpociot** [comment]
This was fixed in 1.8.0
