### ISSUE TITLE
[Bug]: dump viewer error expand threes

### ISSUE THREAD

**Issue by stephanesoares** [beyondcode/herd-community#803]
### Platform

Windows

### Operating system version

Windows 10 (22H2 19045.4474)

### System architecture

Windows

### Herd Version

1.7.0

### Bug description

![image](https://github.com/beyondcode/herd-community/assets/4375100/276860cf-0108-4603-908f-bf36c2ec2fd9)

Cannot expand this after update to 1.7.0

**Comment by mpociot** [comment]
We just published version 1.7.1 which addresses this issue.
