### ISSUE TITLE
[Bug]: Herd is not working correctly

### ISSUE THREAD

**Issue by web-studio-51** [beyondcode/herd-community#807]
### Platform

Windows

### Operating system version

windows 10

### System architecture

Windows

### Herd Version

last

### PHP Version

all

### Bug description

Hi! I started using herd a month ago and everything was fine. At some point, herd stopped seeing the sites. They were opened using the local path, but were not displayed in the program interface.

Then I noticed the message "Please change the port if the status is red or enable debug mode and restart Herd. If it is still red and not working, please email the logs to [support@beyondco.de](mailto:support@beyondco.de)
"

I've tried changing the port, but it doesn't help.

I have disabled the antivirus on my computer

I can't write commands for herd in the console

C:\Users\User>herd
The Herd Desktop application is not running. Please start Herd and try again.

Although the program is running

I am using Windows 10

Configs

{
 "tld": "test",
 "loopback": "127.0.0.1",
 "paths": [
 "C:\\Herd"
 ],
 "share-tool": "expose"
}

and
 {
"apiPort": 9001,
"autoUpdate": false,
"openLastSiteInTinkerShortcut": "",
"openLastSiteInTerminalShortcut": "",
"openSitesShortcut": "CommandOrControl+Shift+S",
"openDumpsShortcut": "CommandOrControl+Alt+Shift+D",
"clearDumpsShortcut": "CommandOrControl+Alt+Shift+C",
"interceptDumpsShortcut": "CommandOrControl+Alt+Shift+I",
"openMailsShortcut": "CommandOrControl+Alt+Shift+M",
"openLogViewerShortcut": "CommandOrControl+Alt+Shift+L",
"basePhpPort": 9000,
"baseDebugAddition": 100,
"smtpPort": 2525,
"dumps": false,
"mails": false,
"setupCompleted": true,
"activeVersion": "8.3",
"showNewDumpsOnTop": true,
"dumpFontSite": 14
}

I tried reinstalling the program, but it doesn't help

 nginx-error.log contains no new errors

2024-06-16 13:46:42.681 +03:00 [DBG] Hosting starting
2024-06-16 13:46:42.723 +03:00 [INF] Config path: C:\ProgramData\Herd\service.json.
2024-06-16 13:46:42.724 +03:00 [INF] Config file with port exists, using port: 1345.
2024-06-16 13:46:42.727 +03:00 [INF] Application started. Hosting environment: Production; Content root path: C:\Users\User\.config\herd\bin\
2024-06-16 13:46:42.728 +03:00 [DBG] Hosting started
2024-06-16 13:46:42.736 +03:00 [INF] HTTP Server started on http://localhost:1345/.

My colleagues use herd, but I see that it does not work on my computer
![2024-06-16_13-59-22](https://github.com/beyondcode/herd-community/assets/44437378/3dbefa05-447d-452a-befb-7c2ce290b575)
![2024-06-16_13-59-47](https://github.com/beyondcode/herd-community/assets/44437378/289ec8a6-4a1e-4ca0-a6e0-43db8caedfdf)
![2024-06-16_14-00-32](https://github.com/beyondcode/herd-community/assets/44437378/1137d25d-61e3-4be0-99fd-b8a41389850d)

**Comment by sschlein** [comment]
Can you please try this:

https://github.com/beyondcode/herd-community/issues/566#issuecomment-2179919627 ?
