### ISSUE TITLE
[Bug]: Launch at login opens the settings window

### ISSUE THREAD

**Issue by olehasoft** [beyondcode/herd-community#808]
### Platform

Windows

### Operating system version

Windows 11

### System architecture

Windows

### Herd Version

1.7.1

### PHP Version

8.3.8

### Bug description

After updating to version 1.7.0, the settings window (main) opens at login, when General > Startup > Launch at login is enabled.
Previously, only the taskbar icon appeared, which was a very nice behavior.

**Comment by sschlein** [comment]
We plan to release a configuration for this with Herd 1.8 that is scheduled for next week.
