### ISSUE TITLE
[Bug]: different `cli/Valet/Drivers/ValetDriver.php` than core valet

### ISSUE THREAD

**Issue by marcorieser** [beyondcode/herd-community#812]
### Platform

macOS

### Operating system version

macOS Sonoma Version 14.5 (23F79)

### System architecture

Intel (x86)

### Herd Version

1.7.1 (Build: 28)

### Bug description

I'm using Statamic and run `herd which` and it outputs: `This site is served by [Valet\Drivers\LaravelValetDriver].` but it should be served from [`StatamicValetDriver`](https://github.com/laravel/valet/blob/master/cli/Valet/Drivers/Specific/StatamicValetDriver.php). I searched for a solution and found that [PR](https://github.com/laravel/valet/pull/1440) where the Statamic driver gets injected before the Laravel driver.

When I diff the [core valet driver file](https://github.com/laravel/valet/blob/master/cli/Valet/Drivers/ValetDriver.php#L48) with my local bundled one in `/Applications/Herd.app/Contents/Resources/valet/cli/Valet/Drivers/ValetDriver.php` they are not the same.

I've no idea why Herd seems to bundle an older version of valet or why they differ.

**Comment by mpociot** [comment]
Herd is running a customized version of Valet, which is why there's a difference.
I'll update the driver in the next release. In the meantime you can use a custom Valet driver for your projects.

**Comment by marcorieser** [comment]
Thanks

**Comment by mpociot** [comment]
This was fixed in 1.8.0
