### ISSUE TITLE
[Bug]: Imagick is not working properly and breaks menu Sites

### ISSUE THREAD

**Issue by Benisy** [beyondcode/herd-community#815]
### Platform

Windows

### Operating system version

Windows 11 Pro 23H2 22631.3737

### System architecture

Windows

### Herd Version

1.7.1

### PHP Version

8.3.8

### Bug description

When you install the "Imagick" extension, a warning notice appears that breaks menu sites. At the same time the extension itself works in php. Please include this extension as part of Laravel Herd because it is more efficient in working with large images than GD extension.

![2024-06-17 14-21-06](https://github.com/beyondcode/herd-community/assets/20333967/688881f1-f01d-4aa7-865f-b969133ab956)

### Steps to reproduce

1. download and install last ImageMagick from Windows [ImageMagick-7.1.1-33-Q16-HDRI-x64-dll.exe](https://imagemagick.org/archive/binaries/ImageMagick-7.1.1-33-Q16-HDRI-x64-dll.exe)
2. download and move `php_imagick.dll` to `.config\herd\bin\php83\ext` [8.3 Non Thread Safe (NTS) x64](https://downloads.php.net/~windows/pecl/releases/imagick/3.7.0/php_imagick-3.7.0-8.3-nts-vs16-x64.zip)
3. add `extension=imagick` to `php.ini` from `.config\herd\bin\php83`
4. run `php -i|find "PHP Version"`
5. result `PHP Warning:  Version warning: Imagick was compiled against ImageMagick version 1808 but version 1809 is loaded. Imagick will run but may behave surprisingly in Unknown on line 0
PHP Version => 8.3.8
PHP Version => 8.3.8`

**Comment by nrmnhdyt** [comment]
> Installing Imagick is definitely pretty tricky on Windows as it requires you to use the exact same version of some DLLs.
> 
> We will make this easier in upcoming versions of Herd for Windows and ship ImageMagick pre-installed 👍

many windows users have difficulty installing imagick in laravel herd sir.

**Comment by benjaminhaeberli** [comment]
We really need it, I'm trying to install since 2 hours on my new laptop, it's insane 🤯

**Comment by Ticket-Master** [comment]
Please add it in by default for windows. It seems that it does not work at all in Windows.
