### ISSUE TITLE
[Bug]: Text not readable in Darkmode at Herdhelper

### ISSUE THREAD

**Issue by hebbet** [beyondcode/herd-community#816]
### Platform

Windows

### Operating system version

Windows 11 24H2 26120.770

### System architecture

Windows

### Herd Version

1.7.2

### Bug description

Text under `General` > `HerdHelper` is not readable
<img width="491" alt="image" src="https://github.com/beyondcode/herd-community/assets/1423115/4937b06d-d92c-4af7-af36-9d311278eb92">

### Steps to reproduce

* Open Laravel Herd
* Go to "General"
* Scroll down

**Comment by sschlein** [comment]
Thanks, fixed for the next release

**Comment by mpociot** [comment]
This is now fixed in v1.8.0
