### ISSUE TITLE
[Bug]: mySQL does not auto-restart after Windows auto-update

### ISSUE THREAD

**Issue by mathiaswillburger** [beyondcode/herd-community#818]
### Platform

Windows

### Operating system version

Windows 11

### System architecture

Windows

### Herd Version

1.7+

### PHP Version

8.2

### Bug description

In the last few days, when receiving three auto-updates shortly after each other, all services auto-started after every update, except for the MySQL service. When manually stopping and starting all services afterwards, everything worked as usual. However, the same behavior could be seen in 1.7.0, 1.7.1 and 1.7.2. 

Just a theory: Maybe MySQL is not shutting down properly when updating and therefore being blocked to start when opening Herd again.

**Comment by mpociot** [comment]
This issue was fixed in v1.7.2 - you might see this once after updating, but stopping/starting all services and then re-opening Herd again should fix it.

**Comment by mathiaswillburger** [comment]
Ok thanks, I will check it after the next update becomes available.
