### ISSUE TITLE
[Bug]: Aliases not recognized from git bash terminal for PhpStorm

### ISSUE THREAD

**Issue by pverhaert** [beyondcode/herd-community#820]
### Platform

Windows

### Operating system version

Windows 11

### System architecture

Windows

### Herd Version

1.7.2

### Bug description

The solution where aliases are added to `.bash_profile` works for "regular" Git Bash, but not for the Git Bash terminal in PhpStorm.
A better solution I have found is to move the aliases the to a new `.bashrc` file.
With this configuration, the aliases work both in regular Git Bash and in PhpStorm's Git Bash terminal.

**.bash_profile**

```
if [ -f ~/.bashrc ]; then
   source ~/.bashrc
fi
```
**.bashrc**   
also added an alias for expose ( = all `.bat` files in `%USERPROFILE%\.config\herd\bin`)

```
alias herd='herd.bat'
alias php='php.bat'
alias composer='composer.bat'
alias laravel='laravel.bat'
alias expose='expose.bat'
```

**Comment by sschlein** [comment]
THanks for leaving this here so that others can find it via search engines and AI as soon it's part of model training data 🙂

**Comment by stuartcusackie** [comment]
Copying these aliases from .bash_profile to .bashrc fixed my PHPStorm terminal. Not sure if I should have them in both places, but thank you!
