### ISSUE TITLE
[Bug]: nvm does not work after reinstalling Herd

### ISSUE THREAD

**Issue by pverhaert** [beyondcode/herd-community#821]
### Platform

Windows

### Operating system version

Windows 11

### System architecture

Windows

### Herd Version

1.7.2

### Bug description

**nvm** does not work after re-installing Herd

When re-installing Herd, `node -v` did not work.
After uninstalling Herd, as described in the documentation https://herd.laravel.com/docs/windows/1/troubleshooting/uninstalling, nvm did install properly, but did not shows an * in front of version 22.3.0 with the `nvm list` command. Neither did `node -v` work.

In my previous installation of Herd, I had set node **20.14.0** as default and that was the reason why the re-installation failed.

When uninstalling Herd, the shortcut `C:programfiles/nodejs` (which now pointed to a non-existent version of Node) remains, and this shortcut is apparently not overwritten on re-installation.

Is it possible to remove the shortcut with the uninstaller?

Or else add a point 5 to the documentation that you have to remove the shortcut manually.

PS: in point 3 of the documentation, a `%` is missing between `%USERPROFILE` and `\.config\herd`.

Point 4 also need a little more clarification. I could not remove nvm with the Windows installer but just need to remove `NVM_HOME` and `NVM_SYMLINK` as described here: https://herd.laravel.com/docs/windows/1/advanced-usage/node-versions#uninstall

**Comment by sschlein** [comment]
Thanks, I'll update this in a minute!
