### ISSUE TITLE
[Bug]: Distorted icons in Sites

### ISSUE THREAD

**Issue by subdesign** [beyondcode/herd-community#822]
### Platform

macOS

### Operating system version

macOS Monterey 12.7.5

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.7.1 (Build 28)

### Bug description

The **Sites** page rows have an empty icon and a half-cutted icon at the right as you can see here:

<img width="844" alt="Screenshot 2024-06-18 at 15 12 43" src="https://github.com/beyondcode/herd-community/assets/691695/c68e0b9b-c08a-47dd-91b5-a18c0c2f9437">

I can not adjust the column width and I guess it should fit by default

my resolution: 1512x982

**Comment by sschlein** [comment]
What device is this? Montery is super old but based on your issue, you already run an Apple Silicon chipset and all of them get the latest versions of macOS.

We'll replace this sites view in in Herd 1.8, so it will fix itself but I am still interested why you're running a version that doesn't get official security updates anymore and that we don't test before releasing new versions.

**Comment by subdesign** [comment]
Hi, tbh I'm afraid of things will break if I upgrade to latest, and I use this M1 Pro machine for daily work, I don't have a 2nd computer to quickly change to. And a full install for me last days to reproduce corporate environment after base app installs and setup.
I have to collect more information about my system/apps if something breaks or not.
but thanks for the answer!

**Comment by sschlein** [comment]
Thanks for your answer! The new sites view will likely be released next week :)
