### ISSUE TITLE
[Bug]: Can not open Sublime from Sites

### ISSUE THREAD

**Issue by subdesign** [beyondcode/herd-community#823]
### Platform

macOS

### Operating system version

macOS Monterey 12.7.5

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.7.1 (Build 28)

### Bug description

In my previous issue I noted the half-cutted icon for _Open in IDE_ command, I created a separate issue for the problem of the button functionality.
My default IDE is set to Sublime, and can not select it when I click **Choose Application** button. It's greyed out.

<img width="373" alt="Screenshot 2024-06-18 at 15 33 23" src="https://github.com/beyondcode/herd-community/assets/691695/a32dc251-20e1-4e9e-bfb5-8c16b2b33c92">

---

<img width="638" alt="Screenshot 2024-06-18 at 15 14 32" src="https://github.com/beyondcode/herd-community/assets/691695/3230b0d5-e0bc-4d9a-aa87-e2127eb53c8f">

**Comment by sschlein** [comment]
It looks like Sublime Text removed (or changed) it's URL scheme and so that doesn't work anymore. You can use this and it will open files on the corect line from the log viewer but opening projects doesn't seem to work for me: https://github.com/inopinatus/sublime_url?tab=readme-ov-file

**Comment by subdesign** [comment]
thanks
