### ISSUE TITLE
[Bug]: Herd UI disappears from Mac Toolbar and Cannot Be Readded

### ISSUE THREAD

**Issue by mrpritchett** [beyondcode/herd-community#826]
### Platform

macOS

### Operating system version

macOS Sonoma 14.5 (23F79)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

Version 1.7.1

### PHP Version

PHP 8.2.8

### Bug description

I have been having trouble for a while now with the Herd icon disappearing from the Mac Toolbar. I've tried force quitting Herd and relaunching, restarting my machine, uninstalling and reinstalling Herd (which got it to reappear once before going back to the same behavior). 

### Steps to reproduce

Unclear unfortunately as no action on my part seemingly caused this.

**Comment by sschlein** [comment]
How many icons do you have in your toolbar? If the toolbar has too many icons on macos, they get pushed under the notch on MacBooks or sometimes just hidden. I recommend trying https://www.macbartender.com/ for managing this 🙂


![CleanShot 2024-06-20 at 16 58 51](https://github.com/beyondcode/herd-community/assets/2911113/0e07f242-6b8f-4889-a051-2390d932519e)

**Comment by mrpritchett** [comment]
@sschlein Not that many: 
<img width="658" alt="Screenshot 2024-06-20 at 11 03 04 AM" src="https://github.com/beyondcode/herd-community/assets/3329081/c8efca7f-a8c7-417d-96ed-8712722339ca">

**Comment by mrpritchett** [comment]
It's definitely not just hidden as the UI services that I've seen in Activity Monitor before when it has worked don't show up.

**Comment by mrpritchett** [comment]
So it magically reappeared after another reinstall. Waiting to see if it is permanently fixed.

**Comment by mrpritchett** [comment]
That's fair. One small ask- is there a way (or could one be added) to launch the GUI via the command line?

**Comment by RuanPienaarCode** [comment]
+1
