### ISSUE TITLE
[Bug]: Xdebug not working with PHPStorm

### ISSUE THREAD

**Issue by josephkerkhof** [beyondcode/herd-community#827]
### Platform

macOS

### Operating system version

macOS Sonoma 14.5

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.7.1 PRO

### PHP Version

PHP 8.3.8

### Bug description

I am not able to get Xdebug to trip for Laravel projects in my PHPStorm IDE.

I have configured PHPStorm to use the following PHP executable: `/Users/jkerkhof/Library/Application Support/Herd/bin/php83`

Things I've tried:
- I am making sure to hit Cmd + S before executing my web request (API requests via Bruno).
- Check the "detect breakpoints automatically" in Herd
- Turn on the "listen for PHP debug connections" in PHPStorm

Here is my CLI interpreter cofiguration:

![Screenshot 2024-06-20 at 10 34 49](https://github.com/beyondcode/herd-community/assets/5824820/4f27378d-7ed2-41c7-97bf-289e5e128935)

**Comment by sschlein** [comment]
Could you please copy the Xdebug configuration from your `debug.ini` that's in your Herd php config folder to your `php.ini` of the same folder just to see if it generally works? 

If that's the case we need to investigate why the automated breakpoint detection doesn't work.

**Comment by josephkerkhof** [comment]
Hi @sschlein, 

I have copied the `debug.ini` from `83/debug/debug.ini` to `83/php.ini` as seen in the screenshot.

<img width="888" alt="Screenshot 2024-06-20 at 11 28 56" src="https://github.com/beyondcode/herd-community/assets/5824820/15341bce-7b0a-4607-85c0-6cb2dd5aeb18">

This had no effect and xdebug still doesn't work.

**Comment by josephkerkhof** [comment]
<img width="1122" alt="Screenshot 2024-06-20 at 11 35 12" src="https://github.com/beyondcode/herd-community/assets/5824820/d042947e-d894-469c-8227-50620cef5aec">

Interestingly, my PHPStorm is following the `php-old.ini` file rename.

**Comment by josephkerkhof** [comment]
I have manually set the config file I want in PHPStorm and it still xdebug does not work.

<img width="1124" alt="Screenshot 2024-06-20 at 11 38 20" src="https://github.com/beyondcode/herd-community/assets/5824820/12a9bcbd-afa5-4537-a9ca-0ee4f2d09fa3">

**Comment by sschlein** [comment]
Can you restart all services in Herd? Your application is likely using an old php-form process that doesn't use Xdebug. 

Just to confirm: When you call your API, that's via http on a .test domain that Herd resolves?

**Comment by josephkerkhof** [comment]
I have restarted all services and still no catch on the xdebug breakpoint.

Yes, the API in my Bruno application is calling a site labeled `v3.test` which is a site running on Laravel Herd.

**Comment by josephkerkhof** [comment]
What is interesting is that if I put `/Applications/Herd.app/Contents/Resources/xdebug/xdebug-83-arm64.so` into my Debugger Extension in PHPStorm, the debugger trips on my tests (and only my tests, not web requests).
![Screenshot 2024-06-21 at 10 44 34](https://github.com/beyondcode/herd-community/assets/5824820/6f50468f-1a13-48d1-9cee-f115856e724e)

**Comment by rabol** [comment]
I have the same issue, Herd debugging does not work, and the documentation is less than perfect

**Comment by josephkerkhof** [comment]
Any update on this? Is this a known issue where Xdebug doesn't work with Herd Pro?

**Comment by mpociot** [comment]
What I do is configure a separate "Debug" interpreter that explicitly loads my debug.ini file.

![CleanShot 2024-08-09 at 12 08 15@2x](https://github.com/user-attachments/assets/2552ef88-0d2d-4473-8a2f-f204a7e518fc)

We are working with JetBrains to make this setup easier though!

**Comment by josephkerkhof** [comment]
@mpociot I'm not sure I understand.

I've added a CLI interpreter as you describe and I'm still not able to get PHP debug to trip on web requests. Are there any other steps you do to get it to work?

<img width="1097" alt="Screenshot 2024-08-14 at 09 34 46" src="https://github.com/user-attachments/assets/f8af0543-e34f-45cd-a9a9-2d2c5b3aecb7">
