### ISSUE TITLE
[Feature Request]: SQL Driver Support

### ISSUE THREAD

**Issue by josepueblaphcs** [beyondcode/herd-community#83]
### Feature Description

How can I put the sql driver on the php directory? I can't found it. Normally I put the drivers on wamp64/bin/php/php8.2.8/ext/php_sqlsrv_82_ts_x64.dll and then add it into the php.ini extensions configuration.

### Is this feature valuable for other users as well and why?

Yes, because some systems have not the typical database. So we need to adapt our application to the system.

**Comment by mpociot** [comment]
Could you please add your extension to #16?
