### ISSUE TITLE
[Bug]: The Laravel installer can't be updated

### ISSUE THREAD

**Issue by alexmanase** [beyondcode/herd-community#84]
### Operating system version

macOS Ventura 13.5

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.1.1 Build 12

### PHP Version

PHP 8.2.8 (cli) (built: Jul 28 2023 13:55:05) (NTS)

### Bug description

I tried to update the Laravel installer using composer and it didn't update the Laravel installer.

```bash
composer global update
```

I have to mention that the Laravel installer and Composer are used from Herd.

<img width="736" alt="image" src="https://github.com/beyondcode/herd-community/assets/10696975/9ca065e8-0226-4769-8008-a2fbaf687fc3">

### Steps to reproduce

1. `composer global update`
2. `laravel --version`

The `laravel` versions should be 5.0, but it's 4.5.

https://github.com/laravel/installer/releases/tag/v5.0.0

<img width="671" alt="image" src="https://github.com/beyondcode/herd-community/assets/10696975/30179df2-3bff-4f1c-bda8-8eb39d8d5002">

**Comment by mpociot** [comment]
This is because in your `~/.zshrc` file, the PATH of Herd is added _before_ your composer global directory.
We need to manually update the Laravel installer  as it dropped PHP < 8.1 support. Feel free to add your composer global bin path into your PATH first to fix this in the meantime.

**Comment by alexmanase** [comment]
Got it. I will wait until you update the Laravel installer from Herd.

Thanks!
