### ISSUE TITLE
[Bug]: Windows context menu regularly overlaps the Herd menu

### ISSUE THREAD

**Issue by Brugman** [beyondcode/herd-community#840]
### Platform

Windows

### Operating system version

Windows 10 Pro (22H2 19045.4529)

### System architecture

Windows

### Herd Version

1.8.0

### Bug description

Right-clicking the Herd icon in the systray to open the context menu seems to also open a Windows native context menu on top, about 3 out of 10 times. Enough to be annoying. Even if I click in the exact same spot. I'm not experiencing this with any other apps.

![2024-06-25-16-37-02](https://github.com/beyondcode/herd-community/assets/2203813/bd12bfe7-e710-4631-86a5-fc26352ae02a)

**Comment by Brugman** [comment]
Related: When inside the hidden icons list, I _cannot_ make the native context menu appear, but the Herd menu always appears behind the hidden icon list. This is the only app that does this.

![2024-06-25-17-12-42](https://github.com/beyondcode/herd-community/assets/2203813/14d7e31f-f0d7-4db1-b7a4-c46cd149feca)

**Comment by mpociot** [comment]
I'm unable to reproduce this error on my two Windows machines and on my VMs and I haven't seen other reports of this issue.
Maybe this is related to the specific Windows version?

**Comment by Brugman** [comment]
Both situations still happen today for me, but I understand if it can't be reproduced it can't be fixed.

Herd 1.9.0
Windows 10 Pro 22H2 19045.4651
