### ISSUE TITLE
[Bug]: Sites menu item gone and clicking open sites list link in shortcuts returns error: invalid shortcut please choose another one

### ISSUE THREAD

**Issue by malantech** [beyondcode/herd-community#841]
### Platform

Windows

### Operating system version

Windows 11

### System architecture

Windows

### Herd Version

1.8.0

### PHP Version

PHP 8.2

### Bug description

Sites menu item gone and clicking open sites list link in shortcuts returns error: invalid shortcut please choose another one

Also, I have the pro license FYI

### Steps to reproduce

Sites menu item gone and clicking open sites list link in shortcuts returns error: invalid shortcut please choose another one

**Comment by sschlein** [comment]
You can open the sites from the dashboard or the system tray

**Comment by malantech** [comment]
Found an Open Sites button on the dashboard that wasn't there which opened sites if the shortcuts link and key combo doesn't work: 
![image](https://github.com/beyondcode/herd-community/assets/37876322/b48b15a4-19a9-4730-9dd7-810722cfce74)

**Comment by sschlein** [comment]
I apologize for bad change UX, we'll update Herd with a sites settings item that explains the change and fix the shortcut
