### ISSUE TITLE
[Bug]: The dumps window cannot be moved and the search bar is partially hidden

### ISSUE THREAD

**Issue by sbc640964** [beyondcode/herd-community#843]
### Platform

Windows

### Operating system version

Windows 11

### System architecture

Windows

### Herd Version

1.8

### PHP Version

php 8.2.20

### Bug description

Dumps window:

1. The window cannot be dragged
2. The search field is partially covered
![image](https://github.com/beyondcode/herd-community/assets/46646044/71e5a53f-35de-4fa4-a195-59e17b291b40)

**Comment by mechelon** [comment]
Which language have you set as display language in Windows?

**Comment by sbc640964** [comment]
@mechelon T.Y.
