### ISSUE TITLE
[Bug]: Mail cannot start

### ISSUE THREAD

**Issue by rabol** [beyondcode/herd-community#845]
### Platform

macOS

### Operating system version

macos v14.5

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.71 build 8

### PHP Version

8.3.8

### Bug description

Mail server will not start

### Steps to reproduce

start herd, and go to meail

### Relevant log output

```shell
Port 2525 is free. Starting mailserver.
Mailserver listening on port 2525
node:events:515
      throw er; // Unhandled 'error' event
      ^

Error: WebSocket was closed before the connection was established
    at WebSocket.close (/snapshot/herd-mailserver/node_modules/ws/lib/websocket.js:292:7)
    at ReconnectingWebSocket._disconnect (/snapshot/herd-mailserver/node_modules/reconnecting/dist/reconnecting-websocket-cjs.js:541:22)
    at ReconnectingWebSocket._handleError (/snapshot/herd-mailserver/node_modules/reconnecting/dist/reconnecting-websocket-cjs.js:180:19)
    at ReconnectingWebSocket._handleTimeout (/snapshot/herd-mailserver/node_modules/reconnecting/dist/reconnecting-websocket-cjs.js:531:14)
    at Timeout.<anonymous> (/snapshot/herd-mailserver/node_modules/reconnecting/dist/reconnecting-websocket-cjs.js:526:75)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
Emitted 'error' event on WebSocket instance at:
    at emitErrorAndClose (/snapshot/herd-mailserver/node_modules/ws/lib/websocket.js:1033:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Node.js v18.5.0
```

**Comment by sschlein** [comment]
Could you check if the debug API port is working and the status is green? We also use this port for the communication between mailserver and Herd and this might be the issue.

![CleanShot 2024-06-27 at 15 02 19](https://github.com/beyondcode/herd-community/assets/2911113/fa6c663c-9dbc-4142-a162-e87a99d5b1a6)

**Comment by rabol** [comment]
Not sure how I should check that - as you can see in the screenshot, the port 2525 is 'free'.

Dump server port is green, when this happens

**Comment by rabol** [comment]
if you use another port than you check, then you should try/catch and give a proper error messages

**Comment by sschlein** [comment]
We checked every possible bit of the code this morning and there are try-catch blocks everywhere – so it's an internal issue of a library that we are using. 

Did you try changing the port for dumps, even if it's green?

We'll improve the error messages in a future update!

**Comment by sschlein** [comment]
What happens if you do?

**Comment by rabol** [comment]
nothing

**Comment by sschlein** [comment]
Still the same error when you open the mails window?

**Comment by rabol** [comment]
I have uninstalled Herd

**Comment by sschlein** [comment]
Please send me an email to support@beyondco.de to get a refund. Just using your email address that you used for the purchase is fine and doesn't need to have more text.

**Comment by rabol** [comment]
not needed... I assume that the product will get fixed and improved in the future

**Comment by rabol** [comment]
just a small note: I reinstalled a 'old intel mbp, running macos 12.7.5' and then the only thing i installed was vscode and herd... everything was working for a few days, but all the sudden, sites will not open unless I add ssl, the mail server does not start unless I manually select a new port e.g. 2526 then it starts and then I can set the port back to 2525.
There is no - obvious - button or link on the sites list to open in IDE

**Comment by rabol** [comment]
I finally made it work :)

**Comment by stefro** [comment]
> I finally made it work :)

Hi @rabol, I have the same issue. Can you share how you fixed it?
