### ISSUE TITLE
[Bug]: Log files do not open: spinning beachball of death :-)

### ISSUE THREAD

**Issue by joostvanhoof** [beyondcode/herd-community#847]
### Platform

macOS

### Operating system version

macOS Sonoma 14.5 (23F79)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.7.1

### PHP Version

PHP 8.3

### Bug description

**The context**
My assumption is that somewhere in my code there is an infinite loop, however I'm not sure. After the max execution time my app crashes. Any page I visit after that doesn't work, no error info is displayed (I have `APP_DEBUG=true`) but the netwerk console indicates a 500 error. Given Laravel does not indicate anything, I wanted to check the PHP and nginx logs.

**The Herd part**
If I click on the Herd icon in the menu bar and then click on Logs, I get the macOS spinning beachball. If I wait long enough, occasionally I get macOS permission alerts asking 'Would you like to give Herd access to X' where for X I've seen 'Other documents', 'Reminders', 'Downloads' so various different things where some seem unrelated to Herd (eg: Reminders). The logs never open so there seems to be something wrong there.

**Comment by sschlein** [comment]
Fixed in 1.8
