### ISSUE TITLE
[Bug]: Herd is recursively adding sites by directory

### ISSUE THREAD

**Issue by josephkerkhof** [beyondcode/herd-community#849]
### Platform

macOS

### Operating system version

macOS Sonoma 14.5

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.7.1 PRO

### PHP Version

PHP 8.3.8

### Bug description

![Screenshot 2024-06-27 at 07 43 24](https://github.com/beyondcode/herd-community/assets/5824820/37a0b17e-aeef-4aaa-b610-b56725e31ebc)

When adding a directory in Herd paths, Herd recursively adds Laravel project sub-directores as separate sites. I expect only the root of the project to be added as a valid site in Herd.

**Comment by mpociot** [comment]
This is how Herd paths work - it makes all subfolders available as sites.

So in your case, if you would only add the `~/code/jamfluencer` folder, it would add `jam-api.test` as well as other projects that are in this directory.

We're going to release an update with a refreshed sites UI to make linking existing sites clearer

**Comment by josephkerkhof** [comment]
I see, so it's not recursively adding sites, it's just adding one folder level deeper. Thanks for the quick answer!
