### ISSUE TITLE
[Bug]: Ports already in use

### ISSUE THREAD

**Issue by shealan** [beyondcode/herd-community#85]
### Operating system version

macOS Venture 13.4.1 (c)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.1.1 (Build 12)

### Bug description

Fresh Herd install on my system that was previously using Valet. Valet was detected by Herd and I was taken through the migration screens.

Herd is running but the NGINX item in the menubar dropdown is not green, nor is DNSmasq.

Is there something else from my previous installation I need to remove? A reboot didn't change anything.

My sites do seem to work though... would be nice to go all in on Herd though to ensure a more predictable environment.

### Relevant log output

```shell
NGINX log output:
```

![image](https://github.com/beyondcode/herd-community/assets/74932/95409e88-f1c1-4aea-8675-91de55962b72)

```shell
DNSMarq log output:
```

![image](https://github.com/beyondcode/herd-community/assets/74932/d74c3545-7b53-44aa-9bdd-472f268d2a74)

**Comment by mpociot** [comment]
Looks like you still have DNSMasq and nginx running from brew.
Try stopping it manually using sudo.

`sudo brew services stop dnsmasq`
`sudo brew services stop nginx`

**Comment by shealan** [comment]
Thanks @mpociot that sorted it
