### ISSUE TITLE
[Bug]: PostgesSQL v16: type "geography" does not exist.

### ISSUE THREAD

**Issue by boxybird** [beyondcode/herd-community#851]
### Platform

Windows

### Operating system version

Windows 11 (23H2 22631.3737)

### System architecture

Intel (x86)

### Herd Version

1.8.0

### PHP Version

PHP 8.2

### Bug description

Using PostgesSQL v16, I get the following error on migration:

`SQLSTATE[42704]: Undefined object: 7 ERROR:  type "geography" does not exist at character 669 (SQL: create table "services"...` when using `$table->geometry('the_geom')->nullable();`

Review the Herd release notes I saw "PostgreSQL 14, 15 and 16 are now available including PostGIS and pgrouting extensions".

I could be mistaken, but I thought these extensions covered the "geography" type, right?

### Steps to reproduce

Use PostgesSQL v16, create a migration, and use the column type `$table->geometry('the_geom')->nullable();`.

**Comment by mpociot** [comment]
Did you activate the extensions by running 

CREATE EXTENSION postgis;

in your database?

**Comment by boxybird** [comment]
That did the trick, thank you! I must have missed that step in the docs.
