### ISSUE TITLE
[Bug]: Values set in php.ini files are NOT respected in PHP FPM, no custom config can be set

### ISSUE THREAD

**Issue by aj-adl** [beyondcode/herd-community#857]
### Platform

macOS

### Operating system version

macOS Monterey 12.6 (21G115)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

Version 1.8.0 (Build 29)

### PHP Version

All PHP Versions

### Bug description

If you read the comments of #675 you will see many people reporting the same issue - Herd does NOT respect the values set in any of the php.ini files. The original issue was not related to this, and also the title is misleading to the issue.

The files are at `/Users/{$USER}/Library/Application Support/Herd/config/php/{$VERSION}/php.ini`, clicking "Open Configuration Files" takes you there, the loaded configuration when running `phpinfo()` states they are being loaded, eg

Configuration File (php.ini) Path | /lib
-- | --
Loaded Configuration File | /Users/dev/Library/Application Support/Herd/config/php/83/php.ini

https://share.zight.com/nOu77pr9

In these PHP files I am trying to change some settings such as `max_memory_limit`, `max_input_vars` (critical for running any decent size craft sites) etc

When running commands such as `herd php -i` it will print out the values from my `php.ini` file.

When actually running the app (ie: in the browser, using PHP FPM) it will NOT load or utilise any of those values - 
Here's the results of phpinfo() https://share.zight.com/2Nu88xDN
Here's the `php.ini` file https://share.zight.com/E0uee8QJ

This is basically a "we're f**ked until this is fixed" issue for us, as a person that bought a team license and has my whole team using this for local environments, it's not a good time.

### Steps to reproduce

- Install Herd.
- Make a change to the `php.ini` file for your current global version of PHP
- Run `herd php -i` and check the value, it will be correct
- Create a php file that calls `phpinfo()` in the browser served via herd, these values will be incorrect

**Comment by aj-adl** [comment]
Hi @mpociot thanks for the speedy response! 

Yes, I've restarted herd multiple times, via both GUI and CLI to see if that helped.

https://share.zight.com/8LuNNdxm for a video of what is happening to me!

**Comment by mpociot** [comment]
Could you try and hold the "option" key while clicking on the Herd menubar icon?
It might happen that there's a leftover FPM service, which would not get restarted properly

By holding the option key, you will see a "Force stop all" entry. Please try force-stopping all services and then starting them again to see if this fixes your issue.

If that does not work either, maybe we can jump on a quick Tuple/Google Meet/whatever call, so I can see what's causing this issue for you.

**Comment by aj-adl** [comment]
Hi @mpociot - this has fixed the issue, thank you very much! 

For additional context, we were running Laravel Valet before we switched to Herd, is it possible there's something we need to clean up there? Just wondering if some old config is going to relaunch Valet's PHP-FPM on restart etc

**Comment by mpociot** [comment]
Usually there's nothing that should be cleaned up 🤔 
Not sure what caused this, but great to hear that this fixed it for you!
