### ISSUE TITLE
[Bug]: Secured Site is "unsafe" according to browser

### ISSUE THREAD

**Issue by Mavv3006** [beyondcode/herd-community#863]
### Platform

Windows

### Operating system version

Windows 11 22631.3810

### System architecture

Intel (x86)

### Herd Version

1.8.0

### PHP Version

PHP 8.3.8 (cli) (built: Jun  4 2024 18:52:26) (NTS Visual C++ 2019 x64)

### Bug description

When I secure a site with Herd and open it in a browse afterwards, I get an SEC_ERROR_UNKNOWN_ISSUER (Firefox) / NET::ERR_CERT_AUTHORITY_INVALID (Chrome) error. It seems like Firefox and Chrome do not trust the Laravel Valet certificate

![grafik](https://github.com/beyondcode/herd-community/assets/52504463/fea65202-413a-4287-b8ef-51fe5f2c16af)

### Steps to reproduce

- secure a site with Herd
- open the site in Firefox or Chrome

**Comment by samtlewis** [comment]
Seeing the same issue on Mac version of Herd as well. This is with sites that were previously working just fine. Not sure if it is related to the latest Herd update or not but the NET::ERR_CERT_AUTHORITY_INVALID error is identical.

**Comment by mpociot** [comment]
I'm pretty sure that this is related to some weird Chrome related caching issues as it's not a general error with Herd / securing sites.
