### ISSUE TITLE
mysql 

### ISSUE THREAD

**Issue by kemaloskan** [beyondcode/herd-community#866]
### Platform

macOS

### Operating system version

macOS

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.8.0 build29

### Bug description

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'myname.sessions' doesn't exist (Connection: mysql, SQL: select * from `sessions` where `id` = Wx4Kkb6jnSG4Wj9INXI8gtBYXLQPKgx1q77pjxAK limit 1)[Bug]: 

### Steps to reproduce

I want mysql settings to come automatically in new site setup

### Relevant log output

```shell
I want mysql settings to come automatically in new site setup
```

**Comment by sschlein** [comment]
If you create a new site via Herd, it automatically uses SQLite at the moment. The Laravel installier that we use for project creating does not support selecting mysql and running the migration via a feature flag.

So please run the installer yourself via `laravel new PROJECTNAME` in your terminal when using MySQL or add this configuration within the project yourself later 🙂
