### ISSUE TITLE
[Bug]: Links on Windows Page opens up MacOS Documentation

### ISSUE THREAD

**Issue by hebbet** [beyondcode/herd-community#868]
### Platform

Windows

### Operating system version

Windows 11 24H2 26120.770

### System architecture

Windows

### Herd Version

1.8.0

### PHP Version

8.3.9

### Bug description

In FAQ on [Windows page](https://herd.laravel.com/windows) you have some links to docs.

 manually compile and install additional PHP extensions should go to https://herd.laravel.com/docs/windows/1/advanced-usage/additional-extensions instead of https://herd.laravel.com/docs/1/advanced-usage/additional-extensions

However, the official documentation will get you a long way in understanding all additional features. should go to https://herd.laravel.com/docs/windows

### Steps to reproduce

open FAQ on https://herd.laravel.com/windows

**Comment by sschlein** [comment]
Fixed and will be deployed later today :)
