### ISSUE TITLE
[Bug]: Statamic Driver not used

### ISSUE THREAD

**Issue by marcorieser** [beyondcode/herd-community#869]
### Platform

macOS

### Operating system version

macOS Sonoma Version 14.5 (23F79)

### System architecture

Intel (x86)

### Herd Version

1.8.0 (Build: 29)

### Bug description

When running `herd which` in a Statamic project the output is `Valet\Drivers\LaravelValetDriver` but it should be `Valet\Drivers\StatamicValetDriver`. The issue https://github.com/beyondcode/herd-community/issues/812 says that it's fixed but it still seems unresolved.

### Steps to reproduce

- Install a Statamic project (https://statamic.dev/installing/laravel-herd#create-a-new-site)
- Open the project in terminal
- Run `herd which`

**Comment by sschlein** [comment]
@marcorieser Could you please check if this also happens with Herd 1.9? I checked the Herd code and also run `herd which` on my machine and got the correct Statamic driver

**Comment by marcorieser** [comment]
> @marcorieser Could you please check if this also happens with Herd 1.9? I checked the Herd code and also run `herd which` on my machine and got the correct Statamic driver

Seems resolved. Thanks.
