### ISSUE TITLE
[Bug]: SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by mikerockett** [beyondcode/herd-community#87]
### Operating system version

macOS Ventura 13.4 (22F66)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.1.1

### PHP Version

PHP 8.2.8 (cli) (built: Jul 28 2023 13:55:05) (NTS)

### Bug description

I am running Laravel WebSockets, and when I attempt to broadcast a message from the backend, I receive this error:

> cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://[REDACTED].test:6001/apps/[REDACTED]/events?auth_key=[REDACTED]&auth_timestamp=1690963814&auth_version=1.0&body_md5=[REDACTED]&auth_signature=[REDACTED]

I adjusted the installation to use the certificates that Herd uses to serve the domain, ie those that were moved across from Valet (in my case), thinking that it would solve the issue.

**Comment by mpociot** [comment]
Could you please verify that `php82 --ini` points to the correct php.ini files?

**Comment by mikerockett** [comment]
@mpociot Sure:

```
$ php82 --ini
Configuration File (php.ini) Path: /lib
Loaded Configuration File:         (none)
Scan for additional .ini files in: /Users/mikerockett/Library/Application Support/Herd/config/php/82/
Additional .ini files parsed:      /Users/mikerockett/Library/Application Support/Herd/config/php/82/php.ini
```

**Comment by mikerockett** [comment]
Sorry, I know what the issue is. I have kept Valet installed, and my env runner (porter) is pointing to Valet’s PHP (strange that it runs as I uninstalled all PHP versions from Homebrew).

**Comment by mikerockett** [comment]
Update: Still getting the error after switching to Herd’s PHP.

**Comment by mikerockett** [comment]
@mpociot I've disabled `client_options.verify` in broadcasting for the time being. But not sure how to fix this – might try find some time this weekend to dig a bit more.
