### ISSUE TITLE
[Bug]: Failed to open stream: Operation not permitted

### ISSUE THREAD

**Issue by pixelastronauts** [beyondcode/herd-community#870]
### Platform

macOS

### Operating system version

macOS Sonoma 14.5

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.8.0 (Build: 29)

### Bug description

We've just upgraded to the latest version and started receiving this fatale error on a couple of projects. It seems to be affecting older projects that are imported from Valet, not the new projects.

```
Warning: require(/Users/maxbaan/Documents/Snkrfndr/public/index.php): Failed to open stream: Operation not permitted in /Applications/Herd.app/Contents/Resources/valet/server.php on line 155

Fatal error: Uncaught Error: Failed opening required '/Users/maxbaan/Documents/Snkrfndr/public/index.php' (include_path='.:') in /Applications/Herd.app/Contents/Resources/valet/server.php:155 Stack trace: #0 {main} thrown in /Applications/Herd.app/Contents/Resources/valet/server.php on line 155
```

I've been tinkering around for about a hour to figure what is happening, but can't seem to find the problem. Things I've tried:

- Reinstalling PHP
- Different PHP versions
- Restarting services

**Comment by mpociot** [comment]
The "Operation not permitted" error indicates that this must come from macOS permissions.
As your sites are located in your "Documents" folder, please make sure that Herd and the Herd helper are allowed to access these folders.

Open "System Settings" and go to "Privacy & Security" -> "Files and Folders".

Both "de.beyondco.herd" (which is Herd's helper tool) as well as "Herd" itself need permissions to access the Documents folder in your case.

**Comment by pixelastronauts** [comment]
The "Herd" application has access to the 'Documents' folder. Also other projects also in the 'Documents' folder are working.

Also I can't seem to find the "de.beyondco.herd" helper tool in the "Files and folders" settings.

**Comment by mpociot** [comment]
Oh, interesting that it only affects some projects.
If you have a minute to jump on a quick Google meet call, I'd love to check it out so we can fix this 
https://meet.google.com/vxy-iwex-fmz

**Comment by pixelastronauts** [comment]
I will mark this as resolved since using "Force Stop All" (option + Stop all) fixed the issues. Another underlying problem was that the main project folder was included in the "Herd paths".

Thanks for the quick help @mpociot 💪
