### ISSUE TITLE
[Bug]: Dump going to response body

### ISSUE THREAD

**Issue by swarley** [beyondcode/herd-community#873]
### Platform

macOS

### Operating system version

macOS Sonoma 14.5

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.9.1

### Bug description

When using `dump` (not `dd`) the dump is being prepended to the response body and not going to the dump window. This was working fine prior to updating (I assume version 1.6). Confirmed with other members of my team with the same operating system and herd versions

### Steps to reproduce

<img width="527" alt="image" src="https://github.com/beyondcode/herd-community/assets/822067/5ff41008-2607-4b9e-ab57-d0d57310fe73">

```php

$routes->get('dump-check', static function () {
    dump('foo');

    return response('hello world', 200);
});

```

**Comment by sschlein** [comment]
@swarley What happens if you toggle dump interception in the dump window? Are the dumps still not picked up but be visible in the browser?

**Comment by mirceasoaica** [comment]
I have the same issue (same OS and Herd version). 

Nothing happens after toggling the interception. Dumps are going to the response body still. 

I've also tried restarting Herd.

**Comment by sschlein** [comment]
Could you post your related php.ini here? Does changing from PHP 8.3 to 8.2 and back to 8.3 again (or different versions)

There seems to be a problem with the dump loader.

**Comment by mirceasoaica** [comment]
Changing the PHP versions doesn't do anything. 

Here's my php.ini config for PHP 8.3
```
curl.cainfo=/Users/mircea/Library/Application Support/Herd/config/php/cacert.pem
openssl.cafile=/Users/mircea/Library/Application Support/Herd/config/php/cacert.pem
pcre.jit=0
max_input_vars=9999999
memory_limit=256M
upload_max_filesize=10M
auto_prepend_file=/Applications/Herd.app/Contents/Resources/valet/dump-loader.php
```

**Comment by mpociot** [comment]
@mirceasoaica I know this issue has been open for a while but have you tried to force-stop the existing services?
When Herd adds the auto_prepend_file to your php.ini, FPM needs to be restarted in order for these changes to take effect.
Maybe the service was somehow "stuck".
