### ISSUE TITLE
[Bug]: bad pattern in zshrc.zsh

### ISSUE THREAD

**Issue by linbaird** [beyondcode/herd-community#876]
### Platform

macOS

### Operating system version

MacOS 13.6.7

### System architecture

Intel (x86)

### Herd Version

1.9.1

### PHP Version

8.2

### Bug description

.zshrc:15: bad pattern: /Applications/Herd.app/Contents/Resources/config/shell/zshrc.zsh[

Updated to Herd Pro and version to latest.

### Steps to reproduce

This is the line causing issues in the .zshrc
[[ -f "/Applications/Herd.app/Contents/Resources/config/shell/zshrc.zsh" ]] && builtin source "/Applications/Herd.app/Contents/Resources/config/shell/zshrc.zsh"[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

**Comment by mpociot** [comment]
Maybe this is a bug with zsh on macOS 13.6

Could you tell me your zsh version when you run `zsh --version`?

You can fix this by manually commenting the line in your zshrc file

**Comment by mpociot** [comment]
Oh indeed, looks like the `[-s` part needs to be on its own line.

**Comment by linbaird** [comment]
Great! This fixed the issue, thank you.

**Comment by casperxs** [comment]
GReat its works for me!!!! thx


> ![CleanShot 2024-08-13 at 09 38 08](https://github.com/user-attachments/assets/327dfffc-5aac-4ba8-9b26-342d47c925d5)
> 
> I encountered the same problem, and the solution was simply to add a line break.
