### ISSUE TITLE
[Bug]: dial tcp: lookup artmesv3.test on 127.0.0.11:53: no such host

### ISSUE THREAD

**Issue by Neamix** [beyondcode/herd-community#877]
### Platform

Windows

### Operating system version

Windows 11

### System architecture

Windows

### Herd Version

1.8

### PHP Version

php 8.3

### Bug description

I am getting dial tcp: lookup artmesv3.test on 127.0.0.11:53: no such host in the browser

### Relevant log output

```shell
dial tcp: lookup artmesv3.test on 127.0.0.11:53: no such host
```

**Comment by Neamix** [comment]
![image](https://github.com/user-attachments/assets/6fe37289-a960-429e-b559-089c21e1a0c7)

**Comment by sschlein** [comment]
This doesn't seem to be related to Herd but to your application. There seems to be an issue with 127.0.0.1 (there is 127.0.0.11 mentioned. Herd doesn't use port 53, so that's something on your machine or app.
