### ISSUE TITLE
[Bug]: Xdebug keeps opening dump-loader.php on every request

### ISSUE THREAD

**Issue by joshwegener** [beyondcode/herd-community#878]
### Platform

macOS

### Operating system version

macOS Sonoma 14.4.1

### System architecture

Intel (x86)

### Herd Version

1.9.1 (Build: 31)

### PHP Version

PHP 8.3.6 (cli) (built: Apr 10 2024 14:21:20)

### Bug description

Whenever I run any cli command, Xdebug opens in PHPStorm in "dump-loader.php" on line `require_once __DIR__ . '/HerdConfiguration.php';` and I must click "play" to move on. There are no breakpoints here, not sure what is causing the issue.

### Steps to reproduce

- Fresh install of herd
- run any cli command

**Comment by sschlein** [comment]
You can configure this in PHPStorm:
![6c7c0221ad8f98ecf87a23042fbca551](https://github.com/user-attachments/assets/95607c7d-2121-4376-9091-5cbf3eec87ed)
