### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by dcoderk** [beyondcode/herd-community#880]
### Platform

Windows

### Operating system version

Windows 11

### System architecture

Intel (x86)

### Herd Version

1.8.0

### PHP Version

8.3.3

### Bug description

Trying to create laravel app but i'ts not working

  Creating a "laravel/laravel" project at "./example"
    Installing laravel/laravel (v11.1.3)
    Failed to download laravel/laravel from dist: The zip extension and unzip/7z commands are both missing, skipping.
The php.ini used by your command-line PHP is: C:\Program Files\php-8.3.3\php.ini
    Now trying to download from source
  - Syncing laravel/laravel (v11.1.3) into cache
      - Installing laravel/laravel (v11.1.3): Cloning 69917ece2c
        Install of laravel/laravel failed

In Git.php line 473:

  Failed to clone https://github.com/laravel/laravel.git via https, ssh protocols, aborting.

  - https://github.com/laravel/laravel.git
    Cloning into 'C:\Users\Jay\Herd\example'...
    error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)
    error: 7456 bytes of body are still expected
    fetch-pack: unexpected disconnect while reading sideband packet
    fatal: early EOF
    fatal: fetch-pack: invalid index-pack output

  - git@github.com:laravel/laravel.git
    Cloning into 'C:\Users\Jay\Herd\example'...
    Host key verification failed.
    fatal: Could not read from remote repository.

    Please make sure you have the correct access rights
    and the repository exists.

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--add-repository] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--remove-vcs] [--no-install] [--no-audit] [--audit-format AUDIT-FORMAT] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--ask] [--] [<package> [<directory> [<version>]]]

### Steps to reproduce

laravel new example

### Relevant log output

```shell
Creating a "laravel/laravel" project at "./example"
    Installing laravel/laravel (v11.1.3)
    Failed to download laravel/laravel from dist: The zip extension and unzip/7z commands are both missing, skipping.
The php.ini used by your command-line PHP is: C:\Program Files\php-8.3.3\php.ini
    Now trying to download from source
  - Syncing laravel/laravel (v11.1.3) into cache
      - Installing laravel/laravel (v11.1.3): Cloning 69917ece2c
        Install of laravel/laravel failed

In Git.php line 473:

  Failed to clone https://github.com/laravel/laravel.git via https, ssh protocols, aborting.

  - https://github.com/laravel/laravel.git
    Cloning into 'C:\Users\Jay\Herd\example'...
    error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)
    error: 7456 bytes of body are still expected
    fetch-pack: unexpected disconnect while reading sideband packet
    fatal: early EOF
    fatal: fetch-pack: invalid index-pack output

  - git@github.com:laravel/laravel.git
    Cloning into 'C:\Users\Jay\Herd\example'...
    Host key verification failed.
    fatal: Could not read from remote repository.

    Please make sure you have the correct access rights
    and the repository exists.


create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--add-repository] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--remove-vcs] [--no-install] [--no-audit] [--audit-format AUDIT-FORMAT] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--ask] [--] [<package> [<directory> [<version>]]]
```

**Comment by sschlein** [comment]
It looks like you have a different php binary in your environment PATH variable that is not from herd but from `C:\Program Files\php-8.3.3`

Please make sure to remove that or sort your environment variables in a way that your command line uses Herd instead of this setup and it'll work.
