### ISSUE TITLE
[Bug]: macOS Sequoia (Beta 3) No GUI/MenuBar Icon available.

### ISSUE THREAD

**Issue by Marceswan** [beyondcode/herd-community#881]
### Platform

macOS

### Operating system version

macOS Sequoia 15 (24A5289g)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.9.1, 1.8.0 (Tested on both)

### Bug description

Upon installing Herd on macOS Sequoia I noticed the GUI and Menu Bar icon were available during the initial install process, however, this is no longer the case. I can interact with Herd via terminal, but I do not have access to any of the GUI assets while Herd is running. 

I have confirmed this issue on 2 separate Mac computers. Mac Studio (M1 Ultra), and MacBook Pro (M1 Pro). 

The log folder contains only empty files.

**Comment by Marceswan** [comment]
Confirmed the Sequoia Beta 3 refresh build (24A5289h) still does not allow GUI assets to initialize. 

Terminal access is still available. :)

**Comment by mpociot** [comment]
I just tried this again on Beta 5 and it's looking good there 👍 

<img width="855" alt="image" src="https://github.com/user-attachments/assets/d8f63b29-45ab-4503-b3e2-33675cec6ef0">
