### ISSUE TITLE
[Bug]: IDE cannot be started from sites list (mentioned in General settings)

### ISSUE THREAD

**Issue by rlb222** [beyondcode/herd-community#884]
### Platform

macOS

### Operating system version

Mac Sonoma 14.5

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.9.1 Build 31

### Bug description

I cannot open the IDE from the sites list, as mentioned in General Settings.

<img width="489" alt="image" src="https://github.com/user-attachments/assets/d1eee8a3-6466-461e-98bd-b427e0527d84">

### Steps to reproduce

Create a Site, choose vscode as the IDE in Settings/General
go to Sites list and look for a way to start the IDE.

**Comment by sschlein** [comment]
What happens when you click this link? [vscode://file/bla](vscode://file/bla)

It sounds like your Mac does not support the URL scheme of VS Code

**Comment by rlb222** [comment]
I think the url scheme is working.
When I click the link, I get this. Seems ok to me.

￼



When I click 
1. On the preview -> nothing
2. On the URL -> Finder opens in the correct place
3. Tinker -> not installed so error in Terminal

The fastest option to opening vscode with the correct files is [Open] the Terminal and type ‘herd edit’.
But nothing I found would open the editor directly. 

￼

**Comment by rlb222** [comment]
Hai Sebastian, 
Small correction, not URL but Path: 
I meant 
2. when I click on the Path -> no Editor opens, just the Finder in the right folder.

(Also I tried all these fields with right click, but also no response).

Thanks for looking into this!
René

￼

**Comment by sschlein** [comment]
I can't see your images but assume that you are using the site UI. The click on the path opens the Finder on purpose and there is no button to open the IDE at the moment. I already run a future version of Herd and we've implemented an IDE button there – so it's on the roadmap but I am not sure it it will be in Herd 1.10 or 1.11 :)

**Comment by rlb222** [comment]
That clears the confusion!
(I’m talking about the sentence underneath the Settings/General/IDE field that says you can open the IDE on the Sites List)


Thank you!
I will wait for it :) 
René

**Comment by rabol** [comment]
same issue here, no way to open in IDE

**Comment by philippe2463** [comment]
I have the same problem. MacOs and Vscode
The herd edit command works

<img width="1033" alt="Image" src="https://github.com/user-attachments/assets/c12fc220-232f-4803-bc8c-59605f925180" />
<img width="1127" alt="Image" src="https://github.com/user-attachments/assets/12d69d2e-a61a-45e9-b569-ec4be26f6451" />
