### ISSUE TITLE
[Bug]:  UI shows site as unsecured, when terminal command shows it as secured

### ISSUE THREAD

**Issue by sammyaxe** [beyondcode/herd-community#887]
### Platform

macOS

### Operating system version

macOS Sanoma 14.4 23E214

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.9.1

### Bug description

Sites show up as secure while running ```herd links```

<img width="114" alt="Screenshot 2024-07-16 at 10 08 44 PM" src="https://github.com/user-attachments/assets/eb6ccb75-01a5-481e-a93a-2b5a62acae7b">

In UI they show up as unsecured, even though they actually are secure and I'm not sure how to force update this

<img width="40" alt="Screenshot 2024-07-16 at 10 09 28 PM" src="https://github.com/user-attachments/assets/99926ccd-9a5a-44b9-9e1a-b68653164fba">

### Steps to reproduce

Not sure if this happens to anyone else, seems pretty random.

**Comment by taivu** [comment]
im also seeing unsecure (disabled) in UI, but in command line SSL column has an X (enabled).
