### ISSUE TITLE
[Bug]: Site missing in UI

### ISSUE THREAD

**Issue by Stevenking1981** [beyondcode/herd-community#890]
### Platform

Windows

### Operating system version

Windows 11 23H2 (Build 22631.3880)

### System architecture

Intel (x86)

### Herd Version

1.9.0

### Bug description

In the left navigationbar the Site tab is missing.

![grafik](https://github.com/user-attachments/assets/306b277a-b313-4859-9ad4-1cf16abc716d)

**Comment by sschlein** [comment]
You can access the site manager via the button on the dashboard or doing a right click on the system tray icon and selecting "sites"
