### ISSUE TITLE
[Bug]: Blank page when share using expose on other gadget like handphone and tablet

### ISSUE THREAD

**Issue by jonathanoeijoeng** [beyondcode/herd-community#892]
### Platform

macOS

### Operating system version

macOS Sonoma 14.5

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.9.1

### Bug description

Blank page when access from other gadget like handphone and tablet. Favicon already showed up but page is only blank.
Seems ok when using own laptop.

### Steps to reproduce

I use expose share, herd share, expose share http://sim-hospital.test but all give blank page

**Comment by jonathanoeijoeng** [comment]
I manage to open it on another laptop and got this error on the console 
![image](https://github.com/user-attachments/assets/78ac5358-098c-46ed-8190-c4614417d7fa)

**Comment by mpociot** [comment]
This is an issue related to using Expose in combination with Vite's dev server.
To fix this, please build your assets using `npm run build`
