### ISSUE TITLE
Access denied for user (Service MySql)

### ISSUE THREAD

**Issue by MightyPete** [beyondcode/herd-community#895]
### Platform

macOS

### Operating system version

macOS Sonoma 14.5

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.9.1

### PHP Version

Php 8.3

### Bug description

The problem happens to me that when I restart my mac or log out and the herd service starts, it stops working and I have to delete the service and recreate it for it to work but I have to import the data again.

### Steps to reproduce

[Bug]: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) 

### Relevant log output

```shell
SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)
```

**Comment by sschlein** [comment]
What happens if you run `brew services list` ?

I am pretty sure that there is an additional MySQL instance running and you are trying to connect to this one instead of the one by Herd. You can also create you Herd MySQL instance on a different port so that they can co-exists with each other and this shouldn't happen again :)

**Comment by zerocool-network** [comment]
![image](https://github.com/user-attachments/assets/3b02b756-42ca-4213-92ff-9d5e6e07ea13)
this happens to me

**Comment by sschlein** [comment]
That's good – but there's likely a different MySQL instance running that has a different password, so if you had MySQL installed differently before, it is a good idea to use a different port for the Herd MySQL instance so that you can be sure that it's different and we can see if this problem still happens when you change the port. I can't come up with a reason why there would be a password, there's no code in Herd that sets one.

**Comment by MightyPete** [comment]
You know, I have done this by changing the port and the same thing happened to me, what I have to do to make it work since it is not the first time, it is happening to me several times and I delete the service and create it again

**Comment by mpociot** [comment]
@MightyPete where exactly do you see the access denied error? Are you trying to connect via the CLI or do you see the error in your Laravel application?

Herd does not modify the password of the `root` user when you log out/restart your machine.

**Comment by jacobgraf** [comment]
I am seeing this same error. I just upgraded to Herd Pro so I could manage these services from within Herd. I add the MySQL 8 service, it says it's initialized, but it won't start. If I press start, it flashes green for less than a second and goes back to gray. If I select the MySQL service and look in the log in Herd, it shows the following. Any idea how to get this working or do I need to remove it from Herd and go with Brew again for now?

```
/bin/sh: /Users/Shared/Herd/services/mysql/8.0.36/bin/mysqld_safe: Permission denied
/bin/sh: line 0: exec: /Users/Shared/Herd/services/mysql/8.0.36/bin/mysqld_safe: cannot execute: Undefined error: 0
```

I did a full uninstall/reinstall using the instructions in the Herd Docs, and the issue persists.

**Comment by mpociot** [comment]
@jacobgraf do you have any specific user access rights on your Mac?

Could you share the "permissions" of `/Users/Shared/Herd/services/mysql/8.0.36`?

It should look something like this:

<img width="391" alt="image" src="https://github.com/user-attachments/assets/74612768-bf75-4ab5-8eb7-934775c734fc">

**Comment by jacobgraf** [comment]
@mpociot I didn't change anything as fas as permissions go and like I said, I did a full uninstall/reinstall too.

![CleanShot 2024-08-09 at 06 51 32@2x](https://github.com/user-attachments/assets/0ead29de-3b94-485f-98e1-1fc1f0b85eca)

![CleanShot 2024-08-09 at 06 52 19@2x](https://github.com/user-attachments/assets/be0184b4-7cc9-494e-8a12-6abd307f308e)

**Comment by jacobgraf** [comment]
@mpociot 

![CleanShot 2024-08-09 at 06 54 04@2x](https://github.com/user-attachments/assets/22f4b0a0-7285-4e48-8d1b-1b62fd8185d1)

**Comment by mpociot** [comment]
Can you manually execute the files in the bin folder via the terminal?
It's weird that you get a permission error

**Comment by jacobgraf** [comment]
@mpociot 
![CleanShot 2024-08-09 at 07 07 08@2x](https://github.com/user-attachments/assets/8e990eee-40b5-48d9-a995-9d179fa9fa6d)

I also did a chmod +x on mysql and got this...

![CleanShot 2024-08-09 at 07 09 12@2x](https://github.com/user-attachments/assets/6bb7e620-8250-49a3-aec2-2a3ffd8fd9b5)

**Comment by mpociot** [comment]
Yeah it's weird that the binaries don't have the correct permissions.
Could you try and delete/re-create the service in the Herd UI to see if this fixed it?

**Comment by jacobgraf** [comment]
@mpociot Yes I've done that many times. Same issue.

**Comment by mpociot** [comment]
@jacobgraf 
Actually, the fact that you still have the .zip file indicates that there was an error unzipping the file.

Could you please do me a favor and:

1. Delete the zip file and the 8.0.36 folder in /Users/Shared/Herd...
2. Quit Herd
3. Start Herd from the terminal via:
```
/Applications/Herd.app/Contents/MacOS/Herd --enable-logfile
```

Then create a new MySQL service in the UI.

If there was an error unzipping the file (it should get deleted automatically afterwards) you should see something in this log file:

`~/Library/Application Support/Herd/Logs/Herd_Debug.log`

We also basically chmod +x all binaries after unzipping by running:

```
find "/Users/Shared/Herd/services/mysql/8.0.36" -type f -exec chmod +x {} \\;
```

**Comment by jacobgraf** [comment]
@mpociot Wow! That worked! So it must have been a corrupted extraction of the zip file originally. Maybe there is a way to add a cleanup method to delete those when you delete the service, or clear the cached ones. Thanks for your help!

**Comment by mpociot** [comment]
I'll improve this on our end as well so we have better error handling in place.
