### ISSUE TITLE
[Feature Request]: Add ext-grpc extension

### ISSUE THREAD

**Issue by lokesh-zersys** [beyondcode/herd-community#9]
### Feature Description

Would be great to have gRPC  extension, Services live firestore uses this extension.

**Comment by iamlux20** [comment]
You can add it into Herd's php.ini as a location then do a Herd restart

`extension="/opt/homebrew/lib/php/pecl/20220829/grpc.so"`

**Comment by sineld** [comment]
> You can add it into Herd's php.ini as a location then do a Herd restart
> 
> `extension="/opt/homebrew/lib/php/pecl/20220829/grpc.so"`

By this sample I've added PostgreSQL drivers. Thanks @iamlux20

**Comment by mpociot** [comment]
As of right now, the grpc extension can not be compiled statically, so you would need to manually compile it and link it in your php.ini file.

**Comment by Saifallak** [comment]
I added extension="/opt/homebrew/Cellar/php/8.4.10/pecl/20240924/grpc.so" but still not working

**Comment by iamlux20** [comment]
> I added extension="/opt/homebrew/Cellar/php/8.4.10/pecl/20240924/grpc.so" but still not working

This solution is for Laravel Herd. You might be using Homebrew, which is a different package manager

**Comment by Saifallak** [comment]
> > I added extension="/opt/homebrew/Cellar/php/8.4.10/pecl/20240924/grpc.so" but still not working
> 
> This solution is for Laravel Herd. You might be using Homebrew, which is a different package manager

I'm using herd, and it worked, after some debugging. idk what made it success, but it works now.
