### ISSUE TITLE
[Bug]: Herd Pro isn't working properly. How on earth do I submit a support ticket for Pro?

### ISSUE THREAD

**Issue by RomkaLTU** [beyondcode/herd-community#901]
### Platform

macOS

### Operating system version

macOS Sonate

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.9.1

### Bug description

Today, out of the blue, some of my sites are inaccessible with a "502 Bad Gateway" error. Nothing changed at all; I just added a new site via the Herd UI. I can't understand how to submit a support ticket as a Pro user. The link is redirecting me to https://beyondco.de/. What should I do there? When I try to log in and submit the license, it says "The selected key is invalid." However, in https://herd.laravel.com/licenses, I can see this email and license is listed. What a mess.

**Comment by mpociot** [comment]
Feel free to send a mail to support(at)beyondco.de

Have you tried to force stop and restart the Herd services? 
502 usually means that an FPM service is somehow stuck. 

If you hold the option key while clicking on the Herd icon, you should see "Force stop"

**Comment by RomkaLTU** [comment]
I actually tried to restart computer. The site is listed in herd parked output also tried to hard link it, no dice.

**Comment by mpociot** [comment]
And that's the only site that's giving you a 502?
What's in your nginx error logs?

**Comment by RomkaLTU** [comment]
What is most strange no it's not only this site some of sites is working some not...I can't find relations between it. All service is marked as running. 

Here is config for site that doesn't work (502)

```
server {
    listen 127.0.0.1:80;
    #listen 127.0.0.1:80; # valet loopback
    server_name cc-api.test www.cc-api.test *.cc-api.test;
    return 301 https://$host$request_uri;
}

server {
    listen 127.0.0.1:443 ssl;
    #listen VALET_LOOPBACK:443 ssl; # valet loopback
    server_name cc-api.test www.cc-api.test *.cc-api.test;
    root /;
    charset utf-8;
    client_max_body_size 512M;
    http2 on;

    location /41c270e4-5535-4daa-b23e-c269744c2f45/ {
        internal;
        alias /;
        try_files $uri $uri/;
    }

    ssl_certificate "/Users/rd/Library/Application Support/Herd/config/valet/Certificates/cc-api.test.crt";
    ssl_certificate_key "/Users/rd/Library/Application Support/Herd/config/valet/Certificates/cc-api.test.key";

    location / {
        rewrite ^ "/Applications/Herd.app/Contents/Resources/valet/server.php" last;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    access_log off;
    error_log "/Users/rd/Library/Application Support/Herd/Log/nginx-error.log";

    error_page 404 "/Applications/Herd.app/Contents/Resources/valet/server.php";

    location ~ [^/]\.php(/|$) {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass $herd_sock;
        fastcgi_index "/Applications/Herd.app/Contents/Resources/valet/server.php";
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME "/Applications/Herd.app/Contents/Resources/valet/server.php";
        fastcgi_param HERD_HOME "/Users/rd/Library/Application Support/Herd";
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    location ~ /\.ht {
        deny all;
    }
}

server {
    listen 127.0.0.1:60;
    #listen 127.0.0.1:60; # valet loopback
    server_name cc-api.test www.cc-api.test *.cc-api.test;
    root /;
    charset utf-8;
    client_max_body_size 128M;

    add_header X-Robots-Tag 'noindex, nofollow, nosnippet, noarchive';

    location /41c270e4-5535-4daa-b23e-c269744c2f45/ {
        internal;
        alias /;
        try_files $uri $uri/;
    }

    location / {
        rewrite ^ "/Applications/Herd.app/Contents/Resources/valet/server.php" last;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    access_log off;
    error_log "/Users/rd/Library/Application Support/Herd/Log/nginx-error.log";

    error_page 404 "/Applications/Herd.app/Contents/Resources/valet/server.php";

    location ~ [^/]\.php(/|$) {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass "unix:/Users/rd/Library/Application Support/Herd/herd.sock";
        fastcgi_index "/Applications/Herd.app/Contents/Resources/valet/server.php";
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME "/Applications/Herd.app/Contents/Resources/valet/server.php";
        fastcgi_param HERD_HOME "/Users/rd/Library/Application Support/Herd";
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    location ~ /\.ht {
        deny all;
    }
}


```

And this one is working:

# ISOLATED_PHP_VERSION=83
s```
erver {
    listen 127.0.0.1:80;
    #listen 127.0.0.1:80; # valet loopback
    server_name nwr.test www.nwr.test *.nwr.test;
    return 301 https://$host$request_uri;
}

server {
    listen 127.0.0.1:443 ssl;
    #listen VALET_LOOPBACK:443 ssl; # valet loopback
    server_name nwr.test www.nwr.test *.nwr.test;
    root /;
    charset utf-8;
    client_max_body_size 512M;
    http2 on;

    location /41c270e4-5535-4daa-b23e-c269744c2f45/ {
        internal;
        alias /;
        try_files $uri $uri/;
    }

    ssl_certificate "/Users/rd/Library/Application Support/Herd/config/valet/Certificates/nwr.test.crt";
    ssl_certificate_key "/Users/rd/Library/Application Support/Herd/config/valet/Certificates/nwr.test.key";

    location / {
        rewrite ^ "/Applications/Herd.app/Contents/Resources/valet/server.php" last;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    access_log off;
    error_log "/Users/rd/Library/Application Support/Herd/Log/nginx-error.log";

    error_page 404 "/Applications/Herd.app/Contents/Resources/valet/server.php";

    location ~ [^/]\.php(/|$) {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass $herd_sock_83;
        fastcgi_index "/Applications/Herd.app/Contents/Resources/valet/server.php";
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME "/Applications/Herd.app/Contents/Resources/valet/server.php";
        fastcgi_param HERD_HOME "/Users/rd/Library/Application Support/Herd";
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    location ~ /\.ht {
        deny all;
    }
}

server {
    listen 127.0.0.1:60;
    #listen 127.0.0.1:60; # valet loopback
    server_name nwr.test www.nwr.test *.nwr.test;
    root /;
    charset utf-8;
    client_max_body_size 128M;

    add_header X-Robots-Tag 'noindex, nofollow, nosnippet, noarchive';

    location /41c270e4-5535-4daa-b23e-c269744c2f45/ {
        internal;
        alias /;
        try_files $uri $uri/;
    }

    location / {
        rewrite ^ "/Applications/Herd.app/Contents/Resources/valet/server.php" last;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    access_log off;
    error_log "/Users/rd/Library/Application Support/Herd/Log/nginx-error.log";

    error_page 404 "/Applications/Herd.app/Contents/Resources/valet/server.php";

    location ~ [^/]\.php(/|$) {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass "unix:/Users/rd/Library/Application Support/Herd/herd.sock";
        fastcgi_index "/Applications/Herd.app/Contents/Resources/valet/server.php";
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME "/Applications/Herd.app/Contents/Resources/valet/server.php";
        fastcgi_param HERD_HOME "/Users/rd/Library/Application Support/Herd";
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    location ~ /\.ht {
        deny all;
    }
}


```

**Comment by mpociot** [comment]
The sites that are isolated explicitly use PHP 8.3, while the other config uses whatever is currently marked as Herds default PHP Version. 
Which one is this for you?

You can also switch it via "herd use 8.3" in the CLI (for example)

**Comment by RomkaLTU** [comment]
The "herd php -v" output was 8.3. However, I still ran "herd use 8.3". What I noticed is that in the UI, I see a checkbox checked for PHP 8.3. Previously, it wasn't checked at all.

![CleanShot 2024-07-25 at 15 25 02](https://github.com/user-attachments/assets/9f45c9e7-0231-4ea6-9b50-e8c51a9c1a49)

**Comment by mpociot** [comment]
Did this change anything for your sites?

**Comment by RomkaLTU** [comment]
Now everything is working and it's indeed some kind of bug becouse herd park showed same output before and after `herd use 8.3`

![CleanShot 2024-07-25 at 15 30 53](https://github.com/user-attachments/assets/86b4663b-db97-4423-8512-61c608b50414)

**Comment by mpociot** [comment]
Yeah thats not causing any issues though, but it's a UI annoyance we should get rid of. 

Alright, then I would close this issue if everything is working again 🙂

**Comment by RomkaLTU** [comment]
Yes I guess so.
