### ISSUE TITLE
[Bug]: Herd not respecting the selected PHP version

### ISSUE THREAD

**Issue by HeytalePazguato** [beyondcode/herd-community#903]
### Platform

Windows

### Operating system version

Windows 11 Home

### System architecture

Intel (x86)

### Herd Version

1.9.0

### PHP Version

8.3

### Bug description

When trying to create a new Laravel project, with PHP 8.3 selected in the global PHP Version

![image](https://github.com/user-attachments/assets/d39dc3e1-de9d-402f-94cc-e468322d9024)

The console writes this message on the first line:

> *Cannot use laravel/laravel´s latest version v11.1.4 as it requires php ^8.2 which is not satisfied by your platform*

And then proceeds to create the new project with Laravel 10. Why is the Global PHP version not working? I have also installed PHP 8.2 and it produces the same behavior

![image](https://github.com/user-attachments/assets/d5db2f46-cf66-4e08-abc4-a48b3f617291)

### Steps to reproduce

1. Install `Herd`
2. Click on "Open Sites" button
3. In the new window click on "Add Site" button
4. Select "New Laravel project"
5. Click on "Next" button
6. Select any option (I have tried with the 3), for example "No starter kit"
7. Give the project name, for example "willNotWork"
8. The console returns the mentioned message

![image](https://github.com/user-attachments/assets/a2f1ec2d-619e-4a77-bb6f-dce0def9f473)

### EDIT ###

When I try to run `herd` from anywhere I get the following error in the console:

```
C:\Users\user>herd
Composer detected issues in your platform:

Your Composer dependencies require a PHP version ">= 8.2.0". You are running 8.1.2.

PHP Fatal error:  Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.2.0". You are running 8.1.2. in phar://C:/Users/user/.config/herd/bin/herd.phar/vendor/composer/platform_check.php on line 24
```

But if I run it from `C:\Users\user\.config\herd\bin` then it works

```
PS C:\Users\user\.config\herd\bin> herd
Herd 1.9.0

Usage:
  command [options] [arguments]
```

Perhaps herd is not installed properly, but I already uninstalled it and tried 5 times, each time using admin rights for both, the installation and the first configuration.

**Comment by mechelon** [comment]
Can you run `Get-Command php` in Powershell and post the output here?
Also, can you check if the Herd binary folder is on top of your PATH? It looks like there's another PHP installation with 8.1 or lower used when running in the Terminal.

**Comment by HeytalePazguato** [comment]
Hello @mechelon

Here is the output of `Get-Command`

```
PS C:\Users\user> Get-Command php

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     php.exe                                            8.1.2.0    C:\php8\php.exe
```

I've confirmed that Herd binary is on top of the user variables for my user's PATH

I've checked the system variables and in the PATH I've moved `C:\Users\user\.config\herd\bin\nvm` to the top and also found there is a `C:\php8`. This is being used by an Apache server running on my PC.

I thought Herd's PHP installations would be taken and executed from the `.config` folder. Could it be that Herd cannot coexist with previous PHP versions installed on the PC?

**Comment by h4r1m4u** [comment]
I had the same exact issue. Whenever I would try to create a new site with the `laravel new example` command, I would get the same error message. And moreover, whenever I would try to run any of the `herd` commands in terminal, I would get the following error:

```
PHP Fatal error:  Uncaught Error: Call to undefined function Valet\curl_init() in phar://C:/Users/JohnDoe/.config/herd/bin/herd.phar/cli/Valet/Herd.php:136
Stack trace:
#0 phar://C:/Users/JohnDoe/.config/herd/bin/herd.phar/cli/Valet/Herd.php(91): Valet\Herd->makeAppRequest('version')
#1 phar://C:/Users/JohnDoe/.config/herd/bin/herd.phar/cli/includes/facades.php(22): Valet\Herd->version()
#2 phar://C:/Users/JohnDoe/.config/herd/bin/herd.phar/cli/app.php(26): Facade::__callStatic('version', Array)
#3 phar://C:/Users/JohnDoe/.config/herd/bin/herd.phar/cli/herd.php(3): require_once('phar://C:/Users...')
#4 C:\Users\JohnDoe\.config\herd\bin\herd.phar(13): require('phar://C:/Users...')
#5 {main}
  thrown in phar://C:/Users/JohnDoe/.config/herd/bin/herd.phar/cli/Valet/Herd.php on line 136
```

This led me to think that the problem might be associated with the PHP cURL extension. I checked the globally installed `php.ini` configuration in `C:\\PHP\php.ini` and the curl extension was commented out: `;extension=curl`. I removed the comment by changing it to `extension=curl`, then ran the `herd` command again and it worked fine. 

So after that, I tried creating a new site with the `laravel new example` command and this time the site creation went through without a hitch.  

@HeytalePazguato See if perhaps your issue has the same cause and if the above fixes it for you too.

**Comment by mechelon** [comment]
Herd is not supposed to work with parallel installations of NVM/PHP, so we cannot provide support for that.
