### ISSUE TITLE
[Bug]: Windows herd proxy command creates invalid NGINX config

### ISSUE THREAD

**Issue by godismyjudge95** [beyondcode/herd-community#904]
### Platform

Windows

### Operating system version

Windows 11 Pro (22631.3880)

### System architecture

Intel (x86)

### Herd Version

1.9.0

### Bug description

Creating a proxy using the `herd proxy` command causes it to create a new NGINX site config that then causes NGINX to not boot because there is an error in it.

The solution is quite simple, we just need to change the path from:
```
error_log "C:/Users/user/.config/herd/config/valet/Log/reverb.test-error.log"
```

To:
```
error_log "C:/Users/user/.config/herd/Log/reverb.test-error.log"
```

### Steps to reproduce

1. Run `herd proxy --secure reverb.test https://localhost:8080`
2. Check the Herd dashboard
3. Notice that NGINX cannot start
4. Click the (i) to see the NGINX logs you will see an error like the below

### Relevant log output

```shell
2024/07/29 00:11:29 [emerg] 32648#4056: CreateFile() "C:/Users/user/.config/herd/config/valet/Log/reverb.test-error.log" failed (3: The system cannot find the path specified)
```

**Comment by jerrens** [comment]
I was experiencing the same problem and the fix suggested by @godismyjudge95 is working for me.

**Comment by zarulizham** [comment]
I'm encountered the same issues on MacOS.

For MacOS:

Navigate to proxy configuration file: /Users/<YOUR_USER>/Library/Application Support/Herd/config/valet/Nginx

From: 
error_log "/Users/<YOUR_USER>/Library/Application Support/Herd/config/valet/Log/<YOUR_PROXY>.test-error.log";

To: 
error_log "/Users/<YOUR_USER>/Library/Application Support/Herd/Log/<YOUR_PROXY>.test-error.log";

After saved, restart Herd and you can access the URL.
