### ISSUE TITLE
[Bug]: when open a laravel project created with herd the and open it with browser it give "This site can’t be reached" message

### ISSUE THREAD

**Issue by fuadTamim1** [beyondcode/herd-community#910]
### Platform

Windows

### Operating system version

Windows 11 Pro 21H2

### System architecture

Intel (x86)

### Herd Version

1.9

### PHP Version

8.3

### Bug description

After I had installed herd and finishing setup I create a new Laravel project in herd dir and And I checked the servers and everything is fine but when I come to see the project the created in the browser it give the current message "
This site can’t be reached **education_demo.test**’s DNS address could not be found. Diagnosing the problem.
DNS_PROBE_POSSIBLE.
and if I tried command `php artisan serve' it tells me `Failed to listen on 127.0.0.1:8000 (reason: ?)`.
I want to mention that I was using XAMPP to manage Laravel apps before and currently I switched to herd,
there are more thing when I check the hosts File in `system32/drives/etc/` I did't found the address was set I'm not sure if it should I don't have a lot of experience to deal with servers and local servers...
so what should I do?

**Comment by mechelon** [comment]
Can you check if the HerdHelper is running correctly and if not, send over the logs? You can check that in Herd's dashboard at the General tab at the bottom.
Also, it's not necessary to run `php artisan serve` with Herd :)

**Comment by acobrerosf** [comment]
I am having the same issue, the projects that I have already created are still working but any new project I create doesn't work. Not sure if this is happening after updating to the last version in Windows to be honest cause it's been a while since I needed to create a new project.

Please let me know what info do you need and will try to provide it.

**Comment by sschlein** [comment]
I am closing this issue because there is no further response by @fuadTamim1 and @acobrerosf 's problem was solved.
