### ISSUE TITLE
[Bug]: Open port 80 shows AdminerEvo

### ISSUE THREAD

**Issue by Gnative** [beyondcode/herd-community#911]
### Platform

macOS

### Operating system version

MAx OSX Sonoma 14.5 (23F79)

### System architecture

Intel (x86)

### Herd Version

1.9.1

### PHP Version

8.2.21

### Bug description

Following on from this bug report - https://github.com/beyondcode/herd-community/issues/900

I change my herd.conf to open the :80 port for testing on my machine as it allows mobile devices to access my herd sites for API endpoints via my local IP. This is now not useable after my last Heard update and I'm not sure how to resolve it. 

server {
    listen 80 default_server;
    

I've always followed this documentation as explained in this comment - https://github.com/beyondcode/herd-community/issues/276

- I am not a Pro user.
- I have no other configuration changes to the base installation of Herd (that i can remember)

**Comment by Gnative** [comment]
Problem is I don't know how to release that port from AdminerEvo to allow my local testing environment again

**Comment by Gnative** [comment]
> @Gnative As a temporary solution you can edit all the config files in /Users/[USERNAME]/Library/Application Support/Herd/config/valet/Nginx/ and remove the localhost IP.
> 
> But this changes may be overwritten by herd, if you change some settings of the page like PHP-Version, etc.
> 
> ```
> from: 
> listen 127.0.0.1:80;
> 
> to: 
> listen 80;
> ```

Thanks @emfMaddin unfortunately that directory is empty but it got me looking into this and I found a solution.
In /Users/[USERNAME]/Library/Application Support/Herd/config/valet/Nginx/nginx.conf, down the bottom of the file, change the line

`#include "/Applications/Herd.app/Contents/Resources/config/pro/nginx/*.conf";
`
to 
`include "/Applications/Herd.app/Contents/Resources/config/pro/nginx/debug.conf";
`

The reason for this is /Applications/Herd.app/Contents/Resources/config/pro/nginx/ contains 2 includes, one for debugging and another for AdminerEvo which si hijackign port 80.

**Comment by emfMaddin** [comment]
@Gnative True, this also works out but you will loose AdminerEvo - no problem if you don't need it :-)

**Comment by Gnative** [comment]
Have to change this with the Heard version 1.11.0

You can comment out the last nginx include line in `~/Library/Application Support/Herd/config/valet/Nginx/nginx.conf` I.E

```
    #include "/Applications/Herd.app/Contents/Resources/config/default-sites/*.conf";`
```

**Comment by Gnative** [comment]
@mpociot sorry, this is still a problem in 1.11.0
