### ISSUE TITLE
[Bug]:  Issue Activating Pro License for Herd

### ISSUE THREAD

**Issue by mauriciodulce** [beyondcode/herd-community#916]
### Platform

macOS

### Operating system version

Version 14.5 (23F79)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.9.1 build 31

### PHP Version

All versions

### Bug description

I am unable to activate the Pro license for Herd. Each time I attempt to activate the license, an error message appears indicating that something went wrong. I have tried reinstalling Herd multiple times, both from the official website and using Homebrew. I have also changed the license token and ensured it is copied correctly, but the issue persists.

### Steps to reproduce

1. Download and install Herd from the official website or using Homebrew.
2. Obtain a valid Pro license token.
3. Open Herd and navigate to the license activation section.
3. Enter the Pro license token and click on the "Activate License" button.
4. Observe the error message that appears after attempting activation.
![Screen Shot](https://dulce.nyc3.digitaloceanspaces.com/Screen-Shot-2024-08-02-12-37-13.png)

### Relevant log output

```shell
Logs 

Logging setup complete.
Stopping Nginx
Stopping DNSMasq
Process is not running - won't stop
Process is not running - won't stop
Process is not running - won't stop
Process is not running - won't stop
Unable to delete PID file
Process is not running - won't stop
Process is not running - won't stop
Process is not running - won't stop
--- Terminate observer called for process
--- Terminate observer called for process
--- Terminate observer called for process
--- Terminate observer called for process
--- Terminate observer called for process
--- Terminate observer called for process
--- Terminate observer called for process
--- Terminate observer called for process
--- Terminate observer called for process
--- Terminate observer called for process
--- Terminate observer called for process
--- Terminate observer called for process
```

**Comment by sschlein** [comment]
Can you please reach out about this via support@beyondco.de so that we can have a look?

Just copy and paste the issue description- we can track down you license from there. 

Thanks

**Comment by mauriciodulce** [comment]
I have been dealing with this issue for two weeks now. I have already sent them emails, but I haven't received a response. Diana and Marcel have replied to me, but I still cannot activate the license that I paid for and I have no solution for this. I have even sent them videos.

**Comment by sschlein** [comment]
I understand your frustration but it's related to your setup because it's works for thousands of others. 

I am 99% sure that you either run a local firewall, proxy or that there is a corporate VPN in place that does not allow you to connect to our API. 

If you can't figure out the problem and our support does not help, we can always issue a refund. We will never in a million years keep money of an unhappy customer – but this is not a Herd bug.
