### ISSUE TITLE
[Bug]: When using `site link --isolate`, it doesn't check for `.valetrc` file

### ISSUE THREAD

**Issue by mikeybinns** [beyondcode/herd-community#917]
### Platform

Windows

### Operating system version

Windows 11 Home 23H2

### System architecture

Windows

### Herd Version

1.9.0

### Bug description

When linking a site with the `--isolate` flag in the `herd link` command, you cannot leave the option blank to allow herd to check for a `.valetrc` file and use that PHP version.

This differs from herd isolate where if you don't specify a version, it will search for a `.valetrc` or `.valetphprc` file, and use that PHP version for it.

This also differs from `valet link --isolate`, which doesn't require a parameter value and works the way I expected.

### Steps to reproduce

1. Have a site that isn't linked
2. Create a `.valetrc` file and specify a PHP version in it
3. Run `herd link SITENAME --isolate`
4. Take note of the error about needing a parameter value
5. Run `herd link SITENAME` to link the site as the previous link will have failed due to that error
6. Run `herd isolate`
7. Note how it correctly isolates to the version in `.valetrc`

**Comment by MeMattStone** [comment]
Have also had this problem on the Mac version, I’ve removed Laravel/valet in favour of using Herd and expected the equivalent herd commands to mirror the Valet ones (I’ve setup an alias in my `.zshrc` file so any command starting with `valet` is redirected to `herd` as we have various projects that have automated setup commands in the package.json which use things like `valet link —secure —isolate`), and it would be great if the `—isolate` flag could read the `.valetrc` file as it does on valet

**Comment by mechelon** [comment]
The `.valetrc` file is not supported when isolating via `link`, however it gets picked up when you use the dedicated `isolate` command. That is on purpose; there will soon be an update for Herd where project-specific settings are improved.
