### ISSUE TITLE
[Bug]: Can't find php

### ISSUE THREAD

**Issue by alexmanase** [beyondcode/herd-community#92]
### Operating system version

macOS Ventura 13.5

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.1.1 Build 12

### Bug description

Hi there!

I made a new installation of Herd and now I can't find php using `php` in terminal.

<img width="293" alt="image" src="https://github.com/beyondcode/herd-community/assets/10696975/2d717252-6c8b-4336-9552-731a0e22011b">

I uninstalled all versions of php from Homebrew.

### Steps to reproduce

1. Install Herd
2. Check `php --version`

**Comment by mpociot** [comment]
Herd injects a modified `PATH` environment variable into your `~/.zshrc` file, please make sure this exists:

```
# Herd injected PHP binary.
export PATH="/Users/YOUR-USERNAME/Library/Application Support/Herd/bin/":$PATH
```

Also, make sure to restart your terminal after installing Herd in order for the PATH changes to take effect.
