### ISSUE TITLE
PHP 8.3 Not Updated - 8.3.10

### ISSUE THREAD

**Issue by bashgeek** [beyondcode/herd-community#921]
### Platform

macOS

### Operating system version

14.6 (23G80)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.9.1 #31

### PHP Version

PHP 8.3.9 (cli) (built: Jul  8 2024 12:00:57) (NTS)

### Bug description

PHP 8.3.10 was released August 1st and has not been updated to Herd yet, while PHP 8.2.22 which was released on the same date was available on Herd shortly after.

**Comment by mpociot** [comment]
The current version of curl (8.9.1) has a bug, which already caused some errors in combination with "herd share". 
We had to investigate this first. 

We will publish an update today with a downgraded version of curl (8.8.0) as the error don't occur in this version - and 8.10.0 is only scheduled for release in one month.

**Comment by mpociot** [comment]
The PHP 8.3 and 8.2 updates are now published. The ARM64 versions are already out, the Intel versions are available in a couple of minutes.
