### ISSUE TITLE
[Bug]: 1.9.1 After clicking to secure a site - all sites say 'This site can’t be reached'

### ISSUE THREAD

**Issue by marchampson** [beyondcode/herd-community#922]
### Platform

macOS

### Operating system version

macOS Sonoma 14.5

### System architecture

Intel (x86)

### Herd Version

1.9.1

### Bug description

I clickeed on the 'secure' icon in the new Sites UI for the site I wanted to secure. It wasn't clear that it had done it, but when checking another site, all sites said they were unreachable. I managed to briefly get a site to appear by changing the tld and then changing back but to to move away from login gave the same error again. 

### Steps to reproduce

I guess just try securing a newly added site. I should add that this was a 'Wordpress' site that I needed to test. 
I have now uninstalled and reinstalled Herd and while the issue is still there, there is nothing in the nginx or dnsmasq logs.

**Comment by marchampson** [comment]
I have got a little further in that I can launch one of my sites - the uninstall has changed the mysql port back to 3306 from 3307, not sure why that was changed, so my databases are now hiding. But that aside, if i secure this site - all browsers say it is untrusted. I've removed any previous from the KeyChain and also run in incognito.

**Comment by mpociot** [comment]
Yeah chrome DNS cache can be super persistent 🙈

**Comment by marchampson** [comment]
Agreed! Something seems to have changed there as I've just secured another and got errors until I restarted Chrome. Never had that before. All good with Herd though - thanks Marcel for reading through though. Cheers.
