### ISSUE TITLE
[Bug]: Context menu appears behind auto hiding taskbar

### ISSUE THREAD

**Issue by adevade** [beyondcode/herd-community#923]
### Platform

Windows

### Operating system version

Windows 11 Home 23H2 22631.3958

### System architecture

Windows

### Herd Version

1.9.0

### Bug description

I have my taskbar hidden in Windows, and interacting with Herds context menu is kind of awkward. It shows up behind the taskbar. See video below. I would expect for it to open from where the pointer was, instead of from a fixed position.

### Steps to reproduce

Activate the auto hiding taskbar in Windows, and try to open the context menu for Herd. 

> Right click taskbar > Settings > Behavior.. > Hide automatically..
> (Don't know the exact wording, because my OS is in Swedish.)

https://github.com/user-attachments/assets/c5865fda-2527-45fe-8798-80a1c2640ad6

**Comment by mpociot** [comment]
This seems to be an issue with the menubar plugin we're using for Windows: https://github.com/max-mapper/menubar/issues/380

**Comment by mpociot** [comment]
I'll close this as we have to wait for the menubar dependency to fix this bug. As soon as that happens, we'll have this fixed in Herd as well.
