### ISSUE TITLE
[Bug]: FPM-7.4 is not stopping when switching from PHP7.4 to other version

### ISSUE THREAD

**Issue by jonjieviduya** [beyondcode/herd-community#924]
### Platform

macOS

### Operating system version

macOS Ventura

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.9.1 (Build: 31)

### Bug description

The FPM-7.4 is not stopping when switching from PHP7.4 to other version of PHP.
<img width="220" alt="Screenshot 2024-08-09 at 11 58 12 AM" src="https://github.com/user-attachments/assets/a55e51ba-ed5c-48d9-984f-471f76a50c02">

**Comment by mechelon** [comment]
Have you isolated sites to 7.4? You can check by running `herd isolated` in your CLI.

**Comment by jonjieviduya** [comment]
@mechelon I have one isolated site to 7.4

**Comment by mechelon** [comment]
That's why the process is still running :)
