### ISSUE TITLE
[Bug]: CORS issue for vite client

### ISSUE THREAD

**Issue by patrickriemer** [beyondcode/herd-community#93]
### Operating system version

macOS Ventura 13.4.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.1.1 (Build 12)

### PHP Version

PHP 8.2

### Bug description

I am desperately trying to get Herd running with Vite and the Herd generated SSL certificate and would appreciate any help.

Latest version of Laravel 10

Vite client cannot be loaded. Error message in Chrome:

GET https://core.test:5173/@vite/client net::ERR_SSL_VERSION_OR_CIPHER_MISMATCH

Error message in Firefox:

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://core.test:5173/@vite/client. (Reason: CORS request did not succeed). Status code: (null).

### Steps to reproduce

The core.php configuration is default and should allow all origins and header.

Vite configuration:

```import { defineConfig } from 'vite'
import laravel from 'laravel-vite-plugin'
import vue from '@vitejs/plugin-vue'
import fs from "fs"
import {homedir} from 'os'
import {resolve} from 'path'

let host = 'core.test'

export default defineConfig({
    resolve: {
        alias: {
            '@': '/resources/js',
        },
    },
    server: detectServerConfig(host),
    plugins: [
        laravel({
            input: 'resources/js/app.js',
            refresh: true,
        }),
        vue({
            template: {
                transformAssetUrls: {
                    base: null,
                    includeAbsolute: false,
                },
            },
        }),
    ],
});

function detectServerConfig(host) {
    let keyPath = resolve(homedir() + `/Library/Application Support/Herd/config/valet/Certificates/${host}.key`)
    let certificatePath = resolve(homedir() + `/Library/Application Support/Herd/config/valet/Certificates/${host}.crt`)

    if (! fs.existsSync(keyPath) || ! fs.existsSync(certificatePath)) {
        return {}
    }

    return {
        hmr: {host},
        host,
        https: {
            key: fs.readFileSync(keyPath),
            cert: fs.readFileSync(certificatePath),
        }
    }
}
```
![Screenshot 2023-08-03 at 11 43 13](https://github.com/beyondcode/herd-community/assets/32695238/3b63d266-696e-4dee-a3e9-57c7f6b39af6)

**Comment by mpociot** [comment]
Hm I just tried it with this exact config and it's working fine for me 🤔

**Comment by RobertCordes** [comment]
Even though this won't help you @patrickriemer, thanks anyways. I've been struggling to get Vite to work with Herd and your configuration just immediately did the trick!

**Comment by patrickriemer** [comment]
I have re-installed my entire operating system and have now only Herd and DBngin installed. My configuration is still as above, but I am getting the same error, which leads me to the conclusion that it must be the project source code. Any hint into the right direction would be appreciated.

**Comment by patrickriemer** [comment]
Finally found the issue - it came from my package.json

After removing --host and --https and reverting to the original vite.config.js it is working fine now :)

![Screenshot 2023-08-08 at 13 15 20](https://github.com/beyondcode/herd-community/assets/32695238/3a4142e8-b0b4-40e3-a540-0dddbcf6b282)
