### ISSUE TITLE
[Bug]: uninstall docs for Windows missing the entries added to .bash_profile

### ISSUE THREAD

**Issue by jcrben** [beyondcode/herd-community#930]
### Platform

Windows

### Operating system version

Windows 11 10.0.22631.3880 (23H2)

### System architecture

Intel (x86)

### Herd Version

1.9.0

### Bug description

I'm a big fan of the Boy Scout motto when it comes to software: leave no trace. I know you've got a good short list of cleanup instructions at https://herd.laravel.com/docs/windows/1/troubleshooting/uninstalling#uninstalling-herd but it's missing these entries in my `~/.bash_profile`: 
![image](https://github.com/user-attachments/assets/48758ea8-0dea-4055-8c8b-6b3e4598da17)

Some may wonder why someone is using bash on Windows, but I'm sure you're aware that it is pretty common for people to use "git bash" or "msys2 git" for Windows. I don't know if your install algorithm is detecting that bash is installed and only updating it if it notices that.

See also: [Herd doesn't seem to work with Git Bash Terminal #697](https://github.com/beyondcode/herd-community/issues/930)

**Comment by sschlein** [comment]
I've added this to the docs and it will be deployed soon :)
