### ISSUE TITLE
[Bug]: ERR_NAME_NOT_RESOLVED after switching wifi networks

### ISSUE THREAD

**Issue by ryanpitts1** [beyondcode/herd-community#939]
### Platform

macOS

### Operating system version

macOS Sonoma 14.6.1 (23G93)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.9.1

### PHP Version

PHP 8.3

### Bug description

I have been facing a rather strange issue that is difficult to reproduce and I'm honestly not sure entirely if it's specifically Herd related yet.

Over the past few weeks, it seems that if i switch network connections (different wifi networks, etc), Herd will stop responding until i fully restart my Macbook. I have tried stopping/starting Herd services and killing all Herd related things through the Activity Monitor and none of those fix it. It will only start working again if i fully restart my laptop.

The error i start getting when it breaks is just that the local .test sites stop loading and i get this:

<img width="651" alt="image" src="https://github.com/user-attachments/assets/06a5b73e-e1ee-4c2f-b4b6-d612c53057e1">

If this is not a Herd issue, feel free to disregard but i haven't changed anything and Herd is the only thing providing me this issue.

**Comment by sschlein** [comment]
I wonder if there are special network and DNS settings for the networks where it does not work, so does this happen if you switch to a specific network or general on a network change?

My assumpion is that the network that breaks it, has a different priority in DNS servers and skips dnsmasq from Herd.

**Comment by ryanpitts1** [comment]
So far, it's appeared to happen on just a general network change - i.e., when I go from my home network to a coffee shop external network or vice versa. I realize this is a not great info to debug with. Are there any logs somewhere or anything I can try and observe when it won't connect?

**Comment by sschlein** [comment]
My only guess is that it's somehow DNS related and that Herd's DNS server dnsmasq doesnt get used anymore after the change.

**Comment by sschlein** [comment]
To be honest, I have no idea if there are logs. 

Can you post the output of the resolver for test domains? run `scutil --dns` and there should be something like:

```
resolver #8
  domain   : test
  nameserver[0] : 127.0.0.1
  nameserver[1] : 127.0.0.1
  nameserver[2] : 127.0.0.1
  flags    : Request A records, Request AAAA records
  reach    : 0x00030002 (Reachable,Local Address,Directly Reachable Address)
```

Is this still there when you get the error?
