### ISSUE TITLE
[Bug]: Can't access test site; Previously used LocalWP

### ISSUE THREAD

**Issue by Twistmystery** [beyondcode/herd-community#944]
### Platform

Windows

### Operating system version

Windows 11 Home (23H2 22631.4037)

### System architecture

Intel (x86)

### Herd Version

1.10.0

### Bug description

I'm trying to run a WordPress site using Herd Pro, but when I try to access the test site I get a DNS_PROBE_FINISHED_NXDOMAIN error (see screenshot). I previously was using LocalWP to run WordPress. I uninstalled LocalWP, but is it possible that it could still be interfering with the nginx or DNS? Where would the would the best places be to look/check if that were the case and how would I get there? 

![Screenshot 2024-08-21 134020](https://github.com/user-attachments/assets/8e976db8-5427-4719-9305-bc63ea07d38b)

**Comment by sschlein** [comment]
Can you check your hosts file? As far as I remember, LocalWP is also writing to this file and this could cause an issue. What happens if you ping your site?

Are nginx and the other services running and display their green icon?

**Comment by Twistmystery** [comment]
@sschlein I see where Local modified my hosts file. Since I've uninstalled it, should I delete that section of the file? 

When I ping my site, it says, "Ping request could not find host jcesom.test. Please check the name and try again." (jcesom.test is the site name.)

Yes, nginx and the other services display the green.

**Comment by sschlein** [comment]
Yeah, you can delete those – if you're going back to local, it would create them again.

Did Herd add the jcesom.test domain to the hosts file? If not, there might be an issue with the HerdHelper and you could enable the logs for this in the settings.

**Comment by Hari-2kd2** [comment]
Hi,  
I have the same issue. Nginx and PHP services are running, and my hosts file contains only `127.0.0.1 localhost` and `::1 localhost`. I created a new Laravel project using the Laravel Herd GUI, but I’m unable to run the project.

![Screenshot 2024-08-24 151520](https://github.com/user-attachments/assets/ceedec8e-f2f9-49a6-bbc7-696276165b00)

**Comment by sschlein** [comment]
Can you please check if the HerdHelper is running in the General settings? Looks like the hosts don't get written to the file.

**Comment by Hari-2kd2** [comment]
> Can you please check if the HerdHelper is running in the General settings? Looks like the hosts don't get written to the file.

![image](https://github.com/user-attachments/assets/d355c295-f04a-4d54-917a-ddf7c384e247)

HerdHelper status is active

**Comment by Hari-2kd2** [comment]
> > Can you please check if the HerdHelper is running in the General settings? Looks like the hosts don't get written to the file.
> 
> ![image](https://private-user-images.githubusercontent.com/97944955/361141424-d355c295-f04a-4d54-917a-ddf7c384e247.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1MDQxNDksIm5iZiI6MTcyNDUwMzg0OSwicGF0aCI6Ii85Nzk0NDk1NS8zNjExNDE0MjQtZDM1NWMyOTUtZjA0YS00ZDU0LTkxN2EtZGRmN2MzODRlMjQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI0VDEyNTA0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxYjlkMmQyOGZiNDI4ODkyNmRlYzhmYTkyZGY3ZmIwNGIxNGNmZjU2ZTNlODFmNmM5OWE2YTc0ODNmZGE5MGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tvb3wmGyeavJkkYM3oBuUMcELpinqm591HQ5i5RYdfI)
> 
> HerdHelper status is active

i have added the host name manually in my windows host file, now its working.

**Comment by sschlein** [comment]
@Hari-2kd2 Would you please enable the logs of the HerdHelper and restart Herd? After that, please send me the logfile to support@beyondco.de. That should give us a clue why you need to add the sites manually, that shouldn't be the case and done by the helper.

**Comment by Twistmystery** [comment]
Deleting the entries made by LocalWP in the hosts file fixed the issue! After I did that, Herd was able to add the jcesom.test domain. 

Thank you so much for your help!
