### ISSUE TITLE
[Bug]: Using 300% CPU, temperatures reaching 90C and killing battery life

### ISSUE THREAD

**Issue by lukearmstrong** [beyondcode/herd-community#947]
### Platform

macOS

### Operating system version

macOS 14.6.1 (23G93)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.9.1 (Build: 31) (Herd Pro)

### PHP Version

8.3

### Bug description

The laptop starts to feel hot to the touch, and then I check Activity Monitor and Herd is slamming the CPU and Battery.

CPU
![image](https://github.com/user-attachments/assets/0d92ef87-760f-48b5-ad37-b71c6ee899a1)

Battery
![image](https://github.com/user-attachments/assets/1b3f5470-a191-4611-8b9c-abf16a5afed6)

Temperatures
![image](https://github.com/user-attachments/assets/14bd4a96-a8b3-44f3-8b99-a5cf82683dd9)

MacOS Version
<img width="392" alt="image" src="https://github.com/user-attachments/assets/492fcc05-dfad-450d-adb0-e9f815bf579d">

Herd Version
<img width="1022" alt="image" src="https://github.com/user-attachments/assets/1e14e4ff-b168-4042-8a1d-3baefbf2d596">

### Steps to reproduce

Nothing. Sometimes it happens, and then I have to reboot to "fix" it.

**Comment by sschlein** [comment]
That's wild, I am super curious what this could be. Are there any windows open, like dumps (with many many dumps), mails or logs?

I bet there is a memory leak somewhere or something is breaking in a specific situation.

**Comment by lukearmstrong** [comment]
So just to give you a bit more information.

I've only been using Herd Pro for a few weeks, I've not yet added any Laravel sites to it yet, so its not doing anything complicated with xdebug/dumps/mail/queues/etc... I'm just using it at the moment for a couple of Wordpress sites.

Neither of these even use node, so theres nothing like that running in the background. So its just a small mysql database for each one, and each site is secured using https.

It's not having this problem right now, its intermittent, but I've just tried looking for log files, anything unusually large or constantly being written to, the mysql one seems simple enough, just shows a few startup lines each time I rebooted really.

Nothing obviously wrong in the Logs folder either.
<img width="1032" alt="image" src="https://github.com/user-attachments/assets/7bb3179a-ecea-44d7-bbb3-f046d7c99f03">

**Comment by sschlein** [comment]
So this will write quite a few logs if it takes time to actually run into the problem but could you start Herd via the terminal with logging enabled? This creates a debug logfile in the logs directory.

`open /Applications/Herd.app --args --enable-logfile`

**Comment by abdusfauzi** [comment]
I think i just had something almost similar:

<img width="305" alt="Image" src="https://github.com/user-attachments/assets/e9457ef7-eeaf-44e5-b677-a26b254fe597" />

Not sure what I did. Last time I remembered, I keep the Herd window open at the background.

macOS Sequoio 15.4.1
Herd 1.20.0 (Build: 45)
