### ISSUE TITLE
[Bug]: PHP Section unusable in offline mode

### ISSUE THREAD

**Issue by TonsiTT** [beyondcode/herd-community#949]
### Platform

Windows

### Operating system version

Windows 11

### System architecture

Windows

### Herd Version

1.10.0

### Bug description

If there is no internet connection, the settings on PHP section become unusable. 
I understand it's probably trying to fetch the latest PHP versions and is stuck on that, but I'd like for it to still show me, at the minimum, the installed versions locally.(or perhaps cache the last result for offline usage?)  
I'd also like to be able to uninstall and change the Max File Upload Size and Memory limit while offline. 
I don't think any of these should require an internet connection, but they don't work without it.

### Steps to reproduce

1. Switch Internet off
2. Go to PHP section from sidebar

**Comment by sschlein** [comment]
Makes sense – I've created an internal issue for that.

**Comment by TonsiTT** [comment]
Thanks for the quick fix. Not to be rude, but what about the ETA for the next release?

**Comment by sschlein** [comment]
September, it's a huge one with many new features, so it takes some time and this change is not important to most users to force them through an update with a patch release.

**Comment by TonsiTT** [comment]
> September, it's a huge one with many new features, so it takes some time and this change is not important to most users to force them through an update with a patch release.

Yeah sure not in a hurry, was generally curious about the Herd update as a whole,
But damn now I'm excited about the new features 🥳 🥳
