### ISSUE TITLE
[Bug]: Can't find php

### ISSUE THREAD

**Issue by alexmanase** [beyondcode/herd-community#95]
### Operating system version

macOS Ventura 13.5

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.1.1 Build 12

### PHP Version

PHP 8.2.8 (cli) (built: Jul 28 2023 13:55:05) (NTS)

### Bug description

Same as https://github.com/beyondcode/herd-community/issues/92

I checked the `~/.zshrc` and the script is injected and I also restarted the terminal. It still can't find `php`, it can find `php82` instead, but this does not help because when I try to use composer it is looking for the `php` and it can't find even if I create an alias (e.g. `alias php='php82'`).

Sorry If I annoy you with the same bug, but I really like Laravel Herd and I want to try to make it work on my machine.

**Comment by mpociot** [comment]
What does "ls -la ~/Library/Application\ Support/Herd/bin give you?

**Comment by alexmanase** [comment]
<img width="786" alt="image" src="https://github.com/beyondcode/herd-community/assets/10696975/78b20c49-6b99-462e-af76-338640f36d87">

**Comment by mpociot** [comment]
It looks like Herd was unable to create/update the `php` symlink for you.

Please try creating it manually:

```bash
cd ~/Library/Application\ Support/Herd/bin/
ln -s php82 php
```

This should fix it

**Comment by alexmanase** [comment]
It worked.

Thank you!

**Comment by jhgeluk** [comment]
I am experiencing the same problem
