### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by mertaydin** [beyondcode/herd-community#950]
### Platform

macOS

### Operating system version

13.3.1 (a) (22E772610a)

### System architecture

Intel (x86)

### Herd Version

1.9.1 (Build: 31)

### Bug description

I installed Herd for the fist time when installing php something went wrong and Herd closed. I started it again and tried to install php 8.3 but showing "Download 1/2" and suddenly disappeared doesn't install.

**Comment by sschlein** [comment]
Can you confirm that there are no Herd processes running on your machine?

**Comment by mertaydin** [comment]
No, there were no duplicate processes. I even restarted the computer and the problem still persists.

**Comment by sschlein** [comment]
Did you try uninstalling and installing it again? 
![CleanShot 2024-09-03 at 16 07 56](https://github.com/user-attachments/assets/6b8ab10f-1878-4075-91b9-1b01f745aeaa)

**Comment by mertaydin** [comment]
Yes I two times installed and uninstalled but no changes.
