### ISSUE TITLE
[Bug]: Deleting mail lags

### ISSUE THREAD

**Issue by mathiaswillburger** [beyondcode/herd-community#954]
### Platform

Windows

### Operating system version

Windows 11

### System architecture

Windows

### Herd Version

1.1.0

### Bug description

Deleting mails via the right-click menu lags and takes about 3 seconds for the application to remove the mail. Currently I am testing with about 20-30 mails in the inbox.

Additionally, it would be helpful to have a delete functionality like for dumps for the mail inbox.

**Comment by sschlein** [comment]
Hey, you can delete whole inboxes via right click on the inbox:
![CleanShot 2024-09-02 at 09 04 40](https://github.com/user-attachments/assets/265e06ac-27b8-46a6-9a6a-763287032bf3)

You can also delete all mails in Herd if you deal with an unusual amount of them:
![CleanShot 2024-09-02 at 09 05 19](https://github.com/user-attachments/assets/863f44a1-f974-475c-beea-68446acaed13)

I'm currently improving the docs for Herd and will add more information about that.

**Comment by mathiaswillburger** [comment]
Thanks.... didn't see that :-( I was looking for a bin-icon or so, like in the dumps. Thanks for clarifying.

**Comment by sschlein** [comment]
This is why we're revisiting the UI and docs constantly. If it doesn't make sense to you as a user, it's bad ux.
