### ISSUE TITLE
[Bug]: unable to uninstall node. node is stuck on version 20 despite my using `nvm use 18`

### ISSUE THREAD

**Issue by vesper8** [beyondcode/herd-community#959]
### Platform

Windows

### Operating system version

Windows 11

### System architecture

Intel (x86)

### Herd Version

1.10

### PHP Version

8.3

### Bug description

Once node is installed form the Herd menu, it's not possible to uninstall those versions. There's a checkbox but clicking on it does nothing.

From the terminal, I am trying to `nvm use 18` and no matter what I do, it remains stuck on node version 20 which was installed by Herd Pro.

Furthermore, even though `nvm list` shows version 20.17.0 is installed, I am unable to uninstall it via nvm

**Comment by vesper8** [comment]
It seems there was some kind of conflict. Node 20 had already been installed on Windows. Then Herd installed node 20 a second time using nvm. After I uninstalled Node manually from Windows Programs and Features, I was then able to do what I wanted using nvm. But it does seem like Herd does not allow you to remove node versions from the Herd menu.

**Comment by sschlein** [comment]
I am currently rewriting the docs, this is the new part for Node and while these are the macOS docs, they still apply for Windows :)

![CleanShot 2024-09-03 at 16 27 26](https://github.com/user-attachments/assets/d9f51b1c-826b-4d34-bf8d-57093cf7f73f)

**Comment by kurucu** [comment]
Would be great to add this to the UI for Herd.
