### ISSUE TITLE
[Bug]: Unable to render the application on local host

### ISSUE THREAD

**Issue by grsherwin** [beyondcode/herd-community#960]
### Platform

macOS

### Operating system version

14.6.1 (23G93)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

 1.9.1 (Build 31

### Bug description

Installed Herd.  Created a Laravel demo app.  I tried to open it on the local server with the.test extension.  Did not open

### Steps to reproduce

Installed Herd.  Created a Laravel demo app.  I tried to open it on the local server with the.test extension.  Did not open

### Relevant log output

```shell
no output
```

**Comment by grsherwin** [comment]
PHP 8.3

**Comment by mpociot** [comment]
Could you give some more information besides "did not open"?
Which error did you get?
