### ISSUE TITLE
[Bug]: Need https support for localhost

### ISSUE THREAD

**Issue by maverickchangithub** [beyondcode/herd-community#961]
### Platform

Windows

### Operating system version

Windows 10 / 11

### System architecture

Windows

### Herd Version

1.10

### PHP Version

8.3

### Bug description

This could be a valet issue.
Followed valet tutorial to set a default site by adding "default" in the config file.
http worked. 
But, the sites is secured before, if use directory name plus .test , it is a https link.

How would I get it done?

**Comment by sschlein** [comment]
You mean https://localhost ?

**Comment by maverickchangithub** [comment]
```
You mean https://localhost/ ?
```
yes. is it possible? please help.

**Comment by sschlein** [comment]
I don't think it is because this is not a domain and shouldn't be supported for TLS certificates. 

Why would you need that?

**Comment by maverickchangithub** [comment]
It's for local lan sharing, in case other machine need to access the data.
Thanks

**Comment by maverickchangithub** [comment]
sorry for the confusion.
machine A has local IP address 192.168.1.10, its localhost is exposed to the lan network.
other machines visit machine A by IP.
still, no https.
> Herd does not support local LAN sharing
Herd use valet , so , if valet can share local, why cannot Herd?
Thanks for your reply.

**Comment by mpociot** [comment]
@maverickchangithub while LAN sharing is possible by modifying your nginx files manually, Herd does not allow you to create TLS certificates for hostnames (such as `localhost`) but only for actual domain names.
