### ISSUE TITLE
[Bug]: xDebug and other functions on windows

### ISSUE THREAD

**Issue by buby84** [beyondcode/herd-community#962]
### Platform

Windows

### Operating system version

Windows 11

### System architecture

Intel (x86)

### Herd Version

1.10.0

### Bug description

Hello i am pretty new of herd and i just bought the pro version, mostly because it was looking easy to integrate xdebug ,
soo i dont know but my herd interface is complety different from the one showed on the doc page, maybe is because that one is for macos but is ..i am not worried for it..i am worried because many function look like missing and many config setting i dont know where i can found...for example ..where i can enable xdebug ? there is no any tab like suggest on ducmentation.

![image](https://github.com/user-attachments/assets/f71588dc-033c-4545-baa0-bd2922cbc35b)

sorry for the dumb question

**Comment by mpociot** [comment]
@buby84 Did you take a look at our documentation?
Xdebug can be enabled using "herd debug" in your command line, or by using the Xdebug browser extension:

https://herd.laravel.com/docs/windows/1/herd-pro/xdebug
