### ISSUE TITLE
[Bug]: ERR_CONNECTION_REFUSED on all sites for windows

### ISSUE THREAD

**Issue by vilhelmjosander** [beyondcode/herd-community#963]
### Platform

Windows

### Operating system version

Windows 11 23H2 22631.4037

### System architecture

Windows

### Herd Version

1.10.0

### Bug description

All sites added (regardless if I enable https or not) get the ERR_CONNECTION_REFUSED. Same issue in Chrome and Firefox.

![image (1)](https://github.com/user-attachments/assets/4937c6f9-cb76-4d75-b821-608e399226a2)

Nginx status is sporadically not running with the following error:

![image](https://github.com/user-attachments/assets/b0a5d0a0-276b-4932-ab51-4ef6838b0dcc)

However, it does not work when nginx is green and running either.

I have tried the following this far:

1. Stop/Start all services
2. Disable all firewalls
3. Restart Herd
4. Restart computer :)

**Comment by fazlarabbi2** [comment]
I am also facing this issue. How can I solve this issue.

**Comment by mpociot** [comment]
Do you see anything in your nginx log files?
Is there maybe something else running on port 80, or something else blocking nginx from getting started?

**Comment by taylordragoo** [comment]
I was able to resolve this issue by running Herd as an administrator.
