### ISSUE TITLE
[Bug]: Cannot unlink site using php 7.4.33 or 8.0.30

### ISSUE THREAD

**Issue by augusto-dmh** [beyondcode/herd-community#965]
### Platform

Windows

### Operating system version

Windows 10

### System architecture

Intel (x86)

### Herd Version

1.10.0

### Bug description

When i try to unlink a site using the command 'herd unlink appname', a composer errors is showed due to a conflict over composer version. This happens when i try to unlink an application that uses php 8.3 using another version of php (in this case, tested with 7.4.33 and 8.0.30). That is not an expected behavior (at least not by a conventional user, and it is not mentioned in the docs): i would expect the site to be unlinked no matter the version of php i'm currently selected. Also a work collegue has tried to unlink a site using php 7.4.33 activatedm and this application uses 7.4.33 too, but it didn't worked as well: only using the latest version of php solved.

![Screenshot_585](https://github.com/user-attachments/assets/d7843324-655a-4a50-8580-29a5aeb5eed5)
![Screenshot_586](https://github.com/user-attachments/assets/38859b2d-548c-4588-acc6-e103593ba90b)

### Steps to reproduce

- Create a Laravel application

- Try to unlink it using php 7.4.33 or 8.0.30 selected as active.

- Try to unlink it again using latest version of php

**Comment by mpociot** [comment]
This will be fixed in the next release.
