### ISSUE TITLE
[Feature Request]: Swoole Extension

### ISSUE THREAD

**Issue by olliescase** [beyondcode/herd-community#97]
### Feature Description

Compile the swoole extension into the PHP binary

### Is this feature valuable for other users as well and why?

Would be really nice to be able to use this with Laravel Octane (swoole); we use this for all our projects and would consider using herd if this was supported.

**Comment by crazywhalecc** [comment]
If you installed homebrew, you can compile a static php binary with swoole by yourself and replace it.

**Comment by mpociot** [comment]
I'm closing this in favor of #16 
Feel free to add Swoole there/leave a thumbs up if it's already in there
