### ISSUE TITLE
[Bug]: Unable to manually override the older built in Redis driver v5.3.7 with v6

### ISSUE THREAD

**Issue by edward-rw** [beyondcode/herd-community#970]
### Platform

macOS

### Operating system version

macOS Sonoma 14.5 (23F79)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.9.1 (Build 31)

### PHP Version

PHP 8.3.10

### Bug description

We have dependencies on Redis driver v6 as we are using features in Redis that need this driver.

But the built in Redis driver seems to be 5.3.7 and it is not upgradable. When we try to add a v6 `redis.so` file into the `php.ini` it crashes due to Redis driver already being loaded.

This has been discussed and pointed out in this issue #797 but was disregarded, yet marked as "complete".

Apparently, according to the discussion, the redis "extension is compiled into the binary for portability". Unfortunately, this makes Herd unusable for our whole team and we have all had to downgrade to Valet again. Valet seems to use the v6 driver.

Could you please upgrade the driver to v6, or make it configurable?

// Big thanks, from someone that wants to go back to Herd ;)

### Steps to reproduce

Write `phpinfo(); die();` in the `index.php` file and search for 5.3.7 and you can see that it is the redis driver in use.

**Comment by mpociot** [comment]
We now ship v6 of the Redis extension by default 👍

**Comment by edward-rw** [comment]
Sounds great! Thank you! 🙏 
Is this coming with the next release?
@mpociot Currently it is only PHP 8.2 that has the v6 redis driver. PHP 8.3 is still on 5.3.7.

Hoping this will come to PHP 8.3 soon so our team can start using Herd again. ❤️ 🙂

See screendumps:

![Screenshot 2024-09-26 at 09 40 51](https://github.com/user-attachments/assets/b551a63e-5050-4e3e-bbcc-a7b3ba398ed3)
![Screenshot 2024-09-26 at 09 40 23](https://github.com/user-attachments/assets/bf24395d-a34e-45ae-ad23-46433078264e)

**Comment by mpociot** [comment]
@edward-rw you should update to PHP 8.3.11 :) 
<img width="541" alt="image" src="https://github.com/user-attachments/assets/38dfee2f-2c67-416d-812c-6ad8534e4469">

**Comment by edward-rw** [comment]
Hmm, I had upgraded to 8.3.11 in the PHP tab in Herd. But for some reason it was still using 8.3.10.
A simple restart solved it! 🎉 

Thank you! 🙏  Love Herd and can now use it again in our projects. 🙂
