### ISSUE TITLE
[Bug]: Herd re install all php version on restart

### ISSUE THREAD

**Issue by ziarv** [beyondcode/herd-community#975]
### Platform

macOS

### Operating system version

Sonoma 14.6.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.9.1 (Build 31)

### Bug description

when restart mac the herd re-install all the PHP versions again. launch on startup is turned off 

### Steps to reproduce

install the above mentioned Herd version and install all PHP versions then restart Mac and start Herd again

**Comment by sschlein** [comment]
What does that mean, I am afraid I don't get your question. Can you provide any screenshots?

**Comment by ziarv** [comment]
@sschlein When you restart the MacBook, Herd will reinstall all PHP versions and display the initial onboarding setup, similar to what is shown during the first installation

**Comment by sschlein** [comment]
I have attached a screenshot of the new docs that we'll deploy later this week. This should fix that :)

![CleanShot 2024-09-11 at 10 43 58](https://github.com/user-attachments/assets/ce054305-45a2-42ba-aa08-14de9c72f403)

**Comment by Pankaj-Baranwal** [comment]
What was the fix?
I am still facing this issue in Jan 2025
