### ISSUE TITLE
[Bug]: Service "Add Service" modal has state of "Settings" modal when "Settings" was opened before "Add Service"

### ISSUE THREAD

**Issue by justusmoroni** [beyondcode/herd-community#976]
### Platform

macOS

### Operating system version

macOS Sonoma 14.6.1 (23G93)

### System architecture

Intel (x86)

### Herd Version

1.11.0 (Build: 33)

### Bug description

When adding or editing a service in the "Services" tab sometimes an existing service is changed instead of adding a new service.

### Steps to reproduce

1. Click on "Add Service" and create one service. E.g. "Queue".
2. Click on "Settings" on the newly created service "Redis"
![image](https://github.com/user-attachments/assets/9cffa560-fe61-4931-a8d4-ca65379e6132)
![image](https://github.com/user-attachments/assets/7d48660b-3d28-48d9-b8b3-fc28da6d2d8d)
3. Dismiss the "Settings" modal by pressing the escape key. I could not reproduce this behaviour when clicking the "Close" button.
4. Click on "Add Service" again

![image](https://github.com/user-attachments/assets/d036fff7-e303-439d-ad75-12e8dc7960fa)

Instead of adding a new service we are now editing the last service where we clicked "Settings".
Sometimes when saving that i could successfully save the service and it was switched. Sometimes the whole application crashed instead.

When i only change the name saving is successful.
![image](https://github.com/user-attachments/assets/4091f8be-9cda-4c09-bee4-101c32472553)
![image](https://github.com/user-attachments/assets/86c54ead-3d87-469f-bf2c-77e6e3eec1ef)

**Comment by mpociot** [comment]
Thanks for reporting this! Will be fixed in the next release

**Comment by mpociot** [comment]
This is now fixed in Herd 1.11.1
