### ISSUE TITLE
[Bug]: Node tab in setting not detecting nvm, conflicting GREP_OPTIONS

### ISSUE THREAD

**Issue by jamesj2** [beyondcode/herd-community#978]
### Platform

macOS

### Operating system version

macOS Sonoma 14.6.1 (23G93)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.9.1 (Build 31)

### PHP Version

PHP 8.3

### Bug description

My node settings tab has never worked for me. I've tried completely removing and re-installing Herd with no luck.  After removing my ~/.zshrc file it worked.  I tracked it down to a GREP_OPTIONS export I'm using in my zshrc.  This causes nvm to be undetected and always ask you to install NVM and the install button appears to do nothing.

### Steps to reproduce

Add "export GREP_OPTIONS='--color=always'" to ~/.zshrc.

**Comment by mpociot** [comment]
Thanks for reporting this, @jamesj2 
The colors indeed messed up our regular expression when checking for the grep output. This will be fixed in the next update!

**Comment by mpociot** [comment]
This is now fixed in Herd 1.11.1
