### ISSUE TITLE
[Bug]: Log viewer shows "No Sites Found"

### ISSUE THREAD

**Issue by isimmons** [beyondcode/herd-community#980]
### Platform

Windows

### Operating system version

Windows 11 Home (23H2 22631.4169)

### System architecture

Intel (x86)

### Herd Version

1.10.0

### PHP Version

PHP 8.3.11

### Bug description

I logged a simple log message and confirm it is logging to the storage/logs/laravel.log file. 

I expect to open Herd and click "Open log viewer" and see the log there.

Instead I get "No Sites Found"

All sites are showing under the sites tab and serving correctly at the site.test domain.

It has been a while since I opened Herd so I'm not sure when this stopped working. I think I had used it before and it worked but when I opened it yesterday, it updated to the latest version and now it's not working.

### Steps to reproduce

Not sure

### Relevant log output

```shell
NA no logs
```

**Comment by sschlein** [comment]
What's your global PHP version? I know that there was an issue when using logs and PHP 7.4 as global version but I thought I have fixed that with Herd 1.10 🤔

**Comment by isimmons** [comment]
Hi, 8.3 is my global version and the site version.  8.3.11 to be exact.

**Comment by isimmons** [comment]
I had installed 8.4 but never used it. I uninstalled it and now my sites show up. Then I re-installed 8.4 and uninstalled it again, testing each time. 8.4 installation is causing the problem but I have no clue what the problem is. 

Should unused versions even have any effect? Seems like they shouldn't but I don't know.

**Comment by mpociot** [comment]
This will be fixed in the next update
