### ISSUE TITLE
[Bug]: Herd crash when run tests with Dump window activated

### ISSUE THREAD

**Issue by devajmeireles** [beyondcode/herd-community#985]
### Platform

macOS

### Operating system version

macOS Sonoa 14.6.1 (23G93)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.11.0

### PHP Version

PHP 8.3.11 (cli) (built: Sep 10 2024 15:12:42) (NTS)

### Bug description

When running tests, if the Herd Dumps window is accidentally open, we will crash Herd due to the number of items to be displayed, such as database and views stuff. We need a way to prevent monitoring the dumps when we are running tests.

Demo: https://share.cleanshot.com/N4Wb0QrFvjdq0hQP97nK

**Comment by mpociot** [comment]
In the meantime, you could disable the dump interception entirely - or disable only queries and views. 

At which point does it crash? I couldn't see a crash in your demo

**Comment by devajmeireles** [comment]
> In the meantime, you could disable the dump interception entirely - or disable only queries and views.
> 
> At which point does it crash? I couldn't see a crash in your demo

As you can see from the demo, I only ran the tests for a single file. If I ran the entire test suite with the Dump window enabled, Herd would crash. Since sometimes the Dump window is not visible (when you're not using the keep on top window), Herd will crash and close, and you will initially not know why.

**Comment by john-wink** [comment]
@devajmeireles  Thank you... I thought it was due to SPX. 
I deactivated the dumps and now it doesn't crash anymore. 
With dumps it crashed every 2-3 minutes for me

**Comment by mpociot** [comment]
Interesting - I'll investigate this!

**Comment by peterthomson** [comment]
Thanks! The behaviour was that the dump window was 'flashing' (things like queries popping up briefly and then disappearing) as the tests ran for a while before seemingly overloading Herd and crashing it. My hypothesis was that it was related to the new profiler tooling. But it sounds like ya'll have it under control. Cheers!

**Comment by mpociot** [comment]
The new "Watch via CLI" toggle is now available in Herd 1.11.1 (default is false)
