### ISSUE TITLE
[Bug]: Unable to connect Laravel Forge account

### ISSUE THREAD

**Issue by duncanmcclean** [beyondcode/herd-community#987]
### Platform

macOS

### Operating system version

macOS Sonoma 14.6.1 (23G93)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.11.0

### Bug description

When I try to connect my Laravel Forge account, the OAuth flow takes me back to `herd.laravel.com`, it focuses the Herd app, but then nothing happens.

I've tried clearing my local storage/session for the Herd domain but that didn't help.

### Steps to reproduce

1. Go to Herd's settings
2. Go to the "Integrations" tab
3. Click "Connect Service"
4. Click "Laravel Forge"
5. Click "Authorize" on the Forge page
6. It redirects back to `hard.laravel.com` and nothing happens

https://github.com/user-attachments/assets/9620e0d9-23e1-4496-93ff-024023761c1e

**Comment by mpociot** [comment]
Some people already mentioned that they had to restart Herd once in order for the OAuth flow to work.

**Comment by duncanmcclean** [comment]
Thanks - that seems to work for me.
