### ISSUE TITLE
[Bug]: Herd missing from menu bar following update

### ISSUE THREAD

**Issue by TomEasterbrook** [beyondcode/herd-community#989]
### Platform

macOS

### Operating system version

Mac OS 14.6.1 (23G93)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

Version 1.11.0

### Bug description

Since updating to the latest version I have no herd icon in the menu bar so can't access the GUI. CLI works as expected. Not sure where the app log lives but happy to provide as a follow up. Tried a reinstall as per docs, same result. Any help much appreciated.

**Comment by TomEasterbrook** [comment]
Looks like it might be an intermittent problem. It randomly appeared for a few minutes, but now it seems to have disappeared again.

**Comment by sschlein** [comment]
I am pretty sure that the icon is pushed out of your menu bar because you have too many icons there. If that's the case, you can either close some apps and the rearrange Herd more to the right or use a tool like Bartender that can hide all the icons that you don't need: https://www.macbartender.com
