### ISSUE TITLE
[Bug]: php.ini located in bin folder not config

### ISSUE THREAD

**Issue by rspahni** [beyondcode/herd-community#991]
### Platform

Windows

### Operating system version

Windows 11 (22H2 22621.4169)

### System architecture

Intel (x86)

### Herd Version

1.10.0

### Bug description

Unlike described [here](https://herd.laravel.com/docs/1/advanced-usage/php-settings), on my Win11 machine, the php.ini file is located in ...\.config\herd\bin\php83 not ...\.config\herd\config\php\83. The latter folder does exist but is empty. Same for additional PHP versions when I activate them via the Herd GUI.

### Steps to reproduce

When updating PHP settings via the Herd GUI (e.g., memory limit), it's the php.ini in the bin folder that gets updated. Also, when using the context menu item 'Open php.ini directory' in the Herd GUI (PHP tab), Windows Explorer opens the config directory, which is empty. Please note I did not check phpinfo() and what is states in terms of php.ini location, but there is exactly one php.ini file on my machine.

**Comment by sschlein** [comment]
You are looking at the macOS docs, the Windows docs have the correct directory:

https://herd.laravel.com/docs/windows/1/advanced-usage/php-settings

The link from the GUI to the correct directory will be fixed with the 1.11 release :)

**Comment by rspahni** [comment]
Wer lesen kann (inkl. "macOS" vs. "Windows"), ist klar im Vorteil... 🙄 Actually, it was the GUI link that pointed me in the wrong direction to begin with. Thx in advance for fixing it!

**Comment by rspahni** [comment]
> You are looking at the macOS docs, the Windows docs have the correct directory:
> 
> https://herd.laravel.com/docs/windows/1/advanced-usage/php-settings
> 
> The link from the GUI to the correct directory will be fixed with the 1.11 release :)

For the record: The link in 1.11 still points to to the wrong directory (i.e., the separate config directory that is empty).

**Comment by pyerro** [comment]
I am noticing the same error in version 1.12.0

In main Laravel Herd window I go to PHP, right click at 8.3 version and in context menu I click "Open php.ini directory". It opens %USERPROFILE%\.config\herd\config\php\83 which is wrong folder. It should open %USERPROFILE%\.config\herd\bin\php83 as specified in the docs https://herd.laravel.com/docs/windows/1/advanced-usage/php-settings

**Comment by myturbodispatch** [comment]
In 1.14.0 is the same problem

**Comment by sschlein** [comment]
Sorry, fixed it for the next version!
