### ISSUE TITLE
[Bug]: Unknown system error -214427238

### ISSUE THREAD

**Issue by peymanr34** [beyondcode/herd-community#992]
### Platform

Windows

### Operating system version

Windows 10 (22H2 19045.4894)

### System architecture

Windows

### Herd Version

1.10.0

### Bug description

I keep my projects in a separate partition with BitLocker enabled, if I open Herd before I unlock the partition, it causes the following error:

> Uncaught Exception:
Error: Unknown system error -214427238: Unknown system error -214427238, stat 'C:\Users\Peyman\.config\herd\config\valet\Sites\site-name'

![image](https://github.com/user-attachments/assets/7df30c42-66dd-4dd9-ab7a-5baa4039ddf9)

It would be nice if Herd could handle this exception gracefully.

### Steps to reproduce

- Put a project in a partition with BitLocker enabled.
- Add the project to Herd.
- Close Herd.
- Lock the partition.
- Open Herd.

**Comment by mpociot** [comment]
We'll try and improve the error message here 👍 
Regardless, you need to unlock the partition for Herd to work 😅
