### ISSUE TITLE
[Bug]: Sites not accessible (ERR_CONNECTION_REFUSED)

### ISSUE THREAD

**Issue by trontank** [beyondcode/herd-community#995]
### Platform

macOS

### Operating system version

macOS Sonoma 14.6.1 (23G93)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.11.0 (Build: 33)

### PHP Version

PHP 8.2.23

### Bug description

I cannot access any of my sites, all browsers report the sites are not accessible (ERR_CONNECTION_REFUSED). I donot have an idea what's going wrong here.

### Steps to reproduce

1. Install Herad
2. Create news site (Laravel default)
3. Try to open the site in any browser

### Relevant log output

```shell
Nginx logs:

2024/09/16 13:17:03 [emerg] 29634#327003: unknown "herd_sock" variable

FPM-8.2 logs

[16-Sep-2024 13:15:31] NOTICE: [pool herd] 'user' directive is ignored when FPM is not running as root
[16-Sep-2024 13:15:31] NOTICE: [pool herd] 'group' directive is ignored when FPM is not running as root
[16-Sep-2024 13:15:31] NOTICE: fpm is running, pid 26410
[16-Sep-2024 13:15:31] NOTICE: ready to handle connections

DNSMasq logs are empty.
```

**Comment by mpociot** [comment]
Is your `Herd.app` in a subfolder within `/Applications`?
We currently require the application to be in `/Applications` directly, because we need to resolve some config files from there.

**Comment by trontank** [comment]
Hi! Thanks a lot for your reply. I have installed `Herd.app` to an external SSD-Drive and later moved the app to `/Applications` because this solved a problem i had with DBNgin today. Same error, though. Should i completely uninstall Herd and install fresh?

**Comment by mpociot** [comment]
@trontank That's not really necessary.

Does this file exist at this location for you: `/Applications/Herd.app/Contents/Resources/config/pro/njs/detect.js`?

**Comment by trontank** [comment]
Uninstalling as described in the docs and reinstalling `Herd.app` into `Appllcations` did do the trick. Thanks a lot for your help!
