### ISSUE TITLE
[Bug]: defer() not working

### ISSUE THREAD

**Issue by Urthawen** [beyondcode/herd-community#997]
### Platform

Windows

### Operating system version

Windows 11

### System architecture

Intel (x86)

### Herd Version

1.10.0

### PHP Version

8.3

### Bug description

I'm in a fresh laravel 11 project using Laravel Herd and i trying to use the helper `defer() ` with the code below : 

```
Route::get('/defer', function () {
    defer(fn () => sleep(2) );
    echo "Boom !";
});
```

The `defer()` method doesn't work. I still need to wait 2 seconds before "Boom !" is echoed.

I have try to use `fastcgi_finish_request()` and get undefined function error. 
Seems FPM is not available in my current version of PHP provide by Herd.

**Comment by sschlein** [comment]
Hey, FPM is not available on Windows, so there's nothing that we can do about that.

**Comment by mpociot** [comment]
@Urthawen Could you open an issue on the Laravel framework repository instead? This sounds to me like it's an issue in Laravel itself.
As @sschlein mentioned, Herd does not use FPM on Windows, so the `fastcgi_*` methods are not available here.
