### ISSUE TITLE
[Bug]: Dumps not expandable in Dumps tab

### ISSUE THREAD

**Issue by pascalvgemert** [beyondcode/herd-community#999]
### Platform

macOS

### Operating system version

macOs Sonoma 14.0 

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.11.0

### PHP Version

PHP 8.3.9

### Bug description

Dumps are not expandable inside the `Dumps` tab, they are expandable from the `All` tab.

See (arrow is missing):
<img width="345" alt="image" src="https://github.com/user-attachments/assets/cf2b6ad4-8cec-4425-a929-756b2c9c192d">

In the all tab is does work:
<img width="429" alt="image" src="https://github.com/user-attachments/assets/9b7da8f3-3191-4d48-ada8-55d0ca225d00">

### Steps to reproduce

1. Dump an two- or multidimensional array `dump(['items' => [['id' => 1], ['id' => 2]]]);`
2. Assert that you cannot expand (do not see the arrow) the secondary array in the `Dumps` tab
3. Assert that you can expand the dump in the `All` tab

**Comment by mpociot** [comment]
Oh right, seems like this happens as soon as the dumps get removed from the UI.
We'll fix this in the next update!

**Comment by mpociot** [comment]
This is now fixed in Herd 1.11.1
